### PR TITLE
U4-1733 - Added overloads to RedirectToUmbracoPage methods to allow passing of a querystring

### PR DESCRIPTION
**Pull request by AndyButland**
Either as a string or as a name/value collection

### CODE REVIEW

**Comment by Shazwazza** [comment]
The code looks good... just making sure that you of course have tested that this all works ? :)

**Comment by AndyButland** [comment]
I have yes, didn't look straightforward to unit test and couldn't see any existing examples for this type of thing (custom action results), so I haven't done that.  But have manually checked the following and all seems OK:

            return RedirectToCurrentUmbracoPage();
            return RedirectToCurrentUmbracoPage(new NameValueCollection { { "a", "1" }, { "b", "2" } });
            return RedirectToCurrentUmbracoPage("a=1&b=2");
            return RedirectToCurrentUmbracoPage("?a=1&b=2");

            return RedirectToUmbracoPage(1060);
            return RedirectToUmbracoPage(1060, new NameValueCollection { { "a", "1" }, { "b", "2" } });
            return RedirectToUmbracoPage(1060, "a=1&b=2");
            return RedirectToUmbracoPage(1060, "?a=1&b=2");

            return RedirectToUmbracoPage(Umbraco.TypedContent(1060));
            return RedirectToUmbracoPage(Umbraco.TypedContent(1060), new NameValueCollection { { "a", "1" }, { "b", "2" } });
            return RedirectToUmbracoPage(Umbraco.TypedContent(1060), "a=1&b=2");
            return RedirectToUmbracoPage(Umbraco.TypedContent(1060), "?a=1&b=2");

**Comment by Shazwazza** [comment]
Great :)

Yeah, need to get around to getting tests up and running for such things!

**Comment by tomfulton** [comment]
@AndyButland Nice work, I've been in this situation before and this will be nice to have! #h5yr

**Pull request merged**
