### PR TITLE
U4 11393 - Health Check for developer files in the root of the site

### PR DESCRIPTION
**Pull request by PeteDuncanson**
### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have linked this PR to an issue on the tracker at http://issues.umbraco.org/issue/U4-11393

### Description

New health check that looks for a hardcoded list of developer related files in the root of the website. These files "could" leak sensitive data to hackers and they shouldn't be released on a public site. Add the option to delete these files with a warning that you should have a back up of the files.

Only put in EN language look ups I'm afraid.

### CODE REVIEW

**Comment by marcemarc** [comment]
Media.zip is my favourite 'find' in the root of a site... usually it's good to find it as I'm often looking in the context of trying to free up disc space... Worth adding here?

**Comment by PeteDuncanson** [comment]
Good shout Marc, but is that mission critical or insecure? I knew there would be more that we can add in. Feel free to suggest :)

**Comment by dawoe** [comment]
Probably could add the following as wel
gulpfile.js
config.json
bower.json

And I lost track of the times i found backup.zip

**Comment by marcemarc** [comment]
It just got me thinking... :-) depends what's in the media folder as to whether it's a security thing..  it's very common... But perhaps a 'different' health check context to thisOn 31 May 2018 17:54, Pete Duncanson <notifications@github.com> wrote:Good shout Marc, but is that mission critical or insecure? I knew there would be more that we can add in. Feel free to suggest :)

**Comment by skttl** [comment]
How about having a setting in umbracoSettings.config for adding other files to this health check?

Then you could have a small selection of default files and folders to look for (thinking the install folder), and you would be free to add any file/folder yourself?

**Comment by abjerner** [comment]
@skttl Wouldn't `HealthChecks.config` be better? `umbracoSettings.config` already has a confusing amount of settings for newcomers

**Comment by abjerner** [comment]
@PeteDuncanson @marcemarc If we already know the files in the root folder that ship with Umbraco by default, wouldn't it be better/safer to have a whitelist rather than a blacklist? With the list being configurable as suggested by @skttl

**Comment by abjerner** [comment]
Also, if we extend the check a bit, it could also check for missing files. Eg. trigger an error if `/media/Web.config` is missing.

Could be called **File Integrity Check** ;)

**Comment by JeffreyPerplex** [comment]
Hi @PeteDuncanson, that looks like a really nice Health Check. But is it maybe an option to do whitelisting instead of blacklisting? Which files should be allowed in the root of your website folder?

- Default.aspx
- Favicon.ico
- *.png 
- Manifest.json
- *.svg
- robots.txt
- Web.config

I think there's no need for any other files, or is there?

**Comment by skttl** [comment]
@abjerner yes, HealthChecks.config is even better, forgot about that one :)

**Comment by PeteDuncanson** [comment]
Thanks for the feedback guys, keep it coming. I'd already pondered users wanting to customise or add to this check so there is this other issue for adding the ability to have some custom health check data so you could add to it as you wanted (http://issues.umbraco.org/issue/U4-11394). Ideally we would release with some baked in defaults and these could be updated each release as we find new ones.

As for blacklist vs whitelist, I can see both sides. They both allow you to opt-in to what you want stripped out, one always has your back as long as you've told it up front who to let in or not (blacklisting) and the other can cause some quirky behaviour if you don't tell it what is allowed (whitelisting) and then delete some perfectly valid files (like your google verification file for instance?). Whitelisting also has the problem that you have to "know" where and how to whitelist these files and makes it a little too dangerous to just delete everything (or someone else to do so thinking its "best" to do so). 

If we went white listed then I would probably remove the delete button and just have a warning instead. Might be super nice to have the option to add files to a black/white list there and then but...thats a much larger UI fix that would be needed and now this is no longer a nice quick helpful health check but a major development! Lets keep it simple for now.

**Comment by nul800sebastiaan** [comment]
I have had a little look at a few hundred Cloud sites and while I can't share the exact results for privacy reasons, I also would suggest going for a whitelist approach instead and I don't think we should have a delete button in either case, chances are that automated build systems will put the files that are being deleted back in the root anyway.
Let's just say that the files I've seen ending up in the root are.. scary(!), so a whitelist is very much more safe IMO.

Some other suggestions of files to whitelist:

- 404.aspx 
- 404.html 
- 500.aspx 
- 500.html 
- bingsiteauth.xml 
- browserconfig.xml 
- favicon.ico / favicon*.* (?)
- google*.html (Google verification files)
- humans.txt
- imagegen.ashx 
- loaderio-*.txt
- robots.txt 

Agreed on keeping it simple for now.
Could you please make the changes to whitelist and show a warning @PeteDuncanson ? That would be great!

**Comment by nul800sebastiaan** [comment]
Hi @PeteDuncanson - it seems like you got caught up in other things after opening this one. If you or someone else can make the requested changes then we can move forward with this one again. Until that time I'll close this so that this PR doesn't just linger forever. 

I've applied the "idea" label to indicate that we still think this would be a valuable addition but we need someone to actively work on it. 

Feel free to re-open once you get a chance to work in this again! Thanks everyone for pitching in on the discussion as well! 👍

**Comment by PeteDuncanson** [comment]
I've actually done this one however I got in a rabbit hole with trying to get the config working in a similar way to how the existing config for Health Checks is done. Its horrid in short and a complete pain to do. My original code just did some simple XPath but all the other stuff is using some crazy Config magic that I simply can't get my head around.

Happy to push up what I've got with the XPath stuff working if that would be ok or a WIP with my Config attempt in there if someone smarter than me wants to take a look over it?

**Comment by nul800sebastiaan** [comment]
@PeteDuncanson Yeah sure if you can push up what you have we should be able to combine it all!

**Pull request closed without merging**
