### PR TITLE
Feature/6024 application event handler default weight

### PR DESCRIPTION
**Pull request by bowserm**
This is a pull request for issue #6024.

Previously, all of the ApplicationEventHandlers in the `Umbraco.Web` project were being assigned a default weight of 100 instead of -100. This was because the `.FullName` of the `umbraco.dll` assembly did not start with `Umbraco.`.

This pull request includes:
1. Fixing the logic of the `GetObjectWeight` method in the `ApplicationEventsResolver` to recognize the `umbraco.dll` assembly as a core assembly.
1. Adding the `[Weight(-100)]` attribute to all `ApplicationEventHandler` classes in the `Umbraco.Web` project.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @bowserm,

Thanks so much for the work here and congrats on your first PR to this repo 🎆 ! If we're happy it all works as advertised and with the way the code is written and structured, we'll go ahead and merge. If we have any questions, we'll be sure to ask. Once we merge, you'll get a contributor badge on your Our.Umbraco.Com profile. :)

Emma, [Pull Request team](https://umbraco.com/blog/introducing-the-new-pr-team/)

**Comment by bowserm** [comment]
Thanks! I hope all goes well. Let me know if you find a reason to reject it
so I have a chance to revise it.

I think I already have a contributor badge, but two also sounds appealing
:) Keep them coming!

**Comment by Shazwazza** [comment]
I didn't see this PR initially so created a diff one https://github.com/umbraco/Umbraco-CMS/pull/6331

This PR makes quite a few changes which are unecessary like adding the explicit Weight attribute, but with the fix this value will be implicity. I've also added a unit test to my PR and solved in a slightly different way.

**Comment by warrenbuckley** [comment]
Thanks for your PR @bowserm its appreciated 👍  
As @Shazwazza mentioned he fixed this in a different way in this PR which has been merged in
https://github.com/umbraco/Umbraco-CMS/pull/6331

**Pull request closed without merging**
