### PR TITLE
Fixes U4 6510 - Norwegian labels, dictionary and language

### PR DESCRIPTION
**Pull request by engern**
I'm not sure how localization works in Umbraco, but it seems to be a comparing of the first 2 letters of the culture name and the filname, because nothing is translated when you switch to Norwegian
language. When changing the filename from no.xml to nb.xml, translations are applied

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Wow, I don't think this ever worked correctly! Thanks!

**Comment by engern** [comment]
I guess this merge failed because I applied the renaming before the changes in #935 ?

**Comment by nul800sebastiaan** [comment]
It didn't fail! :-)

**Comment by engern** [comment]
Ok, the pull request just didn't close like they usually does, and it says "This branch has conflicts that must be resolved" I also downloaded 7.4 BETA today and it seems the language file is still called "no.xml"

**Comment by nul800sebastiaan** [comment]
Weird, looks like I messed up then! Will investigate after the holidays, thanks for letting me know!

**Comment by nul800sebastiaan** [comment]
Alright, fixed this all up now and 7.3.5+ will have the new translations and the nb.xml file by default, thanks again!

**Comment by engern** [comment]
Perfect :+1:  Any chance #932 could be considered for 7.3.5?

**Pull request closed without merging**
