### PR TITLE
v8: Add umb file icon component

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
This PR add a `umb-file-icon` component to add a file icon, with the option to specify icon (default `icon-document`), extension and optionally a text.

Test the file icon is shown correct in these parts of backoffice UI.

- Media picker (show for file types like `.pdf`, `.docx`, `.txt`, etc.
- Media section listview grid layout
- Image cropper, e.g. on media item itself

image

image

image

image

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @bjarnef ,

Many thanks for the PR. I think my eyes are fooling me here, can you elaborate how to test this?

Poornima

**Comment by bjarnef** [comment]
Hi @poornimanayar

As mentioned in the test nodes that the file icon is shown correct in these areas.

- Media picker + media picker dialog (show for file types like .pdf, .docx, .txt, etc.
- Media section listview grid layout
- Image cropper, e.g. on media item itself.

Or you could try adding a custom property editor or dashboard using this component: `umb-file-icon extension="pdf" text="Top Secret" />`

**Comment by poornimanayar** [comment]
Hey @bjarnef ,

Makes total sense now. I see what the work is all about. I have given this a quick spin and everything seems to be working fine, haven't noted any issues.

Poornima

**Comment by nul800sebastiaan** [comment]
Works nicely! I added `aria-hidden="true"` for screen readers but other than that all good! Thanks very much @bjarnef! 🥇

**Pull request merged**
