### PR TITLE
Add predefined ranges in datepicker

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8600

### Description
This PR add predefined dateranged inspired from http://daterangepicker.com/ and https://github.com/flatpickr/flatpickr/issues/1274

https://user-images.githubusercontent.com/2919859/147687596-2521c576-77fc-44cf-956f-9e39ac244418.mp4

It would be cool if we could make this work and since Umbraco Forms currently ships with another datepicker instead of using the core datepicker.

Furthermore it can be useful some custom stuff like a dashboard, maybe in commerce or another custom section.

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
@bjarnef Any reason this is still in Draft? Looks very cool to me! 💪

**Comment by bjarnef** [comment]
@nul800sebastiaan yes, I recall it sometimes didn't show a value in time period after selecting a period, which is seen in the video when "Today" is selected.

I think it was something about `fp.setDate()` not always was called or didn't affect a change in model.

**Comment by bjarnef** [comment]
@nul800sebastiaan I have updated the logic to use vanilla JS and doesn't depends on jQuery as Flatpickr itself doesn't depends on jQuery.

When selecting af date in calendar it trigger the `onValueUpdate`:

image

However when I just click `Today` label in also trigger the `onValueUpdate`, but with do date and the label/button isn't highlighted (active class).

image

**Comment by bjarnef** [comment]
I had another look at this.
However for some ranges, e.g. selecting "This month" it set date using an array of `Date` objects.

image

However when in the trigger e.g. the `onValueUpdate` event it only seem to contain first date.

**Comment by OwainWilliams** [comment]
Hi @bjarnef - I was looking at this PR and everything is looking really good. I notice it's still a Work in Progress PR - are you still looking in to it or do you need help from other community members? Would be great to get this merged in.

**Comment by bjarnef** [comment]
@OwainWilliams yes, I think a few things still doesn't work as expected such as when `minDate` or `maxDate` is set. Furthermore if `rangesOnly` is set to `false` and `rangesAllowCustom` set to `true`, the predefined ranges are not aligned well, because Flatpickr already has calculated the container width.

**Comment by nul800sebastiaan** [comment]
Hey @bjarnef - I see this got stuck in draft for a while now. 

I've just asked for some guidance on this at HQ, with the upcoming new backoffice in mind. We are currently not looking for new backoffice UI features as they will all need to be reimplemented in v13. I will close this one and encourage you to try this one again for the new backoffice. It might be a bit too difficult to work on this right now but we hope to be making it easier for contribution over the next few weeks, so maybe hold off on that for now. 🙂

**Pull request closed without merging**
