### PR TITLE
V8: Better support blueprints in multisite solutions (issue #5425)

### PR DESCRIPTION
**Pull request by AndyButland**
This PR is a solution for [issue #5425](https://github.com/umbraco/Umbraco-CMS/issues/5425), to better support blueprints (content templates) in multi-site solutions.

I've implemented the following:

- Added a new dialog available, from the content templates, created in the "Settings" section to allow them to be associated with user groups.
   - This involved a new table - `umbracoUserGroup2ContentTemplate` - so there's a migration to create this.
- When an editor sees the list of content templates to pick from when creating content, they only see those that match their user group(s).
    - They also see any content templates that aren't assigned to any user groups (so if the feature isn't used, the behaviour is as before).
- When an editor creates a content template from a content node, if the user is not an administrator and does not have the root content node set as their start node, the user groups they are in are automatically set on the content template.
    - The idea here is that if the editor manages just one section of the site, perhaps a single territory, they will only see content templates they, or others in that same section, have made.  They won't see those created in other sections, nor will editors of those other sections see their's.

image

As well as general review, please note this amend in case it's important and otherwise missed...

There was a comment on `IAction` stating _"If an IAction returns false for both ShowInNotifier and CanBePermissionAssigned then the IAction should not exist"_.  And some validation in `ActionCollectionBuilder` to ensure this is the case.  

To implement this feature I've created an action that doesn't adhere to this rule (it lives in "Settings" so content node permissions don't apply, and having a fine-grained permission for this when the user already has access to the "Settings" area doesn't seem useful; and there's no pressing need to be able to subscribe to notifications).

As such I've removed this comment and validation as part of this PR.  Obviously if I've missed something important as to why this check was in place, please let me know.

### CODE REVIEW

**Comment by marcemarc** [comment]
@AndyButland thanks! - in my multi-lingual example, I have user groups for territory, which define start nodes (Italian Territory) and additional user groups which define roles via the action permissions (Editors) an editor is in a combination of Territory Group + Role Group - would I be reading correctly this PR to think that an editor creating a blueprint, would gift it to others in that same generic 'Editors' user group - eg across territories? - I could remove the shared Editors group, and duplicate the settings in each Territory group... (and would do to take advantage of this) but just thinking out loud... since multiple editors can have multiple groups for different parts of a tree I can't think of a better way, I guess at 'blue print' creation the list of groups it will be shared with could be presented, and editor could modify... but appreciate it may just be a niche situation and simple is best!

**Comment by AndyButland** [comment]
@marcemarc - yes, you're right, that would happen with what I've implemented.  Maybe better is I look to have it automatically set permissions only for user groups the editor is in, that don't have a root start node?  That way in your example, the content template would be available to "Italian Territory" users but not "Editors".  And would still work in situations where there's only one user group for the territory.

Will have a think/see if can implement like this later.

As you say, a prompt to the editor could be added, but would be better I think if we could avoid that.  If it just works as expected that would be simpler for editors to deal with of course.

**Comment by AndyButland** [comment]
Updated to that effect now.

**Comment by marcemarc** [comment]
@AndyButland I may not be helping here! - but would it be 'if the current user is in a User Group that **has** a 'Start Node' eg Italian Territory - and the blueprint is created from a content item inside that restriction - only share the blueprint with that UserGroup -  if the User isn't in a UserGroup with a Start Node then share with all UserGroups eg existing behaviour...

Essentially the assumption is if you are in a UserGroup that is restricted in the content tree, your blue prints shouldn't be available 'by default' outside of this restriction to that tree. They can be be manually escalated out by an Admin via the settings.

So for my possibly Niche scenario - Italian Editor creates blueprint - only other Italian editors can view the blue print... but if a non restricted user is a super editor not tied down by territory start node, if they create a blueprint, it's made available to all user groups... but worried I'm over complicating things for my instance!

With the mapping to UserGroup in your PR setup **could** a CreatingBluePrint / MappingBluePrintToUserGroups event fire? - so developers can just implement their own crazy UserGroup mapping logic for their complicated scenarios?

regards

Marc

**Comment by AndyButland** [comment]
@marcemarc - helping for sure.  I think though what you've described is what I've implemented - i.e. a restricted tree user, when creating blueprints only makes them available to the restricted tree user groups they are in; whereas a non-restricted user creating a blueprint will create one available to all.

The event might well be a good idea, but it does seem to me that rather than your case being niche is actually the most sensible option, so think I'll leave that for now - at least until the PR looks to be getting picked up by HQ and they consider then it seems then a useful extension point.

**Comment by marcemarc** [comment]
@AndyButland I was thinking of the event, as I think then it's easier to accept, as all sites may have different logic to how the usergroups are setup - eg I kind of want if an Italian editor creates a blueprint from content in the Italian tree - even though that user is also in the Spanish Editor group, I don't want the blueprint to be available for somebody who is only a Spanish editor, that's hard to describe as 'default behaviour' - the default behaviour you have seems the most sensible for most scenarios!

**Comment by AndyButland** [comment]
I see the point @marcemarc - so with the above commit have set this up to be extensible.  Rather than using an event, I've created an interface `ICreatedBluePrintAssignmentToUserGroupBehaviour` and implemented the logic we've discussed above in `DefaultCreatedBluePrintAssignmentToUserGroupBehaviour` (the implementation that's registered by default).

This could then be replaced in an implementation with 

```
composition.RegisterUnique<ICreatedBluePrintAssignmentToUserGroupBehaviour, 
  MyFancyCreatedBluePrintAssignmentToUserGroupBehaviour>();
```

**Comment by marcemarc** [comment]
Think that covers all bases now!

**Pull request closed without merging**
