### PR TITLE
V8: Add keyboard support for navigating search results

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

The global search dialog can be opened with Ctrl+Space, which is awesome! Unfortunately you can't navigate your way through the search results using the up and down arrow keys. 

This PR adds that feature to the global search:

search-keyboard-support

#### Testing this PR

Simple! Search for something and use the up/down keys to navigate through the results. Then open a result by hitting enter. If things doesn't blow up and you end the right place, the PR works 😎

### CODE REVIEW

**Comment by emmaburstow** [comment]
Kenn! Great fix. Will look and let you know if we need you. 

Em

ps. How are you? Long time no see! Are you over cg19 yet? I'm not. I'm very sad I'm not still there.

**Comment by kjac** [comment]
Me too! Contemplating building a time machine to get back. Incidentally that would also make PR work much faster!

**Comment by emmaburstow** [comment]
Sounds like a win-win situation to me.

**Comment by kjac** [comment]
Woohoo! I love this change. I'm never using the mouse again!

**Comment by nul800sebastiaan** [comment]
That's awesome! Thanks very much!

**Pull request merged**
