### PR TITLE
U4-5942 - change width of grid cell tools

### PR DESCRIPTION
**Pull request by bjarnef**
Change width of grid cell tools, so it doesn't overlap the input
fields/texteditors.

### CODE REVIEW

**Comment by Shazwazza** [comment]
I've pulled this in but after testing there is a problem. If you try to delete a cell, the 'Are you sure' message no longer fits which is why it was 150px in the first place.

**Comment by bjarnef** [comment]
Ahh okay.. didn't think of that. However with 3 columns in the Grid, e.g. in Fanoe starterkit, 150px cover almost half of a column. So maybe change it to 150px when delete button is clicked? Otherwise 50px as default.

**Comment by bjarnef** [comment]
But maybe isn't 150px enough for localized text. E.g. in Danish the text would be "Er du sikker?" .. but if the width is changed after click on delete button,  I don't think it is a problem.

**Comment by Shazwazza** [comment]
yup just fixing that up

**Comment by perploug** [comment]
This might be okay as a temp fix, but I think the root of the issue is the wonky positioning these icons was done with in the first place, so I think the 150px width came from fitting that delete confirm, but the overlap is a problem - working on a float version that doenst overlap or restrict width

**Comment by Shazwazza** [comment]
After debugging this for a bit i think i also saw some wonky stuff, the fix i put in does fix it and it also fixes the issue that you couldn't cancel the alert box when trying to delete a cell/row.

**Comment by bjarnef** [comment]
It is a similar issue in Umbraco Forms, when you click the delete button and can't cancel it without refreshing page or reloading the view.

**Comment by bjarnef** [comment]
@Shazwazza it seems that your fix wasn't merged into 7.2.2? .. maybe there have been a merging conflict?

**Pull request merged**
