### PR TITLE
Replace remaining HttpContext calls with UmbracoContext [v8hackaton, reopened]

### PR DESCRIPTION
**Pull request by ed-parry**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [ ] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description
This is to complete a task from the V8 Hackathon, with a couple of details [here](https://trello.com/c/IlsoDFOr/7-replace-httpcontextcurrentitemspageid-with-umbracocontext). Ultimately it's just a quick replace of `HttpContext.Current` calls with `UmbracoContext.Current`.

### CODE REVIEW

**Comment by clausjensen** [comment]
@ed-parry 
Thanks for the PR (and the effort!) 😄 
As you can see we've marked these PRs with a hackathon tag in the title so we can clearly identify them. We will be reviewing these remaining PRs in the upcoming sprint - they do however require some time set aside from the Core team. In order to get this, they have to be pulled in as a part of our sprint planning so we can allocate the resources for this task.

Changes look fairly simple but we just need to make sure everything checks out before pulling it all in 😄

**Comment by clausjensen** [comment]
@ed-parry That would be great - I didn't look into what the conflicts are .. it could just be due to some line endings that were fixed up recently ... lets hope so 😄

**Comment by ed-parry** [comment]
No more conflicts @clausjensen, but Github thinks I changed all the files! I believe @zpqrtbnk had a look into this over the weekend, but let me know if I need to do anything to resolve it from here.

**Comment by clausjensen** [comment]
Yeah I kinda had an idea that would prolly be the case 😄 
It's all good from here .. we'll normalize the line endings when we get to reviewing!

**Comment by zpqrtbnk** [comment]
Note to reviewer: make sure there is no reference to `["pageid"]` anywhere in our code, so that we are absolutely sure we don't depend on the http context stuff anymore.

**Comment by zpqrtbnk** [comment]
So... few comments:
* I have tried to fix the merge issues but... not sure what happened it's *really* messy - any chance you could kill that PR, start from very latest state of `temp8` branch and reproduce the changes of your very first commit?
* The PR removes *some* references to pageID but there seem to be more left. You probably want to run a "find all" for `["pageId"]` on the solution to be sure. And then, it *may* be tricky to remove it--see for example the comments on `UmbracoContext.PageId`.

That being said, even if not *all* references to pageID are not removed, and the PR is not immediately merged, it's good to have it and it can be further improved during next hackatons, so cool if the first part (clear PR) can be done.

Thanks!!

**Comment by ed-parry** [comment]
Sounds good, thanks @zpqrtbnk! I'll re-do the PR this week and review the changes. I think the task originally seemed aimed at removing the HttpContext references, so the find-all was looking for that before the PR went up. I'll go over for the `pageId` references and update :)

**Comment by nul800sebastiaan** [comment]
@ed-parry I'll close this one for now as it's a bit of mess right now! 😓 Sorry about that! 😂

**Pull request closed without merging**
