### PR TITLE
Add missing localization of dialogs

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

Some texts scattered across the content and media sections aren't localized (probably elsewhere too, but these two sections are where we need it the most). 

To test this PR, validate the translation issues below are fixed.

If you want me to split this PR into several smaller ones just let me know 😄 

#### Content section: Copy dialog

The "Choose where to copy..." headline and the "[node] was copied to..." success message aren't localized:

copy-localized-before

#### Content section: Move dialog

The "[node] was moved to..." success message isn't localized: 

image

#### Content section: Notifications dialog

The dialog uses localization keys from the "notify" localization area, which only exists in the en-US localization file. It should be using localization keys from the "notifications" localization area, which is translated into all languages.

The dialog also uses a different format for the headline (`<h5>`), where most other dialogs use a regular text with the affected node in bold.

As-is:

image

As it should be:

image

#### Content section: Rollback dialog

Several texts aren't localized:

image

#### Media section: Move dialog

The "[node] was moved to..." success message isn't localized (same as for the content section). 

image

🎄 9/24 🎄

### CODE REVIEW

**Comment by emmaburstow** [comment]
Thanks for this one Kenn. 9/24! 🎁

**Comment by kjac** [comment]
Merge conflict resolved.

**Comment by nul800sebastiaan** [comment]
Oh this is going to be some v8-merge-fun! ;-) Thanks!

**Comment by kjac** [comment]
I don't mind redoing it for V8 manually if it's  merge hassle. Just let me know 😊

**Comment by nul800sebastiaan** [comment]
@kjac 	All merged up, was surprisingly easy! Thanks for the offer though! 👍

**Comment by kjac** [comment]
Whoo 🎉

**Pull request merged**
