### PR TITLE
[WIP] Create Umbraco/Bellissima Package (Take Two)

### PR DESCRIPTION
**Pull request by warrenbuckley**
This PR is to rework & reopen the work that @leekelleher done from the previous years community teams day
https://github.com/umbraco/Umbraco-CMS/pull/14975

### CODE REVIEW

**Comment by warrenbuckley** [comment]
OK PR is now in a state that this can be worked on and finish up what Lee started

**Comment by ronaldbarendse** [comment]
Great start on this Warren! 💪🏻 

If this targets v15, we should probably take the opportunity to make the `umbraco-package-rcl` the default (remove the one that uses the build targets and rename the RCL one to `umbraco-package`), see PR: https://github.com/umbraco/Umbraco-CMS/pull/15258.

**Comment by warrenbuckley** [comment]
@ronaldbarendse should I target `v15/dev` as opposed to `contrib` then?

**Comment by warrenbuckley** [comment]
Going to recreate this PR again and cherry pick Lee's commit so we do it from **v15/dev**
_Even after merging v15/dev into this branch seems to be a bit too much going on_

**Comment by warrenbuckley** [comment]
Closing PR as reworked PR targeting `V15/dev` with @leekelleher original commit/work from his fork

**Pull request closed without merging**
