### PR TITLE
#3022   media uploader in rte doesn't select uploaded image

### PR DESCRIPTION
**Pull request by KimHolzmann**
### Prerequisites

- [ ] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is:
- [ ] I have added steps to test this contribution in the description below

### CODE REVIEW

**Comment by KimHolzmann** [comment]
@nul800sebastiaan yes if I  don't add the target values it's not returning the image to the rte.

**Comment by KimHolzmann** [comment]
🙌

**Comment by nul800sebastiaan** [comment]
Cool, this works perfectly! Thank you, that's certainly a nice little timesaver, great job! 👍

**Comment by nul800sebastiaan** [comment]
Hi there @KimHolzmann,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing :pray:

If you haven't heard already we have had a record breaking amount of PR's in both the CMS and the Documentation repository. You can read all about the numbers in the [Umbraco Hacktoberfest Aftermath blog post](https://umbraco.com/blog/the-2018-hacktoberfest-aftermath/).

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://goo.gl/forms/smjQwEMDM5cUnz6x1) :point_left: Please follow this link to fill out and submit the form, **before November 21st 2018**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before December, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Comment by jannikanker** [comment]
@KimHolzmann @nul800sebastiaan I'm still seeing this happen in 7.12.4 :-s Also the browse dialog seems to pop up three times, seemingly unmotivated (although that might be an entirely different issue).

Any idea what is happening?

**Comment by nul800sebastiaan** [comment]
It was fixed in 7.13, see related issue https://github.com/umbraco/Umbraco-CMS/issues/3022

**Comment by jannikanker** [comment]
@nul800sebastiaan Argh, yes, I see - thanks and sorry for my blindness! :-)

**Pull request merged**
