### PR TITLE
Corrected spelling and grammar in the Getting Started tool tips for v7.

### PR DESCRIPTION
**Pull request by Mundairson**
### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have linked this PR to an issue on the tracker at http://issues.umbraco.org/issue/U4-11159

### Description
Corrected the tool tips for Getting Started. Fixed the spelling in a couple of places, added missings words and amended some grammar and punctuation.

### CODE REVIEW

**Comment by Shazwazza** [comment]
This PR has merge conflicts now that https://github.com/umbraco/Umbraco-CMS/pull/2625 has been merged so this branch will need to be merged and re-pushed.

**Comment by Mundairson** [comment]
As I said on the other two PRs, I'm sorry about all this. It's my first time submitting PRs so I'm trying to learn without breaking anything! I've merged and resolved the conflicts.

**Comment by nul800sebastiaan** [comment]
Thanks @Mundairson - all looks good!

Do you have an account on Our Umbraco? I would love to give you a contributor badge but I can't seem to find you! :)

**Comment by Mundairson** [comment]
Hi @nul800sebastiaan thanks, I'm not sure if I have an account haha! Let me check.

**Pull request merged**
