### PR TITLE
Support custom SVG icon in umb-child-selector component

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10340

### Description
When using custom SVG icons these were not show in `<umb-child-selector>` component.
Furthermore this PR also replace the search filter markup with `<umb-search-filter>` component.

image

image

The compass icon is a custom font icon from my [Material Design Icon Pack](https://our.umbraco.com/packages/backoffice-extensions/material-design-icon-pack/), the coffee icon a custom SVG icon and the rest Umbraco core icons.

image

---
_This item has been added to our backlog [AB#12146](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12146)_

### CODE REVIEW

**Comment by bjarnef** [comment]
Okay, I noticed a minor issue in list of datatypes / property editors, because items doesn't have the `umb-card-grid-item` class, but previous just used `.umb-card-grid i` in less.

image

Furthermore I noticed if using a custom SVG icon in a property editor, e.g. `icon-coffee-cup` this wasn't shown either.

**Comment by bjarnef** [comment]
It now looks like this.

image

**Comment by bjarnef** [comment]
I also noticed it is a similar issue if using property editor as macro parameter editor: https://our.umbraco.com/documentation/extending/macro-parameter-editors/

image

**Comment by bjarnef** [comment]
A custom SVG icon was missing here as well - fixed in https://github.com/umbraco/Umbraco-CMS/pull/10344/commits/a54b0b1b0fb4a0d4e059eeb6185902fa94393737

image

**Comment by bjarnef** [comment]
@nul800sebastiaan is it too late to fix this in 8.14.0 release?

**Comment by nul800sebastiaan** [comment]
@bjarnef Awesome! But yes, about 2 hours too late for the 8.14 release, not to worry, we'll get it into a patch release instead 👍 Thanks for the help, you're a star!

**Comment by bjarnef** [comment]
Oh no! 😱 ... no espresso for me then ☕
Hopefully in the next patch releases then 🩹

**Review by nathanwoulfe — APPROVED** [review]
Beautiful, thank you @bjarnef

It still bugs me that we pass the icon string into the umbIcon directive twice (once as the icon attribute, and again in the class). Probably not worth worrying about now, given it would be a pretty big change, but I'm sure we could be using the class attribute only for additional styling (color, size etc), then adding the icon attribute into the class string when we're rendering. Ideally the new UI will drop support for legacy icons, so the umbIcon component would be up for a rebuild anyway

**Pull request merged**
