### PR TITLE
Ensure it is possible to replace media via drag and drop

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9342

### Description
This PR make some changes to this previous PR https://github.com/umbraco/Umbraco-CMS/pull/8390 where it seems the `onFilesSelected` function in `umbPropertyFileUpload` component wasn't triggered after in drop event via drag and drop, but triggered via the change event, when clicking the button.

However with latest changes in `v8/contrib` I did need to change the save button in media back to `type="submit"` to save the media, which was changed in this PR https://github.com/umbraco/Umbraco-CMS/pull/9019

### CODE REVIEW

**Comment by bjarnef** [comment]
@nathanwoulfe maybe you want to try this out? 😁 😎

**Comment by nathanwoulfe** [comment]
@bjarnef might just be me, but I can no longer save media (on v8/contrib, so not related to these changes, but means I can't test this)

**Comment by bjarnef** [comment]
@nathanwoulfe yes, I had same issue after this PR was merged https://github.com/umbraco/Umbraco-CMS/pull/9019

I had to revert that change back to submit button locally.

**Comment by nathanwoulfe** [comment]
@bjarnef #9019 makes the button consistent with content (enter shouldn't submit) which is a positive change, so we really need to make this work with type="button". Noticing too the hotkeys aren't working, so might be evidence of a larger issue in the media edit controller?

**Comment by nathanwoulfe** [comment]
Found it, I think - when type="button", it needs an action property, which will be `action="save()"`

**Comment by bjarnef** [comment]
@nathanwoulfe regarding semantic and accessbility I do think it makes sense with a submit button for the primary action and it act as a page submit.

**Comment by nathanwoulfe** [comment]
@bjarnef I'm split - I like the consistency with content, and submit-on-enter was causing issues, but I agree that submit is semantically correct. It should definitely be consistent, even if that means changes in content to make it work correctly.

Would be good to get @nielslyngsoe thoughts on this, given the changes might grow outside the scope of this PR.

**Comment by nathanwoulfe** [comment]
@bjarnef I think the best way forward for now is to keep the button as type=button, to avoid undoing the change from #9019, and add the action attribute. We can then circle back around and consider the save buttons on content/media/members etc and determine the best way forward for all types.

Also needs to be fixed because the current v8/contrib branch will have non-saveable media, which ain't good. Tagging @kjac here too, since this relates to his changes.

**Comment by bjarnef** [comment]
@nathanwoulfe @nul800sebastiaan I would be great to have this, so it is easy to replace and image via drag and drop. Currently we have to use the click event which trigger the regular file upload.
With the latest changed it seems the button element is of `type="submit"` again :)

**Comment by nul800sebastiaan** [comment]
@bjarnef Sorry, where is `button type="submit"` please?

**Comment by bjarnef** [comment]
@nul800sebastiaan it the latest changes, which is now conflicting with this PR.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/media/edit.html#L63

`action="save()"` added in https://github.com/umbraco/Umbraco-CMS/pull/9376/commits/fb059bfe6a8a3e11b96faffd6769f5fbddf727bc shouldn't be necessary now with a submit button :)

**Comment by bjarnef** [comment]
@nul800sebastiaan it seems @nielslyngsoe meanwhile has submitted another PR with an alternative fix for this in https://github.com/umbraco/Umbraco-CMS/pull/9933

**Pull request closed without merging**
