### PR TITLE
Fixing language install during umbraco installation

### LINKED ISSUE #13852: Database install failing with custom default languages
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

If you configure some languages in the `appsettings.json` which should be installed by default, when installing Umbraco with a SQL Server database, the installation fails.

### Specifics

Before installing Umbraco, you can configure some languages which should be installed by default.
Documentation: https://docs.umbraco.com/umbraco-cms/v/10.latest-lts/reference/configuration/installdefaultdatasettings
For example, add the following configuration to the `appsettings.json`.
```json
"Umbraco": {
  "CMS": {
    "InstallDefaultData": {
      "Languages": {
        "InstallData": "Values",
        "Values": [
          "nl-BE",
          "en-US",
          "fr-BE"
        ]
      }
    }
  }
}
```

When you install Umbraco with a SQL Server database the installation fails:
Umbraco install failed

During install, the configured languages are inserted in the database without a specific id. The id should be generated and incremented automatically when inserting the language in the database.
https://github.com/umbraco/Umbraco-CMS/blob/daff9884a3d0ff0a90d0cde23b7565919647d5fe/src/Umbraco.Infrastructure/Migrations/Install/DatabaseDataCreator.cs#L1767-L1773

However, it looks like `IDENTITY_INSERT` is set to `ON` before the languages are inserted. Because of this, a value for the primary column `id` is required.
https://github.com/umbraco/Umbraco-CMS/blob/daff9884a3d0ff0a90d0cde23b7565919647d5fe/src/Umbraco.Infrastructure/Migrations/Install/DatabaseSchemaCreator.cs#L509-L513

For SQLite databases, this is not a problem because there is no such functionality.

### Steps to reproduce

- Configure some languages in the `appsettings.json` which should be installed by default. See above for an example.
- Install Umbraco with a SQL Server database

### Expected result / actual result

The database installation should be successful and the configured languages should be installed.

### PR DESCRIPTION
**Pull request by CyberReiter**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #13852 

### Description
Fixing the installation process by adding ids to the languagdtos starting by id=1

### How to test
You can test it by using the description of the bug provided in  #13852

### CODE REVIEW

**Comment by JasonElkin** [comment]
Hey @CyberReiter, thanks for looking at this. 

When testing the changes I got an error unless I set the autoIncrement parameter to false (which makes sense, and is the same for the default en-US culture, which gets inserted with an explicit ID).

I've added an extra commit. Are you able to test and confirm that this works as expected for you?

**Comment by CyberReiter** [comment]
Hey @JasonElkin 
Thanks for taking a look at this!
I am not sure how this was actually working on my machine without setting autoincrement to false :sweat_smile: must have been running into some cache.. :thinking:

Anyways I can confirm that the change is working as expected!

Sorry for the inconvenience there!

**Comment by JasonElkin** [comment]
@CyberReiter, that's no problem at all!

Thanks again for contributing a fix for this!

**Comment by nul800sebastiaan** [comment]
Cherry picked for 10.5 in 6b309dc3bebb5e6be287237bb6b3f79aeb306e2a

**Pull request merged**
