### PR TITLE
Rewrite exportdocumenttype.aspx to Angular [v8hackaton]

### PR DESCRIPTION
**Pull request by kows**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [ ] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description

https://trello.com/c/qymO2Wbx/34-rewrite-webforms-to-angular-exportdocumenttypeaspx

Rewrite ExportDocumentType.aspx to Angular.
This is a working version but by no means final.
Starting the PR for further discussion, my Core knowledge is starters level :)

Things that still are open:
- Any extra security measures needed on the export?
- Not sure what UI is wanted in the dialog (now Export just shows "Cancel" & "Export" buttons)
- File download possible through AJAX + API result? Now I'm opening the link in new tab for browser behavior.
- Moved translations?
- Any further remarks on stuff I might be overlooking

### CODE REVIEW

**Comment by Shazwazza** [comment]
For

**Comment by clausjensen** [comment]
@kows 
Thanks for the PR (and the effort!) 😄 
As you can see we've marked these PRs with a hackathon tag in the title so we can clearly identify them. We will be reviewing these remaining PRs in the upcoming sprint - they do however require some time set aside from the Core team. In order to get this, they have to be pulled in as a part of our sprint planning so we can allocate the resources for this task.

I can see that you already received some feedback but as there's still a few questions left unanswered. Hopefully we can give you some answers to the rest of your questions when this is looked at in the sprint!

**Comment by skttl** [comment]
This would be a good enhancement for v7 too. Can it be merged in there too?

**Comment by nul800sebastiaan** [comment]
@skttl  Of course, all of the things being created for v8 would be really nice to backport to v7. 😉

I understand from a technical point of view why this would be good for v7, but can you make a use-case for who exactly it will have benefits on v7? Is there a good reason to spend time on backporting it except for the code being nicer?

**Comment by skttl** [comment]
All the old aspx dialogs are sometimes incredibly slow. If it's not directly mergable, then I understand the hesitation :) then it's a PR candidate for me.

**Comment by skttl** [comment]
I don't use it that much so "getting fed up", is probably an overstatement. There is probably not many people using it very often. 

I'll do the investigation of compatibility and eventually the PR if you want :)

**Comment by nul800sebastiaan** [comment]
@skttl I've been trying to make you see that it is not a priority for v7. First off, on Cloud this dialog is not even available so I suspect you very rarely see it. There is no benefit to changing this dialog in v7 and an additional PR will cost us extra time for no real benefit, delaying other things that you'd also like us to work on. 😄

**Comment by skttl** [comment]
Okay, I get it :)

Just thinking with a lifespan of 7 for at least a year more (my guess), it would be nice to sort out minor annoyances.

**Comment by nul800sebastiaan** [comment]
Thanks @kows ! I have merged with the latest v8 and updated the download method to use the Umbraco built-in one. Now it's complete! 👍 

So next hackathon this Friday, are you going for the import dialog? 😁

Ps. Look at that shiny new Contrib badge on your Our profile! https://our.umbraco.com/member/11521 🏅

**Pull request merged**
