### PR TITLE
Adjust z-index of notifications

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

Fixes https://github.com/umbraco/Umbraco-CMS/issues/11701

### Description
This PR adjust the changes made in https://github.com/umbraco/Umbraco-CMS/pull/10518

- Store the z-index in a variable
- Decrease the z-index (I don't see the reason to use z-index 999999 unless we needed to overwrite some third party overlays etc.). We can't guard us against e.g. package developer doing stuff with an even higher z-index e.g. 1000000 or using `!important`, but we know the z-indexes used in core CSS. Not sure there is a specific use-case where notifications should be above tour overlay?
- Only show `<ul>` when any notifications are appended to list.

If saving a content node and open a block list item, the notification is since https://github.com/umbraco/Umbraco-CMS/pull/10518 above block overlay, but the notification can't be closed.
It seems to because notifications exists inside `mainwrapper` in DOM, while overlays are outside this.

I noticed there is this static view https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Web.UI.Client/src/index.html (not sure what it used for though), but here `<umb-notifications>` component is not placed inside `mainwrapper`. I don't recall if is originally was or has been moved later.

**Before**

https://user-images.githubusercontent.com/2919859/144763993-51f786e3-695b-4591-8a0c-90fae67f108a.mp4

**After**

https://user-images.githubusercontent.com/2919859/144763904-a25a56e8-7277-4247-8fa4-6bda1a1a3574.mp4

### CODE REVIEW

**Comment by bjarnef** [comment]
One thing I also noticed, but can be fixed in another PR, it the low contract between close button and notification background, e.g. in "update available"notification.

**Comment by bjarnef** [comment]
@nathanwoulfe maybe you want to review this? I think it is pretty annoying we can't close those notifications when overlays are open 😅

**Review by nathanwoulfe — APPROVED** [review]
Hey @bjarnef this works nicely - checked with a few different overlays, notification is dismissible when the overlay is open 👍

**Comment by bjarnef** [comment]
@nathanwoulfe @nul800sebastiaan it could be useful to fix this in v8 as well. I think it is still an issue in latest 8.18-RC2 release.

**Pull request merged**
