### PR TITLE
V8: Disable Nested Content add button when max items is reached (regression)

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

I found a small regression issue in the recent rewrite of Nested Content: The "add" button isn't disabled when the maximum allowed number of items is reached.

With this PR the "add" button goes dimmed (disabled) when you're no longer allowed to add anymore items:

image

### CODE REVIEW

**Comment by emmaburstow** [comment]
👌 I really like this one

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by PezCo** [comment]
While on this may i suggest adding a check for single item mode too? vm.singleMode is available possibly on line 39 to hide the whole footer?

**Comment by nathanwoulfe** [comment]
@kjac this appears to be fixed on latest v8/contrib - given that, I'm hitting the bit red button.
image

**Pull request closed without merging**
