### PR TITLE
U4-10839: Backoffice password field 'eye' icon overlaps with password manager icons

### PR DESCRIPTION
**Pull request by ed-parry**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description
Initial work to fix [U4-10839](http://issues.umbraco.org/issue/U4-10839). Positioned and toggles okay, but a couple of points I'm not 100% sure on:

 - Localisation - I've added in the text for `en` and `en-us`, but not for other languages. Is this okay?
 - The show/hide text is currently toggled between two `<span>`'s, which handles the image change as well. I feel a better solution would be for the change to happen on the Angular side, but that's not my strong area. Is the current implementation suitable, or should I revisit and move towards Angular?

Current state:
capture

### CODE REVIEW

**Comment by abjerner** [comment]
@ed-parry Awesome. Thanks for the PR. And 👍 for included screenshot. I will try to give your code a spin over the weekend ;)

Localisation is fine as long as you have included translations for the default language. We can look at other languages once this PR has been merged (as in people can make a PR with the translation for their language - I can help with the one for Danish) .

I'll make sure to look into how to the toggle feature works, and give suggestions on how to improve it if necessary ;)

Anders, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by ed-parry** [comment]
Fantastic, thanks, @abjerner! And good spot on the accessibility, I've added in those two attributes on the `a` tag now.

**Comment by abjerner** [comment]
Btw - if you wish to add it to your PR, the Danish translation for **Show password** is **Vis adgangskode**, and **Hide password** is **Skjul adgangskode**. Otherwise I can create a new PR for it once this PR is merged ;)

**Comment by ed-parry** [comment]
Ah, awesome! I may as well add it in here for a slightly more complete solution :) I'd love to contribute a full Welsh translation for Umbraco one day (being based in Cardiff), but there are so many strings it takes forever!

**Comment by abjerner** [comment]
I imagine doing a translation from scratch might take a while.

But if you're looking into doing something like this, splitting it into multiple PRs is totally fine. Might be a bit easier to comprehend as well.

**Comment by nul800sebastiaan** [comment]
That is awesome @ed-parry and it works very well. Good catch on the accessibility too @abjerner !

Merging! 🎉

**Pull request merged**
