### PR TITLE
Bugfixes for MNTP / EntityController

### LINKED ISSUE #11631: Newtonsoft.Json.JsonSerializationException with Macro Multiple Content Picker Parameter in Umbraco 9.1.0-rc
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.1.0-rc

### Bug summary

Our macros use Multiple Content Picker (Umbraco.MultiNodeTreePicker) to select a number of paths to include in the macro to other pages on the website. This works fine in Umbraco 8 and Umbraco 9.0 and 9.0.1
After upgrading my development version to 9.1, although the links are OK on the face of it, when viewed on the website, when I try to access them in the CMS to edit them or change them etc. when the macro is loaded we get a Newtonsoft.Json.JsonSerializationException and the links are not displayed in the cms. The links cannot be edited. I cannot re-add the links - which would be a tedious task, as these are on every page - if we had to do that for Umbraco 9.1

I also tried creating a completely new macro with just the Multiple Content Picker as a parameter, but after adding it to the page, on every attempt to add a link, the same error happened and I was not able to add any links.

Image 1: Showing the property used in the Macro - Multi Node Tree Picker
cms-settings-showing-multi-node-tree-picker

Image 2: Showing displayed list of links in Umbraco 9.01
cms-9 0 1-links-displaying-ok-no-error

Image 3:  Showing the error displayed when going in to edit a macro in 9.1 rc
cms-error

Image 4: Showing that no links are displayed after the error above
cms-9 1-rc-links-not-displaying

I hope that this is looked and and the error corrected before the release of 9.1 later this coming week.

### Specifics

Example of the error when accessing a Macro in a content page in the CMS:

Error converting value "1113" to type 'Umbraco.Cms.Core.Udi'. Path 'udis[0]'.

Newtonsoft.Json.JsonSerializationException, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed: Error converting value "1113" to type 'Umbraco.Cms.Core.Udi'. Path 'udis[0]'.

stacktrace

at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Umbraco.Cms.Web.BackOffice.ModelBinders.FromJsonPathAttribute.JsonPathBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinder.BindModelAsync(ModelBindingContext bindingContext)
   at Microsoft.AspNetCore.Mvc.ModelBinding.ParameterBinder.BindModelAsync(ActionContext actionContext, IModelBinder modelBinder, IValueProvider valueProvider, ParameterDescriptor parameter, ModelMetadata metadata, Object value, Object container)
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerBinderDelegateProvider.<>c__DisplayClass0_0.<<CreateBinderDelegate>g__Bind|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

### Steps to reproduce

1: Create a Macro
2: Add Parameter - Umbraco.MultiNodeTreePicker (Multiple Content Picker)
3: Allow the macro to be included in a rich text area or grid
4: Include the macro in a rich text area and try to add a link using the above parameter. You get the error shown below and no link added to the list
cms-9 1-rc-test-using-multiple-content-picker

### Expected result / actual result

The ability to add or edit links in the multiple content picker list:
cms-9 0 1-links-displaying-ok-no-error

---
_This item has been added to our backlog [AB#15130](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15130)_

### LINKED ISSUE #11647: MTNP throws Newtonsoft.Json.JsonSerializationException when selecting node
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.0.1

### Bug summary

I started noticed these Newtonsoft.Json.JsonSerializationException exceptions when selecting nodes from MTNP.
I don't recall it originally was an issue when I started the project on v9.0.0, but it seems these are showing up in v9.0.1 (not sure if it could be related to Umbraco Forms or Deploy as these has also been patch updates on Umbraco Cloud).

https://user-images.githubusercontent.com/2919859/142163354-614d0448-d753-4d90-a3be-372c2d531d1c.mp4

It may be related to this issue https://github.com/umbraco/Umbraco-CMS/issues/11448 where I also from time to time get these exception when fetching previous selected content in MNTP.

### Specifics

_No response_

### Steps to reproduce

Configurate a MNTP on v9.0.1 and select a node.
A Newtonsoft.Json.JsonSerializationException exception is thrown.

### Expected result / actual result

_No response_

---
_This item has been added to our backlog [AB#15132](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15132)_

### PR DESCRIPTION
**Pull request by p-m-j**
Closes #11631 & #11448.

Probably also closes #11647

If you follow manual reproducing steps from  #11631

e.g. 

1. Create a partial view macro with MNTP property
1. Create doctype with grid
1. Create page with macro in grid -- makes request GetUrlsByIds(int[])

--

If you also add a regular MNTP to the doc type - makes request GetUrlsByIds(Udi[])

Populate all the pickers with content, then you have covered testing for both issues at onces.

---

image

### CODE REVIEW

**Comment by bjarnef** [comment]
@p-m-j I wonder if the issues I was facing with MNTP is in core as I didn't experienced these errors with MNTP in initial v9.0.0 release. I searched for changed in v9.0.1, but I couldn't find specifically something regarding MNTP and JSON changes.
However `Umbraco.Deploy.Cloud` and `Umbraco.Deploy.Forms` have been patch updated to v9.0.1. When I locally revert these to v9.0.0 much of it this started working again.

I wonder if these have any specific changes or could change/overwrite some JSON configuration?

**Comment by p-m-j** [comment]
I'm not 100% certain this closes #11647 but #11448 was definitely a problem in core with ParameterSwapControllerActionSelectorAttribute.cs.

If you look at the property data in the database for that picker are the references of mixed type e.g. some guids som udis? if not it's probably solved by this PR.

**Review by bergmania — APPROVED** [review]
Looks good and works as expected 💪

**Comment by bjarnef** [comment]
Will this be fixed in a patch of v9.0.x as well? Or do we need to upgrade to v9.1.x? Currently it is not possible to upgrade to v9.1 via Umbraco Cloud portal, so I guess we need to do this manually.

What I think it as bit strange is that for the specific project I am working on I didn't had issues with MNTP in v8 or after migrated to v9.0.0, but after the project was patch updated. I couldn't see anything specific regarding this in v9.0.1 .. but besides that `Umbraco.Deploy.Cloud` and `Umbraco.Deploy.Forms` have been patch updated to v9.0.1
Unfortunately these repositories are not public, so I can't check if there might be changes which could affect the JSON serialization / deserialization?

Locally I get some JSON exceptions as mentioned in https://github.com/umbraco/Umbraco-CMS/issues/11647
The strange thing if I revert `Umbraco.Deploy.Cloud` and `Umbraco.Deploy.Forms` to v9.0.0 it seems MNTP stuff starts working again.
@bergmania @p-m-j could you check if there was made any changes made in `Umbraco.Deploy.Cloud` or `Umbraco.Deploy.Forms` which could collide with the MNTP or the JSON serialization / deserialization? It may only be and issue on Cloud as I guess these packages are not used on non-Cloud projects.

**Comment by p-m-j** [comment]
Existing v8 sites wouldn't have issues with GetUrlsByUdi's as it has never and will never exist there, instead a call for GetUrlById was made for each entry in the MNTP.

This method would have been introduced in 8.18 but now is replaced by GetUrlsByIds along with a bugfix for ParameterSwap attribute.

These fixes are going into 9.1.2

I don't see how Cloud/Forms would impact modelbinding in CMS, imagine the restart is just clearing the cached request body in ParameterSwap attrbiute.

**Comment by bjarnef** [comment]
@p-m-j I originally started the project on v8.15.1 and then migrated to v9.0.0, but I don't recall these issues with MNTP after migrating.

**Comment by p-m-j** [comment]
Which issue there are two here.

The introduction of GetUrlsByUdi was introduced 9.1 https://github.com/umbraco/Umbraco-CMS/pull/11207 and fixed in 9.1.2
The ParamaterSwap caching issue has been around since before 9.0.0-rc001

**Comment by bjarnef** [comment]
@p-m-j okay, I will upgrade of the the project when v9.1.2 is out. However many existing projects on v9.0.0 or v.9.0.1 won't get this fixes automatically and requires manual action to get these bug fixes.

Not sure why I didn't noticed any of these JSON exceptions when working on the project for a while on v9.0.0 though.

**Comment by p-m-j** [comment]
It's not obvious unless you have both pickers for both int and udi mntp on same page.

Steps to reproduce in 9.0.0

1. Create a doc type with an MNTP, create a content with it and populate the MNTP with a single entry.
image

2. Edit and resend the request swapping the udi for the int id.
image

3. Submit - note 500 response
image

What's happening here is that the action constraint says yup I have a valid udi array here you can use that action method, then modelbinding takes place and it says nope that's an int[] not a udi[]

**Comment by p-m-j** [comment]
If you have multipl udi pickers, the contraint says yup can use that action method I request has array of udi's and modelbinding agrees.

second one also works but the model binder and the action constraint were looking at 100% different strings.

**Comment by bjarnef** [comment]
In this specific project it shouldn't be an issue with int id I guess, since it only store udi. The MNTP datatype instances are mainly multi picker and one or two pickers on a document type or a used on a single property in en block element.

**Pull request merged**
