### PR TITLE
V8: Always show content and media search results first

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

_Please note that this PR builds on top of #5307, which should be tested and merged before this one._

Right now it seems that document types are listed as the very first thing when presenting search results:

image

Seems to me that content and media should be listed as the first two groups, so this PR makes it possible to decide explicitly how to sort the search result groups:

image

I have only enforced a specific sort order for content and media, the rest will show in the order they're discovered by Umbraco. If need be, all search result groups can be specifically sorted.

#### Testing this PR

Search for something. If content comes first and then media, the PR works 😄

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @kjac 

I like this! Thanks for the work. If we need you, we'll holler.

Em

**Comment by poornimanayar** [comment]
👍 @kjac!

**Comment by poornimanayar** [comment]
Works well @kjac !

**Comment by poornimanayar** [comment]
Over to @nul800sebastiaan for a closer look at code :-)

**Comment by nul800sebastiaan** [comment]
Yep yep, this is a really nice fix, thanks for that! 👌👍

**Pull request merged**
