### PR TITLE
U4-9544 Added database schema validation health check and language file updates.

### PR DESCRIPTION
**Pull request by OptimisticCoder**
Added DatabaseSchemaValidationHealthCheck into Data Integrity group.

It calls HealthCheckContext.ApplicationContext.DatabaseContext .ValidateDatabaseSchema() to get the validation results to see if the database is valid against the current version of Umbraco.

Success, or the number of errors is shown in the back office, and details are logged.
Updated some of the language xml files with 3 messages the health check needs.

NOTE: The health check returns 48 missing constraint errors on a fresh install, and I think it's because they've been removed at some point, but the index attribute has been left on the DTOs. (So you might want to hold on merging)

[http://issues.umbraco.org/issue/U4-9544](http://issues.umbraco.org/issue/U4-9544)

### CODE REVIEW

**Comment by dawoe** [comment]
Hi @OptimisticCoder 

Thanks for this PR. We will try to review this in max 14 days. Probably sooner.

Dave (CPR Team)

**Comment by OptimisticCoder** [comment]
@nul800sebastiaan you're right, I thought if there is no translation it shows just the alias in square brackets. i'll undo the googled translations asap. thanks for the feedback.

**Comment by nul800sebastiaan** [comment]
Thanks mate! If there's an English one, then that will be used as the fallback! 👍 

Make sure to sync up with the main repo first before you add changes, [fetch from upstream](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/docs/CONTRIBUTING_DETAILED.md#keeping-your-umbraco-fork-in-sync-with-the-main-repository) merge `dev-v7` into your branch and then you can add your corrections and push them up so that this PR updates.

**Comment by nul800sebastiaan** [comment]
Wonderful! This is now good to go, thanks very much @OptimisticCoder !

**Pull request merged**
