### PR TITLE
No more TypedContentAtRoot

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
Just a minor fix in the comments mentioning `TypedContentAtRoot`, which no longer exists.

### CODE REVIEW

**Comment by abjerner** [comment]
@bjarnef thanks 👍 

As `ContentAtRoot` is a specific method, wouldn't it make sense to add it as a reference? Eg. `<see cref="UmbracoHelper.ContentAtRoot"/>`? Then it will also result in a warning should be method be deleted in the future.

**Comment by bjarnef** [comment]
@abjerner not sure. Which class should it reference to since it exists in three different classes:
https://github.com/umbraco/Umbraco-CMS/search?q=ContentAtRoot&unscoped_q=ContentAtRoot

**Comment by abjerner** [comment]
@bjarnef I thought about that as well, but I think ´UmbracoHelper` will be the most likely one to use.

But perhaps the remarks could be something like this?
```
This can be useful in order to return all nodes in an entire site by a type when combined with <see cref="UmbracoHelper.ContentAtRoot"/> or similar.
```

**Comment by nul800sebastiaan** [comment]
Updated as per Anders' suggestion. Thanks @bjarnef and @abjerner! 👍

**Pull request merged**
