### PR TITLE
v8: Updated search component to get translated placeholder "Search.." and "Clear" text

### PR DESCRIPTION
**Pull request by Adolfi**
### Prerequisites
Link to issue: https://github.com/umbraco/Umbraco-CMS/issues/7121

### Description
- Updated search component to get translated placeholder "Search.." and "Clear" text.

### Steps to test:
1. Login to backoffice and select user language "Swedish".
2. Reload page for all Umbraco translations to kick in.
3. Click the search icon in top right corner. Placeholder should now say "Skriv för att söka..." and Clear text should now say "Rensa".

I added en.xml, en_us.xml and sv.xml translation for @general_clear, since these are the languages I know. Other languages will need to be updated with Clear translation over time, but since it fallback to english and the component is hardcoded english today, this should not be blocked by missing translations.

I've included some sceenshots of the end result. The logged in user is Swedish.
after_search
after_clear

Cheers.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @Adolfi,

Thanks for the work here. We'll take a look and let you know if we need any changes.

Emma

**Comment by kjac** [comment]
@Adolfi lovely change 👍 would you mind resolving the merge conflict so I can review your change properly?

**Comment by Adolfi** [comment]
@kjac I merged v8/dev in and resolved the conflicts. Happy if you could take a look at it.
Cheers!

**Comment by Adolfi** [comment]
@kjac Ah, I see. I was not aware that the localize directive could translate placeholer. I searched the project for other places where a placeholder was translated and it was done this way I did (can remember now where I found it.)

But absolutely, I will update my PR using your recommended approach. 
And add the danish translation. ;)

Stay tuned. :)

**Comment by Adolfi** [comment]
Crap. I accidentally closed this PR. The "Close and comment" button should really have a alert varning. :)

**Comment by Adolfi** [comment]
@kjac All done! Please have a look now if you like it. :)

Screen Shot 2019-12-13 at 09 34 36

**Comment by kjac** [comment]
@Adolfi good job! The code looks great, I'll give it a spin tonight 👍

**Comment by Adolfi** [comment]
@kjac thanks!!!

**Comment by Adolfi** [comment]
Thanks! :D

**Comment by kjac** [comment]
@Adolfi I'm sorry but I'm going to have to ask you to resolve another set of language file merge conflicts 😞 

Please note that I have changed the base branch from `v8/dev` to `v8/contrib` for this PR. This means you'll have to pull `v8/contrib` and merge it into your PR branch to resolve the conflicts.

**Comment by Adolfi** [comment]
@kjac I've merged v8/contrib in to this branch and resolved the conflicts.

**Comment by kjac** [comment]
Thank you @Adolfi - it's finally merged now 😄

**Comment by Adolfi** [comment]
Thank you @kjac! And happy holidays!

**Comment by kjac** [comment]
@Adolfi and to you as well 🎄

**Comment by Adolfi** [comment]
Out of curiosity, what is the purpose behind v8/contrib branch? Just something temporary or is this the branch one should use from now on when doing PR:s? (In that case we need to update the Contribute documentation)

**Comment by kjac** [comment]
@Adolfi I believe HQ will bring some docs to the table soon 😄 and the default contributor branch will probably be changed to `v8/contrib` eventually.

**Pull request merged**
