### PR TITLE
PR for U4-5875

### PR DESCRIPTION
**Pull request by Alain-es**

### CODE REVIEW

**Comment by Shazwazza** [comment]
Having a look through this now. The first thing to note is that these validation inputs also need to be handled on the server side first. This is how the fileupload property editor will currently display an error if it is empty (of course that happens after a POST which isn't ideal).

I'm working on this today so will merge in this PR and tweak a few things including server side checks for this in a few of the property editors.

**Comment by Shazwazza** [comment]
It's also worth noting that the 'Property has errors' message currently cannot be modified in server side validators. I'm pretty sure this used to display the error message of the first validator found within the property but for some reason that is no longer the case.

I'll create a different issue for that.

**Comment by Alain-es** [comment]
Great! If there is anything I can help with, please let me know.

**Comment by Shazwazza** [comment]
I've manually merged in your changed and tweaked quite a bit, but it's all working quite nicely now. You can see the changes in rev: a4f7c49f50392d3f30ee97edeb4b821bf9acb261

I've changed the new directive to be called: valPropertyValidator

This is a very flexible validator for property editors and also allows you to change the message that is displayed at the property level on the client side. I've also updated the umbProperty directive to expose an API which now has a setPropertyError method. This API can be exposed to other directives by using ^umbProperty in the require parameter.

The color picker, tag editor and upload field now all use this directive to validate if it's required or not on the client side. You'll not the usage of $setViewValue to force the revalidation, this is required because validators are only triggered by input change events and since we are not using input fields (I've changed to a hidden field), this manual revalidation is needed.

**Comment by Alain-es** [comment]
Awesome! Many thanks.

**Pull request closed without merging**
