### PR TITLE
v8: Update ModelsBuilder dashboard

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
I have updated the ModelsBuilder dashboard to use `vm` and also `umb-box` component + `umb-load-indicator` so it is a bit more consistent with other dashboards.

image

### CODE REVIEW

**Comment by zpqrtbnk** [comment]
nice!

but, note to all: DO NOT MERGE! these two files come from the ModelsBuilder project via NuGet, so we should do the changes in the ModelsBuilder project. will look into it, should be quick

**Comment by bjarnef** [comment]
@zpqrtbnk great. Btw is there a reason the view is a `.htm` file and it can't be a `.html` file? :)

**Comment by zpqrtbnk** [comment]
not at all, will update too ;-)

**Comment by zpqrtbnk** [comment]
updated, into ModelsBuilder repo (see https://github.com/zpqrtbnk/Zbu.ModelsBuilder/commit/0ef989dd93576775376941a07074581c532c4e1b) so... closing this, but many many thanks (basically just copied your changes)

**Comment by bjarnef** [comment]
Thanks @zpqrtbnk :)

**Pull request closed without merging**
