### PR TITLE
U4-6961 Prevent from deleting default used datatypes (e.g. Label)

### PR DESCRIPTION
**Pull request by Adolfi**
Added the DefaultLabelDataTypeIdas a non-deletable datatype.

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @Adolfi ,

Hope you are well! Many thanks for this PR. We are trying to focus on some of the PRs that has been in the queue for long and landed up on this. I am going to test this today and let you know of the outcome. I shall keep you posted :-)

Regards,
Poornima, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by poornimanayar** [comment]
@nul800sebastiaan I have tested this and I can confirm that the Label datatype can no longer be deleted. Are there any more of such default datatypes which should not be deleted as it would be a good idea to get it all covered.

**Comment by Adolfi** [comment]
So what is the status on this?

**Comment by nul800sebastiaan** [comment]
Great @Adolfi! Thank you very much.

And who would've guessed that you, of all people, didn't have a contributor badge yet? Well.. here you go, congrats! 🏅 https://our.umbraco.com/member/124117

**Comment by Adolfi** [comment]
ahhh thank you @nul800sebastiaan and @poornimanayar! Have a great weekend!! :)

**Pull request merged**
