### PR TITLE
Remedy for U4-11073: Always show the upload dropzone in media pickers

### PR DESCRIPTION
**Pull request by kjac**
### Original issue
See [U4-11073](http://issues.umbraco.org/issue/U4-11073).

### Description
Currently when using a media picker, the upload dropzone is explicitly hidden when a folder is not empty. To upload a file directly from the media picker dialog, you have to use the ill-placed upload button next to the search field. 

as-is

This isn't the most consistent editorial experience. And per U4-11073 it also leaves the users with a bit of an editorial challenge: The only way to upload an image straight from the clipboard is by having a visible (and active) upload dropzone.

With this PR I'm proposing we keep the upload dropzone visible in the media picker dialog at all times except when searching. The dropzone is shrunk to its small size in non-empty folders. At the same time the upload button is removed entirely, since the dropzone doubles as an upload button.

to-be

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @kjac ,

Many thanks for the PR. It looks like a good improvement and something that the content editors will really welcome. We shall review your PR and let you know of the outcome within next 14 days.

Regards,
Poornima, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by nul800sebastiaan** [comment]
Thanks again @kjac - I'm waiting for Mads to come back from holidays to give some UX feedback, I think it might be a bit intrusive to always show that huge dropzone if you're just trying to pick items.

So this will be open for a few more weeks, you know how it goes with Danish holidays! :-)

**Comment by kjac** [comment]
It's not thaaaat huge 😁 but I see your point. It could probably be shrinked some. Definitively also open for alternative solutions, I'd just like to have the same upload experience across the board.

**Comment by abjerner** [comment]
I think I agree a bit with @nul800sebastiaan - always showing the dropzone might take up too much place and make it a bit intrusive. Perhaps it should only be there for empty folders? Or just be smaller when the folder has items.

**Comment by kjac** [comment]
@nul800sebastiaan sure I'll have a look (sorry for missing the reply, vacation got the better of me). 

Keep in mind though that with these changes, we won't exactly remedy the original issue. It calls for being able to paste images from the clipboard directly to the media library when one is in the process of creating content. With the changes that won't be possible.

**Comment by nul800sebastiaan** [comment]
@kjac No worries! 

Yep, that seems like a bit of a larger project, but this will be an improvement at least! 👍

**Comment by kjac** [comment]
mediapickerupload

@nul800sebastiaan how's that?

**Comment by kjac** [comment]
@nul800sebastiaan I've created a new PR (#2873) as a replacement, since it was a lot easier to just perform the changes from scratch.

I'm closing this now 😄

**Pull request closed without merging**
