### PR TITLE
Sort the children of a parent node after either deleting or moving a child node

### LINKED ISSUE #17273: Moving item to bin doesn't update its siblings sort order
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.1, 14.3.0, 15 RC

### Bug summary

When new document nodes are created, they are always added as the last child. But in the case when you delete an item with `sortOrder` 0, and add a new one, it will be added as the first item. It seems like this is caused by not recalculating the `sortOrder` of the siblings when the first item is deleted. This means that the new node comes with `sortOrder = 0`, which results in taking the position as the first item.

### Specifics

_No response_

### Steps to reproduce

- Use a simple content type and create the following tree structure in the Content section:
```
- Home
  - Child 1
  - Child 2
  - Child 3
```

- Delete "Child 1"
- Add "Child 4"

---
You can also use the content service and verify that the `sortOrder` property of each child doesn't reflect the correct value:
```c#
var parentId = Home.Id;
IEnumerable<IContent> children = ContentService.GetPagedChildren(parentId, 0, int.MaxValue, out _);
```

### Extected:
- "Child 4" to be added as the last item, so the tree looks like this:
```
- Home
  - Child 2
  - Child 3
  - Child 4
```
and the child nodes to have an updated `sortOrder` after deleting "Child 1".

### Actual
- "Child 4" is added as the first item, so the tree looks like:
```
- Home
  - Child 4
  - Child 2
  - Child 3
```

### PR DESCRIPTION
**Pull request by manutdkid77**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

This fixes #17273

### Description
* When a new document `node A` is created under a parent node, it is assigned a SortOrder value of 0.
* Now if you created another document `node B` under the parenr node, it is assigned a SortOrder value of 1.
* Now delete `node A`
* Create a new `node C`, here the [SortOrderExists](https://github.com/umbraco/Umbraco-CMS/blob/e4dbf4ce9ff9ca70ed7c82c0c735a4d576aad692/src/Umbraco.Infrastructure/Persistence/Repositories/Implement/ContentRepositoryBase.cs#L1018) looks to find any item with sortOrder as 0.
* But the `SortOrderExists` can't find such an item with SortOrder as 0, so it returns false, and this results in setting the [SortOrder as 0](https://github.com/umbraco/Umbraco-CMS/blob/e4dbf4ce9ff9ca70ed7c82c0c735a4d576aad692/src/Umbraco.Infrastructure/Persistence/Repositories/Implement/DocumentRepository.cs#L920)
* My solution is to recalculate the Sort after deletion or move operation of a document node.

### CODE REVIEW

**Comment by emmagarland** [comment]
@manutdkid77  thanks a lot for your PR to fix the issue #17273

One of us Core Collabs team will review it soon 🙌

**Comment by nul800sebastiaan** [comment]
Hi there @manutdkid77! Thanks again and sorry for the delay, we'll get to it!

Just a hint: as you may know, this PR qualifies for [Umbraco's Hacktoberfest](https://umbraco.com/blog/join-us-for-umbraco-hacktoberfest-2024/) participation for which you can [earn rewards](https://cultiv.social/@sebastiaan/113311358180849090).
If you were to make 1 more contribution in the next few days, would be great to see your contributions qualify! You can do it.. 😉

**Comment by manutdkid77** [comment]
Thank you @nul800sebastiaan , I'll look to contribute another one 🙂

**Comment by georgebid** [comment]
Hey, @manutdkid77 thanks again for your PR! This has now been tested and works as expected - therefore I have merged this in 😄

**Comment by nul800sebastiaan** [comment]
Hey there @manutdkid77! Thanks for the contribution and I'm sorry to have to do this, but I have reverted (b00c84a36abc6fb685decc1d7e4bbf1b064a3053) this merge. The solution is (almost) never to do a sort operation. Sorting can be a heavy operation and it is entirely possible that you'll accidentally end up sorting (and re-sorting and re-sorting) hundreds, thousands, or more nodes in the database which can lead to a huge performance bottleneck.

You had the cause of the issue narrowed down pretty closely but you should have checked what was actually happening in the database. Node B actually has a perfectly fine `sortOrder` of 0 but the query includes the `nodeObjectType`, which in SQLite apparently is case-sensitive.

As you can see, this query works: 

image

However, the actual query that is being sent in uses the lower case for `nodeObjectType`:

image

This yields no results and therefore `SortOrderExists` returns false, while it should be true. 

I can update the query by casting the column result and the value to `UPPER()` or `LOWER()`:

image

But I don't know if that's the correct solution, I'm going to have to get some input from the team.

**Comment by nul800sebastiaan** [comment]
FYI: my team member Sven made a new PR for this: #17517

**Pull request merged**
