### PR TITLE
V15: Refresh caches on load balanced environments

### LINKED ISSUE #17263: The New <IPublishedContentCache> NOT is refreshing cache for Subscriber servers on load balanced environment
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15+

### Bug summary

When having multiple nodes ,  one is `SchedulingPublisher` and the others are `Subscriber` ,using the extension method `SetServerRegistrar` .

and when you change a nodes content at the Backoffice, there are no changes at the Subscriber nodes 
we need to reset the cache for it to be reflected. 

My config like follows : 

```
        "DatabaseServerMessenger": {
          "MaxProcessingInstructionCount": 1000,
          "TimeBetweenPruneOperations": "00:01:00",
          "TimeBetweenSyncOperations": "00:00:01",
          "TimeToRetainInstructions": "1.00:00:00"
        }
```

### Specifics

_No response_

### Steps to reproduce

Having 2 nodes  , one is `SchedulingPublisher` and another is `Subscriber`. 

 change content at the `SchedulingPublisher` , 
 
 nothing is changed on the `Subscriber`

### Expected result / actual result

Expected result : changes should be reflected.

 actual result: No changes

---
_This item has been added to our backlog AB#45026_

### PR DESCRIPTION
**Pull request by nikolajlauridsen**
This fixes #17263

Separates updating the memory cache and database cache into two separate methods. 

This is because when load balancing only the publisher should update the database cache, however, all subscribers must update their memory cache. 

The memory cache is updated when: 

* The content/media itself changes
* The content/media type changes
* A datatype the content/media type uses changes

This also adds new named options for the documents and media, allowing you to configure the local memory cache duration, the remote cache duration and the seed cache duration for documents and media separately using named options under `Umbraco:CMS:Cache:Entry:`: 

```
  "Umbraco": {
    "CMS": {
      "Cache": {
        "Entry": {
          "Document": {
            "LocalCacheDuration": "2.00:00:00",
            "RemoteCacheDuration": "100.00:00:00",
            "SeedCacheDuration": "200.00:00:00"
          },
          "Media": {
            "LocalCacheDuration": "50.00:00:00",
            "RemoteCacheDuration": "150.00:00:00",
            "SeedCacheDuration": "250.00:00:00"
          }
        }
      },
{...}
```

### CODE REVIEW

**Comment by IbrahimMNada** [comment]
Hello @nikolajlauridsen just quick question , how will the subscribers know if there is content change ? 

only depend on the LocalCacheDuration ? 

if yes To be honest I don't think that is enough , I think we must have some sort of inter-communication 

pub/sub but since there is no coupling with any providers and some providers does not have pub/sub like sql. 

we need some default provider and i think about best bet here is web-hooks between publisher and  subscribers

**Comment by nikolajlauridsen** [comment]
Hi @IbrahimMNada the subscribers know about content changes through the `IServerMessenger`, the default implementation is `BatchedDatabaseServerMessenger`, but this hasn't changed 😄 The new cache needed to hook into these events 😄

**Comment by IbrahimMNada** [comment]
Hello @nikolajlauridsen  , 
Thank for your response

please execute my stupid questions here,  as I'm only trying to learn/understand. from what I understand 

you are utilizing  `umbracoCacheInstruction` table right you will check on it ever N time based on `Umbraco:CMS:Cache:Entry: `
? 

so if the "LocalCacheDuration": "00:30:00", it will reset every 30 mins right ? 
changes will be the same as long as the cache is not passed this time 

I only trying to understand , Thanks <3

**Comment by nikolajlauridsen** [comment]
No stupid questions 😉 

But no, the `LocalCacheDuration` property is for the hybrid cache entry options. The `LocalCacheDuration` specifies for how long the items will be in the local `IMemoryCache` and the `RemoteCacheDuration` specifies how long the items will stay in the remote `IDistributedCache` if configured. This is all part of the hybrid cache from Microsoft, we're just providing an easy way to configure it separately for media and content in the Umbraco settings. 

The `IServerMessenger` is a different thing, explicitly made to facilitate the communication between publisher and subscribers. 

Without going into too much detail it relies on the `InstructionProcessJob` recurring background job and syncs every minute through a special table in the database 😄

**Comment by bielu** [comment]
I don't think it is correct approach, as currently you leak cache implementation into cache refresher, when cache refresher shouldn't be aware of cache implementation, only of exposed api of cache which allows to cache refresh. I guess logic to handle memory part should be built-in into AppCaches not into Cache refreshers, as than even if someone dont use memory cache it will be doing this bit of logic.

**Review by bergmania — APPROVED** [review]

**Comment by jodydonetti** [comment]
Hi all, I don't know if it can still be useful or not, but now there's a production-ready [`HybridCache` implementation](https://github.com/ZiggyCreatures/FusionCache/blob/main/docs/MicrosoftHybridCache.md) with full multi-node support thanks to FusionCache [v2](https://github.com/ZiggyCreatures/FusionCache/releases/tag/v2.0.0).

Hope this helps.

**Pull request merged**
