### PR TITLE
Fix for UseExceptionHandler no longer working since v10.3 RC

### PR DESCRIPTION
**Pull request by justin-nevitech**
### Summary

This PR fixes an issue with `UseExceptionHandler()` which no longer works since v10.3 RC.

### Description

If you add a custom exception handler to the `Configure` method in `Startup.cs` using `UseExceptionHandler()` pointing to a local static HTML file, this exception handler is no longer called as the exception handler introduced with the new 10.3 Backoffice management API inside `ManagementApiComposer.cs` takes over and returns the exception as JSON rather than rendering your error page.

The fix for this is to only handle API exceptions and return the error as JSON if the error occurs during a request for an API (i.e. where the path starts with `/umbraco/api/`).  This means any errors during normal page requests will be handled by your error page and will display a nice friendly message rather than an unfriendly JSON response (which returns far too much error information).

This is an example of the JSON error response:

```json
{"type":"Error","title":"Error!","status":500,"detail":"   at AspNetCore.Views_HomePage.ExecuteAsync() in C:\\My Documents\\Projects\\Open Source\\Umbraco-CMS\\src\\Umbraco.Web.UI\\Views\\HomePage.cshtml:line 39\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)\r\n   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)\r\n   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)\r\n   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Umbraco.Cms.Web.Common.Middleware.BasicAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\\My Documents\\Projects\\Open Source\\Umbraco-CMS\\src\\Umbraco.Web.Website\\Middleware\\BasicAuthenticationMiddleware.cs:line 62\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Web.BackOffice.Middleware.BackOfficeExternalLoginProviderErrorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\\My Documents\\Projects\\Open Source\\Umbraco-CMS\\src\\Umbraco.Web.BackOffice\\Middleware\\BackOfficeExternalLoginProviderErrorMiddleware.cs:line 50\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)\r\n   at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)\r\n   at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)\r\n   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\\projects\\dotnet\\src\\MiniProfiler.AspNetCore\\MiniProfilerMiddleware.cs:line 119\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\\My Documents\\Projects\\Open Source\\Umbraco-CMS\\src\\Umbraco.Web.Common\\Middleware\\UmbracoRequestMiddleware.cs:line 171\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\\My Documents\\Projects\\Open Source\\Umbraco-CMS\\src\\Umbraco.Web.Common\\Middleware\\UmbracoRequestMiddleware.cs:line 177\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\\My Documents\\Projects\\Open Source\\Umbraco-CMS\\src\\Umbraco.Web.Common\\Middleware\\PreviewAuthenticationMiddleware.cs:line 76\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\\My Documents\\Projects\\Open Source\\Umbraco-CMS\\src\\Umbraco.Web.Common\\Middleware\\UmbracoRequestLoggingMiddleware.cs:line 42\r\n   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)","instance":"Exception"}
```

### Steps to Test

1. Create a static error.html page in your wwwroot with the following content:

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
  <h1>Error!</h1>
</body>
</html>
```

3. In your startup.cs, comment out the following lines in the Configure method:

```csharp
//if (env.IsDevelopment())
//{
    //app.UseDeveloperExceptionPage();
//}
````

4. Add the following line directly before or after the lines you have just commented out:

```csharp
app.UseExceptionHandler("/error.html");
```

5. Add a home page document type and template to your site.
6. Add the following code to your home page template:

```csharp
@{
    throw new Exception("Error!");
}
```

7. Add the home page content and navigate to the root of your site.
8. The exception should be handled in your exception handler and the static `error.html` page should be displayed (with 10.3 RC this was showing a JSON response with the error).

_Note - there is an existing issue where Umbraco pages cannot be used as error pages, see: https://github.com/umbraco/Umbraco-CMS/issues/13052.  You will only be able to use a static HTML file as an error page to test this._

All tests have been run and pass.

### CODE REVIEW

**Review by nikolajlauridsen — APPROVED** [review]
Hey @justin-nevitech thanks for the PR, the changes looks good and works good as well 👍 

It took the liberty of updating the management API path since we've changed it to `/umbraco/management/api/` 😄 

I'm a bit curious when you say that this broke something in v10.3rc considering that the new backoffice management API is not released anywhere, and thus sites on v10 cannot take a reference to it, so the `ManagementApiComposer` will never get run. It only runs when working directly with the source code, but maybe that's what you meant. I'm just a bit confused here 😄 


But regardless this is (or rather was now) a problem with the management API, so big H5YR for this fix :) I'll go ahead and get this merged.

**Comment by justin-nevitech** [comment]
Hi @nikolajlauridsen 

The management API is in the v10 contrib branch so I assumed that was also in the V10.3 RC (possibly a wrong assumption).  I wasn't sure how to get a copy of the code for V10.3 RC as I didn't know what the branch was called?  I only came across this issue as I was trying to fix another issue and ended up seeing a JSON error message.

**Comment by nikolajlauridsen** [comment]
Ahh okay, I see, that makes sense 😄

But no, we've set the projects in the `NewBackoffice` solution folder as non-packable, so they won't get released. These are the new APIs that we want to use with the new backoffice (targeting v13), so these are currently not used. The reason for them being in the v10 and v11 branches is to avoid having to deal with too many merge conflicts, and of course, because it gets people a chance to take a peek 😉.

In regards to releases those are prefixed with `release/`, so for 10.3 the branch was named `release/10.3/`, but these branches are short lived, so it doesn't exist anymore, so if you want to see the code for 10.3 you have to check out the tag `release-10.3.0` 😄

**Comment by justin-nevitech** [comment]
Hi @nikolajlauridsen 

That makes sense, although that means the V10 contrib branch still runs the code as it exists there even if it was not released as part of v10, so running Umbraco via the source code can (and did in this example) result in different behaviour to what would get released.  I think that could potentially be a bad thing as that means you are developing against code you are not releasing?  Just a thought...

Thanks for the tip re the tags!

**Comment by nikolajlauridsen** [comment]
I see your point, and it's true that the runtime will be somewhat different running via the source code (as shown by this PR), but since `Umbraco.Web.UI` is the only which has a reference to the new management API it's not something I'm that concerned about since you can't actually depend on the code itself. 

But it's something worth considering, maybe adding a switch of some kind so the composer only runs if you opt-in to it, or something similar, I'll take it up with the team 😄

**Comment by justin-nevitech** [comment]
Thanks @nikolajlauridsen 

Could you mark this up as a Hacktoberfest contribution please?

**Comment by nikolajlauridsen** [comment]
Oh yes of course, my bad sorry 😅

**Comment by justin-nevitech** [comment]
@nikolajlauridsen Thanks!

**Pull request merged**
