### PR TITLE
Urgent: Add Giphy embed provider support

### PR DESCRIPTION
**Pull request by marcemarc**
### Prerequisites

- [  x  ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description

This PR adds the ability to embed a Giphy using the Embed functionality of the Rich Text Editor in Umbraco.

Open the Rich Text Editor

Press the embed button, add a link to your favourite GIPHY eg:

https://media.giphy.com/media/wZOrAohvQwAbC/giphy.gif

Giphy should become embedded in the rich text area...

... that is it.

### CODE REVIEW

**Comment by dawoe** [comment]
Hi @marcemarc 

Thanks for your wonderful contribution. If you ask me this has been missing from Umbraco for a long time.

I actually think you should create a PR targetted at V7 as well and see if we can get it in v7.15

Otherwise we will get customers asking us to migrate to V8 because of the missing giphy support.

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by leekelleher** [comment]
> Otherwise we will get customers asking us to migrate to V8 because of the missing giphy support.

Missing the marketing potential here... **Umbraco 8... Variants, Content Apps, Infinite Editing... _and Giphy!_**

**Comment by marcemarc** [comment]
@dawoe I did think about that, but it's just an entry in the embeddedmedia.config file for V7, so it's likely people will already have added it in. I mean how else would they build sites without it?

**Comment by dawoe** [comment]
@marcemarc still you can create a PR for adding the entry targeted at V7.

**Comment by marcemarc** [comment]
@dawoe related issue + PR for V7 here: https://github.com/umbraco/Umbraco-CMS/pull/5736

**Comment by dawoe** [comment]
How meta...creating a gif to show the embedding of a gif

**Pull request merged**
