### PR TITLE
Redirects don't work when culture is empty string

### PR DESCRIPTION
**Pull request by nzdev**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description

Redirects don't work when culture is empty string. Previously GetAssignedWithCulture callers would convert empty string before calling to null. This pr handles the empty culture case.

How to test?
Create a parent and publish.
Set the parent to have a domain.
Create child node and publish.
Change child node name (this causes a redirect to be created.
There should be a new redirect record in the redirects table. The url should start with the parent nodes id.
Use the redirect url. Should redirect.

### CODE REVIEW

**Comment by nzdev** [comment]
Fixes breaking change from v8->v9

**Comment by emmagarland** [comment]
Hi @nzdev, 

Sorry for the long delay to this PR, and many thanks for flagging it at the time. 

I've just rebased to the `contrib` branch and there have been some conflicts introduced; however, I was also wondering if this issue still stands?

Checking the `DomainCacheExtensions.cs` file [in contrib branch](https://github.com/umbraco/Umbraco-CMS/blob/36069aa8139b6125398786d378ac712b5382d0b0/src/Umbraco.PublishedCache.NuCache/DomainCacheExtensions.cs#L15)  and I can see a `string.IsNullOrEmpty(culture)` check in there now.

Thanks, 
Emma

**Comment by nzdev** [comment]
Issue remains

**Comment by emmagarland** [comment]
Hi @nzdev 

I'm just trying to replicate the behaviour described, and was wondering how you had setup the domain name for the parent node? Did you use IIS/IIS Express?

Thanks

Emma

**Pull request closed without merging**
