### PR TITLE
Ported over the fixes in #11858 "Check media Parent for permissions when setting correct MediaType" to target v8

### PR DESCRIPTION
**Pull request by OwainJ**
Ported over the fixes in the v9 PR #11858 **Check media Parent for permissions when setting correct MediaType** to v8.

### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes [#7735](https://github.com/umbraco/Umbraco-CMS/issues/7735)

### Description
I have ported over fixes from the v9 PR #11858, as the fixed issue also affected v8, the fixes have been tweaked slightly to work with v8's codebase.

**Description from the v9 PR:**
> Ever since Umbraco version 8.14, the way media gets uploaded has changed. In the past, uploading media directly from a MediaPicker would respect the permissions set on the upload folder when not using the default mediaType of "Image". Ever since version 8.14 this has changed, and even if the folder does not allow the default "Image" item to be uploaded, it still forces the uploaded image to be that media type (and same with File).
> 
> With this pullrequest, as created and demonstrated during today's umbraCollab, we not just upload an image with the default 'Image' Media Type, but first try to determine if the folder we are trying to upload the item to has any specific permissions set that have the "umbracoFile" property. If that is the case, we want to use that Media Type instead of the default!
> 
> For Folders we are not able to distinguish between custom folders or the default Folder, so best practice for now would be to not allow the creation of the default Folder if the parent doesn't explicitly allow this, so that we can't create folders where they aren't allowed!
> 
> To test this Pullrequest, simply try out any mediapicker that points towards a media folder that has specific permissions set up, upload a new image, and it will upload it to the correct media type! If it does not find any items within it's permitted children with a property of alias umbracoFile, it will continue with the rest of the Umbraco logic and upload to the default type!

Gif of the drag & drop upload working correctly in v8:
v8 media drag and drop fix

### CODE REVIEW

**Review by elit0451 — COMMENTED** [review]
Thank you @OwainJ for porting the fix to Umbraco 8 🙌 I reviewed and tested it and left a few comments for you. I will push the needed changes and once the build pipeline succeeds I will make sure to merge it 😉

**Comment by elcoinkeur** [comment]
Hi ! We updated our Umbraco site to 8.18.3 from and older version some weeks ago, and figured out about this issue just now. As 8.18.3 just released a month ago, is there any plan to release 8.18.4 anytime soon ? It's frustrating to go to medias each time we want to upload a specific image type.

**Comment by OwainJ** [comment]
@elcoinkeur according to the release progress tracker, 8.18.14 is scheduled for release on Monday, the 16th of May.
You can view the release progress here: https://our.umbraco.com/download/releases/8184

**Comment by stefanbesteman-weareyou** [comment]
Hi @OwainJ ,

We upgraded an existing umbraco 8.17.1 to 8.18.5 where we use differtent media type images per folder.

After the upgrade we could not upload new images anymore to our specific folders.

We use for example a mediatype 'Header visual images Folder' with rights to add 'Header visual image' media type and rights to add a subfolder of the same media type 'Header visual images Folder'. If we remove the rights to add the subfolder it works again as expected and this is for now a good workaround, but our client will want to make subfolders in the future. Can you please fix this in the next version?

Thanks in advance
Stefan Besteman (IO Digital)

**Pull request merged**
