### PR TITLE
Proposed fix for ReflectionTypeLoadExceptions in WebBootManager (Exce…

### PR DESCRIPTION
**Pull request by r-o-e-l-o-f**
Proposed fix for ReflectionTypeLoadExceptions in WebBootManager (Exception doesn't need to be breaking, see also http://stackoverflow.com/questions/7889228)

### CODE REVIEW

**Comment by Shazwazza** [comment]
Can you link to an issue on our tracker with full details as to why this is needed, steps to reproduce, etc... thanks!

**Comment by r-o-e-l-o-f** [comment]
Hi Shannon,

I’ve discussed this issue with Sebastiaan (as per the instructions on the website), and he told me to go ahead and do a pull request.
I’ve included the email. Let me know if you need more information.

Best regards,
Roelof



Van: Shannon Deminick [mailto:notifications@github.com]
Verzonden: woensdag 22 juni 2016 17:06
Aan: umbraco/Umbraco-CMS <Umbraco-CMS@noreply.github.com>
CC: Roelof Nijholt <roelof.nijholt@malengo.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [umbraco/Umbraco-CMS] Proposed fix for ReflectionTypeLoadExceptions in WebBootManager (Exce… (#1349)


Can you link to an issue on our tracker with full details as to why this is needed, steps to reproduce, etc... thanks!

**Comment by Shazwazza** [comment]
Hi, this is fine as a start but i need an issue to link it to in the tracker with full details of why were doing this.... I need to know what problem this is solving, this is a very core change and i need to be sure what is being done is on every Umbraco installs best interest. 

If you could please create an issue on the tracker with these details it would be appreciated.

**Comment by zpqrtbnk** [comment]
To be discussed on the tracker: I guess this enables Umbraco to run even though the whole DLL set in `~/bin` is not fully consistent, ie some dependencies cannot be resolved. Unresolved dependencies can break many things, including dynamics extension methods. Before that PR we were explicit and would throw. If we now are silent, is there a risk that debugging becomes harder?

**Comment by r-o-e-l-o-f** [comment]
It depends on your aim with the iteration of all external types. In my debug scenario it seemed a case of finding external eventhandlers. Our scenario is like this: we have many projects using a piece of code (C) in a library (L) which references a certain version of an external library (EL). Continuous changes of this external library made us decide to extract code C into a seperate Nuget (N). This enables better upgrade management in new projects, but we need to keep library L backwards compatible. Maintaining separate branches would mean a lot of work. On new projects the code C is now referenced from Nuget N, but library L is also used. Nuget N references a newer version of EL. The bootstrap loader now throws the reflectiontypeloadexception because of namespace changes in external library EL.Without the break the project otherwise works fine. 

I guess this could happen any time a project references 2 (or more) libraries that have references to different versions of the same third party library. Of course I understand your reasoning to be cautious with core changes, but my educated guess would be that this can't really hurt and would be beneficial for more developing parties.

**Comment by r-o-e-l-o-f** [comment]
@Shazwazza, @zpqrtbnk I've registered an issue on the tracker, as requested (http://issues.umbraco.org/issue/U4-8652)

**Comment by zpqrtbnk** [comment]
Since I really want to preserve the default behavior (throw) i'm not merging this PR, but thanks for the input, have created alt. PR https://github.com/umbraco/Umbraco-CMS/pull/2249 which adds the discussed white-list. Now up for review.

**Pull request closed without merging**
