### PR TITLE
V8: Improve plugin language handling 

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/4371

### Description

This PR allows for more flexible plugin language files as discussed on #4371. 

I have removed all restrictions/filtering on file name length as `LocalizedTextServiceFileSources` already handles validation of the file content and mapping to the correct culture.

### Testing this PR

Provided that your Umbraco user is set up to en-US localization:

1. Add this plugin to `App_Plugins`: [LanguageTestPlugin.zip](https://github.com/umbraco/Umbraco-CMS/files/2837096/LanguageTestPlugin.zip)
2. Replace the contents of `~/Config/Lang/en-US.user.xml` with this:
```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<language>
    <area alias="treeHeaders">
        <key alias="content">User defined label here</key>
    </area>
</language>
```
3. Restart the site.
4. Verify that the test dashboard shows the en-US labels defined in `~/App_Plugins/LanguageTestPlugin/Lang/en-US.xml` and that the content tree header is updated according to `~/Config/Lang/en-US.user.xml`:
image
5. Rename `~/App_Plugins/LanguageTestPlugin/Lang/en-US.xml` to `~/App_Plugins/LanguageTestPlugin/Lang/en_us.xml` 
6. Restart the site.
7. Verify that the test dashboard still shows the en-US labels.
8. Delete `~/App_Plugins/LanguageTestPlugin/Lang/en-US.xml` and rename `~/App_Plugins/LanguageTestPlugin/Lang/xx.xml` to `~/App_Plugins/LanguageTestPlugin/Lang/en.xml`.
9. Restart the site.
10. Verify that the test dashboard now shows the en labels defined in `~/App_Plugins/LanguageTestPlugin/Lang/en.xml`:
image

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey Kenn,

As ever, great work and lots of detail for us. We'll shout if we need a thing,

Em

**Comment by clausjensen** [comment]
connects to https://github.com/umbraco/Umbraco-CMS/issues/4371

**Comment by poornimanayar** [comment]
@kjac , Can you resolve the conflicts if you can and I can test this today for you :-)

Poornima

**Comment by kjac** [comment]
@poornimanayar all done 👍

**Comment by poornimanayar** [comment]
@kjac ,

I have tested what you have mentioned above and its fine. Is the selection of language driven by the language set up for the logged in user? Should we be testing that?

Poornima

**Comment by kjac** [comment]
@poornimanayar yeah the user language is defining for which language XML file is used. You can test if if you have the patience 😄 but really it shouldn't be necessary; if the locale reads correctly given the test scenarios outlined above, all should be good.

**Comment by poornimanayar** [comment]
Hi @kjac ,

Thank for the reply. I assume the dashboard plugin should read from en-US if your user language set up is en-US and from en if the user language set up is en-GB, so acts as a fallback basically. Sorry, I just thought too much and got confused with the multi-language set-up as i have as well. Hence clarifying :-) But its all looking good :-)

Poornima

**Comment by nul800sebastiaan** [comment]
Wonderful, lovely changes, thanks very much! 🎉

**Pull request merged**
