### PR TITLE
New user journey for the DataType Picker in the DocumentType Editor

### PR DESCRIPTION
**Pull request by nielslyngsoe**
Improving the user journey of the Data Type Picker in the Document Type Editor.

Fixes https://github.com/umbraco/Umbraco-CMS/issues/5656

Changes:
- Removes the Create New / Use existing Tabs from the DataType picker.
- Only shows the available PropertyEditor in the first view of the DataType Picker, unless search is activated.
- By clicking a PropertyEditor the available DataTypes using that PropertyEditor will be shown, and the ability to create a new DataType.

Screencapture:
doctypeeditor_pick_datatype

If the user wants to search for their Configurations or PropertyEditors the experience is the same as before:
doctypeeditor_pick_datatype_search

### CODE REVIEW

**Comment by warrenbuckley** [comment]
Code is fine, few tiny changes to do please :)
Off to test & check this all works all OK

**Comment by warrenbuckley** [comment]
This is due for 8.7.0 release currently

**Comment by bjarnef** [comment]
Okay, since this is now part of `v8/contrib` branch, it has probably made this PR obsolete:
https://github.com/umbraco/Umbraco-CMS/pull/8071

However I think the "cross" icon signals "remove" or "delete", but it actually "change/edit" the property editor.

@nielslyngsoe is there a specific reason the icon has changed from the `icon-settings` icon, which is used many other places in the UI to change configuration?

**Comment by bjarnef** [comment]
@nielslyngsoe I have made some enhancements in this PR: https://github.com/umbraco/Umbraco-CMS/pull/8251

**Comment by craigs100** [comment]
I hope this is an appropriate place to raise this, but could you please consider changing the order of the automatically generated DataType names? In @nielslyngsoe 's first animation this would make "Product - Multinode Treepicker" into "Multinode Treepicker - Product". It makes it easier to find in the DateType list later.  This was discussed at CG 18 open sessions (I think) and seemed to be a popular suggestion.
Thanks.

**Pull request merged**
