### PR TITLE
Request Handler Settings for character replacement

### LINKED ISSUE #11381: URL replacing doesn't work as expected
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.1

### Bug summary

It seems the URL replacing in V9 doesn't work as expected and we know from e.g. V8.
It has been documented here: https://our.umbraco.com/documentation/Reference/V9-Config/RequestHandlerSettings/

Also see the following forum thread: https://our.umbraco.com/forum/umbraco-9/107221-urlreplacing-for-umbraco-9

I added the following the `appsettings.json` under `Umbraco > CMS` in the JSON. It actually shows intellisense for this in VS, which is nice 👍 

However after stopping application, rebuild and starting application again plus publishing a new, it doesn't seems to have any effect. I tried with  `appsettings.Development.json` as well, but the still no change.

```
"RequestHandler": {
        "ConvertUrlsToAscii": "try",
        "CharCollection": [
          {
            "Char": "ø",
            "Replacement": "o"
          }
        ]
      }
```

In this case I have a  search page "Søg" i Danish. I would expect the URL to change to `/sog` , but stll the default URL `/soeg`  which is default from here: https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Core/Configuration/Models/RequestHandlerSettings.cs#L38

I guess this just not overwrite the default char collection somehow?

### Specifics

_No response_

### Steps to reproduce

Replace characters in `appsettings.json` which is different from default char collection here: https://github.com/umbraco/Umbraco-CMS/blob/5bfab13dc5a268714aad2426a2b68ab5561a6407/src/Umbraco.Core/Configuration/Models/RequestHandlerSettings.cs#L20-L46

Find a node which the char, rename the node or create a new node and notice the char in the URL isn't replaced.

```
"RequestHandler": {
        "ConvertUrlsToAscii": "try",
        "CharCollection": [
          {
            "Char": "ø",
            "Replacement": "o"
          }
        ]
      }
```

However it does seem this example work:
https://our.umbraco.com/documentation/Reference/V9-Config/RequestHandlerSettings/#char-collection

```
{
  "Char": "ñ",
  "Replacement": "n"
}
```

Create a page "Somethiñg" and notice the URL is `/something`.

### Expected result / actual result

_No response_

---
_This item has been added to our backlog [AB#15635](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15635)_

### PR DESCRIPTION
**Pull request by matthewcare**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

Fixes #11381

### Description
Most of the information is listed in the original issue.

`appsettings.json` configuration didn't map RequestHandlerSettings `CharCollection`  correctly, so was never used.

I've updated so that the mapping is correct, and have added a method to get the replacements taking into account the user and default replacements.

Added an extra configuration setting to disable the default replacements
Added a number of tests

Nothing should be a breaking change - however seen as how it was never working to begin with, I'm not sure how it would be classified.

The last thing to consider is that I've left the TODO in which talks about handling the `:` character, but I'm not sure what actually needs to be done there, if anyone can offer assistance.

### CODE REVIEW

**Comment by matthewcare** [comment]
Questions for potential additional work on this PR:

- There was a TODO left in the code that mentions `:` needing consideration, what should I do there?
- `CharCollection` isn't a very user friendly name to be using in appsettings.json, could we change it to be a better name?
- In Umbraco < 9, the `Char` was indeed a `char` whereas in 9, it supports `strings`, is this intentional?
- Again, naming here isn't clear, consider changing?

**Comment by nikolajlauridsen** [comment]
Hey @matthewcare, thanks a lot for your contribution, that's some stellar work 💪 

I've made some changes to your pull request, mostly to avoid breaking changes, but we should be all good now 😄.

I did have to do some janky behaviour with the `CharCollection` property since it previously was intended to return the merge of the default char replacements, as well as the user, define char replacements, so changing this would be a behavioural breaking change. 

The problem occurs if we return the default char replacements the first time the getter is called, if we do that the framework will see that `CharCollection` already returns an `IEnumerable` and will therefore skip the bindings to the `appsettings.json` file, completely ignore the user defined ones,  which defeats the point of this PR 😅. To get around this I've made it so the very first time the `CharCollection` is called by the framework, it'll return null, however, this broke the tests, so I had to add an explicit check in `DefaultShortStringHelperConfig` for the tests. 

Needless to say, this is not super nice behaviour, my fault, not yours, sorry 😅, so I'll have to have a think, and ask around if we can achieve this part in a better way.

In regards to your comment, I've taken a look at the TODO you mentioned, and after some testing, I'm fairly certain that this is a non-issue since we don't actually operate on the config keys at all, so I've removed it, you can test this by adding something like this your `launchSettings.json`, and the chars will still be replaced in the URLs:

```json
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "Umbraco:CMS:RequestHandler:CharCollection:0:Char": "ø",
        "Umbraco:CMS:RequestHandler:CharCollection:0:Replacement": "o",
        "Umbraco:CMS:RequestHandler:CharCollection:1:Char": ":",
        "Umbraco:CMS:RequestHandler:CharCollection:1:Replacement": "colon",
        "Umbraco:CMS:RequestHandler:CharCollection:2:Char": "ñ",
        "Umbraco:CMS:RequestHandler:CharCollection:2:Replacement": "nj",
        "Umbraco:CMS:RequestHandler:CharCollection:3:Char": "Ñ",
        "Umbraco:CMS:RequestHandler:CharCollection:3:Replacement": "Nj",
        "Umbraco:CMS:RequestHandler:EnableDefaultCharReplacements": "true"
      }
```

In regards to the naming aspect, I agree that they're not the best they can be, however, we can't really change this, in  V9 at least, since it sadly would be big-time breaking changes.

In regards to why we support strings now and not chars, I must admit that I don't fully know the reasoning behind this, my guess would be to support scenarios like above where you might want to replace `Ñ` with `Nj` to be as phonetically close as possible, but that's just my best guess 😄

**Comment by nikolajlauridsen** [comment]
After having a chat with Bjarke we came up with a better solution. 

What we've done is we've added a new settings property `UserDefinedCharCollection` and obsoleted the old one, this way nothing should break for anyone. 

We then manually map both `CharCollection` and `UserDefinedCharCollection` from the `appsettings.json`, merging the two with `UsedDefinedCharCollection` taking priority, this way both can be used in the app settings, but `UserDefinedCharCollection` wins.

If you want to get the char replacements you then used the extension method you made `GetCharReplacements`, the obsolete message also points to this. 

This way it all works, and there's no breaking changes 🎉 

This is all good to me now, but before we merge this I'll have another member on the team also review this, just to make sure I haven't overlooked anything. 

## Additional Testing
* Ensure that `UserDefinedCharCollection` takes priority over `CharCollection` and defaults
* Ensure that the values are still correct if you use `IOptionsMonitor` and change the config during runtime (note that DefaultStringHelper does not use IOptionsMonitor, so the URLs won't be correct until the site is restarted)
* Ensure that there are no duplicates in the output from GetCharReplacements

I used the following configuration to test:

```json
  "Umbraco": {
    "CMS": {
      "RequestHandler": {
        "ConvertUrlsToAscii": "try",
        "EnableDefaultCharReplacements": true,
        "CharCollection": [
          {
            "Char": "ø",
            "Replacement": "o"
          },
          {
            "Char": ":",
            "Replacement": "colon"
          },
          {
            "Char": "å",
            "Replacement": "a"
          },
          {
            "Char": ">",
            "Replacement": "gt"
          }
        ],
        "UserDefinedCharCollection": [
          {
            "Char": "<",
            "Replacement": "lt"
          },
          {
            "Char": "å",
            "Replacement": "ä"
          },
          {
            "Char": ">",
            "Replacement": "greaterThan"
          }
        ]
      }
```

And this component can be used to test the IOptionsMonitor, just set a breakpoint in the `OnChange`:

```C#
using Microsoft.Extensions.Options;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Configuration.Models;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.UI
{
    public class TestComponent : IComponent
    {
        private readonly RequestHandlerSettings _options;

        public TestComponent(IOptionsMonitor<RequestHandlerSettings> options)
        {
            _options = options.CurrentValue;
            options.OnChange(settings =>
            {
                var userReplacements = settings.GetCharReplacements();
            });
        }

        public void Initialize()
        {
        }

        public void Terminate() {}
    }

    public class MyComposer : ComponentComposer<TestComponent> { }
}

```

**Comment by albinbrengesjo** [comment]
The Request handler still acts weird (for most replacements not working at all) in Umbraco 9.3.1 with replacements of å, ä, ö. Also, the settings stated in the our documentation brakes the "IsVisible()" method which makes all hidden pages visible. Anyone else experience the same problems?

**Comment by enkelmedia** [comment]
I'm also having issues here, I have configured a simple override in the "UserDefinedCharCollection".

```javascript
"RequestHandler": {
        "AddTrailingSlash": false,
        "ConvertUrlsToAscii": "try",
        "UserDefinedCharCollection": [
          {
            "Char": "å",
            "Replacement": "a"
          },
          {
            "Char": "ä",
            "Replacement": "a"
          },
          {
            "Char": "ö",
            "Replacement": "o"
          }
        ]
      }
```

And getting this error during startup:

```
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException[T](T key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Umbraco.Cms.Core.Strings.DefaultShortStringHelperConfig.WithDefault(RequestHandlerSettings requestHandlerSettings)
   at Umbraco.Cms.Infrastructure.DependencyInjection.UmbracoBuilderExtensions.<>c.<AddCoreInitialServices>b__0_5(IServiceProvider factory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Umbraco.Extensions.ServiceProviderExtensions.CreateInstance(IServiceProvider serviceProvider, Type type, Object[] args)
   at Umbraco.Extensions.ServiceProviderExtensions.CreateInstance[T](IServiceProvider serviceProvider, Object[] args)
   at Umbraco.Cms.Infrastructure.DependencyInjection.UmbracoBuilderExtensions.<>c__DisplayClass31_0.<SetMediaFileSystem>b__0(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Umbraco.Cms.Infrastructure.DependencyInjection.UmbracoBuilderExtensions.<>c.<AddCoreInitialServices>b__0_3(IServiceProvider f)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder.<>c.<AddCoreServices>b__26_6(IServiceProvider f)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at ERASweden.Web.UI.Program.Main(String[] args) in C:\Development\EraSweden\EraSweden.Web.UI\Program.cs:line 11
```

**Comment by enkelmedia** [comment]
@albinbrengesjo just so you know.

I managed to get things working with this configuration:

```javascript
      "RequestHandler": {
        "AddTrailingSlash": false,
        "ConvertUrlsToAscii": "try",
        "EnableDefaultCharReplacements": false
      }
```

This will basically skip all the configured stuff in the default "CharCollection" but still convert stuff to Ascii.

So a page called "Överdriva sätter igång tankar" would produce a URL like this: "overdriva-satter-igang-tankar".

The configuration is really confusing =D

**Pull request merged**
