### PR TITLE
Uses AppSettings.Path constant for SystemDirectories.Umbraco

### PR DESCRIPTION
**Pull request by jmcaveney**
- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/7336

Changes the magic string in Umbraco.Core.IO.SystemDirectories.Umbraco to use the global constant for the AppSettings.Path. This results in the css being pulled from the correct location when the backoffice is launched.

Tested with these settings:
Capture

Then the css files loaded from the correct location:
image

### CODE REVIEW

**Comment by emmaburstow** [comment]
Lovely! Nice spot. And congrats on your first PR to this repo too! One of us will take a look and merge. We shouldn't have any questions for this one :) If you have an Our.Umbraco.Com profile, let us know and we'll get a contributor badge added for you.

All the best!

Emma, [Pull Request team](https://umbraco.com/blog/the-pr-team-chronicles-september-2019/)

**Comment by jmcaveney** [comment]
I thought I had one... guess not? But I set it up linked to my github account now.

**Comment by nul800sebastiaan** [comment]
Thanks so far @jmcaveney! 👍 - I see the other strings also list the v7 appsetting names, could you update those as well please?

**Comment by jmcaveney** [comment]
I did think about that... the other app setting string values (cs spath, scripts path, media path) were consistent with what I could see in the [documentation](https://our.umbraco.com/documentation/Reference/Config/webconfig/), and there aren't constants in place for them. I can add the constants and reference them if that's what you're talking about?

The only other app setting specific reference in that class is the Temp path and from a quick glance looks like it will require duplicating code from the Global Settings to translate the enum value to a path, which might be one of those instances where you should just be migrating those references to the Global Settings class.

**Comment by nul800sebastiaan** [comment]
@jmcaveney Aha! Well, looks like we never changed those then, what a missed chance! We'll leave these as is then, don't mind me! 🙈

But yes, it would be great to make some constants for them so we can easily change them in the future major version 👍 

Regarding the temp path, sounds good to put that in a central place if possible yeah.

**Comment by jmcaveney** [comment]
@nul800sebastiaan those constants are added and code updated to use them.

**Comment by nul800sebastiaan** [comment]
Great stuff @jmcaveney! Sorry for the delay in merging, but all good now! 

I see this is your first PR for Umbraco-CMS as well, congrats on that! :+1:

Congrats on your first accepted PR for Umbraco-CMS, you've earned yourself a well deserved Contributor badge on your Our Umbraco profile: https://our.umbraco.com/members/id:279447/ :medal: :sports_medal:

Look forward to seeing more of your handywork in the future!

**Comment by jmcaveney** [comment]
@nul800sebastiaan that's not my umbraco profile... this is:
https://our.umbraco.com/members/jmcaveney/

no big deal, just wanted to make sure it was applied in the right place. thanks!

**Comment by nul800sebastiaan** [comment]
@jmcaveney 😲 haha, sorry about that, what a weird mix-up! Applied to the correct profile now! 👍

**Pull request merged**
