### PR TITLE
V8: Fix JS error when editing document types with Nested Content properties

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

Just noticed there are a few JS errors in the console when you edit document types with Nested Content properties:

nested-content-copy-action-js-error

It happens whether you use infinite editing or not, and is related to the new "copy all items" feature. 

This PR applies a bit of defensive coding to ensure it doesn't happen 😄

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hola Kenn,

Thanks for the work here. We'll shout if we need you.

Em

**Comment by kjac** [comment]
Updated with latest v8/dev

**Comment by kjac** [comment]
Updated with latest v8/dev

**Comment by poornimanayar** [comment]
And merged⭐️ !!!!

**Pull request merged**
