### PR TITLE
 #2916 Media picker searches entire media archive

### PR DESCRIPTION
**Pull request by KimHolzmann**
### Prerequisites

- [ ] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is:
- [ ] I have added steps to test this contribution in the description below

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @KimHolzmann 

Thanks so much for this pull request. We'll have a look through and test functionality and let you know if we need you to do anything.

One thought - rather than the phrase 'Include from subfolders' where it's printed in English, could you change to 'Include subfolders in search'?

Thanks,

Emma, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-pr-team/)

**Comment by KimHolzmann** [comment]
done :-)

**Comment by KimHolzmann** [comment]
The failling is it my code or is it the deploy/check system ? 
image

**Comment by emmaburstow** [comment]
Thanks @KimHolzmann!

That was fast :)

Yeah I think it is the system. There are a handful of fails at the mo.

**Comment by nul800sebastiaan** [comment]
Hey there @KimHolzmann ! Great to see that you managed to finish this PR! 

I'm guessing you're working on a mac? I had to do some  "interesting" hacks to make sure all files weren't marked as deleted and re-added afterwards. Weird.

image

Anyway, that's done now.

One tip: you never have to change any of the language files except en.xml and en_us.xml. I think Umbraco just falls back to en.xml if it can't find the key in any other file.

I'll accept this PR for now as the functionality is super useful! I do, however think it looks a little but ugly,  but maybe @bjarnef or @BatJan can help out a little with that? Would be ace! 👍 


image

**Comment by KimHolzmann** [comment]
Hi @nul800sebastiaan 
Thx for feedback :-)
yes I works on a mac but with windows installed.
Cool if @bjarnef  or @BatJan  make it less ugly 👍

**Comment by BatJan** [comment]
@nul800sebastiaan I'll be more than happy to take a look :-) - Should I create a new issue (referencing this PR) and then make a PR for my issue?

**Comment by BatJan** [comment]
I have made a PR for making the toggle option look prettier here https://github.com/umbraco/Umbraco-CMS/pull/3103

**Pull request merged**
