### PR TITLE
V8: Simplify font setup

### PR DESCRIPTION
**Pull request by BatJan**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: #4474 

### Description
~~**This PR is still work in progress** - I'll make sure to ping Sebastiaan and edit the title (remove the WIP) when this one is ready for review.~~

Ok @nul800sebastiaan This one is ready for review 😃 

I have cleaned up the font setup, which means many of the unused font files have been removed since .woff and .woff2 has great coverage for the browsers Umbraco supports according to the System requirements section in the documentation here https://our.umbraco.com/documentation/Getting-Started/Setup/Requirements/

Support for .woff and .woff2 can be found here:

https://caniuse.com/#search=woff
https://caniuse.com/#search=woff2

I have modified the setup code so it first looks for the needed font on the users local machine before trying to download it, which should improve performance. I have also set font-display: swap, which means the font's won't block the showing of text so a system font or whatever will be used initially and the browser will do a swap once the font's are ready for being used. This property will be ignored by Edge though since it's not yet support it meaning there can be a short period where text is not visible until the font's are resolved - But that's how it works today anyway 😃 

For the OpenSans font I have deleted the old files and added .woff and .woff2 versions for the font using the Google Fonts helper app at https://google-webfonts-helper.herokuapp.com/fonts/open-sans?subsets=cyrillic,latin

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi Jan!

Thanks for finishing up this wip. We'll take a look and let you know if we need anything. Looks like ace work at a first glance. I've come to expect nothing less from you though ;) 

Em

**Comment by BatJan** [comment]
Thank you @emmaburstow - You're making me blush now 😊 

I'm going to do just one small tweak to the code now - I will store the font paths in some variables. It's a little nitpick but while we're at it we might as well optimize it all 😃

**Comment by BatJan** [comment]
Stored the font paths in some variables for easier reuse 😃

**Comment by nul800sebastiaan** [comment]
Aaah much cleaner, very very nice! 🥉👍

**Pull request merged**
