### PR TITLE
U4-11168 : Making the dropdown menu more user friendly within the Document Type icon picker

### PR DESCRIPTION
**Pull request by OwainWilliams**

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks @OwainWilliams - I understand the thought behind this but unfortunately it becomes a bit of an unreadable mess. I think it would be way better to have each color represented as a square in front of it's name, like the way Chrome does it for example:

image

Any chance you can look into doing that instead?

**Comment by OwainWilliams** [comment]
Hi @nul800sebastiaan 
Funny you should say this, I've been looking in to this option because I totally agree it's not the most accessible option. Leave it with me and I'll see what I can do 👍

**Comment by bjarnef** [comment]
I agree it should use a different approach than changing the text color of the options.

Something like Github label colors:
image

An option could be to use the `umbDropdown` component, but I am not sure how well it works with many items (scroll).
https://our.umbraco.org/apidocs/ui/#/api/umbraco.directives.directive:umbDropdown

Alternatively it could use a third party component like Selectize https://selectize.github.io/selectize.js/ (or another component (Angular/jQuery/javascript) extending the navtive dropdownlist, which allow to have custom labels like these https://tabler.github.io/tabler/form-elements.html (based on Selectize).

Maybe @madsrasmussen has some input on this? :wink: 🦄

**Comment by madsrasmussen** [comment]
I think it is a great idea to add the colored box next to the label instead of coloring the label itself. 

As far as I remember the umbDropdown component should be able to do what you are looking for. You might need to set a max-height on the drop-down element though to allow scrolling.

**Comment by bjarnef** [comment]
A few other ideas could be to list the defined colors and act like a radiobutton list https://bladepop.github.io/colorpicker/ or some kind of dialog (e.g. by using the `umbDropdown` component) or a custom directive/component https://bladepop.github.io/colorpicker/

**Comment by nul800sebastiaan** [comment]
Oh nice! Yes, no need for it to be a dropdown, the color names are not actually used anywhere else anyway.

**Comment by OwainWilliams** [comment]
Brilliant - love the ideas. I'll have a look and see what I can come up with over the coming days.

**Comment by OwainWilliams** [comment]
Thinking about implementing something like this: https://codepen.io/richiksc/pen/dovpyB 
What do you all think?

**Comment by bjarnef** [comment]
I found these two color/swactch pickers, which are simple, yet pretty awesome.
https://saintplay.github.io/vue-swatches/
https://xiaokaike.github.io/vue-color/

Alternatively there is a swatch picker like this.
https://www.webcomponents.org/element/PolymerElements/paper-swatch-picker

I think it is fine to limit the colors to some predefined colors for consistency.

I like all these three examples.

@madsrasmussen any thoughts on these examples? should we have a "swatch picker" component like this in core? Maybe to be re-useable in prevalue editors and property editors?

**Comment by OwainWilliams** [comment]
Nice @bjarnef - I've got some free time next week so I plan to jump back on to this. 👍

**Comment by OwainWilliams** [comment]
Added colour picker options instead of a dropdown list.
image

When the user hovers over a colour, they get a tooltip telling them what colour they are hovering on. 

Once a colour is selected, a shadow is placed behind the colour to show that it's selected as well as all the icons changing colour.
image

**Comment by abjerner** [comment]
@OwainWilliams I haven't looked code, but your screenshots look awesome 👍 

One tiny detail I've noticed is that the rounded corners (border radius) may be a little too much compared to other components in Umbraco.

Umbraco appears to be using a border radius of 3 pixels - eg:

image

image

I'll look forward to seeing this in the core ;)

**Comment by bjarnef** [comment]
@OwainWilliams I think it would be great to create a array of objects for the colors and then use ng-repeat and ng-model
Instead of button element you could use a radiobutton list with hidden radiobuttons and the color selections are the labels as in my package Color Palettes or you could use another elements like span or div with ng-repeat as in this example:
https://codepen.io/ksymeon/pen/qzAjy

It would also be great to create it as a directive, so it could be re-used e.g. as a property editor or a prevalue editor editor, incl. in grid editor settings/styles config.

**Comment by OwainWilliams** [comment]
@bjarnef - I think you might be looking at old code. It is an array of colours now. As for the directive, sounds like a good idea. One step at a time though, it's taken me ages to get this far :) 
@abjerner - good point. I'll fix the radius.

**Comment by OwainWilliams** [comment]
image

New radius on the buttons set, 3px, and added grey border on :active state.

**Comment by bjarnef** [comment]
@OwainWilliams yes, I might have been looked at some of the older commits :)
Sure, we can always create the directive later, but I think that would be useful and easier to re-use in other parts of the UI.

I am not sure how the active selection will work with darker colors.

**Comment by OwainWilliams** [comment]
@bjarnef : I like the idea of the checkmark icon. , I was also considering getting rid of the active state because as soon as the user clicks on the colour, the icons change colour anyway. Is there any need for a checkmark?

I'll read up about the directive option.

**Comment by abjerner** [comment]
@OwainWilliams @bjarnef I actually made something like that. My primary colors package has a property editor where the selected color has a checkmark:

image

Feel free to re-use relevant code ;)

https://github.com/skybrud/Skybrud.Umbraco.PrimaryColors/blob/master/src/Skybrud.Umbraco.PrimaryColors/App_Plugins/Skybrud.Umbraco.PrimaryColors/Views/PrimaryColors.html#L43
https://github.com/skybrud/Skybrud.Umbraco.PrimaryColors/blob/master/src/Skybrud.Umbraco.PrimaryColors/App_Plugins/Skybrud.Umbraco.PrimaryColors/Styles/Styles.less#L46

Although you might have the same problem with the color contrast - eg. it might be difficult to see the checkmark on the yellow color.

**Comment by OwainWilliams** [comment]
@abjerner - I could maybe put a darker outline on the checkmark to help it standout on the yellow? Thanks for the preview, I'll look at it later.

**Comment by bjarnef** [comment]
@abjerner @OwainWilliams  in the vue swatches example they have a "circle" layer behind the checkmark to solve this. https://saintplay.github.io/vue-swatches/

In the vue color example https://xiaokaike.github.io/vue-color/ they fill the svg icon color with black for only the white color option.

I think Umbraco already has TinyColor lib included, so it might also be an options to us the `isLight` or `isDark` functions for this. https://github.com/bgrins/TinyColor

**Comment by OwainWilliams** [comment]
Ok, a work in progress.
image

**Comment by abjerner** [comment]
@OwainWilliams Spot on 👍

**Comment by OwainWilliams** [comment]
Hopefully, the final amend for this PR 😄 Icons, coloured background and titles all working. 
Commented out code removed. 

colourpicker

**Comment by bjarnef** [comment]
@OwainWilliams I have created a basic directive/component for the color swatches from your code. It does however need a callback functon to set the icon font color on selection.
 
image

**Comment by OwainWilliams** [comment]
Cheers @bjarnef - I'm really new to angularjs so I'm not actually sure what you are suggesting. 😃

**Comment by bjarnef** [comment]
@OwainWilliams I few comments to your PR.

These files need to be removed from the PR.

image

image

Furthermore I can't see you are using the dependency to `ngjs-color-picker.js` and I don't think we need it for this, so it can be removed too.

Also any reason you have removed thie heading from the dialog?

```
if (!$scope.model.title) {
    $scope.model.title = localizationService.localize("defaultdialogs_selectIcon");
}
```

**Comment by OwainWilliams** [comment]
@bjarnef - Not sure where those files have come from on my PR, I'll look in to that. I guess last night wasn't the final version 😄 

I'll look at the other points you've made as well. Thanks.

**Comment by bjarnef** [comment]
@OwainWilliams the files were added in this commit https://github.com/umbraco/Umbraco-CMS/pull/2555/commits/0288378e51187ee15761ca32b52ac50f8db9eec7

**Comment by nul800sebastiaan** [comment]
Note: when we get to this PR, we'll also incorporate the sorting of the colors as requested in #2657

**Comment by OwainWilliams** [comment]
Any suggestions on how to fix the conflict?

**Comment by bjarnef** [comment]
@OwainWilliams if you merge the branches in e.g. SourceTree you can choose something like "Use Mine", "Use Theirs" or "Merge using external" tool. I use Beyond Compare as a compare/merge tool, but WinMerge should work as well and is free to use.

**Comment by OwainWilliams** [comment]
@bjarnef It's strange because my local repo says there are no conflicts.

**Comment by bjarnef** [comment]
@OwainWilliams it seems from what I can see in the changes it removes this file.
`src/Umbraco.Web.UI/Umbraco.Web.UI.csproj`

**Comment by OwainWilliams** [comment]
So, maybe take this file out of the ignore file?

**Comment by bjarnef** [comment]
Yes, I think.
I would be easiest to review if the PR only has changes relevant to this specific change.
https://github.com/umbraco/Umbraco-CMS/pull/2555/files

This isn't necessary to add for this PR:
image

and I guess you could revert this change or merge this part from `upstream/dev-v7`

image

**Comment by nul800sebastiaan** [comment]
@OwainWilliams Hold on, relax, we can look at it. :)

**Comment by OwainWilliams** [comment]
Cheers @nul800sebastiaan  - I'll wait but if you need me to do anything, let me know.

**Comment by nul800sebastiaan** [comment]
@OwainWilliams Alright mate, had a bit of a look and indeed it's a bit of a mess! 🙈 

Not to worry though. Let's just start over. The easiest thing for you to do now is to create a fresh clone of your fork in a different directory than your current clone. You'll end up with `dev-v7` as default. 

Make sure to fetch the changes from the main repository, there's [a few commands listed here that will help you get the latest changed from `dev-v7`.](https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/docs/CONTRIBUTING_DETAILED.md#keeping-your-umbraco-fork-in-sync-with-the-main-repository)

Then you can create a new branch from `dev-v7` and call it something different than your current branch, `temp-U4-11168-2` maybe, with the `-2` suffix.
Finally, start applying the same changes you made in https://github.com/umbraco/Umbraco-CMS/pull/2555/files?w=1 

I see that in the process, you've deleted all kinds of files and updated `.gitignore` - there's no need for that as far as I can tell. If you see files pop up during the commit phase that shouldn't be there, then just revert them or don't commit them. I'm not sure why you deleted the `Umbraco.Web.UI.csproj` file, that's definitely not going to work. 😉 

Note that I've recently merged a PR that affects your changes as well: https://github.com/umbraco/Umbraco-CMS/pull/2712
It would be good if you could have a look if that still works alongside your changes, it looks like it should.

Another thing I noticed in your changes is that you've collapsed some of the `less` styles. For readability, make sure to just keep them as they were.

image

We process and minify less files during the grunt build already. 😄 

I'll close this one for now. I think starting fresh with all the knowledge we have from the discussions above is going to make it very easy to implement this feature easily now by just copy/pasting the changes over!

Great work so far Owain, I tested out the changes earlier and they work wonderfully. So once you can submit a new PR, we'll be able to merge them in pretty quickly. Good times! 🎉

**Comment by nul800sebastiaan** [comment]
Oh and it would be good of you re-order the colors a little, as suggested in https://github.com/umbraco/Umbraco-CMS/pull/2657 !

**Comment by OwainWilliams** [comment]
Cheers for the feedback! I'll see if I can get on to this at lunch time and over the weekend. All makes sense. 👍

**Pull request closed without merging**
