### PR TITLE
V8: fixed type of dashboards in EditorModelEventManager

### PR DESCRIPTION
**Pull request by abjerner**
It seems that [**GetDashboard** method](https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web/Editors/DashboardController.cs#L204) was updated to return `IEnumerable<Tab<IDashboardSlim>>` instead of `IEnumerable<Tab<IDashboard>>`, but the matching logic in `EditorModelEventManager` hasn't been updated as well. As a result, the event is no longer invoked. 💣 

This PR fixes that 😉

### CODE REVIEW

**Comment by warrenbuckley** [comment]
Hi @bjarnef did you say you tested this event out?
The code at first glance looks fine but seems like the event does not get emitted.

Can you let me know if you are seeing different results.

Here is my code I used to test the implementation

```csharp
using System.Collections.Generic;
using System.Web.Http.Filters;
using Umbraco.Core.Components;
using Umbraco.Core.Dashboards;
using Umbraco.Web.Editors;
using Umbraco.Web.Models.ContentEditing;

namespace Umbraco.Web.UI
{
    [RuntimeLevel(MinLevel = Core.RuntimeLevel.Run)]
    public class DashboardEvent : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.Components().Append<DashboardComponent>();
        }
    }

    public class DashboardComponent : IComponent
    {
        public void Initialize()
        {
            EditorModelEventManager.SendingDashboardModel += EditorModelEventManager_SendingDashboardModel;
        }

        private void EditorModelEventManager_SendingDashboardModel(HttpActionExecutedContext sender, EditorModelEventArgs<IEnumerable<Tab<IDashboardSlim>>> e)
        {
            var foo = e;

        }

        public void Terminate()
        {
        }
    }
}
```

**Comment by nul800sebastiaan** [comment]
@warrenbuckley Oops, I think you were trying to mention @abjerner instead!

**Comment by warrenbuckley** [comment]
Thanks Seb, yes did mean @abjerner :-P

**Comment by abjerner** [comment]
Sorry for the lack of response 😊

I somehow missed a single line in my original commit - should be fixed here: https://github.com/umbraco/Umbraco-CMS/pull/4364/commits/0636616a6b8a1f928b5e2ce1bb8cbe8fc901658e

While testing this, I also found an issue that I didn't discover initially. Say my event would look something like this:

```csharp
private void EditorModelEventManagerOnSendingDashboardModel(HttpActionExecutedContext sender, EditorModelEventArgs<IEnumerable<Tab<IDashboardSlim>>> args) {

    foreach (var tab in args.Model)
    {

        tab.Label += "(" + tab.Alias + ")";

    }

}
```

When iterating over `args.Model`, a new collection and new tab objects are created, so changes to objects in the collection (eg. changing the label) are not persisted in the output. [Changing the collection to a list before returning it](https://github.com/umbraco/Umbraco-CMS/pull/4364/commits/4d71c5550b0eb36f30932acd94879e37a31b3ba9) seems to fix this.

Anyways, as described [here](https://github.com/umbraco/Umbraco-CMS/issues/4390), there may also be an issue with `model.Args` just being a collection of tabs, and therefore the event has no information about the the section:

> The PR should fix so that the event is now triggered, but the event has another problem, as the model is just a collection of the tabs that should make up the dashboard. As such, the model doesn't expose which section is being returned. I believe information about the section (primary the alias) being rendered would be useful.

**Comment by warrenbuckley** [comment]
Hi @abjerner 
Sorry for the delay been on holiday & this got lost in the whirlwind that was the V8 launch.

This all works fine so it's merged in.
If you think we should do something for the args to contain a reference/context to the section that it's being rendered in currently. Then feel free to open a new issue/PR for it for @sebastian-claesson & the lovely PR team to look at :)

**Pull request merged**
