### PR TITLE
Fix bug U4-6379

### PR DESCRIPTION
**Pull request by Alain-es**
http://issues.umbraco.org/issue/U4-6379

### CODE REVIEW

**Comment by Shazwazza** [comment]
This isn't the correct place to put this fix, this will only work for content, not member or media.

content, members and media use contentEditingHelper.contentEditorPerformSave to assist with saving, the fix would need to go there.

Also note, that in my experience, if you click the save button after an error and it is 'disabled', it will get re-enabled.

**Comment by Alain-es** [comment]
It happened twice so far (Umbraco 7.2.1) and we tried to click on the save button but no luck, it kept disabled. We also tried saving by pressing CTRL+S but didn't work neither. And it is very difficult to reproduce this kind of errors.

Thanks for the pointer, I will create another PR.

**Comment by Shazwazza** [comment]
You can of course also just refresh the whole page with f5 and you'll be
able to try again

**Comment by Alain-es** [comment]
We did that but all changes done by the editors were lost.

**Comment by Alain-es** [comment]
I took a look at the contentEditingHelper.contentEditorPerformSave method and saw that
you already did this (https://github.com/umbraco/Umbraco-CMS/commit/464130a1024676465de5ade9fd3d5e218e9a1ec5). So, it should work!

**Comment by Shazwazza** [comment]
So can i close this PR then?

**Comment by Alain-es** [comment]
Yes please.

**Pull request closed without merging**
