### PR TITLE
Fixes #7404 - Deadlock issue

### LINKED ISSUE #7404: Deadlock issue in 8.4
8.4 contains an issue where a thread deadlock can occur during shutdown which can lock the entire IIS application and require restarting the IIS process.

This is a regression issue.

The regression is changes made to the `RedirectTrackingComponent` in this PR https://github.com/umbraco/Umbraco-CMS/pull/6344/files

It is not obvious at all that the changes made in this PR can cause a deadlock so the actual problem lies much deeper in the codebase.

## Explanation

This will happen during an appdomain shutdown while a content/media write is occuring at the same time. The below is a timeline of 2 threads during a shutdown that will cause a deadlock:

Shutdown thread | Writing thread
------------ | -------------
_ | ContentService.SaveAndPublish
_ | Cache refreshers execute
Application initiates shutdown  | `PublishedSnapshotService.Notify`
`PublishedSnapshotService.MainDomRelease` | Writes to nucache `ContentStore.GetScopedWriteLock`
== **_storesLock** locked  | == **_wlocko** locked (lock attached to Scope which will complete later)
Try to release nucache local db files | `PublishedSnapshot.Resync` since nucache has been written
Try to acquire **_wlocko** lock | Event handler for `ContentService.Published` executes, tries reading from nucache
**waiting on lock** | Try to acquire **_storesLock**
DEADLOCK | DEADLOCK

## Problem

The problem is not the changes in the PR above, though I think this problem may have been realized in the past because the previous code for `RedirectTrackingComponent` had a lot of work arounds and perhaps by fluke it didn't re-acquire the content cache after `PublishedSnapshot.Resync` (which essentially forces a re-read of the cache the next time it's accessed). 

The real issue here is that when the content cache is referenced (done by getting a `PublishedSnapshot.Content`) and the snapshot is created, for some reason it was putting a lock on `_storesLock`. This is the same lock used when booting up and reading from the physical cache files and when shutting down to close the physical cache files. There's no reason why this same lock needs to be used for these purposes. To access the content cache, ultimately the `PublishedSnapshotService` needs to be created, it's during this creation process that the nucache files are read (locking on _storesLock), so its impossible for another thread to try to read the content cache without this first happening. Shutting down needs to lock on _storesLock because it is trying to close the same files and we can have the app both starting up and shutting down at the same time. This lock is protecting opening/closing the actual files so it doesn't need to be used when reading the in-memory nucache which causes this deadlock.

Where this lock is used however, there needs to be a different lock because in `PublishedSnapshotService.GetElements` (where this _storesLock was being used), the code reads/writes to shared resources (i.e. `_contentGen`, `_mediaGen`, `_domainGen`, `_elementsCache`) but that's easily resolve by wrapping this access in a different lock which doesn't need to relate to the physical nucache files because this information is in memory.

I will submit a PR for this shortly.

---
_This item has been added to our backlog [AB#4309](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4309)_

### PR DESCRIPTION
**Pull request by Shazwazza**
This fixes the deadlock issue raisedin #7404 as a patch fix for 8.4.1.

There will be a larger fix/refactor of much of this as part of 8.6.0 but this is the smallest change needed to address the problem for now.

Since it's not the simplest thing to replicate without some tools, I've recorded some videos showing the problem and fix.

This video shows the deadlock before the fix which occurs when requests are reading + writing + app is restarting:

https://www.screencast.com/t/UvRsH6Oz

This video shows the application working as it should without any deadlock when requests are reading + writing + app is restarting:

https://www.screencast.com/t/HocqHTCBn

This should be part of an 8.4.1 release.

### CODE REVIEW

**Comment by bergmania** [comment]
Nice videos.. The code changes is simple, and I guess we should just merge, but I'm unsure whether a `8.4.1` will ever be released or that should be `8.5.0`.

**Comment by Shazwazza** [comment]
I assume since we caused this issue in 8.4 we should release an 8.4.1 so that all cloud sites are auto patched since they will all be affected.

**Comment by fbenyah** [comment]
I know this issue has been reported fixed but keep encountering it even though I have upgraded the site to 8.5.3

**Comment by nul800sebastiaan** [comment]
@fbenyah as Shannon mentions, there's a larger fix/refactor coming in 8.6.0 which should be out in the next few weeks, so keep an eye on that one.

**Comment by appstractmeyn** [comment]
So is this fixed now? since the above mentioned release is public. https://our.umbraco.com/download/releases/860

**Comment by Shazwazza** [comment]
yes, this was released in 8.4.1 and 8.5.0 according to the labels on this issue.

**Comment by appstractmeyn** [comment]
Thanks, I was referring to @nul800sebastiaan s comment about  "there's a larger fix/refactor coming in 8.6.0" . But if you say its fixed, I guess its fixed. :)

**Comment by Rizen-Kris** [comment]
This is NOT fixed in 8.6... Still happening

**Comment by appstractmeyn** [comment]
@Rizen-Kris : I guess its pretty hard to reproduce, What I have noticed with a customers site is that it get unresponsive, but the back office still works i.e. /umbraco Could you give more details on what you notice? so that @Shazwazza can respond?

**Comment by Shazwazza** [comment]
There's a few comments referring to different things here:

* The Deadlock IS absolutely fixed in 8.4.1 and 8.5.0 
* The issue with Azure and nucache being locked if you follow all of these links and with regards to 8.6 is fixed but you have to follow the new configuration guidelines, see the updated docs https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/azure-web-apps

Please try to be as helpful as possible when reporting bugs, single line comments or comments without details explaining how to reproduce or a specific problem aren't very helpful because we aren't sure exactly what you're referring to.

**Comment by Rizen-Kris** [comment]
> There's a few comments referring to different things here:
> 
> * The Deadlock IS absolutely fixed in 8.4.1 and 8.5.0
> * The issue with Azure and nucache being locked if you follow all of these links and with regards to 8.6 is fixed but you have to follow the new configuration guidelines, see the updated docs https://our.umbraco.com/Documentation/Getting-Started/Setup/Server-Setup/azure-web-apps
> 
> Please try to be as helpful as possible when reporting bugs, single line comments or comments without details explaining how to reproduce or a specific problem aren't very helpful because we aren't sure exactly what you're referring to.

It's not fixed if in the issue you don't mention more action is needed.. Don't be a jerk :)

**Comment by nul800sebastiaan** [comment]
@appstractmeyn: 

> I was referring to @nul800sebastiaan s comment about "there's a larger fix/refactor coming in 8.6.0" 

In which I forgot to link the PR, whoops: https://github.com/umbraco/Umbraco-CMS/pull/7306

@Rizen-Kris 
> Don't be a jerk :)

I understand you might be frustrated with some missing information but there's no need for name calling.

**Comment by sbosell** [comment]
I'm not sure this is fixed. I am running 8.6.2, azure, and every time I try to bulk publish anything with more than a few items, this occurs within a few seconds:

```
Failed to publish content with id 1331
Lock request time out period exceeded. The statement has been terminated.

Exception Details
System.Data.SqlClient.SqlException: Lock request time out period exceeded. The statement has been terminated.
Stacktrace
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 272
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__31_0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 209
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass33_0`1.<Execute>b__0() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 222
   at Umbraco.Core.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryPolicy.cs:line 172
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f) in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 219
   at Umbraco.Core.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery() in D:\a\1\s\src\Umbraco.Core\Persistence\FaultHandling\RetryDbConnection.cs:line 209
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.NPoco.IDatabaseHelpers.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
   at NPoco.Database.Execute(Sql Sql)
   at NPoco.Database.Execute(String sql, Object[] args)
   at Umbraco.Core.Persistence.SqlSyntax.SqlServerSyntaxProvider.WriteLock(IDatabase db, TimeSpan timeout, Int32[] lockIds) in D:\a\1\s\src\Umbraco.Core\Persistence\SqlSyntax\SqlServerSyntaxProvider.cs:line 269
   at Umbraco.Core.Persistence.SqlSyntax.SqlServerSyntaxProvider.WriteLock(IDatabase db, Int32[] lockIds) in D:\a\1\s\src\Umbraco.Core\Persistence\SqlSyntax\SqlServerSyntaxProvider.cs:line 254
   at Umbraco.Core.Scoping.Scope.WriteLock(Int32[] lockIds) in D:\a\1\s\src\Umbraco.Core\Scoping\Scope.cs:line 492
   at Umbraco.Core.Services.Implement.ContentService.SaveAndPublish(IContent content, String culture, Int32 userId, Boolean raiseEvents) in D:\a\1\s\src\Umbraco.Core\Services\Implement\ContentService.cs:line 885
   at Umbraco.Web.Editors.ContentController.PostPublishById(Int32 id)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__15.MoveNext()
```

**Comment by LennardF1989** [comment]
@sbosell I think this is a different kind of lock issue than the one reported. I can confirm however that bulk actions in regards to `Save`-methods (and particularly when done in threads) tends to cause lock issues on the database. I feel this warrants a new issue, rather than continuing on this one.

**Comment by sbosell** [comment]
I'll create a new issue. The bulk publish throws it every time and is non
functional in the latest version of umbraco.

**Comment by Shazwazza** [comment]
@sbosell did you create another issue for this? this one is similar https://github.com/umbraco/Umbraco-CMS/issues/8392

**Pull request merged**
