### PR TITLE
Enabled localization of grid editor names

### PR DESCRIPTION
**Pull request by mittonp**
Enabled localisation of grid editor names. If no localized name exists, the grid editor will continue using the name in the package manifest.

To add localized grid editor names, create a language resource file with key grid_editorAlias.

### CODE REVIEW

**Comment by hemraker** [comment]
Awesome 🎉 Tested and it works great!

I have created an issue for it http://issues.umbraco.org/issue/U4-9636 and hopefully we can get this in during next sprint!

**Comment by nul800sebastiaan** [comment]
Hi @mittonp ! First, apologies for the long wait! I've tested out this PR and made sure that fallbacks worked as expected and custom editors could be translated too, all looked great. So I've finally managed to merge this. 

Promise we'll be a lot quicker next time you have something to contribute. Thanks for the effort, #h5yr !

**Comment by nul800sebastiaan** [comment]
Oh, and look at that shiny new Core Contributor badge on your Our profile!

https://our.umbraco.org/member/128500

**Comment by ronaldbarendse** [comment]
This 'forced' localization actually changed the names specified in the `grid.editors.config.js` to the default translations, without an option to opt-out of the translation logic! I would suggest rewriting the translation logic to be the same as in document types/properties: opt-in by prefixing the name with a dash, followed by the translation key, e.g. `#grid_rte`.

For now, 2 work-arounds exist: changing the grid alias or overwriting the translation in the `config\Lang\*.user.xml` files (in every language!).

**Pull request merged**
