### PR TITLE
Add pagination to icon picker

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9352

### Description
When having a lot of icons, either font icons of SVG icons, the icon picker can be slow and cause memory issues, because a lot of icons is rendered and filtered in the DOM. Instead we should fetch a paged list of icons, e.g. 100 per page.

### CODE REVIEW

**Comment by bjarnef** [comment]
While working at this PR I noticed we are not consistent about how to handle the following condition. Sometimes it returns an NotSupportedException, HttpException and sometimes an empty page result.

```
if (pageSize <= 0 || pageNumber <= 0) {

}
```

https://github.com/umbraco/Umbraco-CMS/blob/e9627f2ee962a73cd8c007a42845c9129e3339ee/src/Umbraco.Web/Editors/RelationTypeController.cs#L103-L106

https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Editors/EntityController.cs#L592-L595

Also here it should return the requested `pageNumber` and `pageSize` in the empty paged result instead of `0`.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Editors/EntityController.cs#L610-L614

We can look at this in another PR.
@nul800sebastiaan @Shazwazza is this something we can change and should we handle this in a standard way?

**Comment by bjarnef** [comment]
A challenge with this PR to get a paged result is that we at the moment have a second request inside the `getAllIcon()` to get legacy icons using `iconHelper.getIcons()` and concatenate these.

At the moment the icon picker is however causing memory issues, when having e.g. 1000-2000+ icons (items), which is something I have previous noticed when installing font icon packages with many icons:
https://our.umbraco.com/packages/backoffice-extensions/material-design-icon-pack/

There is a suggestion here to use `limitTo` and a load more approach:
https://stackoverflow.com/a/17350875

**Comment by nul800sebastiaan** [comment]
I don't think paging is a great experience, maybe categories ("core", whatever we ship with, "blabla set", a new named set, etc). 

We'll need to discuss first, we'll get back to you.

**Comment by bjarnef** [comment]
It could still be served as paged results, so it doesn't render e.g. 2000 DOM elements. We could either use pagination or infinite loading / load more.

Even with categories each of these could potential have many icons.

**Pull request closed without merging**
