### PR TITLE
This allows for sorting startup handlers and modifying the list of startup handlers before they execute

### PR DESCRIPTION
**Pull request by Shazwazza**
See commit notes!

The easy way to have a handler execute before others is to use the WeightedPluginAttribute and set the order to something like int.Min, but we can also get more control over the list using a special event. To subscribe to the event you could do something like this:

```csharp
    public class TestStartup : ApplicationEventHandler
    {
        static TestStartup()
        {
            ApplicationEventsResolver.Current.CollectionResolved += (s, e) =>
            {
                //here we could modify the Listof handlers,  re-sort, remove, etc...
                // e.Handlers
            };
        }
    }
```

I've used a static ctor here but you could also do it in the normal ctor of the instance (that might be better)

### CODE REVIEW

**Comment by Shazwazza** [comment]
I've updated the PR so that:

* There is no event to subscribe to but you can implement `IApplicationEventsFilter` instead to perform the filtering/ordering
* After the filtering is performed we always ensure that Core handlers are pre-pended to the beginning and those are sorted by their weight
* The WeightAttribute will publicly only accept positive numbers - so internally we could use negative

Might not be perfect but should get us to where we need to go. This will also help for things like the LinqPad provider or custom apps that need to boot Umbraco - currently I need to use lots of horrible reflection to remove event handlers that are not core since most of them fail on startup if it's not a web project.

**Comment by zpqrtbnk** [comment]
OK, been thinking and having questions about a few friction points.

- We let ppl filter the global collection of handlers but then we make sure that core-space handlers trigger before anything else. This can be confusing. We should let ppl filter only the user-space handlers _or_ respect whatever they do
- We lock negative weights by making them internal, which prevents eg Deploy from registering a "core" handler unless we InternalsVisibleTo Deploy (no!). Granted, Deploy beeing `Umbraco.Deploy` would be detected as core-space, but cannot have a meaningful weight

Proposal is to keep it as simple as possible to explain:
- Core-space handlers use negative weights
- User-space handlers use positive weights, with a default (no attribute) value of `100`
- Just so that we don't have to attribute all Core handlers (but really we should), `GetObjectWeight(handler)` returns either `-100` or `100` as the default weight (no attribute) depending on whether the handler is Core- or User-space, based upon its assembly's name
- Negative weights are not internal, anybody (inc. Deploy) can use eg `-1` - but we document that it means the handler becomes Core-space and that it is reserved for experienced users
- Courier could then use eg `-50` to run after Core handlers yet before user-space handlers

And then I'm not 100% sure we need the filter hook, but why not. Only, I'd rather let ppl do whatever they want to the list _and_ document that it is reserved for experienced users and weights should be used instead. Practically noone should use this, and those that do should have full control.

**Comment by zpqrtbnk** [comment]
And so, I have an extra commit that implements it all... depending on what you think...

**Comment by Shazwazza** [comment]
@zpqrtbnk I've fixed this all up in my latest commit - sorry I didn't see your commit so not sure what you've done.

This is pretty straight forward, see my last commit note and changes and basically allows max flexibility as per your notes above

**Comment by zpqrtbnk** [comment]
my extra commit wasn't pushed yet - waiting for your opinion - now reviewing yours ;-)

**Comment by zpqrtbnk** [comment]
Right, have merged my changes, now happy with this version. If you have a quick look that's great, then I'll merge anyways in a few hours.

**Pull request merged**
