### PR TITLE
Add IExceptionHandlerFeature check to dynamic route check

### LINKED ISSUE #13052: app.UseExceptionHandler(path) fails when path is an Umbraco page
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.0

### Bug summary

In Umbraco 10 and .NET 6, using app.UseExceptionHandler(errorHandlingPath) to display application errors (thrown exceptions) only works when the path is to a static html page. If the path is to an Umbraco content page, the Umbraco end point is never reached.

The same scenario works in a pure .NET 6 MVC web application (where the error page is a Razor view).

### Specifics

The issue occurs because <a href="https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs#L96" target="_blank">UmbracoRouteValueTransformer.TransformAsync()</a> fails to return a required `RouteValueDictionary` to the calling methods during the re-routing to our error page after an exception is thrown. The consequence of the Umbraco issue is that our error page is not displayed because .NET 6's `EndpointMiddleware.Invoke()` fails due to `HttpContext.GetEndpoint()` returning null.

The reason for the failure is that `UmbracoRouteValueTransformer.TransformAsync()` sees that there already is an `UmbracoRouteValues` instance in `HttpContext.Features`, but doesn't know that the reason for the instance being there is that we're in a re-execute of the middleware after a thrown exception. Instead it thinks "*someone else is dynamically routing and in which case we don't want to overwrite the routing work being done there*" (quote from the source code comment inside the TransformAsync() method).

The fix in Umbraco is for Umbraco's code to somehow clear the `UmbracoRouteValues` from the `HttpContext.Features` collection before the call stack reaches the `EndpointRoutingMiddleware`, or update the code in `UmbracoRouteValueTransformer.TransformAsync()` to detect that we're in an exception re-route/re-execution situation and return the correct `RouteValueDictionary`.

Middleware stack (irrelevant entries removed):

1. `ExceptionHandlerMiddleware` // Handles exceptions and updates/clears the HttpContext for re-routing to the error page
2. `EndpointRoutingMiddleware`  // Finds and assigns an Endpoint if the HttpContext.GetEndpoint() returns null
3. `EndpointMiddleware`         // If an Endpoint exists, re-processes the request for the endpoint

The `EndpointRoutingMiddleware` is responsible for re-assigning an `Endpoint` instance to the `IEndpointFeature` installed in `HttpContext.Features` after the original `Endpoint` was cleared by the `ExceptionHandlerMiddleware` (part of the re-routing to the error page). Inside the `EndpointRoutingMiddleware.Invoke()` method the following call stack is created:

1. <a href="https://github.com/dotnet/aspnetcore/blob/main/src/Http/Routing/src/EndpointRoutingMiddleware.cs#L49" target="_blank">EndpointRoutingMiddleware.Invoke()</a>
2. <a href="https://github.com/dotnet/aspnetcore/blob/53a126424ca4399ffd276b2cfe2b70db6bdde252/src/Http/Routing/src/Matching/DfaMatcher.cs#L29" target="_blank">DfaMatcher.MatchAsync()</a>
3. <a href="https://github.com/dotnet/aspnetcore/blob/53a126424ca4399ffd276b2cfe2b70db6bdde252/src/Http/Routing/src/Matching/DfaMatcher.cs#L304" target="_blank">DfaMatcher.SelectEndpointWithPoliciesAsync()</a>
4. <a href="https://github.com/dotnet/aspnetcore/blob/3ea008c80d5cc63de7f90ddfd6823b7b006251ff/src/Mvc/Mvc.Core/src/Routing/DynamicControllerEndpointMatcherPolicy.cs#L68" target="_blank">DynamicControllerEndpointMatcherPolicy.ApplyAsync()</a>
5. <a href="https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Web.Website/Routing/UmbracoRouteValueTransformer.cs#L96" target="_blank">Routing.UmbracoRouteValueTransformer.TransformAsync()</a>

A work-around is to install a middleware callback (see below) right after the call to `app.UseExceptionHandler(ExceptionHandlingPath)` and--if it is inside an exception call--clear the `UmbracoRouteValues` from `HttpContext.Features`. This middleware will then be installed in between the ExceptionHandlerMiddleware and EndpointRoutingMiddleware entries.

```csharp
const string ExceptionHandlingPath = "/error";
app.UseExceptionHandler(ExceptionHandlingPath); // Installs the custom error page
app.Use(async (context, next) =>
{
    // Detect and work around issue causing the error page not to be displayed:
    if (context.Response.StatusCode == StatusCodes.Status500InternalServerError && context.Request.Path == ExceptionHandlerPath)
    {
        context.Features.Set<UmbracoRouteValues>(instance: null);
    }
    await next();
});
```

### Steps to reproduce

1. Create a new Umbraco 10 web app, e.g. using the auto-generated scripts created by https://psw.codeshare.co.uk/ as the starting point.
2. Add a home page, a test page, and an error page using the back office.
3. In the view template for the test page add a "throw new Exception(...)" statement which will trigger the exception handling process when you navigate to the page.
4. In Startup.Configure() remove any `if (env.IsDevelopment())` clause and the `app.UseDeveloperExceptionPage();` call. Instead add a call to `app.UseExceptionHandler("/error");` and replace "/error" with your error page's url.
5. Run the app, navigate explicitly to the error page to verify that it's reachable, and then navigate to the test page to trigger the exception.

### Expected result / actual result

Expected: the assigned error page (controller/view) should be reached and displayed in the browser when an exception is thrown in the application.

Actual: Status code 500 with no content is returned to the browser. In Chrome on Windows the browser displays the following:

image

### PR DESCRIPTION
**Pull request by bramhoven**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #13052 

### Steps to reproduce

1. Create a new Umbraco 10 web app, e.g. using the auto-generated scripts created by [psw.codeshare.co.uk](https://psw.codeshare.co.uk/) as the starting point.
2. Add a home page, a test page, and an error page using the back office.
3. In the view template for the test page add a "throw new Exception(...)" statement which will trigger the exception handling process when you navigate to the page.
4. In Startup.Configure() remove any if (env.IsDevelopment()) clause and the app.UseDeveloperExceptionPage(); call. Instead add a call to app.UseExceptionHandler("/error"); and replace "/error" with your error page's url.
5. Run the app, navigate explicitly to the error page to verify that it's reachable, and then navigate to the test page to trigger the exception.

### Description
This fix solves the problem described in the issue linked above.
This allows for `app.UseExceptionHandler("/error");` being used in the `Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env)` method where `/error` is an Umbraco page. 

Whenever the a static page is used like `app.UseExceptionHandler("/error.html");` this will be handled by the `StaticFileMiddleware` which will run before `UmbracoRouteValueTransformer` is ever called.

I wondered whether it would be a good idea to add a `app.UseUmbracoExceptionHandler("/error");` to replace `app.UseExceptionHandler("/error");` and have it add a `UmbracoExceptionFeature` to the current request. That way we can specifically check for that feature in the `TransformAsync` method. But since `TransformAsync` in this case feels like a last resort I thought it wouldn't hurt to have it check for the `IExceptionHandlerFeature` there.

**Edit:**
Also running a `Clean and Format` from within Rider results in a few changes, but I cannot validate whether they are valid or not so I have not included them (yet).

### CODE REVIEW

**Comment by lauraneto** [comment]
Hi @bramhoven ,

Thank you for looking into this one! 🙌
A member of the Core Collaborators team will have a look at it soon.

Also, I see this is your first pull request to this repository. That's awesome!! Thanks again. #H5YR 🎉

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Thanks @bramhoven for this fix!

I have tested it and it now works with Umbraco pages as well as static pages, so it's ready for merge 😁

I see this is your first contribution to the Umbraco CMS, congratulations 🎉
If you provide us your account name on our.umbraco.com, @nul800sebastiaan will be very happy to assign our shiny contributor's badge to you 🥇

Thanks again, and we'll be looking forward to your next pull requests 😉

Cheers!

**Comment by bramhoven** [comment]
That's awesome! 

@mikecp my name on our.umbraco.com is `bramhoven`.

**Comment by nul800sebastiaan** [comment]
Thanks again and congrats on the `contrib` badge! https://our.umbraco.com/members/bramhoven

**Pull request merged**
