### PR TITLE
U4-8955 Copy/paste grid editors

### PR DESCRIPTION
**Pull request by lars-erik**
Copy-paste feature for grid editors. Uses local storage.
Needs CSS love and probably some indicator for copy success.
Creating PR for discussion and visibility.

### CODE REVIEW

**Comment by bjarnef** [comment]
This would be really valuable to editors, when they want to move a grid editor to another document/page, where you can't just drag & drop the editor.
Probably not a big issue for simple editors, where you just can copy/paste the text, but for e.g. LeBlender editors you have to copy/paste value of each property to a new editor on the other page.

**Comment by lars-erik** [comment]
If only som mvp who's good with css and such would give it some love. 😉

**Comment by lars-erik** [comment]
@madsrasmussen I wanted to move the paste action into the overlay, but seems it's quite challenging. It could be "transcluded" in, but the overlay directive already has an anonymous transclusion. I suspect that means quite some work to change? Wanna take a look and see if there's a better place to put the paste button?

**Comment by madsrasmussen** [comment]
@lars-erik sorry, I haven’t had time to look at this yet. Time is very limited at the moment so it will have to wait a bit. One thing I have been thinking about is: would it make sense to make it possible to copy/paste with keyboard shortcuts? When an editor is active you can use ctrl+c to copy the editor and then use ctrl+v when a group/cell is active to paste it in. It isn’t very obvious but it might be a nice addition until we get the time to have a closer look at this.

**Comment by lars-erik** [comment]
Shortcuts would be a very low hanging fruit I can see about. :) A bit unsure whether ctrl+c/v will work tho, so possibly alt+c/v?

Reg. the overlay and transclusion - if it's possible to have an "anonymous" transclusion template and then named ones, we don't have a problem. Otherwise, the button can't go in the overlay or we have to rewrite a few views. There's ~35 uses of umb-overlay I think. Just have to go through them.

**Comment by madsrasmussen** [comment]
If I remember correctly named transclusion were added in Angular 1.5 or something like that. So the version we use today (1.1.5) doesn't support it 😞

**Comment by lars-erik** [comment]
Oh man, you're right. :/

OK, I've been thinking the icon might be in the cell beside its cog. So copy is beside control editor cog and paste is beside cell cog. Plus keyboard shortcuts should be minimum viable.

**Comment by skttl** [comment]
How about this for tlc?
image

Thinking you could also enable having multiple editors in your clipboard, and accessing them through a split button / dialog. What do you think?

**Comment by lars-erik** [comment]
Sweet, @skttl. I'll try to get the keyboard shortcuts done then.
Having multiple is not a bad idea, but the item picker overlay is a bit limited. The "paste element" button could pop another one, though. It's just about "available items". But we'd need a way to clean them up. Otherwise, you'd just keep filling the list up indefinitely. 

@madsrasmussen like this?
Third option is having the paste icon by the cog in the cell...

**Comment by skttl** [comment]
@lars-erik right now I'm saving a maximum of 10 items. So on each copy, I keep the 10 latest, but remove everyone else.

I was thinking, that in a dialog you could be able to lock elements to prevent them from being deleted, meaning that you then could have 10 elements and whatever number of elements you have locked.

**Comment by skttl** [comment]
image

**Comment by lars-erik** [comment]
That's **** excellent! #h5yr!
Recently-used list is great. Way to use the components.

**Comment by lars-erik** [comment]
A colleague just noted that we should check the allowedItems for a cell before pasting too. Maybe dim the disallowed ones in the recently-used list?

**Comment by skttl** [comment]
You are right, and then also only show the button if there is any allowed elements in the clipboard.

**Comment by skttl** [comment]
Updated my PR :)

**Comment by MichaelNielsenDK** [comment]
Does one have to do anything else than install it to activate it?

I'm not seeing the copy icon, package is listed as installed, tried force refresh, clearing cookies, restarting app pool, but still nothing.

**Comment by skttl** [comment]
@MichaelNielsenDK I think the package is missing some files. I'll check up on that later.

**Comment by skttl** [comment]
Hi @MichaelNielsenDK 

I uploaded a new zip of the package, try that :)
https://our.umbraco.org/projects/backoffice-extensions/copy-paste-grid-editors/

**Comment by hfloyd** [comment]
Great work, guys! I have been missing this sort of functionality :-)

I noticed that when you have a new empty row/column, the "paste" button isn't immediately visible until you add some editor via the standard "Add content" button. I don't know if there is a way to fix that, though...

It would be ever MORE amazing if it could work for entire rows as well - that is a very common need I've come across. You have 3-5 editors added in a row (Header, text, image, etc..), and you want to duplicate that same block arrangement multiple times on the page (or another page...). A girl can dream.... ;-)

**Comment by hfloyd** [comment]
@skttl & @lars-erik I've installed this package in an Umbraco 7.7.3 site, and notice that all the content in my custom LeBlender grid editors is displaying right-aligned.
image

It seems that the css rule which is causing this is "div.tr" in umbraco.css:
image

Is something in the rewriting of the grid causing this?
Thanks!

**Comment by uniquelau** [comment]
As @hfloyd mentioned, there seems to be an extra <div class="tr"> that is not required.

@hfloyd  I have removed this extra div locally from `copypastegrid.html` (App_Plugins\CopyPasteGridEditors\) with no ill effects, however, I could not figure out how to add this update into the pull request. You should be able to do the same, and have aligned grid editors ;-)

**Comment by hfloyd** [comment]
Thanks, @uniquelau for figuring that out :-)

For anyone else interested in a local fix - the div in question is 
`<div class="tr">`
on line 114 (closing div also needs to be removed from line 248)

**Comment by lars-erik** [comment]
#H5YR, @uniquelau & @hfloyd !

If you want your name on a commit in the source, you can do it by forking my branch:  
https://github.com/lars-erik/Umbraco-CMS/tree/U4-8955  
When you've made the change, you PR it to me, and when I merge, this PR will be updated.

I think you can even manage to do it here on GitHub. :)

Otherwise, I can add it and add a big fat H5YR with a mention in the commit.

Again, thanks a lot for putting love into this. I think @madsrasmussen and @hartvig has the grid on their plate for this winter, so we'll just have to sit tight. ;)

**Comment by lars-erik** [comment]
Sadly this has fallen too far down my todo-list.
I got these events added to the grid during codegarden:
https://github.com/umbraco/Umbraco-CMS/pull/2639
The copy-paste feature should be "packageable" by using those hooks.
A custom script has to hook into those and then [angular] $compile the copy-paste directive / html and attach it to edited cells / rows.
Feel free to have a go at it. @skttl should have a package repo for it somewhere, right?

**Comment by emilras** [comment]
Thank you for your swift feedback @lars-erik. Really appreciate it!

@skttl if you have a repo we can work from, that will be really great?

**Comment by skttl** [comment]
Unfortunately not, but it is all js and html, so you can downloade the
package and work from there :)





Den tor. 27. sep. 2018 kl. 12.42 skrev Emil Rasmussen <
notifications@github.com>:

**Comment by emilras** [comment]
@skttl Thanks for replying. Great, just want to make sure we don't step on someone's toes.

**Comment by nul800sebastiaan** [comment]
Hey there @lars-erik!

I'm writing today after anouncing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far. You'll be happy to learn that @nielslyngsoe has been working on a copy/paste feature in v8 already and we're hoping this will make it in soon.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Comment by hfloyd** [comment]
FYI: For anyone who comes across this thread (from forum link, etc)... The v8 version is happening over here: https://github.com/umbraco/Umbraco-CMS/issues/6638

**Pull request closed without merging**
