### PR TITLE
Nested Content: Fix controls to be more accessible 

### PR DESCRIPTION
**Pull request by BatJan**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
I have changed the `<a>` to `<button>` and added some non-visual texts and fixed the styling.

Below is an image that indicates what controls I'm refering too - Visually it looks and acts the same as before.

nested-content-controls

### CODE REVIEW

**Comment by poornimanayar** [comment]
Thanks @BatJan you might want to resolve the conflicts here to speed up the process :-)

**Comment by BatJan** [comment]
It's been merged :)

**Comment by nielslyngsoe** [comment]
Hi @BatJan approved and merged, thanks a lot for this one, we need to get one step closer to only be using a-tags when its a link, so great getting these two corrected plus having the ability to read what the button does. :-D

**Comment by BatJan** [comment]
@nielslyngsoe You're welcome! I hope to start another batch of PR's soon as I'm going on a looong holiday soon 😉

**Pull request merged**
