### PR TITLE
Ability to add redirects

### PR DESCRIPTION
**Pull request by Matthew-Wise**
### Prerequisites
Ability to add redirects manually.  I know @marcemarc  started did this with PR 2511.

I have taken on the idea but have hit a couple of points where I need a hand.

Currently I have a add redirect on the dashboard which I can easily add to the info tab. My sticking points currently are:

The best way to validate the add request in the controller. 
 - User should be an admin or have publish rights on the target content item.

- Validation of the URL (either more in JS or controller)
@marcemarc  has a great list of checks  and questions in his code here -https://github.com/marcemarc/tooorangey.RumDo/blob/master/Solution/RumDo/App_Plugins/tooorangey.RumDo/redirecturlcheck.service.js

Whilst we work this all out Ill add a button to the info tab :)

Matt

### CODE REVIEW

**Comment by Matthew-Wise** [comment]
Hi @emmaburstow 

No problem my main challenge right now is working out what validation needs to be on the url field. As per the @marcemarc  code linked above, it would be good to get some feedback on what is considered valid.

Matt

**Comment by Matthew-Wise** [comment]
Needs some work around wording, other than that its all done. Well until someone reviews it.

Matt

**Comment by Matthew-Wise** [comment]
Thanks for the review @emmaburstow. I have updated the `can not`s :)

**Comment by abjerner** [comment]
Hi @Matthew-Wise,

Thanks a lot for the work you've done here 👍 

I've tried testing your PR, and made the following observations:

- The UI feels a bit "too big" at the moment (I've added a screenshot below for reference). For instance, the add button feels a bit malplaced.

  I think re-using the components from the content picker / MNTP would help making it look a bit smaller - and more like other parts of the backoffice.
  image

- I think the existing automatic redirects and the new manual redirects are too tight coupled together, as disabling "Url Tracker" (as we've had since the automatic redirects were introduced), would disable both parts. IMO it would be a totally valid use case to just want to disable one of them.

  As an example, [Skybrud's redirects package](https://github.com/skybrud/Skybrud.Umbraco.Redirects) works beside the build-in redirects module. So in our case, we would want to disable the new manual redirects, but not the existing logic for automatic redirects. Right now both use the same database table, so it might be difficult to decouple them. As the developer of said package, this is a major concern for me. I'm however not sure the best way to present the choice of disabling them individually 🤔 

- The URL validation feels a bit weird. For instance I'm not sure why inbound URLs are not allowed to contain a dot or a query string. For a manual redirect, this would be a valid use case.

  In my redirects package, a valid URL simply starts with with a forward slash:
https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/master/src/Skybrud.Umbraco.Redirects/App_Plugins/Skybrud.Umbraco.Redirects/Scripts/Services/RedirectsService.js#L118

  Besides perhaps preventing `#` (which we can't target on the server anyways), I think the same validation from my package would be sufficient here.

  It could however trigger a warning (but not an error) if the URL contains characters that should be URL encoded. But this is a nice to have (my package doesn't have this either).

- It may be wrong to only allow admins to add manual redirects. The way our clients use our redirects package, regular editors can add redirects as well. So perhaps there shouldn't be a check for the user's permissions?

  Ideally there should be a way to control the permissions somewhere, but that also adds another level of complexity.

Any thoughts? These are of course just my observations, so I'm not saying that's how it should be 😉

Anders, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by Matthew-Wise** [comment]
Hi @abjerner 

I agree with you on the UI feeling a bit big, Ill take a look at the MNTP see if I can find the right css classes.

I think the disabling different is a question for HQ? If we go with that we could do a similar thing with detecting packages and turning things off automatically.

The URL validation is due to the in built functionally not handling URLs with dots in the url or querystrings.

For permissions, I spoke to @nul800sebastiaan and he said to make the add functionality use the same permissions as the current functionality. 

Thanks for the full on review :)

Matt

P.S for openness I wont be able to look at this till next month :( so if someone want to finish it give me a shout :)

**Comment by andersburla** [comment]
Hi @Matthew-Wise 

Does your time look better here in May? :)

For permission, I think as @abjerner that it doesn't make sense only admins can do that. Content editors need this feature, and are most of the time not admins.

Regarding the URL validation, then the built in functionality should be refactored to support this. Would that be the responsibility of the one making the pull request, or a request to the Umbraco HQ? @abjerner @emmaburstow 

@abjerner - could it be an idea to make the Skybrud package as a pull requets for the Umbraco Core if this package does all the things needed? No reason to invent the wheel again :)

**Comment by marcemarc** [comment]
This did start out as functionality just for editors, the whole idea is that there is a type of redirect that editors need to control, quickly and simply from the back office, eg when print material goes out with the wrong url  etc and also in conjunction with the Redirects that are automatically tracked - , eg you can delete a tracked redirect by mistake, but you can't add it back in, it isn't meant to be used for ALL Redirects for ALL Urls, to manage 'functionality' - that is a different thing that would require discussion and in previous discussions there wasn't an appetite in HQ to maintain an all singing and dancing redirects package! Just install Skybrud Redirects - it is awesome! 

It's been in progress for two years, my suggestion would be to get the simplest version of the functionality into the product and review how editors are using it over time. Remember editors can currently add manual redirects anyway, they just need to rename a published page temporarily to the redirect name, then name it back, then delete the redirect they don't want! The first iteration should be to allow that 'shimmy' to just be done manually.

So if the editor has permissions to update and publish the page, this should grant them permissions to create a manual redirect.

Once this is released, then further discussion can be had over whether redirect url management functionality should 'do more' or whether we've reached a happy medium between out of the box and installing a dedicated package. This isn't the last possible ever change to redirects that is allowed to be made, but would be a great step forwards for editors!

regards

Marc

**Comment by Matthew-Wise** [comment]
All good points lets get this cleaned up and then we can discuss it further. As for the action menu I spoke to @nul800sebastiaan about adding a new permission for this which he felt was not something they wanted to add at the time.

**Comment by marcemarc** [comment]
@Matthew-Wise Yes but I think it could be on the action menu 'without requiring a new permission' it's appearance on the menu can be decided upon whether the user has Update/Publish permissions.

**Comment by Matthew-Wise** [comment]
Updated the info tab. As it was a quick thing to do. I will look at the permission and the Action menu.
Updated UI I moved the Add redirect to the right as it was becoming Ad.. on smaller screens.

image

**Comment by Matthew-Wise** [comment]
updated permissions to edit and publish only. Made the same change to the remove button at content level.

I also did a rebase which is why there is commits all over the shop now :(

Any pointers on doing the action menu?

**Comment by nul800sebastiaan** [comment]
Hey there @Matthew-Wise !

I'm writing today after announcing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Comment by Matthew-Wise** [comment]
@nul800sebastiaan if I create an issue for this feature outlining a plan would it be possible for HQ to agree a plan

**Comment by nul800sebastiaan** [comment]
@Matthew-Wise absolutely!

**Pull request closed without merging**
