### PR TITLE
Fixes: U4-7365 Content list view sorting alias is “sort” and media li…

### PR DESCRIPTION
**Pull request by clausjensen**
…st view sorting alias is “sortOrder”. This gives an ysod when changing sorting in media list views.

Changed the default list view for media to be created with the correct alias in the database.
Added migration for existing databases to be updated.

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
This is potentially a lot of data that needs updating, might be very slow. Also, what if someone added a property with the alias "sort" on their existing media types?
Would love input from @Shazwazza but I think the solution should be to detect if we're trying to sort media or content and use the correct alias.

**Comment by clausjensen** [comment]
@nul800sebastiaan We only do it specifically on the built in listview for media (which is the one datatype where its defined wrong - new ones you define it works just fine .. its just that we're inserting the wrong data in the database when we create this manually during install).

The upgrade script does it directly just on that one ID we've been inserting: https://github.com/umbraco/Umbraco-CMS/pull/952/files#diff-163846bb7df414052d27cd7aa004e897R19 (we do it only on the one with -9 as ID)

**Comment by clausjensen** [comment]
And actually if you look at the table theres already another list view in there for members, which is defined correctly (with sort instead of sortOrder) and we do not touch that one - or anything the users might have created themself.

**Comment by clausjensen** [comment]
If you look at the table theres already a itemProperties row for the built in listview for members - that one we don't touch. So anything the user might have created will not be affected either.

**Comment by nul800sebastiaan** [comment]
@clausjensen Gotcha, looks good, tested and just running one more test but it looks like this will work indeed.

**Comment by nul800sebastiaan** [comment]
Tested with existing media items, which had an existing "sort" property with data in it. Upgrade succeeds.

**Pull request merged**
