### PR TITLE
Remove statuscodepages middleware

### PR DESCRIPTION
**Pull request by patrickdemooij9**
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/11851

All information about the change, reproduce steps can be found in the issue.

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Excellent and thanks for the help @patrickdemooij9 - that works great, and what a pleasure to just be able to add `app.UseStatusCodePagesWithReExecute("/MyErrorPages/{0}");` and have it map to `/MyErrorPages/404` for a 404 error and `/MyErrorPages/403` for a 403 error and so on, didn't know this existed!

**Comment by croban** [comment]
@nul800sebastiaan this don't work for me, do I need something else, all the time I'm getting default umbraco notfound.cshtml as response ;( where app.UseStatusCodePagesWithReExecute("/Error/{0}"); must be returned or?

```
app.UseExceptionHandler("/Error/500");
app.UseStatusCodePagesWithReExecute("/Error/{0}");
...
app.UseUmbraco()
                        .WithMiddleware(u =>
                        {
                            u.UseBackOffice();
                            u.UseWebsite();
                        })
                        .WithEndpoints(u =>
                        {
                            u.UseInstallerEndpoints();
                            u.UseBackOfficeEndpoints();
                            u.UseWebsiteEndpoints();
                        });
```

**Comment by DaltonKirk** [comment]
Hi there,

I think there's an issue with:
`app.UseExceptionHandler("/error");`

If that is pointing to a an Umbraco page, a RenderController, it returns a 404, but if you navigate to that URL directly it works.

**Comment by rahulbpatel** [comment]
Seeing the same thing here as @croban.  Calling `app.UseStatusCodePagesWithReExecute("/CustomErrors/{0}")` before or after `app.UseUmbraco` is doing nothing.  I cannot get the Umbraco pipeline to re-execute.  Is anyone doing this successfully?  

Our desire is to be able to re-run the pipeline to show a custom rendered 404 page if a [custom route](https://our.umbraco.com/Documentation/Reference/Routing/custom-routes/#custom-mvc-routes) returns `NotFoundResult`.  Currently working around this by doing something like:

```
            HttpContext.Response.StatusCode = (int)HttpStatusCode.NotFound;

            var c = _umbracoContext.Content.GetById(1234);
            var templateAlias = c.GetTemplateAlias();
            return View(templateAlias, c);
```

**Pull request merged**
