### PR TITLE
refactor: Only use pooled DbContexts

### PR DESCRIPTION
**Pull request by nikcio**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

Subset of #14563

### Description

This changes the DbContext registration to only use PooledDbContexts which are much more performant.
See: https://learn.microsoft.com/en-us/ef/core/performance/advanced-performance-topics?tabs=with-di%2Cexpression-api-with-constant

To test:
At the moment it's only the delivery API that uses EFCore with OpenIddict so as long as this works we should be good.

### CODE REVIEW

**Comment by georgebid** [comment]
Thanks for the PR @nikcio! Someone on the core collaborators team will review this soon

**Comment by brannmark** [comment]
I think i have hit a problem with this commit.

Anyone tested to use the scoped in a Contentment datalist? 

Wireup in startup:
```c#
public void ConfigureServices(IServiceCollection services)
{
    services.AddUmbraco(_env, _config)
        .AddBackOffice()
        .AddWebsite()
        .AddDeliveryApi()
        .AddComposers()
        .Build();
    services.AddUmbracoEFCoreContext<CommerceContext>(
        _config.GetConnectionString("umbracoDbDSN"),
        _config.GetConnectionStringProviderName("umbracoDbDSN"),
        (options, providerName, connectionString) =>
        {
            options.UseSqlServer(connectionString);
        });
}
```

Datalist in Contentment, need to get the scoped resources like my service that is declared scoped
```c#
public class CategoriesDataListSource : IDataListSource
{
    private readonly IServiceScopeFactory _scopeFactory;
    public CategoriesDataListSource(IServiceScopeFactory scopeFactory)
    {
        _scopeFactory = scopeFactory;
    }
    public IEnumerable<DataListItem> GetItems(Dictionary<string, object> config)
    {
        var items = new List<DataListItem>();
        using (var scope = _scopeFactory.CreateScope())
        {
            var commerceService = scope.ServiceProvider.GetRequiredService<ICommerceService>();
            var dataItems = commerceService.GetAllCategories();
            foreach (var dataItem in dataItems)
            {
                items.Add(new DataListItem
                {
                    Name = dataItem.Name,
                    Value = dataItem.Id.ToString(),
                    Icon = Icon
                });
            }
        }

        return items;
    }
    ...
}
``` 

The service:
```c#
private readonly IEFCoreScopeProvider<CommerceContext> _scopeProvider;
private readonly ILogger<CommerceService> _logger;
private readonly IServiceProvider _serviceProvider;

public CommerceService(IEFCoreScopeProvider<CommerceContext> scopeProvider, ILogger<CommerceService> logger, IServiceProvider serviceProvider)
{
    _scopeProvider = scopeProvider;
    _logger = logger;
    _serviceProvider = serviceProvider;
}

public IEnumerable<Category> GetAllCategories()
{
    using (var scope = _scopeProvider.CreateScope())
    {
        var repo = _serviceProvider.GetRequiredService<ICategoryRepository>();
        return repo.GetAllAsync().Result;
    }
}

``` 

The repo constructor:
```c#
public interface ICategoryRepository : ICommerceRepository<Category>
{
}
public class CategoryRepository : CommerceRepository<Category>, ICategoryRepository
{
    public CategoryRepository(CommerceContext commerceContext) : base(commerceContext)
    {

    }
}
```

The wire up of resources:

```c#
public void Compose(IUmbracoBuilder builder)
{
	builder.AddNotificationAsyncHandler<UmbracoApplicationStartedNotification, CommerceMigrationNotificationHandler>();
	builder.Services.AddScoped<ICommerceService, CommerceService>();
	builder.Services.AddScoped<ICategoryRepository, CategoryRepository>();
...
}
```

The result when running a resource that is using the Contentment datalist is:

```
at StackExchange.Profiling.Data.ProfiledDbConnection.get_ConnectionString()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_ConnectionString()
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.get_IsMultipleActiveResultSetsEnabled()
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerCompiledQueryCacheKeyGenerator.GenerateCacheKey(Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IAsyncEnumerable<TEntity>.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at 
```

Seams like miniprofiler cant access the dbcontext in this scenario? Should I wire it up some other way or do we need to dive deeper into this issue? Can share screens if needed.

**Comment by Zeegaan** [comment]
@brannmark I think we've heard of this, heres a link to the issue (and the comment with the workaround): https://github.com/umbraco/Umbraco-CMS/issues/14893#issuecomment-1749980956

Let me know if that issue sounds like the same (and if the workaround fixes your issue) 🤞

**Comment by brannmark** [comment]
Nope, as you can see on my registration in the startup I'm doing that.
My regular api is working, so I can get items from the service when using a umbraco api controller. So data can be fetched. But the change seams to inflict on how a datalist can get the scoped contex. Maybe @leekelleher has any input on this? Running Contentment 4.5.0. Force downgrade to Umbraco 12.1.2 makes it work...

```c#
public class TestController : UmbracoApiController
{
	private readonly ICommerceService commerceService;

	public TestController(ICommerceService commerceService)
	{
		this.commerceService = commerceService;
	}
	public IEnumerable<Supplier> GetAllSuppliers()
	{
		return commerceService.GetAllSuppliers();
	}

	public IEnumerable<Category> GetAllCategories()
	{
		return commerceService.GetAllCategories();
	}

	public IEnumerable<Product> GetAllProducts()
	{
		return commerceService.GetAllProducts();
	}
}
```

**Comment by nikcio** [comment]
@brannmark Have you tried injecting the DbContext directly into a controller and checking if that has the connection string?
Just to make sure that it isn't the configuration that is causing problems here ☺️

**Comment by brannmark** [comment]
No problems running regular api controllers from Umbraco. Its because Contentment uses singleton pattern that breaks the "addscopeddb" way. Resorted to wire up my dbcontext without using the AddUmbracoEFCoreContext method and removed all IEFCoreScopeProvider to move along as I can't really be stuck with this right now. Might bite back later on.

**Pull request merged**
