### PR TITLE
Fix/delete language error message 14333

### LINKED ISSUE #14333: Deleting a language causes all related content to be deleted permanently. No recycle bin option.
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.0

### Bug summary

Is this a functional bug or missing feature?

All content related to the language you delete is gone. No way to restore. One would expect a huge warning with this explicitly written in de popup dialog. Even better would be the ability to restore the language and content!

### Specifics

image

### Steps to reproduce

1. Go to <SITE URL>/umbraco/#/settings/languages/overview
2. Click delete on the language your are going to delete.
3. Watch all content disappear :octocat: 

### Expected result / actual result

**Expected result:**

Either have a option to restore the deleted content or have a major warning that this will delete all content related to the language with the explicit message there is no way to restore the content.

**Actual result**

All related content is gone!

### PR DESCRIPTION
**Pull request by prjseal**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #14333 

### Description
Try to delete a language and see the warning message

Added extra information to the delete language warning to inform the user that it will also delete all content related to the language

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi @prjseal, 

Thanks for your PR to update the language error message!

I'll review and merge this ASAP, seems good to me 😃 

Emma

**Comment by emmagarland** [comment]
Just a quick question @prjseal 

Should we also update the en.xml and en_us.xml language files with:

`<key alias="languagedeletewarning">This will delete the language and all content related to the language</key>`

instead of

`<key alias="languagedeletewarning">This will delete the language</key>`

In case the fallback isn't used? Happy to make the change if you're in talks etc now 😃 

Thanks

**Comment by prjseal** [comment]
Hi @emmagarland 
Yes please that would be great if you could. 
we got kicked out of the hackathon space for the next event 😃

**Comment by emmagarland** [comment]
Great, have done that @prjseal. Just waiting for tests to complete and then I'll merge :)

**Comment by prjseal** [comment]
Thank you 🙏🏻 😊

**Comment by emmagarland** [comment]
@prjseal 

Thanks so much for your pull request to fix issue #14333, to make it clearer about the impact of deleting a language. 

It has now been successfully merged! 🙌

Thanks so much again for your contribution, and enjoy your Codegarden 2023 day!

**Comment by nul800sebastiaan** [comment]
Cherry picked for v10/11 in f93f3d88dae07bd5b7b565a1e7f8ff87ff7b6b6d

**Pull request merged**
