### PR TITLE
V8: Add infinite editing to datatype references tab

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

From the datatype references tab you can open the referencing types (although it's slightly broken, see #6906). But once you do so, you loose your context. And browser back doesn't get you back to the datatype you were looking at, there's some redirecting going on that prevents it.

So. This PR introduces infinite editing for all referencing types. This also includes adding member types to infinite editing (which might be a feature on its own, but hey... two for one). It works like this:

datatype-references-infinite-editing

Notice how the datatype references tab reloads if the infinite editor submits, thus reflecting any changes made to the referencing type.

### CODE REVIEW

**Comment by kjac** [comment]
Updated with latest v8/dev

**Comment by dawoe** [comment]
I saw infinite editing for member types in this PR as well : https://github.com/umbraco/Umbraco-CMS/pull/6670/

You both named in the same way so merging should be pretty easy

**Comment by kjac** [comment]
Updated with latest v8/dev

**Comment by poornimanayar** [comment]
@kjac, looks like this is a duplicate of #7211 . So I will close this PR down. Thanks for your stellar work as always!

**Comment by kjac** [comment]
@poornimanayar I don't think this is a duplicate of #7211 ... this PR adds infinite editing to the datatype references (info) tab - see the GIF

**Comment by poornimanayar** [comment]
Bad Poornima! I got confused by [6906](https://github.com/umbraco/Umbraco-CMS/pull/6906), I should have been more careful. Apologies @kjac! I ll review this one shortly :-)

**Comment by poornimanayar** [comment]
And merged :-)

**Pull request merged**
