### PR TITLE
V8: Fix alignment between dashboard headers and root nodes

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5722

### Description

As described in #5722, the tree and dashboard headers do not align, and the context menu header does not align with either of them. See #5722 for screenshots.

With this PR applied, all headers align nicely.

#### Settings tree header + dashboard header + context menu header:

image

#### Language selector + dashboard header:

image

#### Language selector + dashboard header + context menu header:

image

#### Language selector + edit content header:

image

#### Member tree header + edit member header

image

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @kjac 

Thanks for the pr. Hope you're well! What a lovely fix this is. I can imagine every detail orientated user out there taking a sigh of relief when this is in.

Em

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by kjac** [comment]
Merge conflicts resolved

**Comment by nul800sebastiaan** [comment]
Sweet, thanks very much @kjac ! 👍

**Pull request merged**
