### PR TITLE
Update PackageMigrationsPlans collection to be Weighted and not Lazy

### PR DESCRIPTION
**Pull request by warrenbuckley**
Changes `PackageMigrationsPlans` to be a weighted collection like dashboards

### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14813

### Description
This changes the PackageMigrationsPlans collection from a Lazy one to be a Weighted one.
It still loads PackageMigrationsPlans from TypeLoader for scanning assemblies for them, this will not break anything existing as PackageMigrationsPlans without a Weight attribute should have a default value of 100.

## Why?
So this allows a package to depend on another package.
For example I may decide to build a package that depends on the Umbraco Starter Kit in order to show off some functionality.

With the current approach and the type scanned assemblies, we have no way of knowing the execution order of PackageMigrationPlans will run on a blank/clean install.

With a weighted approach, I can ensure my PackageMigrationPlan is always run after by specifying a higher weight that 100 on my plan and then I can ensure that the Umbraco Starter Kit has finished installing, before I try to modify anything that it installed/setup.

## Repro
See notes from original reported issue - https://github.com/umbraco/Umbraco-CMS/issues/14813

## Notes
For reference the same issue discussed with @ronaldbarendse on Discord
https://discord.com/channels/869656431308189746/1151161117939335179/1151279287610118185

### CODE REVIEW

**Comment by warrenbuckley** [comment]
I think the API compatibility might be a bit too harsh IMO.
As mentioned above they will still be typescanned and picked up automatically, but now we have a way for some edge cases where packages might depend on another package and change the order to ensure control.

**Comment by ronaldbarendse** [comment]
@bergmania Since this is slightly breaking (it's changing the base class of the `PackageMigrationPlanCollectionBuilder`), but otherwise is a very small change, can we have this merged in for the next v13 RC?

Both Forms and Deploy are using package migrations, but we want to ensure they are executed before any regular package migration (e.g. from The Starter Kit), so Deploy can update signatures of the deployed entities and you can deploy new Forms as well...

**Comment by bergmania** [comment]
Cherry picked in `release/13.0`

**Comment by bergmania** [comment]
@warrenbuckley , thanks for the contribution. I fucked the PR up, but the commit is cherry picked and will be part of next 13 rc

**Pull request closed without merging**
