### PR TITLE
U4-11594 HasFocalPoint in ImageCropDataSet does not return correct value 

### PR DESCRIPTION
**Pull request by Bazmech**
If only one of the Left or Right values changed the HasFocalPoint function would return false but this should now return true if only one is altered

### CODE REVIEW

**Comment by abjerner** [comment]
Awesome. I see this is your first PR to Umbraco (and on GitHub in general), so thanks a lot for taking the time to do so 👍 

For now, I've only skimmed your changes here on GitHub, but it looks to do as described. I'll make sure to test your changes in the coming days. We strive to do so within 14 days, but hopefully I'll be able to so much sooner than that ;)

Anders, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by nul800sebastiaan** [comment]
Thank you @Bazmech ! Do you know how hard it is to move your mouse ONLY upwards and not left or right?! 😅😂

But I got there in the end and was not only able to verify that the logic was wrong (I agreed with the code change) but also that it actually works.

Congrats on your first contribution to Umbraco, we hope to see more of them! Now you can go admire that shiny contributors badge on your Our profile 🎉  https://our.umbraco.com/member/124663

**Comment by abjerner** [comment]
@Bazmech Congrats with your first merge and your new shiny badge 👍 

@nul800sebastiaan you know about the ruler, right?

image

**Comment by nul800sebastiaan** [comment]
Haha! Did not work..

img_20180826_215738

**Comment by Bazmech** [comment]
Love the badge @nul800sebastiaan.

I put it down to "just my luck" that I found this as it was "just my luck" that I did this and then couldn't work out why my code wasn't working for a few hours. Finally took the plunged to not only raise the issue but to also do something about it.

Looking to see where else I can help out now and hopefully put a few more PR's in.

**Pull request merged**
