### PR TITLE
add a gap between icon and label of media menu

### PR DESCRIPTION
**Pull request by mehrdadab**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes [V10 - Media Section - Create button dropdown - Fix the spacing between icons and text](https://github.com/umbraco/Umbraco-CMS/issues/12476)

- Going to the Media page
- Press Create menu
- A 15px space must exist between the menu icon and label

image

I added span with an inline style of 15px space to:
- make the gap size consistent with other menus
- Keep the change as simple as possible

### CODE REVIEW

**Comment by bjarnef** [comment]
This issue is probably a side-effect after the icon was changed to use `umb-icon` instead of `<i>` element.

Note it should be consistent here as well:
https://github.com/umbraco/Umbraco-CMS/pull/12571/files#diff-510b174a89b23d04fee9be0d5e7630829e5bdc4c880131bd54e293702c6d810fR35

**Comment by nathanwoulfe** [comment]
Hi @mehrdadab, thank you for contributing. I agree this should be fixed, and also agree with @bjarnef that we should be using utility classes rather than adding structural elements. Avoiding inline styles also helps with maintenance as changing the utility class will change all instances rather than having to find and update in multiple places.

In other buttons we use the `umb-button__icon` class on the `umb-icon` directive, which adds the spacing and also fixes the line-height. Would you mind updating?

**Comment by mehrdadab** [comment]
Hi @nathanwoulfe ,
I also agree with you and @bjarnef, but I didn't want to introduce a new class if it is not required, so I wanted to spend more time and study the current code first. Now, you gave me the clue, I try to fix it tonight (AEST time).
Cheers,

**Comment by mehrdadab** [comment]
Hi @nathanwoulfe 
Please find the change. umb-button__icon didn't resolve this issue. I used menu-label class instead. I also fixed the style of blueprints.

**Comment by nathanwoulfe** [comment]
Thanks @mehrdadab, looks good to me. I added a minor change to set the vertical alignment on the icons.

Let's get it merged.

**Pull request merged**
