### PR TITLE
Content modal heading fix

### PR DESCRIPTION
**Pull request by tiffy74**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

After merging the above PR #12702 the styling of the headings h1 in the content and create modal were styled incorrectly:

image

whereas the styling of h2's on the content groups had too much white space above and below.

image

This occurs because of a global property for H tags that applies a default lineheight for all headings.

As a result I have:

- reset the lineheight to 0 for headings that use the class .umb-group-panel__header:

```
.umb-group-panel__header h2 {
  font-size: @fontSizeMedium;
  font-weight: bold;
  line-height: 0;
}
```

- fixed the h1 styling for modals by applying the same styling that was previously applied when the element was a div:

```
.umb-modalcolumn-header h1,
.umb-modalcolumn-header h2 {
  margin: 0;
  white-space: nowrap;
  font-size: @fontSizeMedium;
  font-weight: 400;
}
```
image

Therefore I have reset the lineheight to 0 on the group headings and ensured that the styling for the content modal matches the styling it used prior to the above merge - but updated to use headings instead of div.

image

image

In order to test:

- open backoffice
- create a dummy site using doctypes with group sections such as 'content'
- Create a homepage from the root node by right-clicking
- The modal heading (h1) should now be the same size it was previously and not super huge.  This should be the case for all contextual modal headings across the sections such as in Media
- Right-click on the 3 dots on the root node to bring up the 'create' modal.  The heading should be the same as it was prior to the PR referenced above.
- Go to the editing section of the homepage and find the group headings normally called 'content'
- There should now be no whitespace above and below these headings

### CODE REVIEW

**Comment by bjarnef** [comment]
A zero line height won't work for a multi-line text in group headings.

image

image

Generally speaking line height mostly shouldn't be less than 1 depending on the font used as a multi line text would overlap the text on previous line.

**Comment by tiffy74** [comment]
Thanks that's really helpful @bjarnef 

I wasn't aware that there may be a use-case for group headings to be multi-line - hadn't even occured to me :o

I was very unsure about using line-height: 0 but couldn't initially see a reason why not - but as you say using line-height: 1 (or 1.3 as you say) actually makes more sense.

I will apply an update to this with your suggestions in the next day or so.

Ultimately I'm hoping that the rebuild of the backoffice will address these kind of issues.

Thanks for your help!

**Comment by bjarnef** [comment]
I am not sure if it possible to add a multiline text in group headings in core. Maybe with a long text although the text maybe is limited to 255 characters. It could be an issue on narror screene though.

However I know package developers have used the classes, so I would be great to ensure it still works with multiline text.

Furthermore the layout is similar to `<umb-box>` component.

Orignally I think these panels also has some classes to expand/collapse the panel. I think this still exists, but not sure if it is in use - maybe in packages section.

**Comment by tiffy74** [comment]
Have updated according to to @bjarnef 's suggestions

**Comment by mikecp** [comment]
Thanks @tiffy74 for this fix 👍 , and thanks @bjarnef  for your input on this 😁
I'm not quite sure how I managed to not notice those problems myself when I reviewed the initial PR, but it all looks fine now so let's get this correction get into 10.2 before they close the release 😅!
Cheers!

**Review by mikecp — APPROVED** [review]

**Pull request merged**
