### PR TITLE
14744 tour not coded to best practice

### PR DESCRIPTION
**Pull request by nagolucky18**
### Prerequisites

- [X] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes [14744](https://github.com/umbraco/Umbraco-CMS/issues/14744)

### Description

The following changes were made:

1. The focusLockService function is now passed into the TourStepDirective function in umbtourstep.directive.js.
2. HTML properties for accessibility were added to umb-tour.html, umb-tour-step-content.html, umb-tour-step-counter.html, umb-tour-step-footer.html, umb-tour-step-header.html. These properties include tabindex, role, and aria-label.

Prerequisites to test:

1. A screen reader has been downloaded on the PC being used to test. NVDA was used to test during development.

Steps to test:

1. From the Umbraco home page, open any tour via the right side panel.
2. With the screen reader enabled, press TAB until the dialog is reached. "Tour Dialog" should be announced when the dialog is reached.
3. Continue to press TAB. For each element, the content of the element will be announced by the screen reader.
4. When the last button is reached, press Shift + Tab to navigate backwards through the dialog. All contents should be announced by the screen reader.

Note that for certain screen readers and certain screen reader versions, the behavior may be unexpected due to a bug in the screen reader itself. Certain browser versions may also have bugs that produce unexpected behaviors with screen readers.

No unit tests were added, though I can add a few if necessary.

### CODE REVIEW

**Comment by georgebid** [comment]
Hey @nagolucky18, thanks a lot for creating a PR to fix this one, someone from our core collaborators team will review this soon. And **congratulations on your first PR!** 🥳

**Comment by nagolucky18** [comment]
@georgebid Thanks for catching this. The current implementation makes resolving this tricky. Currently the HTML "inert" property is added to the mainwrapper div, however this makes all children of mainwrapper inert. This cannot be overriden. To that end, "aria-hidden" would also not work since that too cannot be overridden.

Selecting only specific nodes to apply "inert" to would work, but might be difficult to do. I can take a look at implementing something like that.

**Comment by georgebid** [comment]
Sorry for the delay @nagolucky18, but yes, I didn't think it would be the easiest fix, I think I will double-check this with HQ or maybe the accessibility team to see if going with your solution would be the best option, as I do think it's an improvement compared to the current. I will get back to you soon 😄

**Comment by georgebid** [comment]
Hey @nagolucky18, once again, thank you for your patience! I've spoken internally regarding this PR, and we are happy that your fix is definitely an improvement, regardless of what I had flagged. Therefore, I will merge this one in 😸 Thanks again for fixing #14744, you should see this in the next release.

**Pull request merged**
