### PR TITLE
Added dictionary import/export

### PR DESCRIPTION
**Pull request by Lantzify**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

I tend to work with dictionaries. And as of right now there is no simple to export dictionaries from1 site to another. By being able to export and import dictionaries you can easily export default dictionary such as "cookie consent", "read more" etc etc. And then import them to the desired site.

Back in Umbraco 8. You would have to create a package and then install it on the desired site. But I noticed that if you have a well organized dictionary list and then install them. All items would end up in the root. (I don't know if this is happening in. Umbraco 9)

------

Just finished making it work on v10/contrib @mikecp 😄

### CODE REVIEW

**Comment by mikecp** [comment]
Great @Lantzify, thanks for doing this so quickly !! 👍
I'll have a look at this PR asap 😁

**Comment by Lantzify** [comment]
Thank you @mikecp! I am however a bit unsure how to fix the check "Uncontrolled data used in path expression" 😅

**Comment by mikecp** [comment]
Ouch indeed 😅
By the way, I was interrupted while reviewing a few days ago, so maybe it's best that I give you a sign when I'm done reviewing it all 😉

**Review by mikecp — CHANGES_REQUESTED** [review]
Hey @larssg ,
I'm finished checking your PR, it al works and it's a really great addition!! 👍
Thanks!!🎉

I left a few comments for you to check and/or discuss, and I also have two main comments:

-  On the screen where you display the dictionary items that are about to be imported, it could be nice to see some hierarchy level between a parent and its children. For the moment, they are all at the same indentation level and I am wondering if this could not become confusing once you try to import big trees of dictionary items.

image

It is not super important, but if somehow it's not too complicated for you to do, I think some indent would be cool 😁

- The import is done only at main root level, which means the imported items will not necessarily be created at the same place they were exported from (we lose the parents if there were any).
I can follow the logic that you don't always want to import them at the same place, and since we now have a "move" action, it's easy to move it afterwards 😉, but maybe this should be mentioned somewhere in the flow, e.g. on the last screen, something like "The following dictionary items have been imported under your dictionary root, you can now move them to their final destination if necessary".

image

It could be a nice extra if it was possible to directly select the desired destination from there, so avoiding the need to initiate a "move" action manually, but again it's certainly not necessary if it's too long to integrate.

Ok so I got a little enthusiastic maybe 😁 Looking forward to your thoughts on all this, but to summarize, I guess the main/necessary take away would be the addition of a comment about the fact that it's imported in the root. The rest is nice-to-have if it's not too complex.

Cheers!

**Comment by mikecp** [comment]
Oh, and also, I will try to get HQ's thoughts on those "Uncontrolled data used in path expression" issues.

**Comment by Lantzify** [comment]
Hi @mikecp! I think you tagged the wrong person there 😅 
But I Love the idea! I made a draft of it (might need some polishing).
Capture

What do you think? 😃

**Comment by mikecp** [comment]
Hi @Lantzify ,

I finally found time to run and test your changes. They're great! 👍

If I may make two last "polishing" suggestions:
- I think the label on the destination tree should be customized to "Chose where to **import** dictionary items..." instead of "Chose where to **move** dictionary items ..." But I don't know if it's easy to do since you probably took the component from the "move dictionary item" functionality.

- The indenting on the last screen for imported dictionary items should be the same as the one on the first screen. For the moment there is no indenting on that last screen:

image

But like I said, this is really polishing, so no worries if not doable   😉

Cheers!

**Comment by Lantzify** [comment]
Hi @mikecp! I changed the label and I indented the dictionaries on the last screen. 😃

**Comment by mikecp** [comment]
Hey @Lantzify ,
Great, I'll have a look soon 👍
I've been a little quite lately because I am finalizing my Codegarden session "The Umbraco PR Show" which I will present on the 17th (Friday) morning.

Actually, if that is OK with you, I would like to use your PR as example during that presentation on June 17th (this is why it has been tagged "CG22 Candidate"), so I will keep your PR open until then. Let me know if that is a problem for you, then I will remove the tag and finalize this PR 😉

Cheers!

**Comment by Lantzify** [comment]
Hi @mikecp!

It's no problem for me at all! But you gotta let me know how it went! 😄

Good luck with your Codegarden session! 🥳

**Comment by mikecp** [comment]
Hey @Lantzify ,

Thanks! I'll keep you up to date 😁!!

**Comment by mikecp** [comment]
Hi @Lantzify,

Thanks again for this great addition to the dictionary 👍
Your PR has just been merged live from CG22 🎉

Looking forward to your next addition to the dictionary 😉

**Pull request merged**
