### PR TITLE
Add unique id for TextSearch / LuceneSearch

### PR DESCRIPTION
**Pull request by bjarnef**
Add unique id for TextSearch / LuceneSearch for each searcher.

http://issues.umbraco.org/issue/U4-6748

### CODE REVIEW

**Comment by Shazwazza** [comment]
thx!!

**Comment by bjarnef** [comment]
@Shazwazza maybe this could merged (or just manually added) in Umbraco 7.2.8? :)

**Comment by Shazwazza** [comment]
Sorry mate, we're too late with testing today to get 7.2.8 out,

**Comment by Shazwazza** [comment]
Ok, we're slightly delayed so have pulled this in

**Pull request merged**
