### PR TITLE
Backoffice Italian localization improvements

### PR DESCRIPTION
**Pull request by jacktric**
### Prerequisites

Fixed issue: https://github.com/umbraco/Umbraco-CMS/issues/10305

### Description

Added missing keys in the it.xml localization file used for the default Italian backoffice language.

### CODE REVIEW

**Comment by mikecp** [comment]
Hello @jacktric , thanks for your first contribution to Umbraco!
This is a nice update for all Italian speaking editors of Umbraco 👍 

Before merging, I wanted to check with you if you had intentionally updated the package-json.lock file as well, or if it was some kind of "automatic magic" that had happened along the way and could be reverted. Just to avoid making unnecessary or unwanted updates.
Thanks!

Michaël.

**Comment by jacktric** [comment]
> Hello @jacktric , thanks for your first contribution to Umbraco!
> This is a nice update for all Italian speaking editors of Umbraco 👍
> 
> Before merging, I wanted to check with you if you had intentionally updated the package-json.lock file as well, or if it was some kind of "automatic magic" that had happened along the way and could be reverted. Just to avoid making unnecessary or unwanted updates.
> Thanks!
> 
> Michaël.

Hi Michael,
I didn't change the "package-json.lock" file intentionally. 
Visual Studio changed it by itself so this file could be reverted.

Christian

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Hi @jacktric ,
Thanks, I reverted the package-lock.json file, so we can merge now 😀

Thank you for your first contribution to Umbraco. I hope this is the first of many  😁

And as new contributor, @nul800sebastiaan will be happy to assign you our contributor badge !! 👍

**Comment by nul800sebastiaan** [comment]
Thanks for the help @jacktric and congrats on your brand new contributor badge! https://our.umbraco.com/members/id:274534/ 🎖️

**Pull request merged**
