### PR TITLE
#5294 Full path for DocType on Nested Content configuration

### PR DESCRIPTION
**Pull request by skartknet**
Please refer to #5294 for more details.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @skartknet 

Thanks for the work and for suggesting the changes in the first place. Looks like a wonderful piece of work - we'll take a good look and let you know if we need anything else from you.

Emma

**Comment by poornimanayar** [comment]
Hey @skartknet ,

Can you fix the conflicts on this PR so that one of us can review? Looks like a great addition.

Poornima

**Comment by skartknet** [comment]
Thanks @poornimanayar, it looks like checks are passing now.

**Comment by poornimanayar** [comment]
Hi @skartknet,

I gave this a quick look and I can see that the modal is working well. The selector for the element types looks ace! Great work! I think this has really given the selector for NC a good overhaul and it brings consistency. 

I think it definitely can do with the extra metadata to show the full path for doc types to fix the original issue in question but this seems a step in the right direction. 

image

Regards,
Poornima

**Comment by skartknet** [comment]
You're right, I didn't address the original issue :(  . I have been trying to find the full path of the elements but it seems that the object returned by the Nested Content Controller doesn't have that property in the returned models. I tried to find a way to get it but it's complicated as it reaches the internal services if I want to do it right? Maybe you know some helper that returns the DocTypes path as a breadcrumb?

**Comment by poornimanayar** [comment]
Hey @skartknet ,

So sorry, I should have made my comments clearer. Apologies if I sounded rude.

What I meant was that you probably need the metadata as mentioned [here](https://github.com/umbraco/Umbraco-CMS/issues/5294#issuecomment-489126601) to address the original issue in question. But the modal is good to go, so may be we can merge this and address the full path of the doc type in the modal in a separate PR. @nul800sebastiaan , @nielslyngsoe , can you confirm? 

@skartknet , top job getting the modal working well. It works really well :-)

Poornima

**Comment by skartknet** [comment]
You didn't sound rude at all! All good. Let me know in case this needs any more changes.  Cheers.

**Comment by skartknet** [comment]
Hey all, should I check those conflicts again? I already resolved them a month ago. I think new changes are done to the v8/dev and this PR gets outdated.

**Comment by poornimanayar** [comment]
Yes @skartknet, if you can that will be good. Yes, if there are changes that affects the files you have changed it can end up in merge conflicts.

**Comment by nul800sebastiaan** [comment]
Hi @skartknet and a big "High five, I suck!" for not giving this PR any attention yet, I'm sorry.

You might be able to get some inspiration for the fix done that addresses the original issue: https://github.com/umbraco/Umbraco-CMS/pull/6092

This displays the alias of the doctype (which must be unique) next to the name if there is more than 1 doctype with the same name.

**Comment by skartknet** [comment]
Haha, that's fine, I forgive you ;P

I'll take a look at that fix, it looks interesting. Should we abandon this PR then or we are going ahead with the modal?

**Comment by nul800sebastiaan** [comment]
The fix in 6092 does get us quite a bit further, but it would still be really nice to have the modal so we can easily see more context, like the icon and color. 

I know that @nielslyngsoe had plans to update that modal with doctype folders as well before he left on paternity leave. Maybe he can pick that back up now that he's back.

**Comment by skartknet** [comment]
I have merged the changes from #6092 . Modal is displaying the alias and filtering the selected elements. Come on team, we are almost there! 🎉

**Comment by nielslyngsoe** [comment]
Hi @skartknet, looking good.
I will be approving this, but I do think we visually need to correct a few minor things.

I would love it to look like this:
image

So the Element Type picker should only be display as a placeholder when nothing is picked, as soon an ElementType is picked its should change look, to a solid border. Hence its not a placeholder but something actually took that place.

To look like other placeholders, the placeholder text should be center aligned. Plus we need to be aware about how we spell Element Type, it's important that it's with capital E and T, since it's the name, not just the words.

We also should make sure that the Element Type picker is the same height as the other inputs, i would change padding to 6px 4px. And decrease the margin between icon and name of a picked Element Type.

I hope that makes sense, thanks for this great addition. I'm looking forward to get this, It will make it much nicer to configure Nested Content.

Thanks!

**Comment by nul800sebastiaan** [comment]
Thanks for the review @nielslyngsoe - are you up for making a few more suggested changes @skartknet? Would be awesome if you could and then we can wrap this up! Love the work so far! 👍

**Comment by skartknet** [comment]
Sure thing.  I'll do the changes.

**Comment by skartknet** [comment]
Thanks for the feedback @nielslyngsoe , it's looking better now. All the changes are up.

**Comment by skartknet** [comment]
Hey team, the PR is conflicting again. This was open in May. If you think you are going to eventually merge the PR before V9 is released I can fix the conflicts again. But I just really don't want to waste more time in something that might not be of value.

**Comment by nielslyngsoe** [comment]
Hi @skartknet, I'm happy, I will push for someone to review. Thanks

**Comment by nul800sebastiaan** [comment]
Thanks @skartknet - we're definitely still interested in this! There's something strange going on with these merge conflicts though, which I tried to resolve, but they are still there after resolving them. I am investigating since I see this problem on other PRs as well, very weird. So no need to take action on your end!

**Comment by nul800sebastiaan** [comment]
Yay! This has finally been merged now, once again sorry for the wait @skartknet !

This works great, only gives us the alias of the element type of there's one with a duplicate name, gives good context with the icons as well and overall is a great experience.

The only thing we're missing is that when you click "Add" you should immediately be able to select an element type, instead of then having to click "Select Element Type", so maybe you'd like to throw in a small additional PR for that?

Thanks so much and thanks for your patience! ⭐️

**Comment by skartknet** [comment]
Awesome! Thanks! Yes, I'll create a new PR for that.

**Pull request merged**
