### PR TITLE
U4-6873 - Remove the hardcoded .jpg thumbnails

### PR DESCRIPTION
**Pull request by TimoPerplex**
This pull request removes the hardcoded .jpg thumbnails and uses the image original extension to create the thumbnail.
Because we now use the original extension the image is no longer masked as another (extension is .jpg but the file is actually a .png)

This fixes issues with Internet Explorer used in combination with the no-sniff header.
Ref topic: https://our.umbraco.org/forum/umbraco-7/using-umbraco-7/66788-adding-nosniff-header-breaks-png-images-in-internet-explorer

### CODE REVIEW

**Comment by Shazwazza** [comment]
Thanks, can you please create an issue on the tracker and link it here please ?http://issues.umbraco.org/

**Comment by JeffreyPerplex** [comment]
Related issue: http://issues.umbraco.org/issue/U4-6873

**Comment by TimoPerplex** [comment]
Hi,

Any update on this pull request? I'll be at the hackathon next Thursday at the Umbraco UK festival and can answer any questions you'd might have.

**Comment by nul800sebastiaan** [comment]
Thanks! I made it so it would still also produce the jpg file in case people have hard coded that somewhere so now it's backwards compatible. All the helper functions that you've changed still return the proper file extensions so most people will be using the correct file, hopefully. :)

**Comment by JeffreyPerplex** [comment]
Perfect!

**Comment by nul800sebastiaan** [comment]
@JeffreyPerplex You'll be happy with this one too: https://github.com/umbraco/Umbraco-CMS/pull/942

**Pull request merged**
