### PR TITLE
Improved punctuation and sentence structure for better readability.

### PR DESCRIPTION
**Pull request by Programeerik**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
I've improved punctuation and sentence structure for better readability.

_The sentence before fix_
BeforeFix

_The sentence after fix_
AfterFix

To test: Run the solution, start the tour of getting started and the sentence is now more clear and correct.

### CODE REVIEW

**Comment by mikecp** [comment]
Hi @Programeerik ,

Thank you for this update 👍 It makes the text more readable indeed. May I maybe ask an extra change: to be coherent with the rest of the written text (e.g. last sentence), I would also replace "you'll need" by "you will need". What do you think?

Cheers!

**Comment by Programeerik** [comment]
Your idea is indeed more coherent. I'll commit the new text.

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Thanks @Programeerik for the quick update!

I think we're ready to merge then 😁
I see this is your first contribution to the Umbraco-CMS, congratulations 🎉
If you send us your user name on our.umbraco.com, @nul800sebastiaan will surely be happy to assign our shiny contributor's badge to you 🥇

And now we'll be looking forward to your next PR's 😉

Cheers!

**Comment by Programeerik** [comment]
@mikecp Thanks! 🎉 I've created an account at our.umbraco.com and linked my Github account. 
https://our.umbraco.com/members/Programeerik/
Is this enough information for @nul800sebastiaan or do I need to message him?

**Comment by mikecp** [comment]
That's perfect @Programeerik 👍
You might need to wait a little because I know he's been quite busy lately. Oh, let me ping my teammate @busrasengul who can also do this I think 😁

**Pull request merged**
