### PR TITLE
v8: Moved the accessibility texts into visuallyHidden

### PR DESCRIPTION
**Pull request by RachBreeze**
This PR moves the accessibility texts  created in #6315 and #5760 into the visuallyHidden section, following @BatJan conventions

### CODE REVIEW

**Comment by poornimanayar** [comment]
Thanks yet again @RachBreeze !

**Comment by RachBreeze** [comment]
Hi
I guess the merge conflicts are blocking this?  Would you like me to review them?
Thank you in advance
Rachel

**Comment by poornimanayar** [comment]
Hi @RachBreeze ,

Apologies for the delay in review. We are still ploughing through the backlog. Yes, if you can fix the merge conflicts I will get it reviewed for you :-)

Poornima

**Comment by RachBreeze** [comment]
Hi @poornimanayar 
No worries, thank you for getting back so quick :-)
I've taken a look at and merged the two conflicting language files.  If there's anything else I can do to help please let me know
Cheers

**Comment by poornimanayar** [comment]
Hi @RachBreeze ,

Can you add some notes on how I can test this?

Poornima

**Comment by RachBreeze** [comment]
Hi @poornimanayar 

Happy New Year! So sorry for the slow reply, Christmas and illness got in the way. 

I moved a number of translations from the placeholders section in the language files to the visuallyHiddenTexts section.  

As part of the move I've renamed 3 of the items as follows as part of the move:

- `a11yCreateItem `is now `createItem`
- `a11yEdit `is now `edit`
- `a11yName `is now `name`

In terms of testing the texts are hidden visually, and show on a screen reader when tabing through the header directive, for example when the user is editing content as shown below 
image

This change impacts the umbeditorcontentheader directive and the umbeditorheader directive.  It can't be seen visually, only be a screen reader users, for example when editing content the screen reader says "Name edit required"
And when creating a new content item the screen reader user hears "xxx name edit required"
Where xxxx is the name of the content item being created

This PR doesn't change any existing functionality, it just ensures that the naming conventions introduced by @BatJan are followed

I hope this helps

Rachel

**Comment by kjac** [comment]
Merged 😄

**Comment by RachBreeze** [comment]
@kjac you're welcome and thank you too

**Pull request merged**
