### PR TITLE
V8/Warn editor when deleting a media item that is in use

### LINKED ISSUE #8693: Warn a editor when deleting a media item that is being used
This is part of #8679

We need to warn a editor when he is trying to delete a media item using the context menu in the tree or the actions in the top left corner. 

The dialog shown should warn the editor that the item or one of its' descendants (in case of folder deletion) is in use.

Depending if the current item or one of the descendants is in use the message should differ to make that very clear to the user.

For testing it should be tested with and without variants enabled

### PR DESCRIPTION
**Pull request by dawoe**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #8693

### Description
This PR introduces a warning to editors when they try to delete a media item or folder in the media section when the item or one of the underlying items of a folder is in use.

delete-warning

### Note for reviewers
This PR builds on top of PR #9116 so it's recommend that that one is reviewed and merged first.

### Steps to test

See steps for media in #9116. When you try to delete the item a warning is shown + information of the references.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @dawoe 

Thanks also for this 👍  We'll shout if we have questions,

Em

**Comment by nielslyngsoe** [comment]
@dawoe YES YES YES! This is so great, thank you! :-D

**Review by poornimanayar — COMMENTED** [review]
Hi @dawoe ,

I started reviewing this. But the minute I check this branch out I am getting xml errors by line 2320 in `en_us.xml`. I think its due to the merge conflicts. Can you check and resolve them? I dont want to break things by attempting it myself. 


Poornima

**Comment by dawoe** [comment]
I see there is a merge conflict. Will see if I can resolve this

**Comment by dawoe** [comment]
Hi @poornimanayar 

The merge conflicts are resolved

**Comment by nielslyngsoe** [comment]
@dawoe I see this Branch/PR is using the same code as https://github.com/umbraco/Umbraco-CMS/pull/9125

Can I ask you to port back those changes? so they use the same approach? (or merge them, how you like.)

If any trouble let me know, I will be available.

Thanks in advance.

**Comment by dawoe** [comment]
@nielslyngsoe changes haven been merged in to this one

**Comment by MushuPlatypus** [comment]
How is it going with PR?  Has the functionality been added to the main branch yet?

**Pull request closed without merging**
