### PR TITLE
U4-8143 - MNTP (content picker) does not set $dirty

### PR DESCRIPTION
**Pull request by villian**
- I have fixed an issue - http://issues.umbraco.org/issue/U4-8143

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @villian ,

Thank you for your PR. We shall review and let you know of the outcome in the next 14 days, probably earlier.  

Are there any steps to reproduce this and see this in action? Please let me know!

Regards,
Poornima, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by poornimanayar** [comment]
Thank you @JoseMarcenaro 

@villian I have tested the changes and it looks good :-) Definitely an improvement and a nice little bug fixed.

Poornima

**Comment by JoseMarcenaro** [comment]
@poornimanayar , thanks for your quick response to this.

By the way, the same bug affects the latest (alpha) version of Content.MediaPicker in Umbraco v8.
I'm testing at the current HEAD of the temp8 branch (commit  2ae9405f dated today)

Is it useful that I report the bug and/or propose a PR for that branch? Or it is "out of bounds" for now?
I don't want to mess with the incredibly complex process of developing a new major version.

**Comment by poornimanayar** [comment]
Hi @JoseMarcenaro ,

I think any bug fixes merged into v7 will automatically make it to v8. @nul800sebastiaan is that correct?

Poornima

**Comment by nul800sebastiaan** [comment]
Thanks very much @villian! And congrats on your first contribution to Umbraco CMS, that's awesome! 🏅 

A few tips for future contributions:

- To make it easier for everyone to read and process your PR, make sure to give the PR a good title, it's fine to use the same title as the issue on the tracker. That's much easier to comprehend than just an issue number
- Make sure to fill in the pull request template which asks for a link to the issue on the tracker
- The other thing the PR template asks for is steps on how to test if it's fixed, if you provide those immediately then we don't have to ask! 👍

That said, this fixed the issue wonderfully and you've earned that shiny new contributor badge on Our Umbraco! https://our.umbraco.com/member/15719 🎉

**Pull request merged**
