### PR TITLE
Bugfix for #10927 - Body steal focus when opening folder overlay

### LINKED ISSUE #10972: Body steal focus when opening folder overlay
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

8.16.0

### Bug summary

When creating a new folder under e.g. document types, media types or datatypes, the inout field have `umb-auto-focus` directive, however it seems something steal focus and set active focus on body element.

t2I7W6TQRy

### Specifics

_No response_

### Steps to reproduce

Create a new folder in e.g. document types, and notice the input doesn't get focus.

In Chrome use the following to see which element currently has focus: https://developer.chrome.com/docs/devtools/accessibility/focus/

I can reproduce this issue in v8.15.1 as well and back to v8.8.0.

### Expected result / actual result

_No response_

### PR DESCRIPTION
**Pull request by BatJan**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #10972

### Description
When creating a folder under "Settings -> Document types" the input field for the name that appears don't get autofocused. I suspect it's due to the section containing the input element is hidden using `ng-show` instead of `ng-if` making the autofocus directive compete with all other places this directive might have been used and also settled on the element to focus on before the dialog for naming the folder appears. Changing it to use `ng-if` instead makes the directive run and set focus again.

**Before**
focus-issue-before

**After**
focus-issue-after

### CODE REVIEW

**Comment by bjarnef** [comment]
@BatJan I think it was also an issue when creating a folder under media types.
https://github.com/umbraco/Umbraco-CMS/blob/23675a33ee2383cf7ceef38cc2d4942c46e3ee6c/src/Umbraco.Web.UI.Client/src/views/mediatypes/create.html

The part with `ng-show="!model.creatingFolder"` and `ng-show="model.creatingFolder"`

**Comment by BatJan** [comment]
@bjarnef Yes it indeed is - I'm going to push shortly. Just need to figure out an issue with the view for https://github.com/umbraco/Umbraco-CMS/blob/23675a33ee2383cf7ceef38cc2d4942c46e3ee6c/src/Umbraco.Web.UI.Client/src/views/datatype/create.html where I see a "Autofocus processing was blocked because a document already has a focused element" after making the change... So need to figure that one out before comitting the extra changes - But good spot 🙌🏻

**Comment by BatJan** [comment]
@bjarnef Ok, found it - Turns out that for some reason the native `autofocus` attribute was being used instead of the `umb-auto-focus` directive in the view for the datatypes dialog 😁 

But should be all good now 👍🏻 Let me know if you spot anything I might have missed - Have been checking all the create.html views I could find.

**Comment by bjarnef** [comment]
@BatJan yeah, I also noticed one dialog using the native `autofocus`. while others used `umb-auto-focus` and wondering why it didn't use same attribute :)

**Comment by BatJan** [comment]
Oh dear - The changes I though I pushed for this PR ended up in an old branch doh! 🙈 All good now!

**Comment by nul800sebastiaan** [comment]
Awesome, thanks for the help @BatJan and @bjarnef ! 👍

**Pull request merged**
