### PR TITLE
feat: Added support for custom languages

### PR DESCRIPTION
**Pull request by nikcio**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/discussions/14736

### Description

This PR adds the possibility to add your own custom language iso codes in the Umbraco UI.

See the discussion for more info.

To test try creating different languages. Available and not available.

New UI:
image
image

Examples of custom languages and their default naming:
image
image

### CODE REVIEW

**Comment by mikecp** [comment]
Hello @nikcio ,

Thanks for this update, someone from the team will have a look at it soon!

Maybe a preliminary question 😉 : did you see the comment of @bergmania in the discussion and were you able to do some testing on Mac/Linux + verifying dat/time formats? Just to give us some insights of what we need to test ourselves 😁

Thanks and cheers!

**Review by mikecp — CHANGES_REQUESTED** [review]
Hello @nikcio,

I just had a first quick look at the changes and I noticed that all the new text displayed are hardcoded in English.

I guess that in a culture-related PR it might be best to replace them by translation labels in there 😁 Thanks!

Cheers!

**Comment by nikcio** [comment]
Hey @mikecp 
I've added a Unit test to test the differences between platforms. I will remove this after we hear what @bergmania thoughts are here: https://github.com/umbraco/Umbraco-CMS/discussions/14736#discussioncomment-6871847

I've also tried localizing the hardcoded english strings but I don't think the `localize` tag works inside the `option` tag for some reason?

**Comment by mikecp** [comment]
Thanks for the update @nikcio 👍

Strange on that options translations, I'll have a look.

**Comment by nul800sebastiaan** [comment]
Hey there @nikcio - thanks for the help here. As noted in [the related discussion](https://github.com/umbraco/Umbraco-CMS/discussions/14736), we're not keen on adding this feature as it is an edge case. 

By coincidence I found today that it is possible to achieve (I think) the same with [2 lines of code](https://discord-chats.umbraco.com/t/16320837/how-to-add-custom-languages-to-the-add-language-dropdown-in-): 

```csharp
var lang = new Language("da-GB", "Danish (Great Britain)");
_localizationService.Save(lang);
```

Additionally, we're in a phase with project Bellissima (also known as the new backoffice) where we want to start wrapping up a Bellissima beta version to ship some time "soon". This means we need to implement a feature freeze on the current backoffice so that we don't keep increasing the scope of Bellissima.

As a general rule from now on, we're still happy for features in C# but anything that gets introduced or refactored in AngularJS probably won't make it. Bugfixes are still great of course!

**Pull request closed without merging**
