### PR TITLE
added finish button so page only reloads after user input. also added…

### PR DESCRIPTION
**Pull request by rjabreu**
added finish button so page only reloads after user input. also added localization for en/en_us

### CODE REVIEW

**Comment by clausjensen** [comment]
@rjabreu Hi Ricardo - could you please link this PR to an issue on the tracker (or create an issue for it if it isn't already there?)

http://issues.umbraco.org/

Thanks !

**Comment by rjabreu** [comment]
@clausjensen just added comment of fix on the issue. you can see over -http://issues.umbraco.org/issue/U4-9036. Let me know if there is any more necessary steps to take.

Thanks,

Ricardo

**Comment by clausjensen** [comment]
@rjabreu Thank you very much :) I think we're good from here!

**Comment by warrenbuckley** [comment]
Code looks great @rjabreu and I am happy with this our designer @madsrasmussen may tweak this slightly after this merge (perhaps button color?)

But thanks for submitting this PR at the UK Fest hackathon & keep up the good work & submitting more PRs in the future 👍

**Comment by rjabreu** [comment]
@warrenbuckley  thanks a lot. being my first PR ever, I am really happy to read your feedback. I certainly agree some other things can be improved and will try to contribute more. cheers!

**Pull request merged**
