### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vyaspranjal33**
added LICENSE badge

### Prerequisites

- [ ] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is:
- [ ] I have added steps to test this contribution in the description below

### CODE REVIEW

**Comment by vyaspranjal33** [comment]
@nul800sebastiaan please review

**Comment by abjerner** [comment]
@vyaspranjal33 congrats on your first PR for Umbraco 🎉 

However please consider that it's weekend. Our goal is the review new PRs within a period of 14 days 😉

As for the badge, I'm not entirely sure why it's needed. Can you perhaps elaborate a bit about your reasons for adding it?

From what I can tell, the license badge is far from standard in other open source repositories, and GitHub already has a built-in way to show the license type:

image

Anders, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by vyaspranjal33** [comment]
@abjerner its good to have a License badge in Project Readme, i hope Team Umbraco Understand reason behind adding badge

**Comment by vyaspranjal33** [comment]
@nul800sebastiaan  whats your thought on this

**Comment by vyaspranjal33** [comment]
@emmaburstow please give your suggestion this

**Comment by nul800sebastiaan** [comment]
@vyaspranjal33 I agree with @abjerner - this is already part of the github interface. Thanks though!

**Pull request closed without merging**
