### PR TITLE
Introduce interfaces to allow customisation of NuCache v2

### PR DESCRIPTION
**Pull request by nzdev**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description

What?
Allow customisation or swapping of NuCache dependencies.

Why?
Out of the box works well for small sites, but needs further optimisations once you have a large amount of content/media.

Ideas you could implement on top of these changes:
- Swap BPlusTree for another ITransactableDictionary implementation e.x. LiteDb (See https://github.com/umbraco/Umbraco-CMS/pull/8898 for a previous attempt at this)
- Retrieve ContentNodeKit (cmsContentNu + other SQL tables) from a cache.
- Use ITransactableDictionary to store data that is not media or content separately. e.x. Settings.
- Use Range insertion, ordering and reads to improve performance

How:

- Introduce ITransactableDictionary interface for BPlusTree.
- Introduce ITransactableDictionaryFactory interface for creating ITransactableDictionary.
- Introduce INucacheRepositoryFactory, INucacheContentRepository, INucacheMediaRepository and INucacheRepositoryBase as a repository layer over ITransactableDictionary, for more complex queries as potentially another storage could be more efficient by rewriting the query. E.g. don't do .GetAll().ToList().Where().OrderBy().Select(), do GetOrderedIdForContentOfType(). As new queries get added, an adapter should be created to ITransactableDictionary to maintain compatability.
- Introduce ITransactableDictionarySerializer, BPlusTreeTransactableDictionarySerializerAdapter and TransactableDictionaryBPlusTreeSerializerAdapter  to decouple serialization from the bplustree library.
- Introduce ITransactionScope for scoping transactions for ITransactableDictionary

Ensure composition of all introduced interfaces is possible.

Testing:
Replace any of the interfaces mentioned above using a composer. Existing unit tests ensure existing behaviour works.

Replaces PR #8781 and #8978

### CODE REVIEW

**Comment by Shazwazza** [comment]
@nzdev finally have a few hrs to get back to some of these. Any chance you are able to fixup these conflicts?

**Comment by nzdev** [comment]
Yes @Shazwazza

**Comment by nzdev** [comment]
Merge conflicts fixed @Shazwazza

**Comment by Shazwazza** [comment]
Thanks for that. I'm running tests/benchmarks/etc... against what is currently in the nucache-perf branch. There's a huge amount of changes here that I think will need to wait until after all of those tests are done so we can try to get something shipped, else having this reviewed and tested before that will unfortunately just prolong this even more. Hope you understand 🙏  I still have this marked as a task in the coming sprints to look at though but need to finish the review/testing of the other first.

**Comment by nzdev** [comment]
Hi @Shazwazza. No worries. I'll be very happy to see the nucache-perf branch released first.

**Comment by Shazwazza** [comment]
Ace. I've started posting some benchmark stats: https://github.com/umbraco/Umbraco-CMS/pull/8376 
Only a few more to do and then can pass over to the community team for further testing but it's looking good I think. I just want to test more with the property compression options.

**Comment by lars-erik** [comment]
@Shazwazza can we at least make the nucache and published content creation all public classes with a "not intended to be used in production code" comment or something? Ref. #10106

**Comment by Shazwazza** [comment]
@lars-erik most of this will probably (already) be changed in netcore. I cannot look at these changes until this one is done https://github.com/umbraco/Umbraco-CMS/pull/8376. And then yes probably with some review.

**Comment by nul800sebastiaan** [comment]
FYI: looks like this one got closed automatically because https://github.com/umbraco/Umbraco-CMS/pull/8376 was merged. I've re-targeted it now and I'll attempt to fix the merge conflicts!

**Comment by nul800sebastiaan** [comment]
Wow I'm sorry @nzdev - I did try to do a merge but that was WAAAAAY to brave of me to attempt. I am hoping you have some time to do it yourself, this is a really tough one with all the other changes on `PublishedSnapshotService.cs` and me not understanding all of the intentions.

**Pull request closed without merging**
