### PR TITLE
Support custom SVG icon in property actions

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
This is a new PR of closed https://github.com/umbraco/Umbraco-CMS/pull/10928 to v9.

Currently this introduce a breaking change to specify full icon name (like in most other part of UI). Alternatively we could use the approach in https://github.com/umbraco/Umbraco-CMS/pull/10928 with a `useLegacyIcon` property to make it work with current icons and full icon name.

At the moment it is assumed the icon (font icon or SVG icon) always is prefixed with `icon-` which is not always the case and not a requirement in other part of the UI).

### CODE REVIEW

**Comment by bjarnef** [comment]
It updates existing icons in https://github.com/umbraco/Umbraco-CMS/pull/12062/commits/b3581d9b2a0b3de292d6cc45aa921b6b3edd615e

However still a breaking change if developers use the component in packages or used by other Umbraco packages like Umbraco Forms.

It would still be great to support SVG icons, which could be useful in Vendr by @mattbrailsford 

Maybe @nielslyngsoe or @madsrasmussen  has thoughts on this. Do we want a breaking changes e.g. in v10 or should we make it backward compatible?

**Comment by bjarnef** [comment]
@nul800sebastiaan @bergmania could we make these breaking changes now we have the chance in v10? 😎
Alternative I can make it backward compatible as previous PRs, but it is not pretty and will most likely require a property to specify whether legacy or new format should be used.

In fact these two places are the only I have found, where it doesn't specify full icon name.

**Comment by bjarnef** [comment]
@nul800sebastiaan @bergmania could we make these breaking changes in v10.. or should we wait for v11?
Let me know if want a different solution, but it would be great if we can use custom icons in menu actions and property actions 🤞

**Comment by nul800sebastiaan** [comment]
Thanks again @bjarnef - while we are technically allowed to break it in v10, we would like to work on how we announce breaking changes first. Currently it's just going to show up as something that package developers "need to know about", which is something we want to make easier to learn about first. So for now I don't feel like we should break it in v10, we'd love it if you could update it to be backwards compatible indeed, with a `useLegacyIcon`. Thanks in advance! 🙏

**Comment by bjarnef** [comment]
Hi @nul800sebastiaan 

Sure, I'll update the two PR's with a `useLegacyIcon` to make it backwards compatible.

**Comment by bjarnef** [comment]
@nul800sebastiaan this should be updated now.

I also took the liberty to add the property actions to Multi URL Picker as welll.

Single Picker:

image

Multi Picker:

image

image

**Comment by bjarnef** [comment]
https://user-images.githubusercontent.com/2919859/165372346-2d845df7-ad1d-4a68-8252-ec62b71461a0.mp4

**Comment by bjarnef** [comment]
@nathanwoulfe I have updated this one as well to target `v10/contrib` branch.

**Comment by bjarnef** [comment]
@nathanwoulfe I have updated this one as well to target `v10/contrib` branch.

**Review by nathanwoulfe — APPROVED** [review]
Cheers @bjarnef, looks good to me. 👍

**Pull request merged**
