### PR TITLE
U4-4196 U7 - Umbraco HTML5 Drop Zone should honor media types

### PR DESCRIPTION
**Pull request by gkonings**
Check allowed mediatypes. choose mediatype if multiple

### CODE REVIEW

**Comment by gkonings** [comment]
Ok, first sketch for a mediatype prompt. Some trouble I'm running into right now:

- When I change contentTypeAlias to another one. It will still be added as type 'Image'
- I'm using umb-overlay, which has 'submit' and 'cancel' buttons. I don't use those buttons. What's best practice in this case
- Just curious if you got some comments already on what could be better

**Comment by madsrasmussen** [comment]
Hi Gerard,

It looks good so far. You can take a look at how we use the ```itempicker``` overlay in the document type editor and get some inspiration from that (maybe it will make sense to use this? we will have to do some testing to find out what feels the best)

This is the code to open and close the overlay:
https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/views/documenttypes/views/permissions/permissions.controller.js#L52

This is the code used to render the overlay:
https://github.com/umbraco/Umbraco-CMS/tree/dev-v7/src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker

To hide the submit button you can set the ```hideSubmitButton``` property on the overlay model to ```false```. We do that here: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/views/common/overlays/itempicker/itempicker.controller.js#L7

but you can also do this when you set up the overlay model the same way you set the title, view etc. from the controller which opens the overlay.

I will have to get some input form @Shazwazza maybe he can tell us why the contentTypeAlias isn’t set correctly.

**Comment by gkonings** [comment]
Almost done.

2 things that still need to be done.
- Get it working on the mediapicker views
- Get it working serverside

For the serverside implementation I need some help. I fear the mediatype upload is hardcoded as "Image" and I cannot make any sense of the code (I'm not the best back-ender). So if someone else could have a look at that, that would be great.

**Comment by gkonings** [comment]
I've made a little update. It will be my last update. It's only the front-end part. Tomorrow I will part with my windows machine, so helping out will be a little harder.

**Pull request closed without merging**
