### PR TITLE
V10 Reduce memory traffic during nucache string deserialization

### PR DESCRIPTION
**Pull request by nzdev**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description
Reduce allocations for nucache string deserialization by using an array pool and string pool when deserializing strings.
Allow override for nucache db construction
How to test?
Existing tests pass, Memory traffic reduced.

### CODE REVIEW

**Comment by mikecp** [comment]
Hi @nzdev, 

Thanks for your contribution👍 Someone from the team will have a detailed look at it soon!

**Comment by mikecp** [comment]
Hi again @nzdev , I just noticed that you were targeting the branch v10/dev, it would be super great if you could retarget it to our `contrib` branch 😁

Cheers!

**Comment by nul800sebastiaan** [comment]
Changing the base of that commit led to a big mess of all kinds of files changing. I tried to resolve it but there's still unrelated commits in there. Sorry to ask @nzdev but could you please re-apply your commit on top of a freshly fetched `contrib` branch so we can make it a clean merge?

A word of warning, I see this is taking on a dependency on `CommunityToolkit.HighPerformance` and I'll need to ask the team first if that's something they want to rely on / ship with.

**Comment by nul800sebastiaan** [comment]
In order to be able to evaluate whether we should add a new dependency we would need more information on the supposed reduction in memory traffic. The team would love to know by how much to be able to see if it's worth the effort in shipping with a new direct dependency. 

I'll close this PR for now but if you have some more information to help us evaluate and a fresh commit that's not mixed with other ones then we can have another look! Thanks @nzdev!

**Pull request closed without merging**
