### PR TITLE
V8: Wildcards in tree searches causes YSODs

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

If you try to use a `*` in any search field (global search, copy/move dialog search, treepicker search, ...), things tend to go horribly wrong:

image

This PR explicitly removes the `*` character in the search queries to avoid that:

image

This doesn't change the fact that the tree searcher still performs wildcard queries:

image

### CODE REVIEW

**Comment by bjarnef** [comment]
@kjac I could also trigger a ysod by including `_` (underscore) in search term.

**Comment by kjac** [comment]
@bjarnef good grief! I will amend the PR. Thanks 👍

**Comment by bjarnef** [comment]
@kjac `-` (hyphen) also trigger the ysod ⚠️

**Comment by kjac** [comment]
Magic markdown code block char ` also does it.

**Comment by kjac** [comment]
Aha! So as it turns out, the problem is two-fold:

1. Lucene search does not like the chars `* - _` so those are now stripped from the Lucene searches.
2. SQL queries containing only one quotation mark (``' " ` ``) throws a logic error when stripping those quotation marks.

The PR has been updated to handle both scenarios. In summary:

### Testing this PR

Global search, copy/move dialog search, treepicker search etc. should *not* throw a YSOD when entering one and only one char of the following: ``* - _ ` ' "``

**Comment by marcemarc** [comment]
Is it specific to those characters or all the Lucene 'Special Characters'?

+ - && || ! ( ) { } [ ] ^ " ~ * ? : \

http://lucene.apache.org/core/2_9_4/queryparsersyntax.html#N10180

**Comment by kjac** [comment]
@marcemarc thanks for the input 😄 but no, for the Lucene searches it's only `* - _`

**Comment by nul800sebastiaan** [comment]
Whoop! 🎉  Much better now, cheers! 👍

**Pull request merged**
