### PR TITLE
Doesn't fix the issue but improves performance by ~30%

### PR DESCRIPTION
**Pull request by hartvig**
Simplifying this xpath query increases performance with around 30% when looking up items by Guid/UDI in the Our Umbraco database.

### CODE REVIEW

**Comment by Shazwazza** [comment]
@hartvig make sure you link the issue here and also the PR in the issue :)

The change will work since we know there is no 'key' in the properties elements, i'm unsure how you tested the performance but happy to trust that it's correct :)

There's probably something we can add to this to make it perform much much faster which is something @leekelleher always reminds me to do, since we are looking for a single item, changing this to:

```cs
var xpath = legacyXml ? "//node [@key=$guid][1]" : "//* [@key=$guid][1]";
```

This code goes on to pass this XPath to `XmlNode.SelectSingleNode` which actually doesn't do anything intelligent, here's the .NET code for that method:

```cs
public XmlNode SelectSingleNode(string xpath)
{
    XmlNodeList xmlNodeList = this.SelectNodes(xpath);
    if (xmlNodeList == null)
    return (XmlNode) null;
    return xmlNodeList[0];
}
```

which as you can see will select all matching nodes and then just return the first one, so it's not doing anything smart with the Xpath passed in. I'm fairly certain that by adding the `[1]` it tells the XPath engine to abort the search once it's found the first one, but by default if you don't specify this, it will keep trying to match the remaining. 

@leekelleher  can you confirm/deny this?

**Comment by hartvig** [comment]
> Issue linking
Roger :)

> Performance
Based on avg of 10x10.000 queries with old vs new query using the Our Umbraco database as test case.

> Adding [1]
Really odd, but it decreases performance by 100x(!!!)

**Comment by Shazwazza** [comment]
Haha, ok then that's not what we want :P Maybe it's something different that @leekelleher had mentioned to me at some point but i was pretty sure that was the premise. I'm sure he'll get back to us :)

**Comment by Shazwazza** [comment]
@hartvig maybe it's to do with this: https://stackoverflow.com/a/5621660/694494

so maybe try 

```cs
var xpath = legacyXml ? "(//node [@key=$guid])[1]" : "(//* [@key=$guid])[1]";
```

**Comment by Shazwazza** [comment]
I'll pull this change in now since we might as well have it, then need to figure out the best approach to fixing this. 

@hartvig would be interested to see what happens with those brackets around that xpath

@leekelleher interesting stuff! I guess there's a few things we can tinker with and I know @zpqrtbnk is quite familiar with the XPathNavigator :)

**Pull request merged**
