### PR TITLE
fix #7127 Unlock user account doesn't work on 7.14.0 and 15

### LINKED ISSUE #7127: Unlock user account doesn't work on 7.14.0 and 15
I have seen this issue posted earlier here: https://github.com/umbraco/Umbraco-CMS/issues/3979
and it was not reproduce-able and closed. I can confirm that it is happening still on 7.14. I think the issue is that these are upgraded sites and the membership provider has changed for users so this are users that have been migrated to the new provider and this might be the issue not mentioned previously.

I am seeing this issue on Umbraco version: 7.14.0 but tested on 7.15 and it's happening there too.

Reproduction
------------

1) Find a locked out user that has been migrated from a previous version of Umbraco with an older membership provider.
2) Go into the user profile and unlock it - it will appear that it has been unlocked.
3) Go back to the main user list - user is still locked out - user can't login.

### PR DESCRIPTION
**Pull request by NillDk**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #7127

### Description
This issue may be difficult to reproduce, as it seems to depend on the speed of the Web-server.
@kjac made an exelent screen shot of the proglem in the related issue #3979:

Umbraco-issue-7127

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @NillDk 

Thanks for the PR. The screenshot should help plenty :)

We'll take a look and let you know if we need any changes

Emma

**Comment by nul800sebastiaan** [comment]
Hey there @NillDk - sorry for the delay on this one, we got there eventually! 🙈 

This is a great little fix, thank you so much! 

Congrats on your first contribution to Umbraco-CMS! ⭐

If you have an account on [Our Umbraco](https://our.umbraco.com) could you link it here? I would love to add a contributor badge to your profile!

**Comment by NillDk** [comment]
Hi @nul800sebastiaan - I've created a profile on Our Umbraco and linked it to my GitHub profile:
https://our.umbraco.com/members/NillDk/

Should I also be able to link from GitHub to Our Umbraco?

**Comment by nul800sebastiaan** [comment]
Hehe, GitHub doesn't know anything about our community site, so no you can't link it the other way!

Thanks again, I've added your contrib badge now, congrats! 🥇

**Pull request merged**
