### PR TITLE
Solves #13378

### LINKED ISSUE #13378: The query parameter format must come before quality to have any effect.
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.3.0-rc

### Bug summary

The query parameter format must come before quality to have any effect. I have located the problem in ImageSharp.Web, but after discussing with my colleague, we believe that ImageSharp.Web follows the order specified by the user on purpose. For Umbraco developers, I would think that if they use furtherOptions and specify format there, or for example use Slimzy's outputFormat which is again added to furtherOptions, that they want quality to apply to the specified format and not run before converting to, for example, webp.

### Specifics

src/Umbraco.Cms.Imaging.ImageSharp/Media/ImageSharpImageUrlGenerator.cs

```c#
        if (options.Quality is not null)
        {
            queryString.Add(QualityWebProcessor.Quality, options.Quality?.ToString(CultureInfo.InvariantCulture));
        }

        foreach (KeyValuePair<string, StringValues> kvp in QueryHelpers.ParseQuery(options.FurtherOptions))
        {
            queryString.Add(kvp.Key, kvp.Value);
        }
```

This is why it happens ([WebProcessingExtensions.cs](https://github.com/SixLabors/ImageSharp.Web/blob/2b1450d287a7c4152d7d41bcab4cfb53f871e377/src/ImageSharp.Web/Processors/WebProcessingExtensions.cs))
image

### Steps to reproduce

image

### Expected result / actual result

_No response_

### PR DESCRIPTION
**Pull request by kritollm**
### Prerequisites

If there's an existing issue for this PR then this fixes #13378

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks @kritollm, this looks great! We should also backport this to v10 when merged. 💡

**Comment by matthewcare** [comment]
Ah, that explains why my image size increased when using format and quality!

**Comment by nul800sebastiaan** [comment]
I could've sworn I merged this one already, sorry for not getting it finalized @kritollm!

All good here, and love the unit test addition! 🎉 

Do you have an account on Our Umbraco? Would love to give you  a contributor badge to congratulate you for your first merged PR to Umbraco-CMS!

**Comment by nul800sebastiaan** [comment]
Cherry picked for 10.4.0 ba53b47b72fe81b98e8e241f393e097271a705b1

**Pull request merged**
