### PR TITLE
17629: Log Viewer The reader's MaxDepth of 64 has been exceeded in Umbraco

### PR DESCRIPTION
**Pull request by piotrbach**
Hi Guys.
This is a PR related to the reported issue: https://github.com/umbraco/Umbraco-CMS/issues/17629
We need this fix in the latest v13 - if you could merge it - it would be great.

You need to be aware that a new default field was introduced in Newtonsoft.Json JsonSerializerSettings.cs:
internal const int DefaultMaxDepth = 64;

https://github.com/JamesNK/Newtonsoft.Json/blob/release/13.0.3/Src/Newtonsoft.Json/JsonSerializerSettings.cs#L70

You will find more details here: https://umbracare.net/blog/fixing-the-readers-maxdepth-of-64-has-been-exceeded-in-umbraco/

PS. The SerilogJsonLogViewer class is slightly different between v15 and v13. The error handling was improved in 15 (the error is not breaking the view now because it's caching the generic Exception). However, error logging for parsing log files could be improved and enhanced with more details in the future (such as the filename that is causing the deserializing error).

Anyway, v13+ logViewer will have trouble with deserializing more extensive log entries without this fix.

Best, Piotr

@wtct @nul800sebastiaan @Zeegaan

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi @piotrbach ,

Thanks for your PR to fix #17629, where there is an error that the _Log Viewer The reader's MaxDepth of 64 has been exceeded in Umbraco._

One of the Core Collaborators team will review this as soon as possible - a you have also tagged, it seems like one that we want HQ to review.

PS Nice to see you first contribution in this repo! #h5yr

Best wishes

Emma

**Comment by bergmania** [comment]
Hi, thanks for the PR to your created issue.

IMO we should not do a fix, in this way. We can create a task with the `Serilog.Formatting.Compact.Reader` project or we can make an injectable `JsonSerializerSettings`. 

If you have logs with 64+ parameters that most like the first issue that should be solved. This just increases the limit so it will crash again with 128+ parameters. 

64 is already much more than we should expect, so I would argue the default should NOT be increased, but having a way to increase in your project is fine.

**Comment by bergmania** [comment]
I think you should, in the solution that experiences this issue, provide your own `ILogViewer`. E.g. just like the one provided here. Thereby we should not change this for all Umbraco solutions. As I said first, this should IMO be handled in `Serilog.Formatting.Compact.Reader`:

```cs
public class MyComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder) => builder.Services.AddSingleton<ILogViewer, MySerilogJsonLogViewer>();
}

internal class MySerilogJsonLogViewer : SerilogLogViewerSourceBase
{
    private const int FileSizeCap = 100;
    private readonly ILogger<MySerilogJsonLogViewer> _logger;
    private readonly string _logsPath;

    public MySerilogJsonLogViewer(
        ILogger<MySerilogJsonLogViewer> logger,
        ILogViewerConfig logViewerConfig,
        ILoggingConfiguration loggingConfiguration,
        ILogLevelLoader logLevelLoader,
        ILogger serilogLog)
        : base(logViewerConfig, logLevelLoader, serilogLog)
    {
        _logger = logger;
        _logsPath = loggingConfiguration.LogDirectory;
    }

    public override bool CanHandleLargeLogs => false;

    public override bool CheckCanOpenLogs(LogTimePeriod logTimePeriod)
    {
        // Log Directory
        var logDirectory = _logsPath;

        // Number of entries
        long fileSizeCount = 0;

        // foreach full day in the range - see if we can find one or more filenames that end with
        // yyyyMMdd.json - Ends with due to MachineName in filenames - could be 1 or more due to load balancing
        for (DateTime day = logTimePeriod.StartTime.Date; day.Date <= logTimePeriod.EndTime.Date; day = day.AddDays(1))
        {
            // Filename ending to search for (As could be multiple)
            var filesToFind = GetSearchPattern(day);

            var filesForCurrentDay = Directory.GetFiles(logDirectory, filesToFind);

            fileSizeCount += filesForCurrentDay.Sum(x => new FileInfo(x).Length);
        }

        // The GetLogSize call on JsonLogViewer returns the total file size in bytes
        // Check if the log size is not greater than 100Mb (FileSizeCap)
        var logSizeAsMegabytes = fileSizeCount / 1024 / 1024;
        return logSizeAsMegabytes <= FileSizeCap;
    }

    protected override IReadOnlyList<LogEvent> GetLogs(LogTimePeriod logTimePeriod, ILogFilter filter, int skip,
        int take)
    {
        var logs = new List<LogEvent>();

        var count = 0;

        var serializerSettings = GetJsonSerializerSettings();
        var jsonSerializer =  JsonSerializer.Create(serializerSettings);

        // foreach full day in the range - see if we can find one or more filenames that end with
        // yyyyMMdd.json - Ends with due to MachineName in filenames - could be 1 or more due to load balancing
        for (DateTime day = logTimePeriod.StartTime.Date; day.Date <= logTimePeriod.EndTime.Date; day = day.AddDays(1))
        {
            // Filename ending to search for (As could be multiple)
            var filesToFind = GetSearchPattern(day);

            var filesForCurrentDay = Directory.GetFiles(_logsPath, filesToFind);

            // Foreach file we find - open it
            foreach (var filePath in filesForCurrentDay)
            {
                // Open log file & add contents to the log collection
                // Which we then use LINQ to page over
                using (var fs = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
                {
                    using (var stream = new StreamReader(fs))
                    {
                        var reader = new LogEventReader(stream, jsonSerializer);
                        while (TryRead(reader, out LogEvent? evt))
                        {
                            // We may get a null if log line is malformed
                            if (evt == null)
                            {
                                continue;
                            }

                            if (count > skip + take)
                            {
                                break;
                            }

                            if (count < skip)
                            {
                                count++;
                                continue;
                            }

                            if (filter.TakeLogEvent(evt))
                            {
                                logs.Add(evt);
                            }

                            count++;
                        }
                    }
                }
            }
        }

        return logs;
    }

    private string GetSearchPattern(DateTime day) => $"*{day:yyyyMMdd}*.json";

    private bool TryRead(LogEventReader reader, out LogEvent? evt)
    {
        try
        {
            return reader.TryRead(out evt);
        }
        catch (JsonReaderException ex)
        {
            // As we are reading/streaming one line at a time in the JSON file
            // Thus we can not report the line number, as it will always be 1
            _logger.LogError(ex, "Unable to parse a line in the JSON log file");

            evt = null;
            return true;
        }
    }

    private JsonSerializerSettings GetJsonSerializerSettings()
    {
        return new JsonSerializerSettings
        {
            DateParseHandling = DateParseHandling.None,
            Culture = System.Globalization.CultureInfo.InvariantCulture,
            MaxDepth = 128
        };
    }
}

```

**Comment by piotrbach** [comment]
Hi @bergmania, thanks for your suggestion.
Custom ILogViewer should work for us.

Have a great day!
cc: @wtct

**Pull request closed without merging**
