### PR TITLE
Save and preview translation.

### PR DESCRIPTION
**Pull request by rogalmic**
### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes

### CODE REVIEW

**Comment by rogalmic** [comment]
@georgebid  I confirm. Customer wanted to have this info that its saving explicitly, same as in English version.

**Comment by georgebid** [comment]
@rogalmic Makes sense! This has now been merged in and will feature in release 11.4.0 😄

**Comment by rogalmic** [comment]
@georgebid Could we have this merged to v10 as well?

**Comment by nul800sebastiaan** [comment]
Cherry picked for 10.6 in 1e0ace7a344a90f682f361000c4d1d66807a1bf4

**Pull request merged**
