### PR TITLE
Add IModelsGenerator Interface

### PR DESCRIPTION
**Pull request by mroberts91**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

- Added `IModelsGenerator` interface to `Infrastructure.ModelsBuilder.Building.ModelsGenerator`
- Updated service registration and usage. 

Just a small inclusion to allow for extending ModelsBuilder.

### CODE REVIEW

**Comment by mroberts91** [comment]
Note: Windows Unit Test failed due to a flaky test:
`TypeLoaderTests.Detect_Legacy_Plugin_File_List()`
[Test Logs](https://dev.azure.com/umbraco/Umbraco%20Cms/_build/results?buildId=88639&view=logs&j=b401e3b4-65ab-54a7-c984-317a3fe442f1&t=56a790af-1dc2-5ccd-7289-59ed231284e8)

**Comment by mroberts91** [comment]
#12245

**Comment by emmagarland** [comment]
Hi @mroberts91,

Thanks so much for the PR and related [discussion](https://github.com/umbraco/Umbraco-CMS/discussions/12245), and apologies for the delay in replying!

To avoid breaking changes (signature of some public methods are changing), would it be possible to adjust the code to make it so it would still be backwards compatible? For instance, making the old constructors obsolete, and allowing people to still be able to inject ModelsGenerator directly? 

Thanks, any questions please let us know!

Emma

**Comment by bielu** [comment]
@emmagarland in which case anyone would inject this specific class? 🤔 
Controller or Notification handler will be rarely use for base classes, so I would probably advocate to keep constructor gone, just because it makes code cleaner and we should stop being afraid to introduce this type of breaking changes, where we introduce cleaner code 😓 

@mroberts91 I love you made this change, I was going soon to go through MB and added much more interfaces to make possible to actually have little better control over output of MB!

**Comment by nul800sebastiaan** [comment]
@bielu Our goal is to be friendly and only introduce immediate breaking changes when strictly necessary. Adding a constructor that redirects the new constructor and deleting the old one eventually (2 majors later) is what we do in these cases.

**Comment by nul800sebastiaan** [comment]
I've given this one an update to be non-breaking, this is the pattern we need to use for that:

- Obsolete the current constructor.
- Create a new constructor that takes more parameters than the old one (i.e. takes both the concrete implementation and the interface). Obsolete this constructor right away.
- Create a new constructor that only accepts the interface. Once the obsoletion period is over for the two previous constructors, this will be the last one standing.

The obsolete constructors should call the non-obsolete one and should have no implementation body themselves. This requires using `StaticServiceProvider.Instance.GetRequiredService<IIndexRebuilder>()` in the current constructor for the interface parameter in the new, non-obsolete one.

Once v13 comes around, we'll be able to finalize this and make a permanent breaking change by removing the obsolete constructors and the (now unused) readonly fields.

So for now, until v13, the DI will actually use the constructor with the most parameters, even if it is obsolete. This is fine, it will just forward to the constructor that is not obsolete. 

I'll wait for the build to finish but I expect that it should complete just fine!

**Comment by nul800sebastiaan** [comment]
Alright after another round of failing tests, we got there with a massive thanks to @kjac for the help here!

In order for the DI to able to figure out which constructors to use on the controllers I had to add a hint in the form of `[ActivatorUtilitiesConstructor]` otherwise these controllers would error out as soon as they got instantiated. 

Avoiding another breaking change was: people MIGHT be injecting the existing `ModelsGenerator` class in their own projects (doubtful that people actually do that, but you never know), we added the registration of that one back in `UmbracoBuilderDependencyInjectionExtensions`. This should be safe, there doesn't seem to be any state held inside the `ModelsGenerator` so it should not be a problem.

**Comment by nul800sebastiaan** [comment]
All the tests pass now and we're fully backwards compatible. Thanks very much @mroberts91 for getting this ball rolling. Apologies for taking so long to get this one reviewed and merged, it was a bit tricky but should not have taken a year. Hopefully "better late than never" still applies here. 

And congratulations on your first ever contribution to Umbraco CMS! 🎉 We'll try to get to future contributions a lot faster 😅 🙈 

You now have a shiny new contrib badge on your Our profile: https://our.umbraco.com/members/mroberts91 🏅 

Thanks again!

**Comment by mroberts91** [comment]
@nul800sebastiaan Thank you for making those constructor changes and fixing the tests! We will be excited when we get to v11.4.0 and can stop using our request-hijacking middleware.

**Pull request merged**
