### PR TITLE
Fixes: U4-7448 Grid - Sorting view

### PR DESCRIPTION
**Pull request by madsrasmussen**

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Hmm, this one doesn't seem to work as expected when re-ordering columns, see gif below. Note: the data is not lost, when I save this and then refresh the browser, the content is where I expected it to be. 
untitled screencast 1

**Comment by madsrasmussen** [comment]
@nul800sebastiaan This issue is not caused by these changes. I have just replicated the issue in 7.3.3, so I think it has been around some time. I think we should create a separate issue for that. All this PR does is to add the "collapsed-mode" where we hide the content of each control.

**Comment by nul800sebastiaan** [comment]
Perfect! Then it works beautifully! :-)

**Comment by nul800sebastiaan** [comment]
_and created http://issues.umbraco.org/issue/U4-7544_

**Pull request merged**
