### PR TITLE
Review: Media picker UX updates

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5172 and https://github.com/umbraco/Umbraco-CMS/issues/5228

### Description

#5172 outlines new rules for how the media picker should behave:

> * Lets get rid of the option to edit a media-item and media-folder from the media-picker selection-dialog (it has offen shown to cause confusion when people hit it by accident)
> * When a media-picker is configured to allow folder-selection, we would have to select folders as the default action and thereby use the folder-name as the way to open the folder. (If folder-selection is disabled we will just open the folder when clicking it everywhere).
> * Media-item file-names should not have an action, and thereby the underline for the name should be gone, and the action when clicking anywhere on the item should be to select the item. (the same goes for folders if folder-selection is disabled)
> * on the media-picker property-editor we would keep the remove and edit-shortcut on each item, and this will be the way if you want to change the focus-point... So you would need to pick it for the media-picker first, and then the option to edit will be available.

This PR implements all of the above 😄 

### Testing this PR

Given the rules above there are a few things to do when testing this PR...

#### 1: Media picker with folder selection enabled

When folder selection isn't actively disabled on the media picker configuration, the media picker should: 

1. Open folders when their name is clicked (and the name should have an underline hover effect).
2. Select folders when anything else is clicked.
3. Select media no matter what is clicked (and the name should *not* have an underline hover effect).

media-picker-enable-folder-select

#### 2: Media picker with folder selection disabled

When folder selection is disabled on the media picker configuration, the media picker should: 

1. Open folders no matter what is clicked (and the name should *not* have an underline hover effect).
2. Select media no matter what is clicked (and the name should *not* have an underline hover effect).

media-picker-disable-folder-select

#### 3: Media library grid layout

The media library grid layout uses the same view component as the media picker. Therefore the media library should be tested to make sure it's not broken by this PR. The media library should:

1. Open folders when their name is clicked (and the name should have an underline hover effect).
2. Select folders when anything else is clicked.
3. Open media when their name is clicked (and the name should have an underline hover effect). 
3. Select media when anything else is clicked .

media-library

---
_This item has been added to our backlog [AB#4396](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/4396)_

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @kjac 

As per usual, amazing docs. Thanks!

Em

**Comment by kjac** [comment]
Merge conflicts resolved.

**Comment by kjac** [comment]
Merge conflicts resolved and code updated to work with latest dev.

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by nielslyngsoe** [comment]
@kjac good work, I'm fixing merge conflicts, correcting a few other minor details and will be merging it soon. Thanks

**Comment by kjac** [comment]
@nielslyngsoe awesome 👍

**Pull request merged**
