### PR TITLE
v8: Checkbox radio onchange fix

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
Just a few fixes to work with optional `on-change` and make radiobuttons a bit more consistent with checkboxlist.

### CODE REVIEW

**Comment by bjarnef** [comment]
@nul800sebastiaan can you review this as well. It would be awesome. 😁👍🦄

**Comment by emmaburstow** [comment]
Hey @bjarnef,

Thanks for the work. Seb will indeed have a look and we'll shout if we need anything.

Emma

**Comment by nul800sebastiaan** [comment]
Thanks again @bjarnef - that works now! That was a bit messier than I was hoping for 🙈

**Comment by nul800sebastiaan** [comment]
Cherry picked for 8.1.5 as well 71b3260b1d86a55037ff2b830099c53e39be3a0b

**Pull request merged**
