### PR TITLE
Fix mssing image caption in RTE

### PR DESCRIPTION
**Pull request by ustadstar**
### Prerequisites

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8457 & https://github.com/umbraco/Umbraco-CMS/issues/10206

### Description
I have adjusted the insertMediaInEditor function to always add a new image and checking if a caption exists, it adds the image inside a figure element with a figcaption as a sibling. 

I also added a data-caption attribute to the image. I did this in order to check if a caption exists and to read the value.

Steps to test this PR:

1. Create a doc type
2. Add a property of type Rich Text Editor
3. Add an image into the Media section
4. Create a content page using the Doc Type you made
5. In the RTE property, click the media picker
6. Fill in the properties; Alternative text (optional), Caption (optional), and select an Image
7. The image is rendered in the Rich Text Editor inside a figure element, with a figcaption element as a sibling

### CODE REVIEW

**Review by nul800sebastiaan — COMMENTED** [review]
Thanks @ustadstar for asking for an update on this one and apologies for the delay!

I have a few thoughts about potential problems I can see with this one, most of all, we can't change the default settings to include `figure,figcaption` as that would be a breaking change. People already rely on the current behavior that these two are not allowed at the moment so it would be giving more permissions than there was before, we can't just do that. 

Other than that, from what I gather, now images will always be wrapped in a `figure` element? I don't know if that's going to upset some people either.. they might not want us "messing" with their markup. 

This might be a lack of understanding the issue on my part though, so please do expand on the chosen solution so I can understand it better.

**Comment by ustadstar** [comment]
@nul800sebastiaan 

The issue is that there is a caption field when picking an image in the rich text editor, but the field does nothing.
image

So I have added some code to generate a caption, when the field is filled and to remove the caption (if there is one) when it is left blank. If I understood the HTML specification (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption) correctly, the img element is wrapped inside a figure element  and a figcaption element is added below the img element. The img element will **not** be wrapped inside a figure element when the caption field is left blank. 

An example:
```
<figure>
    <img src="/media/cc0-images/elephant-660-480.jpg"
         alt="Elephant at sunset">
    <figcaption>An elephant at sunset</figcaption>
</figure>
```

To make this work, we have to add the figure and figcaption elements to the string of ValidElements, else the caption cannot be created in accordance with the HTML specifications. I have removed the elements and tested it locally to see how the caption is placed, this is the result:

```
<p>
<img src="/media/2whfqxd3/istockphoto-1291083519-612x612.jpg?rmode=max&amp;width=500" alt="" width="500" height="316.1764705882353" data-udi="umb://media/5c488fe3b67d4feca3b44f54daa53891" data-caption="Caption" /> Caption
</p>
```

As you can see the figure and ficaption elements are removed.

**Comment by martijnbeumers** [comment]
Hi @nul800sebastiaan , when will this issue be merged with the core project? Lots of sites need this fix to fully comply to WCAG. And the way it is implemeted by @ustadstar it still is optional so nothing happens when people leave it blank. Just the way it works now. So impact should be low.

**Comment by nul800sebastiaan** [comment]
Apologies for the delay! I looked at it again and I seem to have misunderstood the functionality. This is indeed a super useful addition, the "breaking" part is not actually breaking, if you don't use the caption field then nothing changes but when you do you get super useful new functionality. 

So all of this is great! My SLIGHT concern is that it will start causing some confusion when new images with a caption show up on the frontend of the website because the editors can now start using the caption for something useful. This might lead to some unexpected styling issues, images needing to be targeted differently etc. 

However, it feels like the new functionality is adds more than enough value to outweigh that small inconvenience.

If this is very unwanted behavior then people can add some config to the invalid elements: 

image

```json
      "RichTextEditor": {
        "InvalidElements": "figure,figcaption"
      },
```

Thanks very much @ustadstar for the work! And congratulations on your first accepted contribution to Umbraco-CMS! 🎉 

If you have an account on [Our Umbraco](https://our.umbraco.com/), I'd love to give you a contributor badge. I just need to know the URL of your public profile so I can find you! 👍

**Comment by ustadstar** [comment]
Hi @nul800sebastiaan, my public profile url: https://our.umbraco.com/members/ustadstar/

**Pull request merged**
