### PR TITLE
Version history cleanup

### PR DESCRIPTION
**Pull request by p-m-j**
## What's done!

- [x] Supporting database migrations.
- [x] Global XML Configuration support.
- [x] Database policy overrides per doc type.
- [x] Preserving content versions marked as "preventCleanup".
- [x] Scheduled task that deletes historic content versions every hour according to policy.
- [x] Tests for all of the above.
- [x] Ability to set overides per doc type via service call.
- [x] Ability to set overides per doc type via UI.

## Fuuture work

- [ ] Ability to mark content versions as "preventCleanup" via service call.
- [ ] Ability to mark content versions as "preventCleanup" via UI.

## How do I make lots of content versions quickly?

Services are pretty slow if you want a lot of data.

This sql query will create historic versions copying data from the most recently saved and published content.
```sql
begin transaction 

declare @versionsToCreate int = 10000

declare @nodeId int = (
	select max(nodeId) 
	from umbracoContentVersion cv 
	inner join umbracoDocumentVersion dv on cv.Id = dv.id
)

declare @contentTypeid int = (select contentTypeId from umbracoContent where nodeId = @nodeId)

declare @i int = 0
while (@i < @versionsToCreate)
begin

	insert into umbracoContentVersion (nodeID, versionDate, userId, [current], text)
	values (@nodeId, dateadd(year, -1, getdate()), -1, 0, convert(nvarchar(36), NEWID()))

	declare @versionId int = SCOPE_IDENTITY()

	insert into umbracoDocumentVersion (id, published)
	values(@versionId, 0)

	insert into umbracoPropertyData (versionId, propertyTypeId, textValue)
	select @versionId, pt.id, convert(nvarchar(36), NEWID())
	from cmsPropertyType pt where 
	contentTypeId = @contentTypeid	

	set @i  = @i  + 1
end

commit transaction
```

### CODE REVIEW

**Review by bergmania — APPROVED** [review]
Tested and it works as expected.. Ill use this as a base branch and merge other Prs into this

**Comment by niekvanderreest** [comment]
Without going through much of the code I was wondering if the feature deletes solely based on historic version date/time or is it also possible to configure a minimum number of versions to keep? I can imagine some content that changes infrequently (legal notices and such) where having a historic version to check with could be helpfull.
This would also prevent having to set lots of pages to exclude from version cleanup.

**Comment by p-m-j** [comment]
Minimum versions to keep was discussed a lot but decided out of scope for an initial release.
It's possible to provide an alternate implementation of IContentVersionCleanupPolicy if you require functionality sooner.
However if your legal notices all shared a single doc type, you would need only one override to ensure they are never removed so you may be able to get what you need out of the box.

**Comment by timlaughlin** [comment]
This won't delete the primary published version ever correct? Just the history? A bit unclear in the notes. I don't want active publish nodes/versions deleted by this.

**Pull request merged**
