### PR TITLE
v8: Fix media picker svg preview

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6414

### Description
This PR fixes some a few issues with media picker infinite editor.

- The overlay title was not shown - "Select media"
- Breadcrumb root node was not localized
- A minor issue in the browser title browsing a node (edit), where it was missing a space after colon.
- Selecting a SVG image in media picker property editor via the media picker infinite editor didn't update the thumbnail preview.
- Mediahelper `resolveFileFromEntity` and `getThumbnailFromPath` return a thumbnail preview for SVG (vector), so not only for images like `gif`, `jpg`, and `png`.

I have furtermore cleaned up much of the code to use `vm` and more consistent with other inifinite editors and components.

### CODE REVIEW

**Comment by bjarnef** [comment]
I also noticed this "loading" in mediapicker which doesn't seem to be correct since we don't have any `$scope.image` property https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/views/propertyeditors/mediapicker/mediapicker.html#L15-L17

I guess this should be `media.loading`.

**Comment by nul800sebastiaan** [comment]
Holy moly that's a lot of changes for something that sounds quite simple 🙈

It's going to take a while to review all this.

**Comment by bjarnef** [comment]
@nul800sebastiaan most of the changes are just using `vm` syntax and Some renaiming :)

**Comment by nul800sebastiaan** [comment]
😅 Seems to be all good, thanks @bjarnef !

**Pull request merged**
