### PR TITLE
Create tr.xml

### PR DESCRIPTION
**Pull request by Dynacy**
Turkish Language

### CODE REVIEW

**Comment by Shazwazza** [comment]
Hi! Can you please create a task/issue for this on the tracker? http://issues.umbraco.org

**Comment by bjarnef** [comment]
@Shazwazza it seems to be related to this issue http://issues.umbraco.org/issue/U4-8372

**Comment by Shazwazza** [comment]
Thanks!

**Comment by nul800sebastiaan** [comment]
Nice, thanks very much @Dynacy ! :+1:

**Pull request merged**
