### PR TITLE
Fixes: U4-7871 Media picker - add functionality to go to media item w…

### PR DESCRIPTION
**Pull request by madsrasmussen**
…hen an image has been picked

### CODE REVIEW

**Comment by jbreuer** [comment]
Thanks for adding this!

**Comment by kipusoep** [comment]
@madsrasmussen is it like this: https://github.com/rolfis/ExtendedMediaPicker ?

**Comment by jbreuer** [comment]
That's what I suggested ;-)

**Comment by madsrasmussen** [comment]
@kipusoep yes 99% :) I have added an icon next to the delete icon where you can go to the media item in the media section. I can see that the Extended Media Picker also shows the name. I have not added that part. If you would also like that, please open a feature request in the issue tracker and I can have a look at it as soon as time permits.

**Pull request merged**
