### PR TITLE
V12: Cherry pick unscoped migrations

### PR DESCRIPTION
**Pull request by Zeegaan**
# Notes
- This is a v12 cherry pick of: https://github.com/umbraco/Umbraco-CMS/pull/13654
- This was originally planned for v13 but is needed for EFCore.
- This is a breaking change, as it removes the `PostMigration`, there is however a `UmbracoPlanExecutedNotification` you can now hook into instead.
- This is also behaviorally breaking, as now all the migrations run in individual scopes, this means if a migration fails, it will stop on the last successful migration, and not roll all the way back.

### CODE REVIEW

**Comment by KevinJump** [comment]
Hi,

Can i just confirm i am reading this PR correctly ?

If this is in the upcoming  v12 release it will: 
- Removes PostMigrations from the Migration Context ? 
- It removes the Execute method in favor of the ExecutePlan method (as per #13654)) 

The methods where only obsoleted in the v11 branch Jan (#13658) and made the v11.2.0 release ? which means we have really only had these methods obsoleted since 27th Feb - they should really be around to v13 ? 

### can we not keep Execute ?
I am not sure why `IMigrationPlanExecutor.Execute` needs to be removed in this version, could that method not call `ExecutePlan`, and still return the `fromState` from `ExecutedMigrationPlan` object ? 

### PostMigrations
I am less sure about why these need to go, as its a bit more indepth, but is there no way these can somehow be obsoleted in a similar manner to execute ?

**Comment by Zeegaan** [comment]
Heyo! 👋 
Sorry for the late answer here, but good points!
We're looking into making some of this less breaking! 🕵️

**Comment by nul800sebastiaan** [comment]
Follow up PR is here @KevinJump - https://github.com/umbraco/Umbraco-CMS/pull/14225

**Comment by Zeegaan** [comment]
Yea and just an explanation for PostMigrations having to be removed here:

The migrations are now in individual transactions, and no longer wrapped in one big transaction.
If an error occurs during a migration, we only roll back the failing one.
As post-migrations are executed after the migrations have run, we can no longer guarantee they have all run.
Therefore, we can no longer execute post-migrations safely.

**Pull request merged**
