### PR TITLE
V8: Add notification badge to content app

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is: https://github.com/umbraco/Umbraco-CMS/issues/3425
- [x] I have added steps to test this contribution in the description below

### Description

To show a badge on the content app icon, simply assign a value to `$scope.model.badge` from the content app controller - like so:

```js
$scope.model.badge = {
  count: 5, // the number for the badge - anything non-zero triggers the badge
  alert: false // determines the badge color - false = info color, true = alert color
};
```

### Info badge
content app badge info

### Alert badge
content app badge alert

### Test controller
If you create the cake app from the [content app docs](https://our.umbraco.com/Documentation/Extending/Content-Apps/index-v8), replace the contents of `cakecontentapp.controller.js` with this:

```js
angular.module("umbraco")
    .controller("My.CakeContentApp", function ($scope, editorState, userService) {

        var vm = this;
        vm.CurrentNodeId = editorState.current.id;
        vm.CurrentNodeAlias = editorState.current.contentTypeAlias;

        var user = userService.getCurrentUser().then(function (user) {
            console.log(user);
            vm.UserName = user.name;
        });
		
		$scope.model.badge = {
			count: Math.floor(Math.random() * Math.floor(12)),
			alert: Math.random() > 0.5
		};
    });
```

It'll show random badges on the cake app icon with random severity (info/alert).

### CODE REVIEW

**Comment by ronaldbarendse** [comment]
@kjac You're doing some great additions, this is also looking good!

Just for extensibility, instead of `alert: [true|false]`, it would probably be better to use `type: '[info|warning|error]'` or something similar and default to `info` when not set. That way, adding more types/colors would be easy to do, as the type could be used as class and you'd only have to add some CSS.

**Comment by ronaldbarendse** [comment]
That's a valid point, although I think that responsibility should lie with the developer, not this implementation...

Currently, it's restricted to 2 notification types (info and alert), but Umbraco already has 5: https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Core/Events/EventMessageType.cs#L6-L13

Umbraco also has classes for badges and colors for the different types that could be used: https://github.com/umbraco/Umbraco-CMS/blob/1bb593d264a085f94a3ce3bd710392b350561430/src/Umbraco.Web.UI.Client/lib/bootstrap/less/labels-badges.less#L52-L69

Besides that, the type 'alert' would probably better be described as 'error', just to keep using the same terms within Umbraco.

It's easy just to go for the current implementation and merge it as-is, but that would probably cause problems later (extensibility, backwards-compatibility, etc.).

**Comment by kjac** [comment]
@ronaldbarendse I completely agree with the backwards compatibility issues, whey were also on my mind when I decided upon the boolean value. But I guess there's no harm done in replacing the `alert` with a `type` and add `info` and `warning` for the time being. I'll get on it soon.

**Comment by kjac** [comment]
Alright. So instead of `alert = true/false` we now have an optional `type = "warning"/"error"` for dark yellow and red badge colors respectively. Fallback when not defined is still the turquoise info color.

This means the JS to create a badge looks like this now: 

```js
$scope.model.badge = {
  count: 5, // the number for the badge - anything non-zero triggers the badge
  type: "warning" // optional: determines the badge color - "warning" = dark yellow, "alert" = red, anything else = turquoise ("info"-ish)
};
```

### The badge colors look like this
image


### Test controller
If you create the cake app from the [content app docs](https://our.umbraco.com/Documentation/Extending/Content-Apps/index-v8), replace the contents of `cakecontentapp.controller.js` with this:

```js
angular.module("umbraco")
    .controller("My.CakeContentApp", function ($scope, editorState, userService) {

        var vm = this;
        vm.CurrentNodeId = editorState.current.id;
        vm.CurrentNodeAlias = editorState.current.contentTypeAlias;

        var user = userService.getCurrentUser().then(function (user) {
            console.log(user);
            vm.UserName = user.name;
        });
        
        var count = Math.floor(Math.random() * Math.floor(12));
        $scope.model.badge = {
            count: count,
            type: count > 9 ? "alert" : count > 4 ? "warning" : null
        };
    });
```

**Comment by warrenbuckley** [comment]
Code changes look fine - but I will do some testing of this now

**Comment by warrenbuckley** [comment]
Yep all works good work @kjac 
Merged in

Tested with a simple button to ensure it would update the counter. So all good :)

```
vm.updateCounter = function () {
    vm.counter++;

    $scope.model.badge = {
        count: vm.counter,
        type: vm.counter > 9 ? "alert" : vm.counter > 4 ? "warning" : null
    };
};
```

**Comment by abjerner** [comment]
I know I'm a bit late to the party, and there's hardly any place for it in the UI - but would multiple badges make sense? Perhaps they become "stacked" when there is more than one?

For Umbraco 7 we have a property editor that shows quality assurance and accessibility issues reported by an external service. An issue here can be either an error, a warning or just an issue that requires review.

Ideally we should convert that property editor to a content app for Umbraco 8. As such, it would make sense to show the issues of a page using on or more badges.

Any thoughts on this?

As mentioned, if more than one badge, they could become stacked - eg. shown on top of each other, but each one moved slightly to the left so you could se that there is more than one, and then when you mouse over, they could move out and be displayed next to each other instead.

It might still be that the best solution is just to show a badge for the issue with the highest severity.

**Comment by kjac** [comment]
@abjerner anything is usually possible 😁 

Off the top of my head I can't think of any other application that has multiple badges on an icon. I'd hate for us to break with an industry standard... can you think of any? Because otherwise I'd say it makes most sense to show the badge with the highest severity.

**Comment by nul800sebastiaan** [comment]
But not everything SHOULD be possible. 😄 

The use case is interesting @abjerner and it would be good to find examples of well-established UX patterns for this, since I don't know of any. Sounds like information overload leading to.. no real information at all.

Even the counter inside the badge is already bothering me a bit at the moment, but that's more because it stresses people out.

**Comment by abjerner** [comment]
I don't really have any examples on this being used anywhere else. I just saw it as a scenario we could run into, and therefore thought I'd mention it here.

But as said, the best solution might be to show a badge for the issue with the highest severity. Your feedback confirms that 😉

**Comment by nul800sebastiaan** [comment]
@kjac Can you do `count = ""` at the moment? That should do it? But yeah I think it would be great to have a badge without count.

**Comment by kjac** [comment]
@nul800sebastiaan yeah `count = ""` does the trick. Not terribly intuitive though... I'll fix a new PR. CSS, here I come!

**Comment by warrenbuckley** [comment]
@kjac all merged in - can you do the Docs PR please  then I can merge that in too :)

**Comment by kjac** [comment]
@warrenbuckley sure thing: https://github.com/umbraco/UmbracoDocs/pull/1292

**Pull request merged**
