### PR TITLE
Add Swedish translations for prompt

### PR DESCRIPTION
**Pull request by rasolo**
### Prerequisites

- [ x] I have added steps to test this contribution in the description below

### Description

Added Swedish translations for the prompt lang section.

Unsaved changes before translation:
swe-translation-unsaved-changes_before-changes

Unsaved changes after translation:
swe-translation-unsaved-changes

Unpublished changes before translation:
swe-translation-unpublish-before-changes_

Unpublished changes after translation:

swe-translation-unpublish

### CODE REVIEW

**Comment by abjerner** [comment]
@rasolo thanks a lot - and congrats on your first pull request to Umbraco CMS 👍 🎉

My Swedish isn't super god, but this looks good to me 😉

**Comment by rasolo** [comment]
> @rasolo thanks a lot - and congrats on your first pull request to Umbraco CMS 👍 🎉
> 
> My Swedish isn't super god, but this looks good to me 😉

@abjerner Thanks, feels good! :D 

I believe I wrote good translations hehe :)

**Comment by nul800sebastiaan** [comment]
Thanks for your first contribution to CMS as well @rasolo - two repositories in one week, you're on fire! ;-)

My Swedish is even worse, so I'll trust you on this one, thanks!

**Comment by rasolo** [comment]
@nul800sebastiaan No worries! It's fun to contribute!

Thanks!

**Pull request merged**
