### PR TITLE
Block configuration adjustments

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
A few adjustments to the block configuration.

- Property info button overlapped label
- Most of property labels in overlay used `for="iconcolor"` which didn't make sense. For-attribute target the equivalent value in `id` attribute. Currently it doesn't really work for color picker component - ideally it should be a button element.
- Aligned trash icon in delete button.
- I have tried many different ways to stop event bubbling with using enter keypress on delete button in block card, but yet it triggered to card click event, which open the edit view of the block. However I found a workaround to set `ng-click="$event.stopPropagation()"` on parent wrapper + `tabindex="-1"` to not focus this element when navigating via keyboard. It seems to work as expected.

**Before**

https://user-images.githubusercontent.com/2919859/184993401-b82999cc-bcf0-40d7-9aa1-365b0111f86b.mp4

**After**

https://user-images.githubusercontent.com/2919859/184991483-2c257954-b2da-4b35-b516-7152d8cff1dc.mp4

### CODE REVIEW

**Comment by bjarnef** [comment]
@nielslyngsoe @nathanwoulfe I found a workaround to my old question here https://github.com/umbraco/Umbraco-CMS/pull/9062#issuecomment-703243882

Maybe not ideal, but it works 😄🎉
Alternatively the name could edit/open the dialog and not the entire box.. or a background layer and on top of that the actions button. That way the click event wouldn't bubble to parent click event.

**Comment by nielslyngsoe** [comment]
Big thanks @bjarnef  really important things to get corrected!
I'm off to test this :-)

**Comment by bjarnef** [comment]
@nielslyngsoe can we close this one if it has been resolved in this PR? https://github.com/umbraco/Umbraco-CMS/pull/13220

**Comment by nul800sebastiaan** [comment]
Just merged this with the latest to see the effect on this PR and indeed everything was already up to date as Niels said, so closing this one.

**Pull request closed without merging**
