### PR TITLE
U4-5523: Move change password dasboard to user flyout

### PR DESCRIPTION
**Pull request by arknu**
Having the Change password option as a Dashboard is both illogical and very confusing. This PR moves it to the User flyout, where it makes more sense.
The styling works, but could probably use some polish. I went with reusing the existing editor rather than duplicating it, which makes it more difficult to style.

### CODE REVIEW

**Comment by arknu** [comment]
Updated the PR to 7.3 (only a couple of merge issues).

**Comment by rasmuseeg** [comment]
Cool!

**Comment by Shazwazza** [comment]
I promise I'll review this soon... but i cannot promise it will make the initial 7.3.0 release since we might not have time and it will require to be polished up. We could still release it before 7.4 though.

**Comment by madsrasmussen** [comment]
Thank you so much! I have merged your changes into 7.4 and added some small 7.4 changes on top. #H5YR

**Pull request closed without merging**
