### PR TITLE
Fix dropdown validation

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/3500

### Description

#3500 outlines the steps to reproduce/test. 

As mentioned on the issue, this is also a problem for content and media, although slightly smaller for content because the validation error caught on publish. But it makes sense to enforce it on save.

This fix only makes the mandatory validation work. The regex validations won't work for members or media, since they're only evaluated on publish (which is only for content).

A demo of the fix:

dropdown validation

...as you can see, the same problem exists for checkbox lists. I'll have a look at fixing that next.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @kjac 

Thanks for the PR, we'll be in touch soon if we need anything, as ever.

Emma

**Comment by emmaburstow** [comment]
Onto this one!

Em

**Comment by kjac** [comment]
Whoo! 🎉

**Comment by nul800sebastiaan** [comment]
Thank you so much @kjac 🙏

**Pull request merged**
