### PR TITLE
U4-8990 Updated Dutch Language File

### PR DESCRIPTION
**Pull request by ArnoldV**
This updates the Dutch language file with new/missing translations and fixes some wrong translations used by the grid, probably caused by grid changes since when the grid was introduced.

### CODE REVIEW

**Comment by clausjensen** [comment]
Issue here: http://issues.umbraco.org/issue/U4-8990

**Comment by clausjensen** [comment]
And thanks for the PR @ArnoldV :+1:

**Comment by ArnoldV** [comment]
Updated this pull request with ALL the missing fields translated that are in the EN translation file.

**Comment by nul800sebastiaan** [comment]
Thanks!! 👍

**Comment by bjarnef** [comment]
@clausjensen @nul800sebastiaan would it be easier if these kind of PR's get the "localization" label here and maybe `Type: Localization` on the issue tracker? :sunglasses:

**Pull request merged**
