### PR TITLE
Simplified setup of 2FA for users

### PR DESCRIPTION
**Pull request by bergmania**
## Summary 
This PR makes it easier to enable 2FA for users.

## Details
- If no 2fa providers is enabled, nothing is changed
- If any 2fa is enabled
   - Users can enable 2FA on their own user
   - Users can disable 2FA on their own user, by the code from the authenticator
   - Users with access to the users section can disable 2FA on other users without code
- The user overlay is converted to an infinite editor to support the 2fa configuration editor to open on top
   - The introduction tour + cypress test has been adjusted accordingly
   - The log out button has been moved to the footer of the infinite editor for better UX + to allow for more buttons in the user profile section
   
   
## Appendix
The following changes was added to test

### Umbraco.Web.UI\Umbraco.Web.UI.csproj
Added the following nuget package
```xml
<PackageReference Include="GoogleAuthenticator" Version="2.5.0" />
```

### Umbraco.Web.UI\App_Plugins\TwoFactorProviders\package.manifest
New file added
```json
{
  "javascript": [
    "~/App_Plugins/TwoFactorProviders/twoFactorProviderGoogleAuthenticator.controller.js"
  ]
}
```

### Umbraco.Web.UI\App_Plugins\TwoFactorProviders\twoFactorProviderGoogleAuthenticator.html
New file added
```html
<div ng-controller="CustomCode.TwoFactorProviderGoogleAuthenticator as vm">

  <umb-editor-view ng-cloak>

    <form name="vm.authForm" method="POST" ng-submit="vm.validateAndSave()">

      <umb-editor-header name="vm.title" name-locked="true" hide-alias="true" hide-icon="true" hide-description="true">
      </umb-editor-header>

      <umb-editor-container>

        <umb-box>

          <umb-box-header title="Setup information"></umb-box-header>

          <umb-box-content>

            <div class="control-group text-center">
              <img alt="QR code for Google Authenticator" ng-src="{{vm.qrCodeImageUrl}}" ng-if="vm.qrCodeImageUrl" />
            </div>

            <umb-control-group label-for="token" alias="2facode"
              label="Scan with your authenticator app and enter the code:" required="true">

              <input umb-auto-focus id="2facode" class="-full-width-input input-xlarge" type="text" name="token"
                inputmode="numeric" autocomplete="one-time-code" ng-model="vm.code" localize="placeholder"
                placeholder="@login_2faCodeInputHelp" aria-required="true" required />

              <div ng-messages="vm.authForm.token.$error" role="alert">
                <span class="umb-validation-label" ng-message="token">
                  <localize key="login_2faInvalidCode">Invalid code entered</localize>
                </span>
              </div>

            </umb-control-group>

          </umb-box-content>

        </umb-box>

      </umb-editor-container>

      <umb-editor-footer>

        <umb-editor-footer-content-right>

          <umb-button type="button" button-style="link" label-key="general_close" shortcut="esc" action="vm.close()">
          </umb-button>

          <umb-button state="vm.buttonState" button-style="success" label-key="buttons_save" type="submit"
            disabled="vm.code.length === 0">
          </umb-button>

        </umb-editor-footer-content-right>

      </umb-editor-footer>

    </form>

  </umb-editor-view>

</div>
```

### Umbraco.Web.UI\App_Plugins\TwoFactorProviders\twoFactorProviderGoogleAuthenticator.controller.js
New file added
```js
!(function () {
  "use strict";

  const googleTwoFactorProviderCtrl = [
    '$scope', 'twoFactorLoginResource', 'notificationsService',
    function ($scope, twoFactorLoginResource, notificationsService) {
      const vm = this;

      vm.title = "Setup Google Authenticator on " + $scope.model?.user?.name;
      vm.providerName = $scope.model?.providerName;
      vm.qrCodeImageUrl = "";
      vm.secret = "";
      vm.code = "";
      vm.authForm = {};
      vm.buttonState = "init";

      vm.close = close;
      vm.validateAndSave = validateAndSave;

      function init() {
        vm.buttonState = "init";
        twoFactorLoginResource.setupInfo(vm.providerName)
          .then(function (response) {
            // This response is the model I defined to be returned from ITwoFactorProvider.GetSetupDataAsync
            vm.qrCodeImageUrl = response.qrCodeSetupImageUrl;
            vm.secret = response.secret;
          })
          .catch(function () {
            notificationsService.error("Could not fetch login info");
          });
      }

      function validateAndSave() {
        vm.authForm.token.$setValidity("token", true);
        vm.buttonState = "busy";

        twoFactorLoginResource.validateAndSave(vm.providerName, vm.secret, vm.code)
          .then(function (successful) {

            if (successful) {
              notificationsService.success("Two-factor authentication has successfully been enabled");
              vm.buttonState = "success";
              close();
            } else {
              vm.authForm.token.$setValidity("token", false);
              vm.buttonState = "error";
            }

          })
          .catch(function (error) {
            notificationsService.error(error);
            vm.buttonState = "error";
          });
      }

      function close() {
        if ($scope.model.close) {
          $scope.model.close();
        }
      }

      init();
    }
  ];

  angular.module("umbraco").controller("CustomCode.TwoFactorProviderGoogleAuthenticator", googleTwoFactorProviderCtrl);
})();
```

### Umbraco.Web.UI\DemoCode.cs
New file added.
This file has a composer setting up a Google Authenticator and pointing to the custom view to show when setting up the 2FA.
```cs
using System;
using System.Runtime.Serialization;
using System.Threading.Tasks;
using Google.Authenticator;
using Microsoft.Extensions.DependencyInjection;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.DependencyInjection;
using Umbraco.Cms.Core.Security;
using Umbraco.Cms.Web.BackOffice.Security;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.UI
{
    public class TwoFactorAuthenticationComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            var identityBuilder = new BackOfficeIdentityBuilder(builder.Services);

            identityBuilder.AddTwoFactorProvider<UmbracoAppAuthenticator>(UmbracoAppAuthenticator.Name);

            builder.Services.Configure<TwoFactorLoginViewOptions>(UmbracoAppAuthenticator.Name, options =>
            {
                options.ViewPath = "..\\App_Plugins\\TwoFactorProviders\\twoFactorProviderGoogleAuthenticator.html";
            });
        }
    }

    /// <summary>
    /// App Authenticator implementation of the ITwoFactorProvider
    /// </summary>
    public class UmbracoAppAuthenticator : ITwoFactorProvider
    {
        /// <summary>
        /// The unique name of the ITwoFactorProvider. This is saved in a constant for reusability.
        /// </summary>
        public const string Name = "GoogleAuthenticatorUsers";

        /// <summary>
        /// The unique provider name of ITwoFactorProvider implementation.
        /// </summary>
        /// <remarks>
        /// This value will be saved in the database to connect the member with this  ITwoFactorProvider.
        /// </remarks>
        public string ProviderName => Name;

        /// <summary>
        /// Returns the required data to setup this specific ITwoFactorProvider implementation. In this case it will contain the url to the QR-Code and the secret.
        /// </summary>
        /// <param name="userOrMemberKey">The key of the user or member</param>
        /// <param name="secret">The secret that ensures only this user can connect to the authenticator app</param>
        /// <returns>The required data to setup the authenticator app</returns>
        public Task<object> GetSetupDataAsync(Guid userOrMemberKey, string secret)
        {

            var twoFactorAuthenticator = new TwoFactorAuthenticator();
            SetupCode setupInfo = twoFactorAuthenticator.GenerateSetupCode("My application name", "TEST", secret, false);
            return Task.FromResult<object>(new TwoFactorAuthInfo()
            {
                QrCodeSetupImageUrl = setupInfo.QrCodeSetupImageUrl,
                Secret = secret
            });
        }

        /// <summary>
        /// Validated the code and the secret of the user.
        /// </summary>
        public bool ValidateTwoFactorPIN(string secret, string code)
        {
            var twoFactorAuthenticator = new TwoFactorAuthenticator();
            return twoFactorAuthenticator.ValidateTwoFactorPIN(secret, code);
        }

        /// <summary>
        /// Validated the two factor setup
        /// </summary>
        /// <remarks>Called to confirm the setup of two factor on the user. In this case we confirm in the same way as we login by validating the PIN.</remarks>
        public bool ValidateTwoFactorSetup(string secret, string token) => ValidateTwoFactorPIN(secret, token);
    }

    [DataContract]
    public class TwoFactorAuthInfo
    {
        [DataMember(Name = "qrCodeSetupImageUrl")]
        public string QrCodeSetupImageUrl { get; set; }

        [DataMember(Name = "secret")]
        public string Secret { get; set; }
    }
}
```

### CODE REVIEW

**Comment by iOvergaard** [comment]
Suggestions for appendix code:

### Umbraco.Web.UI\App_Plugins\TwoFactorProviders\twoFactorProviderGoogleAuthenticator.html
```html
<div ng-controller="CustomCode.TwoFactorProviderGoogleAuthenticator as vm">

  <umb-editor-view ng-cloak>
    <umb-editor-header name="vm.title" name-locked="true" hide-alias="true" hide-icon="true" hide-description="true">
    </umb-editor-header>

    <umb-editor-container>
      <umb-box>
        <umb-box-content>
          <umb-box-header title="Setup information"></umb-box-header>

          <div class="control-group text-center">
            <img alt="QR code" ng-src="{{vm.qrCodeImageUrl}}" ng-if="vm.qrCodeImageUrl" />
          </div>

          <label>
            <p>Scan the code above with your authenticator app and enter the resulting code here to validate:</p>
            <input class="-full-width-input input-xlarge" type="text" name="token" inputmode="numeric"
              autocomplete="one-time-code" aria-required="true" ng-model="vm.code" localize="placeholder"
              placeholder="@login_2faCodeInputHelp" no-dirty-check />
          </label>

        </umb-box-content>

      </umb-box>

    </umb-editor-container>

    <umb-editor-footer>
      <umb-editor-footer-content-left>
        <umb-button button-style="success" label-key="buttons_save" type="button" disabled="vm.code.length === 0"
          action="vm.validateAndSave()" shortcut="enter">
        </umb-button>
      </umb-editor-footer-content-left>

      <umb-editor-footer-content-right>
        <umb-button type="button" button-style="link" label-key="general_close" shortcut="esc" action="vm.close()">
        </umb-button>

      </umb-editor-footer-content-right>

    </umb-editor-footer>

  </umb-editor-view>

</div>
```

### Umbraco.Web.UI\App_Plugins\TwoFactorProviders\twoFactorProviderGoogleAuthenticator.controller.js

```js
'use strict';

const googleTwoFactorProviderCtrl = [
  '$scope', 'twoFactorLoginResource', 'notificationsService',
  function ($scope, twoFactorLoginResource, notificationsService) {
    const vm = this;

    vm.title = "Setup Google Authenticator on " + $scope.model?.user?.name;
    vm.providerName = $scope.model?.providerName;
    vm.qrCodeImageUrl = "";
    vm.secret = "";
    vm.code = "";

    vm.close = close;
    vm.validateAndSave = validateAndSave;

    function init() {
      twoFactorLoginResource.setupInfo(vm.providerName)
        .then(function (response) {
          // This response is the model I defined to be returned from ITwoFactorProvider.GetSetupDataAsync
          vm.qrCodeImageUrl = response.qrCodeSetupImageUrl;
          vm.secret = response.secret;
        })
        .catch(function () {
          notificationsService.error("Could not fetch login info");
        });
    }

    function validateAndSave() {
      twoFactorLoginResource.validateAndSave(vm.providerName, vm.secret, vm.code)
        .then(function (successful) {

          if (successful) {
            notificationsService.success("Two-factor authentication has successfully been enabled");
            close();
          } else {
            notificationsService.error("There seems to be a problem with the code you entered");
          }

        })
        .catch(function (error) {
          notificationsService.error(error);
        });
    }

    function close() {
      if ($scope.model.close) {
        $scope.model.close();
      }
    }

    init();
  }
];

angular.module("umbraco").controller("CustomCode.TwoFactorProviderGoogleAuthenticator", googleTwoFactorProviderCtrl);
```

**Comment by shearer3000** [comment]
hi - will this ticket mean having to use the google authenticator? what if you don't want to use the google authenticator for back office users and want to use email instead? thanks
https://our.umbraco.com/forum/using-umbraco-and-getting-started/108385-2fa-two-factor-authentication-for-umbraco-user

**Comment by iOvergaard** [comment]
> hi - will this ticket mean having to use the google authenticator? what if you don't want to use the google authenticator for back office users and want to use email instead? thanks https://our.umbraco.com/forum/using-umbraco-and-getting-started/108385-2fa-two-factor-authentication-for-umbraco-user

@shearer3000 No, this will simply give you (as the developer) the option to add any multi-factor authentication you would like to your backoffice users. Or none at all. Completely up to you. The default is and was email/password ☺️

**Comment by iOvergaard** [comment]
@bergmania it looks like you get all providers at the login screen even though only one are enabled (if you hava multiple providers). Any chance of filtering the inactive ones away from the screen?

**Pull request merged**
