### PR TITLE
UmbSessionStorage: Make sure key exists before using it as a JSON string

### PR DESCRIPTION
**Pull request by nielslyngsoe**
Fixes https://github.com/umbraco/Umbraco-CMS/issues/8035

### CODE REVIEW

**Comment by bjarnef** [comment]
@nielslyngsoe https://github.com/umbraco/Umbraco-CMS/pull/8014 also fixes this although it would be great with check if the key exists.

**Comment by nielslyngsoe** [comment]
@bjarnef great. I think we should have both.

**Comment by bjarnef** [comment]
If `storage["umb_" + key]` is null, undefined, an object it just return this value :)

**Comment by bjarnef** [comment]
I think the changes in this PR would return null if `storage["umb_" + key]` was `0` or `false`.

**Comment by nielslyngsoe** [comment]
@bjarnef I think you are right, let me have another look.

**Comment by bjarnef** [comment]
The changes in PR #8014 does the same as in `angular.fromJson()` so it should break anything of the existing behaviour.

**Comment by nielslyngsoe** [comment]
@bjarnef good point, lets keep existing as-is. It would just have been nicer to be consistent in terms of whether you get null or undefined back. But I will save that for another day.

**Pull request closed without merging**
