### PR TITLE
V8: Don't cast IContent to Content in DocumentRepository

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/4234

### Description

This is a brave attempt at keeping `DocumentRepository` from casting `IContent` to `Content`. 

See #4234 for more info.

### CODE REVIEW

**Comment by Shazwazza** [comment]
What we'd like to do is essentially move the `UpdatingEntity` and `AddingEntity` methods to extension methods since they are really just helper methods to update the model properties. Those model properties should all now be public get/set. Then we don't want to cast or type check at all. There's a bunch of these types of places throughout the codebase that we'd like to cleanup but we can still do that in 8.x releases.

**Comment by kjac** [comment]
Thanks for the feedback! I'll update the PR to get rid of the last type casts.

**Comment by kjac** [comment]
@Shazwazza I gave it another look and found a few things:

1. `UpdatingEntity` and `AddingEntity` are virtual methods, overridden by `Member`. Replacing them when extension methods requires a bit of patching up in the member repository to mediate the added functionality in the current overrides.
2. The methods rely on functionality from both `IEntity` and `ICanBeDirty`. The extension methods would be built upon `IEntity`, so they would need to do some type casting to continue to apply the current dirty checking.

I did a quick test with this implementation and it *can* work once I update a bunch of usings:

```cs
internal static class EntityExtensions
{
  internal static void UpdatingEntity(this IEntity entity)
  {
    var now = DateTime.Now;

    // just in case
    if (entity.CreateDate == default) {
      entity.CreateDate = now;
    }

    // set the update date if not already set
    if (entity.UpdateDate == default || (entity is ICanBeDirty canBeDirty && canBeDirty.IsPropertyDirty("UpdateDate") == false)) {
      entity.UpdateDate = now;
    }
  }

  internal static void AddingEntity(this IEntity entity)
  {
    var now = DateTime.Now;
    var canBeDirty = entity as ICanBeDirty;

    // set the create and update dates, if not already set
    if (entity.CreateDate == default || canBeDirty?.IsPropertyDirty("CreateDate") == false) {
      entity.CreateDate = now;
	}
    if (entity.UpdateDate == default || canBeDirty?.IsPropertyDirty("UpdateDate") == false) {
      entity.UpdateDate = now;
	}
  }
}
```

Thoughts?

**Comment by Shazwazza** [comment]
Hi @kjac, I think this is much much nicer. I know this includes some type checking but it doesn't actively require casting and will support any underlying model that supports those properties (which are public get/set after all) :)

**Comment by kjac** [comment]
@Shazwazza all done ... and I even did a bunch of cleanup throughout the repositories to remove the now redundant casts to `EntityBase` 😄

**Comment by kjac** [comment]
Resolved merge conflicts

**Comment by nul800sebastiaan** [comment]
Merging this now, although I saw we recently added a new cast (https://github.com/umbraco/Umbraco-CMS/pull/4611/files#diff-cc8e38dcfcf87a6af166bc1eb33c814eR442). We can deal with that one later though, we need these changes in now to make sure we can document the changes.

**Pull request merged**
