### PR TITLE
Use SVG logo in installer/upgrader

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12908

### Description
This PR change the logo in upgrader from the bitmap logo to a vector logo instead making the logo sharp on screens with a device pixel ratio greather than 1.

**Before**

image

**After**

image

Hint: Open the two images above in two separate tabs and switch between these to see the difference.

### CODE REVIEW

**Comment by bjarnef** [comment]
@nielslyngsoe @iOvergaard let's make this (c)sharp! 🥁😅

**Review by iOvergaard — COMMENTED** [review]
LGTM, but should we add the extra parameters width, height, and draggable to the other logos as well in umb-app-header and BootFailed, @bjarnef ?

**Comment by bjarnef** [comment]
@iOvergaard we probably could, but currently its size in handled via CSS:
https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Web.UI.Client/src/less/components/application/umb-app-header.less#L15

https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Web.UI.Client/src/views/components/application/umb-app-header.html#L9-L12

https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Web.UI.Client/src/views/errors/BootFailed.html#L48-L49

**Comment by bjarnef** [comment]
@iOvergaard I have modified this as well.

**Review by iOvergaard — APPROVED** [review]

**Pull request merged**
