### PR TITLE
Add health checks results to payload

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
Update the `HealthCheckCompletedWebhookEvent`. Add the health check results to the payload. 

Before: 
image

After: 
image

Test: 

- Add a composer 
```csharp
public class WebhookComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.WebhookEvents().AddCms();
    }
}
```
- Configure a Health Check Completed webhook: 

image

- Run one or multiple health checks

### CODE REVIEW

**Comment by georgebid** [comment]
Hey @erikjanwestendorp thanks a lot for your PR, someone on the core collaborators team will review this soon 😸

**Comment by busrasengul** [comment]
Hey @erikjanwestendorp, I tested this and it does work, although the json data comes back within response and the structure doesn't fully match what you share, mind that, there have been some changes since this PR.
So would you be able to sync this PR with the latest state and test it again for me, if I'm doing something wrong or the response I'm seeing is correct?
image
Thank you :)

**Comment by erikjanwestendorp** [comment]
@busrasengul Thanks for your review! Updated the PR. contrib is merged to this branch.

**Comment by busrasengul** [comment]
Thank you @erikjanwestendorp 
Let's get this merge in!

**Pull request merged**
