### PR TITLE
Fix log search dropdown alignment + match search button style with Examine dashboard

### PR DESCRIPTION
**Pull request by matthew-darby**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/4656

### Description

- Go to Log Viewer > All Logs
- Type in the search
- Search icons now correctly right aligned, and the button matches the style of the examine search button
- Dropdown is correctly aligned in the search rather than underneath

snippet

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @matthew-darby,

Thanks for the PR! One of us will take a look at the work and let you know if we need any changes. 

Emma, [Pull Request team](https://umbraco.com/blog/introducing-the-new-pr-team/)

**Comment by nul800sebastiaan** [comment]
@matthew-darby As @poornimanayar points out, we now have a stylesheet for this, any chance you can update this PR please? Thanks!

**Comment by matthew-darby** [comment]
Hey @poornimanayar and @nul800sebastiaan , sorry for the delay - I won't have time at the moment to resolve this.

There are quite a few inline styles outside of my additions, so might be worth moving those too if anyone else can pick this up :)

**Comment by poornimanayar** [comment]
I can pick this up if you can let your PR accept changes from contributors

**Comment by matthew-darby** [comment]
> I can pick this up if you can let your PR accept changes from contributors

Thanks @poornimanayar, it should be enabled, unless I am looking in the wrong place?

Capture

**Comment by poornimanayar** [comment]
Cheers, I ll be on it over the weekend :-)

**Comment by poornimanayar** [comment]
@nul800sebastiaan  looks like the work was already done and merged into the dev branch with this [commit](https://github.com/umbraco/Umbraco-CMS/commit/31e4701487d5c78da2af4145f520b81334ad014d#diff-144204f44d67201e4a96574595d21b13)

**Comment by nul800sebastiaan** [comment]
Ah right, yes, this problem has been fixed elsewhere, hard to keep track of everything sometimes!

Sorry @matthew-darby - it's a lovely update and we appreciate the work very much! I'll close this one. 

Once again apologies, we're slowly getting better at all tying together all the moving parts but sometimes one slips through. Hope to see more of your lovely work soon Matthew! 👍

**Pull request closed without merging**
