### PR TITLE
7058 NullOrEmpty check to fix Grid in NestedContent

### PR DESCRIPTION
**Pull request by joepvtl**
See #7058 for more info about this issue.

If you have a Grid in a NestedContent item and use this item in a node. When you leave the Grid empty and save the node, it will give a nullref exception because in the database it gets set to null.

To test this make a NestedContent datatype which has a Grid. Then use the item on a node and save it. Then it will give the error.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Joe! Nice work!Congrats on your first PR. If you have an Our.Umbraco.Com profile, let us know the name and you'll get a shiny new contributor badge once this is merged.

**Comment by joepvtl** [comment]
Thanks! Here is my profile : https://our.umbraco.com/members/id:276243/

**Comment by joepvtl** [comment]
Hey @kjac , I changed the code to what you requested.

**Comment by kjac** [comment]
@joepvtl thanks a lot 👍 I'll get on it

**Comment by kjac** [comment]
Merged 👍 thanks again!

**Pull request merged**
