### PR TITLE
Revert "Removing X-XSS-Protection healthcheck"

### PR DESCRIPTION
**Pull request by Zeegaan**
Reverts https://github.com/umbraco/Umbraco-CMS/pull/13046 as it contained a breaking change, the pipelines should finally not error out 👍

### CODE REVIEW

**Review by nikolajlauridsen — APPROVED** [review]

**Comment by mikecp** [comment]
Argh, this was creating the build pipeline errors?

**Comment by Zeegaan** [comment]
@mikecp Yes exactly 👍 You might have to merge contrib into some of the open PRs to not have them error out

**Comment by mikecp** [comment]
OK Thx @Zeegaan !
Sorry I missed that one, usually I check on the pipelines etc. prior to merging but apparently I forgot that time...

**Comment by Zeegaan** [comment]
@mikecp Happens to all of us, don't worry 😅 😅

**Pull request merged**
