### PR TITLE
3324 - Suggestion: Align image cropper property editor UI with color picker and checkbox lists

### PR DESCRIPTION
**Pull request by BatJan**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues/3324) for the proposed changes in this PR, the link is: https://github.com/umbraco/Umbraco-CMS/issues/3324
- [x] I have added steps to test this contribution in the description below

### Description

The UI for defining crops on an image cropper property editor is a bit out of date and out of touch with the current UI. Therefore I'm currently working on aligning it a bit more with what we currently have when defining color pickers, checkbox lists etc.

I think I'm done with this PR - Below examples on before and after can be seen. If this PR is accepted then please let me know if I should spend some extra time removing the dictionary items, which are no longer in use because of these changes before the PR is merged - Currently there still is some code that is commented out, which is used for a heading and some text description. This should of course be deleted but keeping it for now to remember, which translation keys that maybe need to be deleted. The deletions can of course be done in another PR but it might be better to have it done in this one.

**Editor experience before**
crop-prop-editor-before

**Editor experience after**
crop-prop-editor-after

### CODE REVIEW

**Comment by BatJan** [comment]
Hey @bjarnef - Yes I did consider doing that too but would await some feedback. But since you have the same thought I think it's worth doing. 😃 

The "Sizes" is not a label but a paragraph. It used to be a label, but it's inconsistent to only have a label for the width input type and not for the height. So added those but with a "visuallyhidden" class to allow for them being there in a non-visual context. But moving it all to the same line then showing the labels instead of "Sizes" is probably a better approach 👍 - Also I think some of the wording needs a little improvement + a description under "Crop sizes" should be added.

I'll give it a go later. Thanks for the input mate 👌

**Comment by BatJan** [comment]
Just comitted the code so instead of having the input fields and controls in 2 rows they're now all in 1 row.

I also removed the code that was commented out.

Still need to fix the following
-  Responsiveness of input fields and controls
- Add description text below "Crop sizes"
- Modify "Crop sizes" text to "Define crops"
- Maybe remove language keys from .xml files depending on @nul800sebastiaan take on this 😃

**Comment by BatJan** [comment]
Ok, so now I have implemented the changes mentioned above and now the image cropper UI looks and behaves like shown in this GIF

crop-prop-editor-round-2

My only concern about this is that whenever one has a narrow screen window the cancel action won't be able to fit on one line and will therefore be pushed below the "Update" action, which makes it a little jumpy. This is illustrated late in the video when i narrow my window. A solution can be to use a close icon instead with a title that says "Cancel" on hover...But I kinda like the text version better and I think it might be more consitent with the UI in general if I remember correctly - Any thoughts on this? @bjarnef  - I can imagine you have some 😃   Or is it ok the way it is now? It can always be improved later on if it's a real issue for people.

Uh, actually one more concern! Should I hide the labels visually?

**With labels**
with-labels

**Without labels**
without-labels

Apart from that the only thing I need to know is whether or not I should delete the language keys that are no longer in use as a consequence of this change (If it gets accepted of course). @nul800sebastiaan

**Comment by bjarnef** [comment]
@BatJan for narrow screen I would move clear the line after alias field, so with, height and the action buttons are aligned.

**Comment by BatJan** [comment]
@bjarnef Good suggestion about the min and pattern attributes - They're now added 😃 

I also had a play with the responsive issues - I think it works quite nicely now? :)

responsiveness

**Comment by bjarnef** [comment]
Very nice @BatJan :ok_hand:
Maybe the "alias" input should have a width on narrow screens (or allow grow on larger screens), so it doesn't fill full width?

**Comment by BatJan** [comment]
Thanks @bjarnef 😃 

I think it looks a bit weird if it does not take up all the space but as it is now it also looks a bit heavy - But maybe I should at least align it with the end of the "Height" input field instead? That's probably better...Will take a look later 👍

**Comment by nul800sebastiaan** [comment]
Looks pretty good so far @BatJan!

Yep, please delete language keys if you're very sure they're not used any more! 👍 

One thing however: it doesn't do the appropriate resizing when you edit the datatype from the doctype editor:

image

**Comment by BatJan** [comment]
@nul800sebastiaan I have fixed the styling in the overlay view - Thanks for pointing that out. I keep forgetting about it for some reason 🤔 

I deleted the 2 translations keys as well. I searched the entire project and the only matches I got was in the translation files - Before it only got used for the text in the prevalue editor, which has now been obsoleted and removed by the changes I have made so everything should be good 😃

**Comment by nul800sebastiaan** [comment]
Great work @BatJan ! 👍 🎉 🏅

**Pull request merged**
