### PR TITLE
Nested content UI fixes

### LINKED ISSUE #9393: Nested Content in Single Item mode looks broken
## Umbraco version

I am seeing this issue on Umbraco version: 8.9.0

Either it lacks some padding, or the border should be removed.

### Steps to reproduce

Add Nested Content property in Single Item Mode (set min AND max items to 1)

### Expected result

Expected it to look better. I would suggest without the border.

### Actual result

image

### PR DESCRIPTION
**Pull request by callumbwhyte**
Since the Block List was introduced in 8.7 the styles for Nested Content have been a little out of whack... This PR addresses some of these issues!

Icons in the header of each content item were already a little out of line in 8.6 versions:

nested-content-8 6 4

But it got a little worse in 8.7+ - needs to be more to the right and down a bit:

nested-content-8 9 1

Equally, using Nested Content in single mode in 8.6 looks like this:

single-nested-content-8 6 4

In 8.7+ the border is added, making it look cramped.

single-nested-content-8 9 1

## Changes

My changes do the following:

- Change the Nested Content header to use `flex` for easier alignment
- Bump the Nested Content item icons down by `3px`
- Remove the border from Single Nested Content items

The end results look like this:

nested-content-fixed

And here's the single Nested Content item:

single-nested-content-fixed

Fixes #9393

### CODE REVIEW

**Comment by skttl** [comment]
Thanks, this fixes #9393 :)

**Comment by nul800sebastiaan** [comment]
@callumbwhyte Just a heads up and an apology, I was doing some work with the core collabs team yesterday and I merged this wrong, so the text is a bit too far left aligned, overlapping with the icons. I'll come back to fix it! 🙈

**Comment by ronaldbarendse** [comment]
Part of this PR might already be fixed in https://github.com/umbraco/Umbraco-CMS/pull/9024, but these are great UI fixes 🎉

**Comment by callumbwhyte** [comment]
Welcome back @madsrasmussen ;-)

**Comment by madsrasmussen** [comment]
I have tested this and it looks good 🎉  I have fixed a small issue with overlapping text and icon in nested content with multiple items. 

I have made a short video with a Nested content (Single Mode), Nested Content (Multiple), and two Block Lists. They all look pretty good to me.

https://user-images.githubusercontent.com/6078361/104457776-c2723d00-55aa-11eb-9f40-7d13e9224c74.mp4

**Comment by madsrasmussen** [comment]
> Welcome back @madsrasmussen ;-)

Thanks @callumbwhyte . You were fast 😄

**Review by madsrasmussen — APPROVED** [review]

**Comment by nul800sebastiaan** [comment]
**Note:** This didn't make it into the 8.11.0-RC build but will be in the final build of 8.11.0.

**Pull request merged**
