### PR TITLE
Feature indicate custom crop

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is: https://github.com/umbraco/Umbraco-CMS/issues/2932
- [x] I have added steps to test this contribution in the description below

### Description
This PR adds a visual indication if an image crop is overridden, as explained/requested in #2932.

To test:

1. Make sure you have defined crops on the Image Cropper data type for the Media item
2. Upload a new image
3. Edit one of the crops and save the edit
4. Notice the little green indicator in the upper right corner of the edited crop
5. Reset the edited crop
6. Ensure that the indicator isn't visible anymore

image cropper custom crop indicator

**Note:** The indicator shows immediately after you've opened a crop for editing. That's because the moment you edit one, a custom crop is created. Even if you don't do any editing to the crop, it's saved and disconnected from the main image (unless you choose "reset" in the crop editor). I'm going to have a look at improving this UX a bit in another PR 😄

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
@kjac The idea of this change is actually a really good one, the UX does need a bit of work indeed!

Somehow the UX needs to express: "you've make a custom crop on this specific item so moving the focal point around is not going to update this preview". I currently have no ideas to offer to be honest but maybe you can think about it some more. I'll discuss how this could be done at HQ as well when I get a chance!

**Comment by kjac** [comment]
@nul800sebastiaan given the tiny bit of space available in the crop preview, I kinda think the badge/indicator approach outlined above is a feasible solution. It's not exactly self explanatory, but hopefully the editors will learn to recognize it.

I tried icons (lock, pen, ...) and explanatory text, none of which seemed to work any better. But if you guys can come up with some golden solution... by all means!

**Comment by mortenbock** [comment]
A couple of ideas:

- The classic padlock I think is regularly used to indicate stuff like "locked aspect ratio" in imaging software. So that could be used to indicate if a crop is "restricted".
- Some other sort of "connected/disconnected" icon. Maybe a "sync" and "sync with red line" icon?
- Dimming the crops that are in sync with the main image may also give a good indication the un-dimmed crops are "custom", and not automatic.

**Comment by dawoe** [comment]
Like @mortenbock suggets a padlock (icon-lock) would make more sense to me. Maybe in combination with some dimming of the custom ones...because these are the ones that don't change when you change the focal point

**Comment by nul800sebastiaan** [comment]
The lock seems to make a bit more sense but then again: you can  still click it and update the custom crop. And what does it mean to an editor who has just opened the backoffice for the first time? They are able to move the focal point for one cropper and all the crops will update their preview, except for the locked one, how do I discover that I came into this locked state and why is it locked and what does a lock have to do with creating a custom crop? 

Just a few questions to consider.. :-)

**Comment by dawoe** [comment]
Although i don't like it personally...you could divide the list in crops that are based on focal point and crops that are custom.

An icon alone will never be enough for new editors

**Comment by mortenbock** [comment]
What if call them "automatic" and "custom" crops? Could we make a good indication the tells the user that something is automatic? Or maybe put a little explanation at the top/bottom with what the icons mean?

It could also just have an "auto" label, if it is automatic, and no label if it is not. And then the "reset" button should be "auto crop" instead.

**Comment by kjac** [comment]
I'm fine with whatever the majority decides 🙂 but the lock should be used with care. After all it does symbolize "locked", which may not be the message we want to send here.

Here's another thought. Could the blue focal point be reused as an indicator of sorts?

**Comment by kjac** [comment]
I don't know... it sounded like a good idea in my head 🤔 but it's not entirely evident what all the blueish dots do:

image

**Comment by nul800sebastiaan** [comment]
I think the message for this thing should be: icons don't work. :-)

I kinda want to separate the custom vs. the auto crops as well, but there's little space.

**Comment by kjac** [comment]
Could be a way to go after all:

image

**Comment by marcemarc** [comment]
How about a 'picture frame' 
image around the box with the overridden crop?

**Comment by nul800sebastiaan** [comment]
@kjac Looks okay actually.. wonder how it would look with a landscape image like this one:

**Comment by hartvig** [comment]
Brilliant, @kjac. Clear, to the point and as a user I don’t need to spend energy wondering what the interface means (thus I can spend it on my work) 👏

**Comment by kjac** [comment]
@nul800sebastiaan it looks as expected, I guess... but definitively still useful (it's mocked up so disregard the same crops being showed twice):

image

@hartvig thanks 👍

**Comment by nul800sebastiaan** [comment]
@kjac Makes sense and looks good, though a bit cluttered but that's the same for the current cropper so I'm not too worried about that.

The only feedback HQ gave me was to try to also put a red X on the user defined crops to make them jump back to the automatic crops. It could work if there's a tooltip on it saying something like "remove user defined crop (an automated crop will be used instead)".

Maybe it's just as good to stick with the current functionality though and you'll have to go into a custom crop to reset it.

**Comment by kjac** [comment]
@nul800sebastiaan ok I have split the crops into two lists as the GIF below shows. Mind you it's built upon the current version of the image cropper UX so it looks a little bit different than the mock up above.

image cropper crop lists

**Comment by kjac** [comment]
Merge conflict resolved.

**Comment by kjac** [comment]
Merge conflict resolved.

**Comment by nul800sebastiaan** [comment]
Hey there @kjac  !

I'm writing today after announcing at Codegarden, our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there.

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to ask on the forum, we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Comment by kjac** [comment]
V8 PR in #5626

**Pull request closed without merging**
