### PR TITLE
Increased tree icon font size for better visibility

### PR DESCRIPTION
**Pull request by mattbrailsford**

### CODE REVIEW

**Comment by mattbrailsford** [comment]
So, discussing on twitter, there was some debate on whether we shouldn't go further and go  to 19px. I've attached some pictures to show the differences and see what people think?

15 (As it currently is)


17 (As my original suggestion)


19 (As debated on twitter)


Debate!

**Comment by rasmusfjord** [comment]
Hmm i would say 19, since I just like them bigger not just because of font rendering but for the overall feel.

**Comment by mattbrailsford** [comment]
I'm leaning that way myself :)

**Comment by ravimotha** [comment]
19 has a "weight" to it 
I think it's good for usability

be interested to hear views from umbraco user with visual impairments
It's not too big to be distracting and it allows more interesting iconography to be used in back office schemas

**Comment by leen3o** [comment]
Initially I thought 17 but now thinking 19

**Comment by mattbrailsford** [comment]
Bumped up to 19 in my PR as seems to be the general consensus both here and on twitter. Of course, keep you opinions coming.

**Comment by netaddicts** [comment]
19 is far more better +1 from me

**Comment by Shazwazza** [comment]
Thanks all, going to pull this in and test will let  you know if it gets reverted for some reason.

**Pull request merged**
