### PR TITLE
Fetch all dictionary items if parentId is null

### PR DESCRIPTION
**Pull request by patrickdemooij9**
In one of our projects we were working with the _GetDictionaryItemDescendants_ function. However, I think the logic of the function can be improved. If there is no parentId passed, it should return all dictionary items (which it does). However, it still looks for them through multiple queries by recursively going through the dictionary items while it should be returning all dictionary items anyway.

If you have the following dictionary items in the old situation:

- Dictionary 1
- Dictionary 2
  - Dictionary 3
  - Dictionary 4
    - Dictionary 5
- Dictionary 6

It would need 3 SQL calls to retrieve all the dictionary items. With my code, it'll only need 1 SQL call. This should make any code where _GetDictionaryItemDescendants_ is passed a NULL parentId faster.

**How to test**
Dictionary overview still works. System uses _GetDictionaryItemDescendants_ there with a NULL parentId

### CODE REVIEW

**Comment by mikecp** [comment]
Hi @patrickdemooij9 ,

Thanks for this PR, it's always nice to improve performances 👍🙂

While reviewing the file, I noticed there is a protected method `PerformGetAll` which lacks the "order by" part of your query, but adds an extra filter on `PrimaryKey > 0`.

The filter seems obvious, but if it was, why did they add it 😉, so I was wondering if it would not be a good idea to either integrate that filter into your query as well, or else to call the existing method `PerformGetAll` and do your sorting on the result list. What do you think?

Cheers!

**Comment by mikecp** [comment]
Hi @patrickdemooij9 ,

Thanks for this PR, it's always nice to improve performances 👍🙂

While reviewing the file, I noticed there is a protected method `PerformGetAll` which lacks the "order by" part of your query, but adds an extra filter on `PrimaryKey > 0`.

The filter seems obvious, but if it was, why did they add it 😉, so I was wondering if it would not be a good idea to either integrate that filter into your query as well, or else to call the existing method `PerformGetAll` and do your sorting on the result list. What do you think?

Cheers!

**Comment by patrickdemooij9** [comment]
Hi @mikecp,
No idea how you managed to post the same reply twice. Or maybe it is just in my Github view. 

But regarding your feedback. I was indeed thinking of using the PerformGetAll as my method is almost the same except the sorting. However, sorting the results after the SQL just makes it slower right? In my head, the SQL server will do the sorting at the same time as the other executions like FetchOneToMany. So, moving the sorting outside of SQL would make it a slower operation. But maybe I am all wrong about that!

Just let me know what you think would be best

**Comment by mikecp** [comment]
Hi @patrickdemooij9 ,

Indeed strange that my comment got twice in there 😅

I'm no expert but indeed I guess that the sorting outside of the SQL will be less performing than sorting in SQL itself... So I guess this leaves only one choice 😀

**Comment by patrickdemooij9** [comment]
Hi @mikecp,

Pull request has been updated!

**Comment by mikecp** [comment]
Hi @patrickdemooij9 ,

I have been a little quite here lately but I am finalizing the preparation of my Codegarden session 'The Umbraco PR show" that will take place on the 17th in the morning.

And actually, if that is OK with you, I would like to use your PR as example during my session (this is why it has been tagged "CG22 Candidate"), so I will keep your PR open until then. Let me know if that is a problem for you, then I will remove the tag and proceed as usual 😉

Cheers!

**Comment by patrickdemooij9** [comment]
Hi @mikecp,
That is no problem. Excited to see how it will fit into your session. I don't see the "CG22 Candidate" tag, so maybe you forgot that part? Or maybe I am not allowed to see tags.

**Comment by mikecp** [comment]
Hey @patrickdemooij9 ,
Thanks! Actually it's not a tag, it's a "project" but this might be something internal that is not publicly visible 😅
I'm trying to make things somewhat interactive so I hope it will go as I expect 😁

**Comment by mikecp** [comment]
Hi @patrickdemooij9 ,
Sorry I did not get the opportunity to merge this one on stage after all.
I'll finalize it when I get back from CG 😁

**Comment by patrickdemooij9** [comment]
@mikecp, was just going through my pull requests and noticed this one still open. So a small reminder here ;)

**Comment by mikecp** [comment]
Hey @patrickdemooij9 , thanks for the reminder, I'll merge this asap 😅

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Hey @patrickdemooij9 , better late than never, I finally found time to check 😅

I just had to resolve conflicts with the "new" v10/contrib V10.1, but it's all OK now. I'll wait for the auto-checks to complete to make sure it's all OK and then I'll merge this later today!

**Comment by mikecp** [comment]
And here we go for the merge 😁

Cheers!

**Pull request merged**
