### PR TITLE
Fix for Issue #135 - Variation < null >, < null> is not supported by the property type

### PR DESCRIPTION
**Pull request by BeardInASuit**
Fix for isssue: https://github.com/umbraco/Umbraco.Cloud.Issues/issues/135 and https://github.com/umbraco/Umbraco-CMS/issues/6451

The root causes of this issue was two bugs:
- Culture variant content node names were not exported in package content serialization and 
- Language node property language were not used when importing DocumentSet properties. 

That triggers an exception "Variation < null >, < null> is not supported by the property type" when importing language variant content since no language variations were initialized by setting node names and property's lang attribute were not used when importing content.

The fix is to add language specific nodeNames in node serialization and importing them in the package import module. This would add the language variant that would be used when importing node properties with the right culture (lang attribute).

### CODE REVIEW

**Comment by BeardInASuit** [comment]
@nikolajlauridsen Good catch - I didn't have this problem since I am adding the right languages in my package when exporting it. You fix would allow a package to be imported without forcing the addition of new languages.

**Comment by nul800sebastiaan** [comment]
Thanks again @BeardInASuit and sorry for the delay! I've replaced some checks with some handy Invariant extension methods we have. This part of the code is not used in Deploy for Cloud so I've removed the references to the Cloud issue to avoid confusion. Other than that this is a good change for packages, thanks very much! 👍 

I would love to give you a contrib badge on [Our Umbraco](https://our.umbraco.com) if you have an account.

Thanks again and congrats on your first contribution the Umbraco CMS! 🎉

**Comment by BeardInASuit** [comment]
@nul800sebastiaan my account on Our Umbraco is Beard in a Suit (286892) Thanks!

**Comment by nul800sebastiaan** [comment]
👍 And now you have that cool contrib badge on your profile! 🥇

**Pull request merged**
