### PR TITLE
Add option to keep the mini profiler active at all times in debug mode

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is: https://github.com/umbraco/Umbraco-CMS/issues/3458
- [x] I have added steps to test this contribution in the description below

### Description

This PR opens up for adding `umbracoProfilerAlwaysActive` to the app settings. If that app setting is `true`, the mini profiler will be active for all frontend requests no matter if `umbDebug` is in the query string or not.

Obviously this only works in debug mode 😉 

The app setting is optional.

To test this:

1. Add `<add key="umbracoProfilerAlwaysActive" value="true" />` to the app settings in web.config.
2. Verify that all frontend requests are profiled.
3. Change the value of the app setting to `false`.
4. Verify that frontend requests are only profiled when using `umbDebug` in the query string.
5. Remove `umbracoProfilerAlwaysActive` from the app settings.
6. Verify that the site doesn't break, and that frontend requests can still be profiled using `umbDebug` in the query string.

If this PR is accepted I'll make sure to update the [web.config docs](https://our.umbraco.com/documentation/Reference/Config/webconfig/) and the [debugging docs](https://our.umbraco.com/Documentation/Getting-Started/Code/Debugging/) on Our as well.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @kjac 

Thanks for the work. As ever, we'll let you know our thoughts soon,

Emma

**Comment by nul800sebastiaan** [comment]
Hi @kjac - great idea! 

In general here's a good one to know: we'll strongly resist adding any more configuration keys to Umbraco because it shows that it's a weakness in the current system. "We don't really know how to deal with this so we'll let someone else figure it out". 
Apart from that, more options make debugging exponentially harder especially since we're already involving 2 different settings here that have the same effect.

In this case, I was also afraid that people would just deploy this setting to live without thinking, every time someone Tweets about their newly launched site, inadvertently someone will tell them 10 minutes later: "better turn off debug mode mate".

That said: I very much agree that this is a useful feature for developers and after asking at HQ the suggestion that came back was: what if this was a toggle in the developer section ("start profiling session") that sets a cookie. It's discoverable, it's only active on your local machine and it can guide you to make sure that `debug="true"` in web.config (probably even make the change for you, with warnings not to deploy that live).

What do you think?

**Comment by kjac** [comment]
@nul800sebastiaan nice feedback 👍 

Generally I agree with the whole "no more config settings, please!" strategy. It really does make testing impossible.

Specifically with this one it has no effect when `debug="false"`, since that's the key to actually profile anything. This extra config setting simply instructs Umbraco to force the profiler to be active if `debug="true"`. 

That being said I really like the alternative idea of turning it on and off in the dev section. My only concern is that people will forget to do it when the cookie gets removed (during cookie banner testing, of course!). But the upside is the increased discoverability. 

I'll do some prototyping and let you know what I come up with.

**Comment by nul800sebastiaan** [comment]
@dawoe The querystring method will still work though.

**Comment by kjac** [comment]
@dawoe good point. I'll keep it in mind. Cookies can be applied to a root domain and work on sub domains. That's the closest we'll get to have working in a cookie based solution (provided the admin server is on admin.domain.tld).

**Comment by nul800sebastiaan** [comment]
@kjac - I'd rather make the cookie domain specific, suppose I'm working on umbraco.io (Cloud), I'd see all sites on Cloud, that have manually enabled debug mode, with the miniprofiler enabled.

Let's start with the full domain name and then figure out how to support loadbalancing without a querystring later.

**Comment by Shazwazza** [comment]
The query string could also just set a cookie, maybe it's an additional query string to persist a cookie but if the mechanism to set the cookie was the query string, then perhaps when the cookie is set in the back office, then when clicking on the link to the content item in the back office, it could automatically append this same query string which means it would 'just work' with any load balanced domain?

**Comment by ronaldbarendse** [comment]
I would go for the option suggested by @Shazwazza: use the query string, just like `umbDebug=true`, to set a _session_ cookie that activates the profiler by default.

Just some suggestions:

1. `umbDebug=true&umbDebugPersist=true` to enable/set cookie and `umbDebugPersist=false` to remove cookie;
2. `umbDebug=session` to enable/set cookie and `umbDebug=false` or `umbDebug=remove` to remove cookie;
3. `umbDebug=enable` to enable/set cookie and `umbDebug=disable` to remove cookie (or something similar, like start/stop, activate/deactivate);

This should make the additional dashboard/tab (including Angular controller), C# API controller and not to forget all translations obsolete. This new functionality should however be correctly documented, of course...

Option 3 would be my preferred choice as it's unambiguous about it's intent. Also make sure the cookie does not have an expiration (so it's a session cookie and automatically gets removed after the browser) and maybe even flag it `HttpOnly`. Naming the cookie 'UMB-DEBUG' seems to be in line with both the query string and custom header that's already used and all other Umbraco cookies, so I totally agree with you here @kjac 👍

**Comment by nul800sebastiaan** [comment]
Hey there @kjac !

I'm writing today after announcing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Comment by ronaldbarendse** [comment]
Porting this feature to V8 based on my comments would be quite easy I guess...

**Comment by kjac** [comment]
I'm already working on it, will submit a PR with a port this weekend

**Pull request closed without merging**
