### PR TITLE
Cherry pick Apply the Umbraco logo to BackOffice (#11949) to V9

### PR DESCRIPTION
**Pull request by nikolajlauridsen**
Cherry picks #11949 to V9

### CODE REVIEW

**Comment by HGCollier** [comment]
Some documentation for this would be nice, as currently it seems that the below code does nothing.
```
"Umbraco": {
    "CMS": {
      "Content": {
        "BackOfficeLogoImage": "",
      },
    }
  }
```

**Comment by jemayn** [comment]
@HGCollier 

This works for me on 9.4rc:

```csharp
 "CMS": {
      "Content": {
        "HideBackOfficeLogo":  true
      }
}
```

**Comment by haldencollier101** [comment]
@jemayn It's a shame that this wasn't implemented for v9.3 (just tested). Guess I'll just have to wait until v9.4 comes out. Thanks for the heads up anyways.

**Comment by HGCollier** [comment]
@jemayn I'm currently using v9.3, just tested your code and it doesn't seem to have an effect, which is a shame. Will just have to wait for v9.4 to come out. Thanks anyways.

**Pull request merged**
