### PR TITLE
Fix translation didn't work in some tree node

### PR DESCRIPTION
**Pull request by wanddy**
Fix translation didn't work in some tree node

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Hey there @wanddy ! Can you please create an issue for this on the issue tracker at http://issues.umbraco.org and explain what the problem is that you're trying to solve? I'm not sure I understand :-)

**Comment by wanddy** [comment]
Fix some menu tree header won't be translated.
This may be caused by the explicit definition of tree node name.

**Comment by mikkelhm** [comment]
Hey @wanddy, thanks for the PR. I'm just revisiting this, could we get you to create an associated issue on the issue tracker at http://issues.umbraco.org. We really need a issue on the tracker, that describes the issue. All release notes etc. are created from those

**Comment by wanddy** [comment]
I'm sorry for this.I tried to create an issue tracker,but I can't open the site:http://issues.umbraco.org in China.

**Comment by mikkelhm** [comment]
Dammit, the great firewall hits us once again :-) let's just try to do the discussion here then.
If I understand it correctly then it is just a follow up on a PR you got merged earlier right which just extends the Chinese translations to the following items in the trees

Partial View Macro files
Partial views
Scripts

Is that correct?

Also you will be glad to hear that at Codecarden we announced that we will be switching from issues.umbraco.org to github issues. That should fix the access problems. (I'm presuming that github is working properly from China?)

**Comment by wanddy** [comment]
@mikkelhm Yes，you got it.
Thank you for your patient.
Github is working properly 99% of the time from China.

**Comment by clausjensen** [comment]
http://issues.umbraco.org/issue/U4-10074

**Comment by clausjensen** [comment]
@wanddy Thanks for the PR - merged in for 7.6.4 :)

**Pull request merged**
