### PR TITLE
Add user picker property editor

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/7594

### Description
This PR add a new user picker property editor instead of using enity picker. At the moment we can't use `treePicker` in `editorService` similar to member picker, because mapping of `User` entity is not handled like `Member`.
https://github.com/umbraco/Umbraco-CMS/blob/a9d45413c89d67280ce54c7fd4182e90323bab6c/src/Umbraco.Web/Editors/EntityController.cs#L921

However `editorService` already have a `userPicker` function used in users section. It would be great to extend this to support multiple like `mediaPicker` (maybe also for `memberPicker later) and being able to configurate this on the configuration of the property editor. For now we can just keep it as a single picker.

A quick demo:

### CODE REVIEW

**Comment by bjarnef** [comment]
It is now possible to select a user and also remove the selected user. I have also made a few changes on `umb-user-preview` to make it a bit more consistent with `umb-node-preview`.

The `userPicker` now also works as a single and multi picker (default is multi picker since it is the current behaviour). Later the we could add a the configuration option on the user picker property editor to decide whether it should be a single or multi picker (we can do something similar for member picker).

At the moment the user picker just stores an id like the exiting picker (using entity picker), but if we later allow this configuration, we also need to update the property value converterhttps://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/PropertyEditors/UserPickerPropertyEditor.cs to return a single object or a collection simialar to media picker, MNTP, url picker, etc.

Since `entityResource.getByIds` doesn't support "User" and we would like the avatars as well to user `umb-user-preview` like the user picker on user groups, I have added a new function `getUsers` in `usersResource`.



**Test notes**
- Select a user via user picker and ensure the picked user is shown after selection. Also ensure that user is shown after save and refresh.
- Ensure multiple users still can be selected in user picker on a user group

**Comment by poornimanayar** [comment]
Hey @bjarnef ,

You seem very busy! Thank you for the work. We shall review your changes and get back to you :-)

Poornima

**Comment by nul800sebastiaan** [comment]
What a lovely update and very useful to have a dedicated user picker! Thanks very much @bjarnef! 👍 

> The userPicker now also works as a single and multi picker (default is multi picker since it is the current behaviour). Later the we could add a the configuration option on the user picker property editor to decide whether it should be a single or multi picker (we can do something similar for member picker).

Yes! Would be great to be able to configure the datatype as single or multiple

> At the moment the user picker just stores an id like the exiting picker (using entity picker), but if we later allow this configuration, we also need to update the property value converterhttps://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/PropertyEditors/UserPickerPropertyEditor.cs to return a single object or a collection simialar to media picker, MNTP, url picker, etc.

Yep, that would be excellent as well! 👍

**Comment by bjarnef** [comment]
@nul800sebastiaan I would like if the different pickers could use `Minimum` and `Maximum` prevalues to configurate is the picker is multipicker or not.
See this PR for multiple member picker https://github.com/umbraco/Umbraco-CMS/pull/7634 and this feature request for media picker https://github.com/umbraco/Umbraco-CMS/issues/8471

At the moment the user picker use `Interger` but need to be `String` instead to store multiple komma delimited values and maybe `Udi` instead, but at the moment I think the API only support to get an user by `int` id.
Furthermore do we have an frontend model for user entity like `IPubslihedContent`. It would be great with a property value converter for user picker, but it probably need to returns something else than `IUser` or `IEnumerable<IUser>`.

**Pull request merged**
