### PR TITLE
#3022 - Media uploader in RTE doesn't select uploaded image

### PR DESCRIPTION
**Pull request by KimHolzmann**
### Prerequisites

- [ ] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is:
- [ ] I have added steps to test this contribution in the description below

### CODE REVIEW

**Comment by abjerner** [comment]
@KimHolzmann Thanks for taking the time to great this PR 👍 

I will have a look at your PR, and report back if I find anything.

By the way - are you aware that you can contribute in [Hacktoberfest](https://hacktoberfest.digitalocean.com/). If you're among the first 50000 to open five PRs on GitHub in October, you get a free t-shirt.

Umbraco also has their own edition - where you get a free t-shirt for opening five PRs for either the [UmbracoCms](https://github.com/umbraco/Umbraco-CMS) or [UmbracoDocs](https://github.com/umbraco/UmbracoDocs) repositories. You can read more about the details here: https://umbraco.com/blog/happy-hacktoberfest/

Anders, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by nul800sebastiaan** [comment]
@abjerner We never promised t-shirts! 🙈 We're still finalizing giveaways. 😄 

@KimHolzmann Can you please revert all changes to language files that are NOT `en.xml` and `en_us.xml`? Umbraco just falls back to English if a key is not present. Make sure to revert the entire commit so that it's nice and clean again. Afterwards, just update `en.xml` and `en_us.xml`. Thanks!

**Comment by abjerner** [comment]
@nul800sebastiaan ahh, my bad. Just saw the article mentioned t-shirts, but noticed now that it's was just mentioning the Hacktoberfest t-shirts 😮

@KimHolzmann in addition to what Sebastian said about the languages files, the Danish translation is fine to keep ;)

**Comment by nul800sebastiaan** [comment]
@KimHolzmann Ah I see what you did there, you continued on top of the previous PR, that's not going to work very well,

You're working on the `dev-v7` branch right now, which means that you'll never be able to get the changes from the origin repository ever again (the umbraco owned git repository).
Normally what you would do is: 
- Fork Umbraco-CMS
- Clone Umbraco-CMS
- Immediately create a branch
- Work on that until you're ready to submit a PR
- Switch back to `dev-v7`
- Get the latest changes from the origin umbraco repo (https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/.github/CONTRIBUTING_DETAILED.md#keeping-your-umbraco-fork-in-sync-with-the-main-repository)
- Make a new branch from the latest changes in `dev-v7` 
- Make new code
- Submit PR
- Switch back to `dev-v7` 
- Get latest changes
- .. and so on!

Since you've made commits now on top of `dev-v7` you won't be able to get the changes from the origin any more. 

I would recommend you make a fresh clone of your fork of the Umbraco repository, create a branch and apply the latest changes again. I'll close this one for now as merging this is going to be difficult and will result in some mess 😄

**Comment by KimHolzmann** [comment]
Damn me ☠
I can first do this tomorrow sorry

**Comment by nul800sebastiaan** [comment]
No problem mate! Just hope the guidance is clear! Thanks for the help! 👍🙌

**Comment by KimHolzmann** [comment]
Hi @nul800sebastiaan 
can you see if I have reversed the last commits correct, before I start on the one with all the languesfiles in 
What will happend with the style changes @BatJan  has done on the searchform ?

**Comment by nul800sebastiaan** [comment]
@KimHolzmann Jan's changes have not been merged yet.

Yes, when you're happy with your work, push and start a PR! :-)

**Comment by KimHolzmann** [comment]
I have reverted all now - hope all is ok again, I wait to make anything until positiv response :-)

**Pull request closed without merging**
