### PR TITLE
V13: Load TinyMCE premium plugins through tiny.cloud

### PR DESCRIPTION
**Pull request by iOvergaard**
### Description
Load the plugins.js file from tiny.cloud when a cloud apikey is set. This allows the editor to load premium plugins from the cloud without uploading them to the server.

The API key and the desired premium plugins (and others) are added to appsettings.json `Umbraco:CMS:RichTextEditor`:

```json
      "RichTextEditor": {
        "CloudApiKey": "no-api-key",
        "Plugins": ["advtable", "checklist", "wordcount", "powerpaste", "advcode", "tinymcespellchecker"],
        "CustomConfig": {
          "statusbar": "true"
        },
        "Commands": [
          {
            "Alias": "checklist",
            "Name": "Checklist",
            "Mode": "All"
          }
        ]
      }
```

This enables the plugins for all instances of the rich text editor. Then we are adding certain new commands for the plugins, such as the `checklist` command, and that will have to be enabled _for each_ configuration in the CMS to allow the editors a certain level of flexibility:

image

### Screenshots
Premium plugins **checklist** and **Spellchecker Pro** activated
image

### Considerations
**Plugins prevalues**
We have considered adding a "plugins" field to the prevalue configuration of the Rich Text Editor. However, an editor would have to know the names of the plugins and manually type those into every configuration. This could still be debated, however.

**Server-side features**
Some premium plugins require certain server-side features such as endpoints to return JWT keys (TinyDrive) and endpoints to return AI suggestions (the **ai** plugin). Umbraco will not and cannot implement these sufficiently to support all the various features of TinyMCE. This is however possible for any developer to implement on their own Umbraco solutions in whatever way they see fit.

### CODE REVIEW

**Comment by drummerboy46** [comment]
I've noticed tinyMCE have an AI assistant plugin as part of the subscription. Will all subscription plugins work with this improvement?

**Comment by drummerboy46** [comment]
I think this is a great idea, but was wondering if this is potentialy in conflict with DXP/Umbraco backoffice package extensions? It's not at all clear how you could go about extending Umbraco's implementation of TinyMCE further to allow for server side plugins like the AI plugin for example. Can you also make it more clear exactly what WILL work without further development and what type of TinyMCE subscription is required to enable these extras?

**Review by leekelleher — APPROVED** [review]
All looks good to me.

I'm happy with the code. 👍 _(I did have a look if there was a way to not hardcode the `cdn.tiny.cloud` URL, e.g. if there was a utility in the TinyMCE library itself, but doesn't look like there is)._

I've tested it out with my own TinyMCE API key and it all works as expected. 👍 
_(I didn't try out the AI Assistant plugin, as that would require extra JS configuration, which I'm unsure how that would be handled with the current Umbraco implementation/integration)._

**Comment by iOvergaard** [comment]
> I think this is a great idea, but was wondering if this is potentially in conflict with DXP/Umbraco back-office package extensions?
> 
> Will there be developer guidance available on how to further extend Umbraco to accept TinyMCE server side plugins like the AI plugin?
> 
> Can you also make it more clear exactly what WILL work without further development and what type of TinyMCE subscription is required to enable these extras?

I think the documentation definitely could/should include more of this. We don't have much experience working with TinyMCE server-side plugins to know what it entails to use them, but it is certainly an area where we could include some more examples.

Regarding TinyMCE subscriptions, I would rather not focus on exactly what is required for exactly which plugins since they change from time to time. We included links around the Docs to Tiny's documentation to give people more information.

If you have anything to add, please feel free to make an inquiry on the [UmbracoDocs repository](https://github.com/umbraco/UmbracoDocs)!

**Pull request merged**
