### PR TITLE
V9: Fix for migration of non-default configurated users/members

### LINKED ISSUE #11366: Migration from 8 to 9, cannot login to backoffice with existing user
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

9.0.0-rc003

### Bug summary

When migrating from 8 to 9, I'm unable to login to backoffice as it says that my password is invalid. 
In the console I can see following:

Invalid password for user.
User failed to provide the correct password. 

Has anything changed in the database logic for login users, hash key? Algorithms? 

As mentioned the database structure should be the same. 

My valid password is for some reason is invalid.

### Specifics

_No response_

### Steps to reproduce

 1. Create new umbraco 9 project and connect to your umbraco 8 database.
 2. Try to login to backoffice

### Expected result / actual result

_No response_

---
_This item has been added to our backlog [AB#15151](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/15151)_

### PR DESCRIPTION
**Pull request by bergmania**
## Summary
This PR fixes issues with migration of users and members that had `UseLegacyEncoding="true"`.
Fixes #11366

#### `UseLegacyEncoding="true"` && `passwordFormat="Clear"`
This was not supported in v8

#### `UseLegacyEncoding="true"` && `passwordFormat="Encrypted"`
This was not supported in v8 

#### `UseLegacyEncoding="true"` && `passwordFormat="Hashed"`
This WAS supported in v8. 
The issue here was that the algorithm `HMACSHA256` was still stored on the user, even that it used `HMACSHA1 `
Now we fallback to try login using super legacy HMACSHA1 even when the algorithm is stated as being HMACSHA256.

#### `UseLegacyEncoding="true"` && `passwordFormat="Clear"`
This was supported in v8.
Now we test if and only if the password algorithm on the member is null, that the password provided is equal to the password in the database. 

#### `UseLegacyEncoding="true"` && `passwordFormat="Encrypted"`
This was supported in v8 
Now we test if and only if the password algorithm on the member is null AND the new `Umbraco:CMS:LegacyMachineKey:DecryptionKey` is NOT null or empty, that the encrypted password in the database decrypted using the provided `Umbraco:CMS:LegacyMachineKey:DecryptionKey` is equal to the password entered by the member. 

#### `UseLegacyEncoding="true"` && `passwordFormat="Hashed"`
This was supported in v8 
Now we test if and only if the password algorithm on the member is null AND the new `Umbraco:CMS:LegacyMachineKey:DecryptionKey` IS null or empty, that the provided password hashes to the same hash as stored in the database using either HMACSHA256 or HMACSHA1

## Test
- Create a v8 projects and databases, with the following settings and for each project create a member/user:

#### `UseLegacyEncoding="false"` && `passwordFormat="Hashed"` (Default)
```xml
<add name="UsersMembershipProvider" type="Umbraco.Web.Security.Providers.UsersMembershipProvider, Umbraco.Web" minRequiredNonalphanumericCharacters="0" minRequiredPasswordLength="4" useLegacyEncoding="false" enablePasswordRetrieval="false" enablePasswordReset="true" requiresQuestionAndAnswer="false" passwordFormat="Hashed" />
```

#### `UseLegacyEncoding="true"` && `passwordFormat="Hashed"`
```xml
<add name="UsersMembershipProvider" type="Umbraco.Web.Security.Providers.UsersMembershipProvider, Umbraco.Web" minRequiredNonalphanumericCharacters="0" minRequiredPasswordLength="4" useLegacyEncoding="true" enablePasswordRetrieval="false" enablePasswordReset="true" requiresQuestionAndAnswer="false" passwordFormat="Hashed" />
```

#### `UseLegacyEncoding="false"` && `passwordFormat="Hashed"` (Default)
```xml
<add name="UmbracoMembershipProvider" type="Umbraco.Web.Security.Providers.MembersMembershipProvider, Umbraco.Web" minRequiredNonalphanumericCharacters="0" minRequiredPasswordLength="10" useLegacyEncoding="false" enablePasswordRetrieval="false" enablePasswordReset="false" requiresQuestionAndAnswer="false" defaultMemberTypeAlias="Member" passwordFormat="Hashed" allowManuallyChangingPassword="false" />
```

#### `UseLegacyEncoding="true"` && `passwordFormat="Clear"`
```xml
<add name="UmbracoMembershipProvider" type="Umbraco.Web.Security.Providers.MembersMembershipProvider, Umbraco.Web" minRequiredNonalphanumericCharacters="0" minRequiredPasswordLength="10" useLegacyEncoding="true" enablePasswordRetrieval="false" enablePasswordReset="false" requiresQuestionAndAnswer="false" defaultMemberTypeAlias="Member" passwordFormat="Clear" allowManuallyChangingPassword="false" />
```

#### `UseLegacyEncoding="true"` && `passwordFormat="Encrypted"`
```xml
<add name="UmbracoMembershipProvider" type="Umbraco.Web.Security.Providers.MembersMembershipProvider, Umbraco.Web" minRequiredNonalphanumericCharacters="0" minRequiredPasswordLength="10" useLegacyEncoding="true" enablePasswordRetrieval="false" enablePasswordReset="false" requiresQuestionAndAnswer="false" defaultMemberTypeAlias="Member" passwordFormat="Encrypted" allowManuallyChangingPassword="false" />
```

#### `UseLegacyEncoding="true"` && `passwordFormat="Hashed"`
```xml
<add name="UmbracoMembershipProvider" type="Umbraco.Web.Security.Providers.MembersMembershipProvider, Umbraco.Web" minRequiredNonalphanumericCharacters="0" minRequiredPasswordLength="10" useLegacyEncoding="true" enablePasswordRetrieval="false" enablePasswordReset="false" requiresQuestionAndAnswer="false" defaultMemberTypeAlias="Member" passwordFormat="Hashed" allowManuallyChangingPassword="false" />
```

- Use that database to migrate to v9.

### CODE REVIEW

**Comment by p-m-j** [comment]
# Manual testing results

## 9.1.1 -> 696a873

- [x] Users still works with defaults post upgrade
- [x] Members still works with defaults post upgrade

## 8.x -> 9

Users

- [ ] UseLegacyEncoding="false" && passwordFormat="Hashed" (Default)
- [ ] UseLegacyEncoding="true" && passwordFormat="Hashed"

Members

- [ ] UseLegacyEncoding="false" && passwordFormat="Hashed" (Default)
- [ ] UseLegacyEncoding="true" && passwordFormat="Clear"
- [ ] UseLegacyEncoding="true" && passwordFormat="Encrypted"
- [ ] UseLegacyEncoding="true" && passwordFormat="Hashed"

All tests used 

```
user: user@example.com
member: member@example.com
password: Umbraco9Rocks!
machineKey (encrypted only): <machineKey validationKey="A6F9879163E752CDBBAEAD07CE06442851C2C2123BB25E554E87A0DF85523159" decryptionKey="FF519A06F89C95684A6C157F026E10631FBD609745609FE847A068AF50374817" validation="HMACSHA256" decryption="AES" />
```


## Database Values (v8 database before migration)

| scenario      | Legacy | Format    | login              | password                                                                             | config                                   |
|---------------|--------|-----------|--------------------|--------------------------------------------------------------------------------------|------------------------------------------|
| 9.1.1 Users   | N/A    | N/A       | user@example.com   | AQAAAAEAACcQAAAAEDCrYcnIhHKr38yuchsDu6AFqqmLNvRooKObV25GC1LC1tLY+gWGU4xNug0lc17PHA== | {"hashAlgorithm":"PBKDF2.ASPNETCORE.V3"} |
| 8.4.0 Users   | false  | Hashed    | user@example.com   | uB/pLEhhe1W7EtWMv/pSgg==1y8+aso9+h3AKRtJXlVYeg2TZKJUr64hccj82ZZ7Ksk=                 | {"hashAlgorithm":"HMACSHA256"}           |
| 8.4.0 Users   | true   | Hashed    | user@example.com   | t0U8atXTX/efNCtTafukwZeIpr8=                                                         | {"hashAlgorithm":"HMACSHA256"}           |
| 9.1.1 Members | N/A    | N/A       | member@example.com | AQAAAAEAACcQAAAAEOIibA0KbFauNVTu4bFuLFrAns0fLG8x0XJ+IMx2o1T/KvUBmojf4ZA6LWqS98cwmg== | {"hashAlgorithm":"PBKDF2.ASPNETCORE.V3"} |
| 8.4.0 Members | false  | Hashed    | member@example.com | m6MpSV6A6pSXYCu9o3Pi3w==3FAJNY/LLu6aUfpGYXeZTewc1vYHEg0cXimbc6wdfaQ=                 | N/A                                      |
| 8.4.0 Members | true   | Clear     | member@example.com | Umbraco9Rocks!                                                                       | N/A                                      |
| 8.4.0 Members | true   | Hashed    | member@example.com | t0U8atXTX/efNCtTafukwZeIpr8=                                                         | N/A                                      |
| 8.4.0 Members | true   | Encrypted | member@example.com | X1Ucv+vg9v7VUsuC9s3xKAvqRL0CKKRoBmpVpFqM4ug=                                         | N/A                                      |

**Comment by p-m-j** [comment]
Issue for members legacy + encrypted, breaks if tried to login before decryption key added.

Steps to reproduce.

1. Run this
```sql
update cmsMember 
set 
    [password] = 'X1Ucv+vg9v7VUsuC9s3xKAvqRL0CKKRoBmpVpFqM4ug=',
    securityStampToken = null, 
    passwordConfig = null
```
1. Remove LegacyMachineKey section from appsettings.json
1. Attempt to login as member, fails
1. Note that cmsMembers passwordConfig updated to `{"hashAlgorithm":"PBKDF2.ASPNETCORE.V3"}`
1. Add legacy machine key section 

```json
      "LegacyMachineKey": {
        "DecryptionKey": "FF519A06F89C95684A6C157F026E10631FBD609745609FE847A068AF50374817"
      },
```
1. Try login, fails
1. Run sql query from step 1 again
1. Try login, works

**Comment by bergmania** [comment]
It is now handled by persisting an "unknown" algorithm instead of the default (which we know is wrong), when the login fails.

**Comment by bergmania** [comment]
Due to the potential security issue with allowing rehashes of clear text passwords, i added a setting to allow it. Defaults to Not-allowed.

**Comment by p-m-j** [comment]
Anything we can do for folks that have already had incorrect config persisted? Run a migration to clear? 

We can check len(password hash) to know if it is correct algo or not presumably, in fact we could do that instead of having the explicit unknown also, cleartext of the exact length of hash seems unlikely.

**Comment by p-m-j** [comment]
## V9.x

- [ ] User and member logins still work as expected v9.x -> d9aaa536

## 8.x -> 9

For each of the below I have tested with a login failure followed by a login success

Users

- [ ] UseLegacyEncoding="false" && passwordFormat="Hashed" (Default)
- [ ] UseLegacyEncoding="true" && passwordFormat="Hashed"

Members

- [ ] UseLegacyEncoding="false" && passwordFormat="Hashed" (Default)
- [ ] UseLegacyEncoding="true" && passwordFormat="Encrypted"
- [ ] UseLegacyEncoding="true" && passwordFormat="Hashed"

## Confirm unsupported

- [ ] UseLegacyEncoding="true" && passwordFormat="Clear"

**Comment by p-m-j** [comment]
LGTM

**Pull request merged**
