### PR TITLE
v8 Fix create button style

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: 

### Description
This PR updates the create button style a few places to make it consistent with the rest of the UI, e.g. after "Create user" and "Create group" are the button action style.

Now "Add language" and "Create package" also use this style. Futhermore the white button style in listviews, e.g. in "Create member" was very anonymous, so this it updated to same button style.

image

image

image

image

image

image

### CODE REVIEW

**Comment by bjarnef** [comment]
@nielslyngsoe doesn't this look much better and more consistent? 👍

**Comment by nielslyngsoe** [comment]
Hi @bjarnef Definitely, good to get this aligned.

I though think most of these options are secondary. Therefor they dont need the attention given by this contrast, so I would prefer making them white, with a subtle shadow to make it not blend to much with the background.

I have made a Pull Request here, let me know what you think.

https://github.com/umbraco/Umbraco-CMS/pull/4638

screenshot 2019-02-18 at 15 01 42
screenshot 2019-02-18 at 15 01 34
screenshot 2019-02-18 at 15 01 23
screenshot 2019-02-18 at 15 02 01

**Comment by bjarnef** [comment]
@nielslyngsoe the issue I have with the buttons being white, is that is a very anonymous color and on these pages I would say these are the main actions.
If the button is white it kinda disappears in the UI.

**Comment by bjarnef** [comment]
Furthermore is disagree these actions are secondary. On these pages it is the primary action, e.g. on listviews.

In a blog archive you might say save / save and publish is the primary action, but when visit these listview editors more likely create a blogpost, while only saving the nodes once in a while if it has any settings to update, e.g. number of blog posts per page.

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef for your input, good stuff! We don't know exactly what we want to do yet so I've put this one on the list for our periodic meetings at HQ and will let you know what the outcome is.

**Comment by bjarnef** [comment]
Also consider the colors of enable/disable url tracker buttons.

image

image

**Comment by bjarnef** [comment]
@nul800sebastiaan any update on this? 😁

**Comment by nul800sebastiaan** [comment]
After a long discussion about making things consistent, vs meaningful, vs is this the primary action everywhere, vs is white better than blue, etc. We came to the conclusion that @nielslyngsoe is going to give this another go and present a few more options internally.
To be continued.. :)

**Comment by bjarnef** [comment]
@nul800sebastiaan @nielslyngsoe any update on this? In the latest changes in `v8/dev` I still feel it is a bit inconsistent with three different button styles for these actions accross the different pages/views: green, white and purple.

**Pull request closed without merging**
