### PR TITLE
U4-8632 - Back-office user groups

### PR DESCRIPTION
**Pull request by AndyButland**
This PR consists of an implementation for a feature to allow the setting of back-office permissions via groups of users, rather than users individually.  As per [some notes in the related issue](http://issues.umbraco.org/issue/U4-8632#comment=67-29853), I've implemented this in a way that seems to me simplest and least intrusive in terms of code changes and issues around migration of existing sites.  In particular I've retained the existing features for setting and checking permissions on users and user types, and introduced groups as well - rather that looking to replace types with groups.  The end result is probably not quite as you'd design such a permissions system from scratch, but is likely an easier way to introduce this feature to the current code base.

In practice I'd expect people to use either the existing setup (user types and user permissions), or use the groups and not use individual user permissions except for odd exceptions.

To set up some tables are required.  The PR contains a (perhaps optimistic!) migration for 7.6, but to set up for testing it's probably easiest to run the following SQL script:

```
/* umbracoUserGroup - user groups */
CREATE TABLE [dbo].[umbracoUserGroup](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[userGroupAlias] [nvarchar](200) NULL,
	[userGroupName] [nvarchar](200) NOT NULL,
	[userGroupDefaultPermissions] [nvarchar](50) NULL,
 CONSTRAINT [PK_umbracoUserGroup] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/* umbracoUser2UserGroup - maps users to user groups */
CREATE TABLE [dbo].[umbracoUser2UserGroup](
	[userId] [int] NOT NULL,
	[userGroupId] [int] NOT NULL
 CONSTRAINT [PK_user2userGroup] PRIMARY KEY CLUSTERED 
(
	[userId] ASC,
	[userGroupId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[umbracoUser2UserGroup]  WITH CHECK ADD  CONSTRAINT [FK_umbracoUser2UserGroup_userId] FOREIGN KEY([userId])
REFERENCES [dbo].[umbracoUser] ([id])
GO
ALTER TABLE [dbo].[umbracoUser2UserGroup]  WITH CHECK ADD  CONSTRAINT [FK_umbracoUser2UserGroup_userGroupId] FOREIGN KEY([userGroupId])
REFERENCES [dbo].[umbracoUserGroup] ([id])
GO

/* umbracoUserGroup2App - maps user groups to apps */
CREATE TABLE [dbo].[umbracoUserGroup2App](
	[userGroupId] [int] NOT NULL,
	[app] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_userGroup2App] PRIMARY KEY CLUSTERED 
(
	[userGroupId] ASC,
	[app] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[umbracoUserGroup2App]  WITH CHECK ADD  CONSTRAINT [FK_umbracoUserGroup2App_umbracoGroupUser_id] FOREIGN KEY([userGroupId])
REFERENCES [dbo].[umbracoUserGroup] ([id])
GO
ALTER TABLE [dbo].[umbracoUserGroup2App] CHECK CONSTRAINT [FK_umbracoUserGroup2App_umbracoGroupUser_id]
GO

/* umbracoUserGroup2NodePermission - maps user groups to node permissions */
CREATE TABLE [dbo].[umbracoUserGroup2NodePermission] (
	[userGroupId] [int] NOT NULL,
	[nodeId] [int] NOT NULL,
	[permission] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_umbracoUserGroup2NodePermission] PRIMARY KEY CLUSTERED 
(
	[userGroupId] ASC,
	[nodeId] ASC,
	[permission] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[umbracoUserGroup2NodePermission]  WITH CHECK ADD  CONSTRAINT [FK_umbracoUserGroup2NodePermission_umbracoNode_id] FOREIGN KEY([nodeId])
REFERENCES [dbo].[umbracoNode] ([id])
GO
ALTER TABLE [dbo].[umbracoUserGroup2NodePermission] CHECK CONSTRAINT [FK_umbracoUserGroup2NodePermission_umbracoNode_id]
GO
ALTER TABLE [dbo].[umbracoUserGroup2NodePermission]  WITH CHECK ADD  CONSTRAINT [FK_umbracoUserGroup2NodePermission_umbracoUser_id] FOREIGN KEY([userGroupId])
REFERENCES [dbo].[umbracoUserGroup] ([id])
GO
ALTER TABLE [dbo].[umbracoUserGroup2NodePermission] CHECK CONSTRAINT [FK_umbracoUserGroup2NodePermission_umbracoUser_id]
GO
```

Once installed you should find with this PR:

- Back-office management screens for creating groups and adding users to them
- Amended back-office management screen for users to allow assigning them to groups
- An additional back-office management screen for setting node permissions to a group (similar to that already there for setting them on a user)
- Amends to code that retrieves a user to also pull back the groups they are associated with
- Checks for access to sections that takes account of groups:
     - A user will be allowed access to any section they have access to as per their user permissions, PLUS any they have access to be being part of a group that has been given that permission 
- Checks for node action permissions that takes account of groups:
     - A user with permissions directly assigned to them for a node will use those and not look any further.  If there are none, the permissions the user receives will be the most permissive set of all actions allowed for their user type and the groups they are in.  E.g. if a user has a type that can do "A", one group that can do "B" and another that can do "C", then they should be able to do "A", "B" and "C"

Code-wise, at least in the UI layer, there's a bit of legacy code that has been dug into here that I imagine is due to be looked at again anyway for V8.  I've not attempted to update that, but have where possible moved code to shared base classes where similar functionality is required for existing user permissions and the new group permissions.  So although there's code in here that will likely be updated in the not too distant future, I've tried not to add too much to the legacy code and avoided duplicating where I can.

Otherwise whilst there's a fair bit here a lot is analogous to existing code that already handled users or user types, so other than the logic around determining permissions where we have introduced groups, not too much actually brand new.

### CODE REVIEW

**Comment by Shazwazza** [comment]
Hi @AndyButland ! Wow! Another huge/great PR :)

I would like to discuss a few things regarding this however (please note I haven't dug through all of your code). Our idea for user groups was going to be quite simplified:

* User specific permissions would not exist
* Only user group permissions would exist
* When upgrading, we'd create a user group per user to maintain their current permissions, then the admin can modify/move accordingly

I think it's going to be too much work and overhead to try to maintain 2x permissions structures. The lookups currently required are pretty insane and then we have to cache the entire structures which could potentially be enormous which is another reason we don't want 2x permissions structures.

Does that make sense? I would suspect that this approach could greatly simplify this PR?

**Comment by AndyButland** [comment]
Hi @Shazwazza - thanks for starting to take a look at it.

I do take your point - gave some thought to this and [commented on the issue tracker](http://issues.umbraco.org/issue/U4-8632).  In the end though my thinking was:

- Yes, you'd need a migration that creates one group per user as you describe.  Which would work, but maybe isn't _that_ nice.  For setups with a small amount of users groups may not be useful and they'd prefer to set permissions directly on users.  And for those with a large number of users, the clean-up would be a bit of a chore.
- The way I've done it, groups are an "added extra".  You'd use them if you wanted to but could ignore if you didn't - which as I say, might be better for smaller sites or migrated ones.
- Being able to set permissions on groups and/or users is more analogous with other permissions systems, like Windows and like other CMSes
- Whilst I'd expect most setups to use groups or users, and not so much both, there may always be value in some cases to have the option to set directly on a user, for exceptions from the general rules

See what you think though when you have chance to dig in a bit further.  I _think_ I've got it set up as needed with the necessary caching and tried to avoid duplication as much as possible (though in the UI inevitably there is some).  But of course there's more than a fair chance I've missed something important, and if the view was that we should go with groups only, then as you say it would simplify things somewhat.

**Comment by antony-v** [comment]
Hi everyone. We're evaluating different CMS for a big enterprise site, and the major stumbling block with Umbraco at this point is the very weak authorization/security model that it has compared to what commercial competitors (e.g. Kentico) have. This PR is definitely a move in the right direction. It would be great to see this merged in and become part of the core. Tab-level and field-level permissions for groups would be the next logical step.

**Comment by Shazwazza** [comment]
I've been meaning to provide some feedback on this which I'll do today on the issue tracker. The plan is to integrate this for a 7.x version, however there will be some changes and simplification required.

**Comment by gippa5** [comment]
Closing this to replace with second PR here: https://github.com/umbraco/Umbraco-CMS/pull/1558

**Comment by AndyButland** [comment]
Closing this to replace with https://github.com/umbraco/Umbraco-CMS/pull/1559

**Pull request closed without merging**
