### PR TITLE
cursor remians default when no alias is given to the umb-control-grou…

### PR DESCRIPTION
**Pull request by pelgro**
…p. Also added alias for the email field on the user details page

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description

Fixed [http://issues.umbraco.org/issue/U4-11040](http://issues.umbraco.org/issue/U4-11040)
Before:
user-details-groups-label
After:
user-details-groups-label-fix

 I also added a missing alias to the email label on the user details page. 

Before:
user-details-email-label
After:
user-details-email-label-fix

### CODE REVIEW

**Comment by bjarnef** [comment]
I think this could be written more simply.

```
label[name=for] {
   cursor: default;
}
```
Otherwise developers have to remember adding the class labels in core and third party packages. Maybe also not necessary with and additional less file for this stuff.

**Comment by pelgro** [comment]
Not sure if it'll work with CSS only, unless we can get angularjs to remove the for attribute when the alias porperty is empty in umb-control-group, because else the label will always have the for attribute. 

Example in this jsfiddle: https://jsfiddle.net/zmo0vx50/

**Comment by nul800sebastiaan** [comment]
This is great @pelgro - thanks very much! 👍 

Do you have an account on Our Umbraco? I'd love to give you a contributor badge but I can't seem to find you.

**Comment by Nicholas-Westby** [comment]
Just a heads up, this will not account for labels that wrap elements, which will make the wrapped element be focused when the label is clicked:

```html
<label>
    Wrapping an input:
    <input type="text"/>
</label>
```

Perhaps it's fine that this doesn't account for that, but wanted to let you know just in case you were not aware.

**Pull request merged**
