### PR TITLE
GetCropUrl can now (easily) force return a file type

### PR DESCRIPTION
**Pull request by Ambertvu**
Now that WebP is fully supported, this seems like a great addition.

I've added an optional parameter to GetCropUrl so any file type that gets retrieved by it can be forced to a predefined (Enum) fileType. Currently I've added Jpg and WebP as formats.
I thought about adding Png but that just seems way off to do so. And if someone would really need it (for some reason) he could fall back to use the 'furtherOptions:' parameter.

You can easily test this by spinning up a installation and test using the MediaPicker (with crops) or just the ImageCropper.

Example code to easily test this. Just put this in a view with a CropItem (ImageCropper datatype) and a MediaItem (MediaPicker datatype) property.

```
<h2>Current functionality</h2>
<strong>Method: Model.CropItem</strong>
<span>Result:</span> @Model.CropItem
<br/>

<strong>Method: Url.GetCropUrl(Model.CropItem, "Small")</strong>
<span>Result:</span> @Url.GetCropUrl(Model.CropItem, "Small")
<br/>

<strong>Method: Url.GetCropUrl(Model.CropItem, "Normal")</strong>
<span>Result:</span> @Url.GetCropUrl(Model.CropItem, "Normal")
<br/>

<strong>Method: Url.GetCropUrl(Model.MediaItem, 500, 300, furtherOptions: "&format=webp")</strong>
<span>Result:</span> @Url.GetCropUrl(Model.MediaItem, 500, 300, furtherOptions: "&format=webp")
<br/>

<strong>Method: Model.MediaItem.GetCropUrl("Small")</strong>
<span>Result:</span>  @Model.MediaItem.GetCropUrl("Small");
<br/>


<h2>New functionality</h2>
<strong>Method: Url.GetCropUrl(Model.CropItem, "Small", fileType:ImageCropperForcedFileTypes.WebP)</strong>
<span>Result:</span> @Url.GetCropUrl(Model.CropItem, "Small", fileType:ImageCropperForcedFileTypes.WebP)
<br/><br/>

<strong>Method: Url.GetCropUrl(Model.CropItem, "Normal", fileType:ImageCropperForcedFileTypes.WebP)</strong>
<span>Result:</span> @Url.GetCropUrl(Model.CropItem, "Normal", fileType:ImageCropperForcedFileTypes.WebP)
<br/>

<strong>Method: Url.GetCropUrl(Model.MediaItem, 500, 300, furtherOptions: "&format=webp", fileType:ImageCropperForcedFileTypes.WebP)</strong>
<span>Result:</span> @Url.GetCropUrl(Model.MediaItem, 500, 300, fileType:ImageCropperForcedFileTypes.WebP)
<br/>

<strong>Method: Url.GetCropUrl(Model.MediaItem, 500, 300, furtherOptions: "&format=webp", fileType:ImageCropperForcedFileTypes.WebP) (Extra check to see it throws no errors)</strong>
<span>Result:</span> @Url.GetCropUrl(Model.MediaItem, 500, 300, furtherOptions: "&format=webp", fileType:ImageCropperForcedFileTypes.WebP)
<br/>

<strong>Method: Model.MediaItem.GetCropUrl("Small", fileType:ImageCropperForcedFileTypes.WebP)</strong>
<span>Result:</span>  @Model.MediaItem.GetCropUrl("Small", fileType:ImageCropperForcedFileTypes.WebP);
<br/>

<strong>Method: Model.MediaItem.GetCropUrl("Small", ImageCropperForcedFileTypes.WebP)</strong>
<span>Result:</span>  @Model.MediaItem.GetCropUrl("Small", ImageCropperForcedFileTypes.WebP)
<br/>

<strong>Method: Model.MediaItem.GetCropUrl("Small", ImageCropperForcedFileTypes.WebP)</strong>
<span>Result:</span>  @Model.MediaItem.GetCropUrl("Normal", ImageCropperForcedFileTypes.WebP)
```

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks @Ambertvu! Maybe `ImageCropperForcedFileTypes` is also a bit too.. forceful ;-) ? Maybe just call it `Format` like ImageSharp does? And why hardcode it to just jpg and webp? 

Or maybe that just shows my ignorance, I don't really know what the idea behind this PR is.. it seems that it's to make it more discoverable that you can convert images to a different format?

**Comment by Ambertvu** [comment]
Thanks for your reply @nul800sebastiaan, naming is always a thing, but lets first focus on the functionality and if you even want it to be merged :-)

My idea is indeed to make it more easily accessible for all your cropping needs. Now that WebP is basically 'the' new format to use, and Imagesharp can easily convert them to WebP, resulting in (from my experience) in a 10-20% file size reducement, my wish was to add this so its far more easy to convert all your cropper outputs to WebP. 

I've chosen JPG and WebP because I couldnt think of any other formats you'd want to force the output to.

PNG? Rather not, it will increase your filesize even
SVG? Not an option, different data

**Comment by Ambertvu** [comment]
On second thought, I think I know what you mean..  Perhaps an good documentation update is enough even.. 
You can basically already do the things I wrote.

For some reason I didn't know that in:
```<strong>Method: Url.GetCropUrl(Model.CropItem, "Normal")</strong>
<span>Result:</span> @Url.GetCropUrl(Model.CropItem, "Normal")
```
You could already easy add `furtherOptions: "&format=webp` to the method and it works. I was always thinking it was only possible in the extended method (perhaps something legacy that got stuck in my head? no idea)

**Comment by nul800sebastiaan** [comment]
Hi again @Ambertvu - sorry busy week! I have had a chat with the team to see how they feel and in this case we won't be going this way. 

While it is more discoverable that you can "WebP all the things" in intellisense, we also know that by exposing more default ImageSharp functionality in a proprietary way in Umbraco, we end up exposing an incomplete copy of the ImageSharp API. Sometimes that's the Friendly thing to do but in this case it feels like we're getting too intertwined with a dependency.

You've already discovered it's perfectly possible to add a querystring to get the same result, which is the whole premise of ImageSharp to begin with, we love that and it works well, maybe a docs update would be good indeed for highlighting that! 👍 

As an additional tip @ronaldbarendse added:

> And specifically for converting to WebP you want to check whether the source format is lossy (like JPEG) or lossless (like PNG), as WebP supports both... For PNG you probably want to add &format=webp&quality=100 to ensure it's losslessly encoded :slightly_smiling_face:

Thanks for your first PR attempt, I hope you at least had fun digging in and we look forward to seeing more from your hand! 🌟

**Comment by Ambertvu** [comment]
@nul800sebastiaan Completely understandable! Had indeed fun digging in and making stuff, and learning some new Umbraco features (and C# even), I was a bit too eager ;-)

You haven't heard the last of me ! 🙂

**Pull request closed without merging**
