### PR TITLE
V8: Content types with description look weird in the create dialog

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

405e9a79 (I think) introduced an alignment issue in the content creation dialog for content types with descriptions:

image

This PR fixes it - when applied the content type name and description align nicely to the left:

image

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @kjac ,

Many thanks for this PR. Looking at it now :-)

Poornima

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by nul800sebastiaan** [comment]
Nice one @kjac - cheers!

**Comment by nul800sebastiaan** [comment]
Cherry picked for 8.1.2 in commit ce5b3531e09958a06e06e69274a214a89563e29a

**Pull request merged**
