### PR TITLE
Issue 17128 - Fix GetMediaByPath when querying for media which has been uploaded with dimensions in the file name

### LINKED ISSUE #17128: Issue with uploading images containing _[width]x[height] in the file name
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.5.0

### Bug summary

When the editor uploads an image with _[width]x[height] at the end of the file name (e.g., image_1270x770.png), the image cannot be retrieved using IMediaService.GetMediaByPath.

### Specifics

- No error message is displayed; the image simply cannot be found via IMediaService.GetMediaByPath.
- Example file name: image_1270x770.png

### Steps to reproduce

1. Log in to the Umbraco back office.
2. Navigate to the media section and upload an image with a file name containing _[width]x[height], such as image_1270x770.png.
3. Try to retrieve the uploaded image using IMediaService.GetMediaByPath.
4. Notice that the image cannot be found.

### Expected result / actual result

Expected result (one of):

- The image should be uploaded and retrievable through IMediaService.GetMediaByPath, regardless of the naming pattern.
- The image shouldn`t be uploaded and the error message should be shown.

Actual result:

- The image is uploaded successfully, but it cannot be retrieved using IMediaService.GetMediaByPath when the file name contains _[width]x[height].

### PR DESCRIPTION
**Pull request by justin-nevitech**
### Prerequisites

- [X] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes:

Fixes #17128 

### Description

This PR fixes the issue raised in #17128 where media is uploaded to the media library with dimensions in the file name but then cannot be queried using IMediaService.GetMediaByPath (see issue details for more information).

All tests have run and pass.

## Steps to Test

1. Upload a file to the media library which has the name in the format [name]_[width]x[height].[ext], i.e. test_200x200.jpg.
2. Add the following code into a template to test that the GetMediaByPath finds the media item:

```
    @inject IMediaService MediaService;

    var media = MediaService.GetMediaByPath("add path to media file here which includes the dimensions");

    if (media != null)
    {
        <p>Media Found! @media.Id</p>
    }
    else
    {
        <p>Media not found!</p>
    }
```

3. Repeat the same test with an image that does not contain the dimensions in the file name to ensure this gets returned by GetMediaByPath.

## Notes

To be honest, I can't find what may have originally created media files with dimensions in the name, it looks like something must have done this in the past when uploading (so resized images are supported).  I can't see where this is done or if it's legacy code so I couldn't see how to test this aspect.

I've completed this PR on v14 but it will need merging into v13 and v15 as well.

### CODE REVIEW

**Comment by Zeegaan** [comment]
@justin-nevitech Seems like theres some issue in the branch you're pointing at 😁 
Could I get you to point your fix at the `v13/dev` branch 🙏

**Comment by nul800sebastiaan** [comment]
I tried switching it to `v13/dev` but that made it a lot worse (with 5100 commits in the PR). 

@justin-nevitech could I please ask you to try again, in your fork, make sure that `v13/dev` is up-to-date with the main repo's `v13/dev` and then apply your fix there. That way it should be only a single commit and the PR is nice and clean!

You should be able to cherry-pick this commit for this PR to the `v13/dev` branch as well.

I'll close this one for now! Thanks for the help so far 🙏

**Comment by justin-nevitech** [comment]
Hhhhm, not sure why is was an issue as I based it on v14/dev which I pulled down fresh last night?  I will re-submit based on v13/dev.

**Comment by nul800sebastiaan** [comment]
Ah I couldn't see that. It's just that the `contrib` branch is on v15 so you it's trying to compare v14 to v15 + your change. 

In general, I'd advise to always put things on top of `contrib` branch, and note if you think it should be applied to earlier versions as well. What would happen is that it gets merged and tagged for the next release and I get to cherry pick the fix to older versions where needed.

Sorry for the confusion!

**Pull request closed without merging**
