### PR TITLE
U4-9003 - Add checkboxlist prevalue editor

### PR DESCRIPTION
**Pull request by bjarnef**
Issue: http://issues.umbraco.org/issue/U4-9003

Currently there is a radiobuttonlist prevalue editor, but not a checkboxlist prevalue editor. A scenario where a checkboxlist prevalue editor would be useful it for e.g. a weekdays property.

Actually I was missing this in this PR https://github.com/umbraco/Umbraco-CMS/pull/984 to extend datepicker options. At the time of submitting the PR it created this weedays checkboxlist prevalue editor, but it would be great to have it in core: https://github.com/bjarnef/Umbraco-CMS/blob/0dbf686a0fa3bf8c3f4c701498b7b457ee9998f6/src/Umbraco.Web.UI.Client/src/views/propertyeditors/datepicker/weekdays.prevalues.html

Umbraco seems to include checklist-model, but I am not sure how much it is used: https://vitalets.github.io/checklist-model/ 

As an alternative it could have a controller to split the selected values.

It could also be useful it grid editor settings. I also included the option to define the labels , which @clausjensen added in this PR https://github.com/umbraco/Umbraco-CMS/pull/1486

image

Both radiobuttonlist and checkboxlist is missing the option to specify prevalues from package.manifest:
http://issues.umbraco.org/issue/U4-7030

### CODE REVIEW

**Comment by bjarnef** [comment]
In d0e3440 I have added the option to choose an icon for each prevalue, which could enhance the editor experience.

```
[
  {
    "label": "Rating type",
    "description": "Choose option",
    "key": "class",
    "view": "radiobuttonlist",
    "applyTo": "row",
    "prevalues": [
      {
        "label": "Star",
        "value": "star",
        "icon": "icon-gmd-star"
      },
      {
        "label": "Heart",
        "value": "heart",
        "icon": "icon-hearts"
      },
      {
        "label": "Thumb up",
        "value": "thumb",
        "icon": "icon-gmd-thumb-up"
      }
    ]
  },
  {
    "label": "Responsive utilities",
    "description": "Choose options",
    "key": "responsiveUtils",
    "view": "checkboxlist",
    "applyTo": "row",
    "prevalues": [
      {
        "label": "Hide on small devices",
        "value": "xs",
        "icon": "icon-mobile"
      },
      {
        "label": "Hide on phones",
        "value": "sm",
        "icon": "icon-iphone"
      },
      {
        "label": "Hide on tablets",
        "value": "md",
        "icon": "icon-ipad"
      },
      {
        "label": "Hide on desktop",
        "value": "lg",
        "icon": "icon-pc"
      }
    ]
  }
]
```

image

**Comment by madsrasmussen** [comment]
Hi Bjarne,

Thanks for the PR. I have tested your changes and the back office part works like a charm. I do though think that the icons are a bit to big, so if we can make them a bit smaller that would be awesome (24px ex).

Before we are able to pull this in we need it to work “out of the box” by updating the bootstrap renderes in core found in /views/partials/grid/ so we are able to handle a config setting with multiple values. If you are able to do this, that would be totally awesome.

Thanks.

**Comment by bjarnef** [comment]
Hi Mads

Yes, we could change the font size a bit. I thought about if icon should be an object, it one want to decide the size like "small", "medium", "large" and other properties like color or is that a bit too complex? :)

The "responsive utilities" was just an example. You might also was to use it for appending some classes or some other settings, where multi choices makes sense.

I don't think the radiobuttonlist do something with the grid either?

**Comment by madsrasmussen** [comment]
Icons: I think this is the right way to do it. Setting size and color will be too complex in my opinion. If you wan’t this kind of flexibility I think the right solution will be to build a custom config editor.

Renderes: We do handle the radio config in the bootstrap renderer: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI/Views/Partials/Grid/Bootstrap3.cshtml#L66 so we need to handle an array of values here and in the other renderes too. I think it's okay if it's out of the box works with the key: "class" (as the radio config) and that it's only possible to use one of them at the time. Again, if people wan't a more complex setup they should make a custom renderer.

**Comment by hemraker** [comment]
Hey @bjarnef did you have a chance to look at rendering the checkbox values in the default renderers?

In order for this to be pulled in we need to make sure it works otb :)

**Comment by bjarnef** [comment]
Hi @hemraker .. I'll see if I have done time in the weekend to look at it.. I think it just need to split the array and join the keys e.g. for classes. And maybe ignore it if the alias is id since multiple values in id attribute not is valid.

**Comment by bjarnef** [comment]
@madsrasmussen @hemraker I have added some more logic in cc8b39c .. 
For *styles* I don't think it make sense with multiple values in same key, so I have just made a check for `JValue` here.

For *settings* I have added check for `JValue` and `JArray` and if type is `JArray` it looks for "value" property if it is an object, otherwise it just use the value.

So e.g. with this config in grid settings in works:

```
[
  {
    "label": "Responsive utilities",
    "description": "Choose options",
    "key": "class",
    "view": "checkboxlist",
    "applyTo": "row",
    "prevalues": [
      "xs",
      {
        "label": "Hide on phones",
        "value": "sm",
        "icon": "icon-iphone"
      },
      {
        "label": "Hide on tablets",
        "value": "md",
        "icon": "icon-ipad"
      },
      {
        "label": "Hide on desktop",
        "value": "lg",
        "icon": "icon-pc"
      }
    ]
  }
]
```
image

The part with `OrderByDescending` order the values, so it match the order of the prevalues in config - without this, it list the values in the order they were selected (by checklist-model directive).

In Fanoe starterkit if changing background-color in settings from radiobuttonlist to checkboxlist, it then add multiple classes.

```
[
  {
    "label": "Background color",
    "description": "Choose background color",
    "key": "class",
    "view": "checkboxlist",
    "applyTo": "row",
    "prevalues": [
      "light",
      "dark",
      "yellow",
      "blue",
      "purple",
      "full",
      "full triangle"
    ]
  }
]
```

image

**Comment by bjarnef** [comment]
I just had another case, where I think it would be useful to have a checkboxlist prevalue editor, when I want to add borders (top and bottom) of grid rows.

image

For now I can add the checkboxlist prevalueeditor from this PR and use the following code the join the selected values seperated by a space and add this in the class attribute on the row.

```
if (property.Name == "grid-border")
{
      // join multiple values from checkboxlist
      var items = (JArray)property.Value;
      var values = items.Select(o => o.Type == JTokenType.Object ? o.SelectToken("value") : o.Value<string>()).OrderByDescending(x => x);
}
```

**Comment by bjarnef** [comment]
@nul800sebastiaan can you have a look at this? It would be great to have a checkbox list prevalue editor, e.g. for weekdays in a datepicker property editor og any other custom property editor which need to a multiple select in its configuaration.

**Comment by bjarnef** [comment]
@nul800sebastiaan maybe you have some time to test this one? It would be great if it could be included in v7.14 and/or in v8 😁

**Comment by bjarnef** [comment]
@nielslyngsoe maybe you want to have a look at this or use this in a new PR.
We have had the `radiobuttonlist` prevalue editor since the Grid editor was introduced in v7 (or maybe already since v7 was released). So it would be great to also have a `checkboxlist` prevalue editor and besides using this in Grid settings/styles I also think property editors can benefits from this, e.g. you could use it for weekdays prevalues in config of e.g. a custom datepicker property editor.

**Comment by nul800sebastiaan** [comment]
Hey there @bjarnef!

I'm writing today after anouncing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Pull request closed without merging**
