### PR TITLE
U4-11372 - Make history section on Info tab translatable

### PR DESCRIPTION
**Pull request by AndersBrohus**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description

After getting som help from @abjerner so i did not go the singleton way, i think i figured out how to do then :)

After going through the backend i made the decision only to make the changes in the ContentService since it was the only one i could find that had a history tab :)

I have made the basic danish translations and then copied the hardcoded ones for en and en_us :)

From my tests it works but i can't figure out where the "DeleteContentOfTypes" function runs, so i don't know if that works :)

Please keep in mind that this is only the "ContentService" that has been "translated".

Still working through some other stuff so these messages also becomes translateable,

Copied content with Id: '1145' related to original content with Id: '1126'
Version rolled back to revision '9982ee12-c3df-4dd5-ac0d-68c03c6b2a0a'
Trashed content with Id: '1126' related to original parent content with Id: '1144'

Just wanted to create the PR so i could get some advice if this is the right way of doing it :)

### CODE REVIEW

**Comment by AndersBrohus** [comment]
Okay i could not go to bed without having made the three last translateable, but they are now! 😄 

So now it's only the "labels" i need :)

"Copy"
"Publish"
"Move"
"Save"
"UnPublish"
"Delete"
"RollBack"

**Comment by AndersBrohus** [comment]
Okay, so i'm nearly done :)

Only missing the "status label" but i can't figure out why i does not work :/

I got this ..

`<localize key="auditTrails_small{{ item.logType }}">{{ item.logType }}</localize>`

And the output is "[auditTrails_small]", BUT when i open the developer tools i can see that the key is "auditTrails_smallUnpublished" which it should output and then the translation will be visible .. :)

But it wont!

I took the same approach at the status labels in the "History" section .. :)

**Comment by AndersBrohus** [comment]
So i can't figure out how to solve the last issue i got, the "status" label in the sidebar .. :/

But the other is translateable .. :)

Maybe the angular master @madsrasmussen can help? :)

**Comment by nul800sebastiaan** [comment]
Not to worry, we'll find you some help! 👍

**Comment by abjerner** [comment]
@AndersBrohus I'm not entirely sure that you can use variables within the `key` attribute. If I remember correctly, this has also caused me some problems in the past.

If this isn't possible, you can instead use the `localizationService` Angular service within the controller. Sorta like I've done here:

https://github.com/skybrud/Skybrud.Umbraco.Redirects/blob/master/src/Skybrud.Umbraco.Redirects/App_Plugins/Skybrud.Umbraco.Redirects/Scripts/Controllers/Dashboards/Default.js#L21

```
localizationService.localize('redirects_media_' + type.value).then(function (value) {
    type.name = value;
});
```

<hr />

If handling it in the Audit trail controller/directive, I would do it something like below:

add here:

https://github.com/umbraco/Umbraco-CMS/blob/59f9a64e816e40e52a64e1636f743da5effb98b6/src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbcontentnodeinfo.directive.js#L94

```js
    angular.forEach(data.items, function (item) {
        item.logTypeName = item.logType;
        localizationService.localize('auditTrails_small' + item.logType).then(function (value) {
            item.logTypeName = value;
        });
    });
```

This iterates over each audit trail item and then sets the `logTypeName` property. You can then use `{{item.logTypeName}}` instead of the entire `<localize />` directive ;)

<hr />

**Disclaimer:** I haven't tested that the above example actually works, so feel free to ping me if it doesn't - then I'll have another look ;)

**Comment by madsrasmussen** [comment]
I don't remember off the top of my head whether you can use variables for the localization directive. But as Anders said you can use the localization service. 

We have a localizeMany function where you can just pass in an array of keys and you then get all the translations back in the same order as you passed them in. Something like this: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/views/templates/edit.controller.js#L47

**Comment by AndersBrohus** [comment]
Okay so i began debugging since the "localizationService.localize" also returned english text when the user was danish ..

Figured out it was because there wasn't any keys any of the specificed keys in the danish translation and then it fallbacked to the english one .. 😆 

But now i have used some time testing it and for me it seems like it's working really good :)

So i'm really looking forward for HQ's feedback :)

Thanks for all your help @abjerner and @madsrasmussen and of course @nul800sebastiaan 😄

**Comment by abjerner** [comment]
@AndersBrohus I've looked through the code, and it looks good so far. I think you've done an awesome job 👍 

The Umbraco site in the repository do however take longer than usual to boot up or it may have crashed (nothing to do with your pull request), so I haven't been able to test your changes in the backoffice yet. I will try to do that tomorrow ;)

**Comment by AndersBrohus** [comment]
Yeay sounds great 😊

Mine boots but it takes a little time 😊

**Comment by abjerner** [comment]
@AndersBrohus I spotted an error, which seems to be caused by one of translations that you added, but underneath it's really a bug in Umbraco.

image

The sort dialog uses `<%=umbraco.ui.Text("save") %>`. The `Text` method has a number of overloads, but when using the version with just a single parameter, no section is specified. It seems that the `save` translation that you added to the `auditTrails` overwrites the one from the `buttons` section (parrently this only happens when we don't specify a section).

By using one of the overloads, we can explicitly specify the section, and we get the right button label. It seems to work if you change `<%=umbraco.ui.Text("save") %>` to `<%=umbraco.ui.Text("buttons", "save") %>` ;)

@nul800sebastiaan any thoughts on this? It may be more than just the sort dialog that is affected. It seems that the bug is in the text service, although I haven't found the exact location yet. That exact method signature is used a bit throughout the solution:

image

**Comment by abjerner** [comment]
@AndersBrohus In the `rollBack.aspx.cs` file, you've changed the part that logs the action to the database so that the message is translated. In a way this is what we wanted, but the message is saved using the language of the current user, at the time of the rollback - so it will always show up in that language in the backoffice, regardless of the language selected by other users in the backoffice.

https://github.com/umbraco/Umbraco-CMS/pull/2650/commits/8a27b692421a3317354784fcd68825e76216d199#diff-1a6c326a86bcea8ba42f22addd4519c9R144

Eg. I started out using the backoffice in English, rolled back and page and did some other changes. Then later, I changed my language to Danish, and rolled back another time.

The result is that the first two log entries are saved in English, and the last two are saved in Danish.

image

This get's a little messy, which may partly be because this is some old legacy code. I guess the solution would be to store the necessary data/tokens instead of a message, and piece the message together when it's being served for the backoffice. I do however not know how much work this would require, as there may be other places in the backoffice relying on the message, which we'll have to update as well. 

@nul800sebastiaan any thoughts on storing tokens instead of the message? Or suggestions for other solutions? Assuming v8 has gotten rid of the `BusinessLogic` namespace, how is it handled there?

@AndersBrohus the rest of the changes I've looked through so far seems to work as intended. Considering this is your first code pull request to Umbraco, I think you have done a great job 👍

**Comment by AndersBrohus** [comment]
Hi @abjerner :)

I guess the first problem can be solved very easily :)
Because i could just give the keys an other name :)

To the second problem, as @nul800sebastiaan says on the issue (http://issues.umbraco.org/issue/U4-11372) "they are really just messages that come from the log." So it's basically just translated logs so then we need to rethink the whole pull request :)

Thank you very much! 😄

**Comment by nul800sebastiaan** [comment]
Yeah I think for now the log messages should be kept in English, we are already storing a category and a user Id so at most we should translate for example the category `BusinessLogic.LogTypes.RollBack` and show an appropriate message based on that in the backoffice, what we store as a comment in the database table should just be 1 consistent language though, it doesn't directly need to be exposed to the interface.

Does that make sense?

**Comment by nul800sebastiaan** [comment]
Aha, I see now that most of this PR deals with these log messages hmmm.. 🤔

**Comment by abjerner** [comment]
@nul800sebastiaan rollback was the only one I spotted being translated at the time of the event - the rest seems to be handled in the UI, which is correct.

**Comment by nul800sebastiaan** [comment]
Ah sure but there's also audit events like these: https://github.com/umbraco/Umbraco-CMS/pull/2650/files?w=1#diff-67fd3c61b9afd5b998696bf88f5694f2L1156

**Comment by abjerner** [comment]
Oh, my bad. I had missed those 😊

**Comment by AndersBrohus** [comment]
Damn 😬🙈

**Comment by nul800sebastiaan** [comment]
I'll give this some additional though @AndersBrohus - we do have the categories already so we might "just" be able to translate those when getting the history overview (instead of saving localized text in the log table).

Not sure yet :-)

**Comment by AndersBrohus** [comment]
Arh so just manipulation with the data inside Angular? :-)

**Comment by AndersBrohus** [comment]
Okay @abjerner  and @nul800sebastiaan i have rolled back and changed inside the Angular view, so NOW it should work perfectly all over :)

**Comment by AndersBrohus** [comment]
And @abjerner i have fixed the "problem in the dialogs" :)

I just moved the "auditTrails" section below "buttons" and now it's "working", but it's the problem still exist..

**Comment by nul800sebastiaan** [comment]
Thanks @AndersBrohus - I hope to look at this this week! 👍

**Comment by AndersBrohus** [comment]
Sounds great 😄

**Comment by nul800sebastiaan** [comment]
See screenshot as well: 

image

**Comment by AndersBrohus** [comment]
Of course, will do that later today @nul800sebastiaan :)

**Comment by AndersBrohus** [comment]
Hi again @nul800sebastiaan 

Last four translations added in the en.xml, en-us.xml and da.xml :)

**Comment by nul800sebastiaan** [comment]
Thanks @AndersBrohus - I've squashed and merged the whole thing now! Thanks for hanging in there and thanks very much for the contribution! 🎉

**Comment by nul800sebastiaan** [comment]
@AndersBrohus One tip for future contributions - these files only had whitespace changes and nothing else, they don't need to be committed and pushed:

image

I've just reverted these changes now so we're left with only 3 changed files! 👍

**Comment by AndersBrohus** [comment]
Thanks alot @nul800sebastiaan 😄 

I guess that the reason those files where changed in the first place was because of my mistake, by not translating in the Angular 😄

**Comment by abjerner** [comment]
Good job @AndersBrohus 👍

**Comment by AndersBrohus** [comment]
Thanks @abjerner :-D

**Comment by nul800sebastiaan** [comment]
@AndersBrohus Yep, so when you stage your files for checkin in git, make sure to inspect each one of them and only check in the ones that you actually had to make changes in.

**Comment by abjerner** [comment]
@nul800sebastiaan I think it was because he did initially did the translations in the services (I may accidentally have suggested that as I didn't see the full picture).

**Comment by AndersBrohus** [comment]
@nul800sebastiaan as @abjerner said that i did the translations in the services, then when we tested it enough we found out that this wasn't the right way to do it, so i reverted back and removed my changed :)

Which then made the changes :)

I will of course remember it next time :)

**Comment by nul800sebastiaan** [comment]
Ah yes, I see! Cool, well no harm done, just wanted to note it. It was all good anyway and happy to fix up things like this! :-)

**Pull request merged**
