### PR TITLE
V8: Force cachebust Nested Content items to handle content copying

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5913

### Description

See #5913 for a detailed description. 

The gist is: When copying a Nested Content property, the element keys embedded in the property data is obviously copied along with it. Because the element cache is based on the element keys, this becomes a problem if you want to render both the original and the copy within the same request.

#### Steps to reproduce

1. Create a Nested Content datatype using an element type with a property of type Textstring named  `Text`.
2. Add the datatype to a doctype and name it `List`.
3. Create a piece of content based on this doctype and add a few items to `List`.
4. Create a few copies of the content. Edit `Text` of all items in each copy so they're unique.
5. Render the original content using the template below. Replace the values of `contentIds` with the IDs of the original and the copies.
6. Notice how the rendered output is the same for each content, despite all values being unique.

Here's how it looks:

nc-copy-cache-before

...and here's the template for testing:

```cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
	Layout = null;
	// TODO: replace 1111, 2222, 3333, 4444 with the IDs of the original and all copies 
	var contentIds = new [] {Model.Id}.Union(new [] {1111, 2222, 3333, 4444}).Distinct().ToArray();
}

<html>
    <body>
        @foreach(var contentId in contentIds) {
            var content = Umbraco.Content(contentId);
            var list = content.Value<IEnumerable<IPublishedElement>>("list");
            <h3>@content.Name (@contentId)</h3>
            <ul>
            @foreach(var element in list) {
                <li>@element.Value("text")</li>        
            }
            </ul>
        }
    </body>
</html>
```

#### The fix

This PR fixes the caching issue by assigning a new `Guid` to each element every time the cache is populated, instead of using the `key` property assigned to the element (the one that's copied along with the Nested Content data).

When applied, the copies render as you'd expect:

nc-copy-cache-after

#### But it's a hack?!

Yes. It is a hack. But right now I don't see any other (feasible) way around it.

I have tried changing the value of Nested Content's `PropertyCacheLevel`. As you'd expect that didn't work, but it was worth a shot.

I tried updating the `key` value of each element on save in [this method](https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web/PropertyEditors/NestedContentPropertyEditor.cs#L201). It works. But it is just as much a hack, and I'm not terribly fond of modifying the keys created on the client as they're actively used in the clientside controller for element identification. It also is an irreversible change to the editor data, whereas the proposed solution can be rolled back later on in favor of a non-hacky solution.

#### Is there a penalty?

I have not been able to identify any penalties to this solution, performance or caching wise. The elements are still cached on first hit, and subsequent renderings of the content or other content based on the same type and using the same template do not incur any extra rendering or caching of these elements.

#### Suggested approach (future)

One less hacky solution would be to propagate `EntityBase.ResetIdentity()` to the individual property implementations and let them modify the property data accordingly. 

This however would entail a performance impact, as each property would have to wire up their implementations, apply the property data and execute the identity reset. It is also likely to be a breaking change.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Brilliant, brilliant stuff. I love a good hack! We'll probably have to have a good chat about this one. Thanks for putting so much detail here though Kenn. It gives us plenty to work with.

Speak soon,

Em

**Comment by ronaldbarendse** [comment]
@kjac Why would you generate random keys to avoid the caching if you can also just change/disable the caching itself on the value converter? This just creates unwanted side-effects, for example when a site uses the (static) key to identify the NC item on that page (sections, anchors, selects/dropdowns, etc.).

The `NestedContentValueConverterBase` doesn't override the `GetPropertyCacheLevel` method, but both `NestedContentSingleValueConverter` and `NestedContentManyValueConverter` do and set this to `PropertyCacheLevel.Element`. This can be easily changed to disable caching (although it's probably better to merge this by moving it to the base class):

```c#
public override PropertyCacheLevel GetPropertyCacheLevel(IPublishedPropertyType propertyType) => PropertyCacheLevel.None;
```

What strikes me as odd, is the comment for `PropertyCacheLevel.Element`:
https://github.com/umbraco/Umbraco-CMS/blob/3bfd9b71e290354744d677440983ecd06c5c0788/src/Umbraco.Web/PublishedCache/PublishedElementPropertyBase.cs#L131-L132

This would make you believe the current cache level would be correct and cache the NC item per content/page, which it clearly isn't!

**Comment by kjac** [comment]
@ronaldbarendse thank you for investigating. Unfortunately (as I wrote in the initial description) I did try changing the property cache level on the value converter implementations to no avail. The elements are cached by key in the current request. Hence this solution.

**Comment by ronaldbarendse** [comment]
@kjac Just to be sure: did you change it in both the `NestedContentSingleValueConverter` and `NestedContentManyValueConverter`, as these override any cache level set in `NestedContentValueConverterBase`? And what cache levels are passed into the `ConvertIntermediateToObject` and therefore `ConvertToElement` methods?

If disabling the value converter cache still caches the element, that's probably done in the `IPublishedModelFactory` or the `IPublishedElement` itself...

Anyway: adding this hack would only introduce other unwanted side-effects, while the issue only occurs if NC items with the same key (caused by copying content) are retrieved _in the same request_.

**Comment by kjac** [comment]
@ronaldbarendse I did change it in both converters, yes 😄 

Disabling the cache entirely is not an option if you ask me. The ideal solution to this problem would be to regenerate the keys on copy, as mentioned above. However I don't think that's feasible short term.

**Comment by stevemegson** [comment]
Although the nested content itself is set to PropertyCacheLevel.Element, each PublishedElementPropertyBase within the element tries to take into account the cache level requested by its own value converter and choose the "shorter-lived" cache. If the "inner" value converter wants PropertyCacheLevel.Snapshot (as TextStringValueConverter does) then Snapshot will be used for that property, leading to the clash between different elements with the same key.

The simplest solution may be to have PublishedElementPropertyBase.GetCacheLevels never return Snapshot, and instead return None when ReferenceCacheLevel is Element and PropertyType.CacheLevel is Snapshot.

There'd be some performance impact if you're repeatedly accessing the same (non-copied) element in the same request, but hopefully that's minimal. If we really want to avoid that then we could have PublishedElementPropertyBase use a random Guid in its ValuesCacheKey rather than using Element.Key.

**Comment by ronaldbarendse** [comment]
So the NC element itself isn't globally cached (not `Elements` or `Snapshot`), but the properties within that item might be and would then use the element key in the cache key, which isn't unique enough (as it can be copied).

I would refrain from generating unique keys (besides the already noted side-effects, this could fill up the cache with duplicate items on different cache keys!) or re-generating the key on copy/save, as that would require implementations for every property editor that uses elements!

@Shazwazza @nul800sebastiaan This should be fixed properly, probably by including more info in the property cache key:
https://github.com/umbraco/Umbraco-CMS/blob/3bfd9b71e290354744d677440983ecd06c5c0788/src/Umbraco.Web/PublishedCache/PublishedElementPropertyBase.cs#L65-L66
https://github.com/umbraco/Umbraco-CMS/blob/3bfd9b71e290354744d677440983ecd06c5c0788/src/Umbraco.Web/PublishedCache/PublishedElementPropertyBase.cs#L77-L80

Adding the `IPublishedContent`s key would fix this, but only the `IPublishedElement` is available in `PublishedElementPropertyBase` and we should also make sure this works correctly for deeper nested elements, e.g. Nested Content within Nested Content...

**Comment by ronaldbarendse** [comment]
@Shazwazza @nul800sebastiaan Do you have any feedback on my last comment? Fixing this would require some major changes in the way the cache keys can be generated or to ensure the IDs can never be the same...

Besides copying a single NC item, PR https://github.com/umbraco/Umbraco-CMS/pull/5706 is already merged for 8.2.0, so duplicate element IDs may become even more common...

**Comment by lcichanowicz** [comment]
@emmaburstow, it seems this is still an issue. Might there be a related issue with an update?

**Comment by Shazwazza** [comment]
Will close this PR as we'll need to implement something a little different to maintain unique/consistent keys when copying.

**Comment by enkelmedia** [comment]
I have the same problem on 8.5.5, @Shazwazza is the "something" that you are referring to implemented? Or is there any known work around?

**Comment by nul800sebastiaan** [comment]
@enkelmedia Some exciting reading awaits you in issue https://github.com/umbraco/Umbraco-CMS/issues/5913 😉

In short, this is not fixed yet and the issue is up for grabs with a description on how we'd like to see it fixed.

**Pull request closed without merging**
