### PR TITLE
Added missing property index value factories

### PR DESCRIPTION
**Pull request by bergmania**
### Summary
- Added property index value factories for:
  - Block Grid
  - Block List
  - Nested Content
  - Tags
- Added no-op property index value factories for:
  - Media Picker
  - Image Cropper

### Test
- Use complex property editors and inspect the InternalIndex, Those should not be json anymore

### CODE REVIEW

**Review by nikolajlauridsen — APPROVED** [review]
LGTM 💪 

Tested with all the editors, tried both save, save and rebuild index, and save and publish and it all behaves as expected 👍 Just waiting for lights to go green

**Comment by LennardF1989** [comment]
@nul800sebastiaan @bergmania There is a breaking change in this that is not documented. If you have BlockList on a DocumentType that is set to Vary by Culture, then ALL the properties of the Block Element in that BlockList ALSO need to be Vary by Culture. Otherwise ther `SetValue` exception of `Property` will trigger:
```
        if (!PropertyType.SupportsVariation(culture, segment))
        {
            throw new NotSupportedException(
                $"Variation \"{culture ?? "<null>"},{segment ?? "<null>"}\" is not supported by the property type.");
        }
```

To me, this seems like an unintended scenario. Just because the BlockList itself is vary by culture, doesn't mean the Element Type has to be. This would only make sense if Block Elements themselves would actually be vary-able - but they aren't (yet). I'll make an issue.

**Comment by LennardF1989** [comment]
See #14149 - Tagging to put relation in place.

**Comment by bergmania** [comment]
Hi @lukehook.. It's definitely a fine balance.. We considered it a bug these was never implemented and thereby had unexpected behaviour.

In reality every single bug fix is behavioural breaking, for those relying on the buggy implementation. We was aware this bug had been around for a long time. That was the reason we asked for [feedback in the RC](https://umbraco.com/blog/umbraco-113-release-candidate/)

> Due to the fact, those have been missing for quite some time, we encourage everybody to ensure you do not rely on the old behaviour. If it turns out, many are relying on the old behaviour, this bugfix is subject to change or being moved to Umbraco 12.

We did not have any feedback on this subject doing the RC period.

**Comment by lukehook** [comment]
No problem @bergmania, thank you for the explanation. Was an easy fix and agree it's the better solution totally, just wanted to mention in case it's something that came up from others. Apologies I hadn't seen the RC. Thanks again 😄

**Comment by nul800sebastiaan** [comment]
Marked as breaking as a marker for other people who might run into this problem, we still feel like it's a bugfix but obviously if people have already worked around the previous bug somehow (like Luke), that workaround might not work any more.

**Comment by mistyn8** [comment]
Should the `__Raw.{propname}.items[0].text` be in the order that the text props appear in the blockgrid? As not seeing that?
image
image
Also should this be just `__Raw.{propname}.text` ?

**Pull request merged**
