### PR TITLE
Hide colors from icon picker

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
I noticed it wasn't possible to hide colors from icon picker infinite editor. Sometimes when using this in custom property editors etc. one may not need the colors, just a icon to select.

I also noticed it "jumped" a bit on icon selection, because it add a 1px border (so it need to 1px transparent border by default - or something else to compensate the 1px solid border on selection.

Furthermore it seems the icons didn't align well for different sizes of overlay. While it may work in small overlay, it would be difficult to adjust correct for medium and large overlays also.

I have replaced this with CSS grid instead with fill the icons to its container, a bit gap between and minimum ~~70px~~ 60px width for each icon. `auto-fill` fill the container, while I noticed `auto-fit` would stretch the icon to full width when filtering for instance "umbraco".

https://user-images.githubusercontent.com/2919859/193059031-d790cc16-f079-4357-9b61-73dd73954654.mp4

I have attached the dashboard from the video above: [MyDashboard.zip](https://github.com/umbraco/Umbraco-CMS/files/9675546/MyDashboard.zip)

### CODE REVIEW

**Comment by bjarnef** [comment]
The current icon picker.

**Small**

image

**Medium**

image

**Large**

image

**Comment by bjarnef** [comment]
With changes in this PR.

**Small**

**Medium**

**Large**

**Comment by bjarnef** [comment]
@mikecp any chance you can review this one. It would be great to be able to hide colors ... and the icons are much better aligned in large overlay.

**Comment by mikecp** [comment]
Hi @bjarnef ,
Sure, I'll have a look at it tonight or over the week-end. Thanks for the reminder 😉

**Comment by mikecp** [comment]
Hi @bjarnef ,

Thanks for this PR, I checked and tested it and it works perfectly 👍
The spacing is indeed looking better now 😁
So I guess it's time to _finally_ merge it! 😅

Cheers!

**Pull request merged**
