### PR TITLE
Added labels to colors in the color picker.

### PR DESCRIPTION
**Pull request by Nicholas-Westby**
Added labels to colors in the color picker: http://issues.umbraco.org/issue/U4-5322

### CODE REVIEW

**Comment by Nicholas-Westby** [comment]
It's been several months now. Any word on pulling this into the core?

**Comment by KirschnerMatt** [comment]
Would love to see this in core

**Comment by zpqrtbnk** [comment]
Closed and replaced by https://github.com/umbraco/Umbraco-CMS/pull/2245 - which is heavily inspired from this PR - thanks!

**Comment by zpqrtbnk** [comment]
(more details on the issue tracker at http://issues.umbraco.org/issue/U4-5322)

**Pull request closed without merging**
