### PR TITLE
U4-11412 only show buttons in umb-confirm when callback is defined

### PR DESCRIPTION
**Pull request by dawoe**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org/issue/U4-11412

### Description

This PR fixes that buttons are shown in the umbConfirm directive when no callback is definend.

I also documented the directive for backoffice api docs

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi ,

Many thanks for your PR. We hope to review your PR within the next 14 days and let you know of the outcome.

Regards,
Poornima

**Comment by poornimanayar** [comment]
@dawoe can you please give me an idea on how I can test this?

Poornima

**Comment by dawoe** [comment]
Easiest is to go to src\Umbraco.Web.UI.Client\src\views\content\delete.html

And then remove on-cancel and on-confirm attributes

**Comment by nul800sebastiaan** [comment]
Thanks @dawoe good stuff!

**Pull request merged**
