### PR TITLE
V8/feature/5914 broken backoffice validation

### PR DESCRIPTION
**Pull request by rosrosros**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5914

### Description

The maxlength property defined on the datatype is now enforced on Save.
User can still add too much text, but is not allowed to save the invalid amount of data

This is implemented for both textarea and textfield
See GIF for new behavior 

text-length-validation

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @rosrosros ,

Thank you for your work once again! We shall review the work and get back to you if we need anything more. 

Regards,
Poornima

**Comment by kjac** [comment]
Merged 😄 thanks again, @rosrosros

**Comment by colin-tactuum** [comment]
Any idea when this will be included in an Umbraco release?

**Comment by kjac** [comment]
@colin-tactuum #5914 (which is the issue fixed by this PR) is slated for 8.6 👍

**Pull request merged**
