### PR TITLE
V8: Allow reordering of allowed child types

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/4923

### Description

This PR adds the ability to explicitly sort the allowed child content types as described in #4923.

It works for both content and media.

For content/media types allowed at root, the current sort order (by name) is preserved.

#### Demo: Content

sort-allowed-children

#### Demo: Media

sort-allowed-children-media

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @kjac 

Another fab change. We'll let you know if we need anything.

Em

**Comment by kjac** [comment]
@emmaburstow super. I'll push an extra commit shortly, there's a `console.log` in there somewhere 🙈

**Comment by poornimanayar** [comment]
@kjac , I am gonna test this now and let you know :-)

**Comment by poornimanayar** [comment]
Hi @kjac ,

Apologies it took a lot longer than I intended, PC issues! I have tested this and its all looking good! Happy to approve 👍 

Poornima

**Comment by kjac** [comment]
Merge conflicts resolved.

**Comment by kjac** [comment]
Merge conflicts resolved.

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by poornimanayar** [comment]
Verified against latest`v8/contrib` and merged! Great work @kjac !

**Pull request merged**
