### PR TITLE
U4-6593 - After sort, reset the TinyMCE editors with previous settings

### PR DESCRIPTION
**Pull request by allyen**
The problem is that when resetting the RTEs, the method tinyMCE.execCommand('mceAddEditor') uses the settings of the currently active RTE to create the new RTE. And these settings contain reference to control.value, thus setting all the reset editors to the same model value.

### CODE REVIEW

**Comment by Shazwazza** [comment]
Testing this now. I can replicate the original issue. Thanks a ton!!

**Comment by kgiszewski** [comment]
FWIW, we have (had) similar issue in Archetype, I had to disable the RTE from updating during our custom event.

https://github.com/imulus/Archetype/issues/268

Haven't really found the root of the issue.

**Comment by Shazwazza** [comment]
Might be worth having a look at this updated code to see if it's the same issue

**Comment by kgiszewski** [comment]
Yup :+1:

**Pull request merged**
