### PR TITLE
Show duplicate URLs instead of letting them cause an angular error

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/3842

### Description

Some colleagues of mine also ran into the issue described in #3842. While the correct solution is described in #3842 (removing the default URL provider when adding your own implementation of it), there really is no reason not to show the duplicate URLs in the UI. If anything it'll give you a hint that you've done something wrong.

In other words: This PR makes sure to show the duplicate URLs rather than to have them cause an angular error.

### Testing this PR

First add a custom url provider by adding the following to App_Code:

```cs
using Umbraco.Core;
using Umbraco.Web.Routing;
using Umbraco.Core.Configuration;
using Umbraco.Core.Configuration.UmbracoSettings;

namespace MySite
{
	public class MyApplicationEventHandler : ApplicationEventHandler
	{
		protected override void ApplicationStarting(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
		{
			UrlProviderResolver.Current.InsertTypeBefore<DefaultUrlProvider, SiteUrlProvider>();
			// UrlProviderResolver.Current.RemoveType<DefaultUrlProvider>();
		}
	}
	
	public class SiteUrlProvider : DefaultUrlProvider
	{
		public SiteUrlProvider() : base(UmbracoConfig.For.UmbracoSettings().RequestHandler)
		{
		}

		public SiteUrlProvider(IRequestHandlerSection requestSettings) : base(requestSettings)
		{
		}
	}
}
```

Then add a couple of dummy domains to your site root (doesn't matter that you can't browse the domains in the frontend, we're only testing the backend here):

image

And finally verify that the duplicate domains are listed on the info tab of your site root and that no angular error is shown in the developer console of the browser:

image

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Hmmm, I am not sure I agree here, yes, it's nicer not to show an ugly error but this also doesn't really help you figure out what the problem is. I'd prefer that there was an actual alert here that points out there must be something wrong. But I don't know if we can somehow detect it's a URLProvider problem or some other problem? 🤔

**Comment by kjac** [comment]
@nul800sebastiaan I can put a vague-ish alert in alongside the duplicate URLs (*"Looks like you have duplicate URLs, perhaps you have registered two URL providers?"*), but I don't really care much for putting alerts right into the UI. 

Perhaps a new health check is really what's needed to help diagnose the problem? Not sure it's actually possible to detect it specifically, but the same symptoms should be detectable at the very least.

Note: The duplicate URLs themselves don't cause a problem as-is, they just look rather out of place.

**Comment by nul800sebastiaan** [comment]
I don't really like the idea of alerts either.. but better to give people a hint than just showing duplicates.. then again, are duplicates harmful? I'll need to discuss this with people who know more about the subject, will get back to you!

**Comment by nul800sebastiaan** [comment]
Thanks @kjac ! We have discussed this at HQ and for now it is fine to just allow the duplicates, but it would be good to filter them and make it a unique list.

I repurposed some code from here: https://stackoverflow.com/a/40482611

This seems to work nicely. If you don't see any problems in it then I can merge it in.

**Comment by kjac** [comment]
@nul800sebastiaan I left the duplicates on purpose so one could see that something's wrong. 

If the intention is to remove/hide the duplicates, I would opt for doing so serverside. This way all the consumers of the content URL list would be given the same unique list to work with. It would be better in terms of debugging later on, in case the duplicate URLs would cause runtime issues for some reason; it'd be annoying to have some *duplicate URL something something* error thrown at you without being able to see the duplicate URLs in the UI.

I'm hope I'm making sense... 😆 and I'd be more than happy to do the serverside filtering if my rambling here made enough sense to justify it.

**Comment by nul800sebastiaan** [comment]
I'm not so sure, I think we should not bother editors with problems if we don't have to but hiding errors on the server might be hiding something serious that's wrong. It would be better that these things get logged as an exception so that they can be investigated as errors if and when they do occur.

**Comment by kjac** [comment]
@nul800sebastiaan right 👍 I'll pull your changes and test them; chances are I'll replace your implementation with the `uniq` method from underscore.js, if indeed it's available in the version bundled with V7.

**Comment by kjac** [comment]
@nul800sebastiaan underscore.js does indeed support `uniq` in the version bundled with V7, so I have updated your code to use that instead - despite your code working just fine, just... there's no reason to have a custom method for uniqueness when we have a library that supports it.

**Comment by nul800sebastiaan** [comment]
Ah duh.. of course we have underscore.js available, wonderful! Thanks very much for the update! 👍

**Pull request merged**
