### PR TITLE
U4-9034 - Add color picker prevalue editor

### PR DESCRIPTION
**Pull request by bjarnef**
Issue: http://issues.umbraco.org/issue/U4-9034

I have added a color picker prevalue editor, which can be used to e.g. select a background-color on a row or cell in the grid editor.

I have also included tinycolor, so it also works if specifying color names and convert it to a hex value. At the moment spectrum color picker also only allow hex colors, but maybe it should has enabled rgba in future releases?

image

```
 {
    "label": "Background color of row",
    "description": "Choose background color",
    "key": "background-color",
    "view": "colorpicker",
    "applyTo": "row",
    "prevalues": [
      "#D30535",
      {
        "value": "LimeGreen"
      },
      "#81E6E0",
      "#109D95",
      "red",
      {
        "label": "White",
        "value": "white"
      },
      "#53B3AE",
      {
        "value": "OrangeRed",
        "label": "Orange Red"
      }
    ]
  }
```

I am not sure how much of the validation it should have compared to colorpicker property editor. Ideally it should also allow package developers to use color picker as prevalue editor in property editor config, but like radiobuttonlist (and checkboxlist: https://github.com/umbraco/Umbraco-CMS/pull/1496) it should be possible to specify the prevalues from package.manifest

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
@bjarnef  Could tinycolor maybe also be useful for https://github.com/umbraco/Umbraco-CMS/pull/2864

And related to that, do you want to rework this one now that we have a color pallet component?

**Comment by bjarnef** [comment]
@nul800sebastiaan do you mean for saving the color in color picker or the issue with `hex-bg-color`?

I think I just use tinycolor for this, because you then in prevalues could specify the value as hex code or color name, so when accessing `$scope.model.prevalues` you get an array of objects, where `val` was used for `hex-bg-color` directive.

```
[
 { "val": "ffffff", "value": "#ffffff", "label": "White" },
 { "val": "000000", "value": "#ffffff",  "label": "White" }
]
```

It could maybe extend the prevalues to have a "useLabels" property (as in the color picker property editor). Based on this it could display the colors with or without labels as in PR https://github.com/umbraco/Umbraco-CMS/pull/2864.

```
 {
    "label": "Background color of row",
    "description": "Choose background color",
    "key": "background-color",
    "view": "colorpicker",
    "applyTo": "row",
    "prevalues": [
      "#D30535",
      {
        "value": "LimeGreen"
      },
      "#81E6E0",
      "#109D95",
      "red",
      {
        "label": "White",
        "value": "white"
      },
      "#53B3AE",
      {
        "value": "OrangeRed",
        "label": "Orange Red"
      }
    ]
  }
```

It would be great if we could finish this PR https://github.com/umbraco/Umbraco-CMS/pull/2864 first, then I can have another look at this one :)

**Comment by bjarnef** [comment]
It it would to convert the color names to its hex values, rgb(a) values etc.

Try here to enter one of the following:
- red
- f00
- #f00

https://bgrins.github.io/TinyColor/

or use one of the example links below the text input ;)

So no matter which format the color is, it is easy to get the hex code etc. 👍

**Comment by bjarnef** [comment]
@nul800sebastiaan okay, it would be fine with just hex colors in first place. I have will have another look at this PR, but I might create a new PR instead, which might be easier since this one in two years old 😁 

I will probably also see if I just can re-use the `umb-color-swatches` component for this as well 🦄

**Comment by bjarnef** [comment]
Hi @nul800sebastiaan 
I will close this PR, in favor of https://github.com/umbraco/Umbraco-CMS/pull/3212, which also re-use the `umb-color-swatches`.

**Pull request closed without merging**
