### PR TITLE
Fix KeepAlive Config so that value from appsettings.json is used

### PR DESCRIPTION
**Pull request by Jeavon**
Fix KeepAlive Config so that value from appsettings.json is used if present

Currently, any value in appsettings.json is ignored

### CODE REVIEW

**Review by nathanwoulfe — APPROVED** [review]
Cheers @Jeavon, changes behave as expected - prior, the appsettings value is not returned, with the changes in place appsettings:Umbraco:KeepAlive:KeepAlivePingUrl is returned when accessing IOptions<KeepAliveSettings>

I've added an update to the comment to reflect the property now having both getter and setter

**Comment by nathanwoulfe** [comment]
Test failures are unrelated - missing cypress artifacts

**Comment by Jeavon** [comment]
> I've added an update to the comment to reflect the property now having both getter and setter

Nice one, I didn't even think to check, cheers!

**Comment by nul800sebastiaan** [comment]
Ha! Tracked this one down now, the test failures were very much related.. the default config is invalid: https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Web.UI/appsettings.template.json#L36

Now that this is actually being used (yay, the PR worked!!), we're no longer able to start the site on Azure Devops because of the invalid config: `InvalidOperationException: The value {umbracoApplicationUrl}/api/keepalive/ping for parameter virtualPath must start with ~/ or /`. 
Fixing now.

**Comment by Jeavon** [comment]
@nul800sebastiaan ah darn, I noted that in my original docs question and I meant to change it but I totally forgot. It should be `~/api/keepalive/ping`

**Comment by nul800sebastiaan** [comment]
That's alright! 

Thanks, I tried to keep it at `~/{umbracoApplicationUrl}/api/keepalive/ping` but just realized that probably did nothing (and it didn't). So [`~/api/keepalive/ping` it is now](https://github.com/umbraco/Umbraco-CMS/commit/55419a04ac13536ce715b9e06bf1a3e238248dba#diff-83ccafe367c91b7e9d98144af4cd5b19f25f5aa498b2bd770697988bd4c06877R36)! Thanks again!

**Pull request merged**
