### PR TITLE
Grant access to get all content types 

### PR DESCRIPTION
**Pull request by bjarnef**
… so content templates can be moved to content section.

### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
When moving content templates tree to content section, editors (or users not having access to document types tree) got an error when creating a content template from Content Templates tree node.

```
public class TreeComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.Trees().RemoveTreeController<ContentBlueprintTreeController>();
    }
}
```

```
[Authorize(Policy = AuthorizationPolicies.SectionAccessContent)]
[Tree(Constants.Applications.Content, Constants.Trees.ContentBlueprints, SortOrder = 10)] //TreeGroup = Constants.Trees.Groups.Settings
[PluginController(Constants.Web.Mvc.BackOfficeTreeArea)]
[CoreTree]
public class ContentTemplatesController : ContentBlueprintTreeController
{
    public ContentTemplatesController(
        ILocalizedTextService localizedTextService,
        UmbracoApiControllerTypeCollection umbracoApiControllerTypeCollection,
        IMenuItemCollectionFactory menuItemCollectionFactory,
        IContentService contentService,
        IContentTypeService contentTypeService,
        IEntityService entityService,
        IEventAggregator eventAggregator)
        : base(localizedTextService, umbracoApiControllerTypeCollection, menuItemCollectionFactory,
            contentService, contentTypeService, entityService, eventAggregator)
    {
    }

    protected override ActionResult<TreeNode> CreateRootNode(FormCollection queryStrings)
    {
        var root = base.CreateRootNode(queryStrings);

        if (!string.IsNullOrEmpty(root.Value.RoutePath))
        {
            // Update route to content section
            root.Value.RoutePath = root.Value.RoutePath.Replace(Constants.Applications.Settings, Constants.Applications.Content);
        }

        return root;
    }

    protected override ActionResult<MenuItemCollection> GetMenuForNode(string id, FormCollection queryStrings)
    {
        var collection = base.GetMenuForNode(id, queryStrings);

        if (collection.Value.Items.Count > 0)
        {
            foreach (var menuItem in collection.Value.Items)
            {
                if (menuItem.Action is ActionCreateBlueprintFromContent)
                {
                    var route = menuItem.AdditionalData["actionRoute"]?.ToString();

                    if (!string.IsNullOrEmpty(route))
                    {
                        // Update route to content section
                        menuItem.NavigateToRoute(route.Replace($"/{Constants.Applications.Settings}/", $"/{Constants.Applications.Content}/"));
                    }
                }
            }
        }

        return collection;
    }
}
```

In the following I am logged in with editor permissons:

**Before**

https://user-images.githubusercontent.com/2919859/147562497-274e0ea9-aec8-4941-95e7-fd4e5c736838.mp4

**After**

https://user-images.githubusercontent.com/2919859/147562111-a7b8eec6-d9ab-464e-aa31-0530008b86a4.mp4

### CODE REVIEW

**Comment by bjarnef** [comment]
@nul800sebastiaan any chance this can make it to v9.2.0 release? I need this for current project, which is close to release date, but curently editors can't create content templates from create dialog (when moved to content section), although they can create content templates for existing content nodes.

**Comment by bjarnef** [comment]
@bergmania could we update this to allow moving content templates to content sections, while editors also are allowed to use the create action (get a list of document types)?

**Comment by nul800sebastiaan** [comment]
I guess the problem here really is that in some cases you don't want to give editors access to all the blueprints and this way you're opening up at least an endpoint so they can get them anyway if they really wanted. I'd probably say we need a new user permission to be able to handle this scenario.

**Comment by bjarnef** [comment]
Why not? Editors with access to content section can create blueprints through the UI, but can't by default edit these afterwards or delete them. This change only allow editors to get a list of blueprints - not to edit or delete these.

What is the difference from editors can access a list of document types?
https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Web.BackOffice/Controllers/ContentTypeController.cs#L450-L502

With this change developers can move the "Content Templates" tree to Content Section (and remove the one in Settings section). Everything works except the create dialog fails, because editors don't have access to get a list of blueprints :)

**Comment by nul800sebastiaan** [comment]
Yep, upon reflection, that's absolutely fine! 👍

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef! Will be shipped in 9.4!

**Comment by bjarnef** [comment]
@nul800sebastiaan cool 🙌
I do however think the Content Templates need a bit more love in future development when it comes to control over which document types / element types should be allowed to create content templates for. Maybe the block list editor can benefits from content templates for element types. Maybe @leekelleher has some great ideas regarding this? 😎

**Comment by nul800sebastiaan** [comment]
Always good to get new ideas but just know that content templates are not currently on the roadmap. We're talking at HQ about how to store blocks better (not in the near future but very much needed at some point).

**Comment by leekelleher** [comment]
> Maybe @leekelleher has some great ideas regarding this? 😎

Just note here, in case I miss a future discussion. That's pretty much the idea, when the user can pick an element type (for whichever block/nested editor), if there are any Content Templates (for that element type), then let them pick from there too.
Current my Contentment Content Blocks editor and DocTypeGridEditor offer this feature.

**Pull request merged**
