### PR TITLE
Minimal changes to class `nav-tabs` styling

### PR DESCRIPTION
**Pull request by markadrake**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is: https://github.com/umbraco/Umbraco-CMS/issues/3051
- [x] I have added steps to test this contribution in the description below

### Description

Issue was brought up where the navigation tabs (when looking at content for example) sometimes jitter on the page and reveal the bottom border that should not be there. [See the original issue for better detail](https://github.com/umbraco/Umbraco-CMS/issues/3051).

I tried to resolve this with minimal effort / changes in mind. I would like some help with QA. I could not longer reproduce the issue now, but want to make sure my changes haven't caused regression in (1) another breakpoint or (2) another page, dialog, etc where this class is used.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @markadrake 

Thanks for this one too! As ever, we'll take a look over and let you know if we need anything.

Emma, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-pr-team/)

**Comment by nul800sebastiaan** [comment]
Wonderful @markadrake - works as advertised and I can't see it breaking anything else. :-)

Thanks very much!

**Comment by skttl** [comment]
This change makes the action dropdown partially invisible 
image

It does because `.umb-panel-header-content-wrapper` now has an overflow-y value of hidden.

**Comment by markadrake** [comment]
Thanks @skttl - looking at it now.

**Pull request merged**
