### PR TITLE
V8: Update create options for content types

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

The current options for creating a content type is very V7-ish:

image

The way I see it, almost of the use cases for "Document type without a template" has been replaced by "Element type" (a.k.a. blueprints for Nested Content etc.).

On top of that I feel like we should help the users create culture variant content types right from the "create" context menu. This would at least partially mend the issues that have popped up since the release of V8 with people realizing too late that their content type was *not* culture variant after creating a bunch of properties, and thus having to re-configure the culture variance on each property.

With this PR applied, the "create" context menu removes "Document type without a template" and introduces "Document Type - varying by culture" and "Element Type":

create-content-types

Ideally I'd like to get rid of "Document Type Collection" too as it is utterly un-intuitive, but that's another discussion 😄

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hey @kjac ,

👍 , watch this space :-)

Poornima

**Comment by kjac** [comment]
Merge conflicts resolved.

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by kjac** [comment]
Merge conflicts resolved

**Comment by ronaldbarendse** [comment]
@kjac Totally agree that `Document Type without a template` should be replaced with `Element Type`!

To address https://github.com/umbraco/Umbraco-CMS/issues/6410#issuecomment-534451505, we could include the description (`<small><localize key="contentTypeEditor_elementDescription"></localize></small>`) in the create dialog:

Create document type

I thought about putting a dialog after the `Document Type` option to ask whether it's varying by culture and if a template must be created (like `Document Type Collection...`), but that would actually slow down the creation and unnecessarily duplicate code/UI.

So I think just adding an additional item `Document Type varying by culture` (with description) seems like the best option 👍

**Comment by kjac** [comment]
Yeah... Generally I'm sure it would be meaningful to add help texts or item descriptions to all applicable options. 

I would however (and this is probably just me) prefer help texts to all options at the same time instead of just one of them. Perhaps another PR?

**Comment by ronaldbarendse** [comment]
Creating another PR for adding the descriptions seems logical, as the changes of this PR don't require them and I would personally rewrite the current `contentTypeEditor_elementDescription` text... This PR needs to get merged in first though ;-)

**Comment by nul800sebastiaan** [comment]
Thanks @kjac - we've put updating this menu on the ideas list for now to work on in the future, please see our thoughts over here: https://github.com/umbraco/Umbraco-CMS/issues/6410#issuecomment-536640835

I'll close this one for now, thanks for the PR though! 👍

**Comment by ronaldbarendse** [comment]
I'm with all the commenters of https://github.com/umbraco/Umbraco-CMS/issues/6410: this is a very simple change and with my suggestion from above would make it even easier for newcomers to get started, right?

**Pull request closed without merging**
