### PR TITLE
Configure ImageSharp WebP encoder to use Lossy by default

### LINKED ISSUE #16768: v13: PNG images with `?format=webp` are much larger than in v10
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13.4.0

### Bug summary

PNG images converted to WebP with ImageSharp using `?format=webp` in Umbraco v13 are much bigger than the exact same ones in Umbraco v10. This does not seem to happen with JPGs but I have not tested that extensively.

This has been reported on the [ImageSharp GitHub](https://github.com/SixLabors/ImageSharp/discussions/2766) and the conclusion is that ImageSharp v3+ defaults to `Lossless` encoding rather than `Lossy` like in v2.

For a sample 9MB image this means the resulting WebP image is not 400 KB, but 7.5 MB instead.

In order to fix this, Umbraco should configure the WebP encoder to default to Lossy instead of Lossless so it behaves like in Umbraco v10. I made a PR here: #16769.

Default Umbraco 13 (Lossless):
image

Umbraco 13 with Lossy:
image

### Specifics

_No response_

### Steps to reproduce

Use this file:
<details>
<summary>earth.png</summary>

</details>

1. Install a new Umbraco v13 site (`dotnet new umbraco -n webp`).
2. Place `earth.png` in the `wwwroot/media` folder (no need to upload in the media section itself)
4. Navigate to `https://localhost:<PORT>/media/earth.png?format=webp` in your browser
5. Observe the file is ~7.5 MB:
image

The fix is to configure ImageSharp to default to Lossy encoding for WebP:

1. Add to Program.cs -- right above `WebApplication app = builder.Build();`
```csharp
builder.Services.Configure<ImageSharpMiddlewareOptions>(config =>
{
    config.Configuration.ImageFormatsManager.SetEncoder(WebpFormat.Instance, new WebpEncoder
    {
        // Lossy encoding creates files that are 10x smaller than Lossless (the default).
        FileFormat = WebpFileFormatType.Lossy
    });
});
```
2. **!IMPORTANT!** Empty the media cache directory `umbraco/Data/TEMP/MediaCache`
3. Navigate to `https://localhost:<PORT>/media/earth.png?format=webp` in your browser again
4. Observe the file is now only 397 kB:
image

### Expected result / actual result

_No response_

### PR DESCRIPTION
**Pull request by PerplexDaniel**
### Description

Fixes #16768, please see the issue for all details.

### CODE REVIEW

**Comment by georgebid** [comment]
Hi @PerplexDaniel, thank you for your PR. Someone on the core collaborators team will review this soon 😸

**Comment by Matthew-Wise** [comment]
Hi @PerplexDaniel 

Well spotted, Ill have see if a HQ'er can cherry pick this fix out for 14 as well. As that is a MASSIVE difference!!

Thanks again
Matt

**Comment by nul800sebastiaan** [comment]
Unfortunately, this has changed in v13 too long ago and changing it back now would be a breaking change when people might be expecting lossless webp images.

I've cherry picked this as a breaking change to v15 instead in afeed543521fe0a36fde3b7bd251879b907d1b68 and reverted the PR for v13.

**Comment by nul800sebastiaan** [comment]
For now, the workaround for v14 and v13 is to add a composer that does the same thing:

```csharp
public void Compose(IUmbracoBuilder builder)
{
	builder.Services.Configure<ImageSharpMiddlewareOptions>(config =>
	{
		config.Configuration.ImageFormatsManager.SetEncoder(WebpFormat.Instance, new WebpEncoder
		{
			// Lossy encoding creates files that are 10x smaller than Lossless (the default).
			FileFormat = WebpFileFormatType.Lossy
		});
	});
}
```

**Comment by nul800sebastiaan** [comment]
@PerplexDaniel I tend to agree but my colleagues didn't and find it safer to maintain the current state that has been in place for 8 months now. 
Our guidelines for regressions are such that if they get noticed early on we can revert them without impacting too many users, but the current state has been in use now for too long to change the output from lossless to lossy without noting it as a breaking change.

**Comment by arknu** [comment]
> Unfortunately, this has changed in v13 too long ago and changing it back now would be a breaking change when people might be expecting lossless webp images.
> 
> I've cherry picked this as a breaking change to v15 instead in [afeed54](https://github.com/umbraco/Umbraco-CMS/commit/afeed543521fe0a36fde3b7bd251879b907d1b68) and reverted the PR for v13.

@nul800sebastiaan  This is a ridiculous stance. No-one expects lossless images. If they should be a single person out there having that expectation, it is easy enough to change it back. Image size is a major factor in performance and Umbraco normally provides great performance out of the box. Yes, this should have discovered earlier, but this is better fixed late than never. Umbraco should be optimized for the majority use case out of the box - and that is not lossless!
You are essentially forcing every single Umbraco developer to have to include this workaround in every single site. Instead of just doing the right thing and changing the defaults back to what they should be.

**Pull request merged**
