### PR TITLE
Fixes #15136: Search includes fields from other cultures

### LINKED ISSUE #15136: Examine Search - Search matching content from other cultures
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

12.3.0

### Bug summary

When using `IPublishedContentQuery.Search` (or in our case, using `GetCultureAndInvariantFields` from `UmbracoExamineExtensions` in our custom code) and providing a culture, fields inside block list or grid from other cultures are also returned.
This makes it so that it will also search for the query in the other cultures of the content.

In our case this was even causing content that wasn't published in the culture being searched to show up in the results, which made the issue more noticeable.

### Specifics

`GetCultureAndInvariantFields` is using a regex `_cultureIsoCodeFieldNameMatchExpression` which is not accounting for the fact that field names can now have `[]` due to the introduction of https://github.com/umbraco/Umbraco-CMS/pull/13819. 
Since the regex is not a match, the code assumes the field is invariant, which isn't correct.
This might not be the only issue with the regex as I noticed some other fields that also didn't look right.

### Steps to reproduce

1. Do a fresh Umbraco install using the latest version (12.3.0).
2. In Settings > Languages > Add Language (e.g `pt-PT`)
3. Create an Element Document Type (e.g `Block`) with a Textstring property.
4. Create a Document Type with Template (e.g `Page`, which varies per culture and with a Block List property, that varies by culture, referencing the previously created element.
5. Create a content node with different block text for each language.
6. Use the following example template code:
```
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.Page>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@using Umbraco.Cms.Core
@inject IPublishedContentQuery PublishedContentQuery
@{
	Layout = null;
    var results = PublishedContentQuery.Search(Context.Request.Query["q"].ToString(), 0, 10, out _, culture: System.Globalization.CultureInfo.CurrentCulture.Name);
}

<div>
    <ul>
        @foreach (var content in results)
        {
            <li>
                <a href="@content.Content?.Url()">@content.Content?.Name</a>
            </li>
        }
    </ul>
</div>
```
7. Go to the english page url, with a query parameter `?q=` set to the block text content of the other culture (e.g `pt-PT`).
8. Verify that you got results which shouldn't be the case, as there is no english page with the term.

### Expected result / actual result

The block fields of other cultures should be filtered out and not used in the search.

### PR DESCRIPTION
**Pull request by vsilvar**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #15136 

### Description
Regex was updated to support block list fields
Unpublished nodes on the supplied culture are now filtered out

Reproduction steps as described in the issue.

### CODE REVIEW

**Comment by georgebid** [comment]
Morning @vsilvar, thanks for PR! Someone on the team will review this soon 😄

**Comment by lauraneto** [comment]
Hi @vsilvar ,

Thank you for looking into the issue that I reported 🙌
On top of your changes I made an adjustment to the `IPublishedContentQuery` to make the new method addition non breaking.

Unfortunately, while this does fix the issue that I reported, it looks like some integration tests are failing now. After a quick look, I think the tests are not taking into account whether the specific culture is published or not, which was part of your fix, so I think they might need to be adjusted.

Would you be able to take a look? 🙂

**Comment by vsilvar** [comment]
Hi @lauraneto,
I took a look at the integration tests, and as you mentioned, it was an issue with the test data.
I've performed the necessary changes, so the tests should now all pass.

Let me know if anything else is needed 🙂

**Comment by lauraneto** [comment]
Hi @vsilvar ,

Again, thanks for the pull request and for fixing the tests.
This has now been merged 🙂

**Pull request merged**
