### PR TITLE
Replaced angular.toJson with Utilities.toJson [#CanConHackathon]

### PR DESCRIPTION
**Pull request by Matthew-Wise**
https://trello.com/c/UTjBLFQd/17-replace-instances-of-angulartojson

Decouples angulars toJson to es6 this is a direct port of the angular code to ensure we keep its features. I also ported the unit tests to make make testing easier for everyone.

Matt

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Great! And the tests work in the DevOps pipeline as well!

image

**Comment by bjarnef** [comment]
@Matthew-Wise do we have an equivalent to `angular.fromJson()` as well?
It seems this PR replacing `angular.fromJson()` with `JSON.Parse()` is causing issues, when inserting an image grid editor in grid content.
https://github.com/umbraco/Umbraco-CMS/pull/7952

`angular.fromJson()` is also checking if value is a string:
https://github.com/angular/angular.js/blob/master/src/Angular.js#L1335-L1339

It seems to work when replacing the getter here with the following:
https://github.com/umbraco/Umbraco-CMS/blob/a5ff8a429b83fb6263617eb2396aa1e80d1e55a4/src/Umbraco.Web.UI.Client/src/common/services/util.service.js#L208-L210

```
get: function (key) {
      var val = storage["umb_" + key];
      return Utilities.isString(val) ? JSON.parse(val) : val;
}
```

But I think we should have an `Utilities.fromJson` as well and use this here instead.

**Comment by Matthew-Wise** [comment]
Jan had already started doing from :) https://github.com/umbraco/Umbraco-CMS/pull/7952

**Comment by bjarnef** [comment]
@Matthew-Wise the PR https://github.com/umbraco/Umbraco-CMS/pull/7952 just replaced `angular.fromJson()` with `JSON.parse`. It didn't added a equivalent `Utilities.fromJson`.

It might work in some cases when wrapped inside `try/catch`, but here it broke inserting an image grid editor in grid content. https://github.com/umbraco/Umbraco-CMS/pull/7952/files#diff-0f50c5d5842e7132955874d51f872a84L209

**Pull request merged**
