### PR TITLE
V8: Never user cculture when sorting the content tree

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

For some reason, `cculture` is used (if present) when sorting content nodes. That makes no sense, since the content tree is always shown in `mculture`:

image

This PR ensures that we only use `mculture` for sorting content.

#### Testing this PR

1. Edit a culture variant piece of content.
2. Change the editor to another language from the language dropdown (thus adding `cculture` to the querystring).
3. Open the sort dialog for any content node.
4. Verify that the node names in the sort dialog are using the default culture (`mculture`) and not the culture selected in the editor (`cculture`).

### CODE REVIEW

**Comment by Shazwazza** [comment]
Interesting! I wonder why that code was there 🤔 If it was a copy/paste type of thing or if there was some underlying reason for it at some point. I don't think the sort dialog is used in context of a content item ever?

**Comment by kjac** [comment]
Sure it is... Sorting content for navigational purposes is a thing 😀

**Comment by Shazwazza** [comment]
I meant - does the sort dialog ever get launched from within editing a content item? (hence the need for cculture) or is it only via the context menu? I guess you can launch the context menu from the 'Actions' drop down from within the content item. In that case would you want it to use cculture? That might make the code a little awkward since the Actions menu is a sort of hack of the context menu and generally isn't contextual to the content editor at all.

**Comment by kjac** [comment]
Aaah... It's possible for sure. But personally I'd still expect it to show mculture, since that's what the tree shows if it's expanded.

**Comment by kjac** [comment]
Upon further reflection it might be reasonable to use cculture when sort is spawned from the actions menu on a content item, if that content item is using list view. 

I will have a look and see if this is at all detectable, both in the editor and in the sort menu controller. If it isn't I still believe that sort should never use cculture.

**Comment by kjac** [comment]
So. It's possible to implement a solution where children of content with list view are sorted using `cculture` if the "Sort" menu is spawned from the "Actions" button. This makes sense because the items in the list view are shown for `cculcure`:

sort-listview-cculture

Question is though... does it make sense at all to sort children of content with list view? The list view itself has its own sort order, and the whole point of list view is to use it when there are a lot of children; seems like that's a direct conflict with the sorting dialog that obviously needs to list all the children to sort them.

@nielslyngsoe I'm thinking you may have an opinion here... 😄 

If you ask me, the "Sort" action should be removed from the menus for content with list view.

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by ronaldbarendse** [comment]
> If you ask me, the "Sort" action should be removed from the menus for content with list view.

The sort order is very important for the front-end rendering, so it should definitely not be removed on list view/container items!

I agree on making it contextual: when sorting from the tree use `mculture` and from the actions menu use `cculture`. @kjac do you still have the code to implement the solution shown above?

**Comment by nielslyngsoe** [comment]
@kjac we should keep the sorting feature. Thought it might be hard to understand for some editors. And I would not recommend anyone who is building a website to use the BackOffice sorting when using list views, its very confusing for Editors. But instead use a value, like a date, index etc. thought that's not always ideal either.

I think either solutions is okay with me. I would properly go with using `mculture` for both, just for the sake that the dialog comes out of the tree(having wo different languages but up next to each other could seem a bit weird), but doesn't matter so much to me, so if you feel that's more right then go ahead with that solution :-)

**Pull request closed without merging**
