### PR TITLE
U4-5386 Filter out items with type for the Media Picker data type

### PR DESCRIPTION
**Pull request by danlister**
It would be helpful if a developer could specify a list of media types to filter out when an editor is selecting from the media picker. For example, if a developer wants to make sure an image is only selected and not a folder. This pull requests adds a pre value field to the Media Picker and Multi Media Picker so that a developer can add a comma separated list of Media Types to filter by when displaying the Media Picker.

### CODE REVIEW

**Comment by abryukhov** [comment]
Great media picker feature! :+1: 
Hope it will be merged into upcoming 7.3!

**Comment by adhub** [comment]
Dear HQ, it will be great if you can include this PR in 7.2.8. We really miss this priceless feature.

**Comment by Shazwazza** [comment]
Sorry 7.2.8 is going to be a very quick turn around and only to fix 2 issues.

**Comment by adhub** [comment]
For @abryukhov and indigents alike: as a palliative we can use the Multinode Treepicker with 'Media' node type specified. The only drawback is that image previews are not visible.

**Comment by bjarnef** [comment]
It would be great to allow only images in media picker.

MediaPicker in dialogService already has an option for that, but it is not used for Media Picker.

Here is how I added it to UrlPicker: https://github.com/bjarnef/uWestFest/blob/master/urlpicker/app/scripts/controllers/url.picker.controller.js#L37

**Comment by abryukhov** [comment]
Originally submitted pull request does it more flexible way than "only images allowed" - it adds to the media picker config one text field for comma-separated list of allowed media type aliases...

**Comment by bjarnef** [comment]
@abryukhov I know you can use the input the filter items by writing png, jpg, gif, etc.
but you have to ensure you considered all file extension which is of a file type "image", .e.g you might also want "tiff" images or "bmp" ..

It is a lot easier just to check a "only images" checkbox. and then use the filter to specify further that you only want to allow e.g. "png, jpg, gif".

**Comment by abryukhov** [comment]
@bjarnef - note: this PR is NOT about filtering by file extensions at all. It's about filtering by <i>media type alias</i>, so we will only write e.g. "Image" in this filter field. If I will need only media folder selector, or pdf documents selector, I will write the appropriate media type alias, or even several aliases separated by comma ("Folder, File") :-) The aliases of custom media types created by myself allowed too :-)

**Comment by bjarnef** [comment]
@abryukhov ahh okay, sorry .. I just read the "type" as "extension".

However I think there is missing an option to restrict by extension like the DAMP package for Umbraco 4 and 6 has: https://our.umbraco.org/projects/backoffice-extensions/digibiz-advanced-media-picker

I will open another issue for that (if none isn't already submitted).

**Comment by abryukhov** [comment]
@bjarnef Ok, I also think that it would be ideally to get the media picker in 7 max close to my favorite DAMP in the nearest future :-)
But the real tasks with my actual v7 web sites extremely require at least media alias filtering, it was exactly the reason I've voted for this FR and this PR :-)

**Comment by abryukhov** [comment]
Ah, forgot to give you a link to the very old issue: http://issues.umbraco.org/issue/U4-3713

**Comment by zpqrtbnk** [comment]
This PR has been closed because it was targetting a branch such as `7.x.x`, and these branches are closed when the version is released, and replaced with a simple `release-7.x.x` tag. If the PR is still relevant, we invite you to re-submit the PR, targetting the current version 7 development branch, ie `dev-v7`. Many thanks!

**Pull request closed without merging**
