### PR TITLE
Fixes binding of FormDataCollection for GET requests which fixes the …

### PR DESCRIPTION
**Pull request by Shazwazza**
…compatibility with the latest WebApi 5.2.7 version

### Prerequisites

- [x] I have added steps to test this contribution in the description below

See https://github.com/umbraco/Umbraco-CMS/issues/3796

### CODE REVIEW

**Comment by ronaldbarendse** [comment]
Would adding a `IModelBinderProvider` for `FormDataCollection` that checks whether it's a GET request be a cleaner solution?

Something like this:
```c#
public class GetFormDataCollectionModelBinderProvider : IModelBinderProvider
{
      public IModelBinder GetBinder(Type modelType)
      {
          if (modelType == typeof(FormDataCollection) && HttpContext.Current.Request.HttpMethod == "GET")
          {
              return new HttpQueryStringModelBinder();
          }

          return null;
      }
}
```
This model binder provider should then be added before the default one on application start:
```c#
ModelBinderProviders.BinderProviders.Insert(0, new GetFormDataCollectionModelBinderProvider());
```

**Comment by ronaldbarendse** [comment]
This will probably already be a breaking change, so why not subclass `FormDataCollection` and add the `ModelBinder` attribute to that type, e.g.:

```c#
[ModelBinder(typeof(HttpQueryStringModelBinder))]
public class QueryStringDataCollection : FormDataCollection
{}
```

And replace all `FormDataCollection` types in the controllers with `QueryStringDataCollection`?

**Comment by Shazwazza** [comment]
We can't do the QueryStringDataCollection approach because that will break all trees since FormDataCollection is part of the public api.

`IModelBinderProvider` is an MVC based thing, not a webapi thing. If we want to apply globally than i think we need to either create a custom MediaTypeFormatter (but i'm not sure if that will even work with the GET request), else we'd need to apply a global webapi config and add to the ParameterBindingRules collection (see https://blogs.msdn.microsoft.com/jmstall/2012/05/10/webapi-parameter-binding-under-the-hood/) . But to do that would require that we apply that via a `IControllerConfiguration` attribute so we aren't actually modifying the global webapi rules since we don't want to muck with those whereas IControllerConfiguration allows applying rules to specific controllers, we do this in various places

> Just one thing to consider: the previous HttpQueryStringFilter would get inherited, right? So if you'd inherit from TreeControllerBase, you don't need to add any additional attributes... But does this also work for the ModelBinder attribute on the parameter?

Yup that is the case since all tree controllers are overriding `TreeControllerBase.GetTreeNodes` and `TreeControllerBase.GetMenuForNode` and all trees and menus are working correctly.

Since this is really just a one off change, i'm happy to leave the parameter attributes in place but if you think it is ugly and would be better to use IControllerConfiguration instead, you can give it a go  :)

**Comment by Shazwazza** [comment]
FYI I've cherry picked this into the v8 branch since we've updated there to use the latest MVC - so we should prob just merge this to v7

**Comment by Shazwazza** [comment]
I'm merging this to v7, the same code is already live and working in v8

**Pull request merged**
