### PR TITLE
Removing unnecessary delete confirmation

### PR DESCRIPTION
**Pull request by mjense173**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes [6436](https://github.com/umbraco/Umbraco-CMS/issues/6436)

### Description
When showing delete-node-dialog, it only show warning: "This will delete the node and all its languages", when site has more than one language.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @mjense173 

Thanks for the PR and congrats on your first contribution to this repo! We'll take a look at the work let you know if we need any changes or have any questions and when we merge, you'll get a shiny, new contributor badge :)

Thanks,

Emma, [Pull Request team](https://umbraco.com/blog/the-pr-team-chronicles-september-2019/)

**Comment by nul800sebastiaan** [comment]
This looks good and I've seen it working in real life,

Congrats on your very first pr for Umbraco CMS, well done! 🥇
And that sticker looks nice on you 😁

image

**Comment by emmaburstow** [comment]
Yay! A real life sticker to go with the virtual contrib badge!

**Comment by RunnicFusion** [comment]
Thanks for fixing @mjense173 !

**Comment by nul800sebastiaan** [comment]
Hi there @mjense173,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing 🥇 

We have had another record breaking amount of PR's in both the CMS, Documentation, and other smaller public repositories. You can read all about the numbers in the [Umbraco Hacktoberfest round-up blog post](https://umbraco.com/blog/pr-team-update-november-2019-hacktoberfest-round-up/).

Due to the amazing work you and others in the community have been doing, we've had a bit of a hard time keeping up. 😅 While all of the PRs for Hacktoberfest might not have been merged yet, you still qualify for receiving some Umbraco swag, congratulations! 🎉 

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://docs.google.com/forms/d/e/1FAIpQLSc-K97Zl5k86cVebKWWqieLM4Fm_jCMGVdbQdYnq4IUJ7EvZg/viewform) :point_left: Please follow this link to fill out and submit the form, **before December 19th 2019**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before February, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
