### PR TITLE
 add aria markup to umb-toggle so it behaves like the checkbox it is

### PR DESCRIPTION
**Pull request by zersiax**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes

### CODE REVIEW

**Comment by zersiax** [comment]
Normally, umb-toggles are semantically rendered as buttons. They aren't buttons conceptually though, they are toggles , which is semantically represented by a checkbox. I added aria-role checkbox and a matching aria-checked property that mirrors the ng-checked state. As a bonus, umb-toggles that have a labeldefined now actually speak that label properly using screen readers.

**Comment by zersiax** [comment]
I see the azure build fails, but on first glance it doesn't seem to be because of something I did? Does anyone know more?

**Comment by nul800sebastiaan** [comment]
Hi @zersiax and congrats on your first PR for Umbraco CMS! 

The build was failing that day for everyone due to a configuration update we needed to do, this is not a failure due to your changes, no worries.

Thanks for the update on these toggles, this works well and I can indeed hear the correct label in NVDA. 

Congrats again, I've added a new contributor badge to your profile on Our Umbraco as well! 👍 https://our.umbraco.com/members/zersiax

**Comment by nul800sebastiaan** [comment]
Hi there @zersiax,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing 🥇 

We have had another record breaking amount of PR's in both the CMS, Documentation, and other smaller public repositories. You can read all about the numbers in the [Umbraco Hacktoberfest round-up blog post](https://umbraco.com/blog/pr-team-update-november-2019-hacktoberfest-round-up/).

Due to the amazing work you and others in the community have been doing, we've had a bit of a hard time keeping up. 😅 While all of the PRs for Hacktoberfest might not have been merged yet, you still qualify for receiving some Umbraco swag, congratulations! 🎉 

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://docs.google.com/forms/d/e/1FAIpQLSc-K97Zl5k86cVebKWWqieLM4Fm_jCMGVdbQdYnq4IUJ7EvZg/viewform) :point_left: Please follow this link to fill out and submit the form, **before December 19th 2019**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before February, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
