### PR TITLE
Change angular.mobile for Hammerjs

### PR DESCRIPTION
**Pull request by ssougnez**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description

As shown in [the screen cast attached to the issue tracker](http://issues.umbraco.org/_persistent/umb.webm?file=64-7073&v=0&c=true), it is currently impossible to select text into some input of the back office (the login screen, the search box in the tree, etc...). After investigation, it turns out that it is due to "angular.mobile" that messes up with some gesture.

As this is an annoying issue and as AngularJs announced that "angular.mobile" is not supported for AngularJs 1.7, this PR proposes a replacement of this library by HammerJs (following the recommendation of AngularJs team).

This PR simply remove references to "angular.mobile" and replaces them by "HammerJs". Some CSS classes have also been updated to allow "HammerJs" to work as expected.

I tested the behavior of the back office with these changes and compared them with the one of the dev7 branch and it seems that there is no regression.

Moreover, as "angular.mobile" is not supported by "AngularJs" 1.7, this PR can also be beneficial for Umbraco v8.

### CODE REVIEW

**Comment by ssougnez** [comment]
I see there is a conflict but it seems I don't have rights to merge it. However, my changes on that file can be discarded as they were only for testing purpose.

**Comment by emmaburstow** [comment]
Hi @ssougnez 

Thanks for the work! We'll have a look at that conflict but if as you say we can go ahead and ignore that then it should be fine to go ahead with checking the PR. We'll let you know shortly if we need anything from you.

Thanks

Emma, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-pr-team/)

**Comment by madsrasmussen** [comment]
Hi @ssougnez 

Thank you for the PR. This is super cool.

I have done some testing and here is some feedback:
* It is now possible to select the text in the username and password field. 👍 
* Touch and swipe works as expected. 👍 
* If hammer.js has a bower version we should use that instead of adding it manually to the lib folder.
* The login screen is pushed down and there is an empty space in the top of the screen (see screenshot 1).
* The content of the legacy dialogs (sort, rollback, etc) is squeezed in the middle of the dialog (see screenshot 2).
* I can’t select text in the dialogs (ex the header “Sort”).

**Screenshot 1**
screenshot 2018-07-31 14 43 37

**Screenshot 2**
screenshot 2018-07-31 14 44 09

**Comment by ssougnez** [comment]
Okay, I will have a look at it. I expected some issue, it's nice that you found them. I noticed that some CSS property don't work well with hammer (especially absolute positioning).

For the bower version, I did it like that because I think other library has been included this way (I checked the bower file and didn't see angular for example) but I might be wrong so I'll have a look at it ;-)

Btw, did you guys notices that on mobile, if I swipe right on the login screen, it goes away (even in the angular.mobile version) ^^

**Comment by madsrasmussen** [comment]
* Do you know if it is possible to only enable the hammer events if touch is supported?
* The AngularJS version we use in Umbraco v7 is not on bower - too old 😉 
* I didn't notice that you can swipe the login screen away - but I didn't really test it. I have tested it now and you can indeed swipe that away. That doesn't really make a lot of sense 😄

**Comment by ssougnez** [comment]
So, I've been working a bit on that one and... not as easy as it looks... The CSS of Umbraco is very... peculiar, so it's already diffcult to make changes without inducing side-effects.

Moreover, maybe HammerJs is not the best replacement ever of angular-mobile... For example, I've been working on the point stating that you can't select text anymore on the "Sort" panel. Well, this is due to HammerJs (I guess), however, if you have a look at the current Umbraco version, you can neither select the text because of the initial issue this PR is trying to solve :-D

Therefore, I replaced the library but the issue is still there (in a slightly different form, but still)... At least, input can be selected... I'll continue working on this issue and if I can't find something satisfying... Well, I don't know... I'll see :-P

**Comment by ssougnez** [comment]
Well, looks like I managed to update the CSS and configure HammerJs to fix the issues you mentionned:

- The login screen is pushed down and there is an empty space in the top of the screen (see screenshot 1). 👍 
- The content of the legacy dialogs (sort, rollback, etc) is squeezed in the middle of the dialog (see screenshot 2). 👍 
- I can’t select text in the dialogs (ex the header “Sort”). 👍 

For the bower version of the packages, I have to check as my Visual Studio tells me that the version of Bower I use is deprecated. I'll tweak that in the upcoming days and I'll update Umbraco to use the bower version.

The merging issue still refers to a file I didn't really modified and can thus be ignored.

_Btw, an unrelated question. Is there a way to discussion directly with a team member to ask question about the development of Umbraco (and I really mean the development **of** Umbraco, not **with** Umbraco). For example, I'm wondering if it is planed to migrate the legacy pages to something more aligned with UI/technology of the current product, and I have no idea where to look or who to ask. The issue tracker is filled with issues and the search isn't really performing..._

**Comment by ssougnez** [comment]
Ok, I finally could install angular-hammer through bower :-D

I think this PR is ready to be tested and merged (hopefully :p)

**Comment by nul800sebastiaan** [comment]
Hi there @ssougnez ! After a few discussions about this at HQ, we currently feel this is a little bit risky to implement in v7. We do realize that we need to move towards Hammer and definitely want it in a later stage. Would you mind trying again but create this for v8? That way we get more time to experiment and play with it at HQ and see if we run into unforeseen issues.

I'll close this for now and will be happy to see a new PR for v8 if you have some time to try again. Let me know if you need some help or anything getting up and running with v8.

Thanks again! 👍

**Pull request closed without merging**
