### PR TITLE
Fixes #6499 by reloading the content in list view after bulk copy/move

### LINKED ISSUE #6499: v7 Bulk move / copy on listview doesn't update listview styles
Related to #5936 and #5907, same behaviour can be found (list view not updating) after performing bulk copy or move.

Still an issue in v7.15.3

### Bug summary

List view doesn't update after performing a bulk copy or bulk move.

### Specifics

Happens on latest v7 v7.15.3

### Steps to reproduce

Create a doc type A with any textstring property. Create another document type B and configure as list view and allow to be created at root. Allow doc type A as child node type of doc B.

Create node of type doc type B, create multiple nodes of type doc type A.

Select one or more doc type A instances in list view, and click on 'Move' or 'Copy'. For 'Move' to be available, you need to configure the list view settings on doc type B.

### Expected result

After 'Copy' was completed, you should see the new nodes in the list view
After 'Move' was completed, you should no longer see the selected nodes in the list view.

### Actual result

List view hasn"t refreshed, for 'Copy' you can't see the new nodes in list view, for 'Move' you can still see the nodes in the list view

### PR DESCRIPTION
**Pull request by netaddicts**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

Fixes #6499 

### Description

Steps to test this contribution are outlined in #6499 by creating the required doc types and performing the bulk actions copy and move and verifying that list view is refreshed after the bulk operations have been completed

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hello and happy Hacktoberfest!

Thanks for your pr. We'll take a look, follow your testing steps (thanks for those!) and if we need anything we'll let you know.

Emma, [Pull Request team](https://umbraco.com/blog/the-pr-team-chronicles-september-2019/)

**Comment by nul800sebastiaan** [comment]
Thanks @netaddicts ! I am having a bit of trouble replicating the refresh, am I testing it wrong?

**Comment by nul800sebastiaan** [comment]
Moving works perfectly though! 👍

**Comment by netaddicts** [comment]
Hi Seb,

Fix is for v7, but think Heather commented it's also a v8 problem. Didn't
check the v8 tbh

--Dirk

**Comment by nul800sebastiaan** [comment]
😂😂

Okay, I didn't see that so I merged it into v8! Makes sense it won't work there though haha. Cool, I'll retest in v7 😉

**Comment by nul800sebastiaan** [comment]
Just had another look @netaddicts - in v7 I have the opposite problem, copy works great, but after a move there is no refresh. I also set a breakpoint on `$scope.getContent();` and it's not getting hit. Can you have another look please?

**Comment by netaddicts** [comment]
@nul800sebastiaan Ok, will have a look at it, pretty sure it was working on my machine (tm) 🤣 , have been done regression testing on all bulk operations

**Comment by netaddicts** [comment]
Hi @nul800sebastiaan Have been checking multiple times now... it actually works for all of the bulk actions... , not sure how to proceed now, there's nothing else i can do to 'prove' this works

**Comment by nul800sebastiaan** [comment]
Hmmm, let's chalk it down to aggressive browser caching! I can get everything to work this time indeed.. Woohoo! 🎉 Thanks for double-checking!

**Comment by nul800sebastiaan** [comment]
Thanks Dirk for your first ever contribution to Umbraco CMS! 🎉 

And congratulations on your contributor badge on Our Umbraco! https://our.umbraco.com/members/id:1173/ 🏅

**Comment by netaddicts** [comment]
Fantastic news... 👍

**Comment by nul800sebastiaan** [comment]
Hi there @netaddicts,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing 🥇 

We have had another record breaking amount of PR's in both the CMS, Documentation, and other smaller public repositories. You can read all about the numbers in the [Umbraco Hacktoberfest round-up blog post](https://umbraco.com/blog/pr-team-update-november-2019-hacktoberfest-round-up/).

Due to the amazing work you and others in the community have been doing, we've had a bit of a hard time keeping up. 😅 While all of the PRs for Hacktoberfest might not have been merged yet, you still qualify for receiving some Umbraco swag, congratulations! 🎉 

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://docs.google.com/forms/d/e/1FAIpQLSc-K97Zl5k86cVebKWWqieLM4Fm_jCMGVdbQdYnq4IUJ7EvZg/viewform) :point_left: Please follow this link to fill out and submit the form, **before December 19th 2019**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before February, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
