### PR TITLE
V8: Remove the GUID hover title from the name input

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

I may be Mister Sensitive here, but the GUID input title shown when hovering the Name input of content and media types is simply driving me mad. It feels so "system-built-by-engineers" like.

guid-input-title

This PR removes the hover title entirely. I realize it may have been added originally for debugging purposes, but I truly hope it's no longer needed to the point where we need to throw it at the editors like this. 

If need be we could add the GUID elsewhere out of sight - maybe under the Permissions. Something along the lines of what's done with data types.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Ah yes! Nice spot @kjac!

Thanks for the work. We'll shout if we need anything,

Em

**Comment by bjarnef** [comment]
@kjac I agree with this, but I think part of the UI still use it, where the guid not is shown elsewhere as in content nodes, e.g. for templates as far as I know, which is useful information on Umbraco Cloud when there are schema mismatch.
For e.g. Forms I think the guid is available in url and same for members.
It would be great to ensure the id and guid is visible from backoffice UI, which I think it is in most different views.

**Comment by Shazwazza** [comment]
It was added on purpose a long time ago - because guids need to be exposed one way or another. AFAIK it was a quick way to just get it done for the time being. We need to expose the GUID somehow. 

* https://github.com/umbraco/Umbraco-CMS/commit/e559a6d48516fd00abe027e80b06242367b0ea23
* https://github.com/umbraco/Umbraco-CMS/pull/1995

unfortunately i can't find a link to an issue description or anything

**Comment by kjac** [comment]
@Shazwazza @bjarnef any objections to adding it to the Permissions tab then?

**Comment by bjarnef** [comment]
@kjac but templates doesn't have any tabs.

image

Maybe it should have a tab or a panel to show id/guid.

I guess it is e.g. content, media, member types, templates.. which show thie tooltip, while e.g. data types don't. I added some time ago the id/guid or data type view.

image

But why doesn't member type show the guid in tooltip as document types and media types? Doesn't member types have guids now?
image

Relation types show the id/guid similar to data types.

image

It would be great to show the id/guid in a consisten way.

image

I think it would be too cluttered if the id and guid are inserted in header e.g. at right below the alias.

Maybe all these should have an "Info" box with id and guid and optionally some additional details.

**Comment by bjarnef** [comment]
Furthermore do languages have guids? Should these show the id/guid as well?

image

**Comment by kjac** [comment]
Let's take a step back here. Who are we adding all of these IDs for again? 

Personally I don't think IDs belong in the UI at all. And they're certainly not added for the benefit of the editors. Let's take the content "General" info panel as an example:

image

The ID doesn't benefit the editor one bit. It's only clutter to the editor.

For datatypes, doctypes etc. one could argue that the IDs makes a little more sense, as we get more and more developer oriented. But for content, media etc. not so much.

Perhaps the IDs should simply be taken out of the UI. If they're only there to benefit occasional issue handling in deployment scenarios, surely the devs could do a reverse lookup in the DB based on the integer IDs in the URL?

**Comment by bjarnef** [comment]
@kjac when working on e.g. Umbraco Cloud and having multiple enviroments these are useful information, but I agree it is not useful to editors, so maybe these should only be visible to admin users?
Furthermore I guess it is also useful for Umbraco support team.

But then users with access to e.g. settings section should maybe see these details.

For content, media and member maybe the id/guid should only be visible to admin users.

**Comment by kjac** [comment]
I think HQ probably needs to get involved here. Perhaps @nul800sebastiaan can forward this discussion?

Other than that I agree that the IDs in content/media etc. could be hidden for non-admins. I'll have a look at that soon.

**Comment by zpqrtbnk** [comment]
my 2 cents: having the ID and GUID somewhere in the UI, and for everything, is *very* convenient and I am not sure I would want to get rid of them - OTOH having them in a discreet place which would be the same for everything, would be great. I am not a UI guy enough to figure out where, though.

**Comment by Shazwazza** [comment]
Yup so just to step back and answer the question

> Who are we adding all of these IDs for again?

I guess it's for a few different categories of people but least of all editors. Support and developer staff tend to need these Ids. There are places where devs need to know the GUID to perhaps put in config files for various reasons and being able to quickly see them when debugging an issue is very handy.

I'm going to assume part of the reason of making it a `title` attribute was to attempt to hide this from an editor but expose it enough for these categories of people, but that seems to have not worked all that well ;)

**Comment by kjac** [comment]
If we can agree that we're only showing IDs for the benefit of devs/supporters, perhaps we could then do something as simple as adding the IDs to the very bottom of every relevant editor - and only make them visible for the admins. For example:

#### Content

image

#### Document type

image

#### Data type

image

#### Template

image

#### User

image

**Comment by Shazwazza** [comment]
Seems fine by me, but would need approval from @nielslyngsoe and would need confirmation from others that only support & devs need this info

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by nielslyngsoe** [comment]
As far as I know its only used by devs and support, but lets check with @clausjensen 

Otherwise a fine change, I think it as well can make it easier for newcomers to find the IDs. Since currently its mostly people who have taken the Umbraco Cloud Training who knows about this trick.

**Comment by kjac** [comment]
> I can only see it begin useful for non-devs if a dev/supporter asks a editor to provide the ID, but I'm not sure thats a likely scenario...

I sincerely hope this isn't a scenario; if it is, we have failed as a community in providing the correct editing tools to the editors 😄

**Comment by clausjensen** [comment]
The GUID was placed on the title tag, purely for debugging purposes for Cloud support.
It was really just considered a good hidden spot for being able to surface something that most people would never really need, while still allowing it to be easily accessible when support needed this information from a customer.

I believe it is mostly used when encountering duplicates in UDA files, as these entities obviously look very similar between environments, but you need to know the exact GUID of the one you want to keep when sorting this out. It was a common scenario that you would end up looking at the wrong GUID due to having 2-3 databases in Cloud, with random generated names and for non-experienced people using SSMS, it can be a bit unclear which database you are actually querying.

We simply found it easier to surface this information directly in the UI for each environment, making it completely clear what the GUID of the entity you're looking at is, in this specific environment.

I don't mind at all, moving it away from the title tag, and showing it discreetly in the bottom of the view - it's a prettier solution and also makes it possible to actually copy this value out (would be even more awesome to add in "click-copy-to-clipboard" functionality here as well). Looking at the screenshots above, I actually wouldn't mind it being even more discreet if possible (do we have anything smaller/more faded?). It is a tool you would not ever really need to see, unless you are told that it is there.

Regarding who should see this - I suppose if we actually surface this to be shown in the UI, we could hide it for everyone but the administrator group. I don't see any use cases where a non-developer user would need it. The only reason why we didn't bother hiding it before, was that we thought it wouldn't really bother anyone since you had to know it was there to actually find it 😃  (guess we were proven wrong...)

**Comment by nul800sebastiaan** [comment]
Wow, such a tiny change, such a loooong story :-)

I'll accept this one and we'll have to work on a better way to surface this information. I am not a huge fan of having it in the "footer" so maybe @nielslyngsoe can give some advice there?

**Comment by nielslyngsoe** [comment]
> I am not a huge fan of having it in the "footer" so maybe @nielslyngsoe can give some advice there?

I think it looks okay, and I guess we only show this for admins. But we could definitely make it more discreet by using a lighter color and a smaller font size.

**Comment by jmayntzhusen** [comment]
@nul800sebastiaan can we please make sure we don't release anything with this change before it is added back in in a new location? 

This is used daily by Umbraco support, and having a released version where we will just not be able to find the guid other than through the database would be super annoying!

**Comment by kjac** [comment]
@jmayntzhusen the IDs are readily available (and copyable!) in the bottom of the editor window for admins - see [here](https://github.com/umbraco/Umbraco-CMS/pull/4829#issuecomment-469247491)

**Comment by jmayntzhusen** [comment]
@kjac ah sorry completely missed that! And this is the case for doc types and templates as well? 🙂 As they are the only spots where the guid can't be found elsewhere currently.

**Comment by clausjensen** [comment]
@kjac might just be me.. but I don't see them anywhere in the latest v8 branch?

**Comment by kjac** [comment]
@clausjensen you're spot on. I realized last night that the mentioned displays of IDs were solely suggestions on how it *could* look - not actual implementations 🤦‍♂ 

However. We had a talk about it at the hackaton, and better alternatives are being implemented, including ID search in the search tools and the addition of "Info"-apps in some areas. @jmayntzhusen probably has more detail on this.

**Comment by jmayntzhusen** [comment]
Yea we talked through what the need was - and the need for the guid on things is mostly due to Deploy error and the Deploy uda files referencing things by guid, so a quick lookup is nessecary. 

Shannon created a PR that solves that issue in an even better fashion at the meetup where he made schema and nodes' guids searchable through the backoffice search. 
The PR is here: https://github.com/umbraco/Umbraco-CMS/pull/6530

**Comment by clausjensen** [comment]
@jmayntzhusen can you confirm that there is **not** a need to _find the guid_ based on looking at the doctype/datatype/whatever? (as in... the opposite scenario where you need to figure out what the guid of something is - something where it isn't shown on an info tab). Because being able to search for guids, won't really help in that case.

**Comment by bjarnef** [comment]
@clausjensen regarding the PR from Shannon would the search also be able to work with Umbraco Forms (and now that forms on Umbraco Cloud is transferred like content) or extend this if Umbraco Forms is installed?

For each form i Umbraco Forms the guid is visible in the url, but if we need to add the guid somewhere in the UI as well, then maybe also consider if it should be added on Umbraco Forms for consistency.

**Comment by Shazwazza** [comment]
@bjarnef forms can implement ISearchableTree - it is up to forms to implement that not the CMS but should be possible

**Comment by bjarnef** [comment]
@Shazwazza great to know :)
I will submit a feature request on the Umbraco Forms issue tracker 👍

**Comment by jmayntzhusen** [comment]
> @jmayntzhusen can you confirm that there is **not** a need to _find the guid_ based on looking at the doctype/datatype/whatever? (as in... the opposite scenario where you need to figure out what the guid of something is - something where it isn't shown on an info tab). Because being able to search for guids, won't really help in that case.

I must have missed the notification for this question 😬 

Nope you are right, just ran into this on an 8.4 site and it was extremely tedious to find the udi when I only had a document type name, ended up just searching for the name in all the uda files.

**Pull request merged**
