### PR TITLE
V8: Use an overlay style dialog for deleting Nested Content items

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5327

### Description

This PR makes Nested Content use the pretty overlay dialogs when deleting items, instead of the default JS confirm.

When applied it looks like this:

image

There was also a little bug in the handling of "confirm deletes" configuration (same as fixed in https://github.com/umbraco/Umbraco-CMS/pull/5324). I have fixed that as well.

To test this PR, remember to enable "confirm deletes" in the Nested Content configuration:

image

### CODE REVIEW

**Comment by bjarnef** [comment]
@kjac there is also this PR open :) https://github.com/umbraco/Umbraco-CMS/pull/4831

**Comment by kjac** [comment]
@bjarnef oops! Guess @nielslyngsoe didn't check that before creating the issue 😆

**Comment by kjac** [comment]
Merge conflict resolved

**Comment by nul800sebastiaan** [comment]
Thanks @kjac and apologies to @bjarnef ! We think this dialog looks a bit more attractive so we're picking his PR over yours. Forgive us 🙈  🙂

**Comment by ronaldbarendse** [comment]
Do <kbd>Enter</kbd> and <kbd>Esc</kbd> still work with this custom dialog? Having to mouse around just to confirm would be a pain if you quickly want to delete multiple items...

**Comment by nul800sebastiaan** [comment]
They do.

**Pull request merged**
