### PR TITLE
V8: Allow nested content without blueprints

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/4685 

### Description

#4685 calls for the ability to create NC configs without item blueprints to ease the workflow when working with infinite editing. 

This PR implements that change. Note that I have opted to retain the default row in the item blueprints when creating a new NC datatype, but it's possible to delete it. Coupled with #4776 this should give the best experience when setting up things: NC doesn't really make sense to use without blueprints, so a validation error stating that you need at least one blueprint (#4776) + an option to move along by deleting the default row (this PR) is in my opinion the best approach.

It looks like this:

nested-content-without-blueprints

**Note:** Don't attempt to submit the NC config with a blank default row. It breaks stuff (#4776 fixes it).

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hiya Kenn,

Thanks for being clear about the reasoning behind your approach. We'll take a look and let you know if we disagree 😄 

Em

**Comment by nul800sebastiaan** [comment]
Maybe I'm overlooking something.. why would you set up a NC editor without anything? I think the validation in the related issues is great, but I don't see the point of setting up something that will not do anything, just don't add it then, hit "Close" and leave.. what am I missing?

**Comment by kjac** [comment]
#4685 calls for being able to add NC prpperties when setting up content types, even if there are no element types available at the time of creation. I think the general idea is that you don't want to leave the content type setup flow to go create the required element types.

**Comment by nul800sebastiaan** [comment]
Okay, so let's say you don't add anything to the NC editor here because you can't yet. Then you go to the document type that you want to add properties to, add them there and then.. wait, you're breaking the setup flow anyway. 

I'd much rather then see an add/edit button to add a new NC doctype or edit an existing one. Isn't this change just "delaying the inevitable"?

**Comment by nul800sebastiaan** [comment]
Let's get @nielslyngsoe in for some feedback!

**Comment by kjac** [comment]
To be honest I don't feel terribly strongly about this one 😀 I think it makes kinda sense to prevent blocking the various flows whenever possible. To that end this change does help. 

Obviously it's only delaying the inevitable. Sooner or later you have to create the element types and subsequently add them to the NC datatype. I guess what I'm trying to say is why not allow this when it's so simple, if it helps newcomers. Personally I think it's doing things backwards, but I have the luxury (?) of having done these things for a long time.

**Comment by nielslyngsoe** [comment]
Hi @kjac, thanks for this PR!

And @nul800sebastiaan thanks for bringing your concerns to the table. We have to accommodate the ways we have provided. And one scenario is that you can create a DocType and while creating it figures out what properties you want it to consist of. If you in that process goes for Nested Content, you will be stuck cause you cant make Nested Content before you have at least one blueprint.

A good solution to avoid having 'empty nested content configurations' would be as you propose to let the user create a DocType while creating the Nested Content — Which would be great, but could also end up begin confusing. And in early states of a project the Creator might not be ready to do that either.

As you can have a empty checkbox-list or radiobutton-list I would say it makes perfect sense to be able to have a empty Nested Content-list. It does not make sense in a final project, but as your project evolves it makes sense to temporary state that you are going for a Nested-Content property, before you have created the blueprints.

I though think that we should make it clear for Editors when a Nested Content property has no blueprints to pick from. In this way its very clear for every one if they end up in a no-blueprint-situation.

Therefor I have created this issue: https://github.com/umbraco/Umbraco-CMS/issues/5319

Thanks

**Pull request merged**
