### PR TITLE
Update WebhookFiring.cs with fix for serialization issue (#15232)

### PR DESCRIPTION
**Pull request by raymondbrink**
Replaces the posted StringContent with JsonContent so the POST-ed body is no longer a JSON object wrapped in a string (#15232).

### CODE REVIEW

**Comment by warrenbuckley** [comment]
@raymondbrink I was gonna give your PR a go to see if it fixed my issue, but I ma not sure if you have missed some files or a usings statement, but this doesn't build at the moment for me.

**Comment by raymondbrink** [comment]
@warrenbuckley Sorry about that. I missed a modified using statement and var renaming. Fixed it in a new commit.

**Comment by warrenbuckley** [comment]
@raymondbrink I'll give it a go later with the PR I am working on. I am sure @Zeegaan or someone else from the Umbraco HQ will get round to looking at this shortly for a proper review.

**Comment by Zeegaan** [comment]
Seems like it still does the wierd escaping 🤔 
image

**Comment by Zeegaan** [comment]
I found the cause, we were serializing an already serialized object 🙈 
Fix here: https://github.com/umbraco/Umbraco-CMS/pull/15248

**Pull request closed without merging**
