### PR TITLE
U4-10801 - Fix label UI bug and update Notification Settings UI to angular.

### PR DESCRIPTION
**Pull request by MMasey**
http://issues.umbraco.org/issue/U4-10801

Fixes label ui issue on template editor ui.

Updated notification settings ui to use angular instead of web forms.

Before:
image

After:
image

### CODE REVIEW

**Comment by greystate** [comment]
This makes me so happy 😆 🎉 👍 💯

**Comment by bjarnef** [comment]
@MMasey it would be great if you also link to the issue here in the first comment and maybe change the first part of the title to "U4-10801" 👍

**Comment by nul800sebastiaan** [comment]
FYI We also have some HQ work done by Mads in PR #1546 - these two need combining.

**Comment by warrenbuckley** [comment]
@MMasey do you have a copy of this work still available on your machine?
As it seems like you have deleted your copy of the forked Umbraco repository as this PR links only to a patch file.

However the patch file from GitHub is not too happy & is empty
https://github.com/umbraco/Umbraco-CMS/pull/2302.patch

So I can't merge this in to test & verify the changes. All that we can do is to create a new PR with the same changes and I would much prefer you to do it, as this was your work and contribution. Than myself take credit for your community contribution.

Would you be able to create for us a new PR please with the same changes, please?

**Comment by warrenbuckley** [comment]
Thanks @MMasey for re-creating this PR.
I will close this one & pick up the new one you created - https://github.com/umbraco/Umbraco-CMS/pull/2839

**Pull request closed without merging**
