### PR TITLE
Reorganize composition code

### PR DESCRIPTION
**Pull request by zpqrtbnk**
See #4566.

Done:

* Moved everything that defines composing (`Composition`, `IComposer` etc) to `Umbraco.Core.Composing`
* Moved everything that composes Umbraco (our composers and components) to `Umbraco.Core.Compose`
* Moved all composition-related extension methods (for `Composition`, `IFactory`, `IRegister`...) up to `Umbraco.Core` so they are easier to discover

Review: code review. Just moved things around, nothing changed.

### CODE REVIEW

**Comment by bergmania** [comment]
I think it looks good. 

Only thing is, the wording `Composing` and `Compose` are very close, but I can't come up with anything better, to differentiate them more.

Do you think we also have to align the namespaces in `Umbraco.Web`?. Here the Components and Composers, live in different namespace. E.g. `Umbraco.Web.Runtime` and `Umbraco.Web.Logging`

**Comment by zpqrtbnk** [comment]
Agree about the wording but could not find other names either.

As for where components and composers should be... I understand your point. It's either group them in the `Compose` namespace, or let them leave in their own namespaces. Point is... I think it's more "domain driven" to have the logging component in `Web.Logging`. So in fact I'd rather have them all in meaningful places vs. `Compose` but I haven't move those that are there out already.

But that should be a longer term goal.

Making sense?

**Comment by bergmania** [comment]
Make sense. From my point of view, you are welcome to merge.

**Comment by mattbrailsford** [comment]
Could `Composing` and `Compose` not just be merged? Or maybe move the implementations into an `Implements` folder or something (can't remember the name, but I've seen this in the core codebase).

**Comment by zpqrtbnk** [comment]
I'd rather not merge them as... `Composing` is "about composing", ie what ppl would use, and `Compose` is where I put our own composers and components - those that... I don't know where they should go - but could we have another name? or find new homes for them?

**Comment by warrenbuckley** [comment]
If its a naming debate, going to merge this in for now and move on :)

**Comment by bergmania** [comment]
@warrenbuckley, remember it is still breaking if the name(space)s are changed.

**Pull request merged**
