### PR TITLE
Fixes #14102 - NestedPropertyIndexValueFactoryBase ignores compositions

### LINKED ISSUE #14102: 11.3 - content with compositions no longer gets indexed in Examine
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3

### Bug summary

Since 11.3, my content doesn't get indexed anymore. In Examine index, pageContent (this is my own property, see further down) is missing:

image

The document type has a Page Content property of "Headered Contents", which it inherits from another document type. 
image
The headered content is a blocklist:
image
With the following settings:
image

The content model is this:
image

In 11.2 this was indexed (as json I think), but in 11.3 it isn't indexed at all 😕 I tried rebuilding the index but it doesn't help.

### Specifics

_No response_

### Steps to reproduce

See screenshots.

### Expected result / actual result

Index page content again.

### PR DESCRIPTION
**Pull request by Nuklon**
### Description
Fixes #14102

Now:
image

### CODE REVIEW

**Comment by Nuklon** [comment]
Merge also into v11 branch.

**Comment by elit0451** [comment]
_Note: In the review, we need to make sure that this change didn't affect the content items without compositions and that their content is also correctly indexed in the new format!_

**Comment by Nuklon** [comment]
> _Note: In the review, we need to make sure that this change didn't affect the content items without compositions and that their content is also correctly indexed in the new format!_

I have checked before this PR that non-composite properties are included in the CompositionPropertyGroups.

**Comment by Nuklon** [comment]
Is this now good to merge? Would be nice to include this in 11.4.

**Comment by nul800sebastiaan** [comment]
@Nuklon We'll review soon! And yes, target release would be 11.4 👍

**Comment by Zeegaan** [comment]
LGTM, thanks for the fix! 🚀 
Unfortunately, as you mentioned, it didn't make it into the RC, and thus won't be in 11.4.
However, if a v11 patch is needed, it will be in that, otherwise it will be in v12 👍

**Comment by Nuklon** [comment]
It'd be nice if this could still make the 11.4 release, it's such a minimal change and impact is significant as it breaks search completely.

**Pull request merged**
