### PR TITLE
Add password toggle to initial setup page

### PR DESCRIPTION
**Pull request by AndrewBater**
### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/3549

### Description

On the initial setup page the password field for the admin user has been changed to a password field from a text field so that the contents are hidden. A button has been added below it to make the password visible if needed.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hiiii @TheWaxMann 

Thanks for the work and congratulations on your first Pr! I shall have a look at it and let you know if we need anything.

Emma, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-pr-team/)

**Comment by TheWaxMann** [comment]
Hi @emmaburstow,

Thanks for the feedback, I'll go and change that now. What could be causing the cms continuous to fail? I do not have access to see what is going on there.

Andrew

**Comment by emmaburstow** [comment]
Oh pay no attention to that for now. It's happening on several Prs.

Thanks @TheWaxMann!

**Comment by TheWaxMann** [comment]
@emmaburstow 

I have made the requested change to the logic

**Comment by nul800sebastiaan** [comment]
Oh and then you can also remove this `why isn't this masked` comment:
 
image

**Comment by nul800sebastiaan** [comment]
Hey @AndrewBater will you have time to look at the requested changes?

**Comment by nul800sebastiaan** [comment]
Hey there @AndrewBater !

I'm writing today after announcing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Pull request closed without merging**
