### PR TITLE
Fix broken CookieAuthenticationRedirect caused by PR #14036 for non-api requests

### PR DESCRIPTION
**Pull request by mwillebrands**
## Details
With Pull Request #14036 a fix has been introduced which makes sure that instances of the `UmbracoApiController` return a 403 and 401 instead of redirecting to the `AccessDeniedPath` which is configured in the `CookieAuthenticationOptions`. This feature works, however as a side effect, instances of `SurfaceController` are also affected by this, and they don't redirect anymore to the `AccessDeniedPath`, which in my opinion is still wanted functionality.

I've altered the `UmbracoMemberAuthorizeFilter` so it always returns a `ForbidResult` as that's the only result that is explicitly handled by the `CookieAuthenticationHandler` and this makes sure the functionality is the same as before the changes in #14036 except for the `UmbracoApiController`. The default redirect behaviour can still be overridden in the `CookieAuthenticationOptions`.

## Test
You can use the same test cases as in the original Pull Request, however do a test case with an UmbracoAPIController and a SurfaceController.

### Expected Results
**ApiController**
Not logged in should return a 401 status code
Not authorized should return a 403 status code

**Surfacecontroller**
Not logged in should return a redirect to the AccessDeniedPath that is configured in the  `CookieAuthenticationOptions`
Not authorized should return a redirect to the AccessDeniedPath that is configured in the  `CookieAuthenticationOptions`

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi @mwillebrands!

Thanks for your PR to handle the surfacecontroller redirect to Access Denied. 

One of the Core Collaborators team will review this as soon as possible. However, in the meantime I am going to raise it internally just to check the desired behaviour of the redirect for a surface controller. 

Best wishes and someone will be in touch soon,

Emma

**Comment by emmagarland** [comment]
Hi @mwillebrands, 

Just to update this one, I have confirmed with HQ that the behaviour you describe sounds like a suitable fix. 

Someone from the core collaborators team will review it and hopefully merge it as soon as we can!

Emma

**Comment by emmagarland** [comment]
Hi @mwillebrands 

That would be ideal, thank you!

Emma

**Review by elit0451 — APPROVED** [review]
I've tested the changes and they work as intended, thanks for the fix @mwillebrands 🙌

**Comment by nul800sebastiaan** [comment]
Cherry picked for v10/11 in 3f196a9de44bf11b5dd132d90fa239b435a29962

**Pull request merged**
