### PR TITLE
Major revamp with keys added and texts fixed everywhere

### PR DESCRIPTION
**Pull request by esn303**
Thanks to huge help from @merkledo and the others of the Stuttgart Umbraco Meetup, we pulled together all the bits and pieces for a single solid translation file. More unified and clean wording, typo fixes and more. Even if not perfect it will still be better than everthing we had before and something we hopefully can keep current from now on. Incorporates everything from @hoehler and @SoerenDeger to best knowledge.

### CODE REVIEW

**Comment by Shazwazza** [comment]
Awesome!! Because I can't speak German I will have to take your word for it that this is better ;) Before I pull this in though, can you confirm that there are no breaking changes with these changes?

**Comment by perploug** [comment]
There is a problem with the key:

```<key alias="nodeTypes">Dokumententypen</key>``` which we are renaming in 7.4 to follow the actual tree alias so the trees can be translated - in 7.4 its named "documentTypes"  - but seems the translation is the same as in this PR

**Comment by esn303** [comment]
If if get that correctly, you mean that nodeTypes and documentTypes shouldn't be the same word? That's right, but we often used more specific word (i.e. "document" instead of "node") if that's what it was used for 95% of the time.

Or what do you mean?

In 7.4 we would have nodeTypes + documentTypes and could split with probably better(?) wording, right?

**Comment by esn303** [comment]
Hey @perploug any chance you could give me a hint? I'd like to fix this if neccessary and get it done. :)

**Comment by clausjensen** [comment]
Hi @esn303,

Per is out for a while - I think what he means to say is that in 7.4 we have renamed the `nodeTypes` key to `documentTypes` for it to actually match what the tree is called, so the `nodeTypes` key is no longer existing.
The translation for what was in `nodeTypes` before however matches what should now be in `documentTypes`.

It makes sense that you used `nodeTypes` here since the PR is done for 7.3.x. So I would say changing the key to `documentTypes` should be in another PR when this is merged in - this PR looks good to me.

**Comment by esn303** [comment]
Thanks, @clausjensen I will prepare a PR for 7.4 with the corresponding change. Thanks for clarifying.

**Pull request merged**
