### PR TITLE
Base features for OAuth integrations

### PR DESCRIPTION
**Pull request by AndyButland**
## Background

This PR contains the results of a cycle hack investigation into whether it would be useful and/or feasible for Umbraco to offer some basic features around authenticating with third-party services using OAuth.  Answers to both questions are still moot, but I wanted to create a draft PR to make a bit more visible what I've worked on.  If useful, but not deemed a core feature, it could be a package of course too.

The idea comes from working on a few integration projects for Umbraco and noting that many services use OAuth, and many require similar (though often not quite the same) steps for handing that authentication process:

- Create an app or account on the service.
- Store client Ids/secrets
- Make an authentication request to the service.
- Get back an authentication code
- Exchange that for an access token
- Pass that token in requests to the third-party's API.
- Handle the expiry of the access token via refresh tokens.

Potentially Umbraco could provide some base features and functionality that would make this process easier to work with, and ensure good practices are used for things like making requests with HttpClient, storing tokens, handling refresh tokens etc

## How It Would Be Used

The Umbraco website implementer would still need to create and bring their own application to authenticate against.  They would retrieve some details from that and store them in configuration.  They can populate an array of authorized services, with details such as the client Id, secret and scopes required.

```
      "AuthorizedServices": {
        "TokenEncryptionKey": "...",
        "Services": [
          {
            "Alias": "github",
            "DisplayName": "GitHub",
            "ApiHost": "https://api.github.com",
            "IdentityHost": "https://github.com",
            "TokenHost": "https://github.com",
            "RequestIdentityPath": "/login/oauth/authorize",
            "RequestTokenPath": "/login/oauth/access_token",
            "RequestTokenFormat": "Querystring",
            "ClientId": "...",
            "ClientSecret": "...",
            "Scopes": "repo",
            "SampleRequest": "/repos/Umbraco/Umbraco-CMS/contributors"
          },
```

There are other optional settings that can be provided to tweak the functionality necessary for different providers.  For example I've added an `AuthorizationRequestsRequireRedirectUri` flag to handle a requirement HubSpot has but GitHub doesn't.

They would then have access to a back-office tree where each service can be viewed.

Clicking into them would show details of the service and indicate whether it is authorized or not (i.e. has a token been retrieved and stored).  If not, a link is provided to kick-off the authentication process.

The user is redirected to the provider where they login in with their account and authorize the request.  They are returned to the back-office with an indication that the service is now authorized.

In code they would work with a new `IAuthorizedServiceCaller ` component, which as you can see in this example is making a call to the GitHub API:

```
    public class AuthorizedServicesController : UmbracoApiController
    {
        private readonly IAuthorizedServiceCaller _authorizedServiceCaller;

        public AuthorizedServicesController(
            IAuthorizedServiceCaller authorizedServiceCaller)
        {
            _authorizedServiceCaller = authorizedServiceCaller;
        }

        public async Task<IActionResult> GetUmbracoContributorsFromGitHub()
        {
            List<GitHubContributor> response = await _authorizedServiceCaller.SendRequestAsync<List<GitHubContributor>>(
                "github",
                "/repos/Umbraco/Umbraco-CMS/contributors",
                HttpMethod.Get);
            return Content(string.Join(", ", response.Select(x => x.Login)));
        }
    }
```

As you can see you pass to the `SendRequestAsync` a type for the response, the alias of the service, the request path and method.  Optionally you can provide a content body too (i.e. for POST requests).

The implementation of `IAuthorizedServiceCaller` handles retrieving the token, verifying it and refreshing it if it's expired, making the authenticated request, deserialising the response into the type provided and returning it.

## Parts to the PR

`ISecretEncryptor` (implemented by `SecretEncryptor`) is not used yet, but the intention is that it can be used to encrypt tokens that are stored.

`ITokenStorage` (implemented by `InMemoryTokenStorage`) provides a means of storing tokens in the application memory.  This of course needs to be more durable, so it's expected there will be a `DatabaseTokenStorage` using a custom database table created via a migration.

`IAuthorizedServiceCaller` (implemented by `AuthorizedServiceCaller`) is the component that handles the various tasks involved with authenticating against and making requests to services.

For the back-office there's an `AuthorizedServicesTreeController` which creates the tree, and an `AuthorizedServiceController` which provides data for the back-office editor screen.

Finally there's a `AuthorizedServiceResponseController` which handles the post back from the third-party service during the authentication flow, and triggers the retrieval of a token from the authorisation code.

## Current Status

The work so far has been implemented first against the GitHub API, and then the HubSpot one, where differences and need for additional configuration was added.

## Still To Do

- [ ] Test and extend against further providers.
- [ ] Token storage requires a database table with migration (currently using an in-memory store)
- [ ] Tokens in storage should be encrypted (using `ISecretEncryptor`).
- [ ] Tidy up configuration (perhaps could have some nested items to make it easier to work with, as it seems we will only need to extend this as more variation in providers is discovered).
- [ ] Tidy up user interface and add the ability to do a test request from service that has been authorised.  Also add details of the configuration so it can be viewed here.
- [ ] Handle errors and unexpected responses in a more robust way (currently just throwing exceptions).
- [ ] Generate random state for validation between the authentication calls (a facility offered by GitHub).
- [ ] Consider more extension points - e.g. if someone uses a third party provider with some variation that we haven't considered and made available in configuration, perhaps they could implement certain parts (e.g. building requests, parsing responses) by having `AuthorizedServiceCaller` depend on other abstractions that could have alternative implementations registered).

### CODE REVIEW

**Comment by bjarnef** [comment]
I think this could be useful as a separate package, which package developers can benefits from as well.

I also suggested recently some extension on the current OEmbed providers, but was closed https://github.com/umbraco/Umbraco-CMS/pull/12609

@nul800sebastiaan mentioned that some of these like Instagram and Ted have changes, so I wonder if OEmbed should be part of the core in future or as an addon package instead. The main concern is probably how the current OEmbed integration in TinyMCE editor will work. Many projects use OEmbed providers, but not all. It was a bit off topic, but I think it may work well hævning OAuth as a separate package/addon and independent of the CMS.

**Comment by abjerner** [comment]
@AndyButland just for reference, he's my reply to you from Slack the other day:

> I've only looked at the PR, and not the code, but I think it looks like a good start. What I was working on only handled storing app and authentication information, but would let it be up to my other packages to handle the actual authentication.
> 
> > Consider more extension points - e.g. if someone uses a third party provider with some variation that we haven't considered...
> 
> I think this is a necessity. Most services are using OAuth 2.0, but even within these, there are some differences. Some use refresh tokens, while other don't because their tokens doesn't expire. Some are not using refresh tokens because they decided to roll their own :upside_down_face:
> 
> There are also a number of services that still use OAuth 1.0.a. However more services are moving away from OAuth 1.0a in favor of OAuth 2.0 (although I still very much like OAuth 1.0a).
> 
> I'm not sure how OpenID works, but ideally a package or core feature should support all of these three (either directly or indirectly via extension points).

<hr />

Anyways, even if not all if this is added to core, could there be an idea of adding the `ISecretEncryptor` interface / `SecretEncryptor` class to core? Back in .NET Framework, we could use MachineKey, but AFAIK nothing similar exists in .NET Core. Possibly also adopting the `IDataProtectorProvider.CreateProector` concept.

For what I was working on, I've been using `IDataProtectorProvider` and `IDataProtector` interfaces, which seems to work fine, but I read somewhere that the default implementation wasn't intended to be used for long term storage.

So having something natively in Umbraco would mean that us developers could have something that is best practice, and not having to reinvent the wheel again and again.

**Comment by abjerner** [comment]
@AndyButland I see that the `SecretEncryptor` class expects a secret key - eg. from config/AppSettings. Any thoughts on how this should be generated? (I'm aware this might differ if the logic ends up in core or in a package).

How does Umbraco generate the GUID for `Umbraco:Global:Id`? I'm assuming this ID will be too obvious to use as a key, but if Umbraco can generate another GUID (or longer value) that can be used as a secret key, I think that would be ideal (again a bit similar to the machine key).

**Comment by AndyButland** [comment]
@abjerner - I've not really looked at this yet as I moved onto the authentication parts, so `SecretEncryptor` is fairly "stub".  But your suggestions sound good.  I've similar seen `IDataProtector` may not be ideal here, and having an key generated sounds a good plan.

**Comment by abjerner** [comment]
It might be worth splitting this up in iterations. Eg. I think the encryption part has broader uses than just what we're doing here, so could be useful to have in core soon'ish (probably too late for 10.2). I would love to have this in the core for some packages I'm working on.

<hr />

If both apps/consumers and access tokens are saved in the database, but potentially used by different property editors, it might also be a good idea to consider a distributed cache layer, so frontend doesn't need to hit the database.

**Comment by AndyButland** [comment]
Will close this as the efforts here have been overtaken by plans for a separate package to provide the functionality that was started on in this PR.  There'll be some announcements about that next week.

**Pull request closed without merging**
