### PR TITLE
Create an extension methods to easily append to CollectionBuilders

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
### Description
Add an extension method to register content apps to make it possible to register content apps in the startup.cs class.
No idea if this is desirable. But to me it seems like a nice addition to easily register content apps. Maybe also an idea to do the same for Components?

Method can be used like:
```csharp
public void ConfigureServices(IServiceCollection services)
{

    services.AddUmbraco(_env, _config)
        .AddBackOffice()
        .AddWebsite()
        .AddComposers()
        .AddContentApp<WordCounterApp>()
        .Build();

}
```

### CODE REVIEW

**Comment by erikjanwestendorp** [comment]
After I made this PR, I thought maybe this could be done in a nicer way. Is the below an option that has a chance?

Rename the file
UmbracoBuilder.ContentApps to UmbracoBuilder.Collections

Add extensions methods for other collections, like: 

```
public static partial class UmbracoBuilderExtensions
{
    public static IUmbracoBuilder AddContentApp<T>(this IUmbracoBuilder builder)
        where T : class, IContentAppFactory
    {
        builder.ContentApps().Append<T>();
        return builder;
    }

    public static IUmbracoBuilder AddDashboard<T>(this IUmbracoBuilder builder)
        where T : class, IDashboard
    {
        builder.Dashboards().Add<T>();
        return builder;
    }

    public static IUmbracoBuilder AddComponents<T>(this IUmbracoBuilder builder)
        where T : class, IComponent
    {
        builder.Components().Append<T>();
        return builder;
    }
}
```

**Comment by mikecp** [comment]
Hi @erikjanwestendorp,

Thanks for this PR! 👍

I think it's a great idea because it not only makes things more ".Net Core like", it also encapsulates the actual implementation, so if for some reason we change it later on, we can just adapt the extensions methods and people that used them won't need to change anything in their code 😁🎉

I don't see any problems in following your second suggestion and having the extensions for the different collections.

Cheers!

**Comment by erikjanwestendorp** [comment]
Hi @mikecp 

Thanks for your review! 😄 I just updated the PR and added the methods below: 

- [x] AddComponent
- [x] AddContentApp
- [x] AddContentFinder
- [x] AddDashboard
- [x] AddMediaUrlProvider
- [x] AddOEmbedProvider
- [x] AddSection
- [x] AddUrlProvider

Would you like to review this?

**Comment by mikecp** [comment]
Hey @erikjanwestendorp ,

I just reviewed it and tested locally, it all works fine 👍 
Just a small remark/question, the method to add an embed provider is named `AddOEmbedProvider`, I guess it's a typo and it should be `AddEmbedProvider` (without the capital O) instead ?😁

If you could make that small change, then it will be ready to be merged!

**Comment by erikjanwestendorp** [comment]
Hi @mikecp 

Thank you for your review again! 👍 

It wasn't actually a typo. I have followed the naming convention of, for example: https://github.com/umbraco/Umbraco-CMS/blob/004d3410e9d2eb9e7cc0962e1fb97bcbb2e8bd34/src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs#L105  I totally agree that it would be nicer to use EmbedProvider instead of OEmbedProvider. 😄  In my last commit I changed it 👍

**Comment by mikecp** [comment]
Hi @erikjanwestendorp ,

Woopsie, I totally missed the fact that the Umbraco collection itself was also called OEmbedProviders 🤦‍♂️

Then I guess it's best to follow the current naming convention the whole way, the O probably stands for "Object" or something.

Would you mind getting back to your previous naming? Sorry about that😬

**Comment by erikjanwestendorp** [comment]
@mikecp Follow the current naming convention sounds good to me 😄! No problem of course! 👍  I renamed it again 😄

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Thanks @erikjanwestendorp 👍😀

**Comment by ronaldbarendse** [comment]
> the O probably stands for "Object" or something

Most (if not all) of these providers use [OEmbed](https://oembed.com/) to retrieve the HTML to embed, so it's actually using an implementation specific name. But then the actual implementation base class `EmbedProviderBase` uses a generic name again 😞

I would recommend changing the following (in a new PR, which needs to be merged before releasing 9.2.0):
- Rename the extension method to `AddEmbedProvider()` again;
- Obsolete `OEmbedProviders()` and proxy it to a new `EmbedProviders()` method with the existing body: https://github.com/umbraco/Umbraco-CMS/blob/004d3410e9d2eb9e7cc0962e1fb97bcbb2e8bd34/src/Umbraco.Core/DependencyInjection/UmbracoBuilder.Collections.cs#L268-L269
- Optionally do something similar (but in 'reverse') for `EmbedProviderBase`:
  - Rename the existing class to `OEmbedProviderBase`;
  - Add an obsoleted class `public abstract class EmbedProviderBase : OEmbedProviderBase`;
  - Add `// TODO (V10):` comments to all implementations to change their base class to `OEmbedProviderBase` in the next major version (changing this will break the inheritance chain, making it a breaking change).

**Comment by mikecp** [comment]
Thanks @ronaldbarendse for the feedback, I think @erikjanwestendorp is gonna have nightmares about this renaming 😂

@erikjanwestendorp feeling like taking this into a new PR 😁?

**Comment by erikjanwestendorp** [comment]
@ronaldbarendse  Thanks for your feedback indeed! 😄. @mikecp nightmares indeed about renaiming this 😂.

@ronaldbarendse @mikecp working on it https://github.com/umbraco/Umbraco-CMS/pull/11703

**Comment by abjerner** [comment]
What was the conclusion for the naming?

I think the **O** stands for **Open** as **OEmbed** is described as an open standard. I think some of the purpose is lost when switching to `EmbedProviders` instead of `OEmbedProviders` as done in #11703.

It's specifically providers for and following the OEmbed standard, so I think it would be wrong to rename the method to just `EmbedProviders`.

**Comment by ronaldbarendse** [comment]
@erikjanwestendorp Awesome work and thanks for getting it done this fast!

@abjerner True, the current `IEmbedProvider` still includes OEmbed specific details... OEmbed isn't the only way to get the embed markup though, as some platforms provide other endpoints, use OpenGraph, etc. Some are now even depreciating their OEmbed endpoints, so I think it makes sense not to tightly couple Umbraco's implementation to this specific standard...

**Pull request merged**
