### PR TITLE
Improve RTE performance when using base64 images

### PR DESCRIPTION
**Pull request by asmailov**
Link to the issue: #7386 

### Description

**Changes:**

1. Changed image tag parsing **Regex** to be more performant
2. Added more **tests** (including one which tests performance)

**How to test:**

1. Add any document with a default rich text editor property
2. Use [this page](https://www.base64-image.de/) or any other to transform an image into a **base64** characters.
3. Insert `` into your document's property source.
4. Ensure that **Saving**, **Publishing**, **Reopening**, **Previewing** works fast.
5. Additionally, add media images and ensure that they are still working correctly.

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Great stuff @asmailov! Thank you very much and wonderful to be adding some unit tests for this, top job! 🌟

I see this is your first PR for Umbraco-CMS as well, congrats on making it an aweseome one. Processing the Html is going down from ~50 seconds to just ~45 milliseconds on my machine, amazing! 👍 

Congrats on your first accepted PR for Umbraco-CMS, you've earned yourself a well deserved Contributor badge on your Our Umbraco profile: https://our.umbraco.com/members/id:279447/ 🎖 🏅

**Comment by asmailov** [comment]
@nul800sebastiaan Glad, I could help 👍

**Comment by nul800sebastiaan** [comment]
Hi again @asmailov - this seems to have broken the ability to insert an image into the Rich Text Editor, so either by using the insert button or by drag & dropping the image into the RTE. Any chance you can try that and see what is going wrong? I would've thought with all those unit tests we'd have some great coverage, but it seems like something is still missing!

**Comment by nul800sebastiaan** [comment]
It's because `umbracoContextAccessor.UmbracoContext` is null so we never get to set up the `_getMediaUrl` Func.

image

**Comment by nul800sebastiaan** [comment]
Fixed by updating the usage to be like the way `HtmlLocalLinkParser` uses the context. 

See commit https://github.com/umbraco/Umbraco-CMS/commit/fbd95f1c8edfc3afc45f3e758b7894a393a40b86

**Comment by asmailov** [comment]
> Fixed by updating the usage to be like the way `HtmlLocalLinkParser` uses the context.
> 
> See commit [fbd95f1](https://github.com/umbraco/Umbraco-CMS/commit/fbd95f1c8edfc3afc45f3e758b7894a393a40b86)

Thank you, @nul800sebastiaan !
I don't often check the GitHub, so I only noticed the notification today 😞 

The mistake was assuming that the **UmbracoContext** will be available in the constructor. Previously we checked the existence of **UmbracoContext** in the public method which is run at a much later time. By moving validation into the constructor it broke the methods.

**Pull request merged**
