### PR TITLE
U4-7017 Grid RTE dosen't load CSS rules properly

### PR DESCRIPTION
**Pull request by madsoulswe**
Used the same as in RTE controller

### CODE REVIEW

**Comment by Shazwazza** [comment]
What version is this for ?

**Comment by madsoulswe** [comment]
Wow, this is wrong.
Only 4c54bab should be in this PR.
Sorry for that!

**Comment by hemraker** [comment]
Hi @madsoulswe 

Is the issue for not respecting CSS rules when using the format dropdown?
If so this has been fixed in a later version.  Have tested with generating html tags and applying css classes from formats and seems to be working as expected?

Can you verify this or correct me if wrong?

All the best
Rune

**Comment by zpqrtbnk** [comment]
This has been fixed already. PR collision! Thanks for your work anyways!

**Pull request closed without merging**
