### PR TITLE
Make methods virtual so they can be redefined in derived classes.

### PR DESCRIPTION
**Pull request by jbreuer**
### Description

When you're using external login providers you sometimes want to override the MemberManager and MemberSignInManager classes with custom implementations. By making the methods of these classes virtual you can inherit from those classes and only override what you need to.

This is an example of the CustomMemberSignInManager where I override the virtual ExternalLoginSignInAsync method:

```
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Umbraco_OpenIdConnect_Example.Core.Extensions;
using Umbraco.Cms.Core.DependencyInjection;
using Umbraco.Cms.Core.Events;
using Umbraco.Cms.Core.Security;
using Umbraco.Cms.Web.Common.Security;

namespace Umbraco_OpenIdConnect_Example.Core.Member;

public class CustomMemberSignInManager : MemberSignInManager
{
    private readonly IMemberManager _memberManager;

    public CustomMemberSignInManager(
        UserManager<MemberIdentityUser> memberManager,
        IHttpContextAccessor contextAccessor,
        IUserClaimsPrincipalFactory<MemberIdentityUser> claimsFactory,
        IOptions<IdentityOptions> optionsAccessor,
        ILogger<SignInManager<MemberIdentityUser>> logger,
        IAuthenticationSchemeProvider schemes,
        IUserConfirmation<MemberIdentityUser> confirmation,
        IMemberExternalLoginProviders memberExternalLoginProviders,
        IEventAggregator eventAggregator)
        : base(memberManager, contextAccessor, claimsFactory, optionsAccessor, logger, schemes, confirmation)
    {
        _memberManager = (IMemberManager)memberManager;
    }

    [Obsolete("Use ctor with all params")]
    public CustomMemberSignInManager(
        UserManager<MemberIdentityUser> memberManager,
        IHttpContextAccessor contextAccessor,
        IUserClaimsPrincipalFactory<MemberIdentityUser> claimsFactory,
        IOptions<IdentityOptions> optionsAccessor,
        ILogger<SignInManager<MemberIdentityUser>> logger,
        IAuthenticationSchemeProvider schemes,
        IUserConfirmation<MemberIdentityUser> confirmation)
        : this(
            memberManager,
            contextAccessor,
            claimsFactory,
            optionsAccessor,
            logger,
            schemes,
            confirmation,
            StaticServiceProvider.Instance.GetRequiredService<IMemberExternalLoginProviders>(),
            StaticServiceProvider.Instance.GetRequiredService<IEventAggregator>())
    {
    }
    
    public override async Task<SignInResult> ExternalLoginSignInAsync(ExternalLoginInfo loginInfo, bool isPersistent, bool bypassTwoFactor = false)
    {
        // In the default implementation, the member is fetched from the database.
        // The default implementation also tries to create the member with the auto link feature if it doesn't exist.
        // The auto link feature has been removed here because the member is from an external login provider.
        // We just build a virtual member from the external login info.
        var claims = loginInfo.Principal.Claims;
        var id = claims.FirstOrDefault(x => x.Type == "sid")?.Value;
        var user = _memberManager.CreateVirtualUser(id, loginInfo.Principal.Claims);
        
        // For now hard code the role. These could be claims from the external login provider.
        user.Claims.Add(new IdentityUserClaim<string>() { ClaimType = ClaimTypes.Role, ClaimValue = "example-group" });

        return await SignInOrTwoFactorAsync(user, isPersistent, loginInfo.LoginProvider, bypassTwoFactor);
    }
}

```

### CODE REVIEW

**Review by mikecp — APPROVED** [review]

**Comment by jbreuer** [comment]
@mikecp Thanks for approving this PR. Can this be merged before the 11.2 RC is out? Thanks.

**Comment by nul800sebastiaan** [comment]
Currently discussing is this would be a breaking change - according to https://learn.microsoft.com/en-us/dotnet/core/compatibility/library-change-rules#members it is:

> :x: DISALLOWED: Adding the [virtual](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/virtual) keyword to a member
While this often is not a breaking change because the C# compiler tends to emit [callvirt](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.emit.opcodes.callvirt) Intermediate Language (IL) instructions to call non-virtual methods (callvirt performs a null check, while a normal call doesn't), this behavior is not invariable for several reasons:
C# is not the only language that .NET targets.
The C# compiler increasingly tries to optimize callvirt to a normal call whenever the target method is non-virtual and is probably not null (such as a method accessed through the [?. null propagation operator](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#null-conditional-operators--and-)).
Making a method virtual means that the consumer code would often end up calling it non-virtually.

But not sure if we need to worry about that.

**Comment by mikecp** [comment]
Thanks for the precision @nul800sebastiaan !
And apologies @jbreuer, I should have mentioned that breaking change questioning point earlier.

**Comment by nul800sebastiaan** [comment]
After some testing, turns out it wouldn't affect us! 👍 

Thanks @jbreuer!🎖️

**Pull request merged**
