### PR TITLE
Updated default branch to dev-8 and removed line that implies you are still on dev-v7 branch

### PR DESCRIPTION
**Pull request by simonech**
### Prerequisites

If there's an existing issue for this PR then this fixes: #4800 

### Description

Removed line on top of Contributing.md (we are on dev-v8, no need to link to it)
Changed default branch to dev-v8
Updated links to zip release and list of tasks

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @simonech!

Thanks for your pull request. We'll take a look and let you know if we need any changes. If not, we'll go ahead and merge and let you know.

Emma

**Comment by simonech** [comment]
> Wonderful stuff. Thanks Simone.
> 
> Em

Thx Emma. Let's wait for the merge then 😄

**Comment by simonech** [comment]
@emmaburstow looks like [a commit on the 2nd of April](https://github.com/umbraco/Umbraco-CMS/commit/6d6121faa6cf289cf777cc54d22cddd901f240c4) fixed more or less the same things I fixed in this PR. Maybe worth that someone checks it again, and if not needed close this PR and also close #4800

**Comment by nul800sebastiaan** [comment]
Thanks for the help @simonech - I see that these files have since been updated appropriately, so I'll close this one! 👍

**Comment by simonech** [comment]
@nul800sebastiaan remember to close the bug I had created too #4800

**Pull request closed without merging**
