### PR TITLE
U4-6231 Refactored Umbraco.Web.WebServices classes

### PR DESCRIPTION
**Pull request by jamescoxhead**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description
Fix for [U4-6231 - Move all Umbraco.Web.WebServices back office controllers to be proper back office controllers](http://issues.umbraco.org/issue/U4-6231).

This has been done by moving back office controllers into Umbraco.Web.Editors (or by moving individual actions into existing controllers where appropriate). UmbracoWebService and UmbracoAuthorizedWebService are used by a few older back office components, the remaining classes don't appear to be used directly by the core.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hiya @jamescoxhead 

Thanks for another PR James! We'll have a look at this shortly and get in touch if we think anything needs altering. 

Emma,  [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by emmaburstow** [comment]
Hi @jamescoxhead 

This really is a hefty bit of work. @Shazwazza can you have a look at this? I can see in the issue tracker that you and James have had a back and forth about making  proper back office controller for the webservices still in use.

Emma

**Comment by Shazwazza** [comment]
Yup it's on my list :)

**Comment by zpqrtbnk** [comment]
Reviewing, merging with `temp8`

**Pull request merged**
