### PR TITLE
#2996 more fixes to force Formatting.None (or correct serializer settings)

### LINKED ISSUE #2996: Umbraco shouldn't store JSON property data as indented
### Bug summary

When saving a content or media item in Umbraco backoffice, the data of properties that store JSON will be saved as indented, which takes up more space in the database. Ideally JSON data shouldn't be indented when saved.

If saved via the content service, it instead depends on the specific implementation whether JSON data is indented or not, making it a bit inconsistent.

### Steps to reproduce

For instance, when saving a page with a grid property, the JSON value saved inthe database is something like:

```json
{
  "name": "1 column layout",
  "sections": [
    {
      "grid": 12,
      "rows": [
        {
          "label": "Section",
          "name": "Section",
          "areas": [
            {
              "grid": 12,
              "hasConfig": false,
              "controls": [
                {
                  "value": "Here is a headline",
                  "editor": {
                    "alias": "headline"
                  },
                  "active": false
                }
              ],
              "active": false
            }
          ],
          "hasConfig": false,
          "id": "e96ffdff-bfd2-8238-0909-33f1717cf7f3",
          "active": false
        },
        {
          "label": "Section",
          "name": "Section",
          "areas": [
            {
              "grid": 12,
              "hasConfig": false,
              "controls": [
                {
                  "value": {
                    "id": 1058,
                    "udi": "umb://media/31e5d65860174179b4052d54eca304b5",
                    "image": "/media/1031/photo-1460901419481-3fc27f0cdae9.jpg",
                    "caption": "Here is a bird"
                  },
                  "editor": {
                    "alias": "media"
                  },
                  "active": true
                }
              ],
              "active": true,
              "hasActiveChild": true
            }
          ],
          "hasConfig": false,
          "id": "1e4639a7-e8e2-00f7-c92a-7c9e27ef1140",
          "hasActiveChild": true,
          "active": true
        }
      ]
    }
  ]
}
```

```json
{"name":"1 column layout","sections":[{"grid":12,"rows":[{"label":"Section","name":"Section","areas":[{"grid":12,"hasConfig":false,"controls":[{"value":"Here is a headline","editor":{"alias":"headline"},"active":false}],"active":false}],"hasConfig":false,"id":"e96ffdff-bfd2-8238-0909-33f1717cf7f3","active":false},{"label":"Section","name":"Section","areas":[{"grid":12,"hasConfig":false,"controls":[{"value":{"id":1058,"udi":"umb://media/31e5d65860174179b4052d54eca304b5","image":"/media/1031/photo-1460901419481-3fc27f0cdae9.jpg","caption":"Here is a bird"},"editor":{"alias":"media"},"active":true}],"active":true,"hasActiveChild":true}],"hasConfig":false,"id":"1e4639a7-e8e2-00f7-c92a-7c9e27ef1140","hasActiveChild":true,"active":true}]}]}
```

The indended JSON string has a size of 1668 bytes, while the non-intended JSON string ha a size of 744 bytes. That is a reduction of roughly **44%**. It may be even more for larger JSON strings.

For a site with thousands of pages, which each may have lots of versions, this will be a lot of extra and unnecessary white space that is being saved to the database.

Another example is when uploading a new image in the media section, the crops of the image is automatically generated and saved (probably directly from C#). The crops are stored something like:

```json
{"src": "/media/1031/photo-1460901419481-3fc27f0cdae9.jpg", "crops": []}
```
Although the result here still has a few spaces here and there, there are no line break or indentation. However if an editor later saves the image through the backoffice, the JSON will instead be stored as indented:

```json
{
  "src": "/media/1031/photo-1460901419481-3fc27f0cdae9.jpg",
  "focalPoint": {
    "left": 0.51166666666666671,
    "top": 0.3575
  }
}
```

### Fix?

I haven't yet found the part of the code where the property values are being serialized to JSON. With a few hints in the right direction, I'd be happy to create a PR for this ;)

### PR DESCRIPTION
**Pull request by benjaminhowarth1**
### Prerequisites

Hopes to fix #2996.

### Description

More edits to force correct serialization settings to use Formatting.None instead of Formatting.Indented.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @benjaminhowarth1 !

Thanks for the work and all the time you put into the discussion around your approach to the solution on the issue tracker.

We'll take a look at the work here and let you know if we need anything else.

Emma

**Comment by emmaburstow** [comment]
Ah, have just spotted that here are some conflicts to resolve and you're the only one able to do that. Could you take a look for us? See above ⬆️

**Comment by nul800sebastiaan** [comment]
The conflicts were because the `v8/dev` branch was the target, instead of `v7/dev`. Updated now.

**Comment by nul800sebastiaan** [comment]
I'm not sure what this PR does @benjaminhowarth1 but it doesn't format all properties as unindented JSON objects. The grid is still stored as indented, for example. Maybe have a look at how Nested Content does it, that one was already stored unindented.

Furthermore UDIs don't get stored as JSON, adding formatting to it doesn't make sense.

I'm going to close this for now, as this doesn't seem the way to go. I wish I had some pointers for you to go find the actual area to make the changes but currently I don't. It would be good if you could test a potential fix next time.

**Comment by nul800sebastiaan** [comment]
FYI it looks like the reason you were trying to fix this was to optimize storage in `datanvarchar`, one of the properties I have is a color picker, which is also still stored with indentation.

**Pull request closed without merging**
