### PR TITLE
Stripped username before login

### PR DESCRIPTION
**Pull request by EmanuelGustafzon**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes here:

https://github.com/umbraco/Umbraco-CMS/issues/16878 

### Description

I simply stripped the username before logging in a user if user accidently add a extra space.

I tried to signin with spaces before and after and it works fine.

### CODE REVIEW

**Comment by EmanuelGustafzon** [comment]
I accidentally a launchsetting.json and then I deleted the file but that caused the azure pipline checks to fail.

**Comment by bjarnef** [comment]
I would move this to client side in Angular handled previously.

Trim user name 

```
username  = username.trim();
```

https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Web.UI.Login/src/components/pages/login.page.element.ts#L76

As developers can implement other external login providers.

**Comment by EmanuelGustafzon** [comment]
That's a a good point @bjarnef thanks for the feedback

**Comment by EmanuelGustafzon** [comment]
@bjarnef Can I please get a brief overview, so the authentication is in the Umbraco.Web.Ui.Login folder but how is this connected to the backoffice actually and why is not the frontend authentication logic in the backoffice repo? I just try to understand how its all connected.

**Comment by emmagarland** [comment]
Hi @EmanuelGustafzon,

Thanks for your PR to fix #16878, to strip usernames before login. I can see you've implemented it as per @elit0451 suggestion in the [issue](https://github.com/umbraco/Umbraco-CMS/issues/16878). It worked for me locally so it has now been successfully merged! 🙌

Also, it looks like this is your first PR to this repository! Nice work! #H5YR 🎉 If you have an account on [our.umbraco.com](https://our.umbraco.com/) please feel free to drop a comment below with your account name. @nul800sebastiaan or one of the team will add you a lovely new `C-Trib` badge to your profile. 🏅

@bjarnef that is an interesting point re the front-end and other login provider implementations - perhaps this should be raised as a new issue (regarding this being in the front-end) for it to be implemented in the client-side too?

Best wishes

Emma

**Comment by EmanuelGustafzon** [comment]
Thank you @emmagarland for merging and yes this is my first contribution so it's exciting. 

I just created an account so would appreciate a badge and my username is Emanuel Gustafzon. 

https://our.umbraco.com/members/EmanuelGustafzon/

**Comment by nul800sebastiaan** [comment]
Congrats on [your contrib badge](https://our.umbraco.com/members/EmanuelGustafzon/) @EmanuelGustafzon and thanks again for the PR! 🏅

**Comment by EmanuelGustafzon** [comment]
Thank you @nul800sebastiaan 🎉

**Pull request merged**
