### PR TITLE
Improve Enum performance

### PR DESCRIPTION
**Pull request by Nuklon**
### Prerequisites

- [X] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description

Drops many unnecessary allocations.

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi @Nuklon!

Thanks for your PR to improve the performance of enums. 

One of our Core Collaborators team will take a look soon!

Best wishes

Emma

**Comment by JasonElkin** [comment]
Hey @Nuklon thanks for taking a look at this. Will review and get back to you as soon as we can.

If you're updating a lot of code to fit the style guide at the same time as making functional changes, it would be super helpful in future if you could split the stylistic and functional changes up into separate commits. It can be hard for reviewers to see the "changes" that really matter, the wood for the trees so to speak.

**Comment by Nuklon** [comment]
> Hey @Nuklon thanks for taking a look at this. Will review and get back to you as soon as we can.
> 
> If you're updating a lot of code to fit the style guide at the same time as making functional changes, it would be super helpful in future if you could split the stylistic and functional changes up into separate commits. It can be hard for reviewers to see the "changes" that really matter, the wood for the trees so to speak.

That's why there are different colors in diffs 😁 But I have undone them.

**Comment by JasonElkin** [comment]
Thanks for the update @Nuklon, it's-a merged!

**Pull request merged**
