### PR TITLE
Only hide icons if hideIcons is set to 'true'

### PR DESCRIPTION
**Pull request by rasmusjp**
### Prerequisites

- [X] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is: #3263
- [X] I have added steps to test this contribution in the description below

### Description

Explicit check if `hideIcons` is `true` and only hide the icons if it is

### CODE REVIEW

**Comment by bjarnef** [comment]
Alternative I think it can be solved in the directive https://github.com/umbraco/Umbraco-CMS/blob/2bb5d0b30eee2f4016b8b48034cb7ec717da66a9/src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbtoggle.directive.js#L69 by checking if the scope property is set and either set the default values of hideIcons to true or false.

**Comment by emmaburstow** [comment]
Hi @rasmusjp and @bjarnef 

This works as is but do we want to take the approach suggested by Bjarne? Which approach is more efficient? 

Emma

**Comment by bjarnef** [comment]
@emmaburstow it would be interessting to try out the different approach inside the directive.

I haven't tested this, but I guess it would be something like this:

```
function link(scope, el, attr, ctrl) {
     
       if(scope.hideIcons === undefined || scope.hideIcons === null) {
              scope.hideIcons = false;
       }

}
```

**Comment by rasmusjp** [comment]
@bjarnef I don't think that'll work since the value that's passed in is a string, and the problem seems to be that if you pass any value it always hides the icons.

I also think it should behave the same way as `showLabels` which already checks for a `true` string value https://github.com/umbraco/Umbraco-CMS/blob/7a474c6fa44adbb4498069a7895f3d38595d0f5f/src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-toggle.html#L3

**Comment by bjarnef** [comment]
@rasmusjp yes, the "showLabels" are handled as a string.
https://github.com/umbraco/Umbraco-CMS/blob/2bb5d0b30eee2f4016b8b48034cb7ec717da66a9/src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbtoggle.directive.js#L56

The same for hideIcons:
https://github.com/umbraco/Umbraco-CMS/blob/2bb5d0b30eee2f4016b8b48034cb7ec717da66a9/src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbtoggle.directive.js#L60

But wouldn't it be more correct to change these to boolean as the checked property?
https://github.com/umbraco/Umbraco-CMS/blob/2bb5d0b30eee2f4016b8b48034cb7ec717da66a9/src/Umbraco.Web.UI.Client/src/common/directives/components/buttons/umbtoggle.directive.js#L54

E.g. as I did with `umb-color-swatches` component.
https://github.com/umbraco/Umbraco-CMS/blob/865cdc09c6bd0e0fef342f09139a82b5120bf3fd/src/Umbraco.Web.UI.Client/src/common/directives/components/umbcolorswatches.directive.js#L31-L33

https://github.com/umbraco/Umbraco-CMS/blob/865cdc09c6bd0e0fef342f09139a82b5120bf3fd/src/Umbraco.Web.UI.Client/src/common/directives/components/umbcolorswatches.directive.js#L31-L33

**Comment by nul800sebastiaan** [comment]
While I agree that handling those values as a string is "wrong", it's also been like that for over a year now, so people using this directive will be relying on `showLabels` and `hideIcons` being a string value.

Correct me if I'm wrong, but I don't see a good way of handling changing that too a boolean now in a backwards compatible way. 🙂

For now, this change works well and I'll merge it. Open to suggestions though to fix this up properly! 👍

**Pull request merged**
