### PR TITLE
Open blueprint editor from tracked references 

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12753

### Description
Currently when a content template (blueprint) has a reference to a media item, the URL (right-click action) and action on anchor click doesn't work.

This PR introduce an infinite editor for blueprints as well, so it works similar to content, media and member.

https://user-images.githubusercontent.com/2919859/182254986-0ac027fd-3e97-4384-bead-660f1ae5133a.mp4

An additional concern is that it is possible to remove the default content templates tree from settings, create a custom tree node inheriting from `ContentBlueprintTreeController` adding this to e.g. content section. Not sure if we can get the alternative section and tree for content templates in core the default tree node has been removed - or maybe we need a setting to override this. There is also a discussion here about if content templates by default should be moved to content section: https://github.com/umbraco/Umbraco-CMS/discussions/11743

I also wonder what should happens when logged in as content editor with no access to settings section?

image

Currently the content editor see the content template in the references, with these changes the user can also open the content template in the infinite mode and seems to be able to save as well.

https://user-images.githubusercontent.com/2919859/182256588-9f067d3a-9ba0-49df-9c24-10694d297f06.mp4

Is this how we want it to work, should the content template reference be locked in this scenario or should we just exclude/filter the reference from the table?
In a specific project we removed the default content templates tree and inserted a custom tree inheriting the default `ContentBlueprintTreeController` and inserted this into content section. In this case we do want content editors to see the references.

A second thing is that the content editor can right-click to open/edit, but in case he/she hasn't access to settings section, it seems to redirect to content section instead.

### CODE REVIEW

**Comment by bjarnef** [comment]
@iOvergaard @nielslyngsoe @nul800sebastiaan I think this it better than what we currently have, but I am not sure how we should handle move of tree to another section? By default it is located in Settings, but we have a project where we removed the default ContentTemplates tree node and registered our own (inheriting the default ContentTemplates tree controller) to insert this into Content section due a demand from the client. By default content editors can create content templates, but not edit or delete these. Maybe another config setting or a server variable exposing section of first ContentTemplates tree controller (either default or one inheriting the default controller).

**Comment by bjarnef** [comment]
@leekelleher maybe you have some feedback on this since you worked a bit with Content Templates / Blueprints in Contentment package.

**Comment by bjarnef** [comment]
@nikolajlauridsen do you know a way to find first registred `ContentBlueprintTreeController` so we can ensure the link works when moved to another section? Or do we need another config option? 😄

**Comment by emmagarland** [comment]
Hi again @bjarnef 🙂 !

Just going through some of the longer running PRs, and noticed this one (it's been a while, so there are now some conflicts sorry!)

Did you need anything else to progress this one? It seems you had some questions?

Thanks,

Emma

**Comment by bjarnef** [comment]
Hi @emmagarland 

Yeah, we need to revolve the merge conflicts 🙂

As mentioned here https://github.com/umbraco/Umbraco-CMS/pull/12764#issuecomment-1399510882 it is possible to move (or removed and register own `ContentBlueprintTreeController`), so regarding this PR which section should we route to, it can be Settings section by default.

Either we need a dynamic way to find (first) registrered `ContentBlueprintTreeController` or another config option to change this to e.g. Content section.

When moved/registered in Content section it also moved blueprints and existing content tree under two root folders in content section. I haven't tested, but I think it may be possible to move the content templates tree under a tree group, so content nodes isn't nested under another level.

**Comment by emmagarland** [comment]
Hi @bjarnef 

Just to let you know, this one hasn't been forgotten - it is being discussed internally with HQ due to the user permissions questions it raises. 

Congratulations on having created your 500th PR, too! Amazing work 🥇 

Best wishes

Emma

**Comment by bjarnef** [comment]
Hi @emmagarland 

Any update on this one?

1. If the user doesn't have access to the settings section (or the section the content templates tree belongs to), maybe the link should just not open the content node - or show node name as text.
2. It is possible to remove the content templates tree and register your own inheriting the core tree controller and register it in e.g. content section. Any way to know about this dynamically or should we just have a settings in appsettings.json to handle this?

**Comment by emmagarland** [comment]
Hi @bjarnef, 

Not yet but thanks for the additional information, I will ask HQ to see if there is an update and you will get a reply soon,

Thanks

Emma

**Comment by nul800sebastiaan** [comment]
Hi @bjarnef, as we talked about a few weeks ago, I'll close this one while we focus on getting Bellissima in good shape.

I'll add the generic comment for people who are reading along with this:

As you may or may not know, we're working on a rewrite of the Umbraco backoffice, codenamed Bellissima (https://umbraco.com/blog/bellissima-preview-releases-of-the-new-backoffice/) and we're trying to make sure that it has feature parity with the current AngularJS-based backoffice.

We're at a point in the development phase where we want to start wrapping up a beta version to ship some time "soon" and we're going to have to implement a feature freeze on the current backoffice so that we don't keep increasing the scope of Bellissima. Unfortunately that means we're going to have to stop accepting PRs like this one that create significant changes to the current backoffice.

As a general rule from now on, we're still happy for features in C# code but anything that gets introduced or refactored in AngularJS probably won't make it. Bugfixes are still great of course!

Thanks for the efforts here and we hope to see you back as a contributor soon! 👍

**Pull request closed without merging**
