### PR TITLE
Added the user ID and GUID to the user details view.

### LINKED ISSUE #3275: Id/guid no longer visible on members
I have noticed that id/guid no longer is visible on members in e.g. v7.12.3, which it previously was. 

In v7.7.13 we had these properties in backoffice.

image

But from v7.8.0 it seems these properties have been removed/hidden.

image

Not sure if this part has been removed/hidden as a part of the GDPR update (v7.9), but I wonder why the id/guid is hidden. The guid/key is visible in the url anyway, and you could potientially guess the id of a member (or just try enter different ids in the url - instead of the guid - if it returns a matching member you know the id of this member).

Besides that some other properties are also hidden/removed: "Created by", "Created" and "Last edited". However it is still allowed to see some other properties like "Last Lockout Date", "Last Login Date" and "Last Password Change Date".

image

### PR DESCRIPTION
**Pull request by ed-parry**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is: https://github.com/umbraco/Umbraco-CMS/issues/3275
- [x] I have added steps to test this contribution in the description below

### Description
Fixes #3275, and also applies to users. Adds the user ID and GUID fields to the user and member properties area. The design is below. 

Users:
image

Members: 
image

There was some discussion on the issue as to why this was originally removed, and whether some of the other fields should be added back too, so let me know if anything else needs adding or this is indeed redundant :)

### CODE REVIEW

**Comment by bjarnef** [comment]
@ed-parry I the lokalisation should be using another are than `template_id`. What are content and media using?

Besides that my issue was also regarding members and not users. But it would be great to add on users as well.

**Comment by ed-parry** [comment]
Ah, of course @bjarnef! Sorry, I'll add it in for members now. It's only `template_id` that's localised, but agree it's not the best one to use. Content just looks to hard-code it, so it's probably worth just adding in `id` to `general`.

**Comment by ed-parry** [comment]
Hi @abjerner, thanks for reviewing!

I've added a new `Id` key to `general`, but stuck with the singular "Id" for now, just because that keeps it consistent with everywhere else that we show the four digit ID and GUID fields together. I've also used your third approach on two lines, again to match other usage. There's probably a bigger question around whether we should pluralize "Id" - it may depend on whether GUID will be the only Id in future versions, or whether V8 keeps both side-by-side?

As for adding in the field to members, should I add that in here or make it a separate PR? It's implemented differently than users so taking me a while to get my head around :)

**Comment by ed-parry** [comment]
Cool, thanks @abjerner - I'll give it a go over the next day or so and then let you know :)

**Comment by ed-parry** [comment]
Hi @abjerner - managed to get this one in for members as well. Created a new property editor for the ID/Guid field as the content/media examples are hard-coded into templates, rather than passing the models through as members does here. Members now looks like the below:

image

Let me know what you think :)

**Comment by nul800sebastiaan** [comment]
Woohoo, this is fantastic! You don't know how much I've missed the ID data being on members (it's really difficult to find the correct member in Our Umbraco since the GUID is displayed in the URL instead of the int id which is what the profile page shows 😅).

Great changes @ed-parry and they work well, great job!

**Comment by bjarnef** [comment]
@nul800sebastiaan do you know why the "Created by", "Created" and "Last edited" is hidden/removed (from v7.8.0) before GDPR release (v7.9.0).
While the "Last login date", "Last lockout date", Last password change date" is available?
See screenshots here: https://github.com/umbraco/Umbraco-CMS/issues/3275

**Pull request merged**
