### PR TITLE
- added class and style rule to make health check fix message look be…

### PR DESCRIPTION
**Pull request by prjseal**
- [x] I have added steps to test this contribution in the description below

I have fixed the styling of the health check fix description. I raised this issue here: #3744 

### Before

before

### After

after

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @prjseal ,

Many thanks for the PR. I shall give this a spin and shall let you know. Watch this space :-)

Poornima

**Comment by prjseal** [comment]
Thanks Poornima

**Comment by bjarnef** [comment]
I think the class `fix-button` is not self explaining. There is already a `pull-left` class to float left. https://github.com/umbraco/Umbraco-CMS/blob/dd6e764588d22ef2b7bce01fd504ece89834f181/src/Umbraco.Web.UI.Client/lib/bootstrap/less/utilities.less#L10-L12

Furthermore how does it look with multiple lines? In that case I think you need to add some padding-left on the container (the grey box) to make the text align. The text might need to be wrapped in a separate container if it not already is.

An option could also be to control the button alignment with a class on the container (the grey box) - maybe by using flexbox.

**Comment by prjseal** [comment]
I've made the changes as suggested and it looks better with pull-left on the button and padding-left on the description.

**Comment by nul800sebastiaan** [comment]
Lovely, thanks very much @prjseal ! 👍

**Pull request merged**
