### PR TITLE
Multiple fixes and improvements for Media Picker and Link Picker popup dialogs used in grid and rte editors.

### PR DESCRIPTION
**Pull request by pynej**
Fix for media picker overlay not reselecting current item.
Fix for image sizing when no MaxImageSize is specified.
Added optional Css Class field to link picker dialog.
Added optional Css Class field to media picker dialog.
Added visible with and height fields to media picker dialog. (Allows setting specific dimensions without having to insert then going into html and edit every image.)
Added shortcut button to clear link title as some people may not want to use it and it is auto-filled in when selecting a content node.
Added a Constrain Properties checkbox.  When selected and width or height are changed the aspect ratio is used to retain the proportions.  When unselected any values can be entered including percentages. (This is working same way that the media picker worked in v6.)

This contains some common image and link attributes as new fields in the dialog popups and is meant as a quality of life improvement so that developers don't have so as often go into the raw HTML and change attributes.

includes fixes and features for http://issues.umbraco.org/issue/U4-5288 and more not listed there.  (Maybe a new linked issue should be created?)

### CODE REVIEW

**Comment by pynej** [comment]
not sure why the merge failed :(

**Comment by PeteDuncanson** [comment]
@nul800sebastiaan can we have some eyes on this one. Lots of goodness here that should be in (or back in) Core.

**Comment by ruant** [comment]
Any plans on adding this?

**Comment by nul800sebastiaan** [comment]
Hey there @pynej!

I'm writing today after anouncing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately this proposed change won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Pull request closed without merging**
