### PR TITLE
Add dropdown prevalue editor

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
Following up on https://github.com/umbraco/Umbraco-CMS/pull/13073 I was a bit surprised that no dropdown prevalue editor is shipped with Umbraco core.

Sometimes this is useful when having many values or in configuration of property editors.

Recently the overlaysize prevalue editor was added https://github.com/umbraco/Umbraco-CMS/blob/v10/contrib/src/Umbraco.Web.UI.Client/src/views/prevalueeditors/overlaysize.html used in configuration of some property editors, but I guess it could have used a general "dropdown" prevalue editor and pass in the prevalues.

I wonder if we want the prevalue editor to be named "dropdown" (which is simple) or "dropdownlist" which is a bit more consistent with the existing "checkboxlist" and "radiobuttonlist" prevalue editors?

Same JSON config as in https://github.com/umbraco/Umbraco-CMS/pull/13073 but just dropdown prevalue editor instead.

```
[
  {
    "label": "Test 1",
    "description": "Test 1",
    "key": "test1",
    "view": "dropdown",
    "prevalues": [
      "value_1",
      "value_2",
      "value_3"
    ]
  },
  {
    "label": "Test 2",
    "description": "Test 2",
    "key": "test2",
    "view": "dropdown",
    "prevalues": [
      {
        "label": "Value one",
        "value": "value_1"
      },
      {
        "label": "Value two",
        "value": "value_2"
      },
      "value_3"
    ]
  },
  {
    "label": "Test 3",
    "description": "Test 3",
    "key": "test3",
    "view": "dropdown",
    "prevalues": [
      {
        "label": "Value one",
        "value": "value_1"
      },
      {
        "value": "value_2"
      },
      {
        "label": "Value three",
        "value": "value_3"
      }
    ]
  }
]
```

https://user-images.githubusercontent.com/2919859/192892725-7b3b1977-11f3-40dd-b540-c02ea191836f.mp4

### CODE REVIEW

**Comment by bjarnef** [comment]
@mikecp I think this would be useful to many package developers 😁😉

**Comment by bjarnef** [comment]
Hi @emmagarland 
Also a custom property editor here using the prevalue editor configuration. A few property editors have a "overlay size" prevalue editor, but this could have solved used a dropdown prevalue editor, which didn't exists at that time.

**Comment by emmagarland** [comment]
Thanks @bjarnef,

For this PR and #13073 I've tried to use the dropdown as prevalues in a custom property editor (changed the names from `dropdown` to `dropdownlist` for consistency locally). 

However, I'm getting null on the `$scope.model.config.prevalues` in the JS for the custom property editor. The `package.manifest` is as follows:

```
{
    "propertyEditors": [
        {
            "alias": "PRPropertyEditor13074",
            "name": "Custom Dropdown Property Editor",
            "editor": {
                "view": "~/App_Plugins/PRPropertyEditor13074/PRPropertyEditor13074.html"
            },
            "prevalues": {
                "fields": [
                    {
                        "label": "Test 1",
                        "description": "Test 1",
                        "key": "test1",
                        "view": "dropdownlist",
                        "prevalues": [
                            "value_1",
                            "value_2",
                            "value_3"
                        ]
                    },
                    {
                        "label": "Test 2",
                        "description": "Test 2",
                        "key": "test2",
                        "view": "dropdownlist",
                        "prevalues": [
                            {
                                "label": "Value one",
                                "value": "value_1"
                            },
                            {
                                "label": "Value two",
                                "value": "value_2"
                            },
                            "value_3"
                        ]
                    },
                    {
                        "label": "Test 3",
                        "description": "Test 3",
                        "key": "test3",
                        "view": "dropdownlist",
                        "prevalues": [
                            {
                                "label": "Value one",
                                "value": "value_1"
                            },
                            {
                                "value": "value_2"
                            },
                            {
                                "label": "Value three",
                                "value": "value_3"
                            }
                        ]
                    }
                ]
            }
        }
    ],
    "css": [
        "~/App_Plugins/PRPropertyEditor13074/PRPropertyEditor13074.css"
    ],
    "javascript": [
        "~/App_Plugins/PRPropertyEditor13074/PRPropertyEditor13074.controller.js"
    ]
}
```

The controller is trying to get the prevalues for the fields from `$scope.model.config.prevalues`, but the `config` object is always empty; let me know if you want me to attach the JS and HTML, too.

I don't suppose you have a working example of the `package.manifest`, JS and HTML that I can test with, please? I've tried for a while on this and have no joy, so I'm wondering if I'm doing something wrong here. I can't find specific documentation on this case, either, but I may be looking in the wrong place.

Thanks

Emma

**Comment by bjarnef** [comment]
Hi @emmagarland 

Yes, the prevalues here isn't nested under a `config` object like in old grid configuration prevalues, but it should be handled here:
https://github.com/umbraco/Umbraco-CMS/pull/13074/files#diff-5b4f5a26658d7116b18ab3e000f4dd5152779535dcffa2fa71a2c3cecf8910a4R11

Could you try adding a `console.log("model", $scope.model)` in the start of the controller?

In checkboxlist in already used this:
https://github.com/umbraco/Umbraco-CMS/pull/13073/files#diff-c4402dd2c13d017f5b73bd428390c771b24f411efa851490431b9068b29dbb79R12

**Comment by bjarnef** [comment]
@emmagarland I merged latest changed from `contrib` branch and used your example of prevalues, but `$scope.model` returns an empty `config` object.

I think the directly access to `prevalues` was a legacy format in property editor or for existing configuration of prevalues in the legacy grid layout editor, where I think the `config` object is preferable.

**Comment by bjarnef** [comment]
This format works:

```
{
    "label": "Strength",
    "description": "How strong do you prefer your coffee?",
    "key": "strength",
    "view": "dropdown",
    "config": {
        "prevalues": [
            "mild",
            "normal",
            "espresso"
        ]
    }
}
```

but strange enough intellisense in VS doesn't suggest `config` property, but "label", "description", "key", "view" and "validation".

**Comment by emmagarland** [comment]
Hi @bjarnef 

I really appreciate this! This is all really helpful. I will get back to reviewing it as soon as I have time 😃 

Thanks

Emma

**Comment by emmagarland** [comment]
Hi @bjarnef 

I've tested PR #13074 and it works well for me regarding the drop-down being available in the prevalue editor for Coffee Editor.

The config value comes through as selected in the property editor when doing `console.log("model", $scope.model)` in the controller:

image

It has now been successfully merged and targeted for version `12.3.0`! 🙌

Also, I've tagged it with `project\bellissima` in case you are also interested in making the same changes for v14. Will say that I have yet to explore property editors in v14. If this isn't possible yet, then the tag will be a reminder for the HQ team to implement the same functionality before the new back-office gets released to ensure feature parity.

Thanks again for your contribution and patience as I worked through this one!

Emma

**Pull request merged**
