### PR TITLE
created an add current domain button to the cultures and hostnames sc…

### PR DESCRIPTION
**Pull request by prjseal**
**PR done at the Umbraco Together Hackathon.**

This PR adds a feature to the Cultures and Hostnames screen

The feature is a button which adds the current domain as a hostname.

addcurrentdomain

If the URL is using a port other than 80 or 443 then it appends the port too, otherwise it just uses the host.

image

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Didn't get to it for v11.0.0 I'm afraid, but this is a great candidate for 11.1.0! 👍

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Thanks @prjseal for this addition, it's a nice shortcut 😁🎉
Cheers!

**Comment by prjseal** [comment]
@mikecp do you think this could be cherry picked for v10?

**Comment by mikecp** [comment]
Hey @prjseal , I guess it could, but it's up to @nul800sebastiaan to decide 😉
Cheers!

**Comment by nul800sebastiaan** [comment]
Cherry picked for 10.4.0 5db507cb9617fc3ec4072e96018da90b434359be

**Comment by prjseal** [comment]
> Cherry picked for 10.4.0 [5db507c](https://github.com/umbraco/Umbraco-CMS/commit/5db507cb9617fc3ec4072e96018da90b434359be)

Woohoo thanks @nul800sebastiaan

**Pull request merged**
