### PR TITLE
Fix docfx generation

### PR DESCRIPTION
**Pull request by nikolajlauridsen**
For some reason the Docfx generation broke when we did the clean up of warnings.

I honestly still have no idea what broke, but it seems like the fix was to re-add an unused using statement for System to SqlSyntaxProviderBase, I have 0 idea why this is nececary, but it seems to be 🤷 

I did also find a couple of other malformed XML docs which I have fixed.

### CODE REVIEW

**Comment by ronaldbarendse** [comment]
@nikolajlauridsen Looks like DocFX doesn't support global usings yet, as I also see the following warnings that indicate it can't find the types in the `System` namespace:
- `Invalid cref value "!:ArgumentNullException" found in triple-slash-comments for`
- `Invalid cref value "!:DateTime" found in triple-slash-comments for`
- And a lot more similar ones...

And as DocFX ignores invalid documentation tags, this will now result in generating incomplete docs 😢

**Comment by ronaldbarendse** [comment]
As for the reason why adding the namespace to `SqlSyntaxProviderBase` fixed the DocFX generation: it has the method `GetFieldNameForUpdate<TDto>(Expression<Func<TDto, object?>> fieldSelector, string? tableAlias = null)` that contains generic types that are in the `System` namespace: `Func` and `object` (alias for `System.Object`).

These types couldn't be resolved and caused it to generate the following invalid [ID string](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/documentation-comments#d42-id-string-format): ```Umbraco.Cms.Infrastructure.Persistence.SqlSyntax.SqlSyntaxProviderBase{`0}.GetFieldNameForUpdate``1(System.Linq.Expressions.Expression{Func{`0,`1}},System.String)```. This caused it to crash with an `ArgumentOutOfRangeException` while trying to replace the zero-indexed backtick `` `1`` when it only had a single `TSyntax` generic type.

With the namespace added, the correct ID string is generated: ```Umbraco.Cms.Infrastructure.Persistence.SqlSyntax.SqlSyntaxProviderBase{`0}.GetFieldNameForUpdate``1(System.Linq.Expressions.Expression{System.Func{{TDto},System.Object}},System.String)```.

**Comment by ronaldbarendse** [comment]
This is related to https://github.com/dotnet/docfx/issues/7737 and can be fixed by pointing DocFX to the assemblies instead of the project files (which will probably also speed up the docs generation).

**Comment by nikolajlauridsen** [comment]
Oh I see, I didn't know about DoxFX not supporting global usings, with that in mind it all makes a lot more sense 😅, thanks demystifying this weird bug, now I can stop scratching my head about it 😆

**Pull request merged**
