### PR TITLE
v8: Fix doctype iconpicker

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/4052

### Description
This fixes an issue with icon picker in e.g. doctypes, so you can change color of an existing picked icon, without having to re-select (submit) the already picked icon.

This I how it already works in the latest v7, tested with v.7.12.4

image

Not that the selected color in `umb-color-swatches` is binded to `vm.color`, so when selecting a different color it doesn't update the `$scope.model.icon`, so for now it does that in submit function.

### CODE REVIEW

**Comment by bjarnef** [comment]
It have update this PR so it actually use the `on-select` callback is previously have added/prepared on `umb-color-swatches` so I can just update `$scope.model.color` here instead.

I had some issues with getting the callback working, where I got an console error: `TypeError: Cannot use 'in' operator to search for 'vm' in color-light-blue` 

image

but I then saw this: https://stackoverflow.com/a/48484100/1693918

After changing `onSelect: '&'` to `onSelect: '<'` it seems to work, but I am not sure why :)

**Comment by bjarnef** [comment]
Okay, it seems `<` is for one-way bindings and `&` is for function binding, so it guess it should use `&` in this case. https://stackoverflow.com/a/37818829/1693918

**Comment by bjarnef** [comment]
@madsrasmussen maybe you have some ideas of how to make the `on-select` work correct?
This https://github.com/umbraco/Umbraco-CMS/pull/4053/commits/63ae4ee3633bc1768fd0e5bf43e42dd86554a4bb was however a workaround to make it work without `on-select`.

**Comment by emmaburstow** [comment]
Hey @nul800sebastiaan - can you have a look at Bjarne's query above?

**Comment by nul800sebastiaan** [comment]
@bjarnef Can you update it to use the workaround instead? That works seems like a fine solution for now.

**Comment by bjarnef** [comment]
@nul800sebastiaan if have updated the code, so it now works with `on-select`. It works similar to how e.g. `on-select` works on `umb-table` component.

https://github.com/umbraco/Umbraco-CMS/blob/dd6e764588d22ef2b7bce01fd504ece89834f181/src/Umbraco.Web.UI.Client/src/common/directives/components/umbtable.directive.js

**Comment by nul800sebastiaan** [comment]
Wonderful, works great! 👍

**Comment by warrenbuckley** [comment]
@nul800sebastiaan & @bjarnef has something been reverted or changed again with this since your PR has been merged in as I can not get this to work anymore. Changing colours does nothing for me.

**Comment by bjarnef** [comment]
@warrenbuckley not sure if this has been merged into `temp8` as it would probably affect this?
https://github.com/umbraco/Umbraco-CMS/pull/4222

**Pull request merged**
