### PR TITLE
U4-9405: Ability to copy Data Types within the backoffice

### PR DESCRIPTION
**Pull request by jamiepollock**
Related Youtrack ticket: http://issues.umbraco.org/issue/U4-9405

### CODE REVIEW

**Comment by jamiepollock** [comment]
Unit tests passing and merged up to dev-v7!

**Comment by dawoe** [comment]
Hi @jamiepollock,

Thanks for this PR and to keep it up to date.

Such a useful addition. I will be testing this somewhere this week.

And apologies for the long silence on this PR.

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by jamiepollock** [comment]
Hi @dawoe, sorry for the late response. Sadly I think I'll need to completely rework this PR to get it working the newer uow system we have in place.

I'll look into creating a new issue and PR when I get the time.

Thanks,
Jamie

**Comment by dawoe** [comment]
Hi @jamiepollock ,

I will close this one then. Looking forward to see the new PR.  Would be a nice productivity addition for developers

Dave

**Pull request closed without merging**
