### PR TITLE
Content type picker in dynamic root pickers

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
This PR adjust the use of  `contentTypePicker` with changes in https://github.com/umbraco/Umbraco-CMS/pull/15080 and a bit cleanup in the controllers.

### CODE REVIEW

**Comment by busrasengul** [comment]
Thank you @bjarnef 
First of all, Happy New Year! 🎉 
So many people on the Core team are still enjoying the holidays atm, we will get back to reviewing the PRs soon!

**Review by nul800sebastiaan — CHANGES_REQUESTED** [review]
Hey @bjarnef - something is very wrong here, when I go to an MNTP and add a query step under Dynamic Root Query, then choose "Specific Node" then I am only allowed to choose from content types, not for actual content. Can you please check this?

**Comment by bjarnef** [comment]
Hi @nul800sebastiaan

Yes, you're right! It should open content, media or member picker as before.
https://github.com/umbraco/Umbraco-CMS/pull/15514/commits/73347822b2abbe5002dbaef54606c801c020934c

It is only shown when content is selected though.
https://github.com/umbraco/Umbraco-CMS/blob/43e373d352793d9fa22575f310cbbf4239cc5edb/src/Umbraco.Web.UI.Client/src/views/prevalueeditors/treesource.html#L24

Just for fun I noticed when allowing this for media and member as well, member picker allow to select root nodes (All members, and other root nodes based on member type, unlike memberpicker property editor (which use treepicker).
https://github.com/umbraco/Umbraco-CMS/blob/43e373d352793d9fa22575f310cbbf4239cc5edb/src/Umbraco.Web.UI.Client/src/views/propertyeditors/memberpicker/memberpicker.controller.js#L16

Content and media pickers allow selecting nodes at root level though.

image

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef this now works great! 👍 

I skimmed through your other comments, but let's keep the scope creep down please. :-)

**Pull request merged**
