### PR TITLE
Fixed strange Email validation behaviour in the backend

### PR DESCRIPTION
**Pull request by renetruelsen**
Fixes: https://github.com/umbraco/Umbraco-CMS/issues/3013

### Changes:

1) Synkronized the email validation patterns to fix irregularities between frontend and backend validation. (had to adapt the regex pattern to work with both angular and .NET)
2) Aligned this regular expression with the default "Email pattern"-validation in the Umbraco backend.
3) Changed size of backend  validation-box for regex-patterns (2 rows instead of 1 row)
4) Bugfixed the valpropertymsg and valserver directives to ignore an empty string, since this is handled by the valrequired-directive.

### Tests

- I tested on the backend validating email-datatypes with and without "required" validation. 
- On string-datatypes with combinations of email-regex-validation and "required"-validation.

...this is my first pull-request, so be gentle. And let me know if I overlooked something in the process. :-)

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @renetruelsen!

Congrats on your first Pr! The description looks to be nice and detailed so thanks for that. We'll look over and let you know if we need anything more from you. We will be kind, though!

Emma

**Comment by renetruelsen** [comment]
Thanks Emma. I feel safe with you on the case ;-)

**Comment by nul800sebastiaan** [comment]
Hi there @renetruelsen,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing :pray:

If you haven't heard already we have had a record breaking amount of PR's in both the CMS and the Documentation repository. You can read all about the numbers in the [Umbraco Hacktoberfest Aftermath blog post](https://umbraco.com/blog/the-2018-hacktoberfest-aftermath/).

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://goo.gl/forms/smjQwEMDM5cUnz6x1) :point_left: Please follow this link to fill out and submit the form, **before November 21st 2018**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before December, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Comment by emmaburstow** [comment]
Hey @renetruelsen 

Question - since you've changed the validation, what will happen for those who have already entered a value into this field? Are we looking at validation that is more restrictive? Or less restrictive? Because if it's the former, we could have some problems...

Em

**Comment by renetruelsen** [comment]
Hey @emmaburstow 

It's a bit more restrictive:
1) Doesn't allow leading special-chars like # or ¤, but emails should always start with a letter or number.
2) Doesn't allow for @localhost or @example - and I just realize that this might pose a problem for some test and dev setups.

The big thing is, though, that previously the backend and frontend email validation would validate different emails, which could cause annoying issues. 
However - I will change the regular expression, so that 2) will no longer be a problem. 1) Should not pose an issue, since it would not be allowed under any circumstances. Later tonight, ok?

**Comment by renetruelsen** [comment]
@emmaburstow - there we go. done.
It's now only slightly more restrictive than previously (example 1. - as described in the previous message).
An error by the original expression is that it doesn't support x@d.co.uk, which is clearly an error. This is now corrected.
The expression can always be improved for even more restrictive correctness, but I decided to keep it with this, which is still readable. :)

**Comment by nul800sebastiaan** [comment]
Hey there @renetruelsen !

I'm writing today after announcing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Pull request closed without merging**
