### PR TITLE
Content/Media/MemberTypeRepository refactoring

### PR DESCRIPTION
**Pull request by zpqrtbnk**
See priv.284 - adresses startup time improvement.

This PR refactors the ContentTypeRepository, MediaTypeRepository and MemberTypeRepository which were using complex SQL queries, and `dynamic` DTOs, to use simpler queries and no `dynamic` + to load all types at once through a new `ContentTypeCommonRepository`.

Review = code review + all tests (should be green) + a site should work normally including editing and using content, media and member types. Especially member types, as they have extra properties (`canEdit`, `viewOnProfile` and `isSensitive`) that should be tested.

### CODE REVIEW

**Comment by bergmania** [comment]
@zpqrtbnk, There are some changes in the new implementation with sensitive data on members.

I added one field as sensitive. On `v8/dev` the entire page is not visible (which is maybe also an error?)
image

On this branch I can see all data, even I'm not part of the sensitive data user group
image

**Comment by zpqrtbnk** [comment]
when the entire page is not visible - I can in fact scroll down and see properties - but the sensitive value is not displayed - happens both with and without PR so I'd say this is an independent UI issue?

**Comment by bergmania** [comment]
I agree.. The original issue is resolved - The one about you could see the sensitive data without permissions

**Comment by bergmania** [comment]
I tested this, and I can't find any errors anymore.

**Comment by Shazwazza** [comment]
@bergmania are you able to merge this now?

**Pull request merged**
