### PR TITLE
V8: Improve notifications save button style and interaction

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

The save button on the notifications dialog is the wrong color, and it's always enabled even if there are no changes to the current notification settings:

image

This PR changes the save button color to green and disables it until one or more changes are made to the notification settings:

notifications-save-button

**Note:** To test this PR you must configure non-default SMTP settings, otherwise the notifications menu item is hidden.

**Also note:** If #5096 is merged in, this PR will have to be updated to reflect the changes in #5096. However, I have written this PR so it should be a simple task.

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @kjac ,

Thanks for this PR. Another great effort at consistency You know the drill  :-)

Poornima

**Comment by nul800sebastiaan** [comment]
@kjac Thanks! I did a merge with the latest v8, which contains #5096 - however, I'm not sure how to propagate the `change` event to the controller now, Can you have a look please?

**Comment by kjac** [comment]
Will do 👍

**Comment by kjac** [comment]
@nul800sebastiaan all done 😄

**Comment by nul800sebastiaan** [comment]
Awesome @kjac - all working beautifully know, thank you!

**Pull request merged**
