### PR TITLE
Grid: Add row only per layout column

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

When you add a row to a grid layout column, the row selectors are activated for every grid layout column. When a row is selected, all the other row selectors disappear again. This seems a bit confusing to me:

grid-add-row-layout-column-before

This PR ensures that only the row selector for the targeted grid layout column is activated:

grid-add-row-layout-column-after

🎄 23/24 🎄

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi hi!

Thanks Kenn. We'll take a look soon.

Emma

**Comment by nul800sebastiaan** [comment]
I've given it a go and while it fixes the one thing, I feel it kinda makes it more confusing by being inconsistent. Feel like we kinda should always show the "+" button or always show all of the options for all columns?

In any case, I've marked this as up for discussion at HQ and will report back!

**Comment by kjac** [comment]
Excellent! 

I'm not much of a grid user so my confusion may be a result of me just not being used to how it works. On the other hand that's usually an indicator that something isn't perfectly intuitive.

**Comment by nul800sebastiaan** [comment]
Hey there @kjac !

I'm writing today after announcing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Pull request closed without merging**
