### PR TITLE
fixing issue in #3292

### PR DESCRIPTION
**Pull request by fresh-caffeine**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, this fixes: https://github.com/umbraco/Umbraco-CMS/issues/3292
- [x] I have added steps to test this contribution in the description below

### Description
I have added a max-width property to fix and IE issue.  IE doesn't respect the flex with property with padding and box-sizing. Its fixed by setting a max-width to 33.33%

### CODE REVIEW

**Comment by abjerner** [comment]
@nul800sebastiaan To help you out, here are some before and after screenshots:

Three columns - before:
image

Three columns - after:
image

Four columns - before:
image

Four columns - after (with the suggested fix):
image

**Comment by fresh-caffeine** [comment]
Thanks @abjerner @nul800sebastiaan  - I've updated the PR accordingly.

**Comment by abjerner** [comment]
@fresh-caffeine Awesome. Your PR is hereby approved 😉

**Comment by nul800sebastiaan** [comment]
Thanks @fresh-caffeine, that looks great!

Congrats on your first PR and on that shiny new contributor badge on Our! https://our.umbraco.com/member/70690 🎉

**Comment by nul800sebastiaan** [comment]
Hi there @fresh-caffeine,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing :pray:

If you haven't heard already we have had a record breaking amount of PR's in both the CMS and the Documentation repository. You can read all about the numbers in the [Umbraco Hacktoberfest Aftermath blog post](https://umbraco.com/blog/the-2018-hacktoberfest-aftermath/).

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://goo.gl/forms/smjQwEMDM5cUnz6x1) :point_left: Please follow this link to fill out and submit the form, **before November 21st 2018**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before December, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
