### PR TITLE
v8: Add keyboard support to slider

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/3957

### Description
This updates noUiSlider used as slider plugin in Umbraco to use version 13.0.0+ which has keyboard support build in.

There are no breaking changes from the current used noUiSlider version only enhancement and bug fixes.

The keyboard support might not be ideal for the slider in image cropper, because the step size in very small (a lot of steps in the range). I have suggested on the noUiSlider issue tracker to be able to set a specific step size when using keyboard in this specific case. https://github.com/leongersen/noUiSlider/issues/992

Furthermore it is only possible the disable keyboard support on noUiSlider (enabled by default), but the `umb-range-slider` doesn't handle this at the moment. I think it is fine for now the always keep it enabled.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hello @bjarnef 

Thanks for another wonderful contribution. We'll take a look and let you know if we need anything. Looks grand.

Em

**Comment by bjarnef** [comment]
Oh, now we might want to update to v14.0.0 to include a few more bug fixes, so the keyboard controls fire the `change` and `slide` events.
https://github.com/leongersen/noUiSlider/releases

**Comment by emmaburstow** [comment]
Ah good thinking @bjarnef!

**Comment by bjarnef** [comment]
It also seems the developer liked my suggestion to control the stepsize, when using keyboard interaction 👍 
https://github.com/leongersen/noUiSlider/issues/992

**Comment by bjarnef** [comment]
The noUiSlider has been updated to latest v14 which only include bug fixes, where the the keyboard controls fire the `change` and `slide` events https://github.com/leongersen/noUiSlider/releases

**Comment by nul800sebastiaan** [comment]
Works beautifully! Thanks very much @bjarnef 👍

**Pull request merged**
