### PR TITLE
6361 v7 bulk publish status

### PR DESCRIPTION
**Pull request by jannikanker**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6361

### Description
The issue linked above contains a perfectly good test case :-) I've simply added the missing audit entry to all items getting published in the Save wit children bulk operation.

To test

1. *Save* a child node (not publish).
2. Publish parent node including unpublished subpages.
3. Verify that both the parent node and all subpages now has an audit trail including your publish event.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @jannikanker,

Thanks for the steps and for linking the Issue. We have plenty to work with here. We'll take a look and let you know if we have any questions.

thanks,

Emma

**Comment by jannikanker** [comment]
Hi @elit0451 - wow, yup, I see that! Excellent catch - I think I know what's going on and will try to fix it later today :-)

**Comment by jannikanker** [comment]
@elit0451 That should do it. I found out that the actual messages in the audit trail in the backoffice are fetched from the lang files, so there's no real need for two different messages.

**Comment by elit0451** [comment]
@jannikanker thanks for investigating further! 
I've re-tested it and now we have just 1 message when we **Publish** the parent and **its subpages**, great!! However, at the moment you can't really distinguish between **Save & Publish** (action invoked through the button) & **Publish with Children** -> the message is `Save and Publish performed by user` in both cases 🤔 

Ideally, it would be amazing if you could add the **Publish with Children** message only for the node that we are publishing with children (_parent node_) and the regular `Publish performed by user` for the subpages.

**Comment by jannikanker** [comment]
@elit0451 Yeah, that's what I was aiming for to start with, but there is some really strange behaviour going on. It's almost as if "Publish with Children" only shows up if there's also a "Save & Publish" message which doesn't really make sense to me. But I'll gladly dig even deeper :-D

**Comment by nul800sebastiaan** [comment]
@jannikanker I haven't looked at the code, but you might need to do an "if id equals id of publishing item then show 'with Children' otherwise show 'publish'".

**Comment by jannikanker** [comment]
@nul800sebastiaan @elit0451 Tried it :-) Then the audit trail still has the same "Save and Publish performed by user" message on all published pages including the parent (e.g. exactly the same result as the latest commit).

If you notice the screenshots from the issue itself, there was never a "Publish with Children" message in the first place - that one seems to appear only if another audit entry has already been added. Magic? I for sure can't figure out why this happens.

Is the distinction between "publish with children" and "save and publish" actually important, though? (he says, ignoring the seeming inexplicable magic trick)

**Comment by jannikanker** [comment]
I guess I could create a new AuditType.PublishWithChildren and maybe even add some localization. I wonder if that'd do it. Maybe that's something to do this weekend :-D

**Comment by jannikanker** [comment]
@elit0451 @nul800sebastiaan I created a new AuditType. I still think this is a lot to do, just to get that specific audit message?

image

**Comment by nul800sebastiaan** [comment]
Hi there @jannikanker,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing 🥇 

We have had another record breaking amount of PR's in both the CMS, Documentation, and other smaller public repositories. You can read all about the numbers in the [Umbraco Hacktoberfest round-up blog post](https://umbraco.com/blog/pr-team-update-november-2019-hacktoberfest-round-up/).

Due to the amazing work you and others in the community have been doing, we've had a bit of a hard time keeping up. 😅 While all of the PRs for Hacktoberfest might not have been merged yet, you still qualify for receiving some Umbraco swag, congratulations! 🎉 

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://docs.google.com/forms/d/e/1FAIpQLSc-K97Zl5k86cVebKWWqieLM4Fm_jCMGVdbQdYnq4IUJ7EvZg/viewform) :point_left: Please follow this link to fill out and submit the form, **before December 19th 2019**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before February, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request closed without merging**
