### PR TITLE
7.5 list view custom field sorting

### PR DESCRIPTION
**Pull request by Shazwazza**

### CODE REVIEW

**Comment by AndyButland** [comment]
Just realised one thing, since I submitted the original PR for this I also provided another one to add a decimal data type, which has now been included around 7.4 time.

But this means data types based on this won't be handled in the sorting code (as the field `dataDecimal` didn't exist at the time).

It will need an addition to `VersionableRepositoryBase.GetSortedSqlForPagedResults()` to add:

```
var sortedDecimal = string.Format(SqlSyntax.ConvertDecimalToOrderableString, "dataInt");

and

var orderBySql = string.Format(@"ORDER BY (
 	                SELECT CASE
 		                WHEN dataInt Is Not Null THEN {0}
						WHEN dataDecimal Is Not Null THEN {1}
 		                WHEN dataDate Is Not Null THEN {2}
 		                ELSE {3}
 	                END 
					...", sortedInt, sortedDecimal, sortedDate, sortedString);
```					

And `ISqlSyntaxProvider` and implementations will need:

```
string ConvertDecimalToOrderableString { get; }
```			

MySQL (I believe) will look like this:

```
public override string ConvertDecimalToOrderableString { get { return "LPAD({0}, 25, '0')"; } }
```

When I tested the PR this worked with integer fields, but I don't have MySQL handy now, so I'm assuming it also does with decimal ones.  If not, you may need a convert:

```
public override string ConvertDecimalToOrderableString { get { return "LPAD(Convert({0}, VARCHAR(20)), 25, '0')"; } }
```

And for SQLServer:

```
public virtual string ConvertDecimalToOrderableString { get { return "RIGHT('0000000000000000000000000' + CAST({0} AS varchar(25)),25)"; } }
```

**Comment by Shazwazza** [comment]
Thanks @AndyButland! I'll get that sorted before we pull this one in

**Comment by Shazwazza** [comment]
@AndyButland I've also updated the MySql with the decimal sorting, it doesn't throw an exception but it doesn't sort either so just having a look at that now.

**Comment by Shazwazza** [comment]
Ah, was just a typo. all fixed :)

**Comment by Shazwazza** [comment]
This is part of dev-7.5 branch now, closing this PR.

**Comment by blevai13** [comment]
Hi everyone,

I have a quick question for you and hopefully somebody can give me an answer on this, although I see int the previous comments were also mentioned this subjtect, but it seems like it still need to adjust. I set a custom field on listview sorting, everything was set, but the only thing is happen my custom field is a numeric int but the sorting functionality on this newly added column will order by alphabetically, but for me is wrong because I have numbers, Does it possible to change(convert) to order by numeric?
Any suggestion would be much appreciated!

Thanks,
Botond

**Comment by AndyButland** [comment]
@blevai13 - what data type is the field you are looking to sort?  If I recall correctly, sorting was supported on numeric columns, but they have to be of a numeric data type.  If you were storing a number as a text string though, that would be stored as text and sorted alphabetically.

**Comment by blevai13** [comment]
HI @AndyButland,
Thank you for your fast reply, yeah I was still digging into the hole(when I wrote here) to see what's going on, because I knew that the sorting on numeric columns is supported from 7.5, but I think the problem might be with the data type is stored in the field. We have used string to store number, but now as I was crawling through this I found out there are rows which has in this custom field also alphanumeric characters, but initially I've supposed there are only numbers, so although I set the datatype to numeric, the conversion couldn't be made I guess because of these values. So I think that's the reason why the default behavior was taken as alphabetical order...
Thanks again, and if I couldn't get through this I will come back to ask you guys. 

Kind regards,

**Pull request closed without merging**
