### PR TITLE
New login background as SVG

### PR DESCRIPTION
**Pull request by nielslyngsoe**
New login background for v.11 as an SVG.

I kept the old JPG, so it's still there if referenced by some(?)

Notice, this must be cherry-picked for 11.0 branch.

### CODE REVIEW

**Comment by ronaldbarendse** [comment]
@bergmania Please note that Umbraco 10 only had a custom **installer** background, which this PR doesn't replace/update and left the login background to a more generic/muted blue with colored shaped...

**Comment by bergmania** [comment]
@ronaldbarendse, the intension is to update the background on each major. Like it changed on minors in the v7 timeperiod.

**Comment by ronaldbarendse** [comment]
> @ronaldbarendse, the intension is to update the background on each major. Like it changed on minors in the v7 timeperiod.

I think that's great, although I can imagine not everyone will like the updated, colourful background (as it can be a bit distracting from the login panel). Since we still ship the previous, more generic/muted background, they can easily set `Umbraco:CMS:Content:LoginBackgroundImage` to `assets/img/login.jpg` and revert back to that one👍🏻

Shouldn't we also change the installer background by changing the following to the new `login.svg`?
https://github.com/umbraco/Umbraco-CMS/blob/b69afe81f3f6fcd37480b3b0295a62af44ede245/src/Umbraco.Web.UI.Client/src/less/installer.less#L34

We can then also remove the `installer.svg` file (since that's hardcoded into the CSS and most likely not referenced anywhere else) and possibly rename `login.svg` to a more generic `background.svg`?

**Comment by bergmania** [comment]
The installer background is fairly new and we do not plan to change that for each version.

And as you say, people can easily change the background image, like before. I always changed the login background to the installer background in v10. Not everyone liked the v8-v10 login background either.

**Pull request merged**
