### PR TITLE
Set focus to Umb-Tags when clicking property label

### LINKED ISSUE #6605: Set focus to Umb-Tags when clicking property label
Clicking the property-label for a umb-tags property should set focus to the "write new tag"-input.

image

### PR DESCRIPTION
**Pull request by stevemegson**
### Prerequisites

If there's an existing issue for this PR then this fixes #6605

### Description
Allows the Tags property editor to pass the property alias into umb-tags-editor, where it can be used as the ID of the text box to match the label's `for` attribute.

### CODE REVIEW

**Comment by bjarnef** [comment]
It would be great to name the property `input-id` (inputId) to make it consistent with setting `id` attribute in e.g. `umb-checkbox` and `umb-radiobutton`.. and also `umb-toggle`.

https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/views/components/tags/umb-tags-editor.html#L24

**Comment by nul800sebastiaan** [comment]
Thanks @stevemegson - I just want to make sure you've seen the fix in https://github.com/umbraco/Umbraco-CMS/pull/6512/files - it deviated a little from this one. 

Specifically, I can never remember what the difference between `htmlId: "<?",` and `htmlId: "@",` would be?

**Comment by bjarnef** [comment]
@nul800sebastiaan `@` means it is an one-way binding, but converted to a string value.  `<` is one-way binding, but the type is preserved, `=` is two-way binding.
`?` means it is optional :)

**Comment by stevemegson** [comment]
Both excellent points, I hadn't seen that PR. I'll update this one to match.

**Comment by nul800sebastiaan** [comment]
Hi @stevemegson - sorry for the delay! Unfortunately, this seems to have generated an unfortunate side-effect, now when you click on the tags label and try to navigate away to a different node, the current node has been marked as dirty and you get a "discard changes" notification. Any chance you can look into that one please?

**Comment by nul800sebastiaan** [comment]
I've just re-tested this and the dirty marker doesn't get set this time, might have been some weird caching issue.. ! Thanks very much @stevemegson! 👍

**Pull request merged**
