### PR TITLE
V13: Use updated form components in the login form

### PR DESCRIPTION
**Pull request by iOvergaard**
### Description

Updates @umbraco-ui/uui to the latest 1.11.0.

Also cherry-picked a fix from V14 where the custom login input component was no longer needed, which was fixed because it errors out. This simplifies the login form.

### How to test

Make sure that the login form works.

### CODE REVIEW

**Review by leekelleher — CHANGES_REQUESTED** [review]
Tested out. Overall it works, but there's a slight regression. 

If you press <kbd>Enter</kbd> on the password field (after entering a password), the form does not submit. I tried this out on the main `v13/dev` branch and I was able to do this.

**Comment by iOvergaard** [comment]
Excellent catch, @leekelleher. Thinking back to V14, we had to fix this explicitly there as well. I have cherry-picked the code we used back then. Would you check again, please?

**Review by leekelleher — APPROVED** [review]
Re-tested, all good with the <kbd>Enter</kbd> submitting! 🙌

**Comment by AndyButland** [comment]
Tracked under https://github.com/umbraco/Umbraco-CMS/issues/18191 @Wolfkhan66

**Pull request merged**
