### PR TITLE
Treat warnings as errors for initial projects

### LINKED ISSUE #15015: Multiple warnings in source code
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

~~12.3.0+ (but applies to any version)~~
v16 (latest)

### Bug summary

There are thousands of warnings within the Umbraco source code. I was hoping to try and start to reduce these as use this issue as a base to work from (unless there already is one?).

My idea is to go through each project and check that there are no warnings, and if there are, remove them. 

This is until perhaps we can set warnings as errors to keep it clean for future? Bigger step/decision! I have started an initial PR for this at #15019.

### Specifics

I recommend ticking off each project if there are no warnings, or if all warnings have since been removed. 
To maintain this, we would also set warnings as errors (something for HQ to consider)

### Steps to reproduce

1. Open IDE of choice
2. Build
3. Observe warnings

### Expected result / actual result

Minimal to no warnings ultimately
```[tasklist]
### Tasks
- [x] Remove warnings from Templates/Umbraco.Templates project
- [ ] Remove warnings from Tests/Umbraco.TestData project
- [x] Remove warnings from Tests/Umbraco.Tests.AcceptanceTest.UmbracoProject project
- [x] Remove warnings from Tests/Umbraco.Tests.AcceptanceTest project
- [ ] Remove warnings from Tests/Umbraco.Tests.Benchmarks project
- [x] Remove warnings from Tests/Umbraco.Tests.Common project
- [ ] Remove warnings from Tests/Umbraco.Tests.Integration project
- [ ] Remove warnings from Tests/Umbraco.Tests.UnitTests project
- [x] Remove warnings from Tools/Umbraco.JsonSchema project
- [x] Remove warnings from Umbraco.Cms project
- [ ] Remove warnings from Umbraco.Cms.Api.Common project
- [ ] Remove warnings from Umbraco.Cms.Api.Delivery project
- [ ] Remove warnings from Umbraco.Cms.Api.Management project
- [x] Remove warnings from Umbraco.Cms.Imaging.ImageSharp project
- [x] Remove warnings from Umbraco.Cms.Imaging.ImageSharp2 project
- [ ] Remove warnings from Umbraco.Cms.Persistence.EFCore project
- [x] Remove warnings from Umbraco.Cms.Persistence.EFCore.SqlServer project
- [x] Remove warnings from Umbraco.Cms.Persistence.EFCore.Sqlite project
- [ ] Remove warnings from Umbraco.Cms.Persistence.SqlServer project
- [ ] Remove warnings from Umbraco.Cms.Persistence.Sqlite project
- [x] Remove warnings from Umbraco.Cms.StaticAssets project
- [ ] Remove warnings from Umbraco.Cms.Targets project
- [ ] Remove warnings from Umbraco.Core project
- [ ] Remove warnings from Umbraco.Examine.Lucene project
- [ ] Remove warnings from Umbraco.Infrastructure project
- [ ] Remove warnings from Umbraco.PublishedCache.HybridCache project
- [ ] Remove warnings from Umbraco.Web.Common project
- [ ] Remove warnings from Umbraco.Web.UI project
- [x] Remove warnings from Umbraco.Web.UI.Client project
- [x] Remove warnings from Umbraco.Web.UI.Login project
- [ ] Remove warnings from Umbraco.Web.Website project
```

### PR DESCRIPTION
**Pull request by emmagarland**
Treat warnings as errors for initial projects:

- templates/Umbraco.Templates
- Umbraco.Cms
- Umbraco.Cms.Api.Common
- Umbraco.Cms.Imaging.ImageSharp
- Umbraco.Cms.Imaging.ImageSharp2
- Umbraco.Cms.Persistence.EFCore.Sqlite
- Umbraco.Cms.Persistence.EFCore.SqlServer
- Umbraco.Cms.StaticAssets
- Umbraco.Cms.Targets

### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #15015  

### Description

There are numerous warnings in the Umbraco source code. I have created an issue #15015 to suggest removing these warnings. 

To ensure that warnings don't creep back in, I propose setting warnings as errors project-by-project (as these warnings are removed). This will help ensure that we no longer end up in a situation with so many warnings, because people/the build server will not be able to compile the code with warnings in it. 

_(Conversations with HQ have approved this initiative)_

### CODE REVIEW

**Comment by mikecp** [comment]
Thanks @emmagarland for initiating this warning cleanup 👍

I like the idea of preventing those warnings to come back, but I'm wondering if treating all as error would not have the side effect that people would just set "ignore" flags on those warnings? On the other hand, I don't see what else we could put in place 😅

**Comment by emmagarland** [comment]
@mikecp I get what you mean, but in my experience of doing this on other projects, that hasn't happened. And if it did, the pull request reviewers would be able to comment about it and hopefully it wouldn't be a problem 👍

**Comment by mikecp** [comment]
Yes it's true, we'll just need to watch out 😁

**Comment by emmagarland** [comment]
@mikecp it will take a while to remove all warnings from some of the projects, anyway. Perhaps, if HQ are happy to try this, we could merge this PR with warnings as errors initially, and see how it goes?

**Comment by mikecp** [comment]
@emmagarland Yes indeed I guess we could give it a try if that would be OK for HQ. And it shouldn't be too complex to come back to the current situation if needed 😉

**Comment by emmagarland** [comment]
@mikecp this PR is ready for review, presuming HQ are ok to try this approach on some initial projects? 

I think @Migaroez was handling this in terms of HQ?

**Comment by Migaroez** [comment]
Hey y'all

HQ is ok with the approach. As soon as all warnings have been removed in a given project, this setting can be turned on for that project.

Thanks for all the work @emmagarland #H5YR!

**Comment by emmagarland** [comment]
Ah that's amazing! Thanks so much @Migaroez for sorting. I'll hopefully get some time to do some more on Friday. 😃

**Comment by emmagarland** [comment]
(Switching back to draft as more warnings have been introduced since the initial PR that I need to fix/remove)

**Comment by emmagarland** [comment]
@Migaroez It's been a while, but I've merged from v14 and removed some where warnings had come in, but there's still a fair few warnings as errors switched on here. 

Thanks!

**Review by ronaldbarendse — CHANGES_REQUESTED** [review]
Great initiative! A cleaner way to gradually enable this on all projects would be to add `<TreatWarningsAsErrors>true</TreatWarningsAsErrors>` to `Directory.Build.props` (in the property group next to `WarningsAsErrors`, omitting the conditions used in this PR) and then disable them per project:

```csproj
<PropertyGroup>
  <!-- TODO: Fix all warnings and remove this override -->
  <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
</PropertyGroup>
```

Or only for specific [warning numbers](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-options/errors-warnings#warningsaserrors-and-warningsnotaserrors), like `CS0618` ([referenced obsolete members](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0618)):

```csproj
<PropertyGroup>
  <!-- TODO: Remove all usages of obsolete members and remove this override -->
  <WarningsNotAsErrors>CS0618</WarningsNotAsErrors>
</PropertyGroup>
```

Package validation uses a similar approach: https://github.com/umbraco/Umbraco-CMS/blob/d10596896e965b73a707354ffcad5be0ebd34235/Directory.Build.props#L32 https://github.com/umbraco/Umbraco-CMS/blob/9c5871434335ca2008b2c2db4222b68c81bf7c8f/src/Umbraco.Web.UI/Umbraco.Web.UI.csproj#L5

**Comment by emmagarland** [comment]
Cool, I like that idea @ronaldbarendse. I'll tweak that later and push the updates.

**Comment by emmagarland** [comment]
Hi @ronaldbarendse and @Migaroez 

Thanks for the suggestion, I've now updated as per the PR request to update the `Directory.Build.props` file to set all warnings as errors and then remove them on a project basis. I've done a specific removal for smaller numbers of warnings, and then a catch-all where there are many different warning codes. 

Please let me know if you have any other feedback, 

Thanks

Emma

**Comment by Migaroez** [comment]
Hey Emma, I am still seeing a few errors creep up on your branch

```
GoogleBackOfficeExternalLoginProviderOptions.cs(30, 40): [CS0618] 'Constants.Security.EditorGroupAlias' is obsolete: 'Use EditorGroupKey instead. Scheduled for removal in V15.'

ContextualAuthorizeAttribute.cs(114, 41): [CS1998] This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.

ContextualAuthorizeAttribute.cs(72, 9): [SA1117] The parameters should all be placed on the same line or each parameter should be placed on its own line (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1117.md)
  
GoogleBackOfficeExternalLoginProviderOptions.cs(43, 9): [SA1111] Closing parenthesis should be on line of last parameter (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1111.md)
    
PerformanceHelper.cs(11, 14): [SA1649] File name should match first type name (https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1649.md)
```

**Comment by emmagarland** [comment]
Thanks Sven, I didn’t catch that locally when I built it so I’ll check it
out later today

**Comment by Migaroez** [comment]
I am an idiot, these things from my test stash🤦 All good to go.

The only thing that worries me is the pipeline failing on the code analyzers. I had a similar issue when first checking out your branch. But it got auto resolved after swapping branches back and forth 🤷 I can't find any packages that are different from v14/dev...

**Comment by emmagarland** [comment]
Nice one @Migaroez, sounds good with those cherry picked build fixes!

**Pull request merged**
