### PR TITLE
V8: Add back button to listviews in media

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

When navigating content within listviews there's a back button that lets you navigate up the hierachy until you reach the root node level. That back button does not show when navigating media - e.g. folders with listview enabled.

This PR adds the back button:

media-listview-back

#### Testing this PR

1. Enable list view on the default media folder if it isn't already.
2. Create a folder structure in the media library.
3. Verify that the back button appears as soon as you start navigating downwards through the structure.
4. Verify that the back button takes you to the parent folder.
5. Add a media picker to a content type and edit some content of that type.
6. Open the media picker, navigate at least one level down through the structure and edit one of the folders there.
7. Verify that the back button does *not* appear in the infinite editing layer.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Oh I like this back button @kjac ! Great work - we'll shout if we need changes.

Em

**Comment by Shazwazza** [comment]
Do we already have this functionality for Content + Members ?

**Comment by kjac** [comment]
Yeah. The functionality was already there, I just enabled it for media. I'm pretty sure I tested it specifically for members, but I'll do a double take.

**Comment by kjac** [comment]
Right... the back button is not there for members. Yet. I'll have a look at a PR for that as well.

It *is* there for users and groups, though:

image

**Comment by kjac** [comment]
PR for member lists in #5158

**Comment by nul800sebastiaan** [comment]
Nice one, cheers!

**Pull request merged**
