### PR TITLE
Uploading SVG's Causes Error (Depending on imageFileTypes Setting)

### PR DESCRIPTION
**Pull request by imranhaidercogworks**
Created for the SVG bug reported here:

https://github.com/umbraco/Umbraco-CMS/issues/2909

Worked together on this PR with:

https://github.com/trt

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks @imranhaidercogworks and @trt 

I made a few more changes as there was a lot of things not working yet:

- Please only commit files that are actually changed for this PR. The media/web.config file was deleted and dashboards.config had an unrelated update
- I removed the option to make the default svg size configurable, we really only want to add any more config options unless it's absolutely necessary
- Uploading to a regular upload field crashed on generating thumbnails, moved some code around for that and made sure we don't try to create thumbnails for svg files as it's just not necessary
- In the image cropper no preview would be shown because the `` tag renders as 0x0 pixels for svg files, the browser has no idea how to deduce size either. I changed that to 200x200 too
- Finally, it doesn't make any sense to crop svg files, so I had to remove cropping behavior as well.

I think it all looks good now and I've tested (I think) all the ways to upload files, including the old upload datatype. Pickers work as well as far as I can tell.

Many thanks for the help here! @trt if you have an account on Our Umbraco can you link to your public profile? Then I can add that shiny contributor badge to your profile! 👍

**Comment by trt** [comment]
Hi @nul800sebastiaan,
Thanks for the missing parts in our code.
My public profile on our is: https://our.umbraco.com/member/151346

Thanks,

**Comment by nul800sebastiaan** [comment]
@erzki It will be released in 7.1.3.0, see the related issue: #2909

**Comment by ErikHen** [comment]
@erzki I think @nul800sebastiaan means 7.13.0 :-)

**Pull request merged**
