### PR TITLE
Apply pickDate-config setting to hide calendar in datepicker

### PR DESCRIPTION
**Pull request by inetzo**
A time-only picker is only possible if the format is configured like "hh:mm:ss". By using the pickDate config it is possible to determine whether the calendar should be shown or not, instead of depending on a certain time format.

### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes

### CODE REVIEW

**Comment by mikecp** [comment]
Hi @inetzo ,

Thanks for your PR!

I tested it locally and I tried it with pickDate config set to 'false' and format set to "not hour format" (e.g. YYYY-MM-DD HH:mm:ss), which I guess is the use case for this PR. 
It  gave something strange, because it displays only the time picker indeed, but the value displayed still contains the date, which I find kind of confusing.

image

Maybe I have been overseeing something in my test, but I am wondering if an alternative could be to make the "time format" check on line 59 less strict, for example moving from the current one which requires at least hours, minutes and seconds to one that requires only hours and minutes.

What is your feeling about this? Or maybe I tested it wrongly?

Cheers!

**Comment by inetzo** [comment]
Hi Mike,

Thanks for reviewing. It depends on what you want to achieve with it. In my case I want a user to be able to set only a time, not a date. So in format "HH:mm" or "H:mm". This is not possible without this adjustment because a time picker is only shown if the date format is set to "HH:mm:ss", so always with seconds added to it.  Currently if it is not exactly this format, the calender is always shown at this time. 

Cheers!

**Comment by mikecp** [comment]
Hi @inetzo ,

Thanks for the clarification of your situation. I checked with my teammates and we think that it would be better to remove your check and update the regex instead, making it work with formats containing hours and minutes but without seconds.

This way, we still have a display of the picker that matches the output format (and avoid confusing situations like my screenshot above), but we make the verification less strict and probably better matching the real use of "time only".

It would be great if you could make that change, I'll then be glad to merge it 😁

**Comment by inetzo** [comment]
Hi @mikecp ,

I've updated the regex. But what to do with the pickDate config property? It's not used in the dateTimePickerController.
Should it be removed?

**Comment by mikecp** [comment]
Hi @inetzo ,

Thanks for the update, it works great 👍 
Regarding the pickDate config property, we probably can get rid of it as it is indeed not used within the datepicker controller. But in that case, the logviewer search controller probably needs some cleanup too as it is setting that property.

If you feel like doing that cleanup too, I'll wait before merging. Thanks!

**Comment by inetzo** [comment]
Hi @mikecp , I removed the unused config.pickDate property.

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Thanks for the update @inetzo 👍 

I took the liberty to cleanup the logviewer search controller as well, I hope you won't mind 😁

Cheers!

**Pull request merged**
