### PR TITLE
Fix internal class being returned from media cache service

### LINKED ISSUE #17204: Unable to cast IPublishedContent in MediaWithCrops
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

15.0.0-rc1

### Bug summary

When trying to cast IPublishedContent present in MediaWithCrops to its relevant type you get the exception
`InvalidCastException: Unable to cast object of type 'Umbraco.Cms.Infrastructure.HybridCache.PublishedContent' to type 'xyz'.`

### Specifics

_No response_

### Steps to reproduce

Create a document type with a media with crops allowing `Image`.
Try to cast the content e.g
`Model.MediaWithCrops.Content as Image`
Observe that the result is null. Attempting with a hard cast of
`(Image)Model.MediaWithCrops.Content` results in the exception
``InvalidCastException: Unable to cast object of type 'Umbraco.Cms.Infrastructure.HybridCache.PublishedContent' to type 'TheNamespace.Image'.``

### Expected result / actual result

You should be able to cast the PublishedContent in this case

### PR DESCRIPTION
**Pull request by matthewcare**
Return the correct models from the media cache service

Fixes #17204

### CODE REVIEW

**Comment by mikecp** [comment]
Hi @matthewcare,

Thanks a lot for spotting the issue and providing the fix for it 🤩👍

I noticed that you targeted the branch `v15/dev`, but we expect the contribuions from our community members to be targeting the `contrib `branch 😅
So it would be super great if you could retarget your PR, and then someone from the core collaborators team will have a look at it.

Thanks and cheers!

**Comment by matthewcare** [comment]
Hey no worries, I've retargeted

**Review by bergmania — APPROVED** [review]

**Comment by bergmania** [comment]
Thanks for contributing. We must have missed this one, when we did it for content. Code changes looks good to me

**Comment by bergmania** [comment]
Cherry picked for 15.0.0-rc2 here https://github.com/umbraco/Umbraco-CMS/commit/ea073e61580cd2b5ac4dab13ed8a263836db19b7

**Comment by nul800sebastiaan** [comment]
Thanks again @matthewcare!

Just a hint: as you may know, this PR qualifies for [Umbraco's Hacktoberfest](https://umbraco.com/blog/join-us-for-umbraco-hacktoberfest-2024/) participation for which you can [earn rewards](https://cultiv.social/@sebastiaan/113311358180849090).
If you were to make 1 more contribution in the next few days, would be great to see your contributions qualify! You can do it.. 😉

**Pull request merged**
