### PR TITLE
#3163 - Don't overwrite the label name even though labels are disabled in the color picker

### PR DESCRIPTION
**Pull request by BatJan**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues/3163) for the proposed changes in this PR, the link is: https://github.com/umbraco/Umbraco-CMS/issues/3163
- [x] I have added steps to test this contribution in the description below

### Description
I've modified the code so the entered label does not get deleted in case we need to enable it again at a later stage.

I can see that it might be confusing that there is a label name when labels are not activated. But on the other hand the field is greyed out and it does not change value when switching.

I'm open to change the binding back to item.value instead of label but I don't see any reason why the value can't be kept so when enabling the labels again the label entered earlier is still present 😃 

Behavior before PR
enabledisable-labels-before

Behavior after PR
enabledisable-labels-after-2

### CODE REVIEW

**Comment by bjarnef** [comment]
Not sure if it should use labels, if you decide to disabled labels. It will use the label as tooltip https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/views/components/umb-color-swatches.html#L3
With this change it will then use the labels instead of the values (color code) as tooltip. 

How will the tooltip looks if the color labels are cleared and disabling the labels?
When upgrading sites from older version it will use value as label. Not sure which impact this change will have on these scenarios?

**Comment by BatJan** [comment]
I modfied the code in the line you mentioned @bjarnef to check whether useLabel is true or not and then either use the label the value for the tooltip depending on this https://github.com/umbraco/Umbraco-CMS/pull/3164/commits/5a196b8f9620361ba4c686b63d6bc752b3260b42#diff-5e8649bacf1058a00cad4caa49b033c8R3

This is what it looks when the labels are not in use
tooltip-not-using-labels

And this is what it looks like when it is in use
tooltip-using-labels

With this change I don't think that there will be any issues when doing an upgrade since in that case the useLabel value will be false or falsy and therefore not try to render the label.

The only thing I can think will appear a bit different is that part on the property editor where we render the label value in a span instead of the input field. That might be empty when upgrading but I don't think that's a big issue. It won't break anything and if labels are added one will see the behavior showcased in the after gif from my initial post...I think! :)

**Comment by poornimanayar** [comment]
Hi @BatJan ,

I have tested the PR and it works as expected. One little question, do you think the tooltip should say the hex code like "#000000" rather than "000000"

Poornima

**Comment by BatJan** [comment]
Hi @poornimanayar thank you for testing :-) - Hmm, yeah that is probably a good idea. I'll have a look at it later today :)

**Comment by nul800sebastiaan** [comment]
Gave it a little `#` as suggested, all great otherwise, thanks a lot everyone, loved the discussions and suggestions back and forth! 👍

**Comment by bjarnef** [comment]
@BatJan you broken the tooltip on colors in document type icon picker :see_no_evil: :grimacing: 
, but no worry I have fixed it https://github.com/umbraco/Umbraco-CMS/pull/3248 :grin: :raised_hand:

**Comment by BatJan** [comment]
Haha! Well @Sebastiaan merged before I had another chance to look at the PR after Poornimas suggestion 😜 So I blame Seb 😅

Good catch Bjarne! 😀👌🙌

**Comment by poornimanayar** [comment]
Good catch @bjarnef 👍 I have tested both again and can confirm that all is looking well :-)

**Pull request merged**
