### PR TITLE
fixed #14832 user without  HasAccessToSensitiveData change sensitive data:  IsApproved IsApproved IsTwoFactorEnabled

### LINKED ISSUE #14832: Issue with Approved property when members from Umbraco Backoffice with a user that doesn't have the "Sensitive data" role.
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.6.1

### Bug summary

There seems to be a bug/issue when trying to update an Umbraco member from the Umbraco backoffice, signed in with a user that doesn't have the **Sensitive data** user role assigned.

The value of the **Approved** property of a member is only visible to the umbraco user, if that user has the **Sensitive data** user role assigned. I'm personally wondering why the **Approved** property is considered sensitive data, but at the moment it is.

If a member has the **Approved** property set to true, and a Umbraco user updates any data on that member without having the **Sensitive data** role (so the value of the field is hidden to the user), the value of the **Approved** property is then set to false after the update. I believe the correct behavior would be that values of fields hidden to the user would stay as they were before the update, and not change?

This has caused some issues for us, because without the Approved property set to true, the member login doesn't work. So suddenly member logins stopped working after having some unrelated field updated on them from the backoffice. 

### Specifics

The URL is: /umbraco#/member/member/edit/{memberId}

I have only tried this in Google Chrome browser.

### Steps to reproduce

- Have an Umbraco member that has the **Approved** property set to true
- Log into the Umbraco backoffice with a user that doesn't have the **Senitive data** role assigned.
- Update any property on that member from that umbraco user
- Check the value of the **Approved** property on the member afterwards - It should not be false.

### Expected result / actual result

I would expect any property hidden to the user updating a member, to stay the way they were before the update, and not change.

### PR DESCRIPTION
**Pull request by kevinfu2**
### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #14832 

### Description

change persisted IsApprove with user data if user HasAccessToSensitiveData
restore user data  IsApprove  IsLockedOut  IsTwoFactorEnabled  with persisted data

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi @kevinfu2,

Thanks for your PR to fix #14832, where the Approved property of a member is set to false when updated by a user without the "Sensitive data" role assigned.

One of the Core Collaborators team will review this as soon as possible.

Best wishes

Emma

**Comment by IanIsFluent** [comment]
Hi! We're excited for this bug being fixed! Looks like there's a problem with the CodeScene check?

**Comment by kevinfu2** [comment]
> Hi! We're excited for this bug being fixed! Looks like there's a problem with the CodeScene check?

Hi, I've only made the minimum changes to fix this bug. If we want to reduce code complexity, it might be necessary to modify many bug-unrelated pieces of code. Please let me know if that's needed.

**Comment by nul800sebastiaan** [comment]
Thanks for this one @kevinfu2 - the CodeScene checks are really more for new code written, so this is just fine. All good on the work here and thanks very much for the contribution (apologies for the delay!). Great work 👍

**Comment by AndyProsperEx** [comment]
Is this not being merged into v10?

Cheers

**Comment by nul800sebastiaan** [comment]
Umbraco 10 has only been getting security fixes since June last year and will not get any more fixes after December: https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/

**Pull request merged**
