### PR TITLE
Convert model factories to static classes in Umbraco.Core.Persistence.Factories  

### PR DESCRIPTION
**Pull request by ismailmayat**
### Prerequisites

- [ X] I have written a descriptive pull-request title
- [ ] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### CODE REVIEW

**Comment by lars-erik** [comment]
I might be daft, but why was this done? With DI in place, there could be one static abstract factory invoking all the IEntityFactory implementations we had. To me making all this static is just less solid and more rigid.

**Comment by zpqrtbnk** [comment]
Previous situation: instanciate factory objects each time we had to map to/from a DTO. Same factory object, no way to replace it by anything else. And, everything very dependent on the underlying implementation of things (eg `Content` vs `IContent`). So all in all very unefficient.

Could be made way more elegant with DI and abstract factories etc. But, that would require design, and we cannot design everything at once. So, short term, we just reduce allocations. In due time, of course, it may be worth considering injecting these factories.

You might find other similar situations in v8, where half-backed pseudo extension mechanisms that did not work are just plainly going away so the situation is, at least, clean - does not mean a real, clean DI solution is ruled out, long term.

**Comment by lars-erik** [comment]
Cool 😊 Future.

**Comment by lars-erik** [comment]
Agreed it's better not to allocate new instances all the time. There are two options. Revert and register them as singletons, or leave it be and abstract behind statics later. I guess later is the go-to option for now.

**Pull request merged**
