### PR TITLE
Dev v7 pluggable i searchable tree

### PR DESCRIPTION
**Pull request by efabioli**
This pull request has been thought to allow developers to customize back-office tree searches.

It works quite simply: I have taken off all code Examine related in EntityController and moved into ExamineTreeSearcher class (that implements IUmbracoTreeSearcher);
EntityController constructor calls UmbracoTreeSearcherResolver.GetInstance that provides an implementation of IUmbracoTreeSearcher.

Web.Config (app.setting in Umbraco.Web project has been updated) contains a new section called UmbracoTreeSearcherFactory that can be used to specified a custom factory class which will provide the custom implementation of IUmbracoTreeSearcher.

### CODE REVIEW

**Comment by Shazwazza** [comment]
Thanks, we'll review when there is time for an upcoming version, see here for discussion: http://issues.umbraco.org/issue/U4-2676

**Comment by darrenferguson** [comment]
@Shazwazza I'm told "post codegarden" by HQ for having this reviewed. Any reason?

**Comment by Shazwazza** [comment]
Purely due to priorities and timeframes, i'll do my best to review sooner but i can't guarantee anything

**Comment by Shazwazza** [comment]
Closing this PR as this one supersedes it https://github.com/umbraco/Umbraco-CMS/pull/2063, see updated issue for full details http://issues.umbraco.org/issue/U4-2676

**Pull request closed without merging**
