### PR TITLE
Media library thumbnail does not reload if a new image with the same name is uploaded

### PR DESCRIPTION
**Pull request by mvanhelmont**
Simple fix to reload thumbnail image if same name

### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description
Added a simple rnd to the url for GetBigThumbnail. 

Issue: http://issues.umbraco.org/issue/U4-7463

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Maybe it's just me but that doesn't seem like the best idea, we only want to get a new thumbnail if it actually changed, now we'll just never get a cache hit?

**Comment by dawoe** [comment]
This is in the file upload controller. So I think this will only cache bust when uploading new files @mvanhelmont can you confirm ?

**Comment by dawoe** [comment]
@mvanhelmont maybe you can make a short screencast showing the bug and attach that to the issue on the tracker ? I use https://www.screentogif.com/ for that

Dave

**Comment by mvanhelmont** [comment]
@dawoe First off all i wanna tell it's only with the file upload property and i have noticed that on new installs the Image Cropper is used and that works perfectly.

The problem with the File Upload property is the browser will never try to load the images again when the name is the same.  http://geniuscarrier.com/a-problem-with-ng-src-in-angularjs/

I have added a before:
before

and after:
after

**Comment by nul800sebastiaan** [comment]
Sorry for the delay @mvanhelmont - looking at this again, indeed it only applies to when you upload a file, so in that case I'm fine with adding a bit of randomness to it! 👍

**Pull request merged**
