### PR TITLE
V8: Accessibility improvements for page name entry

### PR DESCRIPTION
**Pull request by RachBreeze**
This PR is a resubmission of #5585

It aims to fix 43, 69, 75, 81 from the from the A & AA accessibility issue list #5277

**Creating a content item**
When creating a new content type there is screen reader only text which says:
"Create" + content type name

The concept is that it wkors as per Microsoft Teams, here when a user creates a folder they see:

image

**Editing a content item**
When editing an existing content item there is screen reader only text which says
"Edit" + content name

**Name label**
The "name" text box also now now has a hidden label which is "content type name" + Name

**Placeholder**
The placeholder in the name textbox remains the same as prior to this change, as placeholder text provides guidance for many users, placeholder text is not a replacement for labels.

_Language amends_
The language files now have accessibility specific place holders these have been added to en.xml and en_us.xml only

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi Rachel,

Thanks ever so much for the work. We'll take a look and let you know if we need anything from you.

Emma

**Comment by nul800sebastiaan** [comment]
Hey @RachBreeze! Thanks very much for the help here, I'll test it soon.

Just as a heads up: I have reverted most of your changes in the language files since it was impossible to figure out what actually changed. In the future, try to see in your git client, before you commit changes if all the whitespace has changed. It would be good to only commit the few lines that have actually changed so that the diff is readable. 👍

**Comment by nul800sebastiaan** [comment]
Works great! 🔉 "Edit Home" and 🔉 "Create ContentPage" - cool stuff!

Thanks very much @RachBreeze - well done! 👍👍

**Comment by nul800sebastiaan** [comment]
Cherry picked into 8.1.3 (9cab7894256507ec30a43f4d48fafb72cab5bddb)

**Pull request merged**
