### PR TITLE
Update ContentTypeRepositoryBase.cs

### PR DESCRIPTION
**Pull request by erolakgul**
propertytypeid => propertyTypeId

### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes

### CODE REVIEW

**Comment by erolakgul** [comment]
It is necessary you to approve the changes i have made in ContentTypeRepositoryBase class for turkish users. Many people can be use turkish_ci or turkish_cs collation their database. thank you..

**Comment by ronaldbarendse** [comment]
Issue https://github.com/umbraco/Umbraco-CMS/issues/7552 contains a related discussion about changing all these different casings into constants and the conclusion is to do this in small PRs, so you're on the right track.

Regarding the issue you're trying to fix: this probably isn't the only column name that contains a different casing. You're better off using a database with the generic `Latin1_General_CI_AS` collation (see https://our.umbraco.com/forum/using-umbraco-and-getting-started/86852-umbraco-sql-collation-issue - keep in mind that changing the database collation doesn't change existing column collations though).

**Comment by erolakgul** [comment]
Maybe you are right may be not. 

I dont agree with because;
In turkish, "I" and "i" are different characters. İ is upper case of i. Then  "I" is upper case of ı. If we chosed turkish_ci... it does not work 1187. line in ContentTypeRepositoryBase.cs because of propertytypeid. It must be  propertytypeid => propertyTypeId.

I agree with because;
If we chosed Latin1_General_CI_AS, it works.

> Issue #7552 contains a related discussion about changing all these different casings into constants and the conclusion is to do this in small PRs, so you're on the right track.
> 
> Regarding the issue you're trying to fix: this probably isn't the only column name that contains a different casing. You're better off using a database with the generic `Latin1_General_CI_AS` collation (see https://our.umbraco.com/forum/using-umbraco-and-getting-started/86852-umbraco-sql-collation-issue - keep in mind that changing the database collation doesn't change existing column collations though).

**Comment by nul800sebastiaan** [comment]
Thanks @erolakgul, this change will be shipped with Umbraco 8.8.0! 

As Ronald noted, this is likely not the only problem you'll encounter but I hope this is enough for you for now. The related discussion details that it's going to be difficult to change all of the problems without making breaking changes, but updating the SQL query here is fine of course.

Looks like this is your first contribution to Umbraco CMS, congrats! 👍 

If you have an account on [Our Umbraco](https://our.umbraco.com) I'd love to give you a contributor badge, just send me a link to your profile!

**Pull request merged**
