### PR TITLE
Only show rollback button if allowed action

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/13539

### Description
When rollback isn't an allowed action for the node, the rollback button shouldn't be rendered.

https://user-images.githubusercontent.com/2919859/207027343-40d86558-4388-499e-8efb-11667ffcaf62.mp4

Example using `SendingContentNotification`:

```
public class EditorSendingContentNotificationHandler : INotificationHandler<SendingContentNotification>
{
    private readonly IBackOfficeSecurityAccessor _backOfficeSecurity;

    public EditorSendingContentNotificationHandler(
        IBackOfficeSecurityAccessor backOfficeSecurity)
    {
        _backOfficeSecurity = backOfficeSecurity;
    }

    public void Handle(SendingContentNotification notification)
    {
        if (notification.Content.ContentTypeAlias.Equals("blogpost"))
        {
            var currentUser = _backOfficeSecurity?.BackOfficeSecurity?.CurrentUser;
            if (currentUser == null)
                return;

            List<string> readOnlyProperties = new()
            {
                "authors"
            };

            bool found = false;

            // Hide tabs/properties depending on user access.
            if (!found)
            {
                var tabAliases = notification.Content.Variants.First().Tabs
                    .Where(x => x.Alias != "content")
                    .Select(x => x.Alias)
                    .WhereNotNull()
                    .ToList();

                ReadOnlyProperties(notification.Content, readOnlyProperties);

                HideTabs(notification.Content, tabAliases);

                HideActions(notification.Content, new string[]
                {
                    $"{ActionUpdate.ActionLetter}",
                    $"{ActionUnpublish.ActionLetter}",
                    $"{ActionPublish.ActionLetter}",
                    $"{ActionToPublish.ActionLetter}",
                    $"{ActionRollback.ActionLetter}",
                    $"{ActionDelete.ActionLetter}"
                });
            }
        }
    }

    private static void ReadOnlyProperties(ContentItemDisplay contentItemDisplay, List<string> propertyAliases)
    {
        if (propertyAliases.Any())
        {
            foreach (var tab in contentItemDisplay.Variants.First().Tabs)
            {
                List<ContentPropertyDisplay> properties = new();

                foreach (var prop in tab.Properties!)
                {
                    if (propertyAliases.Contains(prop.Alias))
                    {
                        prop.Readonly = true;
                        //prop.Editor = "Umbraco.Label";
                        //prop.View = "readonlyvalue";
                    }

                    properties.Add(prop);
                }

                tab.Properties = properties;
            }
        }
    }

    private static void HideActions(ContentItemDisplay contentItemDisplay, string[] actions)
    {
        contentItemDisplay.AllowedActions = contentItemDisplay.AllowedActions?.Where(x => !actions.Contains(x));
    }

    private static void HideTabs(ContentItemDisplay contentItemDisplay, List<string> tabAliases)
    {
        if (tabAliases.Any())
        {
            contentItemDisplay.Variants.First().Tabs = contentItemDisplay.Variants.First().Tabs.Where(tab => !tabAliases.Contains(tab.Alias!) && tab.Properties?.Any() == true);
        }
    }

    private static void HideProperties(ContentItemDisplay contentItemDisplay, List<string> propertyAliases)
    {
        if (propertyAliases.Any())
        {
            foreach (var tab in contentItemDisplay.Variants.First().Tabs)
            {
                tab.Properties = tab.Properties?.Where(property => !propertyAliases.Contains(property.Alias));
            }
        }
    }

    private static void HideEmptyTabs(ContentItemDisplay contentItemDisplay)
    {
        contentItemDisplay.Variants.First().Tabs = contentItemDisplay.Variants.First().Tabs.Where(tab => tab.Properties?.Any() == true);
    }
}
```

### CODE REVIEW

**Comment by bjarnef** [comment]
@nikolajlauridsen this should fix the UI issue 😉

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Thanks @bjarnef for fixing this issue 👍  It now works as expected indeed 😁🎉
Cheers!

**Comment by bjarnef** [comment]
@nul800sebastiaan could this be cherry picked for 10.4.0 release as well?

**Comment by nul800sebastiaan** [comment]
Cherry picked for 10.4 in c04b11cf1772b605ce2425e4cc9773b629ab0227

**Comment by nul800sebastiaan** [comment]
Cherry picked for 10.5 in c04b11cf1772b605ce2425e4cc9773b629ab0227

**Pull request merged**
