### PR TITLE
Added "git submodule update --init" command to the documentation

### PR DESCRIPTION
**Pull request by BuddhiEash**
### Description
**Before**

- Try with an older git version.

- In my case, it was git version - 2.32.0.windows.2

Screenshot 2024-05-31 115849

**After**

- Works with any git version

- Submodule path 'src/Umbraco.Web.UI.Client': checked out

### CODE REVIEW

**Comment by Matthew-Wise** [comment]
Hi @BuddhiEash 

Thanks for this this PR and making contributions more accessible. 
One of the Core Collaborators team will review this as soon as possible.

Matt

**Comment by Matthew-Wise** [comment]
Hi @BuddhiEash 

Just the current documented method with the version of git you mentioned and it does work for me:

image

Did you also do this from a fresh check out?

thanks
Matt

**Comment by BuddhiEash** [comment]
> Hi @BuddhiEash
> 
> Just the current documented method with the version of git you mentioned and it does work for me:
> 
> image
> 
> Did you also do this from a fresh check out?
> 
> thanks Matt

Hi @Matthew-Wise: Thanks for the reply.
Yes, I tried this from a fresh check out.
I tried cloning a fresh copy to different locations in my folders as well.
So didn't work until I use `git submodule update --init`

**Comment by Matthew-Wise** [comment]
Hi @BuddhiEash 

The mysteries of git versions! Single commands are always nice little speed up so merged :D 

Do you have an account on https://our.umbraco.com/ so we can add your contributor badge? 

Thanks again for your first contribution!!

Matt

**Comment by nul800sebastiaan** [comment]
Congrats on your shiny new contrib badge @BuddhiEash! 🏅  https://our.umbraco.com/members/id:60409/

**Comment by BuddhiEash** [comment]
Thank you @Matthew-Wise and @nul800sebastiaan :)

I'm really happy :D

**Pull request merged**
