### PR TITLE
Fix: Force create SQL Server database if connection details are valid.

### PR DESCRIPTION
**Pull request by AndyBoot**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

If installing Umbraco using SQL Server as a database provider before creating a blank database within SSMS first, this causes the installation to fail with the error "Could not connect to database".

I've made minor changes to the installation process which first checks if the DB provider is `Microsoft.Data.SqlClient` after failing a connection test and applies a flag to force create database. Upon doing so the DB will be created using the `CREATE DATABASE` command before attempting to create the schema and data. However, upon attempting to do this immediately after invoking the create DB command would cause a failure given the DB is still technically being created and unable to proceed. To combat this I've adapted it to retry every 500ms for up to 10 times before eventually failing. During my tests this works after the 3rd or 4th retry attempt.

### Testing

Simply install without creating the SQL Server DB first.

#### Videos

Without fix: https://github.com/umbraco/Umbraco-CMS/assets/82056925/2b8f85e8-64a9-4fe5-908b-4d55264d9da3

With fix: https://github.com/umbraco/Umbraco-CMS/assets/82056925/694c1aa4-da2b-4bee-9b67-043aa83a2a91

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi again @AndyBoot!

Thanks for your PR to fix an where you get a failed installation when using SQL Server as a database provider before creating a blank database within SSMS. I was wondering if there is a related issue to link to that this PR would close just to tie it together?

One of the Core Collaborators team will review this as soon as possible. I expect we might need to double check with HQ too. 

Best wishes

Emma

**Comment by AndyBoot** [comment]
> Hi again @AndyBoot!
> 
> Thanks for your PR to fix an where you get a failed installation when using SQL Server as a database provider before creating a blank database within SSMS. I was wondering if there is a related issue to link to that this PR would close just to tie it together?
> 
> One of the Core Collaborators team will review this as soon as possible. I expect we might need to double check with HQ too.
> 
> Best wishes
> 
> Emma

Hi @emmagarland, 

No issues related to this PR as far as I know. This was more resolving a personal frustration than anything and figured I'd try and fix it myself before escalating as an issue (which I think I was successful in doing!?). 

Thanks,
Andy

**Comment by AndyBoot** [comment]
See the below tests performed with invalid connection details:

image
image

**Comment by ronaldbarendse** [comment]
> If installing Umbraco using SQL Server as a database provider before creating a blank database within SSMS first, this causes the installation to fail with the error "Could not connect to database".

This is expected behaviour, because you need to opt-in to creating the database by enabling `InstallMissingDatabase`, see the [setting documentation](https://docs.umbraco.com/umbraco-cms/reference/configuration/globalsettings#install-missing-database) and the [info note on the unattended install instructions](https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/unattended-install#configure-your-database).

However, how this all works has recently changed (because of a potential security issue), which had caused some other problems, see issue https://github.com/umbraco/Umbraco-CMS/issues/14956.

**Comment by JasonElkin** [comment]
Hey @AndyBoot, thanks for taking the time to contribute to Umbraco for Hacktoberfest!

As Ronald points out, this feature already exists as an opt-in setting.

One of the reasons it's opt-in is because it's easy to make mistakes with this approach. It can lead to unwanted database creation (consider an typo in a database name) and there are some scenarios where this won't work as expected (e.g. An Azure SQL Database). Failing by default is a good approach as it forces the developer to think about the problem and make a more intentional choice to fix it.

This is also a significant change to Umbraco's current behaviour that could cause problems for developers that are used to Umbraco working this way.

With those points in mind, I'm going to close this PR.

Thanks again for contributing! For future contributions where you want to change Umbraco's behaviour like this, or add a new feature, it's really helpful to raise an issue or start a discussion so that the community and HQ can weigh in and make sure that we're building Umbraco to be as friendly as possible.

**Pull request closed without merging**
