### PR TITLE
V8: Can't delete user groups

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

It's not possible to delete user groups - the server simply returns an error:

image

It doesn't matter if you attempt to delete one or multiple user groups, the result is the same.

With this PR applied, user group deletion works as expected:

delete-user-groups

### CODE REVIEW

**Comment by kjac** [comment]
Reported as an issue in #5958

**Comment by emmaburstow** [comment]
Hey Kenn, Thanks for doing this. And thanks for linking it to the issue. We'll be in touch if we need you,

Em

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by nul800sebastiaan** [comment]
Lovely fix, thanks a lot @kjac !

**Pull request merged**
