### PR TITLE
Fixes: Consistency for Nullable reference types in LINQ extensions methods #12692

### PR DESCRIPTION
**Pull request by DanDiplo**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes - https://github.com/umbraco/Umbraco-CMS/issues/12692

### Description

Removes some of the pain around nullable reference types.

Makes querying `Children()` and similar axis methods simpler by ensuring they never return null - they will always return an empty collection.

Also ensure that the `Root()` method can never return null, as there always should be root content. 

Finally, ensures the `.Name` property can never be null. It will default to `string.Empty`. Again, this makes referencing it simpler as avoids the need to add extra null checks.

All Unit tests pass.

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Sorry for the delay @DanDiplo - we rebased your changes and this all seems good to go for v11. Thanks again for the help! 👍

**Comment by DanDiplo** [comment]
@nul800sebastiaan No worries, glad to help! Looking forward to v11

**Comment by KevinJump** [comment]
Hi, 

looks like this makes a breaking change? 

(specifically, https://github.com/umbraco/Umbraco-CMS/pull/12703/files#diff-04ea84454360ff165d2411fe7f2fb64ceb3f8f2ee5de57789a0f424d35608a5fL694-L699 )

For example on the Umbraco starter kit - if you add the following to the `master.cshtml` template: 

```cs
@{
    var productsPage = Model.AncestorOrSelf("Products");
    if (productsPage != null) {
      <h2>[@productsPage.Name]</h2>
    } else { 
      <h3>No Product parent</h3>
      }
}
```

in v10 or below you would expect "No Product parent" on any page that isn't the poducts or a product page. so for example on the homepage it would say "No Product Page"

on v11.1 this returns "[Home]" when on the homepage. which means you can no longer use the logic above if you want to put something in a master or parent template that only renders in certain parts of your site tree.

**Comment by DanDiplo** [comment]
@KevinJump I think you are right in regard to the `AncestorOrSelf` method. The idea was that all LINQ methods that returned collections should never return null - they should always return an empty collection - so you could chain methods without worry. But the `AncestorOrSelf()` method looks like it should return null if not found as it just returns a single node. Not sure why I changed that...

I think the other methods are OK, though? Is it just that one? I can do a PR to fix if it's just that...

**Comment by ixitab** [comment]
I ran in to this issue when upgrading a v9 site to v11. @DanDiplo you are correct that it should return null. Can you make a pull request to fix it as you suggested?

**Pull request merged**
