### PR TITLE
fix 2fa user login - add twoFactorView property to response (15781)

### PR DESCRIPTION
**Pull request by MihailichenkoPavel**
### Description
This PR fixes the login function in **auth.repository.ts** on the new Login UI. _twoFactorView_ property has been added to the response to display the custom 2fa view, before that returned only status and error and displayed the default 2fa view
Issue: https://github.com/umbraco/Umbraco-CMS/issues/15781

### CODE REVIEW

**Comment by mikecp** [comment]
Hi @MihailichenkoPavel ,

Thanks for your contribution and for providing a fix on the 2fa login screen. Someone from the core collaborators team will have a look at it soon.

Cheers!

**Comment by mikecp** [comment]
Hello @MihailichenkoPavel ,

Thanks again for your PR! I have checked it and it solves the problem as described, so it looks like we're ready to merge  😁

I see this is your first contribution to Umbraco, congratulations 🎉
If you provide us with your account name on the forum, we will gladly assign our shiny contributor's badge to you 🏅

This was a great contribution to start with, and we'll be waiting for the next ones 😉

Cheers!

**Comment by MihailichenkoPavel** [comment]
Hi @mikecp thank you! 

My account on the forum: https://our.umbraco.com/members/id:343775/ 😃

**Comment by busrasengul** [comment]
Your badge is now granted!! Congratulations! 🎉

**Pull request merged**
