### PR TITLE
V8/feature/super doctype create menu

### PR DESCRIPTION
**Pull request by marcemarc**
### Prerequisites

- [^ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6410

### Description

Hi, this is an update to the Document Type Create Menu.

Why? - there is a blog post here that contains most of the thinking: https://moriyama.co.uk/about-us/news/creating-doctypes-in-umbraco-v8/

I've been using it as a 'getting started' training support tool when working with people who are new to Umbraco to help them get used to the concepts. I released it as a package:

https://our.umbraco.com/packages/backoffice-extensions/super-doc-type-create-menu/

There has been a clamour to add it to the core, but as the issue, this is linked to states - HQ have better plans than this for the Doc Type menu.

However, have been asked if I would submit a PR anyway by thechiefunicorn:

image

and so I am doing so.

### To test this

Go to Settings - Document Types - and open the Create Menu, you should now see an updated menu with different icons, and descriptions for different types of Document Types you can create, the thinking is in the blog post above.

It's worth testing each menu item, to see if it performs as advertised, the Element Type option should create a Document Type with the 'Is Element Type' checkbox already checked.

### Wording

In terms of the wording of the options, I'm sure it could be improved, really it's the icon and the clear label of the option, and the order of the options that is the improvement (eg no Document Type Without Template option). But I'm happy if people maybe want to tweak the descriptions, etc

I'm aware this removes the Document Type Collection option.

That's it I think!

Thanks for considering this contribution to Umbraco CMS!

### CODE REVIEW

**Review by kjac — DISMISSED** [review]
This is really awesome! Thank you for this ⭐ 

So a few things come to mind when reading through your changes:

1. `data-element="action-documentTypeWithoutTemplate"` is used multiple times in the HTML. You should update those for uniqueness.
2. Creating a "Document type" and a "Component" performs the exact same action. I get the idea, but I'm not sure newcomes find it intuitive. Perhaps one single action that describes both use cases would be better?
3. Since you're (rightfully) removing the doctype collection creation, I reckon the server side controller action should be cleaned up as well?

**Comment by marcemarc** [comment]
Hi @kjac 

Thanks for looking at this!
In answer to your points

1) I have updated these to be unique - to be honest, I'm not sure what they are for!

2) I think you not thinking about 'discoverability' for people who are starting out with Umbraco - this is why the menu and package was updated to be like this - to help people are new to Umbraco understand the options from this menu - I have been using it for the last year with new Umbraco developers to help explain the fundamentals of Doc Types - Umbraco is poor about introducing the concept of composition to new people, and the differences between a Doc Type having a template and not having a template - surfacing this as an option on this menu allows people to think 'hmm, what is a composition?' and use their intuition to explore, discover and learn... otherwise they need to be directly taught about the differences because they are 'less intuitive'. The blog post does go into more detail too: https://moriyama.co.uk/about-us/news/creating-doctypes-in-umbraco-v8/ - but I totally understand if you just feel it shouldn't be this way based on your own experiences...  it's just more of a convoluted explanation when you merge the different 'concepts' into one option, and I felt it worked better if each different thing was a different thing on the menu.

3) I did think about removing the serverside stuff too, but I wasn't confident this PR would be accepted anyway :-) based on the issue! - but if we do remove them - would this be a breaking change? eg what if somebody is using the implementation in a custom package etc, or wants to add the collection functionality back in, via a package because they have come to rely on it? - or we could mark them as obsolete?

regards

Marc

**Comment by kjac** [comment]
@marcemarc I have no idea about those attributes either. I believe you could also just them, but if they're there I guess they ought to have some uniqueness to them. 

As for the options and discoverability I really do get your point. I just don't think it's terrible intuitive having two distinctively different options performing the exact same action. I fear people will simply conclude there is something not working. Hence why I suggested a single action that describes both use cases. Would that be possible or would it become too much of a wall of text? Perhaps linking to docs would be a workaround?

Lastly... if I recall correctly, changes to the backoffice controllers are not considered breaking. That would make it impossible to maintain any kind of progression. See also https://our.umbraco.com/documentation/development-guidelines/breaking-changes#backoffice-controllers

**Comment by marcemarc** [comment]
Ahhh @kjac , I think you are really close to understanding! because I think you have revealed the reason why you are not grasping the rationale - it's because you think that a Composition is exactly the same thing as a Document Type!!

Because they are currently implemented in the same fashion in the backoffice using the same views...

But did you know?

A Composition Document Type CAN NOT be composed of another Document Type Composition???

Whereas a Document Type CAN be composed of a number of other different Document Type Compositions, but as soon as it is, it cannot be used as a Composition itself.

Do you see? they are conceptually two different things! 'currently' implemented by the same shared view and stored in the database in the same way - but with different business rules and concepts applied!

I'm trying to surface these concepts, by giving them separate names to hang the different concepts on.

So it hangs on whether you feel, when you right click Create Document Type that the distinction between the two types of thing is immediately intuitive!

My argument is, it is not!

You want people to understand when they right-click Create Document Type - what are the 'building block' options available to me? What are the concepts? at this point in the transaction, the user is focussing on the 'outcome' and not the 'delivery mechanism' - they are not thinking - 

"I wonder how these options are stored in the database - they better not be tricking me! I will immediately stop in my tracks if I think for one second that the way to create a composition is identical to the way to create a Document Type - I'd much rather not know about compositions until after I've implemented my Document Types if it happens that they are implemented in too similar way!"

The same argument could be made against the Element Type option too - hey it's just the same as a Document Type but with Is Element Type ticked - what a swizz I have been tricked.

Same with Document Type With Template - How annoying - it's the same implementation they've just created and picked a Template with the same name for me, what a swizz I could have done that manually!

So there is an argument to be made about having only two options one called 'Document Type'  and one called 'Folder', it will be simpler, and the suggestion is people will 'just' be able to use their intuition to immediately understand the nuances and variations of Document Type conceptual differences.

Really though users are concerned with creating the thing they have chosen to create, and are not fixated on comparing the implementations!

The menu is the perfect place to display and introduce the concepts, and the order of them is important too, conceptually!

For me, and the people I have taught to use Umbraco, having all the different concepts listed here as 'different options' is really extremely helpful, (do try to think from the perspective of somebody using Umbraco for the first time and who are new to the concept of creating a Document Type). 

It's important to understand that a Document Type is different to a Composition, it's not important to compare how they are currently implemented.

What works well with this UI is that before you create your first Document Type, you are made aware of the concepts - the fact composition 'is a thing', and the existence of Element Types! - I think descriptive text for the different options can always be improved, but by doing it this way, with one option for each different concept, you expose these 'concepts' - the building blocks, and well, it becomes very intuitive!

Anyway, I am happy to reach a compromise, I will add an extra querystring parameter to the Composition option called 'IsComposition' and then they will DEFINITELY being doing different things and that should satisfy your concerns?

I keep saying 'currently' implemented because 'to me' it would be a great next step to 'hide' the 'Compositions button' from the View, if the IsComposition value is present on the querystring... because when creating a composition you do not need to ever press that button, and again it would help intuitively explain about the underlying difference in the concepts between a Composition and a Document Type - and more importantly it would also satisfy your users who 'compare' views and get upset if there is seemingly no visual difference between the implementation of two different options!

I had a whole another analogy about Apples and Oranges, and how they are implemented in the same way, but are eaten differently - but hopefully the above explains enough?  :-P

**Comment by nathanwoulfe** [comment]
As far as I know, the data-element attributes are used as hooks for creating backoffice tours. Might be some other uses, but that's all I'm aware of. 

Also, this PR is awesome. Will have a proper play with it, but based on that detailed exposition, I understand the rationale.

**Comment by marcemarc** [comment]
Aha thanks  @nathanwoulfe will have to fix the tour too!

**Comment by kjac** [comment]
@marcemarc please be a chap and keep a respectful tone here ❤️ I don't take offence easily, but others might feel somewhat offended by assumptions being made on their behalf.

I am perfectly aware of the concepts. My job here is to ensure the PR has been viewed from different perspectives, and thus I'm offering one.

No matter. This change improves the doctype create menu a lot and I'm happy to approve it once I have had a play with it (unless @nathanwoulfe beats me to it).

**Comment by kjac** [comment]
@marcemarc the change works perfectly. If you don't mind, I'll go ahead and add Danish translations for your new texts before completing the PR?

**Comment by marcemarc** [comment]
> @marcemarc please be a chap and keep a respectful tone here ❤️ I don't take offence easily, but others might feel somewhat offended by assumptions being made on their behalf.
> 
> I am perfectly aware of the concepts. My job here is to ensure the PR has been viewed from different perspectives, and thus I'm offering one.
> 
> No matter. This change improves the doctype create menu a lot and I'm happy to approve it once I have had a play with it (unless @nathanwoulfe beats me to it).

Hey kjac, it would be really great to jump on a call if possible, as I feel genuinely mortified that my post would have caused any upset to you, and I can assure that was not my intention. ❤️❤️❤️!  - I agree that glib and lighthearted expression and also the use of the rhetoric of ridicule and exaggeration when exploring and assessing an idea can often be misconstrued if you can't see the twinkle in the eye of the person using it. 

I can only assure you my tone here is playful, well-meaning and respectful to you as an individual based on our previous conversations (remember last year, my ridiculous isElementType video 'colored you impressed'), but I will revise that style in the future for our correspondence, as the style of the comment shouldn't ever distract the listener from the point being made!

Thank you for taking the time to make me aware of this.

I did genuinely feel from the evidence of your suggestions that you were not 'understanding this', and felt the burden was on me to explain in much greater detail... I feel awful that I got the wrong end of the stick in doing so - by saying 'this is what I think you are saying, this is what I am hearing from you, is that right?' I was hoping it would then allow you to say 'no not that, don't be so stupid and ridiculous marcemarc - I actually mean this....' - the intention wasn't to 'win the argument', stifle the debate and make you concede, but to expose why I might be missing your point in a lighthearted way.

We both want the best improvement for this menu - it's been over a year in the making, so I'm totally open to exploring further enhancement, and collaboration on this, if you have improvements to suggest - but again that sounds like a totally arrogant thing to say! - 'IF' - I don't mean that to sound 'passive-aggressive and challenging' - what I'm trying to say is it doesn't just have to remain how I've done it, because I've done it, and that's it - but I guess, I have also worked and thought hard about this over a long period of time, to get it to this point, so maybe I'm in that edgy overly precious state about the whole thing, where I just want people 'to get it', and like what I've done (so needy) - having been asked to contribute it.

Anyway, hopefully, you'll accept my apology, it's so difficult with reading intent and tone into text sometimes, for example, you have said 'please be a chap and keep a respectful tone here' - and I'm sure you don't mean that Men are more respectful in tone than Women, and that 'aiming to be more like a male figure', when speaking, is desirable in the Umbraco community - but see how it can be accidentally misconstrued? - I'm sure you are actually focussing on the word 'chap' in a dictionary sense of a 'friendly man' and your emphasis here is on the word 'friendly' and perhaps also because I am in the UK, it sounds a bit 'ye olde British' speak - and maybe you are not aware of the word's origins, and the connotations of condescension associated with its use - but if you are, and that is your intention, then consider me rebuked sire. **doffs cap, heads back t'mill**

**Comment by marcemarc** [comment]
> @marcemarc the change works perfectly. If you don't mind, I'll go ahead and add Danish translations for your new texts before completing the PR?

cool, yes, think I'll also need to test all the tours still work before it can be complete.

**Comment by kjac** [comment]
`Anyway, hopefully, you'll accept my apology`

No apology needed. I did not take offence, and I did get the playful tone. My remark was more in a general sense; hit me up on Slack next week and I can elaborate there, this isn't the place 😄 

`cool, yes, think I'll also need to test all the tours still work before it can be complete.`

Should've probably mentioned: I did test the "Introduction" and "Create document type" tours with this PR and they work just fine: 

image

I pushed translations to the PR; anything else you want to add to it?

**Comment by TimGeyssens** [comment]
So, any update on when this will be merged? Such an easy win for a lot of folks...

**Comment by TimGeyssens** [comment]
Hello @nul800sebastiaan ?

**Comment by TimGeyssens** [comment]
so @kjac is this pr ok? Or still waiting on changes?

**Comment by marcemarc** [comment]
I have rebased to resolve the merge conflict if that helps!

**Comment by TimGeyssens** [comment]
merge it like it's hot!

**Comment by nathanwoulfe** [comment]
@marcemarc, @kjac is this beast ready to go? Pinging @nielslyngsoe and @madsrasmussen in case they have any feedback/input given it's a reasonably large (and very awesome) change.

If everyone is in agreeance, I'm happy to test/review and merge.

**Comment by TimGeyssens** [comment]
Do it @nathanwoulfe !

**Comment by TimGeyssens** [comment]
and not sure mads is the guy to tag here since he isn't working on umb anymore...

**Comment by dawoe** [comment]
@TimGeyssens yes he does. He's back at HQ since this year.

**Comment by nielslyngsoe** [comment]
@nul800sebastiaan can we bring this one in for our talk tomorrow? Thanks

**Comment by TimGeyssens** [comment]
ah cool nice to see you back @madsrasmussen

**Comment by TimGeyssens** [comment]
> @nul800sebastiaan can we bring this one in for our talk tomorrow? Thanks

sweet keep us updated!

**Comment by nathanwoulfe** [comment]
One of the best parts of this PR:
image
Adds feature, removes LOC.

**Comment by TimGeyssens** [comment]
@nathanwoulfe what's not to love ;)

**Review by nathanwoulfe — APPROVED** [review]
Said it before, will say it again - this is really slick. Did have to put back the PostSave method on the ContentType controller, it was kinda important for saving changes...

I think this should really be marked as a breaking change due to removing the create collection endpoint. If the preference is to mark it obsolete, we can always put it back.

**Comment by bjarnef** [comment]
@nathanwoulfe I noticed with the latest changes in `v8/contrib` branch, that the button is on top on these items.

image

**Comment by nathanwoulfe** [comment]
@bjarnef same issue was in the create member dialog. I've fixed both in #9846.

**Pull request merged**
