### PR TITLE
U4-8734: Changes to allow custom anguar pages for two factor auth

### PR DESCRIPTION
**Pull request by steroberts89**
@Shazwazza These are my changes for what you discus here http://issues.umbraco.org/issue/U4-8734

Note i opted for 402 Payment Required instead of your suggested 407 in the case. This is because chrome does weird things for 407... it refuses to believe the server sent that down to it. (see https://bugs.chromium.org/p/chromium/issues/detail?id=372136 )

Thanks
Stephen

### CODE REVIEW

**Comment by Shazwazza** [comment]
We'll have look at starting this review next sprint, we'll keep you posted. Thanks!!

**Comment by PeteDuncanson** [comment]
@Shazwazza any update on this one or ETA?

**Comment by Shazwazza** [comment]
Part of the description for implementation was:

> Upon submitting the form it will send a request to the server. The AuthenticationController  will need to be updated to handle this logic - again should follow the same logic/principals found in the default ASP.Net MVC app template with a SendCode  action.

Can you tell me what you have done in your custom 2FA view and how that then interacts with Umbraco to log the person in?

**Comment by Shazwazza** [comment]
I've manually merged this in 5060e709d143f6b706bdfd7b553a9210d84f4723

**Comment by PeteDuncanson** [comment]
@Shazwazza glad it made sense and you got it merged in. @steroberts89 was a little sad you did it manually as it won't show up on his github account, does this count towards a contributor badge for Our for him? ;)

**Comment by nul800sebastiaan** [comment]
🥇 👍 https://our.umbraco.org/member/16348

**Comment by Shazwazza** [comment]
It had to be manually merged since it had to target a diff branch and wouldn't auto merge. Github just wasn't smart enough to figure out that the commits in this PR closed this PR, the commits are still in the umb history and this will show up on his Github

**Comment by PeteDuncanson** [comment]
@steroberts89 is currently doing his happy dance, thanks both for making his day :)

**Pull request closed without merging**
