### PR TITLE
Default parameter in ToSafeAlias / ToUrlSegment

### PR DESCRIPTION
**Pull request by JoseMarcenaro**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

This fixes #11173 

### Description
Provides a default value for the `IShortStringHelper shortStringHelper` argument in the simplest overload of `ToUrlSegment()` and `ToSafeAlias()` 

### Steps to test:

```
string urlSegment = "my document weird name & adiós".ToUrlSegment();
```

### CODE REVIEW

**Review by nathanwoulfe — COMMENTED** [review]
@JoseMarcenaro this makes sense, just want to check with @p-m-j that allocating the static helper is preferable to instantiating it when required in the new extensions?

**Comment by p-m-j** [comment]
:man_shrugging: might be nicer to service locate the registerd instance, probably a good candidate for the crossover slack channel.

**Comment by nathanwoulfe** [comment]
Hey @JoseMarcenaro, checked in with HQ and the preference here is to add the new extension in Umbraco.Web.Common/Extensions, and use service location to get the registered IShortStringHelper instance rather than instantiating a new object with the default config (as the registered instance may be different to the default).

[Here's a good example](https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Web.Common/Extensions/FriendlyUrlHelperExtensions.cs) of how this would work.

Hope you don't mind refactoring your PR 😃

**Comment by JoseMarcenaro** [comment]
Hi @nathanwoulfe  - thanks for the explanation, and of course you can dynamite my PR and build it the right way 😆

**Comment by nathanwoulfe** [comment]
@JoseMarcenaro no intention of dynamiting anything on your behalf - if you want to refactor the existing PR, I'm fine with merging it 😄

**Comment by emmagarland** [comment]
@JoseMarcenaro also, just as an FYI I have just updated the base to `contrib`.

I've noticed that `StringExtensions.cs` now has conflicts to be resolved. 

Emma 🙂

**Comment by JoseMarcenaro** [comment]
Hi @emmagarland thanks for contacting me.
This is a very old issue and I'm really not sure about the best action to take - please disregard this PR

**Comment by emmagarland** [comment]
@JoseMarcenaro thanks very much for the update and letting me know. 

Emma

**Comment by shearer3000** [comment]
hi - what was the end result here? can we use ToUrlSegment() without needing to pass in IShortStringHelper? thanks

**Comment by JoseMarcenaro** [comment]
@shearer3000 no you cannot - As far as I know, that option is not available

**Pull request closed without merging**
