### PR TITLE
Update styling of log viewer

### PR DESCRIPTION
**Pull request by skttl**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
I have updated the styling of the log viewer, so the message column gets a bit more space. When expanding a row, I have removed the spacing inside the expanded row, so the table containing information has more space and feels more connected to the parent row.

#### Before
firefox_2019-10-27_10-33-20
firefox_2019-10-27_10-48-08
firefox_2019-10-27_10-48-24

#### After
firefox_2019-10-27_10-49-08
firefox_2019-10-27_10-48-52
firefox_2019-10-27_10-49-30

### To test
Open the log viewer, make sure it looks like the "after" images.

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @skttl ,

Can you fix the merge conflicts?

Poornima

**Comment by skttl** [comment]
Hi @poornimanayar 

I have merged v8/contrib into this, and changed the base branch.

Also fixed the merge conflict :)

**Review by nathanwoulfe — CHANGES_REQUESTED** [review]
@skttl, I'm dragging up some old PRs, this looks good but curious as to why you chose to change buttons to links and removed the localization directives?

**Comment by skttl** [comment]
Hi @nathanwoulfe 

The buttons/links and localization directives weren't there when I originally did the PR, and I must have overlooked them when merging in c0b9cbd.

I can fix it in the coming days if you'd like :)

**Comment by nathanwoulfe** [comment]
@skttl that makes sense! No rush, just whenever you can - it's a good looking change, so makes sense to merge (even after a looong delay)

**Review by nathanwoulfe — APPROVED** [review]
Hey @skttl, I've fixed up the buttons/a changes and tidied up a couple of other minor UI issues introduced by merging latest. All good to go, will merge.

**Pull request merged**
