### PR TITLE
Added ContentApps for Members

### PR DESCRIPTION
**Pull request by robmaas**
This PR enables ContentApps for Members.

Both the Content and the Info ContentApps have been implemented as well.
Some additional work can be done on the content of those tabs, for example Infinite Editing is not yet working for the MemberType in the Info ContentApp.

It is possible to limit the visibility based on the memberType (both manifest and c# definitions), like so:

    "show": [
            "-member/testType",
            "+member/*"
        ]

**BREAKING**
Please note that this can be a breaking change for sites if they throw Exceptions like Core does, this is discussed in issue: #5843 
The way to fix these issues is to include a IMember case to the switch statements:

    switch (source)
    {
        case IMedia media:
            // dosomething(media);
            break;
        case IContent content:
            // dosomething(content);
            break;
        case IMember _:
            // don't show for member
            return null;

        default:
            throw new NotSupportedException($"Object type {source.GetType()} is not supported here.");
    }

Screenshots:
1: Default view (no custom ContentApps)
image

2: Added two custom ContentApps (1 from manifest, 1 from code)
image

3: Removed the (internal) Info ContentApp from code using:

    composition.ContentApps().Remove<ContentApps.ContentInfoContentAppFactory>();

image
Since there is only 1 ContentApp remaing (Content) it does not show.

---
_This item has been added to our backlog [AB#3417](https://umbraco.visualstudio.com/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/3417)_

### CODE REVIEW

**Comment by burstowemma** [comment]
Morning Rob! Glad to see that my talk helped someone. Wonderful work here. We'll take a look and let you know our thoughts. 

Also, fabulous documentation. You're a ⭐️ 

Emma

**Comment by emmaburstow** [comment]
Morning Rob! Glad to see that my talk helped someone. Wonderful work here. We'll take a look and let you know our thoughts.

Also, fabulous documentation. You're a ⭐️

Emma

**Comment by dawoe** [comment]
Hi @robmaas

I tested this one. Registering through package manifest works fine. Also setting which roles and membertypes the app can be shown on.

Registering through a content app factory broke for me. So I think this should be marked as a breaking change.

Maybe you can tweak the info tab a bit. It know it looks a bit strange with only the box on the right
member info tab

Also this box shows some info that is also displayed on the content tap (id, member type, etc).

My proposal would be to move some information that is currently on the content tab over there.
But I think we need input from Umbraco HQ on that.

I will see if I can get somebody to look at this.

Great addition by the way.

Dave

**Comment by robmaas** [comment]
Hi @dawoe 

Thanks, was thinking the same thing.
I'll wait for HQ's response on this before make any other changes.

Rob

**Comment by nul800sebastiaan** [comment]
Hi @robmaas - thanks for all the work here! I'm sorry for the late reply, we're quite overwhelmed with all the hacktoberfest contributions. 

I need to talk to some people at HQ for that Info tab, which does seem a little bit empty. I personally think the properties that cannot be changed by the editor should go there, like:

Failed Password Attempts
Is Locked Out
Last Lockout Date
Last Login Date
Last Password Change Date 

Seems like "information" to me that would belong on the "Info" tab.

**Comment by robmaas** [comment]
Hi guys, thank you for the feedback!
I will try to take a look at the suggested changes somewhere next week.

**Comment by robmaas** [comment]
Hi guys, finally gotten around to finishing this up.

I have moved the readonly fields to the Info ContentApp. It also does this (partially) automatically for custom readonly fields and renders those in their own tab in the Info ContentApp.

Some new screenshots:
**New Content ContentApp** (without readonly fields, the Data tab is a custom tab/field defined in the MemberType)
image

**New Info ContentApp**
image

**Comment by nielslyngsoe** [comment]
@robmaas looks good!

**Comment by nul800sebastiaan** [comment]
Hi there @robmaas,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing 🥇 

We have had another record breaking amount of PR's in both the CMS, Documentation, and other smaller public repositories. You can read all about the numbers in the [Umbraco Hacktoberfest round-up blog post](https://umbraco.com/blog/pr-team-update-november-2019-hacktoberfest-round-up/).

Due to the amazing work you and others in the community have been doing, we've had a bit of a hard time keeping up. 😅 While all of the PRs for Hacktoberfest might not have been merged yet, you still qualify for receiving some Umbraco swag, congratulations! 🎉 

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://docs.google.com/forms/d/e/1FAIpQLSc-K97Zl5k86cVebKWWqieLM4Fm_jCMGVdbQdYnq4IUJ7EvZg/viewform) :point_left: Please follow this link to fill out and submit the form, **before December 19th 2019**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before February, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Comment by nul800sebastiaan** [comment]
Thank again for the lovely work @robmaas - sorry for the delay! This looks great, works great and it's going to be fun to see what member apps might appear in the future! 👍

**Pull request merged**
