### PR TITLE
5989 - fixed focalpoint for infinite media picker

### PR DESCRIPTION
**Pull request by Malthebp**
### Prerequisites
Fix for #5989 

### Description
Fixed focal point in infinite editor not being used on the model of the media.

### CODE REVIEW

**Comment by ronaldbarendse** [comment]
It's probably a good idea to undo all the changes in formatting and skip the `package-lock.json` file. The only real changes seem to be:

https://github.com/umbraco/Umbraco-CMS/blob/070c499d8cc626e99d0a9cd91a8433c4810183f2/src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.controller.js#L483-L494

https://github.com/umbraco/Umbraco-CMS/blob/070c499d8cc626e99d0a9cd91a8433c4810183f2/src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/mediapicker/mediapicker.html#L102

**Comment by Malthebp** [comment]
@ronaldbarendse thank for your review. I have reformatted everything to look nice again and skipped the package.lock file. Hope it is fine now. :-)

**Comment by ronaldbarendse** [comment]
That's better indeed 👍 There a still some white-space changes, but that can be hidden when reviewing: https://github.com/umbraco/Umbraco-CMS/pull/5991/files?w=1.

Should be ready for HQ to review 😄

**Comment by Malthebp** [comment]
Is there any timeline for when a PR is going to be merged? 
Our customers are waiting for this to be fixed. :-)

**Comment by nul800sebastiaan** [comment]
Many apologies for the delay on this one @Malthebp 🙈 

I've finally found some time to try it out and and it's good to go! 👍 

Also: congratulations on your first merged PR for Umbraco-CMS - well done! I've added a shiny new contributor badge to your Our Umbraco profile https://our.umbraco.com/members/malthebp🏅

**Pull request merged**
