### PR TITLE
Changing title from availableItem.name to availableItem.alias

### PR DESCRIPTION
**Pull request by sebastiandammark**
So you can tell the difference between to DocumentTypes that are named the same

### CODE REVIEW

**Comment by warrenbuckley** [comment]
Hi @sebastiandammark 
Thanks for the PR and it looks simple enough to merge in, but to make sure we follow the process, can you please create an issue on the issue tracker http://issues.umbraco.org

This is so that we can easily create release notes & identify what things are contained in a release.

Once you have done this, I will do a quick test to confirm and then merge your first PR into the Umbraco core :)

**Comment by warrenbuckley** [comment]
After a second consideration a small update to your PR would be nice please.
Perhaps the format could be `Document Type Name (docTypeAlias)` so its clear what the relation is between the name of the document type & it's alias.

**Comment by nul800sebastiaan** [comment]
Hi @sebastiandammark - Before looking into this further, I wonder if you can clarify some more since I'm confused 🙂

- Where is this used? As far as I can see, it's used for picking grid editors when adding a new grid item
- Why would you name 2 document types the same (or 2 grid editors the same)?
- Do we really want to expose the alias of these items to the person trying to edit content? To me it seems like that is an internal detail that should never be relevant to content editors

**Comment by nul800sebastiaan** [comment]
In absence of feedback I'll close this for now. 😃

**Pull request closed without merging**
