### PR TITLE
U4-10722 fix in Dutch localization

### PR DESCRIPTION
**Pull request by MrCosmo**
issue: http://issues.umbraco.org/issue/U4-10722

Just a small fix in a Dutch localization error.

### CODE REVIEW

**Comment by ilhambo** [comment]
Thanks 👍

**Comment by ilhambo** [comment]
Hi,
I can't find you on Our Umbraco. If you could send me the link to your profile, I would be able to give you the Contributor badge.

**Comment by MrCosmo** [comment]
@ilhambo Thanks. My profile is: https://our.umbraco.org/member/271913

**Comment by ilhambo** [comment]
Look at that shiny new contribute badge on your profile! 
https://our.umbraco.org/member/271913

**Pull request merged**
