### PR TITLE
Clean up multiple textstring(repeatable textstring) view - 

### LINKED ISSUE #2933: Clean up multiple textstring(repeatable textstring) view
- Create a repeatable textstring property type in your document type
- You can notice that the layout is congested and can be made cleaner

image

### PR DESCRIPTION
**Pull request by poornimanayar**
Introduced some styling rules to make the view look cleaner

### Prerequisites

- [ ] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is: https://github.com/umbraco/Umbraco-CMS/issues/2933
- [ ] I have added steps to test this contribution in the description below

### Description
The multiple textstring datatype view is congested. I have introduced some styling rules to make it look neater. 
https://github.com/umbraco/Umbraco-CMS/issues/2933

**Existing**
image

**Proposed**
image

Fixes #2933

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Looks better @poornimanayar ! I don't know why there was all kinds of files added to the csproj file but I've removed them.

Just as a future tip: before you stage a file, try to see if you actually need to commit it's changes for your fix to work! 👍

**Comment by poornimanayar** [comment]
Duh! That was really careless of me @nul800sebastiaan Extremely sorry!

**Comment by nul800sebastiaan** [comment]
@bjarnef Not sure what happened after that one was merged but the before and after in Poornima's screenshots above could definitely be reproduced!

**Comment by nul800sebastiaan** [comment]
Looking at that one now, the "Add" button is also in the old style still? 🤔

Maybe your changes weren't merged correctly at all.. ☹

**Comment by nul800sebastiaan** [comment]
Yikes.. yes, somehow the changes to `property-editors.less` didn't make it in! I've re-applied them now, thanks for noticing mate! 👍

**Comment by bjarnef** [comment]
Thanks Seb! 😀😎🙋‍♂️🦄

**Comment by ronaldbarendse** [comment]
Should this not use the same style as the [prevalue editor](https://issues.umbraco.org/issue/U4-11071) or better yet like [`Our.Umbraco.PropertyList`](https://github.com/umco/umbraco-property-list)?

Our.Umbraco.PropertyList editor view

Going the `Our.Umbraco.PropertyList` route would also be a lot more flexible: that way you'd have multiple textstrings, numbers, dropdowns, etc. Maybe contact Matt and/or Lee about integrating this editor into Umbraco core? 👼

**Comment by bjarnef** [comment]
@ronaldbarendse I updated the styles to look a bit cleaner, but yes I agree we can adjust this further, so the styles is more consistent with the multivalues prevalue editor and e.g. like the styling in `Our.Umbraco.PropertyList` https://our.umbraco.com/packages/backoffice-extensions/property-list/

The delete icon could also use the `umb-confirm`. Not sure is we then should use the trash icon or text "Remove" as for other pickers.

Furthermore previously other pickers had the grey background, but it was removed as in this issue on old issue tracker https://issues.umbraco.org/issue/U4-11552 which gives some issues with closure.

@madsrasmussen should we use the grey background in this case? Should we use icon or text for delete/remove?

**Pull request merged**
