### PR TITLE
Added ReSharperTestRunner to KnownAssemblyExclusionFilter

### PR DESCRIPTION
**Pull request by Amalie-Wowern**
### Prerequisites

- [x] not sure how best to test this

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14598

### Description
i have added ReSharperTestRunner to KnownAssemblyExclusionFilter

### CODE REVIEW

**Comment by lauraneto** [comment]
Hi @Amalie-Wowern ,

Thank you for the pull request! 🙌
Someone from the Core Collaborators team will have a look at it soon. 👩‍💻

I also see it's your first PR to this repository, that's awesome!! #H5YR 🎉

**Comment by mikecp** [comment]
Hi @Amalie-Wowern , I wanted to have a try at your fix, but I'm not quite sure I know how to test this either 😅

Maybe @kedde could help us on this one since he has the correct setup to check if this fixes the problem?

Cheers!

**Comment by Amalie-Wowern** [comment]
Hi @mikecp 

Yes it would be nice if he would help :)

**Comment by nul800sebastiaan** [comment]
Thanks @Amalie-Wowern! While we haven't gotten any test results, this can't hurt so I've gone ahead and merged it, good work! 👍

**Comment by nul800sebastiaan** [comment]
Oh and your first PR too! Congrats on the contrib badge 🎉 https://our.umbraco.com/members/Amalie-Wowern

**Comment by umbracocommunity** [comment]
This pull request has been mentioned on **Umbraco community forum**. There might be relevant details there:

https://forum.umbraco.com/t/forum-todo-list-progress/363/1

**Pull request merged**
