### PR TITLE
Umbraco avatar component image fit fixed

### PR DESCRIPTION
**Pull request by arulprabakaran**
### Description
This PR changes the object-fit & object-position properties for umb-avatar component in backoffice to fix the avatar fit issue.

### Before
image

### After
image

### CODE REVIEW

**Comment by nathanwoulfe** [comment]
Hi @arulprabakaran if you could update the target branch for your PR from v9/contrib to v10/contrib, we can merge to 10 and  cherry-pick back to v9.

**Comment by arulprabakaran** [comment]
I have changed the target branch @nathanwoulfe  👍

**Comment by nathanwoulfe** [comment]
@arulprabakaran sorry to be a pest, but looks like the rebase included a previous v9 commit. Would you mind creating a fresh PR with only the CSS change?

**Comment by arulprabakaran** [comment]
@nathanwoulfe I have created a new pull request, so I'm closing this request.

**Pull request closed without merging**
