### PR TITLE
U4-8437 - Allow for property editors to be able to determine what values are indexed by Examine

### PR DESCRIPTION
**Pull request by lars-erik**
PropertyValueEditor can now return multiple XML elements for a field and have them indexed in lucene.

### CODE REVIEW

**Comment by Shazwazza** [comment]
This is all resolved in v8, see https://github.com/umbraco/Umbraco-CMS/issues/3531

**Comment by lars-erik** [comment]
404 on the issue tho

**Comment by Shazwazza** [comment]
not sure what you mean? this link works for me https://github.com/umbraco/Umbraco-CMS/issues/3531

**Comment by lars-erik** [comment]
Ah, no it's actually a 500 :O

**Comment by Shazwazza** [comment]
definitely not seeing any errors on those links

**Pull request closed without merging**
