### PR TITLE
Temp 5596 grid edit alttext

### LINKED ISSUE #5596: V8 - Grid - allow editing image alt text
Quick win - when adding an image control on the grid, editors can optionally provide alt text when selecting their image. What they can't do is edit that alt text without removing the image, reselecting, and providing new text.

Can be easily remedied by adding an additional input to the media grid view, below/above the existing one for the image caption.

Will have pull request shortly.

### PR DESCRIPTION
**Pull request by nathanwoulfe**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

Refer to #9681 for a fresh take on this PR - this was 18 months old, lot has changed since then...

### Description
Current editing flow when adding an image in the grid doesn't allow the editor to easily update the alt text - it is set when adding the image, and can only be modified by removing and re-adding the image, which means losing any value set for the caption.

This change modifies the grid media editor to show only the image (no more caption text), with two new buttons - one launching the media picker dialog to select a new image, the other opening the media picker details dialog to edit the caption and alt text.

The details dialog was previously inline in the mediapicker view, which made reuse impossible. I've split it out into a new infinite editor and made it available on editorService as .mediaPickerDetails(). With that change in place I've also updated the mediapicker to use the infinite editor when placing an image in the grid.

### CODE REVIEW

**Comment by nathanwoulfe** [comment]
This grew a little when I started looking through existing issues - were a few related to this change, so addressed them all. I can provide screen captures if anything needs visual explanation.

**Comment by emmaburstow** [comment]
Hiiii Nathan! 

Thanks for the PR. Lots to look at here. We'll do that and then shout if we need anything else from you.

Em

**Comment by nathanwoulfe** [comment]
Hiiii Emma! It's probably not as much as it looks - most of those commits are pretty tiny. Holler if you need me.

N

**Comment by nathanwoulfe** [comment]
Refer to #9681 for a fresh take on this PR - this was 18 months old, lot has changed since then...

**Pull request closed without merging**
