### PR TITLE
Netcore: Add package dotnet template and improved the templates

### PR DESCRIPTION
**Pull request by bergmania**
# Description
- Added new umbracopackage template, that is a simple template for package developers, that include the target file, and is ready to use `dotnet pack` for.

- Updated the existing template to add an option to make it a testsite for a package.

https://user-images.githubusercontent.com/1561480/112154178-4caad300-8be4-11eb-8669-d3f082c169f7.mp4

# Tests
- Build the templates (using .\build.ps1)
- Setup a nuget source to the `build.out` folder
- Install the new templates
   - `dotnet new -i Umbraco.Templates::9.0.0-alpha004`
- Usecase: Package with testsite
   1. Create a blank solution
   1. Create a new umbracopackage project (remember the name)
   1. Create a new umbraco project, and specific the name of the package in the field `PackageTestSiteName`
   1. Build
      - Expected result - The app_plugins/{packagename} folder is copied to the test site.
   1. Clean soltuion
      - Expected result - The app_plugins/{packagename} folder removed
- Solution
   1. Optional: Create a blank solution
   1. Create a new umbraco project, and leave field for `PackageTestSiteName` empty 
   1. Build
      - Expected result - The static umbraco content is copied into the project.
   1. Clean soltuion
      - Expected result - The umbraco and wwwroot/umbraco folders removed

### CODE REVIEW

**Review by nikolajlauridsen — APPROVED** [review]
Looks good to me, and tested with dotnet cli tool and everything seems to work as intended provided that the very final "Expected result - The app_plugins/{packagename} folder removed" is left over from a copy/paste, I'm guessing that it is seeing how the app_plugins folder doesn't get created when you leave the `PackageTestSiteName` empty  😛

**Comment by AndyButland** [comment]
Have clonsed this and followed the instructions for testing - works as described.

I was a bit confused by a couple of things though.

One small thing was just the use of the term "Umbraco solution" and "An empty Umbraco solution to get you started".  I guess i'm just used to an empty Visual Studio "solution" being actually empty.  So just might be best to use "project" or "web application" over "solution" here, e.g.:

_"Umbraco Web Application - An empty Umbraco CMS web application"_

Secondly wasn't sure about the expected result from the "Clean solution" - _the app_plugins/{packagename} folder removed_.  There doesn't seem to be a way to get this back following a rebuild, so not sure why this feature was added?

**Comment by bergmania** [comment]
When calling clean, it is expected that the umbraco folders are removed. If it is a testsite, it is also expected the app_plugin/{packageName} is removed

**Comment by bergmania** [comment]
Found one issue. The new template's umbraco version was not updated for nightly builds. That's fixed now.

The reason for the Clean target, is to be sure we can change these files in future versions.
I changed it a bit so we are very explicit about what to remove.

Now we remove:
- `~/wwwroot/umbraco/*`
- `~/umbraco/PartialViewMacros/*`
- `~/umbraco/UmbracoBackOffice/*`
- `~/umbraco/UmbracoInstall/*`
- `~/umbraco/UmbracoWebsite/*`
- `~/umbraco/config/*`

So we do not remove log files, modelsbuilder models etc.

**Comment by nikolajlauridsen** [comment]
Seems I was a bit too hasty testing this yesterday, I've done a bit more testing, and run into a weird issue. If I manually click "clean" then it will remove the expected files (it no longer removes logs, modelsbuilder models, database, etc), and when I then builds it readds the files as expected. If I just run a rebuild though, it removes the files, but then gives an error for each file it has to re add like: ` Microsoft.Common.CurrentVersion.targets(4858, 5): [MSB3030] Could not copy the file "C:\Users\nikol\Documents\Github\Umbraco\TemplateTest\PackageTest\TestSite\umbraco\UmbracoBackOffice\AuthorizeUpgrade.cshtml" because it was not found.`

**Pull request merged**
