### PR TITLE
15209 media picker shows incorrect date

### PR DESCRIPTION
**Pull request by nagolucky18**
### Prerequisites

- [X] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes [15209](https://github.com/umbraco/Umbraco-CMS/issues/15209)

### Description

This pull request contains the following changes.

- In mediapicker.controller.js, remove the 'Z' character representing UTC+0 timezone to ensure that "Last Updated" date for media picker shows time in local user's time zone.

Steps to test (taken from main issue body): 

1. Ensure SQL Server is Database (not SQL Lite)
2. Upload a file to "Media"
3. Create a document type, with "Allow as Root" enabled and "Media Picker" property.
4. In "Content", create item and click the "Add" button.
5. In the dialog choose list view
6. Notice that date is as expected as per your local time zone.
7. (Optional) Repeat 1-6 for other database types to ensure that date is still correct for timezone.

**A note about this change:** From debugging, it looks like the last update date time is correct, however the 'Z' is appended because I think that the user timezone is based in UTC+0 as there are many calls to DateTime.UtcNow in UserRepository.cs and other database code. The fix above will mask this issue but really, any media uploaded will still technically have a last updated string that is in UTC+0.

### CODE REVIEW

**Comment by bjarnef** [comment]
I haven't had a closer look at this, but I think we should use `dateHelper.getLocalDate()` to format the date based on backoffice use locale/language like most other part on the UI.
https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js#L709

**Comment by nagolucky18** [comment]
> I haven't had a closer look at this, but I think we should use `dateHelper.getLocalDate()` to format the date based on backoffice use locale/language like most other part on the UI. https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/listview/listview.controller.js#L709
> 
> Something like this:
> 
> ```
> item.formattedUpdateDate = dateHelper.getLocalDate(item.metaData.UpdateDate, currentUser.locale, "LLL");
> ```

Thanks! I'm relatively new to contributing and didn't know that this existed. I'll check it out.

**Comment by nagolucky18** [comment]
dateHelper.getLocalDate() is now used to format date.

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Hi @nagolucky18 ,

Thanks for this PR! I have tested your fix and it works perfectly, so let's merge it and get dates displayed correctly  😁🎉

Cheers!

**Pull request merged**
