### PR TITLE
Remove legacy Instagram oEmbed provider

### PR DESCRIPTION
**Pull request by ronaldbarendse**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9155.

### Description
The Instagram oEmbed endpoint will be deprecated on October 24, 2020 and return an error code 400. This makes the current Instagram oEmbed provider useless and because the new endpoint requires configuring tokens, can't be fixed without requiring additional (site/environment specific) configuration.

This breaking behavior can already be tested by adding `breaking_change=oembed` as query string parameter (see links in related issue), which can be done by adding this to the current `RequestParams` property of the provider. This will result in the 400 error and not returning the embed HTML markup.

After applying this PR, the Instagram oEmbed provider is removed and will not recognize the instagram.com/instagr.am URLs anymore, skipping the needless request to the API endpoint.

### CODE REVIEW

**Review by nathanwoulfe — APPROVED** [review]
@ronaldbarendse I see no issues with this - it's a breaking change, technically, but the deprecation of the entire oEmbed endpoint is also a breaking change, so I think this becomes a breaking breaking change. Or a breaking change breaker.

Existing sites won't be any more broken by removing this than they are already, given we've past the Instagram deprecation date.

**Comment by bjarnef** [comment]
Would we implement the new Instagram oEmbed provider instead as mentioned here?
https://developers.facebook.com/docs/instagram/oembed-legacy/

The new one:
https://developers.facebook.com/docs/instagram/oembed
https://developers.facebook.com/docs/graph-api/reference/instagram-oembed/

Looking at the registred providers it doesn't look like we have a Facebook oEmbed provider either:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Runtime/WebInitialComposer.cs#L271-L284

https://oembed.com/
https://developers.facebook.com/docs/plugins/oembed/

**Comment by bjarnef** [comment]
Actually it seems there has been made some changes recently:
https://github.com/iamcal/oembed/issues/468
https://github.com/iamcal/oembed/pull/470

where the new https://graph.facebook.com/v8.0/instagram_oembed API endpoint has been added.

**Comment by nathanwoulfe** [comment]
From the discussion in #9155, there's a fair bit work left for devs to implement the new embed (active, approved Facebook app for starters), whereas the deprecated embed was essentially plug n play. 

I think the additional work required to set up the new embed negates the benefit of having it out of the box in the backoffice. That's my take, at least.

**Pull request merged**
