### PR TITLE
Bugfix: #14481 - Landmark roles missing

### LINKED ISSUE #14481: Landmark roles missing
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

When trying to navigate the CMS using a screen reader, I cannot easily jump between the major parts of the interface (top menu, content tree, editing pane, ...). 

### Specifics

Landmark roles should be applied to all of the major parts of the page, according to best practice.
The easiest way to fix this would probably be to add appropriate landmark roles. 
Something like this:
`role="banner"` for the "hideBackofficeLogo" div
`role="navigation" aria-label="main menu"` for the "applications" div
`role="search"` for the "global-search" div
`role="navigation" aria-label="content tree"` for the #navigation div
`role="main" aria-label="edit panel"` for the ".umb-editor" div
...

Or, at the very least, the editor pane should begin with a heading for screen reader users, something like this `<h2 class="sr-only">Editor panel</h2>`

### Steps to reproduce

Log in to Umbraco. Use a screen reader. Try to navigate between landmarks. Not possible, because there are no landmarks.

### Expected result / actual result

Should be easy to list the landmarks present on the page.

### PR DESCRIPTION
**Pull request by BatJan**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #14481

### Description
I've added the appropiate HTML elements and the roles mentioned in the created issue. It might seem weird to add `<main role="main">` since the landmark is baked into the `<main>` element itself but since perhaps not all screen readers support the semantics properly it might be better to be explicit and add the role as well. This goes for most of the changes commited in this PR.

I can't really showcase anything here since these are all HTML changes that don't affect the visuals really :-)

### CODE REVIEW

**Comment by bjarnef** [comment]
From my knowledge the semantic HTML elements like `<main>` and `<nav>` doesn't need to landmark roles.

> The [<main>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main) element has a role of main. Developers should use semantic HTML — in this case [<main>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main) — over using ARIA.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/main_role

**Comment by BatJan** [comment]
> From my knowledge the semantic HTML elements like `<main>` and `<nav>` doesn't need to landmark roles.
> 
> > The  element has a role of main. Developers should use semantic HTML — in this case  — over using ARIA.
> 
> https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/main_role

In theory it should not be necessary to use role when using the proper element. But some screen readers might not recognize the meaning of the element/support it but will support the role attribute. So it’s kind of a graceful degradation 😊

**Comment by bjarnef** [comment]
@BatJan do you have an example of a screen reader which doesn't understand these?
They really should if they follow the HTML5 specification.

**Comment by BatJan** [comment]
@bjarnef I'm afraid that is not really possible for me to do, since there are many out on the market and other assistive technologies can depend on landmark roles as well, which is why I think there is no harm in using both. It's not an uncommon pattern and it does not do any harm. One thing is specs another thing is the reality of how things are implemented in the software whether it's a browser, screen reader etc. 😊

**Comment by bjarnef** [comment]
There may be some not so modern technologies, which doesn't fully understand `<main>` element 
https://stackoverflow.com/a/19596437

But I guess the modern technologies do.
Maybe someone has made a research about this or some if the popular assistive technologies could be tested 🙂

**Comment by BatJan** [comment]
@bjarnef wow! Just realized that <main> was added to the spec 10 years ago! It feels like yesterday to me - Time flies! But you appear to be very correct that we can in fact skip the pattern of also adding the role attribute to the landmark elements since all browsers now properly support it at least. So I guess it would be ok to remove them. I'll update the PR. But at a later stage we might need to add the role attribute in case it turns out some assistive technology for whatever reason has not adopted to the spec. And there is a lot of ways to browse the web out there 😅

**Comment by BatJan** [comment]
@bjarnef yeah the attribute can co-exist on the element and does absolutely no harm. Merely graceful degredation.

**Comment by mikecp** [comment]
Thanks @BatJan for this fix and thanks @bjarnef for the extra insights 👍

This will be checked soon by one of the core collaborators.

Have a nice week!

**Comment by emmagarland** [comment]
Hi @BatJan!

Thanks again for this PR. I started to review it, but noticed the new conflict (which I couldn't auto-resolve) and so I've pushed a change to resolve this. If you get chance, please could you check the change I made is ok (in the `en.xml`?)

After that it will be all good to review and merge!

Thanks,

Emma

**Pull request merged**
