### PR TITLE
Faster cache key generation

### PR DESCRIPTION
**Pull request by nzdev**
Reduce the number of string concatenations required to generate cache keys

### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description

CacheKeys are still the same.
In the future it may be more optimal to use shorter keys, especially for Nucache.PropertyCacheValues as the size of the cache key can easily exceed the size of the value cached.

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi @nzdev 

Thanks very much for your faster cache key generation PR!

I ran some tests using the methods in LinqPad to compare the string generation with the new way vs the existing way. All seem to output the same, except for `NuCache.ContentCache.Roots` and `NuCache.MediaCache.Roots` (`D` and `P`), where I noticed that there were two colons output like `::` instead of `:` as it is currently. I updated the relevant code in your branch to keep it the same, just so you know why I changed it.

It is clear from the PR that there will be fewer operations happening to create the cache key strings. 

My only question would be, do you happen to have any benchmarks to show how this improves performance? No worries if not, just if you had them already :)

Thanks, 

Emma

**Comment by nzdev** [comment]
Hi @emmagarland . I don't have benchmarks at hand. Most of these reduce the number of string concat operations by 1, reducing memory allocations. For the docs/media root key, this is now zero allocation. Now that the key generation is a bit simpler, it should be easy enough to later further improve this using string.Create() to create the strings.

**Comment by emmagarland** [comment]
Thanks @nzdev, this has now been merged! 🙌

**Comment by nul800sebastiaan** [comment]
Cherry picked for 10.5 in 7c77fd1ca9e2a8c7049506e10734d01a3a8a2531

**Pull request merged**
