### PR TITLE
added Ukrainian language

### PR DESCRIPTION
**Pull request by mykolagorbatenko**
I have added Ukrainian language support.

I have made Ukrainian translation according to Language to Language Files & Localization article because Umbraco doesn't have Ukrainian language localization.
There is project for Ukrainian government institution where Umbraco solution is used. This is why I need to have Ukrainian language support.
Ukrainian language should be available in user profile dropdown. User could see Ukrainian interface after language selection.

### CODE REVIEW

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Hi @mykolagorbatenko,

Thanks a lot for this great addition! A whole new language at once, this is amazing 👍😁

And congratulations on your first PR for the Umbraco CMS 🎉
If you provide us with your account name on our, I'm sure that @nul800sebastiaan will be super happy to assign our shiny contributor's badge to you 🥇

And we'll be looking forward to the next ones  😉

Cheers!

**Comment by mikecp** [comment]
Hi again @mykolagorbatenko ,

Just for your info I saw that there were some English texts remaining in the UI after switching to Ukrainian, and when comparing the length of the ua.xml and en.xml (which is the "root" file), they are quite different: the en.xml file is much longer. I just wanted to let you know in case it is very important for your project that all texts appear in Ukrainian, and maybe new labels came into the en.xml file after you copied it for the Ukrainian translations.

Cheers!

**Comment by mykolagorbatenko** [comment]
Hi @mikecp ,
My name is Mykola Gorbatenko.
Thank you for your approval and investigation.
I am going to add missed translations as soon as I can.

**Comment by nul800sebastiaan** [comment]
Cherry picked for 10.5 in 6be8d2e88511d3bdbf684ebcf184fac4bb5767af

**Pull request merged**
