### PR TITLE
Umbraco-CMS.Accessibility.Issues#18

### PR DESCRIPTION
**Pull request by rammi987**
### Prerequisites
If there's an existing issue for this PR then this fixes ](https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/18)

### Description
Steps to replicate:
1) Open search modal in the top navigation (top right)
2) Modal will appear (modal is missing modal trap)

Now the focus is trap and will never escape.

### CODE REVIEW

**Review by mikecp — APPROVED** [review]
Hi @rammi987 ,

Thanks for this fix, I have just checked it and the modal now works as expected when using the tab key  👍
So let's not wait more and merge this right now 😁

**Comment by mikecp** [comment]
Oh, and this is your first contribution to the CMS, congratulations!! And thanks 😉
If you leave us your account name on Our, @nul800sebastiaan will be happy to assign our shiny contributor's badge to your profile 👍🥉
I'll be looking forward to your next one (which I think is already there waiting for us if I saw correctly 😊)
Cheers!

**Comment by rammi987** [comment]
@nul800sebastiaan @mikecp https://our.umbraco.com/members/rammi987/

**Comment by nul800sebastiaan** [comment]
Thanks again and congrats on your first contribution @rammi987! Your badge has been added! 👍

**Pull request merged**
