### PR TITLE
Feature: Variant Permissions (Readonly access)

### PR DESCRIPTION
**Pull request by madsrasmussen**
This PR makes it possible to set specific languages/variants to be readonly.

### Read-only access for languages:
We have added a new area on a user group where it is possible to limit access to specific languages. If no languages are added to the list the user will have access to everything.

Screenshot 2022-06-22 at 13 22 49

### Read-only properties
If the user have read-only access to a language/variant, they will see Property Editors in readonly mode. That means it is possible to interact and copy values from a Property Editor, but it is not possible to update/remove the values.

We have introduced a new configuration in a Property Editor Manifest, where you can specify whether a Property Editor has implemented and supports a readonly mode. If a Property Editor doesn't support readonly mode, we add an overlay on top of the Property Editor that prevents all interaction.

```json
"propertyEditors": [
  {
    "alias": "My.PropertyEditor",
    "name": "My Property Editor",
    "editor": {
      "view": "/App_Plugins/MyPropertyEditor/MyPropertyEditor.html", 
      "supportsReadOnly": true​
    }
  }
]
```

### Prevent Save and Publishing actions
If a user doesn't have write access to a language/variant we prevent all save and publishing actions by filtering the languages from the possible options in the corresponding dialog. It is still possible to save, publish, schedule, etc. any other language/variant.

### Editing invariant/shared properties
Until now it has only been possible to edit invariant/shared properties on the default language. We have added the possibility to edit invariant properties on all languages/variants a user has write access to.

The feature can be enabled through `appsettings.json`:

```json
"Umbraco": {
  "CMS": {
    "Security": {
      "AllowEditInvariantFromNonDefault": "True|False"
    }
  }
}
```

_Pop over to "unlock" and edit the value. The Popover is visible when the property is hovered or has focus._
Screenshot 2022-06-22 at 13 45 24

### Culture and invariant/shared labels on properties
We have introduced new culture/shared labels on properties to make it more clear where value comes from.

For invariant properties we used to have a label that explained that the value was inherited from the default language. It is now possible to allow editing a value from any variant that makes the label confusing. We now make it clear that the value is "shared" across all languages.

_A label for a variant property that shows the current culture. The label is visible when the Property Editor is hovered or has focus._
Screenshot 2022-06-22 at 13 24 40

_A label for an invariant property that shows it's shared. The label is visible when the Property Editor is hovered or has focus._
Screenshot 2022-06-22 at 13 25 35

### CODE REVIEW

**Comment by bergmania** [comment]
Found an issue doing test:
- The languages (+ sections) on user groups are not marked as dirty, so you do not get a warning when leaving the page

missing dirty

**Review by bergmania — CHANGES_REQUESTED** [review]

**Comment by nielslyngsoe** [comment]
@madsrasmussen I found one issue with the Media Picker (Legacy, v2.), Its regarding the 'Remove all'-property action which is still available and works, through my user does not have access to edit the current variant culture.

For comparison, I have here a screenshot with MediaPicker v.3 and v.2 below:
image

**Comment by Zeegaan** [comment]
@madsrasmussen While testing the backend for the hasAccessToAllLanguages toggle and trying to save a userGroup, I noticed that we're not yet sending the hasAccessToAllLanguages to the backend, here is the request we're currently sending when saving a UserGroup:
image

**Comment by Zeegaan** [comment]
> @nielslyngsoe This is now fixed. When fixing this I noticed that the Legacy Media Picker is missing "supportsReadOnly". Can you have a look at that @Zeegaan ?

@madsrasmussen This should now be fixed, but please double check 👍

**Comment by nul800sebastiaan** [comment]
Marked this as breaking as it could hide some things for package developers as explained in this issue: https://github.com/umbraco/Umbraco-CMS/issues/12989

**Comment by creativesuspects** [comment]
I've just installed a clean 10.2.1 project. Any reason why I'm not seeing the culture and invariant/shared labels on properties? And when I want to edit a shared property I only see a green 'Edit' button, no '{propertyname} is shared across all languages warning'.

image

These new features were visible in the [Unboxing Umbraco 10.2 video](https://www.youtube.com/watch?v=3Z4Quq82FDE).

**Pull request merged**
