### PR TITLE
Member picker value converter

### PR DESCRIPTION
**Pull request by hkooiker**
better null checking and renamed source to inter in ConvertIntermediateToObject. 
this more in line with the ContentPickerValueConverter.

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks @hkooiker! Unfortunately messing with the signature of a public method is not going to work, if someone is using named parameters (`ConvertIntermediateToObject(owner: content, propertyType: this, referenceCacheLevel: cacheLevel, inter: myObject, preview: isPreview)`) we'll break their code and they will need to fix it. 

It's "just" an unfortunate name slip-up that we'll need to live with.

**Comment by nul800sebastiaan** [comment]
@hkooiker I've reverted the name change for now but happy with the added null check! 

Congrats on your first merged PR for Umbraco-CMS! Always happy to get new contributors, well done! 🎖️ 

Am I correct in assuming this is your profile on Our Umbraco? https://our.umbraco.com/members/id:277817/ - if so I will add that coveted contributor badge to your profile as well.

Thanks again!  👍

**Comment by hkooiker** [comment]
@nul800sebastiaan Yes, that's my profile on Our Umbraco!

Thanks for the merge.

**Comment by nul800sebastiaan** [comment]
Awesome, contributor badge added! 👍

**Pull request merged**
