### PR TITLE
Fix typos in Danish translation

### PR DESCRIPTION
**Pull request by larssg**
Fixes a couple of typos in the Danish translations

### CODE REVIEW

**Review by abjerner — APPROVED** [review]
Thanks @larssg - og godt spottet 👍

**Comment by abjerner** [comment]
And now it's merged. Congrats on your first contribution to Umbraco 🎉 

Do you by any chance have a profile on [Our Umbraco](https://our.umbraco.com/)? As a token of appreciation, and if you share the link to your Our profile here, we'll add a shiny contributors badge to your profile 😉

**Comment by larssg** [comment]
@abjerner Awesome! I do: https://our.umbraco.com/members/larssg/

**Comment by nul800sebastiaan** [comment]
Sorry for the delay @larssg  and congrats with your shiny new contributor badge on Our! https://our.umbraco.com/members/larssg/ - Thanks again! 🥇

**Pull request merged**
