### PR TITLE
v8: umbCheckbox and umbRadiobutton fixes

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
This PR cherry picks a few commits merged to `v8/dev` in https://github.com/umbraco/Umbraco-CMS/pull/6258

We should probably also change this comment in docs from `<code>id</code>` to `<code>input-id</code>`.

It also seems the documentation needs to be updated since none of these components are shown here https://our.umbraco.com/apidocs/v8/ui/#/api

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef, you did beat me to it! 😁

I don't think the docs need an update, they are correct: the `id` attribute will be set, there is no `input-id` attribute. 🙂

**Comment by nul800sebastiaan** [comment]
_Oh, and yes: we need to deploy the new docs.. it's on the list_

**Comment by nul800sebastiaan** [comment]
Hmm, something is missing from both this and the #6258 PR. Currently, changes to checkboxes are not being saved at all. Radiobuttons work fine. Can I get you to have a look at that please @bjarnef ?

**Comment by bjarnef** [comment]
Any specific places where it doesn't save checkbox changes? In packager it should save the changed selections when hitting save button?

**Comment by bjarnef** [comment]
@nul800sebastiaan the packager seems to save the selected checkboxes.



But it seems there is an issue in checkboxlist property editor.

**Comment by bjarnef** [comment]
@nul800sebastiaan the model passed in to `onChange` function is no longer an boolean, but an object.

So this condition is not equal true: https://github.com/umbraco/Umbraco-CMS/blob/b1674235e936401e9884364fb97eea3931518344/src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.controller.js#L81

```
 function changed(model, value) {
     console.log("changed", model, value);
     ...
}
```

image

**Comment by bjarnef** [comment]
@nul800sebastiaan it seems it is fixed now in this PR https://github.com/umbraco/Umbraco-CMS/pull/6345

I guess Angular was a bit confused by the `vm.onChange()` in the view and the callback with same name.

**Pull request merged**
