### PR TITLE
U4-11168 - Replace document type colour selector with colour picker

### PR DESCRIPTION
**Pull request by OwainWilliams**
Hover over each colour and you get a useful title showing what the colour is. 
image

Once you select the colour, it changes all the icons and also has a shadow behind it to show that is the colour that you've selected. 
image

### CODE REVIEW

**Comment by callumbwhyte** [comment]
Congratulations on your PR, I love this change! 👍

I have a couple of pointers to hopefully improve the chances of this getting merged :-)

1. I don't suppose the files in `build/_BuildOutput` are supposed to be committed to the repo as they're the output of building the project. No fault of your own - there should probably be a rule in the `.gitignore` file for the project but there doesn't seem to be... (maybe a bug?) Same goes for `src/package-lock.json` which should probably also be removed.

2. In cases where we're replacing code it probably best to just remove it from the repo, rather than leaving it commented out which leaves mess in the project. As we have source control it's easy to recover if we need :-) In this case, lines 52-96 in `iconpicker.html` could probably be removed.

3. To keep the code clear and maintainable, I'd personally move the `.button` CSS out of the HTML file and into the `umb-iconpicker.less` file in the Umbraco.Web.UI project. Perhaps adjusting the name to of the `.button` CSS class to be inline with the others in that file would be good too

Just my own views of course, and HQ may think differently :-)

**Comment by OwainWilliams** [comment]
great comments @callumbwhyte - I'll make the changes and resubmit

**Comment by callumbwhyte** [comment]
No need to resubmit, just commit to your branch and it will update 👍

**Comment by OwainWilliams** [comment]
Pushed to the wrong PR

**Pull request closed without merging**
