### PR TITLE
V8: Use a pretty overlay dialog when deleting users

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5464

### Description

This PR replaces the system confirm dialog with the custom Umbraco one when deleting users:

delete-user-confirm

The PR introduces `dialogService` which will serve as a place to put generic user dialogs, so we don't have to write all the boilerplate code every time we need a generic dialog (for now `dialogService` only includes `confirmDelete`). If this PR is merged, #5357 should be updated to use `dialogService` for item deletion confirmation in Nested Content.

#### Tips for testing

The easiest way to test this is to create a new user *without logging it in*. Then edit the user and hit "Delete User" 😄

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @kjac 

Thanks for this (and thanks for that tip!). This seems like a better approach so might be worth changing   #5357 as suggested. Anyways, we'll take a look and let you know if we need anything from you.

Em

**Comment by bjarnef** [comment]
@kjac not sure if we should have another service to open dialogs/overlays since we already have `overlayService` to open these dialogs/overlays, so it is a bit confusing whether to use `overlayService` or `dialogService`. Can't overlayService have default views to use instead or functions to re-use? E.g. for infinite editing we can re-use `mediapicker` view or define a custom view.
And instead of a `confirmDelete` function why not a more generic name like `confirm` in traditional javascript. You might want to confirm something that should not delete, but create, update or something else than delete.

**Comment by kjac** [comment]
@bjarnef I tried creating a generic dialog with default translations in `overlayService` when I did #5357, but it ended up in circular dependencies on `localizationService`, so that was a no-go. Thus the need to introduce a new service. It wasn't my first choice either, but I prefer having the boilerplate code on one place.

As for the naming... I did actually name the method `confirm` at first, but while reviewing my work I realized the dialog defaults to "Yes, delete" on the submit button. My first thought was then to change this to "Yes" and let the caller override the submit button label with the "Yes, delete" localization key. But thinking a bit more about it, having a confirmation dialog when deleting things is a pretty common operation (e.g. Nested Content items, as mentioned above). In other words, with a `dialogService.confirm()` method we'd have to supply the same override to the submit button label everywhere we need to delete stuff, and that doesn't seem right. So I renamed it to `confirmDelete`. When the need arises it's super simple to extend `dialogService` with a generic `confirm` method as well.

**Comment by bjarnef** [comment]
@kjac I still feel we should only have `overlayService` to deal with these overlays. I v7 there was both dialogService and umbConfirm to open dialogs/overlays and dialogService was then deprecated and later removed.
I think we can have either the option to use default views in overlayService or functions to open these type og overlays. But I think it should be possible to use default views or functions like in infinite editing (editorService), where we only have this single service.

**Comment by kjac** [comment]
@bjarnef I don't know what to tell you 🤔 a default dialog needs translations. Overridable ones, that is, which means you need to have `localizationService` in play. Soon as you add `localizationService` to `overlayService`, Angular throws up:

image

**Comment by bjarnef** [comment]
@kjac it could have some generic dialogs to re-use, most of the delete overlays we have now are identical. If we need more custom text, details, etc. in an overlay, we can always add a custom view as we already can. Adding a new `dialogService` which basically just add some functions to call the overlayService. I just think this add an extra layer and we have two different services to manage overlays/dialogs instead of just having one service for dealing with overlays.

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by nul800sebastiaan** [comment]
Did you forget about this one when submitting https://github.com/umbraco/Umbraco-CMS/pull/6319? 😅

**Comment by kjac** [comment]
Oh my gosh that's idiotic 🤦‍♂️

**Pull request closed without merging**
