### PR TITLE
Enables list view column templates

### LINKED ISSUE #5591: Allow custom filters on columns in list view
Similar to how you can modify the label of nested content items, it could be nice if you could make javascript filters for the display of property values in columns of the list view.

For non-simple editors the result today is like this:
billede

Adding a simple filter like `{{ this[0].value }}` could make this one write Dunlop.

Or if you are having a large textarea as a column in the listview, you could do like `{{ this.substring(0,20) + '...' }}`

(assuming `this` is the value of the column)

### PR DESCRIPTION
**Pull request by skttl**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #5591

### Description
This PR adds the template functionality known from Nested Content to the values of columns in list views.

In the columns setting of the list view a new column for templates is added.
billede

Here you can type your template, or filter. The value of the column is in the `value` variable.

On the list view the template is now used to show the column value in stead of the raw data value.
billede

For demonstration purposes here is a screenshot of the above list view *without* templates
billede

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Sweet, we'll have to give this a look soon, thanks so far!

**Comment by elit0451** [comment]
Great work @skttl :raised_hands: Tested and it works great!
Merging 👍

**Comment by Rizen-Kris** [comment]
when I use {{ value | ncNodeName }} for a multimode tree picker I get this.. "loading..."

image

**Comment by skttl** [comment]
Try {{ value[0] | ncNodeName }}

**Comment by Rizen-Kris** [comment]
I tried that and then got this:
image

**Comment by skttl** [comment]
You should probably open up a new issue about this...

**Comment by Rizen-Kris** [comment]
I found a little more info and opened a separate issue here:
#9145

**Comment by alecrt** [comment]
Same issue here, Umbraco 8.14

**Pull request merged**
