### PR TITLE
Ensure backward compatibility in listview edit with custom listview layout

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10016

### Description
This PR fixes the changes introduced in https://github.com/umbraco/Umbraco-CMS/pull/9026 which broke  backward compatibility using custom listview layouts.

Not sure why it need to pass in the entire scope as second parameter and not just the options though, but we probably can't change that now without making another breaking change. It would probably be simpler with something like this:

```
const options = {
      id: 1234,
      useInfiniteEditor: true
}
```

The rest is available from `item`, but maybe it has something to do with it also need `scope.getContent(scope.contentId)`.

To make in easy to test I have create a custom listview for people in default starter kit. Unzip this "ListviewLayouts" folder to `App_Plugins` and configurate a custom listview for the "people" using the following path: **/App_Plugins/ListviewLayouts/grid-people/grid.html**

[ListviewLayouts.zip](https://github.com/umbraco/Umbraco-CMS/files/6172556/ListviewLayouts.zip)

image

**Before**

chrome_mLKtQRzRbU

**After**

zvdTwoh0tf

### Test notes

- Check clicking link works for both standard list and grid + custom layout
- Enabled "Edit in Infinite Editor" in listview configuration and ensure both standard list and grid open infinite editor. The custom listview would do that, but if modifying the listview controller with this following it handle this as well:

```
$scope.gotoItem = function (item) {
    listViewHelper.editItem(item, $scope);
};
```

### CODE REVIEW

**Comment by bjarnef** [comment]
I wonder if the "Edit in Infinite Editor" also should work with the old format:

```
$scope.gotoItem = function (item) {
    listViewHelper.editItem(item);
};
```

Currently the toggle has no effect on the listview layout unless you modify the implementation in your custom listview layout.

**Review by nathanwoulfe — APPROVED** [review]
@bjarnef this works nicely - I agree it would be good to not have to pass the entire scope object into the listviewhelper, but it is due to needing both the options object and the getContent method. I guess too by passing only what's required, it would be possible for implementors to pass a different method for getContent, which would then cause issues.

getContent is originally passed into the umbListViewLayout directive, I'm guessing to ensure the displayed values in the list reflect any changes made in the infinite editor. 

So yeah, while it's not ideal given it will required updates in custom listviews to use infinite editing, I think your fix here is sensible since it stops anything from breaking.

**Comment by bjarnef** [comment]
@nul800sebastiaan can this one be cherry picked to next patch release of v8.12 as well?

**Comment by nul800sebastiaan** [comment]
Yep! Cherry picked for 8.12.2 in https://github.com/umbraco/Umbraco-CMS/commit/72e468428ad0c76ea4076d22693cc38f8a331eae

**Comment by bjarnef** [comment]
@nul800sebastiaan I guess you mean v8.12.3 😁👍🚀

**Comment by nul800sebastiaan** [comment]
Yes!! Duh.. 😅

**Pull request merged**
