### PR TITLE
Add ExpireDate to IPublishedContent

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is: https://github.com/umbraco/Umbraco-CMS/issues/2930
- [x] I have added steps to test this contribution in the description below

### Description

As outlined in #2930, this PR adds `ExpireDate` to IPublishedContent. It allows us to utilize the unpublish date of content when rendering - like this:

```cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}
<h1>My super awesome page</h1>

@if(Model.Content.ExpireDate.HasValue) {
    <i>This document expires @Model.Content.ExpireDate</i>
}
```

This can be tested by:

1. Set an unpublish date on some content
2. Publish the content (Choose "Save and publish", *not* "Save and schedule")
3. Render `Model.Content.ExpireDate` as outlined in the sample template above

**PLEASE NOTE:** Adding stuff to IPublishedContent is a breaking change for a lot of package devs.

### CODE REVIEW

**Comment by abjerner** [comment]
@kjac Awesome. Thanks submitting a PR for this 👍 

I just skimmed through the code, and so far it seems to do as advertised 😄 Nevertheless, I will try to give the code a spin to see it in action.

I'm however a bit concerned by making changes to the `IPublishedContent` interface for Umbraco 7. I guess we'll have to hear @nul800sebastiaan about that one.

**Comment by dawoe** [comment]
Also have a quick look at the code but did not test it yet.

First thing that pops to mind is if you follow the steps outlined by @kjac above. But do a extra step
Change the expiry date, but don't publish the content. Just save it. Is that change reflected in the XML cache ?

But I think the page will be unpublished on the newly set unpublish date. 

But like I said...haven't tested it yet

Dave

**Comment by kjac** [comment]
@dawoe the XML cache isn't updated on save. So it won't be reflected unless you actually publish.

**Comment by dawoe** [comment]
So that means the value in the cache is not actually up to date.

But like I said...need to run some tests

**Comment by kjac** [comment]
@abjerner I don't disagree. Updating `IPublishedContent` shouldn't be done on a whim.

On the other hand - as long as there is no date for V8, can we really postpone changes for that reason alone? The issue was moved from the old issue tracker, I suppose there was a reason for it 😄

**Comment by kjac** [comment]
@dawoe correct. Just like UpdateDate and all your changes won't be updated either until you publish them.

**Comment by nul800sebastiaan** [comment]
I guess there's not really a good way to solve this right now. I didn't realize at the time that changing `IPublishedContent` has a large impact.

- We can't update the interface
- We could come up with a weird thing like we did with `IPublishedContentWithKey` but it would require wiring up loads of stuff for a tiny impact
- We could wait for v8 but.. yeah, that might not be desirable

The only thing I can think of off the top of my head is to have an extension method available that could get this data, but it should be cached somehow. I'm not sure what kind of caching mechanism we'd use for that or how we could make sure that we invalidate it when a content item gets updated with a new expire date.

**Comment by kjac** [comment]
@nul800sebastiaan an extension method on `IPublishedContent` could be a solution. But it wont be pretty, nor future proof. Basically it'd check if the `IPublishedContent` was an instance of `XmlPublishedContent` and then return the `ExpireDate` from that instance. 

`ExpireDate` would in other words still be a property on `XmlPublishedContent` but not on `IPublishedContent`.

This approach would require updating if/when the XML cache is changed or supplemented with alternative caching methods.

**Comment by nul800sebastiaan** [comment]
After some discussions at HQ we've come to the conclusion that this change is unwanted:

- You'd be adding information to the cache that's only rarely used (the usecases posted are not something that apply to the majority of users of Umbraco)
- The update, whichever way it would be done, is pretty intrusive as we've discussed above
- For people who do need this feature the advise is to add a new label property on the doctype and bind to the `Saving` eventhandler to populate the property. This property can then be used to display the `ExpireDate` on the page

Thanks for looking into it and sorry that I didn't think this through when moving over the issue from the old tracker!

**Pull request closed without merging**
