### PR TITLE
#3141 fixed broken Do something else button

### PR DESCRIPTION
**Pull request by dawoe**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is: #3141 
- [x] I have added steps to test this contribution in the description below

### Description

PR #3056 broke the "Do something else" button. This PR fixes that

Steps to test 
- Check if do something else button opens the context menu
- Check if a node keeps the active state when right clicking it or bringing up the action menu.

### CODE REVIEW

**Comment by BatJan** [comment]
@dawoe I also thought about simply removing that line but the "feel" of the context menu showing instead of the creation menu does not feel quite right is it used to. Maybe it's just me but it feel more "clunky" somehow.

I'll see if I can do a comparisson with 7.12.3 later and figure out if it's just my memory playing tricks on me or if there is a difference :)

**Comment by BatJan** [comment]
@dawoe Turns out it's my bad memory - The menu acts as it did before 👍

**Comment by markadrake** [comment]
I think the logic is conflicting a bit here. If you don't mind us taking extra time to look at this it would be great. The reason I reset the `currentNode` (which represents what is active) is because this method is called across the board when the navigation is hidden away. 

With the change above, if you click off of the menu by clicking on the editor workspace (vs closing the menu another way) then `currentNode` is no longer set to null, and thus the content node remains highlighted.

I'm looking at this right now.

_Context menu for a node is opened. The node remains highlighted._

image

_Click to the right of the context menu to dismiss, node remains highlighted._

image

**Comment by dawoe** [comment]
Hi Mark,

I applied the fix you recommended. That works better

**Pull request merged**
