### PR TITLE
#6215 Added basic monaco editor for stylesheet

### PR DESCRIPTION
**Pull request by rasmuseeg**
Providing a sample on how to integrate Monaco Editor. Keep open for discussion.

### CODE REVIEW

**Comment by rasmuseeg** [comment]
#6215

**Comment by bjarnef** [comment]
Maybe we should rename the code editor to something independent on the library e.g. `umb-code-editor` similar to we now have `umb-range-slider` (noUiSlider) and `umb-date-time-picker` (Flatpickr).

**Comment by bjarnef** [comment]
We should probably also change this to an Angular component and instead of use naming as "aceOption", it should be something more general like "options", "config" or similar.

**Comment by nul800sebastiaan** [comment]
@rasmuseeg I'm really happy for you to keep hacking away on this, but we still need to decide if it worth it for HQ to switch the editor. Which is why we asked for a list of pros/cons on the related issue. 

Just letting you know that we haven't decided anything yet and I don't want to waste your time with building stuff that may not make it into Umbraco.

**Comment by rasmuseeg** [comment]
@nul800sebastiaan Yes, i remember. I was making the draft to see how much needs to change, because i was not familiar with how it was structured.
Was also trying to get more familiar with the Monaco Editor and it's features, in order to later come up with the feature list for comparison.

@bjarnef Yes, i agree to some extend. By naming it monaco editor, we can reference to the monaco editor api. 
But if it is named umbraco-code-editor, we have to implement events, options, as methods or events inside the directive. I rather not build an API wrapper around the already great and well structured api.

**Comment by bjarnef** [comment]
@rasmuseeg that is how other components are structured in Umbraco and it allow package developers the re-use this stuff, e.g. in a custom property editor, custom section or in a custom dashboard.

Furthermore I would prefer not naming it after the library, but based on its behaviour, e.g. `umb-code-editor`.

**Comment by rasmuseeg** [comment]
@bjarnef Okay, well then we can add that to the pro/con list.
If we are to implement an API wrapper, we need to be picky about which options and events we want to implement.

**Comment by bjarnef** [comment]
@rasmuseeg you already have the `umbMonacoEditor` directive, which is wrapped the monaco editor. This should probably be a angular component instead and renamed to something like `umbCodeEditor`. This component can implement the callback functions monaco editor has and can then be used in the different parts of backoffice in core or by (package) developers similar to other components in core.

**Comment by rasmuseeg** [comment]
Yes, we can agree on that.
The callbacks already there, but the options and the editor is directly exposed through.
We can't just not wrap options and callbacks, and stille have the editor exposed through params.

**Comment by bjarnef** [comment]
Instead of `vm.monacoEditorOptions` it can be more general like `vm.editorOptions` or similar.

**Comment by zersiax** [comment]
One pro I can add is that, given this is not disabled, Monaco's accessibility mode is very mature due to it being battle-tested in Visual Studio Code. I myself use that as my daily driver and can confirm this works very well for a web-based editor.  TinyMCE is certainly usable, but for code I would definitely much prefer Monaco here.

**Comment by bjarnef** [comment]
@zersiax I guess you meant Ace Editor not TinyMCE as code editor 😁

**Comment by zersiax** [comment]
Hah :) I thought code editor was also tinyMCE, very much an Umbraco newbie still. Same goes for ACE though, Monaco would be a huge step up :)

**Pull request closed without merging**
