### PR TITLE
Upgrade projects to automatic package restore

### PR DESCRIPTION
**Pull request by vnbaaij**
This is done to follow NuGet best practices. See [the NuGet site](http://docs.nuget.org/consume/package-restore/migrating-to-automatic-package-restore)

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
I'm not sure what's going on here, the targets file is there to do an MSDeploy, added specifically because it was hard for people to deploy everything as it was out of the box. I don't see a replacement for that scenario in this PR? Just removing the targets file that facilitates the wanted functionality?

**Comment by nul800sebastiaan** [comment]
Ah, never mind, this is not for our NuGet package :-) for the core.. okay, we'll have to evaluate this then! Ignore my comment above :)

**Comment by zpqrtbnk** [comment]
Uh... more than 200 commits and more than 1000 changed files? Either that's a _massive_ PR or you've done something wrong?!

**Comment by vnbaaij** [comment]
Haha. lets assume the latest. please ignore this pr. Will see if I can submit a new one

**Pull request closed without merging**
