### PR TITLE
3408 - Improve accessibility of notifications

### PR DESCRIPTION
**Pull request by BatJan**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues/3408) for the proposed changes in this PR, the link is: https://github.com/umbraco/Umbraco-CMS/issues/3408
- [ ] I have added steps to test this contribution in the description below

### Description
I have added an aria-live region with the value of "polite", which means the screen reader will finish whatever it's currently reading before reading out the notification. Ideally this would be setup on the <li> element but since it's injected and removed from the DOM dynamically screen readers will not pick it up. But ideally the value should be "assertive" whenever the notification is of type "warning" or "error", which will make the screen reader read out the notification message immediately and thereby interrupting the user of what they were currently doing.

However I think using polite is better than not doing anything. By using the free NVDA screen reader I also discovered that the source order of the HTML was a bit off, which has also been changed so the close button is placed after the message.

I still need to fix the following

- [ ] Investigate if translation keys for the words "Close" and "Notification" already exists - If not create them and map them using the <localize> directive
- [ ] Figure out if perhaps the aria-live attribute can be changed dynamically when we know whether it's a succes, warning or error notification message we render

I'll see if I can record a video displaying the differences in what the screen reader does before and after - Just not sure how to do it yet but will add when I figure it out 😃

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @BatJan!

Love an accessibility PR - it's something that can so easily be overlooked. Thank you for this - I shall look over it today and let you know if we need anything.

Enjoy DK fest!

Em

**Comment by BatJan** [comment]
Hey @emmaburstow Thank you! :) I still need to get some work done on it so it's not quite ready for review yet - I'll ping you when it's ready 😃

**Comment by BatJan** [comment]
@nul800sebastiaan This is till WIP - But do I need to update more translations based on the change we did splittet out name and id into two strings? So far I have only updated the "contentPublishedFailedByParent" key - But perhaps more keys need to be updated now?

**Comment by nul800sebastiaan** [comment]
Yep, so in this case.. you will need to update ALL of them! 

As you've seen, it now only shows the page name by default, so you should at least change `%0%` to `%0% %1%` in all of the language files to make it look the same as it did before.

**Comment by BatJan** [comment]
Hey @abjerner - Nope it's not ready for being merged yet. I hope I can find some time to work on those PR's I have open during the coming weekend 😃

**Comment by BatJan** [comment]
@nul800sebastiaan Ok - So I think this one is finally ready for being reviewed. So in order to make the notification when saving & publishing a document a bit more accessible I have added a "live" region using the ara-live attribute, which means the text content of the notification will be read by screen readers.

Ideally the "polite" value could be changed to "assertive" if warnings or error notifications are displayed but I don't currently see that it's possible since the attribute needs to be available from the beginning in order to detect the changes - So all notifications are set to "polite" for now, which is still better than it was before 😃 

So some notifications show the node name + node id... So before it would display "About this starter kit (1123)..." Now it will say "About this starter kit (Id: 1123)...", which makes more sense in an aural context.

I hope the following videoes paint a picture of how it works now - I have just picked an example where I get a warning about the page not being able to publish, since it's been scheduled for another time. But all notifications will now be read out loud by a screen reader as opposed to before where it would not be - In the example I have made sure to get a warning notification where the ID text change is also possible to see. 

Before change
https://youtu.be/Yu8w7bs0ZFM

After change
https://youtu.be/Yu8w7bs0ZFM

I hope it all makes sense and I'm looking forward to receive some feedback on this 😃

**Comment by nul800sebastiaan** [comment]
Hey there @BatJan !

I'm writing today after announcing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Pull request closed without merging**
