### PR TITLE
Add GetById(Udi) to published caches

### PR DESCRIPTION
**Pull request by zpqrtbnk**
See #5216 - issue has been fixed, was adressing v7, and this is adressing v8.

### CODE REVIEW

**Comment by Shazwazza** [comment]
Looks good, have added as 'breaking' only because we've added some methods to a public interface at the caching level.

**Comment by Shazwazza** [comment]
(not sure why it's not letting me delete this branch though)

**Comment by zpqrtbnk** [comment]
about branch deletion: because GitHub branch protection rules don't work as... expected - if a branch is protected, one cannot delete it anymore - have de-activated some rules, and deleted the branch - will figure it out

**Comment by KevinJump** [comment]
Is this the fix to 

#4407 - v8: ContentService.GetById gets cached version when using Key (Guid)
& #2997 - ContentService returns outdated result 

?

**Pull request merged**
