### PR TITLE
V12: Property editors should only contain layout when in preview mode

### LINKED ISSUE #14302: Back Office: Tag suggestions getting hid by Summary field
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.0

### Bug summary

Document Library Back-Office: If there are multiple tag suggestions by the text entered in the “Tags” field, the list gets hidden underneath 

Umbraco Bug
the Summary field text box.

### Specifics

_No response_

### Steps to reproduce

Create an Umbraco Document Type with content properties of a Tags field and Text Editor field

### Expected result / actual result

I expect that the dropdown list would be overlaid on top of the other property fields when looking at suggestions, but it is buried underneath the other properties

### PR DESCRIPTION
**Pull request by iOvergaard**
Fixes #14302

It ensures that the fix for #13495 is only active when the property editor is in preview mode by appending an extra class to apply the more strict `contain: layout` styling when preview mode is active.

It should work for property editor "preview" (when editing invariant properties and in the document type editor) as well as with the "unlock" setting activated by `allowEditInvariantFromNonDefault`.

I have also chosen to remove the seemingly now defunct `readonly` attribute on umbPropertyEditor since I cannot find any usage throughout the application for that. It seems it was replaced by the additions to the preview mode at some point.

### CODE REVIEW

**Comment by madsrasmussen** [comment]
I am not sure we can remove the readonly attr 🤔 All property editors rely on a readonly value on the $scope, and If I remember correctly this is where it comes from. Does the readonly mode of a property editor still work after these changes?

Ex: 
https://github.com/umbraco/Umbraco-CMS/blob/v12/dev/src/Umbraco.Web.UI.Client/src/views/propertyeditors/textbox/textbox.html#L14

**Comment by iOvergaard** [comment]
@madsrasmussen Good catch, of course, you are right. It's that magic scope thing of AngularJS again. Always missing that 😎

**Review by madsrasmussen — APPROVED** [review]
Good changes looks good to me, and the result is a expected. Great 🎉 

Screenshot 2023-09-14 at 13 03 38

**Comment by iOvergaard** [comment]
Picked for v10 & v11: 0a4cc27a5d01fbd4be9828e55a8e2a8d52c12f2b

**Pull request merged**
