### PR TITLE
U4-854 Add MaxLength to Textstring fields --> Fixed

### PR DESCRIPTION
**Pull request by ja0b**
Now the textstring datatype has a limitation of min=0 and max=500 by default and it will only show the message of "x characters left" when the "Maximum allowed characters" property is set to < 500.

http://issues.umbraco.org/issue/U4-854

### CODE REVIEW

**Comment by bjarnef** [comment]
I think it shouldn't have a default max characters set, otherwise you might need to change this for existing sites being upgraded (or maybe loose some data).
Furthermore if using textstring or textarea as macro parameter, the prevalues is not available for macro parameters, which mean the default value can't be changes.

**Comment by bjarnef** [comment]
It should probably also be consistent on textbox and textarea property editors. It seems it is only modified for textbox.

**Comment by nul800sebastiaan** [comment]
@bjarnef You can't loose data, right now you can already not store more than 500 characters, you will get a database error if you try to. Which was the whole point of this improvement (I will test this to make sure).

It's fine for now to only add this to the textbox, which is problematic due to the 500 char database limit.

**Comment by bjarnef** [comment]
@nul800sebastiaan ahh okay. I didn't think about that :)
I was working a bit on `character-limit` and `word-limit` components/directives some time ago, before the max characters feature was added to core. I thought that could be useful to re-use in parts of the core, custom property editors and custom sections.

**Comment by nul800sebastiaan** [comment]
@ja0b Good stuff, I made some changes and merged it all in, thanks!

**Comment by nul800sebastiaan** [comment]
@bjarnef Sure thing, sounds good! Probably larger in scope than this fix though!

**Comment by ja0b** [comment]
I'm sorry for not replying sooner, @bjarnef seems like you already know about the database limitation, thanks for your feedback 🙂

@nul800sebastiaan regarding this line:

` <div class="help" ng-if="model.showcharacterslefttext">`

I found a bit weird to show the limit if we are using the default value = 500, that's why the little check there, but all good! 

Thanks! 👍

**Comment by nul800sebastiaan** [comment]
@ja0b Yeah I think it is just a lot clearer to show the limit rather than just magically cutting people's typing off with no warning. :-)

**Comment by bjarnef** [comment]
@nul800sebastiaan I think it might add some clutter to the UI if adding the max characters help text to all textbox fields :)

image

Imagine having 10-20 textboxes under a tab ;)

Maybe change the class `help` to `help-block` since it use same font color as `help-inline`.

**Comment by nul800sebastiaan** [comment]
@bjarnef You're right, have reverted to the this behavior again now: if a max number is specified, then show the characters left, otherwise hide that help text. 

https://github.com/umbraco/Umbraco-CMS/commit/b1ceeb23b3318871bf22717e9c2fe1d1961cef50

**Pull request merged**
