### PR TITLE
V8: Fix the Nested Content title overflow

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

The title overflow handling introduced in #2457 has been broken at some point, leaving long item titles looking rather off:

nc-wrap-before

This PR fixes it 😄 

While I was at it, I removed a bit of the left and right padding for the items, so they look a tad more in line with e.g. the MNTP items.

Here's a preview of how NC works with this PR applied:

nc-wrap-with-icons

...and here's an preview of the same, only without item icons:

nc-wrap-without-icons

/cc @nielslyngsoe

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hey @kjac ,

Thank you and watch this space :-)

Poornima

**Comment by emmaburstow** [comment]
We might thank you for the Pr, @kjac,  but I'm not going to thank you for getting that song stuck in my head. A lalalala long... ;)

**Comment by kjac** [comment]
Hahaha! Inner Circle 😆

**Comment by skttl** [comment]
Looks great, but could use a bit more spacing between the icon and the title for consistency.

Also, a description function for NC would be nice, but that is another issue :)
image

**Comment by kjac** [comment]
Hey @skttl. Good point, I'll adjust the spacing 👍

Incidentally I spotted this issue while working on a description solution per item. The work is done, but it conflicts with this PR, so... One thing at a time 😀

**Comment by kjac** [comment]
Done; the spacing between the item icon and title text now looks like this:

image

**Comment by nielslyngsoe** [comment]
@kjac Looks good, thanks!

**Comment by nul800sebastiaan** [comment]
Despite your questionable song choice ( ;-) ) this is a nice little fix, thanks!

**Pull request merged**
