### PR TITLE
Replaced <i> with umb-icon in umb-node-preview

### PR DESCRIPTION
**Pull request by poornimanayar**
Another `umb-icon` from me. I have replaced the `<i>` with `umb-icon` in `umb-node-preview` . This is quite a sweeping change as the `umb-node-preview` is used in many many places. Would recommend testing the following
1) Info content apps in content, media, members
2) Icons in grid editor config
3) icons in content picker in content edit
4) icons for user groups in users section

### CODE REVIEW

**Comment by nathanwoulfe** [comment]
Hi @poornimanayar should this be setting all the icons in the umb-node-preview directive to the svg value or is that a separate change? All looks fine otherwise, no more `<i>` in the node preview elements.

**Comment by poornimanayar** [comment]
Hey @nathanwoulfe , my work replaces the `<i>`  in the `umb-node-preview`  to use the `umb-icon` directive. But the node preview is used in many many places across the application as I said before. I have done a search on where it is used and tested all of it. It all seems to be working okay

**Comment by nathanwoulfe** [comment]
Yup, all works fine from what I've seen 👍👍

**Comment by bjarnef** [comment]
@poornimanayar when using `<umb-icon>` it doesn't need `aria-hidden` attribute. The component takes care of this 👍

**Comment by poornimanayar** [comment]
Thanks for pointing out @bjarnef, missed that detail.. will correct it :-)

**Review by nathanwoulfe — APPROVED** [review]
Hey @poornimanayar, took me a while to get back to this, but it's allllll good 👍

**Pull request merged**
