### PR TITLE
U4-7721 install button miss aligned

### PR DESCRIPTION
**Pull request by StefanoChiodino**
Tested on Safari 5.1.7, latest Chrome and Firefox

### CODE REVIEW

**Comment by Draga** [comment]
Finder's fees to @stomppah

**Comment by StefanoChiodino** [comment]
Hello?

**Comment by StefanoChiodino** [comment]
Helloooooo?

**Comment by warrenbuckley** [comment]
Hellloooooooo @StefanoChiodino 
Sorry we must have been under a rock or something when you submitted this PR.
I've taken a look and the change is fine, great stuff! It's now all merged in!

Thanks again for the PR & sorry for us taking so long to get back to you - the next time you'll submit a PR we'll get back to you a lot sooner 👍

**Pull request merged**
