### PR TITLE
Update our.umbraco.org links to our.umbraco.com

### PR DESCRIPTION
**Pull request by prjseal**
### Description
I have found and replaced all references to our.umbraco.org in the source code, docs links and api links etc. I have also replaced any of these links that were http:// with https://

This PR is for this issue [http://issues.umbraco.org/issue/U4-11542](http://issues.umbraco.org/issue/U4-11542)

### CODE REVIEW

**Comment by prjseal** [comment]
Sorry the PR is not named the same as the issue. I created the issue first. But I don't think it should matter too much.

**Comment by nul800sebastiaan** [comment]
@prjseal No worries about the title, you've provided all the info we need. Someone might have beaten you to it though! 😮 https://github.com/umbraco/Umbraco-CMS/pull/2811

**Comment by nul800sebastiaan** [comment]
Thanks Paul, the other PR I referred to was almost exactly the same, but you found a few more files. [I added those few changes](https://github.com/umbraco/Umbraco-CMS/pull/2811/commits/8404efc521b50c53a0cfa4ad15f071d6d7eff443) there as well. Too bad that Imran had the exact same idea as you! 😅

**Comment by prjseal** [comment]
Ah well. Never mind a hackathon commit trumps a late night Sunday though commit. Even if mine was linked to an issue in the PR lol

**Pull request closed without merging**
