### PR TITLE
Spectrum colorpicker v2

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
I noticed that we at the moment are using the spectrum color picker here:
https://bgrins.github.io/spectrum/

However it seems this is unmaintained and another developer has taken over the project and continued the work:
https://seballot.github.io/spectrum/

With some minor adjustments this PR replaces spectrum-colorpicker with spectrum-colorpicker2. The configuration is pretty much the same as this existing one, but with some enhancements.

**Before**

chrome_2020-09-01_10-12-38

**After**

image

### CODE REVIEW

**Comment by bjarnef** [comment]
@nielslyngsoe this looks a bit nicer and seems to works pretty much like the existing one 👍

**Comment by nul800sebastiaan** [comment]
Love it, thanks @bjarnef! I guess you can preconfigure a color pallet with this one as well? Would be cool with something like "brand colors" and hide the spectrum picker maybe. Anyway, this is a great start and definitely, turning it into a component would be excellent. 👍

**Comment by bjarnef** [comment]
@nul800sebastiaan at the moment it shows this color palette by default (in v1 I think it was hidden by default).
Actually I am planning the release this package in a short moment https://github.com/bjarnef/color-pickr having a `<color-picker>` and from property editor it is possible to configurate the predefined colors. It is using another JS plugin though.

**Comment by bjarnef** [comment]
@nul800sebastiaan here a WIP PR to add a color picker component https://github.com/umbraco/Umbraco-CMS/pull/8812 🥳

**Pull request merged**
