### PR TITLE
Show BlockGrid Create Dialog if there are items in clipboard

### PR DESCRIPTION
**Pull request by stefanstankovic**
Default behavior:

If you have only one available module for an area Umbraco will open a dialog for adding the module. If you have more than one module you will get a dialog to choose a module and that dialog will have a Paste option in the top right corner.

New behavior:

If there is a module in the clipboard, Umbraco will open a dialog with the Paste option even thou there is only one available module in the area. In other cases, it will work as usual.

Reported issue: https://github.com/umbraco/Umbraco-CMS/issues/15755

### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes

### CODE REVIEW

**Comment by mikecp** [comment]
Hi @stefanstankovic ,

Thanks for spotting this issue and providing the fix 👍
A member of the core collaborators team will have a look at it soon, butI already took the action of rebasing your PR on the `contrib `branch which is the only one that the community contributors are supposed to target. The other branches being reserved to HQ 😉

Cheers!

**Comment by mikecp** [comment]
Hi @stefanstankovic ,

I have just checked your update and it works as expected, enabling consistency in all cases 👍
Thanks a lot for your PR, I see this is your first one on the Umbraco CMS, congratulations!! 🎉
If you provide us with your account name on the forum (Our), I am sure that our steward @nul800sebastiaan will be very happy to assign our shiny contributor's badge to you 🏅

Thanks again, and we'll be looking forward to your next contributions 😉

Cheers!

**Comment by mikecp** [comment]
Oh and I have added the bellissima label so that HQ can make sure that this is handled on V14 as well 😁

**Comment by Migaroez** [comment]
@stefanstankovic Just wanted to throw another big thank you your way. It's because of people like you that the CMS is flourishing as it is!

**Pull request merged**
