### PR TITLE
Fix bug#16782

### LINKED ISSUE #16782: OpenIddict `code_challenge` error
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.1.0

### Bug summary

Logging in via `localhost` works while logging in via `host.example.com` does not.

### Specifics

The error message after logging into `/umbraco/login` is as follows:

```txt
error:invalid_request
error_description:The mandatory 'code_challenge' parameter is missing.
error_uri:https://documentation.openiddict.com/errors/ID2029
```

### Steps to reproduce

On a fresh install of Umbraco 14.1.0, run the following command:

```pwsh
dotnet run --urls "http://0.0.0.0:80"
```

Verify that logging into:
 - <http://localhost/umbraco/login> works 
 - <http://host.example.com/umbraco/login> does not

### Expected result / actual result

After a successful login, I expect to land on the dashboard. Instead, I see the error message listed above.

### PR DESCRIPTION
**Pull request by IbrahimMNada**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #16782 

### Description
When trying to host a v14 Umbraco application on an Http server you are unable to login whatsoever 

and you are getting this error `error_description:The mandatory 'code_challenge' parameter is missing.`

and it makes since because this error means PKCE is not there and PKCE do not work with http. 

so in order to fix this I only put a condition on PKCE  if and only if is  `"Umbraco:CMS:Global:UseHttps": true`
and now its working as expected. 

Steps To Test this : 
1-att the app settings Set :  `"Umbraco:CMS:Global:UseHttps": true`
2-Run you application on http
3- try to login 
4- you are able to login 

##I really hope this gets merged soon all of my testing/development servers are http :(

### CODE REVIEW

**Comment by mikecp** [comment]
Hello @IbrahimMNada,

Thanks a lot for providing a fix for this bug§

**Comment by nul800sebastiaan** [comment]
This is probably not a good idea, it could lead to people accidentally running an unsecure http server while they really should be running over https. 

I believe you can fix the problem by actually spinning the server up with `dotnet run --urls "https://0.0.0.0:443"` instead. Then you don't need to change `BackOfficeHost`, `UmbracoApplicationUrl` or `UseHttps`. It will run on https, your browser might complain that it doesn't understand the certificate, but that is fine, you  can tell the browser to ignore that and continue anyway (keeping in mind all the warnings). It tested a setup like that and it worked for me.

image

image

Ultimately, please be EXTREMELY careful when you do something like this, your logins / cookies will travel in clear text for anyone on your network to see and there's absolutely no protections from people intercepting your requests and ruining your Umbraco install. 

For now I will close this PR and issue with the recommendation to run it on an https port, even if you don't have a valid certificate.

**Comment by wadrschall** [comment]
@nul800sebastiaan 

I understand the thinking in your recommendation, however, in some hosting scenarios, this isn't an option. For example, we have clients which have cloud based virtual machines running IIS and the IT requirements is for all sites to run on HTTP. These aren't open to the outside world, instead they utilize a Web Application Firewall to handle the SSL binding and then route the traffic to the HTTP hosted site in the VM. 

In this scenario, the security checks being performed ensure V14 is unable to run as the website on the VM is run as HTTP but the outside world sees HTTPS (unless I'm missing something). We can always recommend our clients install SSL certs internally as well (or switch to App Services), but this requirement is set for their IT policies (assumption being since the server isn't publicly accessible, they don't see a need to maintain SSL certificates in 2 places).

**Comment by IbrahimMNada** [comment]
@nul800sebastiaan 

Hello, I hope all is well with you. 

I just want to make things clear.

The flag regarding https is already there 
I just built on it. 

All i did was ignore PKCE, which is only in the context of open id connect protocol.

your argument is 100% valid
But this pull request is a small extension of what is already there.

It's your call after all, and i respect that
You guys gave us this awesome CMS.

So we can't complain 🌹

**Comment by nul800sebastiaan** [comment]
Thanks for the feedback! 

I have use Cloudflare before with a setup like that @wadrschall and I do think this was not a problem, so I would expect Azure to be able to do the same.

@IbrahimMNada You're always allowed to (respectfully) complain, we need to hear when something is not working as expected and I thank you once again for your attempt at fixing it! 

As an alternative you can use the following bit of code to reconfigure the OpenIddict options:

```csharp
using OpenIddict.Server;
using Umbraco.Cms.Core.Composing;

namespace MyNamespace;

public class InsecureComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        if (builder.Config.GetValue<bool>("Umbraco:CMS:Global:UseHttps") == false)
        {
            builder.Services.PostConfigure<OpenIddictServerOptions>(x => { x.RequireProofKeyForCodeExchange = false; });
        }
    }
}
```

Please note that this is looking for `UseHttps` to be explicitly set to false. So make absolutely sure that in your production appsettings file that `UseHttps` is set to true. As noted earlier, it's easy to open up security holes so please be safe and only use this as a last resort.

Thanks again!

**Comment by IbrahimMNada** [comment]
@nul800sebastiaan 

Hello , Can you confirm if the solution above works ? 

because as I recall  the extension method `RequireProofKeyForCodeExchange()` will set Override the OpenIddictServerOptions 
even if its set to false. 

I have tried it ,I think its not working

**Comment by ctolkien** [comment]
I believe we are hitting the same issue here. We have HTTPS terminated at the load balancer, and any internal comms are then over HTTP....

**Pull request closed without merging**
