### PR TITLE
Contribution guidelines moved to .github directory

### PR DESCRIPTION
**Pull request by mzajkowski**
Pull Request for issue [#U4-10619](http://issues.umbraco.org/issue/U4-10619).

### Summary of Changes

After short talk with Sebastian we decided that we can switch from keeping this documentation on content pages on Our into proper Github docs. After it'll be merged the URLs / paths should be updated on Our.

So I've moved the documentation for the contribution process from the Our content page into proper and suggested CONTRIBUTION.md file displayed for all possible future contributors on Github.

I've also added some additional files like PR template and Issue report template.

Some of the legacy sections were removed and some of them requires HQ's attention for sure, but at summary - it's a huge step forward.

### Documentation Changes Required

It's a documentation change itself :)

### CODE REVIEW

**Comment by alanmac** [comment]
some changes as discussed @mzajkowski 

In FIRST_TIMERS.md under the section Build & run the solution:

Change Grunt to Gulp where it says "This will set up everything for you and runs MSBuild and the Grunt build for you." 

Change "Once that loads you can hit **F5** or press the **"Play" button** to start the solution." 
to:

Once that loads set the startup project to **Umbraco.Web.UI** and hit **F5** or press the **"Play" button** to start the solution.

**Comment by mzajkowski** [comment]
Hey @alanmac,

thanks! I made the adjustments and they are here in the PR now. Hope it will be a great starting point for the further contributions around it.

Cheers!

**Comment by alanmac** [comment]
Hey @mzajkowski,

That's fantastic thanks! looking forward to sending more in.

Cheers,

Alan

**Comment by nul800sebastiaan** [comment]
Thanks @mzajkowski - great effort so far!

This will take a little bit of time and rewriting on our part before we can merge it in. Some of the documentation on Our is already pretty old so we want to replace it completely. 

We also don't need to link to the documentation contributions, this is only for core.

**Comment by mzajkowski** [comment]
Sure thing @nul800sebastiaan. Let me know if you'll need any further help here. IMO it might be useful to merge it even before adopting Our, as it will be already used and useful for all contributors and contributions (PRs etc) here on Github. Visibility may be tweak later (agile! ;)).

**Comment by nul800sebastiaan** [comment]
Thanks again, we have all of these in place now so we'll close this one! #h5yr!

**Pull request closed without merging**
