### PR TITLE
Revert breaking changes adding IContextCache to deploy connectors

### PR DESCRIPTION
**Pull request by ronaldbarendse**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
PR https://github.com/umbraco/Umbraco-CMS/pull/13287 contained breaking changes that affected implementations of `IDataTypeConfigurationConnector`, `IServiceConnector`, `IValueConnector` and `IGridCellValueConnector`. This PR reverts these breaking changes by moving them into a new interface and providing extension methods that tries to use the overload accepting `IContextCache` when available.

Testing should ensure the breaking changes are reverted and after merging/releasing this, the Deploy/Deploy Contrib implementations should be updated and tested separately.

### CODE REVIEW

**Review by AndyButland — APPROVED** [review]
This looks correct to me and reverts the breaking changes.  I think we mostly need to test this once we have it available for referencing from Deploy.

**Comment by leekelleher** [comment]
Thanks @ronaldbarendse, @bergmania, et al. I appreciate the fast turnaround. #h5yr

**Comment by bergmania** [comment]
@leekelleher, these changes will not work with your 4.3.0-beta of Contentment, that seems to rely on the changes unbroken by this PR. 🙈

**Comment by leekelleher** [comment]
@bergmania No problem, I'll get that updated on my side. Thank you for following up on it. 🙏

**Pull request merged**
