### PR TITLE
Suggestion: Add config setting in Rich Text Editor to control the linkpicker overlay size

### PR DESCRIPTION
**Pull request by BatJan**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
This PR is similar to #11006 and please refer to the GIF illustration in that PR when understanding what this PR does. Only difference is that this affects the Rich Text Editor 😃

### CODE REVIEW

**Comment by bjarnef** [comment]
@BatJan as mentioned here https://github.com/umbraco/Umbraco-CMS/commit/e707490b471098d229cd23b44b24b408a4e12c78#r55772637 could we add a `overlaysize` global prevalue editor?

If there is a specific reason to add a `overlaysize` prevalue editor for a property editor, we can always add that later. But for now if seems to be redundant.

**Comment by nul800sebastiaan** [comment]
Nice one again @BatJan 😁

**Comment by bjarnef** [comment]
I have cleaned a bit up in https://github.com/umbraco/Umbraco-CMS/pull/11010 so we don't have a redundant prevalue editor.

**Comment by bjarnef** [comment]
It seems this doesn't work, but fixed in https://github.com/umbraco/Umbraco-CMS/pull/11010

The `overlayWidthSize` prevalue editor is not part of the `args.model.config.editor` object, but `args.model.config`.

**Comment by nathanwoulfe** [comment]
#11010 keeps this change generic and reusable for other editors 👍

**Pull request merged**
