### PR TITLE
User invite flow review

### PR DESCRIPTION
**Pull request by agrath**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is: https://github.com/umbraco/Umbraco-CMS/issues/2993
- [x] I have added steps to test this contribution in the description below

### Description

Several fixes related to the user invite and password reset flow

- if signed into backoffice when clicking a verification link, sign out before any redirections, otherwise you can be taken to the backoffice instead of see an error
- set password reset tokens to 72 hours (suggest changing this to less for testing)
- when a user clicks the invite link, they are partially logged in, this sets their last login date which in turn prevents invites from being resent and changes their account status from invited to disabled. revert the date from this partial login method (as the behaviour of signinmanager can't be changed without breaking changes)
- fix a bug that means you can't set a user's last login date back to minvalue because of a utc/local conversion problem
- when an *invited* user completes the password reset flow (not invite, e.g. they have an expired token) ensure their account is fully enabled after the reset (confirmed that this doesn't allow a disabled user to use password reset to reactivate their account)

https://github.com/umbraco/Umbraco-CMS/issues/2993

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Great job @agrath - this all checks out 👍

**Comment by agrath** [comment]
@nul800sebastiaan what release did this get merged into? I can't see it in the release notes

**Comment by nul800sebastiaan** [comment]
It will be released in 7.13, the related issue has a version number on it! https://github.com/umbraco/Umbraco-CMS/issues/2993

**Comment by agrath** [comment]
@nul800sebastiaan thanks, sorry missed that!

**Pull request merged**
