### PR TITLE
Show custom EventMessage when cancelling ContentService.Moving event

### PR DESCRIPTION
**Pull request by creativesuspects**
### Prerequisites

- [X] I have added steps to test this contribution in the description below

https://github.com/umbraco/Umbraco-CMS/issues/8372

### Description

This PR fixes an issue where the `ContentService.Moving` event does not show a custom `EventMessage` to the user when the event is cancelled using the `e.CancelOperation(new EventMessage(...))` method. The user would always see the default success message even if the Moving event was cancelled.

I have basically just copied pieces of logic from the `ContentService.Trashing` event which is almost identical to the Moving event. You can use the following code to test the fix, just add the code to a PublishedContentEvents.cs file in the src/Umbraco.Web.UI/App_Code/ folder:

```
using System;
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Core.Events;
using Umbraco.Core.Models;
using Umbraco.Core.Services;
using Umbraco.Core.Services.Implement;

namespace Application.Core.Composing
{
    public class PublishedContentEventsComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.Components().Append<PublishedContentEventsComponent>();
        }
    }

    public class PublishedContentEventsComponent : IComponent
    {
        public PublishedContentEventsComponent()
        {
        }

        public void Initialize()
        {
            ContentService.Moving += ContentService_Moving;
        }

        private void ContentService_Moving(IContentService sender, MoveEventArgs<IContent> e)
        {
            foreach (var moveInfo in e.MoveInfoCollection)
            {
                e.CancelOperation(new EventMessage("Unauthorized", "This document type can't be moved", EventMessageType.Error));
            }
        }
        public void Terminate()
        {
        }
    }
}
```

Video_2020-07-02_152157

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks @creativesuspects! Unfortunately we can't just update this method with a new return type, that will require everyone who upgrades to this version to recompile the code. Instead I would recommend creating a new method like `MoveWithResult` - it's ugly and you need to know it exists, but that can be documented.. This will be the only way we can maintain backwards compatibility and not break everything for a lot of people. 

Thanks for contributing so far!

**Comment by creativesuspects** [comment]
@nul800sebastiaan: Thanks for the feedback. I will try to make the necessary to the PR.

**Comment by creativesuspects** [comment]
@nul800sebastiaan: I've updated the PR. Question though: Can I use the new `MoveWithResult()` method in `ContentController.PostMove()` or does this method also need some extra work to maintain backwards compatibility?

**Comment by creativesuspects** [comment]
@nul800sebastiaan Any news on this?

**Comment by creativesuspects** [comment]
Any news on this? This issue is still present in Umbraco 8.10.1.

**Comment by creativesuspects** [comment]
Any news on this? This issue is still present in Umbraco 8.10.1.

**Pull request closed without merging**
