### PR TITLE
U4-11335 Failed to retrieve data for media id undefined

### PR DESCRIPTION
**Pull request by mvanhelmont**
### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description
What did you do?

1. In chrome go to a website other than the umbraco site, right click - copy image
2. In umbraco site HTML editor paste image
3. Left click on image in HTML editor, left click on "Media Picker"

What did you expect to happen?

No error 

What actually happened?

Error: Failed to retrieve data for media id undefined

Issue: http://issues.umbraco.org/issue/U4-11335

### CODE REVIEW

**Comment by dawoe** [comment]
Hi @mvanhelmont 

Thanks for this PR. I will try to review this soon. 

I actually learned something new. Didn't know you could paste external images in the RTE.

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by mvanhelmont** [comment]
I did not know that that was possible either. It was simple to fix.

**Comment by dawoe** [comment]
I also added 2 video's 2 the issue on the tracker to show the before and after situation.

**Comment by nul800sebastiaan** [comment]
Yay! Very nice and thanks for the videos, that helps a lot too! 🎉

**Pull request merged**
