### PR TITLE
#3575 - Adding support for middle click and ctrl+click for grid views

### PR DESCRIPTION
**Pull request by mattycare**
### Description
List / Gird / Folder views didn't support certain click events when clicking on item names

I have added a new middle click directive, and added this where needed to the item names to restore the missing functionality of opening in new tabs.

I have also restored the functionality of Ctrl+click to also open in a new tab.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hiya @mattycare!

Hope you had a good time at Uk Fest - was nice to meet you!

Thanks for this Pr. One of us will take a look at the work and let you know if we need anything. I'm pretty sure your last Pr got a mention in Seb's talk on the day? It is such a handy change. 

Anyways, speak soon,

Emma

**Comment by mattycare** [comment]
Hi @emmaburstow,
It was nice to meet you also; I had an enjoyable time in London.
I'm not sure if my Pr was the one he was referencing, but if it was, then good times.
Hope to be at the next one!

Matt

**Comment by nul800sebastiaan** [comment]
Hey there @mattycare !

I'm writing today after announcing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Comment by mattycare** [comment]
Hi @nul800sebastiaan 

I'll get this ported over to V8 when I next have a moment. Would you like me to open a new issue or stick with the issue attached to this pull request?

Thanks,
Matt

**Comment by nul800sebastiaan** [comment]
Sorry for the delay @mattycare ! We can just keep the same issue for it, no problem.

**Pull request closed without merging**
