### PR TITLE
Render preview of SVG files

### PR DESCRIPTION
**Pull request by bjarnef**
Issue: http://issues.umbraco.org/issue/U4-8580

For svg files they are displayed in an `` element and for other files types there is a font icon + the extension. Maybe we can take this further and e.g. display a font icon for audio files, on for video files, one for compressed files like .zip and .rar ... and maybe also one for word, excel, pdf  files like these icons included in font awesome http://glyphsearch.com/?query=file
However the different "file" icons included in core are limited to e.g. `icon-document` and a few other. So I have done like this for now (only for fileupload property at the moment).

image

image

Now SVG files are displayed like this so you get a nice preview (before just url to media).
image

It also looks great for animated SVG files (like animated GIF files are displayed via ImageProcessor).
mmhrf4xpwd

I have tested with different SVG files with and without animation - some of them found on codepen.io and the fox is from here:
http://stylecampaign.com/blog/2014/02/svg-animation/
http://stylecampaign.com/blog/?p=164&preview=true
http://stylecampaign.com/blog/blogimages/SVG/svgbase64img-link-fox-final.html
http://stylecampaign.com/blog/blogimages/SVG/svgbase64bg-fox-big-final.html

The listview media grid also display the SVG files (both non-animated and animated SVG) - however here I would like to disable the animations.
image

sejmituiha

I am not sure how to stop animations of SVG files, maybe like this? http://stackoverflow.com/a/26349286 - `SVGRoot.pauseAnimations();` - although I haven't tested that part.
And I guess ImageProcessor can't generate thumbnails of SVG files?

Alternative I believe there are different options to convert SVG -> Canvas -> png ... or SVG -> png, which doesn't animate. But it would be nicest to keep it in vector.

Finally I think we can optimize the listview media grid a bit to use full width (I have noticed similar issue in media picker).
E.g. the screen resolution of my laptop is 1366x768 pixels and can almost contain 4 items per row.

The non-animated and animated SVG files are attached in the issue.

### CODE REVIEW

**Comment by bjarnef** [comment]
I don't think we can start/stop SVG animations, when included in an `` element since it doesn't have any events for that. http://stackoverflow.com/a/11391768

But instead it can use this:
```
<object class="umb-media-grid__item-image" width="{{item.width}}" height="{{item.height}}" 
   ng-if="!item.thumbnail && item.extension == 'svg'" type="image/svg+xml" data="{{item.file}}" 
   alt="{{item.name}}" draggable="false" />
```

In Chrome you can e.g. then test it by selecting `<object>` element in DOM explorer, go to console window and write `$0.contentDocument.rootElement.pauseAnimations();` to pause animation or `$0.contentDocument.rootElement.unpauseAnimations();` to start animation again.

SVG SMIL animation works in Chrome, but is now deprecated http://caniuse.com/#feat=svg-smil and instead it is recommended to use CSS animations. But people can still upload files using SVG SMIL animation, which some of these SVG files use.

image

So I think it both should use javascript and css using `animation-play-state`, but only needed for SVG files.

**Comment by bjarnef** [comment]
In commit https://github.com/umbraco/Umbraco-CMS/pull/1402/commits/c5b9e6a1945f79f168c908bbccf99eb05a133152 I have changed load of SVG inside an object so we can access `pauseAnimations()` and `unpauseAnimations()` for SVG. However after changing to `<object>` I can't select the item if clicking on the `<object>` - but if I add a sibling element to `umb-media-grid__image-background` that acts as an transparent overlay with higher z-index and cover the `<object>` then the item can be selected.

If you test with this svg too http://xn--dahlstrm-t4a.net/svg/css/animations/hover-root-transform.svg - it has by default paused animation and on hover it run the animation. That is because the svg has the following css embeded:

```
svg > * { 
	animation-play-state: paused; 
}
svg:hover > * {
	animation-play-state: running;
}
```

but because the SVG is embedded inside the `<object>` we cannot style the svg like this directly from `umb-media-grid.less` ... but it is possible via javascript http://stackoverflow.com/a/4906603

There is *jquery-svg* plugin for that https://github.com/mberneti/jquery-svg/ ... maybe there exists something similar for AngularJS?

**Comment by bjarnef** [comment]
Maybe we should add a new directive for svg something like this: http://stackoverflow.com/a/28167145

To make the markup cleaner and doing some manipulation inside the directive:
```
<svg-image src="/icons/my.svg" class="any-class-you-wish"></svg-image>
```

**Comment by madsrasmussen** [comment]
Hi Bjarne, 

It looks good so far. 👍 

We need to find a solution to selecting the svg image in the media grid before I can pull it in. Is this something can add to the PR?

**Comment by bjarnef** [comment]
Hi Mads

I think it is this you are looking for?

> However after changing to `<object>` I can't select the item if clicking on the `<object>` - but if I add a sibling element to umb-media-grid__image-background that acts as an transparent overlay with higher z-index and cover the `<object>` then the item can be selected.

**Comment by madsrasmussen** [comment]
Thanks! I had to change the object tag in the umb-media-grid to an img tag for now. I could not get the svg's to render in Edge so we will have to go without the animation - even though it was super cool. It also fixed the selection problem.

Let's do some more investigation on how to get the rendering and animation to work cross browser and then we can add it back.

Super tak! 👍

**Comment by bjarnef** [comment]
Great! :+1: 

Yes, I am not sure why the `<object>` made the grid element unclickable (or only where it covered the element) - maybe something similar like when using flash in old days, where it needs `wmode=transparent` so e.g. dropdown not was hidden behind.
I also noticed the SVG images in my tests not always be scaled/fit within the object - I guess it was something about the viewbox size defined in the SVG itself.

IE and Edge are special - usually I use svg4everybody to make SVG render correct in most browsers.

**Comment by bjarnef** [comment]
@madsrasmussen I think I only tested this for media grid - how does it look in media picker? Can we do the same stuff there? :)

**Pull request merged**
