### PR TITLE
Fix the media picker not rendering when a media item has no image

### PR DESCRIPTION
**Pull request by kvakulo**
Reproduction steps:

1. Add a Media Picker property to a document type
2. Create an image media item with an image
3. Create a content entity, select the media item and save
4. Remove the image from the media item
5. The media picker no longer renders on the content entity in Umbraco

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Looks great, can you please create an issue on http://issues.umbraco.org so that we can link this fix to a release? Thanks!

**Comment by kvakulo** [comment]
Sure, I've created this issue: http://issues.umbraco.org/issue/U4-7705

**Comment by nul800sebastiaan** [comment]
@kvakulo In case you didn't get notifications: we can't repro the problem, let us know what we're missing! :) http://issues.umbraco.org/issue/U4-7705

**Comment by clausjensen** [comment]
From the looks of the fix Regin proposes - it looks like his media item for some reason doesn't have a value (and therefore we get an exception when trying to access the `src` of that value directly without checking for nulls first).
I'm not really sure in which cases this could happen since we can't reproduce it, but the check he implements is actually perfectly valid and should have been there in the first place. I'd say if it fixes something for him (and potentially others in some rare cases) we should just pull this in.

**Comment by kvakulo** [comment]
It seems like it only breaks if *Image Cropper* is used instead of the default *Upload* type on the Image Media Type. I've added a comment on the issue.

- Regin

**Comment by nul800sebastiaan** [comment]
:+1:

**Pull request merged**
