### PR TITLE
Updated the URL for the issue tracker.

### PR DESCRIPTION
**Pull request by readingdancer**
Also updated the version number to reflect the current version.

I have not created an issue for this as it's so small, sorry :)

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
In fact: `engines` can be removed too it seems!

**Comment by readingdancer** [comment]
Hi @nul800sebastiaan 

I am happy to make these changes and test it, will get back to you.

In the mean time, I've just added a Forum post related to updating this completely in V8, in a separate branch I have already updated the build process and tools to remove all the warnings, but I'd like to go further and remove Bower completely, I thought the Forum would be a better place for the discussion :)

https://our.umbraco.com/forum/umbraco-8//93889-discussion-about-the-frontend-build-process-used-in-the-core-project

**Comment by nul800sebastiaan** [comment]
Cool, I've moved it to the "Contributing to Umbraco" forum. 👍

**Comment by readingdancer** [comment]
FYI, there is an old issue related to it here: https://issues.umbraco.org/issue/U4-11563

**Comment by nul800sebastiaan** [comment]
I got curious and tried it all out 🙈 

All good with removing the properties, merging!  👍

**Pull request merged**
