### PR TITLE
Inherit from `OEmbedProviderBase` in OEmbed providers

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
Updated the OEmbed providers to inherit from `OEmbedProviderBase` as commented and which the `LottieFiles` provider already use.

I also updated it to use `QueryHelpers.AddQueryString()` method in .NET Core, which we also use in `ImageSharpImageUrlGenerator`:
https://github.com/umbraco/Umbraco-CMS/blob/0134199035cf4caf0deddc24648be5cdeb27d2f9/src/Umbraco.Web.Common/Media/ImageSharpImageUrlGenerator.cs#L97

### CODE REVIEW

**Comment by bjarnef** [comment]
@bergmania not sure if we can include `Microsoft.AspNetCore.WebUtilities` in `Umbraco.Core` project? ... and not sure why OEmbed providers are included in `Umbraco.Core` project while `ImageSharp` implementation exists in `Umbraco.Web.Common`. I would probably have expected these to exists in same project.

**Review by mikecp — APPROVED** [review]
Hi @bjarnef, thanks for following this up and for the "cleanup" PR 🙂
I'll be waiting for the feedback from @bergmania on your questions before merging, but for the rest it all looks OK to me!

**Comment by bergmania** [comment]
Hi..

From my point of view `Umbraco.Core` should not know about anything in `Microsoft.AspNetCore.*`. 

I think the reason OEmbed providers are in `Umbraco.Core` is mainly that they do not have any dependencies.  One could argue some of them should be in `Umbraco.Infrastructure`, as long as the baseclasses and abstractions are in `Umbraco.Core`.

`ImageSharp` is a dependency and is therefore welcome in `Umbraco.Infrastructure`, but `ImageSharp.Web` is a web-dependency so `Umbraco.Web.Common` sounds correct for that.

**Comment by bjarnef** [comment]
Hi @bergmania 
Okay, it was mainly to use `QueryHelpers.AddQueryString()` method in `OEmbedProviderBase` similar to `ImageSharpImageUrlGenerator.cs`, but it depends on `Microsoft.AspNetCore.WebUtilities`.

So I guess we can't use this extension here, unless `OEmbedProviderBase` was moved to another project like `Umbraco.Web.Common`.

**Comment by bergmania** [comment]
> So I guess we can't use this extension here, unless `OEmbedProviderBase` was moved to another project like `Umbraco.Web.Common`.

Yep, that's correct..  Querystring is a very web-aware thing :P

**Comment by bjarnef** [comment]
@bergmania I have reversed the changed to use `StringBuilder`.
It could alternatively use `UriBuilder` to construct the URL with querystring.

```
var uriBuilder = new UriBuilder(ApiEndpoint);
var query = HttpUtility.ParseQueryString(uriBuilder.Query);
query["url"] = WebUtility.UrlEncode(url);

foreach (var param in RequestParams)
{
    query[param.Key] = param.Value;
}

if (maxWidth > 0)
    query["maxWidth"] = maxWidth.ToString();

if (maxHeight > 0)
    query["maxheight"] = maxHeight.ToString();

uriBuilder.Query = query.ToString();

return uriBuilder.ToString();
```

image

**Comment by bjarnef** [comment]
This should also fix all the CodeQL-Build warning 😄

**Comment by bjarnef** [comment]
@bergmania @mikecp anything preventing this to be merged?

We can consider later if some of this should be restructured to use `Microsoft.AspNetCore.WebUtilities` or `UriBuilder` to contruct the querystring.

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Hey @bjarnef ,

Thanks for the cleanup, it's all ready to merge 😃

Cheers!

**Comment by bjarnef** [comment]
@mikecp merge conflicts resolved. I added a description to all providers, but we can adjust these further.

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Hi @bjarnef ,

Thanks for solving the conflicts and adding a description, they all look good! 👍
So this time let's  merge it for real 😅

**Comment by bergmania** [comment]
This will need to move to v11, as it is breaking.

**Comment by bergmania** [comment]
Reverted on v10 and reintroduced on v11

**Pull request merged**
