### PR TITLE
 Verify that the current member is approved and not locked out

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/3017

### Description

This PR ensures that the currently logged in member is approved and isn't flagged as logged out before allowing access to restricted content. Steps to reproduce can be found in #3017.

### Performance impact considerations

As-is (without this PR) the core only performs one round trip to the DB when validating the current member access (to fetch the member groups):

validate member approved before

With this PR, the core performs 4 round trips because it needs to fetch the current member (because they're not cached on application level):

validate member approved after

I have tried a few alternative approaches, including direct fetch via `MemberService`:

```cs
var member = _routingContext.UmbracoContext.Application.Services.MemberService.GetByUsername(membershipHelper.CurrentUserName);
// if the member has the "approved" and/or "locked out" properties, make sure they're correctly set before allowing access
var memberIsActive = member != null && member.IsApproved == true && member.IsLockedOut == false;
```

...but the result is exactly the same, because `MembershipHelper.GetCurrentMember()` uses `MemberService` to fetch the member.

Obviously these extra round trips aren't ideal. However... chances are pretty high that the round trips would be performed later anyway while rendering the page - e.g. for displaying the name and other data for current member somewhere on the page. And the member *is* cached on the request (I have double checked and tested this), which means the member will only be fetched once.

Lastly I don't think we really have a choice here, if we want to keep the "Approved" functionality of members. One can always hope that the application level cache will someday include members, which would solve the round trip issues.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Another Pr with lots of detail in the description Thanks!

**Comment by kjac** [comment]
Always 😀

**Comment by nul800sebastiaan** [comment]
Thanks @kjac - finally managed to review and test this one. I dropped back to using a few if-else statements insteasd of the huge `&& || != null ||&&@$$` thing that was a bit hard to decipher. Other than that it's great, thanks!

**Comment by kjac** [comment]
Awesome!

**Pull request merged**
