### PR TITLE
U4-11356 Events emitted from the grid on init, row added and item added

### PR DESCRIPTION
**Pull request by lars-erik**
…element and scope.

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description
Added extension points to the grid so we can make packages of misc. extensions that are currently PRs due to missing extension points. Should also be simple to add more and easily accept further PRs when new events are needed.

### CODE REVIEW

**Comment by dawoe** [comment]
@lars-erik 

I checked this one and can confirm that all events are fired.

Just out of curiousity what is the use case for this. For PR #2640 i can see the benefit, but can't figure out a use case for this one.

@nul800sebastiaan works fine

**Comment by lars-erik** [comment]
Hey @dawoe,
Thanks for taking the time to review.
Reg. use cases:
Tim (Attackmonkey) made a "lock grid for non-admins" package once. Søren and I made the copy paste one. None of it was possible to package without "hacking the core" by replacing grid.html, intercept a call or just make a custom copy of the editor. I'm opening it up, and who knows - maybe they'll be several new packages just because now we can. :)

**Comment by nul800sebastiaan** [comment]
Looks fine @lars-erik - just wondering what the additional `$uniqueId`s are for?

**Comment by lars-erik** [comment]
@nul800sebastiaan Being able to grab elements from the DOM by id.

**Comment by lars-erik** [comment]
For instance: The itemAdded event passes the grid DOM element, the cell js object and the item js object. To get the DOM element representing either, you need to look it up by the [data-whateverid] attribute and the $uniqueId of the js object.

**Comment by nul800sebastiaan** [comment]
Sweet, makes sense!

**Comment by lars-erik** [comment]
\o/

Love the new process!

**Comment by LennardF1989** [comment]
@lars-erik Out of curiousity, how would one hook into the "initializing" event? The only way I can imagine is making sure some Controller is already loaded on the page before the Grid Controller is loaded... But I can't really figure out a clean way for it. Any pointers?

**Comment by lars-erik** [comment]
@LennardF1989 The Umbraco "core" `eventsService` can be injected into anything and with it you can `subscribe` to any event, IE. the `grid.initializing` one.

For some reason the service isn't mentioned in the backoffice api.

**Comment by LennardF1989** [comment]
@lars-erik I get that, but the intializing -vent happens so early in the lifetime of a GridController instance, what kind of method would you use to listen for this event in time? I can only imagine making a dummy datatype (hidden/not visible) with an Angular Controller on it, which I add on the same DocumentType as where the Grid is... But I reckon there must be a cleaner way. Is there a way to load a controller when the Umbraco backoffice loads?

**Comment by lars-erik** [comment]
@LennardF1989 You can hook up a singleton in angular.module("umbraco").run(function(eventService) {}). See 1.1.5 module docs: https://code.angularjs.org/1.1.5/docs/api/angular.Module

**Comment by LennardF1989** [comment]
@lars-erik Great! I learned something new today, thanks!

**Comment by lars-erik** [comment]
\o/ :)

**Pull request merged**
