### PR TITLE
Limit link picker to content tree in content section

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12309

### Description

When having multiple tree root nodes in content section besides default configuration, e.g. moving Content Templates and Dictionary trees, the link picker was showing all trees and not limited to just content tree.

**Before**

image

**After**

image

Content Picker / MNTP already restrict the tree picker to content tree here:
https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Web.UI.Client/src/views/propertyeditors/contentpicker/contentpicker.controller.js#L190

### CODE REVIEW

**Review by nathanwoulfe — APPROVED** [review]
Hey @bjarnef looks good to me - nice clean change!

I'm holding off merging until I've confirmed where we're pushing community PRs (9.5 is done, and the final minor for 9, so not sure if we're 9.5.1 or straight to 10, hopefully the latter).

**Comment by bjarnef** [comment]
@nathanwoulfe yes, it a simple fix. It would be nice it is could be included in a patch of v9 as well. We have a project on v9 where we moved Content Templates to content section, so content editors can manage these.

I also checked Content Picker / MNTP, which only show content tree.

I guess it is safe to merge to v10 and then maybe cherry pick to v9? @nul800sebastiaan

**Comment by nathanwoulfe** [comment]
Updated base to v10/contrib, will let tests run before merging.

**Comment by nathanwoulfe** [comment]
Test failure likely due to the base changing - SDK would have been updated in 10.

**Pull request merged**
