### PR TITLE
V8: Make sure all user start nodes are shown in the media picker

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6408

### Description

See a detailed issue description in #6408

For some reason it's up to the `umb-media-grid` directive to filter out items that do not match the current media picker configuration and state. And this is what causes the problem: The `umb-media-grid` directive makes a few failed assumptions about the items passed to it, and thus ends up filtering out user start nodes that aren't on the same level as the first start node encountered.

This whole setup makes very little sense; `umb-media-grid` should simply display the items being passed to it. If any filtering of the items is required, the caller (e.g. the media picker) should be responsible for this. So... this PR moves the filtering to the media picker.

#### ⚠️ Possible breaking change ⚠️

This change may be considered breaking because the built-in filtering functionality of the `umb-media-grid` directive changes. Any 3rd party packages depending on this functionality will have to implement their own filtering logic.

Problem is... we can't fix the failed assumptions in `umb-media-grid` without introducing additional parameters to the directive. As the functionality in question would rely on these parameters it would be a functional breaking change regardless. And then I'd rather opt to clean up `umb-media-grid` and move the filtering to the media picker.

#### The result

With this PR applied, a user with these media start nodes:

image

...is able to navigate the media picker as is expected in #6408:

media-picker-user-start-nodes

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @kjac ,

Thanks once again!

Poornima

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by poornimanayar** [comment]
Hi @kjac ,

That totally works and I agree with you on what you have mentioned about the directive. Since its a potential breaking change I will let @nul800sebastiaan or someone else from the HQ to have a look before its all approved and merged in :-)

Poornima

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by poornimanayar** [comment]
@nul800sebastiaan May be someone from the HQ can cast an eye on this one as this has a potential breaking change as @kjac  suggests.

**Comment by nul800sebastiaan** [comment]
We'll have a chat about it and see if it's an acceptable breaking change or not! Functionality looks great though! 👍

**Pull request closed without merging**
