### PR TITLE
U4-8509 - Added woff2 mime type

### PR DESCRIPTION
**Pull request by electricsheep**
Added the woff2 mime type to the web config to fix http://issues.umbraco.org/issue/U4-8509

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks! I know it's a small thing but would you mind formatting it so it has the same indentation as the other ones please?

**Comment by electricsheep** [comment]
Done. Couldn't see the difference in VS, had to open in notepad++. What tab/space settings do you use for the project?

**Comment by nul800sebastiaan** [comment]
Sweet, thanks!

We use whatever the default is in Visual Studio for that particular filetype. :)

**Comment by nul800sebastiaan** [comment]
👍

**Pull request merged**
