### PR TITLE
Use strongtyped Models as grid and RTE config

### PR DESCRIPTION
**Pull request by bielu**
### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description
When I was working for one of the internal projects in my Company I had a need to use strong type models in a grid configuration and I notice in Umbraco source code comment which was saying:
`// TODO: Make these strongly typed, for now this works though`
And I decide to make PRs with my models, which I am using to set up grid configs.

### CODE REVIEW

**Comment by tompipe** [comment]
Nice. But is there some overlap with the models at `Umbraco.Core.Models.GridValue` etc?

**Comment by bielu** [comment]
@tompipe will look into that :)

**Comment by bielu** [comment]
A quick overview of what is in models, which are overlapping:

| Model Name  | Umbraco.Core.Models                                                                                                                                                                               | Umbraco.Web.Models.PropertyEditorsConfigs |
|-------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------|
| GridSection |  public string Grid, public IEnumerable<GridRow> Rows |   public int grid,public bool AllowAll,public List<string> Allowed                                         |
| GridArea    | public string Grid, public IEnumerable<GridControl> Controls,public JToken Styles,public JToken Config                                                                                                                                                                                                  |   public int Grid,public bool AllowAll,public List<string> Allowed                                         |

**Comment by bielu** [comment]
@ronaldbarendse 
>I've added some suggestions on the models, but they should probably be added as child classes of GridConfiguration (like ListViewConfiguration),
I don't really agree they should be child classes here and tbh I think Listview subclasses should be extracted and be separate classes but yeah here we will have a different opinion about things. Also, they shouldn't inherit from Jobject as we actually convert JTokens/Jobject to real object somewhere in code via Newtonsoft.Json.  Rest Of Comment in code looks ok and going to merge them into the commit. :)

**Comment by bielu** [comment]
>The Umbraco.Core.Models.GridValue should be used with an IPropertyValueConverter, but that's also something on the to-do list:
True it should use also that will add that soon to my PR and update also GridValueConverter.cs

**Comment by bielu** [comment]
@ronaldbarendse I just look into values which are propagated in both and they are different, ares in grid values != ares in backoffice :) it is why I didn't changed gridvalue :)

**Pull request closed without merging**
