### PR TITLE
Disable sortable if readonly or max is limited to one item

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/14116

### Description
When property editor is readonly or maximum items is configurated to a single item (including single block mode) the sortable should be disabled.

- Content Picker
- MNTP (maximum 1)
- Multi URL Picker (maximum 1)
- Block List (maximum 1)

https://github.com/umbraco/Umbraco-CMS/assets/2919859/9e9e0460-7169-49f2-b387-fac47ec46ff9

However since some picker allow to add more items (although limited to max 1) I am not sure if this should be sortable? E.g. content picker / MNTP doesn't show the add button when limit is reached. And what about Block Grid if limited to maximum 1?

https://github.com/umbraco/Umbraco-CMS/assets/2919859/01dd4886-abd6-4840-8ace-f473e3e57856

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
@bjarnef Thanks, the Core Collabs team will get back to you soon!

**Comment by emmagarland** [comment]
Hi @bjarnef,

Thanks again for this sorting PR, it I have passed it on to HQ for discussion and will let you know what the response is when I know!

Best wishes,

Emma

**Comment by nielslyngsoe** [comment]
Hi @bjarnef

I fully understand your interest in dealing with this case, as the 'add' button acts as an invitation to add more content.

I'm not fully settled on how to go about this specific case (maximum 1 case), but here is some perspective and thoughts:

The general concept is never to use validation as a limitation.

The main case to support this is the following:
* Imagine a property limited to three items.
* The already property has three content items.
* The user copies one or even more items from another page.
* The user pastes the new items, into the property, making the total of items 4+. One too many.

To give the user freedom to work with the content, there is no limit to how many items there can exist while working with it.
This enables the user to freely choose which item to remove. In terms of Blocks, the user might want to copy some properties from an existing block into the new ones, before deleting the old one.

This freedom is what we need to support in general.

Does the user not need this freedom when working with a single-item list? I guess that depends on the case. So the question comes to mind. Should we limit this, or should the user still be able to create/paste a new item, then delete the existing item afterward? Basically to keep the existing content as a reference while working on the new one.

Another slim case: is if someone had existing content with multiple items and then changes the configuration to a maximum of one. Then the editor should still be able to manage all three and keep the right one the next time they publish. (also relevant when reverting content)

I think it all makes sense, but we haven't simply spent enough time on the matter, investigating what we can do to emphasize that we are out of the room, while still enabling the user to add more.

Options are both within indications(text, color, symbols..) on the add button. and/or provide a more visual/clear validation indication. So the user is not in doubt that they have too much content.

As you documented above we now have a Single Item Mode for the Block List Editor. This both changes the output in Razor and limits the user to only having one item. Since it's an additional configuration, I find it more acceptable that the experience changes when this has been actively chosen. This as well limits the user to never paste multiple items.

In New Backoffice, we most likely also will enable the user to drag items across properties. If limitations are enforced the user would not be able to simply switch the blocks between two properties.

Let me know what you think about the topic with those perspectives in mind. Thanks!

**Comment by bjarnef** [comment]
Hi @nielslyngsoe 

Good points :)

I haven't fully tested how the pickers act when changing a multi picker to a single picker.

The content picker, MNTP and Multi URL pickers hide the "add" button and doesn't allow adding more items.  But I am not sure if it allow to paste more items or publish existing multiple items (I think it shows a validation error).

Regarding Block specific pickers it allow to add more items and re-arrange these before saving, so I guess the "new" approach makes sense to keep sorting Even maximum is limited to one.

Regarding single block mode, I think it makes sense to disable sorting as the item it already scaffolded either inline or opened as overlay.

**Comment by nielslyngsoe** [comment]
@bjarnef yes, that's right. In Single Item Mode then sorting should be disabled :-) As well as the add-button disappears.
And the 'paste' feature should turn into a 'replace' feature, only ever pasting one item.

**Comment by bjarnef** [comment]
@nielslyngsoe I have updated this, so block list only disable sorting is readonly or single block mode.
Content Picker, MNTP and Multi URL Picker have sorting disabled when limited to maximum one item (which hide the add-button). I seems these pickers currently doesn't have the copy/paste feature though.

I noticed a bit inconsistency as the Content Picker / MNTP and Multi URL Picker have the "Remove all items" property action, but only Content Picker / MNTP has this on single mode, while Multi URL Picker (Single URL Picker) does not.

image

image

**Comment by bjarnef** [comment]
I also noticed sorting is enabled in media picker 3, when not configured to allow picking multiple items.

https://github.com/umbraco/Umbraco-CMS/assets/2919859/a3dfa124-670e-4f34-a595-0ddf2a27e3d1

**Comment by bjarnef** [comment]
I disabled sorting in single mode for media picker 3 as well, but doing so, it seems to have odd behaviour the image itself can be dragged and dropped in same editor.
It seems the draggable should be disabled.


https://github.com/umbraco/Umbraco-CMS/assets/2919859/df7d52cc-251b-4b45-be9e-99b790871ad0

**Comment by bjarnef** [comment]
I can disable draggable of the existing items in `<umb-media-card>` and uploaded image as these can otherwise be dragged to new uploaded items.

However it seems to be possible to drag and drop new items to a single mode picker as well, so not sure if it makes sense to disable sorting in single mode picker as existing and newly uploaded file(s) can't be sorted, but maybe that's okay as the single media pickers then doesn't have sorting enabled (where the add-button also is shown only when the picker is empty/blank).

https://github.com/umbraco/Umbraco-CMS/assets/2919859/19be30e8-3ee6-4ec3-a55a-65ae93c4382c

**Comment by emmagarland** [comment]
Hi @bjarnef 

Thanks so much for this, when I have capacity I will look to pull the code and test it locally too.

@nielslyngsoe thanks for the detailed reply; as discussed, these tasks can be worked on in another PR:

- The add-button disappears
- The 'paste' feature should turn into a 'replace' feature, only ever pasting one item

Please let me know if there is anything else I need to consider before testing,

Best wishes

Emma

**Comment by ronaldbarendse** [comment]
> The content picker, MNTP and Multi URL pickers hide the "add" button and doesn't allow adding more items. But I am not sure if it allow to paste more items or publish existing multiple items (I think it shows a validation error).

Just to chime in on this behaviour: adding more items than configured on the data type should indeed be allowed (for the reasons Niels already mentioned), but show a message that you've exceeded the maximum, allow saving the content and only show validation errors when trying to publish the content (to still enforce this limit on published content). Data types that have single item mode configured can differ from this behaviour, so changing the paste action to a replace action would then indeed make sense...

**Comment by bjarnef** [comment]
@ronaldbarendse yeah, that's the behavior of the new pickers like Media Picker 3, Block List, etc... but not the older pickers which hide the add-button when the limitation was reached.
I do think switching from a multi picker to a single picker (or changing configuration of existing picker to maximum 1) still kept the existing items in e.g. MNTP, but save/publish would show a validation error.

**Comment by emmagarland** [comment]
Hi @bjarnef 

I have been testing this PR and wanted to share my steps. 

I have also tweaked the “items” messages to “item(s)” to cater for the fact there may only be 1 item, in en-us.xml and en.xml and in the files themselves. Please could you confirm you are happy with these changes I have pushed to your branch? 😊

The steps I ran through are:

1.	Setup Umbraco with a content picker, an MNTP, a multi URL picker and a block list picker (not in single block mode), with defaults for now (not limited to 1):
image

 
2.	Test that you can sort all the multiple items (except the content picker)
3.	Change to limit all pickers to maximum 1 item
4.	Return to your test page and observe the messages:
 
image

5.	Note that I can still sort and drag the existing items while there are > 1
6.	Remove the additional items
7.	I can no longer drag the items, but I still observe the draggable cursor crosshair symbol
8.	Save, publish, and refresh the page
9.	The draggable cursor crosshair symbol disappears
image

 
10.	Change the block list to Single Block mode
 
image


11.	Return to the test page and observe the block list is no longer sortable
 
image


Is this the behaviour you were expecting @bjarnef and is there anything else I should test?


Emma

**Comment by bjarnef** [comment]
Hi @emmagarland 

Regarding the older picker hiding add-button when max is reached, I think these always have sorting disabled when maximum is set to 1.
The cursor style is based on if sorting is enabled or not.

**Comment by emmagarland** [comment]
Thanks @bjarnef.

On my testing, the cursor mode disappeared once I had saved, published and refreshed the page, but I may have had something cached (step 8 on my list).

If you are happy with my updates to your branch I will merge this PR.

Just to clarify, are either of these tasks complete or do they need to be worked on in another PR?

- The add button disappears
- The 'paste' feature should turn into a 'replace' feature, only ever pasting one item

Many thanks

Emma

**Comment by bjarnef** [comment]
Hi @emmagarland 

Yes, it seems fine to me 🙂

Regarding the other question.
- The older pickers used the approach to hide add-button, when max was reached, but starting from Media Picker 3 and Block List the newer approach is the show validation instead. Only single block mode doesn't show the add-button.
- The paste/replace is a new feature. These pickers like Content Picker, MNTP, Multi URL Picker only show property action to remov/clear item(s).

**Comment by emmagarland** [comment]
Thanks a lot @bjarnef!

It has now been successfully merged! 🙌

This ensures that sortable mode is disabled for situations where there is only one item #14116. 

The other considerations would be for separate PRs if required:

- The add button disappears
- The 'paste' feature should turn into a 'replace' feature, only ever pasting one item

Your efforts are again much appreciated, 

Emma

**Pull request merged**
