### PR TITLE
Fix for exception throw when validating URLs

### PR DESCRIPTION
**Pull request by whatwasmyusername**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

This fixes https://github.com/umbraco/Umbraco-CMS/issues/7688

### Description

* Replaced the use of FileInfo with Path.GetExtension to support URL-based filenames
* This can be tested by:
  * Setting up an Azure or S3 media file system
  * Uploading a media item with a Umbraco.FileUpload property (i.e. the default File type)
  * Re-save the media item

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hello hello!

Thanks for the PR and congrats on the first PR to this repo! We'll take a look and when we merge you'll get a nice new contrib badge on your our.umbraco.com profile so let us know where to find you.

We'll be in touch if we need anything,

Emma

**Comment by nul800sebastiaan** [comment]
I would love to hear what @kimschurmann thinks as well, since they changed this in PR https://github.com/umbraco/Umbraco-CMS/issues/7688 and I would like to make sure that we're not breaking that scenario again with this update. I can't see why it would break though. 🤔

**Comment by kimschurmann** [comment]
Hi @nul800sebastiaan 

I currently do not have the time to look at it, but my colleague @kjac probably knows what is going on and could perhabs be talked into looking at the issue?

**Comment by rasmusjp** [comment]
I don't think the fix breaks anything as `Path.GetExtension(filename)` and `new FileInfo(filename).Extension` essentially does the same, the different is that `new FileInfo(filename)` tries to demand some file permissions which it can't because the filename isn't a valid path.

As far as I can tell this is only a problem with the UmbracoFileSystemProviders.Azure if you disable the virtual path provider by adding the `AzureBlobFileSystem.DisableVirtualPathProvider=true` app setting, then it stores the full Url to the media item instead of the relative one.

**Comment by stevetemple** [comment]
Should do the same thing, except the Path.GetExtension is more lightweight, doesn't do anything with the actual file system, just string manipulation so is just a better choice for this anyway. 

A unit test around this, would prove that this works identically to the old version, happy to knock something up if that's desired.

**Comment by nul800sebastiaan** [comment]
@rasmusjp Oh, fantastic feedback, in that case neither of these methods would work! 

So it would be better to get the extension through a method like this: https://stackoverflow.com/a/52748299/5018

As has been pointed out to me as well, this also includes a few unit tests, which is great.

So it looks like the solution should be: to get the file extension of a URL or file name, feed it into this method as a string. Then we don't need to worry about filesystem operations. Additionally, this method has unit tests which we can use and expand upon. 

Could you make those changes @whatwasmyusername ? I would add this to `Umbraco.Core.StringExtensions` so it can be used easily. And there's a bunch of unit tests for that class already as well so they can be expanded upon.

**Comment by nul800sebastiaan** [comment]
@rasmusjp Oh, fantastic feedback, in that case neither of these methods would work! 

So it would be better to get the extension through a method like this: https://stackoverflow.com/a/52748299/5018 - but without the `FromURL`, it's getting the extension from a string, whether it's a URL or not.

As has been pointed out to me as well, this also includes a few unit tests, which is great.

So it looks like the solution should be: to get the file extension of a URL or file name, feed it into this method as a string. Then we don't need to worry about filesystem operations. Additionally, this method has unit tests which we can use and expand upon. 

Could you make those changes @whatwasmyusername ? I would add this to `Umbraco.Core.StringExtensions` so it can be used easily. And there's a bunch of unit tests for that class already as well so they can be expanded upon.

**Comment by whatwasmyusername** [comment]
Sounds great @nul800sebastiaan .  I'll go the route of adding the string extension.

**Comment by whatwasmyusername** [comment]
Thanks for the recommendations.  

I've added a few extra test cases based on your suggestion and took a look at using your regex.  The regex you threw out there didn't work for strings without question marks in them, and it assumed letters and numbers only in the extension, so I made a couple of changes to get it to pass all of the tests.  

I didn't see any performance changes (all tests were already executing in the 4-10ms range for me, though admittedly that doesn't really constitue extensive testing around memory usage or big pieces of data), but If you really think that's a better route to go, I will push up a new commit.

**Comment by kjac** [comment]
@whatwasmyusername I do believe it's a better route to go. My concern with the current implementation is that someone will use the extension method to process larger sets of data and thus put an unnecessary strain on the CPU.

**Comment by whatwasmyusername** [comment]
Thanks for moving this along!  Here's [my profile](https://our.umbraco.com/members/whatwasmyusername/).

**Comment by nul800sebastiaan** [comment]
@whatwasmyusername Sweet, badge added! 👍 Thanks again!

**Pull request merged**
