### PR TITLE
Cleanup radiobuttonlist prevalue editor

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
I noticed the radiobuttonlist prevalue editor wasn't consistent with checkboxlist prevalue editor. Furthermore the view was a bit cluttered.

I have simplified this to make it a bit more consistent and also ensured no `<ul>` is rendered if no prevalues are available.

Test settings to paste into e.g. grid settings, which has an example of string array, array of object and an combined + an option with no label property (fallback to value property).

```
[
  {
    "label": "Test 1",
    "description": "Test 1",
    "key": "test1",
    "view": "radiobuttonlist",
    "prevalues": [
      "value_1",
      "value_2",
      "value_3"
    ]
  },
  {
    "label": "Test 2",
    "description": "Test 2",
    "key": "test2",
    "view": "radiobuttonlist",
    "prevalues": [
      {
        "label": "Value one",
        "value": "value_1"
      },
      {
        "label": "Value two",
        "value": "value_2"
      },
      "value_3"
    ]
  },
  {
    "label": "Test 3",
    "description": "Test 3",
    "key": "test3",
    "view": "radiobuttonlist",
    "prevalues": [
      {
        "label": "Value one",
        "value": "value_1"
      },
      {
        "value": "value_2"
      },
      {
        "label": "Value three",
        "value": "value_3"
      }
    ]
  }
]
```

https://user-images.githubusercontent.com/2919859/192886902-86f56090-d39e-4a86-bfa5-ebe2fd9ac6c3.mp4

### CODE REVIEW

**Comment by bjarnef** [comment]
@mikecp I think this would cleanup the login in the view file and make it more consistent.

**Comment by emmagarland** [comment]
Hi @bjarnef 

I have found you have 2 open PRs with no reply yet, this one and #13074, so apologies for that!

I will review this one as soon as I can, it is on my list. 

Best wishes

Emma

**Comment by emmagarland** [comment]
Hi @bjarnef 

Now that [Grid layout](https://docs.umbraco.com/umbraco-cms/fundamentals/backoffice/property-editors/built-in-umbraco-property-editors/grid-layout) is marked as obsolete, do you have a way I can replicate this on the latest v12, please? Can I use a block grid or just a normal radio-button list?

Sorry, the delay has meant this happened 🙂 

Thanks

Emma

**Comment by emmagarland** [comment]
Hi @bjarnef 

Please excuse the delay over the summer!

I have attempted to replicate this with a property editor using the attached property editor example, and the fields are the prevalues you are using.

However, I'm not getting any radio buttons showing up. I'm not sure if I needed custom JS/HTML when using the built-in radio button views etc. though?

Property editor view:
image

Content view:
image

Custom property editor manifest (no views or js):

[PRPropertyEditor13073.zip](https://github.com/umbraco/Umbraco-CMS/files/12560044/PRPropertyEditor13073.zip)

If you have time, please can you help guide me on what I need to update in the property editor creation to be able to test your PR?


Best regards

Emma

**Comment by bjarnef** [comment]
Hi @emmagarland 

I checked this and I see what you mean.
It actually seems the property editor always return this `config` object and thus prevalues are returned as empty array.

image

If used the the legacy grid editor.

**Comment by bjarnef** [comment]
@emmagarland actually I think `$scope.model.config` in old days could be null inside property editors, but it may be a regression in Umbraco 9+ (.NET Core) since the config property on `ConfigurationField` is no longer null.

**Comment by bjarnef** [comment]
It seems `$scope.model` won't return a `prevalues` property directly in the property editor since the `ConfigurationField` class doesn't have this field/property.

I think it was only used/supported in the legacy grid editor, where the JSON configuration initially has `prevalues` property, but later also a `config` object as some other prevalue editors then were supported to use in the legacy grid layout editor (but not legacy at that time).

**Comment by emmagarland** [comment]
Hi @bjarnef 

Thanks for your updates and the config. I've pasted that in and I now see the following in the back-office Settings section:

image

Although it is blank in the content editor:

image

Going back to the original purpose of the PR, to clean up the radio button list pre-value editor, is there a way to test this in the content section using this config?

Best, 

Emma

**Comment by bjarnef** [comment]
Hi @emmagarland

How does it looks if changing the property editor to checkboxlist?

The changes should mostly be regarding the prevalue editors, but I will check how the selected prevalues are used in the property editors.

**Comment by emmagarland** [comment]
Ah,. @bjarnef I just realised you're only testing the settings on your original video, anyway. Don't worry about the content side if that isn't part of this PR. 

Thanks

Emma

**Comment by emmagarland** [comment]
> How does it looks if changing the property editor to checkboxlist?

It throws an exception upon first changing it, but that is presumably because the list values are different. When I resave the doctype it is fine. 

Emma

**Comment by emmagarland** [comment]
Hi @bjarnef 

I've tested this PR #13073 cleanup and it works well for me regarding the radiobutton lists and checkbox lists being available in the prevalue editors and doctypes (as shown in my previous comment).

It has now been successfully merged and targeted for version `12.3.0`! 🙌

Also, as per #13074, I've tagged it with `project\bellissima` in case you are also interested in making the same changes for v14. As I said before, I have yet to explore property editors in v14. If this isn't possible, the tag will remind the HQ team to implement the same functionality before releasing the new back-office to ensure feature parity.

Thanks once again for your patience as I worked through this one, too! 

Emma

**Pull request merged**
