### PR TITLE
In addition to #6236 - now this now longer keeps appending the conten…

### PR DESCRIPTION
**Pull request by nul800sebastiaan**
…t name on each change of the language dropdown

image

### CODE REVIEW

**Comment by bjarnef** [comment]
@nul800sebastiaan you might also want to add a space after colon, which I added in this commit https://github.com/umbraco/Umbraco-CMS/pull/6418/commits/f77430234848abfc9248b27d8c1abe58c3433e92

**Comment by nul800sebastiaan** [comment]
@bjarnef I did!! 😁👍

**Comment by nul800sebastiaan** [comment]
FYI something went wrong with this commit and I ammended it here: https://github.com/umbraco/Umbraco-CMS/commit/7de7e59f5543031fa0635499306509a42f57f3d7

**Comment by nul800sebastiaan** [comment]
Cherry picked for 8.2.1 - e37434d816221cd949c1c9855993e8d3e9683d5d

**Pull request merged**
