### PR TITLE
Ensure macromodel implements IContentModel, fixing #7504

### PR DESCRIPTION
**Pull request by tompipe**
Implement IContentModel on PartialViewMacroModel - fixing #7504

### CODE REVIEW

**Comment by emmaburstow** [comment]
Brill! Lovely spot and thanks for making it a PR. 

Speak soon,

Em

**Comment by tompipe** [comment]
What's the reason you consider it a breaking change?

**Comment by kjac** [comment]
I may be wrong (and by all means please prove me wrong here), but far as I know.. adding an interface to a type is a binary breaking change to that type..?

**Comment by tompipe** [comment]
That would usually be the case, but perhaps it's not breaking as such. It doesn't add/remove any  properties, and it's public 'surface' is effectively unchanged, it already contained the Content property, so any existing code should remain unaffected (in theory 😂)

Checking guidance for .net core's definitions of acceptable/breaking changes, I guess it falls under 'REQUIRES JUDGMENT' 🤷‍♂️

https://docs.microsoft.com/en-us/dotnet/core/compatibility/#types

**Comment by kjac** [comment]
@tompipe it's not breaking on code level as such, since you can just recompile and be on your way. However if you upgrade without recompiling, I do believe things will break "just" because the interface was added. At least that's how I conceive it.

Perhaps @Shazwazza has a perspective on this?

**Comment by Shazwazza** [comment]
Additive changes are fine and will not require you to recompile.

**Comment by Shazwazza** [comment]
see https://our.umbraco.com/Documentation/Development-Guidelines/breaking-changes

**Comment by nul800sebastiaan** [comment]
Thanks @tompipe! 👍 

And thanks Shan and Kenn for the discussion, good refresher on breaking changes!

**Pull request merged**
