### PR TITLE
V8: Add in Recycle Bin context message

### PR DESCRIPTION
**Pull request by warrenbuckley**
This is a super simple PR to add a message bar to give context that this node you are viewing is in the recycle bin. This should make a @JeffreyPerplex a little happier too as this improvement was from one of his dreams at his CG19 talk :)

- Adds language keys to en_us.xml and en.xml
- New CSS style rule added
- New HTML markup added to display message based off the trashed bool that's in the API response/data we already have

image

### CODE REVIEW

**Comment by warrenbuckley** [comment]
Yep will fix up messages and then you can re-review

**Comment by warrenbuckley** [comment]
All good for you to go @kjac

**Comment by kjac** [comment]
@warrenbuckley I'm afraid there's a merge conflict for one of the langage files. Could you please resolve it when you find a little time?

Please note that I have changed the base branch from `v8/dev` to `v8/contrib` for this PR. This means you'll have to pull `v8/contrib` and merge it into your PR branch to resolve the conflicts.

**Comment by warrenbuckley** [comment]
EUGH I hate dealing with merge conflicts with lang files will try & sort this out before I have a meeting

**Comment by kjac** [comment]
Thanks @warrenbuckley - merged and all good ⭐️

**Pull request merged**
