### PR TITLE
Fix for issue 13017 - BeginUmbracoForm doesn't work with custom umbraco routes

### LINKED ISSUE #13017: BeginUmbracoForm doesn't work with custom umbraco routes
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.2.0

### Bug summary

Surface controller actions are not hit when rendering an Umbraco form from an [Umbraco custom routes](https://our.umbraco.com/documentation/reference/routing/custom-routes/).

This used to work with the v8 equivalent setup (UmbracoVirtualNodeRouteHandler).

In v10 (and presumably v9 also) the alternate routing that takes place when a ufprt is present in the request only takes place for the dynamic controller route and not custom Umbraco routes.

### Specifics

N/A

### Steps to reproduce

1. Create a new Umbraco 10 site & initialize.
1. Create a document type (with template) named Home (no properties required).
1. Create an instance of Home at root.
1. Copy code samples below into project
1. Form is handled appropriately from `/` but not from `/demo/`

### Home.cshtml
```cshtml
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.Home>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
    Layout = null;
}

<h1>@Model.Name</h1>

@using (Html.BeginUmbracoForm<DemoSurfaceController>("Handle"))
{
    @Html.TextBox("name")
    <input type="submit"/>
}
```

### Demo.cs
```csharp
public class DemoComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.Services.Configure<UmbracoPipelineOptions>(options =>
        {
            options.AddFilter(new UmbracoPipelineFilter(nameof(DemoPageController))
            {
                Endpoints = app => app.UseEndpoints(endpoints =>
                {
                    endpoints.MapControllerRoute(
                        "DemoPageController",
                        "demo",
                        new {Controller = "DemoPage", Action = "Index"});
                })
            });
        });
    }
}

public class DemoPageController : UmbracoPageController, IVirtualPageController
{
    private readonly UmbracoHelper _umbracoHelper;

    public DemoPageController(
        ILogger<UmbracoPageController> logger,
        ICompositeViewEngine compositeViewEngine,
        UmbracoHelper umbracoHelper) : base(logger, compositeViewEngine) =>
        _umbracoHelper = umbracoHelper;

    public IPublishedContent? FindContent(ActionExecutingContext actionExecutingContext) =>
        _umbracoHelper.ContentAtRoot().First();

    public IActionResult Index() =>
        View("~/Views/Home.cshtml", CurrentPage);
}

public class DemoSurfaceController : SurfaceController
{
    public DemoSurfaceController(
        IUmbracoContextAccessor umbracoContextAccessor,
        IUmbracoDatabaseFactory databaseFactory,
        ServiceContext services,
        AppCaches appCaches,
        IProfilingLogger profilingLogger,
        IPublishedUrlProvider publishedUrlProvider)
        : base(umbracoContextAccessor, databaseFactory, services, appCaches, profilingLogger, publishedUrlProvider)
    { }

    public IActionResult Handle(string name) =>
        Ok(new {name});
}
```

### Expected result / actual result

Should see output from DemoSurfaceController Handle() on submission of from from /demo/

### PR DESCRIPTION
**Pull request by justin-nevitech**
**Summary**

This fixes #13017 (https://github.com/umbraco/Umbraco-CMS/issues/13017) which is an issue displaying a custom Umbraco route and a virtual page controller after submitting a form to a surface controller.

**Description**

When using a custom Umbraco route and a virtual page controller which submits a form using a surface controller, the surface controller action method is called but control is not returned to the virtual page afterwards resulting in a 404 error.  This is because the surface controller is invoked before the action filter for the virtual page is called which means the route values (and indeed the content for the published request) is not setup correctly to return to the virtual page after the surface controller action is executed.  It also means the current page is not set in the surface controller for the virtual page.

When using a virtual page controller, the route values and the content (via FindContent) are executed as part of an action filter that is called when the virtual page controller action is invoked.  This code is never called after a form has been submitted via a surface controller so a 404 is displayed as no Umbraco content can be found at that URL.

The fix for this is to ensure the virtual page controller route values and content are setup before the form is handled so control can be correctly returned to the virtual page route via RedirectToCurrentPage and also so the CurrentPage correctly resolves to the content that has been returned via FindContent.

I have moved some of the code and logic that was previously in the UmbracoVirtualPageFilterAttribute class into a separate re-usable UmbracoVirtualPageRoute class which also gets called from UmbracoRouteValueTransformer prior to a surface controller form being handled.  I have deliberately left the existing virtual page action filter in place and the IVirtualPageController interface as it was so this does not break any existing code or routing.

**Testing**

To test, create a home page (alias homePage) and a hijacked page (alias hijackedPage) and allow the hijacked page under the home page (no other properties are required).  Create a home page node and underneath that a hijacked node and add the following code/templates:

Demo.cs

```
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Umbraco.Cms.Core.Cache;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Logging;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.Routing;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Infrastructure.Persistence;
using Umbraco.Cms.Web.Common;
using Umbraco.Cms.Web.Common.ApplicationBuilder;
using Umbraco.Cms.Web.Common.Controllers;
using Umbraco.Cms.Web.Website.Controllers;

namespace Umbraco.Cms.Web.UI
{
    public class DemoComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.Services.Configure<UmbracoPipelineOptions>(options =>
            {
                options.AddFilter(new UmbracoPipelineFilter(nameof(DemoPageController))
                {
                    Endpoints = app => app.UseEndpoints(endpoints =>
                    {
                        endpoints.MapControllerRoute(
                            "DemoPageController",
                            "demo",
                            new { Controller = "DemoPage", Action = "Index" });

                        endpoints.MapControllerRoute(
                            "TestController",
                            "/test/",
                            new { Controller = "Test", Action = "Index" })
                                .ForUmbracoPage((actionExecutingContext) =>
                                {
                                    var umbracoHelper = actionExecutingContext.HttpContext.RequestServices.GetService<UmbracoHelper>();
                                    return umbracoHelper?.ContentAtRoot().First()!;
                                });
                    })
                });
            });
        }
    }

    public class TestController : UmbracoPageController
    {

        public TestController(
                    ILogger<UmbracoPageController> logger,
                    ICompositeViewEngine compositeViewEngine)
                    : base(logger, compositeViewEngine)
        { }

        [HttpGet]
        public IActionResult Index()
        {
            return View("HomePage", CurrentPage);
        }
    }

    public class DemoPageController : UmbracoPageController, IVirtualPageController
    {
        private readonly UmbracoHelper _umbracoHelper;

        public DemoPageController(
            ILogger<UmbracoPageController> logger,
            ICompositeViewEngine compositeViewEngine,
            UmbracoHelper umbracoHelper) : base(logger, compositeViewEngine) =>
            _umbracoHelper = umbracoHelper;

        public IPublishedContent? FindContent(ActionExecutingContext actionExecutingContext) =>
            _umbracoHelper.ContentAtRoot().First();

        [HttpGet]
        public IActionResult Index() =>
            View("~/Views/HomePage.cshtml", CurrentPage);
    }

    public class DemoSurfaceController : SurfaceController
    {
        public DemoSurfaceController(
            IUmbracoContextAccessor umbracoContextAccessor,
            IUmbracoDatabaseFactory databaseFactory,
            ServiceContext services,
            AppCaches appCaches,
            IProfilingLogger profilingLogger,
            IPublishedUrlProvider publishedUrlProvider)
            : base(umbracoContextAccessor, databaseFactory, services, appCaches, profilingLogger, publishedUrlProvider)
        { }

        //public IActionResult Handle(string name) =>
        //    Ok(new { name });

        [HttpPost]
        public IActionResult HandleCurrentPage(string name)
        {
            var currentPage = CurrentPage;
            ViewData["name"] = name;
            TempData["name"] = name;
            return CurrentUmbracoPage();
        }

        [HttpPost]
        public IActionResult HandleRedirectToCurrentPage(string name)
        {
            var currentPage = CurrentPage;
            ViewData["name"] = name;
            TempData["name"] = name;
            return RedirectToCurrentUmbracoPage();
        }

        [HttpPost]
        public IActionResult HandleRedirectToCurrentUrl(string name)
        {
            var currentPage = CurrentPage;
            ViewData["name"] = name;
            TempData["name"] = name;
            return RedirectToCurrentUmbracoUrl();
        }
    }

    public class HijackedPageController : RenderController
    {
        public HijackedPageController(ILogger<HijackedPageController> logger, ICompositeViewEngine compositeViewEngine, IUmbracoContextAccessor umbracoContextAccessor)
            : base(logger, compositeViewEngine, umbracoContextAccessor)
        {
        }

        public override IActionResult Index()
        {
            ViewData["Hijacked"] = "Yes!";

            return CurrentTemplate(CurrentPage);
        }
    }
}

```

HomePage.cshtml

```
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
    Layout = null;
}

<h1>@Model.Name</h1>

@using (Html.BeginUmbracoForm<DemoSurfaceController>("HandleCurrentPage"))
{
    @Html.TextBox("name")
    <button type="submit">Handle Current Page</button>
}

@using (Html.BeginUmbracoForm<DemoSurfaceController>("HandleRedirectToCurrentPage"))
{
    @Html.TextBox("name")
    <button type="submit">Handle Redirect To Current Page</button>
}

@using (Html.BeginUmbracoForm<DemoSurfaceController>("HandleRedirectToCurrentUrl"))
{
    @Html.TextBox("name")
    <button type="submit">Handle Redirect To Current URL</button>
}

<p>View Data: @ViewData["name"]</p>

<p>Temp Data: @TempData["name"]</p>

```

HijackedPage.cshtml

```
@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.HijackedPage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
	Layout = null;
}

<h1>@Model.Name</h1>

@using (Html.BeginUmbracoForm<DemoSurfaceController>("HandleCurrentPage"))
{
    @Html.TextBox("name")
    <button type="submit">Handle Current Page</button>
}

@using (Html.BeginUmbracoForm<DemoSurfaceController>("HandleRedirectToCurrentPage"))
{
    @Html.TextBox("name")
    <button type="submit">Handle Redirect To Current Page</button>
}

@using (Html.BeginUmbracoForm<DemoSurfaceController>("HandleRedirectToCurrentUrl"))
{
    @Html.TextBox("name")
    <button type="submit">Handle Redirect To Current URL</button>
}

<p>Hijacked: @ViewData["Hijacked"]</p>

<p>View Data: @ViewData["name"]</p>

<p>Temp Data: @TempData["name"]</p>

```

**Tests**

Scenario 1 - Home Page (this page has a normal render controller)

1. Navigate to /
2. Enter a name into the top text field and click Current Umbraco Page - The form should submit and retain the model, view data and temp data.
3. Enter a name into the middle text field and click Redirect to Current Page - The form should submit but only the temp data should be retained (as expected after a redirect).
4. Enter a name into the bottom text field and click Redirect to Current URL - The form should submit but only the temp data should be retained (as expected after a redirect).

Scenario 2 - Hijacked Page (this page has a hijacked page controller)

1. Navigate to /hijacked
2. Enter a name into the top text field and click Current Umbraco Page - The form should submit and retain the model, view data and temp data.
3. Enter a name into the middle text field and click Redirect to Current Page - The form should submit but only the temp data should be retained (as expected after a redirect).
4. Enter a name into the bottom text field and click Redirect to Current URL - The form should submit but only the temp data should be retained (as expected after a redirect).

Scenario 3 - Virtual Page (this is a virtual page controller and a custom route)

1. Navigate to /demo
2. Enter a name into the top text field and click Current Umbraco Page - The form should submit and retain the model, view data and temp data.
3. Enter a name into the middle text field and click Redirect to Current Page - The form should submit but only the temp data should be retained (as expected after a redirect).  Note, this will submit and redirect to the home page as expected (as that is the URL for the home page).
4. Navigate back to /demo.
5. Enter a name into the bottom text field and click Redirect to Current URL - The form should submit but only the temp data should be retained (as expected after a redirect).

Scenario 4 - Virtual Page (this is a custom route finder delegate using a custom route)

1. Navigate to /test
2. Enter a name into the top text field and click Current Umbraco Page - The form should submit and retain the model, view data and temp data.
3. Enter a name into the middle text field and click Redirect to Current Page - The form should submit but only the temp data should be retained (as expected after a redirect).  Note, this will submit and redirect to the home page as expected (as that is the URL for the home page).
4. Navigate back to /test.
5. Enter a name into the bottom text field and click Redirect to Current URL - The form should submit but only the temp data should be retained (as expected after a redirect).

All automated tests have been run and pass.

### CODE REVIEW

**Review by bergmania — APPROVED** [review]
Hi @justin-nevitech ..

Thanks a lot for this detailed PR..

I when through the test scenarios and all seems to work as expected. 

I have fixed the breaking changes in constructors

**Comment by bergmania** [comment]
Cherry picked for `v11/dev` and `v10/dev` 💪

**Comment by jeroenmink2** [comment]
I think this is causing an error when integrating an Umbraco Form in the view that's served by a custom route. After the upgrade we're getting the following excetion after submitting the Umbraco Form:

`System.InvalidOperationException: No service for type '<customControllerName>' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Umbraco.Cms.Web.Common.Routing.UmbracoVirtualPageRoute.SetupVirtualPageRoute(HttpContext httpContext)
   at Umbraco.Cms.Web.Website.Routing.UmbracoRouteValueTransformer.TransformAsync(HttpContext httpContext, RouteValueDictionary values)
   at Microsoft.AspNetCore.Mvc.Routing.DynamicControllerEndpointMatcherPolicy.ApplyAsync(HttpContext httpContext, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matching.DfaMatcher.SelectEndpointWithPoliciesAsync(HttpContext httpContext, IEndpointSelectorPolicy[] policies, CandidateSet candidateSet)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.<Invoke>g__AwaitMatch|8_1(EndpointRoutingMiddleware middleware, HttpContext httpContext, Task matchTask)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 121
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Forms.Web.HttpModules.ProtectFormUploadRequestsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Vendr.Umbraco.Web.Mvc.VendrRequestBufferingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at UmbracoVO.Startup.<>c__DisplayClass6_0.<<AddHttpHeaders>b__0>d.MoveNext() in C:\agent\_work\17\s\UmbracoVO\Startup.cs:line 127
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)`


Is it possible to support this scenario?

**Comment by bergmania** [comment]
Hi @jeroenmink2 
Im pretty sure this is fixed in 11.3 and 10.5 by this PR https://github.com/umbraco/Umbraco-CMS/pull/13910

**Pull request merged**
