### PR TITLE
U4-8522 cmsPropertyData needs unique constraint indexes and index refactoring

### PR DESCRIPTION
**Pull request by Shazwazza**

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
If you get a chance to look at this today, the same issue was found in Courier and was fixed like so:

https://our.umbraco.org/Documentation/Add-ons/UmbracoCourier/DataIntegrity

Stephane found a way to execute queries in migrations first so that you can then safely apply the constraint: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Persistence/Migrations/Upgrades/TargetVersionSevenFiveZero/AddRedirectUrlTable4.cs

So I think this could easily be rewritten to do 
`DELETE FROM cmsPropertyData WHERE id NOT IN (SELECT MIN(id) FROM cmsPropertyData GROUP BY contentNodeId, versionId, propertytypeid HAVING MIN(id) IS NOT NULL)` first and then Delete and Create the `IX_cmsPropertyData_1`.

**Comment by nul800sebastiaan** [comment]
Well.. my proposed code was going to be the update below, but both your code and this code fails with an error:

```
 2016-07-14 14:48:14,441 [P12004/D3/T156] ERROR Umbraco.Web.Install.Controllers.InstallApiController - Installation step DatabaseUpgrade failed.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Umbraco.Web.Install.InstallException: The database failed to upgrade. ERROR: The database configuration failed with the following message: There is already an open DataReader associated with this Command which must be closed first.
 Please check log file for additional information (can be found in '/App_Data/Logs/UmbracoTraceLog.txt')
   at Umbraco.Web.Install.InstallSteps.DatabaseUpgradeStep.Execute(Object model)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Umbraco.Web.Install.Controllers.InstallApiController.ExecuteStep(InstallSetupStep step, JToken instruction)
 2016-07-14 14:48:14,441 [P12004/D3/T156] INFO  Umbraco.Web.Install.Controllers.InstallApiController - Step completed (took 14154ms)
 2016-07-14 14:48:14,441 [P12004/D3/T156] ERROR Umbraco.Web.Install.Controllers.InstallApiController - An error occurred during installation step DatabaseUpgrade
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Umbraco.Web.Install.InstallException: The database failed to upgrade. ERROR: The database configuration failed with the following message: There is already an open DataReader associated with this Command which must be closed first.
 Please check log file for additional information (can be found in '/App_Data/Logs/UmbracoTraceLog.txt')
   at Umbraco.Web.Install.InstallSteps.DatabaseUpgradeStep.Execute(Object model)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Umbraco.Web.Install.Controllers.InstallApiController.ExecuteStep(InstallSetupStep step, JToken instruction)
   at Umbraco.Web.Install.Controllers.InstallApiController.PostPerformInstall(InstallInstructions installModel)
```

```
using System.Linq;
using Umbraco.Core.Configuration;
using Umbraco.Core.Logging;
using Umbraco.Core.Persistence.SqlSyntax;

namespace Umbraco.Core.Persistence.Migrations.Upgrades.TargetVersionSevenFiveZero
{
    /// <summary>
    /// See: http://issues.umbraco.org/issue/U4-8522
    /// </summary>
    [Migration("7.5.0", 2, GlobalSettings.UmbracoMigrationName)]
    public class UpdateUniqueIndexOnCmsPropertyData : MigrationBase
    {
        public UpdateUniqueIndexOnCmsPropertyData(ISqlSyntaxProvider sqlSyntax, ILogger logger)
            : base(sqlSyntax, logger)
        {
        }

        public override void Up()
        {
            Execute.Code(MigrationCode);
        }

        private string MigrationCode(Database database)
        {
            //Clear all stylesheet data if the tables exist
            //tuple = tablename, indexname, columnname, unique
            var indexes = SqlSyntax.GetDefinedIndexes(Context.Database).ToArray();
            var found = indexes.FirstOrDefault(
                x => x.Item1.InvariantEquals("cmsPropertyData")
                     && x.Item2.InvariantEquals("IX_cmsPropertyData_1")
                     //we're searching for the old index which is not unique
                     && x.Item4 == false);

            var localContext = new LocalMigrationContext(Context.CurrentDatabaseProvider, database, SqlSyntax, Logger);

            if (found != null)
            {
                //In order to apply this unique index, we must ensure that there is no duplicate data.
                // so we need to query for this
                localContext.Execute.Sql("DELETE FROM cmsPropertyData WHERE id NOT IN (SELECT MIN(id) FROM cmsPropertyData GROUP BY contentNodeId, versionId, propertytypeid HAVING MIN(id) IS NOT NULL)");

                //we need to re create this index
                localContext.Delete.Index("IX_cmsPropertyData_1").OnTable("cmsPropertyData");
                localContext.Create.Index("IX_cmsPropertyData_1").OnTable("cmsPropertyData")
                    .OnColumn("contentNodeId").Ascending()
                    .OnColumn("versionId").Ascending()
                    .OnColumn("propertytypeid").Ascending()
                    .WithOptions().NonClustered()
                    .WithOptions().Unique();
            }

            return localContext.GetSql();
        }

        public override void Down()
        {
        }
    }
}
```

**Comment by nul800sebastiaan** [comment]
And when I comment out this migration, the upgrade works..

**Comment by Shazwazza** [comment]
That delete query will not work with my sql, i tested my migration and it seemed to run just fine. Are you sure you get the error when just using my original pr? 

I can update stephanes query to work with my sql but it won't work just like that.

**Comment by nul800sebastiaan** [comment]
Fair enough. 
Yeah, I was about to accept this PR, but the Our upgrade hung on this error.. :/

**Comment by nul800sebastiaan** [comment]
It has 118723 results for the `const string sql = @"SELECT mt.id,..etc` query. That might've helped kill it.. :wink:

**Comment by Shazwazza** [comment]
Wha?! Ok, let me try to update the delete query to work with my sql and see if that will work

**Comment by nul800sebastiaan** [comment]
I got the same error with that query, so it's probably one of the other queries in this migration that's failing!

**Comment by Shazwazza** [comment]
I'll update some code - for some reason i didn't recommit another change i made, one sec, will update and test/push

**Comment by Shazwazza** [comment]
Part of the problem is you moved things into a queued Execute.Code block and then inside of that you are queuing up even more stuff - which will actually not get queued. You cannot queue things up inside of a queue, the Execute.Code block is a special case. Hang on and I'll make a commit

**Comment by nul800sebastiaan** [comment]
Yes, I was a bit hasty yesterday. :-) Sleeping on it was good. Your changes work now with a database with LOADS of duplicate property data, so all good, thanks!

**Pull request merged**
