### PR TITLE
V8: Add "Move" option for deleted items in the content tree

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/3919

### Description

This PR adds move capability inline in the restore dialog if an item in the content tree can't be restored automatically to its original location.

It looks like this:

restore-content-with-move

🎄 24/24 🎄 

🎅 **Merry Christmas, Umbraco!!** 🎅

### CODE REVIEW

**Comment by emmaburstow** [comment]
Heeeey @kjac 

All done!!! Congratualtions! We'll get around to looking soon and let you know if we need anything.

Em

**Comment by kjac** [comment]
Thank you! 😁

**Comment by nul800sebastiaan** [comment]
Sweet, all good! 👍

**Comment by nul800sebastiaan** [comment]
Oh! I just realized the media part of this PR is also missing in V8, could I ask you do that one as well @kjac ? 😁

**Comment by kjac** [comment]
But of course, I did promise after all 😀

**Comment by nul800sebastiaan** [comment]
🙏 THANKS!

**Comment by kjac** [comment]
PR in #4056

**Pull request merged**
