### PR TITLE
Added a condition to check last write time of files and to always copy over if nuget source is newer

### PR DESCRIPTION
**Pull request by tompipe**
The previous msbuild condition prevents newer umbraco/umbraco_client folders from being copied over in certain situations.

Check last write time of both files and copy over if nuget source is newer.

http://issues.umbraco.org/issue/U4-6372

### CODE REVIEW

**Comment by zpqrtbnk** [comment]
Hey @tompipe this refer to an old issue that has been closed now - is this still relevant?

Also I notice that the original condition was

    !Exists('%(RecursiveDir)%(Filename)%(Extension)')

and that you add

    AND $([System.DateTime]::Parse('%(ModifiedTime)').Ticks) &gt; $([System.IO.File]::GetLastWriteTime('%(RecursiveDir)%(Filename)%(Extension)').Ticks)

which would be wrong I think, as it could copy if the file does not already exist, AND if the file to copy is more recent than the existing file - where I think you'd want to do an OR ie copy ALSO if it exists but is older?

Anyways... that's an old PR... let me know what I should do with it ;-)

**Comment by tompipe** [comment]
Oh wow - this is an old one!

Erm, from what I remember - it was an issue with nuget packages - either upgrading or adding nuget into an existing project.

I think the previous condition would only copy files if they didn't exist. But if you are upgrading or reinstalling, then you would want the 'older files' to be upgraded/reinstalled, so I added a check to look at the modified time to ensure the newer file is always copied?

I think?! :)

**Comment by nul800sebastiaan** [comment]
As far as I know this targets file only kicks in when using certain configurations using WebDeploy to deply Umbraco sites. It will be difficult to test without a proper way to reproduce the original problem (which is probably why this PR has been dorment for so long).

But yes, the `AND` comparison should definitely be an `OR` in this case.

**Comment by tompipe** [comment]
Yes - we definitely would have been using webdeploy back then!

**Comment by zpqrtbnk** [comment]
Right, closing the PR then. Thanks!

**Pull request closed without merging**
