### PR TITLE
Link to template from "document types" or "content" screen

### PR DESCRIPTION
**Pull request by ssougnez**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description

Added the possibility to open the template(s) associated to a document type from the "document type" screen: 

untitled2

And the "content" screen.

untitled

The link of the "content" screen disappears if no template has been selected.
For the ID of the template to be available on the "content" screen, I added a "templateId" field in the "ContentItemDisplay" class.

Note that I made way less changes that the ones displayed. All of these modifications are the result of "Visual Studio" auto formatting the file.

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @ssougnez ,

Many thanks for the PR. Is there a related issue for this?

Poornima

**Comment by ssougnez** [comment]
Hi,

yep, this one: http://issues.umbraco.org/issue/U4-11521

**Comment by nul800sebastiaan** [comment]
@poornimanayar - Make sure to check the branch name, it's usually named after an issue number, in this case: 

image

**Comment by poornimanayar** [comment]
Silly me!

**Comment by ssougnez** [comment]
Okay, will do in the upcoming days. It will give you some time to think about how to improve the "Open" link on the template selector ;-)

**Comment by ssougnez** [comment]
Sebastiaan,

I just checked what you told me and there is indeed a property "allowOpen" to the directive "umb-node-preview" that defines whether the "Open" link is visible or not but the strange thing is that this property is bound to a variable that is always true.

Indeed, if you have a look at line 183 of "umb-content-node-info.html", you'll see that the property "allowOpen" is bound to the scope property "allowOpen" declared at line 16 in "umbcontentnodeinfo.directive.js". However, I did a search for "allowOpen" (and even "allow") and it turns out that I didn't find anything else than the declaration of the variable. I also checked at the code of "umbnodepreview.directive.js" to see if this directive didn't update this variable but it does not. 

So, I'm probably wrong but it looks like even though there is a possibility to display/hide the "Open" link based on a condition, this one is not used. Therefore, I cannot really use the same behavior for the "Open" link for the template.

What I suggest is to accept this merge request (depending on your opinion about the "Open" link on the template selector component), then create another issue for the permission of this "Open" link (if it makes sense... Indeed, I didn't check but maybe the whole tab is not displayed for people not able to see the settings section).

**Comment by nul800sebastiaan** [comment]
Haha! You are absolutely right.. 👍 

Alright then let's take it one step at a time and add this link now and fix when it should show up later! 

I've tested your changes and they're absolutely fine, great job!

**Comment by ssougnez** [comment]
Awesome! Thanks :-)

**Pull request merged**
