### PR TITLE
Removes the left-offset on the notifications wrapper, to instead use left:0

### PR DESCRIPTION
**Pull request by nathanwoulfe**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: #4548 

### Description
Removes the left-offset on the notifications wrapper, to instead use left:0 (which already existed in umb-notifications.less but was overridden in grid.less). Removed a bit of unnecessary CSS too, just to be tidy.

Now means notifications will run full-width when no left pane is displayed, rather than having an 80px gap. Can be verified by saving something (content, content type etc).

Also fixed an overflow issue in the editor sub-nav, where the nested <a> elements had height set to 70px, which was the same as their container, but the container had 1px border bottom so only 69px of available space. This does shift the active item marker slightly - seems like a sub-pixel-rendering thing though since offsetting it 1px in the opposite direction (ie bottom:-1px) was too much. 

Before:

nav overflow

After: 

nav no overflow

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @nathanwoulfe!

Nice to hear from you. Thanks for this PR. We'll let you know if we need anything and will be in touch soon,

Em

**Comment by nathanwoulfe** [comment]
Hey @emmaburstow I've been a bit of a ghost in these parts recently... It's not the most exciting PR, but UI polish is a good thing.

**Comment by clausjensen** [comment]
Thanks for the PR @nathanwoulfe ! 😃

**Comment by nathanwoulfe** [comment]
No worries at all!

**Pull request merged**
