### PR TITLE
Disable clicking on disabled checkboxes/radios

### PR DESCRIPTION
**Pull request by nathanwoulfe**
Adding pointer-events:none so that the disabled checkbox/radio is not clickable. Without this rule, the disabled item is opaque but still clickable, so not really disabled.

### CODE REVIEW

**Comment by emmaburstow** [comment]
ooh good spot. Thanks for this Nathan! 

Em

**Comment by nathanwoulfe** [comment]
👍👍

**Comment by emmaburstow** [comment]
heyyyy 

I wanted to merge this but we have a problem. 

image

Thoughts?

Emma

**Comment by nathanwoulfe** [comment]
Ah yes. I might have killed my fork. Don't ask, it was not a good day. 

It's a one-liner, I'll redo.

**Comment by nathanwoulfe** [comment]
https://github.com/umbraco/Umbraco-CMS/pull/7689

**Pull request closed without merging**
