### PR TITLE
Allow SVG's to be uploaded as image types [U4-6008]

### PR DESCRIPTION
**Pull request by JJCLane**
Catches exceptions caused by System.Drawing.Image trying to read the SVG file stream and set's it's height and width to 0. Could potentially try and read the XML to get width and height?

### CODE REVIEW

**Comment by Decad** [comment]
Can this be merged? We are running into this issue when using SVG's.

**Comment by zpqrtbnk** [comment]
Hey!
Sorry for reviewing this soooo late.
When I just drop an SVG file in the media section, it is uploaded as a File (not an Image) so does not really have a height/width, however it shows and is recognized as an image. If I upload it into an Image media, it works but (depending on SVGs) some of them are displayed with a 0x0 size.
That I can fix.
So... I *think* we've waited for too long and this PR is not relevant.
Sorry about it.

**Comment by Nicholas-Westby** [comment]
@zpqrtbnk I think you misunderstood the issue, and **I'd like to request you open this PR again and review it again**. Here's why.

By default, Umbraco is not configured to recognize SVG files as images. You must configure it in umbracoSettings.config, like this:

`<imageFileTypes>jpeg,jpg,gif,bmp,png,tiff,tif,svg</imageFileTypes>`

That has a few benefits, including the fact that the media item will be created with a media type of "Image" (which has other benefits, such as being able to pick it with a media picker that has been configured to only allow images to be picked).

However, even in Umbraco 7.10.4 (latest at the time of this writing), you get an exception when you configure Umbraco this way and upload an SVG image.

This is what this PR is supposed to fix. It's still relevant. Here's a Twitter thread of some troubles I experienced with this yesterday: https://twitter.com/MrMarsRed/status/989625965029482496

**Comment by zpqrtbnk** [comment]
Get it. Should be possible to upload SVG as image, but then, should not crash. Reopening.

**Comment by JJCLane** [comment]
@zpqrtbnk There's still this one http://issues.umbraco.org/issue/U4-6008, or should a new one be created?

**Comment by zpqrtbnk** [comment]
Nope that's perfect thanks!

**Comment by JimBobSquarePants** [comment]
This method could do with some love. 
If you want to parse file sizes, introduce specific per filetype parses to do so. Choosing the correct file type should be based on the file headers. Anything else is both slow and potentially dangerous.

e.g 

``` c#

public interface IImageInfo {
    string Name {get;}
    int width {get;}
    int height {get;}
    IEnumerable<string> MimeTypes { get; }
    IEnumerable<string> FileExtensions { get; }
}

public interface IImageDetector {
    int HeaderSize { get; }
    IImageInfo GetInfo(ReadOnlySpan<byte> header)
}
```

Called by something like

``` c#
int maxHeaderSize = this.ImageDetectors.Max(x => x.HeaderSize)
long startPosition = stream.Position;
stream.Read(buffer, 0, maxHeaderSize);
stream.Position = startPosition;
IImageInfo info = this.ImageDetectors.Select(x => x.GetInfo(buffer.Span)).LastOrDefault(x => x != null)
```

**Comment by Nicholas-Westby** [comment]
@JimBobSquarePants Are you referring to the original code, or the code introduced by this PR?

If you're referring to the original code, perhaps that would be best addressed with a separate issue/PR, so as to now slow down any progress that might be made on this (now, two year old) PR?

**Comment by JimBobSquarePants** [comment]
@Nicholas-Westby Yes and No... 

The PR is a bit of a hack relying on exception handling and if so should be committed with a stark warning. If everyone's happy to have unmanaged code attempting to parse any old file format then merge it.

**Comment by Nicholas-Westby** [comment]
Doesn't seem any worse than what's already there.

**Comment by JimBobSquarePants** [comment]
Indeed, but do we want to further compound a problem as a solution?

**Comment by Nicholas-Westby** [comment]
I don't think it really does exacerbate the problem. It just adds a fix for another problem (which is a very real one impacting people, including one of my coworkers yesterday) while not addressing the issues you've brought up.

This code just happens to live in the same spot as some code you've identified issues with, as far as I can tell.

**Comment by JimBobSquarePants** [comment]
Code for the future not now. You can either. 

1. Add a further bad hack to already bad code.
2. Fix the problem properly. 

I know which one I would choose. This is duct tape around a leaky pipe.

**Comment by Nicholas-Westby** [comment]
To be clear, this is not my PR, but I would like to see this fixed, and I have no strong preference for how it gets fixed so long as it does.

Perfect is the enemy of good. As the saying goes, make it work, then make it work right, then make it fast. You would of course be able to create your own PR to do the latter two.

I'd prefer duct tape around a leaky pipe to a leaky pipe with no duct tape.

**Comment by Nicholas-Westby** [comment]
@JJCLane It looks like there are now some merge conflicts. Would you mind merging the latest dev-v7 branch into your feature branch to ensure this PR can be included sooner? Maybe do a rebase so the history is cleaner.

**Comment by Nicholas-Westby** [comment]
At least some of the code has moved here: https://github.com/umbraco/Umbraco-CMS/blob/7ee510ed386495120666a78c61497f58ff05de8f/src/Umbraco.Web/Strategies/DataTypes/LegacyUploadFieldWorkaround.cs#L99

**Comment by JJCLane** [comment]
@Nicholas-Westby I can certainly do that, but as @JimBobSquarePants said this definitely isn't the most elegant solution. At the time I just got something working and hoped it could spark something for them to get it fixed finally.

**Comment by Nicholas-Westby** [comment]
@zpqrtbnk What's your opinion on this? How do we get this PR or another PR integrated so that this issue can finally be fixed? I just had another coworker run into this again today. Happens all the time.

I would rather you reject this PR now so that we can get a PR that satisfies whatever standard is necessary than to leave this open forever in an ambiguous state.

**Comment by Nicholas-Westby** [comment]
BTW, I migrated the issue to the new issue tracker: https://github.com/umbraco/Umbraco-CMS/issues/2909

**Comment by nul800sebastiaan** [comment]
Hello everyone! First off, apologies for the delay in re-evaluating this PR! I could have sworn I had replied to this with the problems found in the first round of re-testing but I guess I never posted it. 🤦‍♂️

I've re-reviewed this now and while this fixes the one specific problem there's multiple other problems:

- An upload field on a document type (for content, not media) can be aliased `umbracoFile`, which then generates thumbnails, which fails as well, there should be a try-catch there too
- An image cropper field with alias `umbracoFile` has the same problem as above
- It seems like anywhere `Image.FromStream` is used this will turn into a problem for SVG files, so all places in the code where we use this would need to be fixed with a try-catch block
- After actually trying this out, most things seem to work, except for number 2 above, the image cropper - it sometimes accepts the file and shows the cropper, sometimes it just keeps showing the upload field. I guess that the swallowed error in the catch could provide more info, not sure (this is also the problem with swallowing exceptions of course)

Even if all these problems are also fixed, I doubt the usefulness of even allowing svg uploads as images at the moment since they just look like blank images. For example, here I've uploaded 5 different svg files:

image
 
Opening an svg file in the media section will give you an image cropper, as far as I know it's not actually possible to crop an svg file, and again, the preview is blank:

image

Of course the same problems occur with media pickers: 

image

I'll close this PR for now since it's so old and I would encourage a new PR for #2909 to address the problems found. 👍

**Comment by Nicholas-Westby** [comment]
Hi @nul800sebastiaan,

Thanks for reviewing again. The fact that you can't see those SVG's may be a result of the particular SVG's you were uploading. I can see them just fine in the media picker and on a property in the content section once picked.

Though, I too am unable to see them in the media section when I'm using image cropper, at least for the main image; I can still see the SVG image in each of the crops for the image cropper.

This is Umbraco 7.10.4 though; maybe the version of Umbraco you are testing with positions images differently (e.g., SVG images that don't have an embedded width/height may display with zero width/height in some browsers unless the CSS sets the dimensions).

**Comment by nul800sebastiaan** [comment]
Yeah, I figured out that because I was try/catching all these height/width detections, I returned height & width 0 for them. Could default to 500x500 or something.

**Pull request closed without merging**
