### PR TITLE
Configurable internal search

### PR DESCRIPTION
**Pull request by ismailmayat**
The internal backoffice search for content and media only searches on id and nodeName.  This pull request updates the umbracoSettings.config and adds new section where users can add field aliases for content and media. The internal search for content and media will also now take into consideration any fields set in the umbracoSettings.config and used in the internal search.

http://issues.umbraco.org/issue/U4-10416

### CODE REVIEW

**Comment by warrenbuckley** [comment]
Hi @ismailmayat 
Thanks for the PR, can you add an issue on the issue tracker please for this thanks.

**Comment by marcemarc** [comment]
@ismailmayat @warrenbuckley Would this PR resolve this issue? (or could we add it for members search tooo)  http://issues.umbraco.org/issue/U4-8417

**Comment by ismailmayat** [comment]
@marcemarc just seen this, I knew someone would ask about the members grr. So I originally did it for content as we had a requirement for a project we are supporting, then I saw someone on forums going on about searching images with alt text.  Really should have added member one as well but in theory same principle just add the field in config and update code in search.

**Comment by nul800sebastiaan** [comment]
Hey there @ismailmayat !

I'm writing today after announcing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Comment by marcemarc** [comment]
@nul800sebastiaan @ismailmayat The introduction of ISeachableTree enables developers to customise the backoffice search - so before the PR is ported to V8 - do we still need this in V8?

**Comment by Shazwazza** [comment]
Nothing needed for v8 or v7. All ISearchableTree's are replaceable in both v7 and v8. In v8, Examine's APIs are properly abstracted so it is possible to replace Examine's provider with a custom one (i.e. Azure search) and then you don't have to change any ISearchableTree's for media/content/members since they are based on Examine. I am aware I haven't written documentation on this ;) Also, yes i have a prototype of an Azure Search examine provider, and I have not tried an Elastic Search one but that would be possible.

**Comment by marcemarc** [comment]
@Shazwazza cool, yes I have ISearchableTree + Azure search working on a site and it's super cool, have seen it in the Examine repo too

**Pull request closed without merging**
