### PR TITLE
Change to "MoveToRecycleBinDo" function of the MediaService and IMediaService

### PR DESCRIPTION
**Pull request by bharanijayasuri**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, this fixes: https://github.com/umbraco/Umbraco-CMS/issues/3387
- [x] I have added steps to test this contribution in the description below

### Description

- Made a small change to "MoveToRecycleBinDo" function of the MediaService.cs file to get the notifications working in the backoffice for event cancellations.

- Minor changes to  IMediaService.cs, MediaService.cs (Added a new function MoveOp to return an Attempt), media.resources.js (Added code to handle cancellation/error messages) and MediaController.cs (Made a minor change to call the new function)

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @bharanijayasuri 

Congrats on your first PR to the repo! One of us will take a look over the work and will be in touch should we need anything from you.

Emma, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-pr-team/)

**Comment by bharanijayasuri** [comment]
@nul800sebastiaan Thanks for the feedback Sebastiaan. I will get on with the requested modifications ASAP and give you guys a shout.

**Comment by Shazwazza** [comment]
It should just be called "Move". All method implementations of IMediaServiceOperations should be explicitly implemented which means it won't conflict with the original Move method ... just like how the others are implemented.

We don't need to keep any commented out code so that can be removed. Lastly should the error message be localized? I think there's already a localization header for Error.

**Comment by nul800sebastiaan** [comment]
@Shazwazza Can't call it `Move` though, it conflicts with the original `Move` method? Unless the signature is changed but that would be changing the signature just so we don't have to make a breaking change. Ideas..?

**Comment by bharanijayasuri** [comment]
I have renamed the new "MoveOp" to new "Move" in IMediaServiceOperations. But if I made the "Move" function in IMediaService obsolete, that would mean we would have to use the "WithResult" extension to access the new "Move" function that returns a status. Would this be alright? 

I am yet to commit the code though. I thought I would clarify before I went ahead and committed the changes. 

@Shazwazza By Localization, should I add an entry for the error message in the lang files and user TextService Localize function to fetch and display the message. Apologies if this is trivial, but I am relatively new to the scene and still digging to try and understand the source.

Thanks in advance.

**Comment by Shazwazza** [comment]
2 interfaces can have the same name, it depends on how they are implemented. As I said, this is exactly the way that the entire `IMediaServiceOperations` is implemented (explicitly). You'll see that `IMediaServiceOperations` contains `MoveToRecycleBin` just as `IMediaService` does, same goes for all of the other methods on `IMediaServiceOperations`

**Comment by Shazwazza** [comment]
I don't think we need to obsolete the original Move, we didn't obsolete the other methods that `IMediaServiceOperations` shadows. I think they can be used for different purposes, so I'd leave it as-is. In v8, these are all merged together and there isn't a `IMediaServiceOperations`

for localization, yup just add a key/value to the en_us.xml file where it makes sense and use the ILocalizedTextService to do the localization, there's lots of examples in the core for that, i think it's exposed on Services.TextService.

**Comment by bharanijayasuri** [comment]
I have now made the suggested changes and committed the code back to the repository. 

Renamed MoveOp back to Move.
Localized the error message.

**Comment by nul800sebastiaan** [comment]
Thanks very much @bharanijayasuri ! 

I added a few more corrections: https://github.com/umbraco/Umbraco-CMS/pull/3453/commits/1974485fad6c933cc26913cda513b3cae974f530 

Other than that everything seems to work and is backwards compatible, great job on your first PR for Umbraco CMS! 👍 🏅 

If you have a profile on Our Umbraco could you send a link here? I'd love to give you the contributor badge.

Thanks again!

**Comment by nul800sebastiaan** [comment]
Hi there @bharanijayasuri,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing :pray:

If you haven't heard already we have had a record breaking amount of PR's in both the CMS and the Documentation repository. You can read all about the numbers in the [Umbraco Hacktoberfest Aftermath blog post](https://umbraco.com/blog/the-2018-hacktoberfest-aftermath/).

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://goo.gl/forms/smjQwEMDM5cUnz6x1) :point_left: Please follow this link to fill out and submit the form, **before November 21st 2018**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before December, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
