### PR TITLE
v8: Fix SVG image preview

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5857

### Description
This PR fixes some issues, where SVG files no longer was showing previews in media section on the page for the individual files and in media picker preview. I noticed the entities no longer returns meta data extension as previous. I guess it is because the entities have been refactored and e.g. it only set an additional property for `MediaPath` here. https://github.com/umbraco/Umbraco-CMS/blob/580ba79619cee347512131eff28e53d96af4958b/src/Umbraco.Web/Models/Mapping/EntityMapDefinition.cs#L52
Besides this meta data it also has `ContentTypeAlias` and `IsContainer` properties. Maybe media items should also have an `Extension` property and an `Size` property (umbracoBytes)? The `umbracoBytes` might require some additional lookup, but the extension can be determined from the media path.

This can however be determined from the media path as here:
https://github.com/umbraco/Umbraco-CMS/blob/ade9bb73246caf25a7073f2b9e5262641a201863/src/Umbraco.Web.UI.Client/src/common/services/mediahelper.service.js#L378-L387
https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web.UI.Client/src/common/directives/components/umbmediagrid.directive.js#L166

If there is no file path I think this function should return `null` instead of `false`.
https://github.com/umbraco/Umbraco-CMS/blob/ade9bb73246caf25a7073f2b9e5262641a201863/src/Umbraco.Web.UI.Client/src/common/services/mediahelper.service.js#L381

image

### CODE REVIEW

**Comment by bjarnef** [comment]
An example of the SVG icon shown in both media picker, listview grid in media section and at the fileupload.



Maybe we should consider to add a component, e.g. `umb-file-icon` or similar with can be re-used the show the file icon and specify the extension and maybe a size as well.
For example `<umb-file-icon extension="txt" size="s" />`.

At the moment the file in both media picker and the icon at the fileupload has the following structure:

```
<div class="umb-icon-holder">
       <span class="file-icon">
              <i class="icon {{media.icon}}"></i>
                  <span>.{{media.extension}}</span>
              </span>
       <small>{{media.name}}</small>
</div>
```

Only in media grid layout the markup is a bit different, but it would be great if we just could re-use this component and adjust the styling from a component less file.

**Comment by bjarnef** [comment]
@nul800sebastiaan it would be great if we could have these svg previews working again :)

**Comment by nul800sebastiaan** [comment]
Thank you kindly good sir and apologies for the delay! 🙈

**Comment by bjarnef** [comment]
Yeay! 😁 I wonder if it would make sense to create an `umb-file-icon` directive/component to wrap this markup, which can be re-used?

**Pull request merged**
