### PR TITLE
Adding the Ability to toggle show password at the back office login

### PR DESCRIPTION
**Pull request by IbrahimMNada**
### Description

I have added a configurable way of adding a show password functionalityx
with a configuration that gives a ability to to turn it off from app settings , it goes like the following :

image

image

and it mix well with the other configurations like remember me /forget password

image

Please Merge it ASAP , if you have any comments I will fix them super fast

### CODE REVIEW

**Comment by georgebid** [comment]
Hey @IbrahimMNada, thank a lot for your PR! Someone on the core collaborators team will review this soon 😄 As this will be a new feature I will check with HQ to see if this is something they'd want to add to the solution. I'll be in touch soon!

**Comment by IbrahimMNada** [comment]
Hello any update on this ? 

a Client wants me to revert to Umbraco 13 because of it  x_x 
help

**Comment by georgebid** [comment]
This discussion has been created here: https://github.com/umbraco/Umbraco-CMS/discussions/17117 

It would be great if you could include your thoughts and reasonings for this PR here, and hopefully we can get this resolved for you 😄

**Comment by nielslyngsoe** [comment]
Hi @IbrahimMNada 

 We do have a password input component in the UI Library, that serve this feature. Do you think that could be used?
 
 https://uui.umbraco.com/?path=/docs/uui-input-password--docs

**Pull request closed without merging**
