### PR TITLE
Fix linkpicker overlay issues

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/3068

### Description

This PR fixes the four issues outlined in #3068. If you want me to split the PR up in four separate PR's I'd be happy to do that. I just figured it made sense to fix all of them in one PR, as they all revolve around the same lines of code.

An easy way to test this is to:

1. Unzip this plugin under App_Plugins: [TestPlugin.zip](https://github.com/umbraco/Umbraco-CMS/files/2597030/TestPlugin.zip)
2. Add the following to `Dashboard.config` above `<section alias="StartupDashboardSection">`:
```xml
  <section alias="TestPlugin">
    <areas>
      <area>content</area>
    </areas>
    <tab caption="Test Plugin">
      <control>
        /App_Plugins/TestPlugin/testplugin.html
      </control>
    </tab>
  </section>
```

Here are some gifs that show the various fixes in action.

#### Don't show an error when opening the linkpicker overlay with a media item selected

link-picker-overlay-after-1

#### Keep the selected content node highlighted for all subsequent displays of the linkpicker overlay

link-picker-overlay-after-2

#### Remove the content node highlight when selecting a media item

link-picker-overlay-after-3

#### Make sure the initial model is not updated before the dialog is submitted

link-picker-overlay-after-4

### CODE REVIEW

**Comment by emmaburstow** [comment]
This too!

Em

**Comment by poornimanayar** [comment]
Hi @kjac ,

First of all thanks for the super gifs and such good explanation of the issues and the resolutions. Secondly, thanks for the test plugin :) I have tested all the conditions as mentioned here and it all works as advertised. As for the number of PRs I am not sure whether it should be 4 different ones or not but I can see the logic behind doing all of them in a single PR. 👍 

Poornima

**Comment by abjerner** [comment]
@kjac the conflict was with my PR - your merge seems to have resolved the conflict the right way 👍 (haven't tested it though)

3kgasaxxx3wy

**Comment by kjac** [comment]
Thanks @abjerner. 

I just found out I had the whole thing set up for testing already so... I can confirm it still works 😁

**Comment by nul800sebastiaan** [comment]
It's very wonderful, much better, thanks again!!

**Pull request merged**
