### PR TITLE
Fix: Package view - Layout not showing correctly in respect to screen size #12576

### PR DESCRIPTION
**Pull request by Migaroez**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

**Linked Issue**: #12576 

### Description
Reproduction steps are in the issue

**Before** (from the issue)
image

**After**
image

### CODE REVIEW

**Comment by nathanwoulfe** [comment]
Cheers @Migaroez, this is much better 👍

**Review by mikecp — APPROVED** [review]
Thanks for the fix @Migaroez , looking better like this indeed! 👍
Cheers!

**Comment by mikecp** [comment]
Woops! Looks like @nathanwoulfe and myself were checking  this in parallel 😅

**Comment by mikecp** [comment]
@nathanwoulfe you commented first so I'll let you finalize the merge 😉

**Comment by nathanwoulfe** [comment]
No idea why I didn't hit the big green button... Done now 😊

**Pull request merged**
