### PR TITLE
Thread safety in RuntimeState.EnsureApplicationUrl

### PR DESCRIPTION
**Pull request by stevemegson**
`RuntimeState.EnsureApplicationUrl` uses a `HashSet<string>` to store previously-seen URLs, which is not thread-safe. It is possible to corrupt the HashSet in a way that causes calls to `Contains` to enter an infinite loop (I think it creates a loop in a linked list). Since `EnsureApplicationUrl` is called in `BeginRequest`, this breaks everything.

Since there is no `ConcurrentHashSet`, this PR uses a `ConcurrentDictionary<string, byte>`.

### CODE REVIEW

**Comment by Shazwazza** [comment]
We have a `Umbraco.Core.Collections.ConcurrentHashSet` in the core that you can use

**Comment by stevemegson** [comment]
@Shazwazza thanks, I didn't know that was there.

While I'm sure it's unlikely to affect performance in practice here, does `Contains` really need to take a write lock and clone the inner HashSet? Would this not do the job?

```c#
public bool Contains(T item)
{
    try
    {
        _instanceLocker.EnterReadLock();
        return _innerSet.Contains(item);
    }
    finally
    {
        if (_instanceLocker.IsReadLockHeld)
            _instanceLocker.ExitReadLock();
    }
}
```

**Comment by Shazwazza** [comment]
@stevemegson yep i haven't looked at this code for ages and don't fully recall the history there but you are correct, there's certainly no need to clone to get a contains (or a count), feel free to make those updates as part of this pr.

**Comment by Shazwazza** [comment]
Looks good! thanks @stevemegson !

**Pull request merged**
