### PR TITLE
U4-10247 - updated blue doctype icons to be blue instead of green

### PR DESCRIPTION
**Pull request by prjseal**
For too long the icon color which is supposed to be blue is actually green

I've created this issue so I can submit a pull request with the change in it.

Please accept my pull request.

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Hi @prjseal !

I'm not sure what happened here, but it seems like you committed a new file in the build output. I assume you changed the color in the `.less` files somewhere in the `Umbraco.Web.UI.Client` folder? Those are considered the source files and those get built into the minified umbraco.css.

Anyway, the colors in the backoffice have been carefully chosen and we have no plans to update them at the moment, we're happy with the way the colors look!

I do agree, it's not entirely blue, so if you'd like to send a new PR where the dropdown is changed to name the color turquoise that would be cool!

Best, Sebastiaan.

**Comment by nul800sebastiaan** [comment]
Ps. Remember to create an issue at http://issues.umbraco.org and link it to a PR you send. It's important that all changes show up in the release notes, and having an issue in the tracker is the way to make that happen!

**Comment by prjseal** [comment]
Thanks for the tips
I did create an issue, I just don't think I linked it to the PR.
Baby steps for me.

**Comment by prjseal** [comment]
Hi @nul800sebastiaan 
I created a new PR having updated the colour name to Turquoise.
I hope this is ok now. https://github.com/umbraco/Umbraco-CMS/pull/2102

Please let me know if there is anything else you need.

Thanks

Paul

**Pull request closed without merging**
