### PR TITLE
V8: Improve treepicker keyboard navigation for trees with listviews

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

When you navigate the treepicker using the keyboard (tabbing around), you run into all sorts of issues if the tree contains a listview. The default tab focus more often than not moves to the dialog footer in the transition between views:

treepicker-listview-navigation-before

This PR fixes it by:

1. Applying default input focus to the search box within the list views.
2. Restoring input focus to the last focused element in the tree when you close the last listview.

Here's how it works:

treepicker-listview-navigation-after

### CODE REVIEW

**Comment by poornimanayar** [comment]
Thanks @kjac , Speak to you soon my friend!

Poornima

**Comment by poornimanayar** [comment]
Hi @kjac ,

I have been trying to test this locally after I merged in the latest `v8/contrib` and it doesnt seem to be working. Can you please verify?

Poornima

**Comment by kjac** [comment]
Hi @poornimanayar 😄 

I do believe it's working. Although apparently there's a regression issue that makes the "Back" link of the mini list unable to focus with the keyboard. I will dive into that asap, but it's outside the scope of this PR.

Here's how this PR works on my machine after a merge with `v8/contrib`:

mini-list-view-tree-navigation

**Comment by poornimanayar** [comment]
And merged. Thanks again @kjac

**Pull request merged**
