### PR TITLE
V8: If Nested Content has multiple item types, always let the editor choose which to add

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5427

### Description

See #5427 for an issue description.

This PR updates the rules for adding items to Nested Content as follows:

#### If there is only one item type defined

1. The minimum number of items should be automatically created.
2. If the minimum number and the maximum number of items are both 1, NC should enter "single mode".
3. It should not be possible to delete items so less than the minimum number of items remains.

#### If there are multiple item types defined

1. No items should be automatically created (as we don't know what item type to create).
2. It should be possible to delete all items regardless of the minimum number of items (specifically this makes it possible to change item type in the scenario described by #5427).
3. NC should never enter "single" mode (because it makes deleting items impossible).
4. A validation error should show if one attempts to save without having created the minimum number of items.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @kjac 

Thanks for the work, as usual! We'll look over and shout if we need you for a thing.

Em

**Comment by kjac** [comment]
Merge conflicts resolved.

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Pull request merged**
