### PR TITLE
v8: Fix tree not allowed

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/4415

### Description
At the moment when using `filter` and `filterCssClasses` on a file picker (tree picker) and it is not allowed to select folders it set `cursor:not-allowed` but also for all descendants, which might be valid files/nodes to select.

I have also added opacity like here https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/less/listview.less#L161

You can test this when inserting a partial view in a template:

image

Or if this PR https://github.com/umbraco/Umbraco-CMS/pull/4412 has been merged before reviewing this.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi Bjarne,

Thanks for this work. One of us will have a look and let you know if we need anything, as usual.

All the best,

Emma

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef - this has been fixed in core in the mean time already, so I'll close this one! 👍

**Comment by bjarnef** [comment]
@nul800sebastiaan I added a comment here https://github.com/umbraco/Umbraco-CMS/pull/4551#issuecomment-463116852 that I think the "not allowed" should have an opacity as the mini listview has for not allowed nodes.

E.g. in package options view it is not obvious that the editor only is allowed to select `html` or `htm` file. Then only difference here is at the moment the cursor style, when hover the tree nodes.
image

**Comment by nielslyngsoe** [comment]
@nul800sebastiaan I agree with @bjarnef, can we get the correction that bjarne have for this?

**Comment by nul800sebastiaan** [comment]
Yep, if @bjarnef or you want to create a PR for that then that would be good.

**Pull request closed without merging**
