### PR TITLE
Fix for fallback file upload

### PR DESCRIPTION
**Pull request by Ambertvu**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

Existing issue: https://github.com/umbraco/Umbraco-CMS/issues/14752

### Description
It's basically already described in the issue. I've added the checks around line #833
Did ALOT of cleanup on the code itself, I also saw a IRelationService relationService that wasn't used in the file, but perhaps it is still there for a reason?

### CODE REVIEW

**Comment by busrasengul** [comment]
Thank you @Ambertvu Someone from the core team will look into this soon :)

**Comment by mikecp** [comment]
HI @Ambertvu 
It seems that your PR has now some breaking changes due to some merges we've done recently 😬
It would be great if you could have a look and see if you can sort them out, in order for us to check your PR further 👍

Thanks!

**Comment by Ambertvu** [comment]
@mikecp Merged it 👍 

Already have any comments about the removed (unused) relationship service? Should that remain?

**Comment by mikecp** [comment]
It seems my teammate @lauraneto is taking car of it ;-)

**Comment by lauraneto** [comment]
Hi @Ambertvu ,

I'm still reviewing the pull request, but regarding the `IRelationService` removal question, removing it from a public constructor would be a breaking change indeed (not sure why the build didn't fail, as it is supposed to check for those 😅).
There are ways to make it non breaking, but not sure if it would be worth the effort? So reverting that part would also be ok!

**Comment by Ambertvu** [comment]
Hi @lauraneto,

Reverted it 👍 , I like cleaning up though, haha.

**Comment by lauraneto** [comment]
Hi @Ambertvu ,

As an update, I tested your fix and it worked great! 🙌

But regarding the cleaning 🧹, I had to revert the removal of `null` checks...
On one side, for endpoint parameters that was not correct... Even though it's not set as nullable, it does accept `null`. 🤷‍♀️

image

On another side, while some things are not marked as nullable in the code base, they can still be `null` and were simply never updated due to being "old".

Seeing things like this does not make me confident about these changes 😅
```
IContent IContentSave<IContent>.PersistedContent { get; set; } = null!;
```
Having said that, I wouldn't be comfortable removing the null checks knowing that the code base is not following that at 100%, and it would be really hard to actually follow all the trails and test everything.
I hope you understand!

Other than that, just waiting for the build to finish! 🙌

**Comment by Ambertvu** [comment]
Haha, yea all good!
I wasn't 100% sure about them myself but forgot to mention it, its always risky when you have a lot of 'old' code laying around..

Have a great day!

**Comment by lauraneto** [comment]
@Ambertvu 

Thank you again for the pull request!
This has now been merged! 🙌

**Pull request merged**
