### PR TITLE
v8: Fix created packages delete

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/4162

### Description
This PR adjust the delete package confirm modal a bit and remove the legacy delete dialog, which was used on tree node delete action.

**Before**
chrome_2019-01-20_21-42-56

**After**
chrome_2019-01-20_21-46-34

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
@bjarnef Don't you think that now (with a 3rd delete dialog being introduced) is a great time to start making it a directive instead that can be re-used everywhere?

**Comment by nul800sebastiaan** [comment]
Yep, I agree with all of that! And the hint here was: we need some help with that, so if you're up for it then that would be great to do in this PR!

**Comment by bjarnef** [comment]
@nul800sebastiaan can we create another issue and PR to solve that?

**Comment by nul800sebastiaan** [comment]
Sure, but my point is, we will not accept this PR and introduce technical debt that will need to be cleaned up. So let's do it correctly for this PR. 😊

**Comment by bjarnef** [comment]
@nul800sebastiaan at the moment this is how it is done for many other confirm modals in v8, e.g. in content: publish, publishdescendants, save, schedule, unpublish + delete in listview.

**Comment by nul800sebastiaan** [comment]
Really? Well okay then fine. Let's refactor at some other time then. :-)

**Comment by bjarnef** [comment]
Yep, e.g. the different confirm modals in content editing using `overlayService`.

https://github.com/umbraco/Umbraco-CMS/blob/temp8/src/Umbraco.Web.UI.Client/src/common/directives/components/content/edit.controller.js#L506-L538

**Comment by nul800sebastiaan** [comment]
How annoying, my OCD is being triggered.. ;-)


Testing this one now..

**Comment by nul800sebastiaan** [comment]
Wonderful, does what it says on the tin! 👍

**Pull request merged**
