### PR TITLE
NetCore: Abstract ConfigurationManager references

### PR DESCRIPTION
**Pull request by cyberdot**
### Prerequisites

- [] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/7667

### Description
Implements [#7667 ](https://github.com/umbraco/Umbraco-CMS/issues/7667)
In this PR I've created new `Umbraco.Abstractions` project. 

All `ConfigurationManager` references from the following files have been extracted:
`src\Umbraco.Examine.Lucene\LuceneIndexCreator.cs `
`src\Umbraco.PublishedCache.NuCache\DataSource\BTree.cs ` 
`src\Umbraco.Web\Composing\BuildManagerTypeFinder.cs`
`src\Umbraco.Web\Runtime\WebInitialComponent.cs`
`src\Umbraco.Web\Security\ActiveDirectoryBackOfficeUserPasswordChecker.cs`
`src\Umbraco.Web\Mvc\ModelBindingExceptionFilter.cs`
`src\Umbraco.Web\UmbracoApplication.cs`
`src\Umbraco.Web\Editors\BackOfficeServerVariables.cs`
`src\Umbraco.Web\Install\InstallSteps\DatabaseInstallStep.cs`

I've created corresponding interfaces in `Umbraco.Abstractions` project and their implementations
in `Umbraco.Configuration` project.

`src\Umbraco.ModelsBuilder.Embedded\Configuration\ModelsBuilderConfig.cs` have been moved to `Umbraco.Configuration` project and an interface for it has been created in `Umbraco.Abstractions`

### CODE REVIEW

**Comment by bergmania** [comment]
Hi @cyberdot..

Thank you.. 
I will just merge the `Umbraco.Abstractions` into the `Umbraco.Core`, before I do a real review and test.

The `Umbraco.Abstractions` was the old temporary name of `Umbraco.Core`. It is my bad the text in the issue was not updated

**Comment by bergmania** [comment]
Hi @cyberdot.

Overall this is super good work.

I changed a few bits, just to let you know:
- We don't want all projects to have a compile time dependency on `Umbraco.Configuration`
  - I moved a constant and some extension methods into core
- I move the container registration into the configfactory.
  - In this way, you can use the configurations before the container is initialized.

I can see that this was you first contribution 🎉 
Do you have a profile on Our - We can assign a `Contributor` badge we have you a link to your profile?

**Comment by cyberdot** [comment]
Hi @bergmania.
Thanks for your kind words and your detailed response!
Your changes make sense
I've just created profile on Our - https://our.umbraco.com/members/cyberdot/

**Comment by nul800sebastiaan** [comment]
Thanks @cyberdot - you now have a nice little contributor badge on your Our profile! 🌟

**Pull request merged**
