### PR TITLE
U4-10953- Help-drawer, (caption + h3 -> h5

### PR DESCRIPTION
**Pull request by madsoulswe**
Populate Caption in dashboardhelper
h3 -> h5

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks @madsoulswe - since I'm not very familiar with the help drawer, do you have a screenshot or something to show me what you're trying to do?

**Comment by madsoulswe** [comment]
Sure! I'm not sure what purpose the "tiny-help-dashboards" have, but I saw the code and tried it and i found a purpose? ^_^







<br/><br/>
Maybe @madsrasmussen knows?<br/>

<br/><br/>
And the dashboard.config<br/>

**Comment by madsrasmussen** [comment]
I think you found the perfect answer to that question 😃 The idea is that you can extend the drawer with your own documentation to editors, developers etc. As an example, we add lessons to the drawer from “the-starter-kit” with guides to extending the starter kit with new functionality. See example here: https://github.com/umbraco/The-Starter-Kit/tree/dev-v3/src/Umbraco.SampleSite.Website/App_Plugins/StarterKit

**Comment by nul800sebastiaan** [comment]
Thanks Dennis! 👍

**Pull request merged**
