### PR TITLE
V8: Accessibility Changes For umbEditorHeader Directive

### PR DESCRIPTION
**Pull request by RachBreeze**
This PR applies the accessibility amends made in https://github.com/umbraco/Umbraco-CMS/pull/6236 and https://github.com/umbraco/Umbraco-CMS/pull/5760 to the umEditorHeader Directive.

Specifically it aims to:

- Set the <title> attribute on the page based on the user's location
- Allow screen reader users to understand when they are creating an item what item they are creating
- Allow screen reader users to understand when they are editing an item what item they are editing

### CODE REVIEW

**Comment by RachBreeze** [comment]
Hi @nul800sebastiaan, @poornimanayar  and @emmaburstow 
This is marked as a draft PR because of the amends I have made to a core directive specifically the addition of the "editorfor".  It would be good to get this approach reviewed please.  If it is the correct approach then there are a few more controllers I need to add this to, specifically those that are used in the settings section.
Thank you in advance for your time

**Comment by emmaburstow** [comment]
Hi Rachel,

Thanks for getting in touch. We'll be sure to take a look and give you some feedback.

Emma

**Comment by RachBreeze** [comment]
Hi Emma
Really appreciate that thank you

**Comment by nul800sebastiaan** [comment]
Hi @RachBreeze, this looks fine to me, but I don't know why you're doubting this direction?

**Comment by zersiax** [comment]
This looks good to me, it will add some useful info. I think @RachBreeze is mainly being careful because the core code is touched, am I correct there?

**Comment by RachBreeze** [comment]
Hi @nul800sebastiaan and @zersiax  thank you for reviewing. Florian is correct I was concerned about touching something that everyone can reuse. I will look to finish off and submit a PR

**Comment by RachBreeze** [comment]
Hello,
This pull request is now ready for review.  In order to preserve backward compatibility the page title is only set if the header is explicitly told to set it.
The header directive is used in a number of areas.  This PR aims to address accessibility when it is used in the following locations

- Create/ edit media
- Create/ edit document types
- Create/ edit media types
- Create/ edit member types
- Create/ edit content templates
- Create/ edit templates
- Create/ edit partial views
- Create/ edit partial view macro files
- Create/ edit style sheets
- Create/ edit scripts

**Comment by RachBreeze** [comment]
There are a couple of areas still to do (and I will submit PRs for them) but am looking forward to getting feedback.  Cheers

**Pull request merged**
