### PR TITLE
Add color swatches directive

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org/issue/U4-11168

### Description
This is an alternative PR to https://github.com/umbraco/Umbraco-CMS/pull/2792 which instead add a directive for color swatches, which can be re-used in core and by third party packages.

Here is an example with both the directive (first):

```
<div class="umb-control-group">
        <umb-color-swatches colors="colors" selected-color="color" size="s"></umb-color-swatches>
</div>
``` 

and without a directive (bottom):
```
<div class="umb-control-group">
        <button ng-repeat="c in colors" class="button btn-{{c.value}}" ng-class="{ active: c.value === color }" title="{{c.name}}" ng-click="setColor(c.value)">
            <div class="check_circle" ng-class="{active:c.value === color}">
                <i class="icon-check small" ng-class="{active:c.value === color}"></i>
            </div>
        </button>
    </div>
```

```
$scope.changeColor = function (color) {
        $scope.model.color = color;
};
```

image

### CODE REVIEW

**Comment by bjarnef** [comment]
I have ordered the colors more by the color spectrum as suggested here; https://github.com/umbraco/Umbraco-CMS/pull/2657

image

**Comment by nul800sebastiaan** [comment]
@bjarnef I don't understand why there's all kinds of unrelated files here?

I would suggest to wait for @OwainWilliams to finish the last bits on his PR and then you can do a PR based on his fork, that would be much easier. I would love to combine the two but with all the unrelated files I can't see what you've actually changed.

**Comment by bjarnef** [comment]
@nul800sebastiaan I guess it is because this original was a fork of his branch.
I would love to contribute to his PR, but it seems like he don't want a directive for this stuff :)

**Comment by bjarnef** [comment]
I am not sure if it is possible to get rid of previous commits in a PR, but this changes I have made starts from this commit https://github.com/umbraco/Umbraco-CMS/pull/2793/commits/e76211227e19ff8b9e2dd25419d8d92e386d31c8

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef - I've manually applied the relevant changes to #2792 since I didn't want all that history of merge problems in there! 👍

**Pull request closed without merging**
