### PR TITLE
Maintenance page when in upgrade state

### PR DESCRIPTION
**Pull request by bergmania**
Fixes https://github.com/umbraco/Umbraco-CMS/issues/13309
Fixes https://github.com/umbraco/Umbraco-CMS/issues/13247

# Summary
The catch all route that existed to redirect to login/installer when in `RuntimeState.Level` = `Install` or `Upgrade`, made a lot of trouble when `RuntimeState.Level` = `Run`.
 This have been an issue since v9, because we can't reboot. Therefore the catch all route still existed when `RuntimeState.Level` = `Run`.
 
 This PR removes the catch all route. Redirects to installer is now handled by `UmbracoRouteValueTransformer` and to handle upgrades nicely, I have introduced a new Maintenance page.
 
 This is by default used, instead of redirecting website visits to the upgrader.  A new configuration is added, to not show the maintenance page, as most migrations can be handled without the website having to be down. The default value is to show the maintenance page, to keep it consistent with the current behaviour and handle those few cases where the website would be broken in the upgrade mode.
 
 The design on the Maintenance page can be overridden like for 404 page. By default it is inspired by the 404 page.
 
image

 
 # Test
The easiest way to test is to install a starter kit, so 404 pages can be tests just after install and upgrade. Furthermore, add a custom api, like in https://github.com/umbraco/Umbraco-CMS/issues/13309

 - Open Umbraco when not installed
   - Verify all paths show the installer
   - 404 page is not possible
   - Custom API controllers are not possible 
 - Install Umbraco
   - Verify umbraco works as expected in run mode
   - Verify 404 pages works
   - Verify custom api controllers works
 - Shut down Umbraco
   - Add migrations. E.g. the following in `UmbracoPlan.cs`: 
   ```cs
   To<NoopMigration>("{BABEBABE-BABE-BABE-BABE-BABEBABEBABE}");
   ```
 - Open umbraco (now the new maintenace page show show up on website requests)
  - Test 404 still works
  - Test custom APIs still works
  - Go to backoffice and verify it shows upgrader after login (Maybe login is skipped, if cookie is still valid)
- Finish the upgrade
   - Verify 404 pages works
   - Verify custom api controllers works
   - Verify website works as expected
   - Verify backoffice works as expected
- Close down Umbraco
- Start Umbraco (should start directly in Run)
   - Verify 404 pages works
   - Verify custom api controllers works
   - Verify website works as expected
   - Verify backoffice works as expected
 - Close down Umbraco
   -  Add another migrations. E.g. the following in `UmbracoPlan.cs`: 
   ```cs
   To<NoopMigration>("{BABEBABE-BABE-BABE-BABE-BABEBABEBAB2}");
   ```
   - Change the config `Umbraco:CMS:Global:ShowMaintenancePageWhenInUpgradeState` to `false`
- Start Umbraco (Now in upgrade)
   - Verify 404 pages works
   - Verify custom api controllers works
   - Verify website works as expected
   - Verify backoffice shows upgrader
 - Finish the upgrade
   - Verify 404 pages works
   - Verify custom api controllers works
   - Verify website works as expected
   - Verify backoffice works as expected
 - Close down Umbraco
  - Add a custom maintenance page in  `/umbraco/UmbracoWebsite/Maintenance.cshtml`, e.g.
  ```cshtml
 <!doctype html>
<html>
<body>

<h1>CUSTOM</h1>
</body>
</html>
  ```
     - Change the config `Umbraco:CMS:Global:ShowMaintenancePageWhenInUpgradeState` to `true`
- Start Umbraco (Now in upgrade)
   - Verify 404 pages works
   - Verify custom api controllers works
   - Verify the custom maintenance page is used
   - Verify backoffice shows upgrader
 - Finish the upgrade
   - Verify 404 pages works
   - Verify custom api controllers works
   - Verify website works as expected
   - Verify backoffice works as expected

### CODE REVIEW

**Review by nikolajlauridsen — COMMENTED** [review]
Overall it looks good and tests good 💪.

I did however run into one issue when testing this, and that is: If you're not logged in when authorizing the upgrade, you'll no longer actually be redirected to the login page (see video). 

I looked a little into it and it seems to come from [the frontend controller](https://github.com/umbraco/Umbraco-CMS/blob/v11/contrib/src/Umbraco.Web.UI.Client/src/views/common/authorizeupgrade.controller.js#L17) it looks like it expects a query parameter with the name `redir` however the query parameter is named `returnPath`.  I suspect this has been broken for a long time, but since we had a catch-all it didn't matter terribly what we redirected to.

Another thing that I noticed, but don't really think is an issue, but if you create your own non-umbraco controller, then it always gets routed, even when in the install state, however I think this is fine, since you're completely side-stepping umbraco specific routing with a controller like that, I tested it with this controller: 

```C#
[ApiController]
[Route("/test/[Action]")]
public class BasicApi : Controller
{
    [HttpGet]
    public string Test() => "TestNonUmbracoController";
}
```

https://user-images.githubusercontent.com/16456704/207053567-7eace70e-c7ad-4be7-b829-47707558660a.mp4

**Comment by nikolajlauridsen** [comment]
Tested out the redirect again, and that seems to work just fine 👍 

Unfortunately, though, I discovered another thing while trying to test the first issue 🙈 

If you don't have any content nodes at all when you hit an upgrade, the maintenance page won't be shown, you'll see the no nodes pages instead, I guess this is not a huge issue, since you can't really do much other than go to the backoffice, which starts the upgrade, but still.

Other than that it tests out great now. 

https://user-images.githubusercontent.com/16456704/207361627-538173d0-9ba6-4adf-9fd7-777ab26a0cd0.mp4

**Comment by bergmania** [comment]
Yeah, I have seen that too. I think it is a bit nasty to let our no-nodes handling check for upgrade state too, due to the limited use cases.

Do you think it worth it to handle this case too?

**Comment by nikolajlauridsen** [comment]
No, I agree, I think its fine that this is the case 😄 Especially since it is indeed a bit ugly if we have to add an additional check to the no-nodes handling, just to fix this very very edge case, especially considering that if you don't have content you're probably headed for the backoffice anyways, which starts the upgrade 😄 

So I think this is good the way it is, so I'll go ahead an merge this 😄

**Pull request merged**
