### PR TITLE
U4-10779 Allow Members tree to work independently of Member Types tree 

### PR DESCRIPTION
**Pull request by jchurchley**
Allow Members tree to work independently of Member Types tree by giving it permission to access the MemberType.GetAllTypes Method

### CODE REVIEW

**Comment by Shazwazza** [comment]
Hi, is there a related issue on the issue tracker for this? Can you describe the problem that this is fixing?

Thanks!

**Comment by jchurchley** [comment]
Issue is if you don't want a member group to be able to alter member types so you move the tree to settings/developer section. It breaks the general members tree.

I've treated a ticket here [](http://issues.umbraco.org/issue/U4-10779)

**Comment by jchurchley** [comment]
Proposed Testing Method:
Create user who only has access to Members "Application" section.
In the tree.config update the tree of alias "membersType" update application to "developer"
Login with created user and view Members section

**Comment by jchurchley** [comment]
Hi Shannon, Any chance of this being included in 7.7.9?

**Comment by nul800sebastiaan** [comment]
@jchurchley 7.7.9 is closed right now, we'll consider it for 7.7.10 though.

**Comment by jchurchley** [comment]
Thanks for the reply Sebastiaan! Hopefully see it in 7.7.10 or a suggestion of a work around.

Cheers

John

**Comment by jchurchley** [comment]
Hi Sebastiaan anychance this could be considered in 7.11?

**Comment by jchurchley** [comment]
Hi, do you have any coments on this? I just had an issue with one of my sites where a user who shouldn't really have access accidentally deleted the member custom properties. Would love to move the Member Types/Member Groups under the Developer section.

**Comment by nul800sebastiaan** [comment]
Thanks for the reminder @jchurchley and apologies for the delay!

I was a bit stuck on this one as I wasn't sure about the implications. But from recently moving the dictionary tree around I did learn how simple and easy this was. I've tested out the changes and they work great!

I'll merge them in and they will appear in the upcoming v7.12.0 coming in the next few weeks.

Thank you very much for the help and the ongoing check-ins for us to look at it! #h5yr 👍 🥇

**Comment by Shazwazza** [comment]
Ahh... I just noticed that `[UmbracoTreeAuthorize(Constants.Trees.MemberTypes)]` was then applied to the individual POST actions on the MemberTypeController, so the security issue isn't really a problem, however it would be easier to manage moving forward if these attributes were applied in the opposite fashion, else when a developer adds any POST action on the MemberTypeController they will need to know to explicitly apply `[UmbracoTreeAuthorize(Constants.Trees.MemberTypes)]` to it

**Pull request merged**
