### PR TITLE
Netcore: Fix unit tests, so they pass on linux too

### PR DESCRIPTION
**Pull request by bergmania**
Fixed unit tests so the pass on both windows and linux

### CODE REVIEW

**Comment by rustybox** [comment]
Not relevant to your PR but Is there a plan to get integration tests running at some point? 

perhaps using the ms sql docker images or something?

**Comment by bergmania** [comment]
> Not relevant to your PR but Is there a plan to get integration tests running at some point?
> perhaps using the ms sql docker images or something?

Currently, we don't have a plan.  I would love it to run on Linux, but it is not part of the scope for the Unicore project.

Even using a docker image, we would need functionality to create and drop databases, i guess?

**Comment by rustybox** [comment]
Is that any different to using LocalDb, LocalDbTestDatabase just calls DatabaseSchemaCreator.RebuildSchema, this should work for say sql developer or sql express also shouldn't it?

**Comment by bergmania** [comment]
Sorry, the `DatabaseSchemaCreator.RebuildSchema` should work without changes. By databases, I actually meant database instances/servers like the `LocalDb` class, which is used to create LocalDB instances

**Comment by rustybox** [comment]
yeah but that class just connects to localdb, calls create database in a sql command or copies around an mdf if it already exists.

**Comment by bergmania** [comment]
> yeah but that class just connects to localdb, calls create database in a sql command or copies around an mdf if it already exists.

It also uses the underlying `SqlLocalDB.exe`..

**Comment by rustybox** [comment]
But you wont need that because localdb wouldn't be used ?

**Comment by bergmania** [comment]
That's correct, but we still need functionality to somehow get or create the instance from the docker? Or would you "hardcode" that path/connection sting to the db in the docker image?

**Comment by rustybox** [comment]
master connection string I'd have in a pipeline variable + docker-compose file, set it as an environment variable for use by csharp.

**Comment by rustybox** [comment]
Here you go

```yaml
version: '3.1'

services:

  db:
    image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: bergmanias_super_secure_password
```

**Comment by bergmania** [comment]
I guess that could work. But then the requirement to run integration tests would be to have docker running (as linux containers), instead of LocalDB. This would be the same for windows, mac and linux, right?

**Comment by rustybox** [comment]
Doesn't have to be, you can use LocalDb for windows if you want, bit of conditional logic.

It'd just be nice if the integration tests on the CI server tested it works on Linux,

**Pull request merged**
