### PR TITLE
U4-9599 - Fix caret in font size select

### PR DESCRIPTION
**Pull request by bjarnef**
Issue: http://issues.umbraco.org/issue/U4-9599

This was also reported in http://issues.umbraco.org/issue/U4-7618 but I think this was never fixed for font size select.

Now it doesn't overwrite padding-right for `.mce-menubtn` which both "Format" and "Font Sizes" select dropdown has, but not the other buttons.

Before:
image

After:
image

It have also added an icon for `fontsizeselect` which used same icon as `styleselect` - just an icon the show it is an dropdownlist (list).

To test add the following to tinyMCEConfig.config

```
<command>
      <umbracoAlias>mcefontsizeselect</umbracoAlias>
      <name>Font size select</name>
      <icon>images/editor/fontsizeselect.gif</icon>
      <tinyMceCommand value="" userInterface="true" frontendCommand="fontsizeselect">fontsizeselect</tinyMceCommand>
      <priority>18</priority>
</command>
```

image

This could also be included as default, but just not enabled.

It would also be great to add `<name>` element to docs here, but somehow the "Edit" button at the top just return 404 page. https://our.umbraco.org/documentation/reference/config/tinymceconfig/

### CODE REVIEW

**Comment by bjarnef** [comment]
Note that it is only an issue, when using ricttext editor in the grid - where it adjust padding inside `.umb-grid`

**Comment by negyven6** [comment]
Hey Bjarne, I tested the issue on our latest version and it seems we fixed it already.
I will close this pull request, but if you still can reproduce the bug, feel free to reopen it.

**Comment by bjarnef** [comment]
Hi @negyven6 

I have tested with latest changed in `dev-v7` branch and I am also able to reproduce the issue with the latest changes.

**Steps to reproduce**

-  Add following command to `/config/tinyMceConfig.config`

```
<command>
      <umbracoAlias>mcefontsizeselect</umbracoAlias>
      <name>Font size select</name>
      <icon>images/editor/fontsizeselect.gif</icon>
      <tinyMceCommand value="" userInterface="true" frontendCommand="fontsizeselect">fontsizeselect</tinyMceCommand>
      <priority>18</priority>
</command>
```

- For Richtext editor datatype instance or a grid editor datatype instance, you should be able to see the missing icon for "Font size select", fixed in https://github.com/umbraco/Umbraco-CMS/pull/1780/commits/be1172d6042f1ef61b0dd3b80fac86091e269a1d

image

- Enable "Font size select" for a grid editor datatype instance and in toolbar, there is an issue with the caret (only when inside grid editor).

image

**Comment by bjarnef** [comment]
@negyven6 can you take a look at this again? 👍

**Comment by warrenbuckley** [comment]
@bjarnef added in the extra button and it all works as expected aligned in the toolbar

**Pull request merged**
