### PR TITLE
Ensure there's explicit scopes used for all service access in the Examine indexing logic

### PR DESCRIPTION
**Pull request by Shazwazza**
Follow up to https://github.com/umbraco/Umbraco-CMS/issues/8030#issuecomment-732232597 and https://github.com/umbraco/Umbraco-CMS/pull/7994

There is still one area of the background task logic in Umbraco Examine that wasn't using an explicit scope and if the call to that isn't cached we may get unexpected exceptions. 

This update should solve all of this now. With the previous change we put all indexing operations explicitly on a background thread which is good but we assumed that all DB/Scope operations were also being done in explicit scopes. Turns out one area was missing. This change ensures that this area has an explicit scope, but this change also goes ahead and just wraps the entire indexing logic on the background task in one outer scope so any new changes done within there will always be run within an explicit scope.

### CODE REVIEW

**Comment by mzajkowski** [comment]
Looks like the tests are failing. Might it be related with the introduction of the new code here?

**Comment by Shazwazza** [comment]
Have pushed an update, we'll see if that build passes. Have assigned as community-review tag - hopefully someone in the community or PR team can pick this one up

**Review by bergmania — APPROVED** [review]
Changes look good..  Btw, the changes to the tests really show why Builder pattern is valuable. If we had a ContentValueSetValidatorBuilder, you would only have to update the builder with the new `Mock.Of<IScopeProvider>()` and not all tests.

**Comment by Shazwazza** [comment]
@bergmania don't forget we need to apply the version tag to these things

**Comment by bergmania** [comment]
Need to talk with @nul800sebastiaan to know what versions this will be part of.

**Pull request merged**
