### PR TITLE
V8: Align delete dialog UX with the other dialogs

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

This one may be a matter of personal taste. But I really think it's weird how the delete dialogs have their buttons placed left-aligned in the top of the dialog, instead of in the bottom right like the other dialogs.

This PR moves the buttons to the bottom of the dialog for all delete dialogs and the empty recycle bin dialogs. 

#### This is how the delete dialogs look right now

image

#### This is how the delete dialogs look with this PR applied

image

### Testing this PR

To test this PR you basically have to delete a node of every type in the Content, Media, Settings and Translation sections, and verify that:

1. The dialog looks like the screen shot above.
2. If there is a confirmation checkbox (i.e. for doctypes), the delete option is disabled until the checkbox is checked.
3. You're able to actually delete the nodes.

🎄 21/24 🎄

### CODE REVIEW

**Comment by dawoe** [comment]
Hi @kjac,

Thanks for another PR.  3 more to go : -D

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by nul800sebastiaan** [comment]
Thanks @kjac - I'm going to have to get some feedback at HQ, while I agree it should be consistent it also seems that the buttons might be hard to find if they're not near the message.

**Comment by kjac** [comment]
Fixed merge conflicts.

**Comment by nul800sebastiaan** [comment]
Hey @kjac - we discussed this recently and the feedback was: for now, let's keep it the way it is (buttons right under the text and not all the way at the bottom of the screen) but move the buttons to the left so they align with the left border. Specifically we don't yet want to move it to the right since a lot of other buttons also align left. We need to think of a complete overhaul of these kinds of dialogs at some point as it is not very good UX to have a notification and then action buttons very far away from them.

**Comment by kjac** [comment]
@nul800sebastiaan roger that 👍 

Do say so if you need help with it.

**Comment by nul800sebastiaan** [comment]
@kjac Oh yes, forgot to say: please help! 😄

**Comment by kjac** [comment]
Sooo basically you just want me to move the existing buttons to the left... Right?

**Comment by kjac** [comment]
New PR in #4288 - I'm closing this now.

**Comment by kjac** [comment]
@nielslyngsoe here's the PR we discussed in the open space session last Friday 😄 let me know if you want me to redo it, should be possible.

**Comment by nielslyngsoe** [comment]
@kjac thanks, I approve the correction and have made sure #4288 will be reviewed soon :-)

**Pull request closed without merging**
