### PR TITLE
Update to TinyMCE implementation

### PR DESCRIPTION
**Pull request by Shazwazza**
This is a WIP

* Better configuration format
* Newest tinymce version
* Fixes "Loading..." issue
* Adds some nice additional plugins by default (needs review, etc...)
* Better implementation (not using a textarea) with ability to support all skin types including inline/inlite theme 
* Inline/inlite theme by default (need to add options for pre-values for devs to toggle this)
* Removes unnecessary old theme/skin files that are not needed at all, we instead just inject a stylesheet
* Since we now inject the backoffice stylesheet, by default it looks the same as the back office
* Streamlines the tinymce implementation between the normal rte and the grid rte (still more work to do)

* [ ] ~Upgrade to the Dev version of 5~
* [x] Need to add options for pre-values to toggle inline/inlite theme options
* [ ] Need to review plugin options
* [ ] Need to review having H1, H2, H3 as default styles (always)
* [ ] Need to finish streamlining the integration between the normal rte and the grid rte so there's no code duplication

### CODE REVIEW

**Comment by jaddie** [comment]
If the implementation of the RTE is being updated, would it be possible to make it so the property editor can be responsive instead of the current setup of having a fixed size dictated manually in the data type settings?

**Comment by warrenbuckley** [comment]
@Shazwazza any chance you got 5mins at some point to make sure this PR is upto date without merge conflicts that would be awesome - then I can see if I get time tomorrow to get this reviewed/tested & merged. But will chat to you at standup tomorrow about it!

**Comment by Nicholas-Westby** [comment]
> Need to review having H1, H2, H3 as default styles (always)

FYI, I typically add H2-H6 to the RTE via the config. I intentionally leave out H1 because it's almost always the case that there is some banner widget that has an H1 tag in it and I disallow adding H1's in the rich text editor (since I expect all the other headers aside from the main one two start at H2 or below).

**Comment by nul800sebastiaan** [comment]
Really good point @Nicholas-Westby !

**Comment by warrenbuckley** [comment]
Ah I renamed to temp8-tinymce (was hoping this PR got updated too)
But this is now merged in

**Pull request closed without merging**
