### PR TITLE
#7789 Prevent grid config being submitted if not valid

### PR DESCRIPTION
**Pull request by SvenPam**
Prerequisites

    I have added steps to test this contribution in the description below

Fixes issue: umbraco#7789
Description

I have disabled the submit button until JSON is valid.

### CODE REVIEW

**Comment by abjerner** [comment]
Thanks a lot @SvenPam - and congrats with your first PR for Umbraco 🎉 

I had a quick look at the code, and it seems to do the trick - but we'll have a extra look to make sure that it does 😉

**Comment by matterlab-admin** [comment]
Think I butchered the template sorry!

**Comment by SvenPam** [comment]
I butchered the template, sorry!

**Comment by abjerner** [comment]
@SvenPam don't worry about that 😉 

You done a good job with describing what is wrong in the issue, which should be sufficient 👍

**Comment by nul800sebastiaan** [comment]
Thanks @SvenPam - unfortunately this doesn't seem to work for me, I think it's because we check if the model is valid on `'blur'` but that might not be in time to prevent the button from being disabled?.
I am not sure how to fix this so I can't guide you unfortunately. Happy for better suggestions!

**Comment by SvenPam** [comment]
Sorry for taking a while to get back - the world needs a PR I think!

I'm really sorry, I'm having to do this blind as I can't run the back office. I've followed the contribution guide as best I can with a fresh install, but get errors like: "No url found for api name updateCheckApiBaseUrl" as soon as I log in.

I've pushed a possible solution to what you have described. Validation of JSON should happen on keyup, which should disable the submit button in the code from my previous commit. I imagine the error message will appear as you type, but this is - in my opinion - is better than losing data when you try to save it.

**Comment by nul800sebastiaan** [comment]
@SvenPam Alright, we need to fix your setup then, what's the problem in getting it to run the backoffice?

I think it's a TINY bit better, for sure, but unfortunately not good enough 🙈. We really just want to prevent the submit button from actually submitting anything until the validation errors are fixed. 

Let me know if I can help get your solution to run so you can do some proper debugging. In general it should be enough to run the solution from VS by pressing F5, you might want to go into the Task Runner Explorer and run the build task:

image

image

**Comment by nul800sebastiaan** [comment]
Hi @SvenPam did you happen to try again and make some progress? Would be nice to wrap this one up!

**Comment by SvenPam** [comment]
Hi @nul800sebastiaan! Hope you're safe and well.

The issue was server-side so Gulp, unfortunately, didn't help. Sorry that wasn't clear in my last comment. I've had another stab at this today, I deleted Umbraco temp data and reset the version and the API issue appeared went away, I guess it was an issue during installation.

I'm not familiar with Angular, so I hope this update is OK: it looks like I was referencing the state of an internal Angular component `ng-form` from outside its scope. It made sense to move the form scope higher and closer to the parent where the actual HTML form is. Subsequently, this solved the submit button not getting disabled as it was able to pick up `gridConfigEditor`.

**Comment by SvenPam** [comment]
Just to clarify: I did get it working and was able to test in my browser this time around.

**Comment by nul800sebastiaan** [comment]
Hi again @SvenPam - I seem to have forgotten to reply to this! 😅 

I think this doesn't really solve the problem unfortunately, it's quite annoying that on each keypress you get a validation error until you get the json to be valid. It's also a lot of overhead to keep checking that on each keypress. I think the real solution needs to be that we validate the json when pressing the Submit (should be "Save") button. 

I'll close this one for now but if you'd like to update this one then we'll be happy to give it another look! Thanks for the help so far! 👍

**Comment by SvenPam** [comment]
Ah, swing and a miss! Thanks for your time, glad to be of help.

**Pull request closed without merging**
