### PR TITLE
Fix for U4-5480 "Bad value for attribute rel on element img in Richtext ...

### PR DESCRIPTION
**Pull request by Jeavon**
...editor" by removing the attributes in the RTE value converter so they don't render on the front end site but still exist in the Umbraco UI

### CODE REVIEW

**Comment by Shazwazza** [comment]
It's a good fix without breaking stuff. Only thing I'm wondering are the performance implications but I think in the grand scheme of things it should be fine as we're already parsing links in the whole rte html, etc... in this method anyways.

**Comment by Shazwazza** [comment]
Have manually pulled this in, thx!

**Comment by Jeavon** [comment]
Fab!

**Comment by kgiszewski** [comment]
I know this is closed, but this broke a site of mine.  I'm gonna have to rollback to v7.2.4 :(  We were relying on the `rel` attribute and there is now no `data-` attribute to replace it.

http://issues.umbraco.org/issue/U4-5480

**Comment by Shazwazza** [comment]
@kgiszewski As mentioned by @Jeavon on that issue, you can replace the value converter with your own without stripping the attribute

**Pull request closed without merging**
