### PR TITLE
Allow indexing variant nodes when not all variants are published - fixes issues 11383.

### PR DESCRIPTION
**Pull request by jonnymoo**
### Description

This fixes https://github.com/umbraco/Umbraco-CMS/issues/11383

### The fix

The introduction of the new [Examine library changes](https://github.com/umbraco/Umbraco-CMS/commit/eba6373a1239d89770fa02287665b7ebfa3bd5db) caused an unintended consequence that it stopped indexing of nodes with language variants on them when one of the variants was unpublished.

It did this because meaning of ValueSetValidationStatus.Filtered became overloaded as:

1) This node is to be filtered from the search result - for instance if it is in the recycle bin
2) The set of values under this node have been exluded - for instance if one variant of the node is unpublished

The umbraco content index functionality uses "filtered" to decide whether to delete the node - i.e. inline with scenario 1. Unfortunately it means any node with an unpublished variant also gets caught in the net.

These changes align ValueSetValidationStatus.Filtered to indicate that a node is intended as filtered out of a search, not that parts of its contents had been excluded from the result.

This brings it inline with how it is used in Umbraco.Examine.Lucene/UmbracoContentIndex

Unit tests changed to indicate the intent of ValueSetValidationStatus.Filtered

Change to UmbracoViewPage to make model variable nullable (because the solution wouldn't build otherwise on 2022)

### Steps to test

1) Create a new umbraco system

2) Install the [detault starter kit](https://our.umbraco.com/packages/starter-kits/the-starter-kit/)

3) Follow the instructions for how to [implement Examine](https://our.umbraco.com/documentation/Reference/Searching/Examine/quick-start/)  

4) Make like easier by allowing your newly implemented search to search all content by changing the searcher code and removing the NodeTypeAlias("person") contrainst e.g.

    var searcher = index.Searcher;
    var results = searcher.CreateQuery("content").Field("nodeName", searchTerm).Execute();

5) If you do a search for say "contact" it should return the contact page:

image

6) Follow the instruction for how to [make your site multilingual](https://our.umbraco.com/documentation/tutorials/multilanguage-setup/)

7)  Make a the contact node multi-lingual - put when you go publish it - only publish the root language.
image

8) Repeat you search - before the fix, you will get no responses. After the fix the contact page will still be present.

Note: The fix applies at time of indexing, not at the searching. I.e. if you published your pages before the fix - you will need to re-publish after the fix to get your pages indexed.

### Unintended behaviours

This is correcting the behaviour of  how "filtered" on ValueSetValidationStatus is interpreted / making it consistent. 

I have done searches through the code and the status is not used in any other functionality so it looks safe. Existing unit tests back this up also. 

The ValueSetValidator class is public, so it is possible that external code could be using the filter status in what will now be the incorrect way (to indicate an exclusion of innards), however since the change was only introduced relatively recently I think it is unlikely. None the less - it could be so it may be worth mentioning in the release notes as a potential change in behaviour?     

### Prerequisites

- [x] I have added steps to test this contribution in the description below

### CODE REVIEW

**Comment by jonnymoo** [comment]
My commit clashed somewhat with the cleanup to remove warning - https://github.com/umbraco/Umbraco-CMS/pull/12369
I've merged the latest and redone the changes.

**Comment by nul800sebastiaan** [comment]
Thanks @jonnymoo and apologies for the fact that there's not been progress on this PR yet! It's the holiday season and that means many people are enjoying a sunny beach 🏖️ instead of evaluating pull requests. Thanks in advance for your understanding and patience. This fix seems great though and we'll get to it as soon as we can! 👍

**Comment by nathanwoulfe** [comment]
Heya @jonnymoo I've taken this for a spin, works exactly as advertised - previously nodes with an unpublished variant were not indexed, now they are. Appreciate the commented code and updated tests 😄 

I think this warrants a mention in the release notes that it may result in a change in behaviour, but it's non-breaking and fixes a genuine bug, so shouldn't be a problem. Pinging @nul800sebastiaan for confirmation, but otherwise I see no reason this shouldn't be merged 👍

**Comment by nul800sebastiaan** [comment]
I am just wondering why `isFiltered` was introduced in the first place. Any PRs / commit messages that shed a light on this?

**Comment by jonnymoo** [comment]
Hi @nul800sebastiaan - good question!

The change was introduced here about 4 years ago https://github.com/umbraco/Umbraco-CMS/commit/eba6373a1239d89770fa02287665b7ebfa3bd5db

The actual commit has quite a few other changes on in, but one of them is to update to a new version of the examine library. The filtered result is part of this. I think the issue is that the original contributor simply overloaded the meaning of filtered which worked in most scenarios, but not scenario where an unpublished variant is created. 

My change is to make consistent the meaning of ValueSetValidationStatus.Filtered to mean "This node is to be filtered from the search result"

So to answer your original question - I don't think the local "isFiltered" was actually required in the original commit. It was an accident.

**Comment by dawoe** [comment]
@nul800sebastiaan just stumbled onto this one because we running into this a well (after upgrade to V10). 99.9% sure this worked on V9

Any ETA when this will be merged ?

Dave

**Comment by bergmania** [comment]
Hi @jonnymoo..

I have merged latest contrib branch and investigated a bit.
I think you are completely right, with these changes - so thanks a lot for the PR. I'm sorry the process time have been that long.

**Review by bergmania — APPROVED** [review]

**Comment by bergmania** [comment]
Cherry picked to v11/dev

**Comment by bergmania** [comment]
And cherry picked to v10/dev

**Comment by dawoe** [comment]
@bergmania Awesome !

**Pull request merged**
