### PR TITLE
Adds nametemplates for grid editors

### PR DESCRIPTION
**Pull request by skttl**
#6633

### Description
This adds name templates to grid editors, that you can use like in Nested Content.

I have added some templates to the default grid editors too, as an example.

If there is no template available, the name will be used instead.

billede

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hiiiiii @skttl 

Fantastic work here. We'll look and let you know if we need anything more from you. Great work that you've done here. Name of the template in the grid will be suuuuuper handy.

Em

**Comment by elit0451** [comment]
Great work @skttl 👏 
Tested and it works as you described 👍 
Merging!

**Comment by Shazwazza** [comment]
@skttl + @elit0451 + @nul800sebastiaan this causes a ton of errors to be produced when adding an image to the grid

You can reproduce by:

Add an image block to the grid and don't select anything, you'll get a stream of JS errors:

```
VM2058:37 Error: [$interpolate:interr] Can't interpolate: {{ 'Image: ' + (value.udi | ncNodeName) }}
TypeError: Cannot read property 'toString' of undefined
https://errors.angularjs.org/1.7.5/$interpolate/interr?p0=%7B%7B%20'Image%3A%20'%20%2B%20(value.udi%20%7C%20ncNodeName)%20%7D%7D&p1=TypeError%3A%20Cannot%20read%20property%20'toString'%20of%20undefined
    at angular.js?cdv=299132534:138
    at Function.$interpolateMinErr.interr (angular.js?cdv=299132534:13620)
    at Object.interpolationFn [as nameExp] (angular.js?cdv=299132534:13950)
    at ChildScope.$scope.getTemplateName (umbraco.controllers.js?cdv=299132534:17479)
    at fn (eval at compile (angular.js?cdv=299132534:16387), <anonymous>:2:241)
    at expressionInputWatch (angular.js?cdv=299132534:17398)
    at Scope.$digest (angular.js?cdv=299132534:19095)
    at Scope.$apply (angular.js?cdv=299132534:19463)
    at angular.js?cdv=299132534:21564
    at TaskTracker.completeTask (angular.js?cdv=299132534:21194)
```

See: 
B0A94055-167C-4407-AA83-AAA50F55C677

**Comment by skttl** [comment]
Hi @Shazwazza 

Thanks for reporting this, I'll see what I can do about it :)

**Comment by skttl** [comment]
#7059

**Pull request merged**
