### PR TITLE
Fix styling of confirm actions in tags editor

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8526

### Description
This PR fixes some styling issues after merging https://github.com/umbraco/Umbraco-CMS/pull/5293 and moved trash icon inside `umb-confirm-action` in https://github.com/umbraco/Umbraco-CMS/pull/8198

It also fixes issues where no outline was shown on focus.
Since `umb-tags-editor` is a separate component I have moved the styling to `umb-tags-editor.less`, so it re-used developers will get the same styling. The property editor still has the `umb-tags` class which has styling with the limited width.

### CODE REVIEW

**Comment by bjarnef** [comment]
@nul800sebastiaan sure, will take a look at that as well 👍

**Comment by bjarnef** [comment]
@nul800sebastiaan actually the icons are still there, just too much padding.

image

It seemed @kjac changed this in https://github.com/umbraco/Umbraco-CMS/pull/8504 but it also affect these confirm and cancel buttons. Looking at a fix for this.

**Comment by bjarnef** [comment]
@nul800sebastiaan I have reverted the fix from @kjac so it only target `<button>` element directly below `umb-group-builder__property-action` (not delete button since this is moved inside `umb-confirm-action`), but both buttons has the `btn-icon` class.

So it should be good now 👍 

image

image

**Comment by nul800sebastiaan** [comment]
Yep, works great again now! 👍 ⭐

**Pull request merged**
