### PR TITLE
Listview Template {{ value | ncNodeName }} Problem #9145

### LINKED ISSUE #9145: Listview Template {{ value | ncNodeName }} Problem
If you follow instructions here:
https://github.com/umbraco/Umbraco-CMS/pull/6597
and create a column in a list view that uses {{ value | ncNodeName }} as the template, it works like so..

image

 until you are viewing the list view and do a hard refresh of the browser.. At which time the items appear as so

image

## Umbraco version

I am seeing this issue on Umbraco version: 8.8

Reproduction
------------

see above.. 

### Specifics
Not sure browser plays a role but I am using the latest version of safari.. and also Firefox..
I have my list view set to display 100 items so performance could be playing a role..

### PR DESCRIPTION
**Pull request by cleversolutions**
### Prerequisites

Fixes #9145 

### Description
Fixes 9145 by polling nameExp until it returns a value other than 'Loading...'
It's an ugly way to do this, but the angular infrastructure wouldn't accept a promise from a filter, and setPropertyValues isn't called by interpolation or ng-bind so simply resolving the filter in a safeApply wasn't re-evaluating the list view.

### CODE REVIEW

**Comment by cleversolutions** [comment]
Well this is odd, only b2f5b4d and 41f92cd should be included in this pr.

**Comment by cleversolutions** [comment]
Is there some way I can correct this pr, or should I try again?

**Comment by jacklawry** [comment]
v8.12.1 also still has this issue. Any idea when it will be applied to core?

**Comment by TRexStark** [comment]
Any chance we can get an update on this issue?

**Comment by hfloyd** [comment]
@cleversolutions Considering that the PR team is taking some time with this one... Is there any way that your fix can be added to a running site manually?

**Comment by jacklawry** [comment]
Yes the ability to add this *temp* fix to an exiting site would be great! 
This is still an issue in v8.16.0

**Comment by nul800sebastiaan** [comment]
Sorry for the delay this PR @cleversolutions! We would be happy to look at it but could I encourage you to try to make a new PR please? Something indeed went wrong with this one. To fix I would do the following 

- Check out the `v8/contrib` branch
- Synchronize it with our repository https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/.github/CONTRIBUTING.md#keeping-your-umbraco-fork-in-sync-with-the-main-repository
- Once you've got all the latest changes from us in your `v8/contrib` branch you can create a new branch from `v8/contrib`
- In the new branch you should be able to cherry-pick the two changes that you listed

As a bonus, if you don't commit between doing the cherry-picks you'll end up with just the 1 commit, making it look even nicer. 😄 

Let me know if you need some more help with that!

**Comment by cleversolutions** [comment]
Thanks @nul800sebastiaan, I will do that today. I'll name my new branch em-9145. I take it we will close this PR and I'll start a new PR from the new branch?

**Comment by nul800sebastiaan** [comment]
@cleversolutions Yep, that would be a new PR that would replace this one indeed! 👍

**Comment by cleversolutions** [comment]
Thanks @nul800sebastiaan I've created PR #11072 to replace this one.

**Pull request closed without merging**
