### PR TITLE
V8: Doctype icon color picker selection is broken

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

Oh no... color picker trouble again. This time in V8, though.

The doctype icon color picker is broken. No matter what color you select, you end up with black icon colors... even if your current icon isn't black:

icon-color-picker-before

This PR fixes it, and aligns the callback mechanism (`on-select`) with similar callbacks in V8:

icon-color-picker-after

### CODE REVIEW

**Comment by emmaburstow** [comment]
Happy Monday @kjac!

Thanks for the work. We'll give you a shout if we need a thing,

Em

**Comment by kjac** [comment]
Happy Monday!

**Comment by warrenbuckley** [comment]
Connects #4420

**Comment by warrenbuckley** [comment]
Thanks @kjac code reads fine & I have tested it.
All merged in

**Pull request merged**
