### PR TITLE
V8: Filter out invalid selections in the MNTP "Allowed items" picker

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

The "Allowed items" picker does not impose any limitations when configuring the MNTP. In fact it allows you to select container nodes (folders), even though that makes no sense whatsoever and also leads to an error:

image

This PR imposes the following restrictions on the "Allowed items" picker:

1. Do not pick containers (folders).
2. Do not pick element types (specifically for content).
3. Do not pick any item that has already been picked.

It all comes together like this:

tree-source-invalid-selections

### CODE REVIEW

**Comment by emmaburstow** [comment]
Yo Kenn, whaddup?

Thanks for the work here. We'll holla if we need you - as ever.

Emma

**Comment by poornimanayar** [comment]
Hi @kjac ,

I have tried testing this for a new MNTP datatype as well as an existing datatype and I am unable to select any allowed types. Can you test once again and comment? I have tried testing in Incognito mode as well but cannot see this in action. 

Poornima

**Comment by kjac** [comment]
@poornimanayar my apologies, something's definitively gone terribly wrong here. I can't select any items either. I'll have a look.

**Comment by kjac** [comment]
@poornimanayar super weird... it's like underscore.js started acting different since I tested this. Anyway - I've made the filtering more robust, it should work now.

Sorry for the inconvenience.

**Comment by poornimanayar** [comment]
No inconvenience at all! I will give it a spin again today :-)

**Comment by poornimanayar** [comment]
@kjac ,

There still seems to be trouble. I have 2 element types - one inside a folder and one in the main tree. I can still select those. Can you check and let me know?

MNTP

Poornima

**Comment by kjac** [comment]
@poornimanayar how strange, I don't see that at all!

mntp-filter

I have even tried running `npm install` from the latest v8/dev just to see if there's some package dependency difference going on... same result.

**Comment by poornimanayar** [comment]
@kjac, let me test it again! Watch the space :-)

**Comment by kjac** [comment]
Yay 😀

**Comment by nul800sebastiaan** [comment]
Hot stuff, works like a charm! 🔥

**Pull request merged**
