### PR TITLE
Prevent subtle casing changes to app path names generating a different hash value for the system lock.

### PR DESCRIPTION
**Pull request by John-Blair**
Try merging onto this branch again.
I only changed 1 file MainDom.cs - but git thinks i changed over 800!

Prevent subtle casing changes to app path names e.g. c:\home to c:\Home generating a different hash value for the system lock.

### CODE REVIEW

**Comment by Shazwazza** [comment]
Hi @John-Blair yep something has gone awry with this one, it also says it's from an unknown repository so that seems odd.

I'll need to close this one if you can open up another one, that would be great.

Also note, that anytime you are submitting a PR, it should be done from your own custom made branch, even if you are targeting a different branch other than `dev/v8`. 

So for example, if you want to make PRs against this core branch: `umbraco:v8/bugfix/6546-MainDom-Cleanup` you should pull down all sources (both your own forked repo + this repo), checkout the `umbraco:v8/bugfix/6546-MainDom-Cleanup` branch and then create a new local branch (called whatever you like), and push that to your own repo, then use the Create PR button in GitHub and then select the `umbraco:v8/bugfix/6546-MainDom-Cleanup` as the target branch. 

It is then possible to pull all changes from both your own forked repo + this repo and then merge changes from `umbraco:v8/bugfix/6546-MainDom-Cleanup` back into your own custom branch and re-push which will automatically update the PR.

**Comment by John-Blair** [comment]
> it also says it's from an unknown repository so that seems odd.

Sorry, I deleted my forked repo to get me back in alignment. I had screwed it up by rebasing onto the "v8/bugfix/6546-MainDom-Cleanup" branch  so i couldn't see your branch code changes -  instead of just working on the branch - lack of git knowledge and your process for change.

I now manage to see your branched changes and will (try to) follow your instructions for any further changes.

**Comment by Shazwazza** [comment]
Cool, happy to help with any git related stuff, once you get it, you'll have an 'aha!' moment. Not sure what Git client you use but I use Git Extensions: https://gitextensions.github.io/ IMO it's the best client out there. It's all GUI based so you don't need to know all the fancy cmd line stuff if you don't want to, otherwise there's some additional docs on how to do all this stuff here https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/.github/CONTRIBUTING.md#which-branch-should-i-target-for-my-contributions

**Comment by John-Blair** [comment]
Thanks - I'm just using the Team Explorer in Visual Studio - but will take a look at your suggestion!

**Pull request closed without merging**
