### PR TITLE
Allow use of infinite editor in list views

### LINKED ISSUE #8341: Provide list view directive option to edit items in infinite editor
The current list view implementation assumes that clicking an item will simply send it to it's editor interface, however, with the advent of infinite editing, it would be nice for people reusing the directive to be able to state whether the list view should open as normal, or whether it should open the item for editing in an infinite editor window.

### PR DESCRIPTION
**Pull request by skttl**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #8341

### Description
This one adds a new setting to a list view definition, allowing you to enable infinite editing for the content in the list view.
image

vEcb4rPQqL

To test, set a list view to use infinite editing and verify that clicking an item in the list view opens the item in an infinite editor.
Also verify that creating new items opens in an infinite editor.

**Note:** Blueprints hasn't been implemented in the editorService, so they don't open an infinite editor when getting created.

### CODE REVIEW

**Comment by nielslyngsoe** [comment]
@skttl I love this! I just have one concern which is; what if a Content Editor wants to send a BackOffice link to a colleague to a specific article? Browser URL is not updated when opening infinite editors, right?

I just wanted to share that thought, we might just make an issue to solve that in some way?

:-)

**Comment by skttl** [comment]
Valid point - but isn't that a general problem with infinite editors?

**Review by nathanwoulfe — APPROVED** [review]
@skttl this is awesome, really nice work. It all works as expected 👍

**Comment by bjarnef** [comment]
Not sure if it is affected by this change, but after upgrading af site from Umbraco v8.8.4 to v.8.12.1 the "go to" link doesn't work in my custom listview layout.

It is throwing this console error:
image

**Controller**
```
(function () {
    "use strict";

    function ListViewGridLayoutController($scope, $routeParams, mediaHelper, mediaResource, listViewHelper) {

        var vm = this;

        vm.nodeId = $scope.contentId;

        $scope.toggleItem = function (item) {
            if (item.selected) {
                listViewHelper.deselectItem(item, $scope.selection);
            } else {
                listViewHelper.selectItem(item, $scope.selection);
            }
        };

        $scope.gotoItem = function (item) {
            listViewHelper.editItem(item);
        };

        $scope.items = $scope.items.map(function (obj) {

            if (obj.contentTypeAlias === "employee") {
                var imageProp = _.find(obj.properties, function (p) { return (p.alias === "image"); });
                if (imageProp) {
                    obj.thumbnail = "https://www.gravatar.com/avatar/?d=mm&s=100&f=y";

                    var mediaId = imageProp.value;
                    if (mediaId) {
                        mediaResource.getById(mediaId).then(function (media) {
                            obj.thumbnail = mediaHelper.resolveFile(media) + "?width=100&height=100&mode=crop&animationprocessmode=first";
                        });
                    }
                }
            }

            return obj;
        });
    }

    angular.module("umbraco").controller("ListView.GridMembersLayoutController", ListViewGridLayoutController);
})();
```

**View**
```
<div ng-controller="ListView.GridMembersLayoutController as vm">
    
    <div class="umb-content-grid employees-grid">     
        <div ng-repeat="item in items" 
             class="umb-content-grid__item employees-grid__item umb-outline umb-outline--surrounding"
             ng-class="{' -selected': item.selected }"
             ng-click="toggleItem(item)"
             role="button"
             tabindex="0">
            <div class="employee-details">
                <div class="image-wrapper">
                    <img ng-if="item.thumbnail" src="" ng-src="{{item.thumbnail}}" alt="" draggable="false" />
                    <umb-icon icon="{{item.icon}}"></umb-icon>
                </div>
                <a href="" ng-click="gotoItem(item)" class="employee-name">{{item.name}}</a>
                <small class="muted">{{item.email}}</small>
            </div>
        </div>
    </div>
    
    <umb-empty-state
        ng-if="!items && options.filter.length > 0"
        position="center">
        <localize key="general_searchNoResult"></localize>
    </umb-empty-state>

</div>
```

**Comment by nathanwoulfe** [comment]
The compatibility issue with custom list views is fixed in #10018

**Pull request merged**
