### PR TITLE
V8: A few UX updates to the listview move dialog

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

The move dialog used by listviews is lacking a bit UX wise:

1. Unlike the move dialog used by the trees it does not have any contextual help text ("Choose where to move [node name] to in the tree structure below"). If you're not used to the Umbraco move dialog, you're kinda left wondering what to do here.

2. The "Submit" button is always enabled. If you click it without choosing a target for the move operation, the dialog simply closes without any user feedback.

image

This PR addresses both issues. When applied the move dialog works like this:

listview-move-update

### CODE REVIEW

**Comment by kjac** [comment]
Updated with latest v8/dev

**Comment by kjac** [comment]
Updated with latest v8/dev

**Comment by kjac** [comment]
Updated with latest v8/dev

**Comment by poornimanayar** [comment]
hello @kjac ,

Can you fix the merge conflicts with the language files.

Poornima

**Comment by kjac** [comment]
@poornimanayar that ought to do it 👍

**Comment by poornimanayar** [comment]
And merged!

**Pull request merged**
