### PR TITLE
U4-9025 - Add sortable to color picker prevalues

### PR DESCRIPTION
**Pull request by bjarnef**
Issue: http://issues.umbraco.org/issue/U4-9025

I have added sortable to color picker prevalues, like multivalues prevalue editor.
However it has some issues saving model.value after sorting ... ui-sortable require `ngModel`, but when I add this, then `ui.item.index()` returns another value, than if it is not added.

I have previously noticed some bugs in then current version - not sure if this is related to this issue:
https://github.com/angular-ui/ui-sortable/issues/218

I have also updated multivalues prevalue editor, so you can't add same prevalue twice like in color picker prevalues - e.g. if you add "Test 1" and then "Test 1" again you will get an error on save anyway.

### CODE REVIEW

**Comment by madsrasmussen** [comment]
Hi Bjarne,

Thanks for the PR. I have tested your changes and I am not able to get the reorder to work. It looks like the server has reset the sort order when the data comes back after save. Is this something you can look into?

Thanks.

**Comment by bjarnef** [comment]
Hi Mads

Yes, that was the only thing I was missing. Often when using `ui-sortable` it is enough to add `ng-model` on the container where `ui-sortable` directive is added. I also tried using same sort functionality from multivalues prevalue editor, but didn't seem to work correct.

Even the order (indexes) was correct after sorting, on save it seems to change to order. Not sure if there is some other logic server side on this part?

**Comment by madsrasmussen** [comment]
I have just tested the ```ui-sortable``` and it works fine with the ```ng-model```. It updates the model fine and I think we will be able to remove all the code in the ```update``` callback. I think the problem is the way the server handles the preValues and resets the order again. I will have to get some assistance from @Shazwazza because I don’t know the reason why we are doing this.

**Comment by bjarnef** [comment]
@madsrasmussen @Shazwazza maybe it is this that change order of the array? https://github.com/umbraco/Umbraco-CMS/blob/5397f2c53acbdeb0805e1fe39fda938f571d295a/src/Umbraco.Web/PropertyEditors/ColorListPreValueEditor.cs#L32

I think it creates a new list, which is ordered by the value? As I remember I think black (#000000) was always re-ordered to this first item.

**Comment by bjarnef** [comment]
I had a closer look at this yesterday and compared with multivalues prevalus editor for e.g. dropdownlist where sorting works. I noticed this get its model for "items" updated with id, value and sortorder from serverside.

In ValueListPreValueEditor.cs is order by sortorder, which it doesn't in ColorListPreValueEditor.cs

https://github.com/umbraco/Umbraco-CMS/blob/5397f2c53acbdeb0805e1fe39fda938f571d295a/src/Umbraco.Web/PropertyEditors/ValueListPreValueEditor.cs#L67

Furthermore ValueListPreValueEditor.cs use this part:

https://github.com/umbraco/Umbraco-CMS/blob/5397f2c53acbdeb0805e1fe39fda938f571d295a/src/Umbraco.Web/PropertyEditors/ValueListPreValueEditor.cs#L74-L82

In Angular controller for multivalues prevalue it furthermore has:
https://github.com/umbraco/Umbraco-CMS/blob/5397f2c53acbdeb0805e1fe39fda938f571d295a/src/Umbraco.Web.UI.Client/src/views/prevalueeditors/multivalues.controller.js#L11-L22

Maybe prevalue editor for color picker should be moved to prevalues folder in a major version, so e.g. package developers can use it - or other property editors.

**Comment by bjarnef** [comment]
I reviewed more of the source code and how the multivalues prevalues works, which are used for dropdown, checkboxlist, radiobuttonlist..

In commit bbf3dff I have updated the model for colors, so it also has a id, value and sortOrder properties.

image

I have also updated the property editor to use the new model.
image

It could also set id and sortorder when appending new items to array client side - and before saving to server side - however it doesn't seem to be necessary and the multivalues prevalues doesn't do this either.
To demonstrate this:

Before save:
image

After save (model updated with sortOrder and id):
image

**Comment by bjarnef** [comment]
I am not sure if the logic in ui-sortable update function is necessary if the view has ng-model, which I think is required, otherwise it write info about this in console window.
image

```
<div ui-sortable="sortableOptions" ng-model="model.value">
...
</div>
```

**Comment by bjarnef** [comment]
After this PR has been solved/merged I can update PR https://github.com/umbraco/Umbraco-CMS/pull/1503 so it is possible to use color prevalues in grid editor config.

**Comment by bjarnef** [comment]
@Shazwazza can you check if the server side logic to sort the prevalues is correct?

**Comment by bjarnef** [comment]
I think this is almost finish. @Shazwazza does the server side code look correct? :)

**Comment by zpqrtbnk** [comment]
Hey,
I know it's been a looong time... but since your proposed this PR, we have merged another PR which adds support for labels to the color picker. It's not in branch `dev-v7`. I wanted to review your PR next, but of course it cannot merge easily now. Do you think you would have a moment to review your changes?
Thanks!

**Comment by bjarnef** [comment]
Hi @zpqrtbnk 

I can have a look at it maybe tonight or one of the next day and update the branch with latest changes in `dev-v7` branch.

I guess the other feature is part of `dev-v7` branch now?
https://github.com/umbraco/Umbraco-CMS/pull/2245
http://issues.umbraco.org/issue/U4-5322

**Comment by bjarnef** [comment]
@zpqrtbnk I have updated the branch with latest changed in `dev-v7` and resolved the conflicts. However some of my changes is missing and need to be merged with the new label feature.

On server side in `ConvertEditorToDb` it need to update to SortOrder and in javascript array also have a sortOrder property.

I have also fixed a few other issues:

- Localization of `choose` and `cancel` text in color picker
- `val-highlight` didn't highlight on error, it seems it needs to be wrapped in `{{ }}` https://github.com/umbraco/Umbraco-CMS/search?utf8=%E2%9C%93&q=val-highlight&type=

I also noticed I can't add two different colors with same Label value?

**Comment by nul800sebastiaan** [comment]
Hi @bjarnef - I've been trying to figure out how to make this one work, but the `ColorListPreValueEditor` has changed over time and I can't figure out how to add sorting to it. 

Currently there's a few problems: sort order is not sent to the server, when I do send the sort order it's not persisted, when I do persist it (`ConvertEditorToDb`) then it's not applied (`ConvertDbToEditor`) when I do apply it the result is in the correct order but... in the browser they're suddenly sorted wrong again even though the response to the browser looks good, so might be something in js going on?

Maybe it would be better to start this one from scratch, what do you think?

FYI I updated `ConvertEditorToDb` like this to persist the `sortOrder`:

```
                        int.TryParse(x["sortOrder"].ToString(), out var sortOrder);

                        var value = useLabel
                            ? JsonConvert.SerializeObject(new { value = color, label = label, sortOrder = sortOrder.ToString() })
                            : color;
                        return new PreValue(id, value, sortOrder);
```

And in `ConvertDbToEditor` I'm retrieving it in the correct order like so:

```
            var dictionary = persistedPreVals.FormatAsDictionary();
            var items = dictionary
                .OrderBy(x => x.Value.SortOrder)
```

**Comment by nul800sebastiaan** [comment]
Ah crap, now I've messed it up! :-(

I pushed my changes, but that also included the merge so now everything is changed. Yikes. Well, have a look at the current state and then if you could see if you can figure out how to include the `sortOrder` on the model so it's actually sent to the server and then when the sorted results come back if you can display them in the correct order then we can figure out how to untangle this mess here :/ Sorry about that!

**Comment by bjarnef** [comment]
@nul800sebastiaan indeed it is a bit of a mess now and Github only shows latest 250 commits, so I can't actually see what I committed two years ago 😬😀 

image

**Comment by bjarnef** [comment]
@nul800sebastiaan I will close this PR since I have cleaned up this mess and I have opened this new PR instead https://github.com/umbraco/Umbraco-CMS/pull/2775 🦄

**Pull request closed without merging**
