### PR TITLE
Change translation for add row for fix issue U4-6564

### PR DESCRIPTION
**Pull request by Aaen**
I have changed the translatation to fix issue U4-6564

### CODE REVIEW

**Comment by Shazwazza** [comment]
Yup, definitely agree with that!

**Comment by sitereactor** [comment]
First pull request :sparkles: :smiley:

**Comment by Aaen** [comment]
The first pull request that have been merged in and the first one as HQ member. I have made some before that was manually merged in

**Comment by sitereactor** [comment]
:+1: so you're already a seasoned pro :wink:

**Pull request merged**
