### PR TITLE
Unit test for template editor.

### PR DESCRIPTION
**Pull request by lars-erik**
Currently testing that masterpage and layout is set.

### CODE REVIEW

**Comment by lars-erik** [comment]
Actually blows up karma. Will try to fix. Hold for now. :)

**Comment by lars-erik** [comment]
Works with Karma but not R# runner. Can be pulled now.

**Comment by lars-erik** [comment]
\o/ Hope the test doesn't wither and die while the template editor evolves. ;)

**Comment by Shazwazza** [comment]
me too :) I need to create a task for the whole thing too

**Pull request merged**
