### PR TITLE
Boolean editors - adds ID attribute to umbToggle

### PR DESCRIPTION
**Pull request by leekelleher**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

The Boolean editor (aka. TrueFalse, aka. Checkbox 🤔) using the `<umb-toggle>` directive (for both prevalue-editor and property-editor), isn't associated with the property's `<label>`.

ECBnKKPXsAExgUM

Meaning that if a user clicks on the property label, nothing happens.  Previous with the old checkbox (e.g. native HTML input), this would check/uncheck the input.

By adding an `id` attribute, with the property's alias (e.g. `id="{{model.alias}}"`), it will be associated with the toggle control.

In terms of testing, it'd be a case of clicking the label, and see the toggle state change.

### CODE REVIEW

**Comment by bjarnef** [comment]
Should we add this as a property `input-id` (inputId) like in `umbCheckbox` and `umbRadiobutton` and use this value to add the `id` attribute to the button element here?
https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/views/components/buttons/umb-toggle.html#L1

https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/common/directives/components/forms/umbcheckbox.directive.js#L60

https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/views/components/forms/umb-checkbox.html#L3

**Comment by leekelleher** [comment]
@bjarnef Sure, can do. 👍 I wasn't sure where else `<umb-toggle>` was used, so didn't want to change the directive itself.

**Comment by leekelleher** [comment]
@bjarnef I've updated the PR with your suggestion. 👍

**Comment by nul800sebastiaan** [comment]
Wonderful, thanks very much @leekelleher ! 👍

**Comment by nul800sebastiaan** [comment]
Hi there @leekelleher,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing 🥇 

We have had another record breaking amount of PR's in both the CMS, Documentation, and other smaller public repositories. You can read all about the numbers in the [Umbraco Hacktoberfest round-up blog post](https://umbraco.com/blog/pr-team-update-november-2019-hacktoberfest-round-up/).

Due to the amazing work you and others in the community have been doing, we've had a bit of a hard time keeping up. 😅 While all of the PRs for Hacktoberfest might not have been merged yet, you still qualify for receiving some Umbraco swag, congratulations! 🎉 

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://docs.google.com/forms/d/e/1FAIpQLSc-K97Zl5k86cVebKWWqieLM4Fm_jCMGVdbQdYnq4IUJ7EvZg/viewform) :point_left: Please follow this link to fill out and submit the form, **before December 19th 2019**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before February, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Comment by leekelleher** [comment]
@nul800sebastiaan Thanks Seb! (form completed) 🎉

**Pull request merged**
