### PR TITLE
Improve system information/telemetry

### PR DESCRIPTION
**Pull request by JasonElkin**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Differentiate between IIS & IIS Express
I noticed that the system information in the backoffice help menu doesn't differentiate between IIS and IIS Express. I think it probably should, so this adds that distinction.

To test: Open the help menu, then system information, while running in IIS Express and it will tell you that you're using IIS Express.

#### I'm not convinced by the Kestrel detection...

The IIS & IIS Express check makes sense, as the point of those servers is that they host the site in process. Kestrel is a little different as it's bootstrapped _inside_ of ASP.NET. Kestrel is the default, but presumably the web server _could_ be HTTP.sys or some other IServer implementation.

I think the only way to know for sure is to inject IServer and get the name of the class implementing it, but that adds a dependency on [Microsoft.AspNetCore.Hosting.Server](https://learn.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.hosting.server?view=aspnetcore-6.0) to Umbraco.Infrastructure.

### Add runtime mode

As per the suggestion in #12631, this adds the runtime mode to the system information/telemetry.

To test: Open the help menu, then system information, and you'll see the runtime mode reflected in the system information.

### CODE REVIEW

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Thanks for this update @JasonElkin 👍
Regarding your last point on Kestrel, maybe this could be added as breaking change into V12 (looking at you @nul800sebastiaan 😁) ?
Cheers!

**Comment by nul800sebastiaan** [comment]
I don't think we should add a dependency if the only thing we need it for is this. I'm also very happy if instead of "Kestrel" we say "Likely Kestrel" or something like that.

**Comment by mikecp** [comment]
Yes I agree, I almost suggested putting "Not IIS" 😅

**Comment by mikecp** [comment]
But of course then it becomes labelized/localized 😉

**Pull request merged**
