### PR TITLE
Fixing danish typos

### PR DESCRIPTION
**Pull request by AndersBrohus**
This fixes the issue #14183 where we found some typos in the danish translation of the Block Grid editor :)

### CODE REVIEW

**Comment by abjerner** [comment]
Great spot @AndersBrohus 👍 

While you're at it, I would argue that  **standard layout** should be **standardlayout** (as nouns aren't separated by spaces in Danish). Could you fix this as well?

Otherwise it looks good 😉

**Comment by AndersBrohus** [comment]
Of course, it has been changed now :)

**Comment by nul800sebastiaan** [comment]
Thanks again @AndersBrohus! And a heads up: absolutely no need to create an issue if you already are making a PR, just create the PR and tell us what it's fixing!

**Comment by nul800sebastiaan** [comment]
Cherry picked for 10.6 in e27e8d1189dfd35244aa66fe0c2a8fd9dc02a22f

**Pull request merged**
