### PR TITLE
V8: Support multiple URL aliases in umbracoUrlAlias

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5823

### Description

Apparently it's possible to enter multiple URL aliases in `umbracoUrlAlias` by separating them with comma (*not* comma+space, though!). However, as #5823 points out, the backoffice doesn't really honor this scenario.

Turns out the `AliasUrlProvider` is the culprit. This PR updates it, so it can handle multiple URL aliases:

multiple-url-aliases

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey Kenn,

Thanks for this. We'll shout if we need anything from you.

Em

**Comment by ronaldbarendse** [comment]
@kjac What about the case when no domains are configured?

https://github.com/umbraco/Umbraco-CMS/blob/cc940f719dd92236fbe0e2d0d450fe53a37bd94b/src/Umbraco.Web/Routing/AliasUrlProvider.cs#L76-L93

**Comment by kjac** [comment]
@ronaldbarendse 👍 good catch. I'll amend the PR.

**Comment by kjac** [comment]
Done 👍

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by bmargevicius** [comment]
Did this PR get merged in? I really would like to have this feature restored..

**Comment by ronaldbarendse** [comment]
@bmargevicius The PR is still open, so no...

@kjac It would be nice if the multiple textstring editor could also be used for this property, so you can see the URLs in a list and easily remove/add items. What happens when we retrieve the value using `node.Value<string[]>()`?

**Comment by bmargevicius** [comment]
Thanks for the reply, I hope this gets pushed soon. I have a project in development sort of depending on this feature. I have a work around, but I'd rather not include my own route maker. 🎆Happy Friday the 13th everyone 🎆

**Comment by nul800sebastiaan** [comment]
Works well, thanks very much @kjac and @ronaldbarendse for the double-check! 👍

**Comment by nijdamb** [comment]
Hi there,

I'm sorry, as this is an old case but has there been any changes to possibly include the "repeatable text string" editor for this field?
With a comma separated list it's not very user friendly when you have more than 2 aliasses in the input.. especially if those aliasses aren't single words.
Having the "repeatable text string" editor work too would give a lot better overview on what Aliasses are set on a content node.

If I've missed any more recent cases for this I'm sorry, but this came up in Google :)

**Pull request merged**
