### PR TITLE
V8: Accessibility Changes For umbEditorHeader Directive (settings section)

### PR DESCRIPTION
**Pull request by RachBreeze**
This PR extends #6315 adding the screen reader properties and setting the page title for almost all of the remaining menu items in the settings section.   It leaves the language and the log viewer as the remaining items to update within this section

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @RachBreeze ,

Thank you, you know what happens next!

Poornima

**Comment by RachBreeze** [comment]
Hi @kjac 
Yep I can look at the merge conflicts.
I did try and set the properties on `umb-editor-header` originally but it wouldn't pass through to the header controller

**Comment by RachBreeze** [comment]
Hi @kjac 
Thank you once again for reviewing.
I've merged the language files, if you have a sec it would be good to know how I can set VS to keep the formatting the same as those in the xml files, even when I copy and paste the indentation I can't keep it the same :-(

**Comment by kjac** [comment]
As for the language files, well... that's a longer story. 

At some point in the past someone formatted one or more of them in a manner that doesn't conform to the default indentation which 4 spaces, as defined in `.editorconfig`:

```
# Default settings:
# A newline ending every file
# Use 4 spaces as indentation
[*]
insert_final_newline = true
end_of_line = crlf
indent_style = space
indent_size = 4
```

As a result, VS fails miserably at indenting these files.

What I usually do is hit Ctrl+Z immediately after copying and pasting an entry in the language files if the indentation looks wrong. VS will usually undo it's failed auto-formatting then, leaving behind something that at least *looks* correct (even if it is wrong according to `.editorconfig`).

Logic would dictate that we should simply force format those files in a separate commit to `v8/dev` and be done with it. Unfortunately this would leave a whole lot of existing PRs with a merge conflict 😞

**Comment by kjac** [comment]
Merged. Thanks again, @RachBreeze 👍

**Pull request merged**
