### PR TITLE
Umbraco accessible

### PR DESCRIPTION
**Pull request by JeffreyPerplex**
Making Umbraco keyboard navigatable. Related issues: http://issues.umbraco.org/issue/U4-9991 &

### CODE REVIEW

**Comment by greystate** [comment]
High praise 🙌 🎉

**Comment by warrenbuckley** [comment]
@JeffreyPerplex after CodeGarden & the retreat, what is the state of this PR?
Does it need some further work & polishing before we take a look over this to be considered & merged into the core?

**Comment by warrenbuckley** [comment]
@JeffreyPerplex as you worked on this with @madsrasmussen at the retreat, I quickly reached out to him and he has a small concern about the number of event listeners added to the tree which could be problematic for larger sites with lots of nodes.

I think @madsrasmussen is going to try & find some time to look over this, before its considered to be reviewed & tested. 

In the meantime can you please create an issue on our issue tracker for this, so we have an issue for this so it can be used in release notes.

Thanks again for the great work on this 👍
Warren :)

**Comment by JeffreyPerplex** [comment]
Hi @warrenbuckley,

thanks for the feedback and indeed that was what Mads said. Hopefully he can find some time, because I don't think the potential concerns about performance outweights the benefits. 

Lot of wisdom to you both :),

Jeffrey

**Comment by JeffreyPerplex** [comment]
Hi @warrenbuckley and @madsrasmussen ,

I've been thinking about this PR, but IMHO it's too good to leave it resting out here. Would it be a possibility to remove the event listener for the tree and commit the rest. There are more fantastic changes in this same PR.

Furthermore I think that the performance impact for the additional event listener is minimal and it wouldn't be that much of a concern. I know it's one more event listener, but the solution is so worth it for so many people.

Hope we can come up with a (partial) solution soon. By doing that we (as Perplex) can restart this project also and improving Umbraco even further for accessibility.

Cheerio, Jeffrey

**Comment by JeffreyPerplex** [comment]
Hi @warrenbuckley,

I've decided to cut this pull request in smaller pull requests so it's easier for you guys to review them and merge them in. The first one is: https://github.com/umbraco/Umbraco-CMS/pull/2426.

After that one is merged I will try to fix the other changes that are part of this commit and address Mads concerns.

Ok?

Jeffrey

**Comment by pijemcolu** [comment]
@JeffreyPerplex The other PR is now successfully in. :)

**Comment by abjerner** [comment]
@JeffreyPerplex would it be okay to close this PR then?

> I've decided to cut this pull request in smaller pull requests so it's easier for you guys to review them and merge them in. The first one is: #2426.

**Comment by JeffreyPerplex** [comment]
Hi Anders,

that is okay for now. I don't see any chance to fix the last stuff although it's a pity :(... But I will get back to it at a later moment maybe,

cheerio, Jeffrey

**Comment by abjerner** [comment]
@JeffreyPerplex Ok. Closing the PR here then. Thanks for the effort 👍

**Pull request closed without merging**
