### PR TITLE
Adjust styling of variant switcher for not created variant

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

I think the variant switcher looked a bit off and the "Open in split view" button wasn't center aligned vertically.

**Before**

chrome_2020-07-29_13-48-07

**After**

image

Not sure about the "+" icon in front since it doesn't align the languages, but we can look at that in another PR.
When the language (not created) is selected I am not sure if this styling should also be applied. Otherwise it seems to be a few pixels off to align with other languages.

image

### CODE REVIEW

**Comment by bjarnef** [comment]
It noticed we have duplicate styling of `umb-variant-switcher`.

We have this specific less file `umb-variant-switcher.less`:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/less/components/editor/umb-variant-switcher.less

but still much here in `editor.less`.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/less/components/editor.less#L170-L323

I guess at some point the styling was moved to `umb-variant-switcher.less` but forgotten to remove the styling in `editor.less`, which makes in quite confusing, since some might make changes in one less file, while others make changes in another less file making in hard to track which changes are being made.

**Comment by bjarnef** [comment]
`umb-variant-switcher.less` is after `editor.less` so we can keep styling in `umb-variant-switcher.less` and start removing from `editor.less`:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/less/belle.less#L106
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/less/belle.less#L110

image

**Comment by bjarnef** [comment]
I have done some house cleaning in https://github.com/umbraco/Umbraco-CMS/pull/8511/commits/e544f0ea10f8ec1523dd375151d9628dcde68575 where the styling in duplicated in `umb-variant-switcher.less` or this would overwrite the styling.

Still a bit more to cleanup.

**Comment by bjarnef** [comment]
I have moved all relevant umb-variant-switcher styling to `umb-variant-switcher.less`.

Note we would we also want to move this for `.umb-editor-header__close-split-view?`
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/less/components/editor.less#L143-L159

but we can move this after merging https://github.com/umbraco/Umbraco-CMS/pull/8510

**Comment by bjarnef** [comment]
@nul800sebastiaan I have merged latest changes from `v8/contrib`  branch and resolved the conflicts 👍 

image

**Comment by nul800sebastiaan** [comment]
Ah this looks so much nicer now, great update @bjarnef - thanks!!

**Pull request merged**
