### PR TITLE
#6812 AuditService some methods not returning any values

### PR DESCRIPTION
**Pull request by enkelmedia**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

https://github.com/umbraco/Umbraco-CMS/issues/6812

### Description

Create a backoffice user (not the admin) and perform some Saves, Publish, Unpublish in the backoffice.

Then following code in for example a view should all return results.

```
var pagedByUser = Services.AuditService.GetPagedItemsByUser(1, 0, 100, out totalItems);

var byUserBydate = Services.AuditService.GetUserLogs(1,AuditType.Publish,DateTime.Now.AddDays(-15));

var logsByType = Services.AuditService.GetLogs(AuditType.Publish);

// Might need to change the hardcoded id here when testing
var pagedByEntity = Services.AuditService.GetPagedItemsByEntity(1104, 0,100, out totalItems);
```

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @enkelmedia 

Thanks for the work and the testing steps! Should give us plenty to work with. 

We'll let you know if we need anything more from you.

Emma

**Comment by enkelmedia** [comment]
@emmaburstow There might be some updates to this PR, have a look at https://github.com/umbraco/Umbraco-CMS/issues/6812

**Comment by nul800sebastiaan** [comment]
Hi there @enkelmedia,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing 🥇 

We have had another record breaking amount of PR's in both the CMS, Documentation, and other smaller public repositories. You can read all about the numbers in the [Umbraco Hacktoberfest round-up blog post](https://umbraco.com/blog/pr-team-update-november-2019-hacktoberfest-round-up/).

Due to the amazing work you and others in the community have been doing, we've had a bit of a hard time keeping up. 😅 While all of the PRs for Hacktoberfest might not have been merged yet, you still qualify for receiving some Umbraco swag, congratulations! 🎉 

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://docs.google.com/forms/d/e/1FAIpQLSc-K97Zl5k86cVebKWWqieLM4Fm_jCMGVdbQdYnq4IUJ7EvZg/viewform) :point_left: Please follow this link to fill out and submit the form, **before December 19th 2019**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before February, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Comment by poornimanayar** [comment]
Hi @enkelmedia ,

Do you want to make the checks for userid more consistent as mentioned in the comment [here]?(https://github.com/umbraco/Umbraco-CMS/issues/6812#issuecomment-545961246)

Regards,
Poornima

**Comment by poornimanayar** [comment]
And merged! Thanks once again :-)

**Comment by enkelmedia** [comment]
@nul800sebastiaan @poornimanayar Thanks! I know I've made other PRs but I never got the "Core"-badge on our.umbraco.com =D Can you fix that? =D

https://our.umbraco.com/forum/extending-umbraco-and-using-the-api/99097-console-app-with-access-to-the-published-content-cache

**Comment by nul800sebastiaan** [comment]
@enkelmedia Oops, shame on us! Added the Contributor badge now! 👍  https://our.umbraco.com/members/id:2535/

**Pull request merged**
