### PR TITLE
Changed delete button style on media type folder delete to danger style

### PR DESCRIPTION
**Pull request by poornimanayar**
Currently, the delete confirm on media type folder is the default green button, I have changed it to the `danger `style(red) button.

image

### CODE REVIEW

**Comment by kjac** [comment]
@poornimanayar I changed the base of this PR to `v8/contrib`, and now I'm seeing a bunch of additional changes. In other words: This one can't be merged in just yet - we'll have to wait until `v8/dev` is merged into `v8/contrib` again 😄

**Comment by poornimanayar** [comment]
can this be merged @kjac ?

**Comment by kjac** [comment]
@poornimanayar I thought it could by now, but GitHub still lists a bunch of changes. I had the same issue on other PRs... I had to perform another merge from `v8/contrib` to fix it, so - maybe you should try that (again) 😄

**Comment by kjac** [comment]
Thanks @poornimanayar - all good and merged now 👍

**Pull request merged**
