### PR TITLE
Fixes U4-11296 allowing nulls to be stored in the comment column of the umbracoConsent table

### PR DESCRIPTION
**Pull request by ProNotion**
At the moment the comment column does not allow nulls yet the default value for the optional comment parameter when calling `RegisterConsent` on the `ConsentService` is null resulting in an exception being thrown if no comment parameter is passed.

This PR allows nulls in the column. Also includes a simple Unit Test :)

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi,

Many thanks for your PR. We shall review your PR and let you know of the outcome within the next 14 days.

Regards
Poornima

**Comment by nul800sebastiaan** [comment]
Sorry for the delay @ProNotion - this looks fine in general but do you have any idea what happened to the csproj file? It seems to have grown double in size somehow! 😱

**Comment by poornimanayar** [comment]
Hi @ProNotion ,

Can you direct me on how I can test this?

Poornima

**Comment by dampee** [comment]
Looks like a bad merge or rebase before pushing. :-D

**Comment by nul800sebastiaan** [comment]
Haha well in fixing up the csproj file, I also managed to do a merge with `dev-v7`.. 😱

So it looks like loads of changes but not to worry, actual changes are pretty small!

**Comment by nul800sebastiaan** [comment]
Thanks @ProNotion - all merged! 👍  I moved the target version to 7.12 as we couldn't fit it into 7.11 on time any more.

**Pull request merged**
