### PR TITLE
Filter out disallowed content types from the delivery API content index

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

This PR ensures that we never add content to the delivery API content index, if it is of a type which is not allowed to output through the delivery API.

### Testing this PR

1. Create some published content of different types.
2. Rebuild the delivery API content index from Examine management.
3. Verify that all content has been added to the index.
4. Add one of the content types to `DisallowedContentTypeAliases` in appsettings.
5. Rebuild the delivery API content index from Examine management again.
6. Verify that no content of the disallowed type has been added to the index.

### CODE REVIEW

**Comment by elit0451** [comment]
Looks and tests out great! 🙌 Since we filter out all children of disallowed content types from the index, shall we also return "Not Found" when we use either the `id` or `path` of such items in the item-based endpoints?

**Comment by kjac** [comment]
Yeah actually we should. Both children of disallowed content types and also children of unpublished content (edge case, but still). I'll have a look at it right away and amend this PR, so we keep it all in one place.

**Review by elit0451 — CHANGES_REQUESTED** [review]
In the test scenario where I have the following Content tree structure:
- contentType1
  - contentType2
    - contentType3

And I list `contentType2` as disallowed, I **don't** get `contentType3` from the index but only from the item endpoints. We should fix this so that we can retrieve the item from any of the endpoints 🙂

**Comment by kjac** [comment]
@elit0451 strange! It works for me... given this structure:

image

...where "The Post" is a disallowed type, I still get "The Article" when querying all children of "The Post" and when querying all descendants of "Home One". "The Post" is not included in the descendants response.

Maybe you need to rebuild your index?

**Review by elit0451 — APPROVED** [review]

**Pull request merged**
