### PR TITLE
V8/merge/5061 v7 to v8 take two

### PR DESCRIPTION
**Pull request by warrenbuckley**
V7 to V8 merge I am not 100% confident this has gone smoothly.
@Shazwazza or @zpqrtbnk can you please sanity check this, as I have a gut feeling it's not right...

### CODE REVIEW

**Comment by Shazwazza** [comment]
Just at a glance i think some things have leaked through, for example, there are quite a lot of new files for things like `src/Umbraco.Web.UI.Client/src/views/common/overlays/contentpicker/contentpicker.html` which have been deleted in the v8 branch and we definitely don't want to bring these back to live in the v8 branch. 

@nul800sebastiaan did you say you'd be able to give this merge a go?

**Comment by nul800sebastiaan** [comment]
@Shazwazza Yep, working on it today!

**Comment by nul800sebastiaan** [comment]
Thanks @warrenbuckley - I've borrowed a lot of this, but working on more updates now to make it work. I'll close this one and send in my own PR as soon as I'm done.

**Comment by warrenbuckley** [comment]
Thanks @nul800sebastiaan for saving me - looks like I messed this one up a bit. Kudos to you & @Shazwazza who do these manual merges 💪

**Pull request closed without merging**
