### PR TITLE
Change link text for installing starter kit thumbnail & update styles

### PR DESCRIPTION
**Pull request by lynnewritescode**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

This PR fixes [https://github.com/umbraco/Umbraco-CMS/issues/6383](https://github.com/umbraco/Umbraco-CMS/issues/6383)

### CODE REVIEW

**Comment by zersiax** [comment]
I like the end result this should give, but it appears one of the tests is now failing. Should this fix be made in a different spot, or is this test too restricting?

**Comment by zersiax** [comment]
That's a tricky one.
Conceptually, we need to listen for some kind of indication that loading completed successfully, and trigger the altering of the link text when that happens. How that would work though ...I honestly don't know about AngularJS or the Umbraco core to give a definitive answer.Seems like a pretty cvommon AJAX use case though :-)

**Comment by lynnewritescode** [comment]
> 
> 
> @zersiax The tests are failing because of an unrelated commit from HQ, not to worry about that one! :-)
> 
> I think the original reason for this "loading.." text was misunderstood, we show it while we're getting the list of started kits from Our Umbraco.
> 
> To visualize (apologies Florian 🙂 ):
> 
> 
> 
> You can emulate a slow connection in your browser's dev tools, on the network tab there is usually a way to slow the connection down to "Slow 3G" or something.
> 
> Can you update this so that we still show the "Loading.." placeholder while the image is not yet loaded? I am personally not sure how to do this properly, I don't really know how to remove it when the link and the thumbnail from the remote server have loaded.

I may be wrong, but I thought that the text above that says "Loading..." serves that purpose? Or is that for something different? The line of code is:
`<small ng-if="!packages || packages.length == 0">Loading...</small>`

and it appears above the thumbnails unordered list. (see code screenshot below to visualize)

image

**Comment by nul800sebastiaan** [comment]
Aha, this is a good point @lynnewritescode! I'll have another look with this PR applied.

**Comment by nul800sebastiaan** [comment]
Sweet, I totally missed that there was TWO `loading` elements there. In which case, this is great. I tested it and it works just fine. 2 PRs merged in one day @lynnewritescode - well done! ⭐️

**Comment by lynnewritescode** [comment]
> 
> 
> Sweet, I totally missed that there was TWO `loading` elements there. In which case, this is great. I tested it and it works just fine. 2 PRs merged in one day @lynnewritescode - well done! ⭐️

Haha great! Thanks :) seems like the initial issue might have been more of a typo than anything. Thanks for reviewing it!

**Comment by nul800sebastiaan** [comment]
No worries, keep 'em coming!

**Pull request merged**
