### PR TITLE
v8: Nested content delete confirm

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
This PR updates Nested Content to use an overlay confirm to be consistent with other confirm overlays in v8 UI instead of the traditional javascript confirm.

image

Furthermore is update the editNode function to pass in the node object and also add track by on ng-repeat.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @bjarnef,

Well noticed! Love it when we can make things nice and consistent. We'll let you know if we need anything,

Emma

**Comment by nul800sebastiaan** [comment]
Hey @bjarnef, sorry for closing this one, we picked Kenn's PR over yours, see comments: https://github.com/umbraco/Umbraco-CMS/pull/5357

**Comment by bjarnef** [comment]
@nul800sebastiaan okay, this PR also shows a warning of which item is going to be deleted similar to when deleting a language 😉

**Comment by nul800sebastiaan** [comment]
Sure! I think we're going with the ethos of "keeping it simple" for now. 🙂

**Pull request closed without merging**
