### PR TITLE
V8: Added babel-plugin-angularjs-annotate to the tool chain for JS

### LINKED ISSUE #4901: V8: Ensure angularjs is easier to minify in the future by adding ng-annotations
From the reading I've done if we want to compress the JS for the back office anymore than we do with CD (which is something we "could" do as CD compression is pretty simplistic) then we need to make it safe to do so. 

Luckily there is a simple additional step we can add into the build process to do this for us called ng-annotate which will make our DI chain minify friendly. They describe the reasoning better than I could over at their readme: https://github.com/Kagami/gulp-ng-annotate

This isn't 100% needed as yet but with it in we can play around with compressing the back office JS even more and make it even more "Umblazing" fast :)

### PR DESCRIPTION
**Pull request by PeteDuncanson**
This fixes #4901 and future proofs the js tool chain setup so we can better minify the JS and support ES6 syntax better.

To test:

In windows explorer navigate to /src/Umbraco.Web.UI/umbraco/js/ and make a note of the umbraco.directives.js file size (assuming its there from a previous build, if not build the js first)

In the /src/Umbraco.Web.UI.Client folder run `npm install` to pull down the new package.

Then run `gulp js`. Then switch back to windows explore to see if the file size increases, we are expecting it to as this mod adds in an array at the front of all our DI references in our directives and controllers etc. Its this array that makes it safe for us to minify the files with more :)

Hit up the back office and double check everything is "working" as it should. As all the JS is loaded when you login if there was a JS error it should appear straight away in the dev console or the back office would simply not work/render. It should all just work as is.

Its possible that you might want to sit on this PR and not push it in until needed but I think its better to have it in now as its another bit of the puzzle for getting us to ES6 and smaller file sizes. Better to have it in I think.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hiya @PeteDuncanson 

Thanks for the PR. We'll take a look and let you know if we need anything. 

Em

**Comment by nathanwoulfe** [comment]
While this is a pretty old PR, it's absolutely worth updating and merging - the annotate plugin introduces really useful changes. I use it in Plumber, and as a result write less JS boilerplate, with more robust compiled output.

```js
angular.module("MyMod").controller("MyCtrl", ($scope, $timeout) => {});
```
becomes 
```js
angular.module("MyMod").controller("MyCtrl", ["$scope", "$timeout", ($scope, $timeout) => {}]);
```

The injected literals mean nothing will break when the $scope and $timeout parameter names are minified. This is good.

Combined with ES6 class syntax, the JS gets a whole lot cleaner. It encourages more generic code which will ultimately make a framework migration a bit easier. That's a whole other story.

Pinging @nielslyngsoe in case he has any issue with adding the dependency. If not, I'll fix the conflicts and merge.

**Comment by nathanwoulfe** [comment]
@nielslyngsoe / @madsrasmussen do either of you have opinions on this one? It's old, and the related issue has been bot-closed, but I think it's still useful given the additional robustness it adds to the build. Happy to close or merge.

**Comment by nathanwoulfe** [comment]
Hey @PeteDuncanson remember this one? Once the tests go green I'm merging it - even with a shift away from AngularJs on the horizon, it's still a really useful change and makes the backoffice more robust. Works as advertised, adding annotations to recognised AngularJs patterns, meaning minification/uglification can be applied without breaking dependencies 👍

**Comment by nathanwoulfe** [comment]
@nul800sebastiaan appreciate your advice on this - the CodeQL check failed, but it looks to be finding issues in files that aren't in the repo... Suggestions on how to fix that, or am I misinterpreting the results?

**Pull request closed without merging**
