### PR TITLE
Include the PluginController Area when searching for matching surface…

### PR DESCRIPTION
**Pull request by vwa-software**
### Prerequisites

Create an Controller derived from the SurfaceController, decoratie it with the PluginController attribute like this:
image

Then create a form with the BeginUmbracoForm method, make sure the area is filled.
image

This throws an exception with the message that the controller could not be found. This is true, becouse the area is not included in the route parameters searching for the controller.

(Also the typed version of the BeginUmbracoForm method is broken.)

This patch fixes this.

### CODE REVIEW

**Comment by nathanwoulfe** [comment]
@nul800sebastiaan would you treat this as a breaking change? PR modifies the interface, but does so with an optional parameter so won't break any implementations... Feels like it should be ok...

**Comment by KevinJump** [comment]
In framework (and I can't find anything to suggest this has changed in .net core but it might have). 
adding optional parameters makes breaking change for code already compiled against the existing interface. 

Optional parameters don't really exist at the compiled level and the code using them is essentially compiled down to something with the default value in the argument list. Existing code built against the old method, will not have the correct method signature internally. if it is rebuilt against the new interface it will 'just work' but only because the compiler will add the extra parameters. 
_(i've been stung by this one in the past https://github.com/umbraco/Umbraco-CMS/issues/5822)_ 

so from a compatibility point of view its better to keep the old method there, and call the new one. 

```cs
 public ControllerActionDescriptor Find<T>(HttpContext httpContext, string controller, string action)
    => ControllerActionDescriptor(httpContext, controller, action, null) ; 
    
 public ControllerActionDescriptor Find<T>(HttpContext httpContext, string controller, string action, string area = null)
```

but doing this does then break the interface as it has a new method it it. - You could use a default interface methods to fix that, but it might be a bit ugly/

**Comment by nul800sebastiaan** [comment]
Not just the interface also a public constructor. Optional parameters are a binary breaking change so any packages/custom code built against this `ControllerActionDescriptor` method will need to recompile.

What we usually do in this case is add a method that overloads the existing one, make the old one obsolete with a message telling people to use the method with the added parameter, and redirect the method call to the new method.

However.. that would mean adding the method to the interface too, which would again be a breaking change. And then we'd need to add a new interface `IControllerActionSearcher2` which inherits `IControllerActionSearcher` and has the additional method.

It gets a bit ugly but it will work and not break anything for anyone!

**Comment by nul800sebastiaan** [comment]
Haha, didn't see @KevinJump's comment while I was posting, but glad you agree! 😁

**Comment by nathanwoulfe** [comment]
Magical feedback, thanks both. 

I've seen the IMyInterface2 pattern elsewhere in the codebase, bit messy but easy to merge the two interfaces in a later version... 

Long story short though, sounds like a breaking change however we chop it...

**Comment by KevinJump** [comment]
Default interface methods isn't something i've used a lot, but in theory, it means you can keep one interface. 

adding the new method, but with a default calling the old one. 

```cs  
 ControllerActionDescriptor Find<T>(HttpContext httpContext, string controller, string action, string area)
     => Find<T>(httpContext, controller, action) ; 
```

would mean that that bit isn't breaking 🤷 - because the interface is still implimented by everything  and new methods can override this default 

so in the `ControllerActionSearcher` class, it would then be the other way around, the original method would call the new method. 

```cs
 public ControllerActionDescriptor Find<T>(HttpContext httpContext, string controller, string action)
    => ControllerActionDescriptor(httpContext, controller, action, null) ; 
    
 public ControllerActionDescriptor Find<T>(HttpContext httpContext, string controller, string action, string area) .... 
```

**Comment by KevinJump** [comment]
I think you can add [obsolete] because the new method will also be there. ? 

so `[Obsolete("use the method that accepts the area.... this one will be removed")]` ?

**Comment by vwa-software** [comment]
Don't feel sorry, i am so glad it is taken seriously, and i learn a lot as wel. Thank you.
I made a new commit with the sugested implementation, i hope it's correct, if not please tell.

**Comment by nul800sebastiaan** [comment]
One more tip for the future to make our lives easier, screenshots of code are not great, I had to figure out which code I needed to write to do a most minimal test for this, of course the screenshots helped, but a copy/paste of code would have been a lot quicker. So for reference, this is the code I used:

View:

```cshtml
@using(Html.BeginUmbracoForm(action: "AddBasket", controllerName:"Basket", area: "Amazilia"))
{
    <input type="submit" />
}
```

Controller:

```csharp
using Microsoft.AspNetCore.Mvc;
using Umbraco.Cms.Core.Cache;
using Umbraco.Cms.Core.Logging;
using Umbraco.Cms.Core.Routing;
using Umbraco.Cms.Core.Services;
using Umbraco.Cms.Core.Web;
using Umbraco.Cms.Infrastructure.Persistence;
using Umbraco.Cms.Web.Website.Controllers;

namespace Umbraco.Cms.Web.UI.Controllers
{
    [Area("Amazilia")]
    public class BasketController : SurfaceController
    {
        public BasketController(
            IUmbracoContextAccessor umbracoContextAccessor,
            IUmbracoDatabaseFactory databaseFactory,
            ServiceContext services,
            AppCaches appCaches,
            IProfilingLogger profilingLogger,
            IPublishedUrlProvider publishedUrlProvider)
            : base(umbracoContextAccessor, databaseFactory, services, appCaches, profilingLogger, publishedUrlProvider)
        {
        }

        public IActionResult AddBasket()
        {
            return CurrentUmbracoPage();
        }
    }
}
```

Do note: I used the `Area` attribute here instead of `PluginController` - both work but if you're not building a plugin then I think `Area` is recommended. I don't actually know what the benefits/differences between `Area` and `PluginController` are these days though. 

Anyway, as I said, both will work now and they definitely do throw the error that you saw before this PR. 

So all good now, merging! 👍 

Thanks again for the help and your patience, and congrats on your shiny new contributor badge on Our [gith ](https://our.umbraco.com/members/id:274727/) 🎉

**Pull request merged**
