### PR TITLE
U4-11849 - tree not aligned with editor

### PR DESCRIPTION
**Pull request by nathanwoulfe**
Changes here are related to http://issues.umbraco.org/issue/U4-11489, which is a cosmetic improvement to the tree alignment to set the root node height to the same as the editor header.

content tree

That's a one liner (setting the height using the editorHeaderHeight variable), but have also taken a bit of time to clean up the tree styles:

 - moved /tree.less to /components/tree/umb-tree.less and split into appropriate partials (tree-item, tree-root, actions)
 - consolidated tree styles from other files
 - removed unused styles (some remain in this commit, and are annotated as needing confirmation before removing)
 - moved from css-disguised-as-less to use sensible nesting to namespace components where appropriate

I haven't checked any of this cross-browser, and there's likely some states I haven't seen that may need further work, but wanted to get this in as baseline (I'd like to do more CSS stuff for v8, but want to make sure my approach isn't missing the mark).

### CODE REVIEW

**Comment by nathanwoulfe** [comment]
Will need to look at how to display when site has variants - adds language dropdown above the tree

**Comment by nathanwoulfe** [comment]
When content has variants, I've set the language picker height to match the sub-editor header (per the tree changes). Also then tweaked the height of the tree root node to align nicely into the editor content and made the negative space around the editor content consistent (20px on all sides).

**Comment by nathanwoulfe** [comment]
No worries @nul800sebastiaan, there's no rush

**Comment by madsrasmussen** [comment]
Hi Nathan, thanks for the PR.

Here is the first round of testing and feedback.

**The refactoring:**
* The splitting up into multiple files looks great. It makes it a bit easier to find the styles you want and it will make it easier to group related components and style files in the future. 👍 
* Code not in use: My search also told me the code is not in use so I think it will be ok to remove. 👍 
* You have a block of code which is commented out but doesn’t have any comments. Is this something you haven't deleted after it was moved to another file?
* It looks like each tree-item has gotten a bit more padding. I think they take up a bit too much space now.
* When opening a content picker the tree now has a bullet next to it. It looks like some "list-style: none" is missing somewhere.
* Personally I am not a big fan of nesting CSS. I think you quickly get caught up and nest really deep which will make really long selectors with a high specificity. It makes it hard to overwrite and in the worse case, we will end up with a lot of “!important” everywhere. To me, it is better to just add a new class for the specific element when nesting gets too deep. I know you didn’t write the initial code but I have tried to keep nesting out of the new files for this reason.
* I know you didn’t write this either but selector like these: ".umb-tree div” just keeps giving me problems 😄

**I have tested the following states:**
* ✅Unpublished
* ✅Delete
* ✅List view has an icon
* ✅When opening a content picker the “more options” are not showing
* ✅not allowed (used when inserting partial views)

Feel free to test more states. I am pretty sure I didn’t get all of them.

**The tree root height:**
The tree root height/language selector is something I have struggled a bit to find the right solution for. I like the idea of aligning them with the content header but I think they get a bit chunky when we do that. It works okay with the tree root but I think the language selector gets too much attention when it is that high.

**Some things we can try out:**
* We might be able to squeeze the header height a bit more. The challenge is the doctype editor which has an icon, name, and description in there. I did a quick test with a 70px header and changed the name input field to 30px. I think that might work.
* Redesign the language selector to look more like a subtle button you can click than a header.

When all of this is set then H5 for picking some of the craziest CSS in the code base to refactor 🙂

**Comment by nathanwoulfe** [comment]
@madsrasmussen that's awesome feedback, thank you. I'll get back in and refine/tidy up when I can.

I'm happy to follow whatever style guide suits you - if the preference is to add classes, that's what I'll do. I like to use sass to namespace components, just to ensure things are nicely encapsulated, and ideally would only ever be nested in the scss file, which would compile out to flat, single-selector styles:

    .umb-tree {
        &--link {}
        &--list {}
        &--item{
            &:hover {}
        }
    }

Agree on the tree root for the language selector, it's fat. Will keep fiddling and see what comes out...

**Comment by nathanwoulfe** [comment]
@nul800sebastiaan I disappeared to Fiji for a week... Will get back into this one today 👍

**Comment by nathanwoulfe** [comment]
Latest commits tidy up CSS nesting where appropriate - flattens everything out as much as possible. To do that, I've added a few new classes in a couple of views (added benefit there of no longer having to use element selectors).

Pretty sure this will have taken care of @madsrasmussen's notes. Have also reverted the height changes on the language selector, will give that more thought.

Finally, the merge conflict... attempting to rebase my local temp8 branch tells me I'm up to date, which I know I'm not. Suggestions there would be awesome...

**Comment by nathanwoulfe** [comment]
No more merge conflict - pretty sure I went the long way around to fix that, but hey, all green now.

**Comment by madsrasmussen** [comment]
Hi Nathan, thanks for all the fixes. I am 100% sure they are better than the current code.

If anybody from the PR team has time to do an extra test feel free or else I will do the last test as soon as possible. Don't worry about the alignment of the language selector (even though it was the raised issue). I think we should get this PR merged in and then I will see what I can do about the language selector. I am doing some UI clean up anyway.

**Comment by nul800sebastiaan** [comment]
Sorry for the delay @nathanwoulfe ! I've given this a spin and it all looks very lovely and aligned (for now! 😉).

I've resolved the merge conflicts for you and I think everything looks fine and nicely restructured now! Top job!

**Comment by nathanwoulfe** [comment]
Thanks @nul800sebastiaan, hopefully makes it a bit easier to maintain in future.

That language selector tho...

**Pull request merged**
