### PR TITLE
The ImageCropperPropertyValueEditor doesn't convert values in ConvertDbToString correctly

### PR DESCRIPTION
**Pull request by Shazwazza**
It is trying to serialize as json but it is failing since it's just concatenating objects and the ToString() of the crops is not the actual json of the crops.  Have fixed this to properly serialize.

### CODE REVIEW

**Comment by cleversolutions** [comment]
Hey @Shazwazza would this by why media.GetCropUrl("alias") returns null?

**Comment by Shazwazza** [comment]
@cleversolutions i don't know - i'm not sure what version you are using? is it latest 8.1 from code or 8.0.x ?

**Comment by cleversolutions** [comment]
8.0.2. Without getting too deep into the code it seemed like maybe the Codes property was null which causes getcropurl to return a null. Since codes came from property values it seemed likely at first blush this might fix that.

**Comment by warrenbuckley** [comment]
@Shazwazza do you have repro steps for me to test before/after the PR is applied, please.

## Repro Steps Used
As I have tested before the PR is applied and done the following steps without any issues:

- V8 with SK installed
- Update `Image` Media Type -> Update `umbracoFile` Image Cropper DataType settings to include two crop types
- Goto Media Section & Choose a Product Image
- Set manual crops for the image
- Update Product.cshtml / template with ``
- View page on frontend & confirm image renders out all OK

**Comment by cleversolutions** [comment]
@warrenbuckley I followed your repro steps with 8.0.2. It works in 8.0.2 only for images you have saved after adding the new crop alias. One would not expect to have to re-save all their images after adding a new crop alias. I haven't tested this PR to see if it changes that behavior.

**Comment by cleversolutions** [comment]
I just tested this PR, it doesn't seem to have changed the behavior. Crops is still null unless you save the image after creating the crop alias.

**Comment by warrenbuckley** [comment]
@Shazwazza I am not sure this change affects anything as far as I know, as the usage seems to refer to legacy XML cache.

When you get time do you mind if you can see if you agree with me on this or are able to give me some repro steps for this?

I agree the serialization is better and be OK to merge this, but I can never seem to hit a breakpoint at the moment for where this code was changed, to see the fix before & after.

Let me know what you want me to do with this please mate :)

**Comment by cleversolutions** [comment]
Sorry I threw a red herring in there with my comments about GetCropUrl. I’ll create a new issue for it.

**Comment by warrenbuckley** [comment]
Merged :)

**Comment by cleversolutions** [comment]
I added issue #5737

**Pull request merged**
