### PR TITLE
V8: Don't use floats in the slider config as it only supports integers

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

#4778 calls for decimal step increments, but noUiSlider only supports whole numbers throughout its configuration. To avoid future confusion on this I have changed the slider controller configuration so it explicitly parses integers instead of floats (which wouldn't work anyway).

**Note:** `SliderConfiguration` already uses integers for every configuration option, so this PR has no practical effect - just adds a little consistency to the code.

### CODE REVIEW

**Comment by bjarnef** [comment]
@kjac I don't think the issue is that noUiSlider doesn't support decimals, but the  properties in the configuration is defined as int values https://github.com/umbraco/Umbraco-CMS/blob/91c52cffc8b7c70dc956f6c6610460be2d1adc51/src/Umbraco.Core/PropertyEditors/SliderConfiguration.cs

**Comment by kjac** [comment]
@bjarnef I am pretty sure. I tried hard coding decimal point config values in the property editor JS and it didn't work. And since the docs never show any decimal point config values I guess it makes sense.

**Comment by bjarnef** [comment]
@kjac in another PR I am working on it is using float values, so I am prety sure it is not because noUiSlider doesn't support decimal values, but how the slider property editor handle the values, where is round the values using `Math.round` function.

**Comment by kjac** [comment]
Digging more into this @bjarnef is correct here. I'll update the PR.

**Comment by kjac** [comment]
OK. This is a bit of a pickle.

The slider only supports *one* formatting routine to handle both the value tooltip and the min and max labels.

Now... we should't show the any numbers with decimal places if they are configured as whole numbers - e.g.

- don't show the tooltip as 5.00 if step increments are set to a whole number
- don't show max as 100.00 if max max is set to 100

...but given the formatting routine limitation mentioned above, we're left in a bad spot if we allow configuring both step increments and min/max as decimals (as #4778 calls for).

The way I see it we have two options:

1. Always format all labels with the maximum number of decimal points across min, max and step.
2. Only allow decimal points in step and format the tooltip accordingly - e.g. no decimal points if step is a whole number, and 2 decimal points if step is 0.01.

I'm inclined to go with option 2, but this doesn't solve #4778 (which, in all fairness, could be solved in a number of other ways).

Thoughts?

/cc @nul800sebastiaan

**Comment by kjac** [comment]
Disregard the last comment. I found a workaround. 

Now the slider works like this:

slider-decimals

**Comment by kjac** [comment]
Oh, and I have verified that upgrading existing sliders from the old integer based config to the new decimal based one works just fine. Which makes sense as you can assign integer values to decimal properties in C#.

**Comment by nul800sebastiaan** [comment]
Yay!! Lovely! 🎖 

image

**Pull request merged**
