### PR TITLE
Update tinymce version to 4.9.4 in v7

### PR DESCRIPTION
**Pull request by ssougnez**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/4702

### Description

Update the version of tinymce to ensure that non breaking spaces are only added where they need to be.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @ssougnez 

Thanks for the pull request. We'll take a look over it and let you know if we need anything!

Emma

**Comment by drbldgtl** [comment]
It looks like this is the only issue required for the release of 7.15 - is there a date for this?

**Comment by ssougnez** [comment]
I think that on my side, everything is done.

**Comment by nul800sebastiaan** [comment]
Thanks very much @ssougnez ! 
Sorry for the delay, in the mean time v4.9.4 came out so I updated it to that 👍

**Pull request merged**
