### PR TITLE
Add red class to remove button in dynamic query steps

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
Added the `umb-node-preview__action--red` to remove button, to make it consistent with other remove buttons in `<umb-node-preview>`.
We could probably just use the component here instead, but for now I have added the class.

### CODE REVIEW

**Comment by busrasengul** [comment]
Thank you @bjarnef 
Someone from the Core collabs team will look into this! Mind that it's holiday times so might take some time :)
Merry Chrismas 🎉

**Comment by emmagarland** [comment]
Hi @bjarnef 

Just to clarify, if this PR is superceded by #15510, should this one still be open for review?

Thanks

Emma

**Comment by bjarnef** [comment]
Hi @emmagarland 

Not if https://github.com/umbraco/Umbraco-CMS/pull/15510 is accepted, but I have left this open for now.
It can also be merged until https://github.com/umbraco/Umbraco-CMS/pull/15510 has been reviewed, but I think it makes more sense to review the refactored changes in https://github.com/umbraco/Umbraco-CMS/pull/15510

**Comment by nul800sebastiaan** [comment]
Superseded by https://github.com/umbraco/Umbraco-CMS/pull/15510

**Pull request closed without merging**
