### PR TITLE
[v8] U4-11555 - Remove App_Browsers folder

### PR DESCRIPTION
**Pull request by leekelleher**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org/issue/U4-11555

### Description

Detailed outline of the proposed changes are on the issue tracker: <http://issues.umbraco.org/issue/U4-11555>

It is still unknown (to me) if WebForms will be used for any part of the v8 back-office. From my limited testing, the current WebForms powered components, (e.g. Macro editing, Relation Types, Content Rollback, Audit Trail, et al) are marked as to be rewritten in AngularJs.

### CODE REVIEW

**Comment by leekelleher** [comment]
@Shazwazza Gotta say, I'm not 100% sure if the "Form.browser" config is needed for frontend WebForms either.

My assumption was that without it, a `<form runat="server">` would have a value of `action="/default.aspx"`, since all pages were routed through that, _for WebForms, that is_ ... and the Control Adapter (for `HtmlForm`) would rewrite the `action` value with the current page URL, (for postback reasons).

I'm not sure if the newer URL routing (in Umbraco) changes this at all?  It'll probably need a test scenario, _(I'm even struggling to remember how to do frontend WebForms in Umbraco these days)_.

**Comment by Shazwazza** [comment]
Umbraco's routing won't have any impact on this at all. I think we'll just need to test it to see what happens, i 'think' this would be how you could test this?

* Change the rendering engine to Webforms in the umbracoSettings.config
* Create a new template (which will now be webforms)
* assign the template to a doc type
* Add anything that has ViewState to the master page, like <asp:TextBox, and I think you need to wrap all of that in a <form runat="server", but maybe the template comes with that already and add webforms button
* Then type anything into the text box and hit the button and see if the viewstate works and that the URL remains the same

**Comment by leekelleher** [comment]
@Shazwazza Finally got around to testing this out... I had to jump through several hoops to get WebForms to work in v8, (not sure how much you want to know about that? as I don't want to distract from this specific ticket).

In a nutshell, the Form.browser is being used to rewrite the `<form runat=server action=...` value to be the current URL, as in the "nice URL".

e.g. `<form method="post" action="/my/nice/url/" id="ctl00">`

However if we remove all the code associated with Form.browser, (as in this PR), then the `action` value is set to `"./"`, (not `"/default.aspx"` as I assumed). Which is the current page/URL.

e.g. `<form method="post" action="./" id="ctl00">`

> **Note:** This also works with querystrings, as in any params in the URL will be appended to the `action` value.

Soooooo... I'm not sure what you want to do here? As the rendered markup is different, but the functionality is essentially the same.

---

If you want to keep the legacy code in place for v8, then I can modify this PR to only remove the "w3cvalidator.browser" file, (which we agree is no longer needed).

**Comment by Shazwazza** [comment]
@leekelleher If there's some stuff we need to change/fix in core for v8 to make webforms work again maybe open another ticket or PR? If we aren't removing it entirely it should probably still work if it's not a giant PITA

So without the Form.browser does postback still work sounds like it might not if the URL is different? or maybe that doesn't actually affect how it all works underneath?

**Comment by leekelleher** [comment]
> So without the Form.browser does postback still work sounds like it might not if the URL is different? or maybe that doesn't actually affect how it all works underneath?

To clarify, postback **does work**, (without "Form.browser" and related code), it'll submit back to the current URL.  I think it's fine to merge this PR in, but that's a decision for you & team. 😃❤️

**Comment by nul800sebastiaan** [comment]
I love it! Thanks very much @leekelleher ! #h5yr!

**Pull request merged**
