### PR TITLE
U4-10756 - id/guid cache

### PR DESCRIPTION
**Pull request by zpqrtbnk**
see http://issues.umbraco.org/issue/U4-10756

### CODE REVIEW

**Comment by allyen** [comment]
Recently I've come across a very slow site on one of our webs and tracked the issue down to this PR :). The problem is deleted content... When a deleted content is referenced from many property editors (in this case MNTP) used on a site, each and every `GetPropertyValue<IEnumerable<IPublishedContent>>` hits the DB to find out there is no content with the given GUID because fails are not cached.

I've tried a quick fix by introducing a cache of not found keys which helped. The question is -- is this the right approach and should I put up a PR for this? I think it should be ok because a deleted key (or id) cannot come back into existence but I may be missing something.

**Comment by Shazwazza** [comment]
@zpqrtbnk what do you think? Perhaps a PR might be ok. I would hope this is more of an edge case though and this problem doesn't exist in v8.

**Comment by zpqrtbnk** [comment]
The same thing will happen in v8 - the `IdkMap` currently works as a *cache*. If first looks the key up in its own cache, then looks into the content cache (NuCache), then falls back to a database lookup and, if the returned value is null, does *not* cache that null value.

Meaning that tons of references to an non-existing (deleted) key in pickers result in tons of queries.

But... the content cache (NuCache) supports being queried by key, and all property value converters *should* do this, and not rely on `IdkMap`, meaning that the content cache would understand that the key maps to a missing element, *without any DB query*.

So I would say that v8 is safe.

But it's a problem in v7 - and not an edge case. The problem is going to become more and more a problem, as time passes, sites grow, and accumulate references to deleted documents.

Now - caching failed lookups means that (a) one could potentially DOS the site by looking up every possible key, but that's probably a minor risk and (b) we need to make sure that things that import content (thinking about Deploy here but what about uSync or others?) do flush the `IdkMap` when they are done.

They probably do. So yea... interested in a PR. Would probably like it to be configureable in a way.

**Comment by allyen** [comment]
@zpqrtbnk, thanks for your very detailed reaction! Concerning the two possible problems:
(a) To perform these lookups, you would need to have programmatic access to the site, wouldn't you? How could you possibly perform an arbitrary IdkMap query from just the frontend? I may be missing something...
(b) When importing content:
  - ids should be safe as they are generated in a sequence and a deleted id shouldn't be reused,
  - with keys, GUID collision is virtually impossible as well.
So the deleted entities cache could probably stay intact after import as the newly imported items cannot collide with it. So the only reason for clearing the `IdkMap` would be performance (quering the imported content shouldn't hit DB)?

**Comment by allyen** [comment]
Thinking on it, I see the (b) case is valid – you would have to import something, delete it and then import it again... So it really is necessary to clear the cache after import.

**Pull request merged**
