### PR TITLE
Nested Content PropertyValueConverter is missing DefaultPropertyValueConverter attribute

### PR DESCRIPTION
**Pull request by ronaldbarendse**
Creating a custom `PropertyValueConverter` for the built-in `Umbraco.NestedContent` editor is not possible, because the built-in PVCs is not marked with a `DefaultPropertyValueConverter` attribute.

This functionality (and the attribute) were added in issue [U4-3591](http://issues.umbraco.org/issue/U4-3591), but because NC was added later and originated from a community package, marking it as a default PVC was probably overlooked.

I've also converted the `IPropertyValueConverterMeta` interface to attributes, since the values are static. Implementing the interface would be the way to go if the PVCs (`NestedContentSingleValueConverter` and `NestedContentManyValueConverter`) were merged into a single class, but changing that would be a breaking change.

Connected to #2925

### CODE REVIEW

**Comment by ronaldbarendse** [comment]
I've created a branch on my fork that merges the PVCs: https://github.com/ronaldbarendse/Umbraco-CMS/tree/nested-content-mergedpropertyvalueconverters. This is probably a breaking change, but maybe it can be merged for V8?

**Comment by nul800sebastiaan** [comment]
Connected to #2925

**Comment by poornimanayar** [comment]
Hi @ronaldbarendse ,

Many thanks for the PR. We shall try and review the PR within the next 14 days and get back to you.

Regards,
Poornima, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by ronaldbarendse** [comment]
I've updated the linked issue (#2925) and think we should continue the discussion there!

**Comment by poornimanayar** [comment]
Hi @ronaldbarendse ,

I think it will be good if @nul800sebastiaan can provide some input as well. Tagging him here.

Poornima

**Comment by poornimanayar** [comment]
Hey @ronaldbarendse ,

Would you be able to give me some sample code to test with and may be tell me how to test it? Also can you check whether the output of the old PVC and the new one are exactly the same?

Poornima

**Comment by ronaldbarendse** [comment]
Hi @poornimanayar! I've tested it on a clean install using the starter kit (Nested Content is used for the product features). Also, check my comment on the linked issue https://github.com/umbraco/Umbraco-CMS/issues/2925#issuecomment-420800775...

**Comment by nul800sebastiaan** [comment]
Hey there @ronaldbarendse !

I'm writing today after announcing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Pull request closed without merging**
