### PR TITLE
V8: Fix unchangeable language/variant after closing split view 

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/3991

### Description

As described in #3991, the split view can easily get you into a state where you can't change the active language/variant.

#### Steps to reproduce

1. Open a page that has two or more language variants. By default it'll open the current main language variant.
2. Open another language variant in split view.
3. Close the left part of the split view (the one that contains the first language variant).
4. Notice that you can't change back to the first language variant using the language selector (but you can probably open it using split view).

With this PR applied, the same operation looks like this:

fix-unselectable-language-after-closing-split-view

### CODE REVIEW

**Comment by emmaburstow** [comment]
Morning @kjac,

Thanks for spending your monday evening on us! Speak soon,

Em

**Comment by kjac** [comment]
@emmaburstow I'd expect nothing less of you guys 😁 and nice catch! However, "cculture" is actually correct in this case. It's the "currently culture", where "mculture" is the "main culture".

That being said I could update the comment to "current culture" instead of "cculture" if you like?

**Comment by emmaburstow** [comment]
Oh Kenn - I really should know better than to question your logic 😆 - go on then. You may as well humour me and change it to current culture. Thanks!

**Comment by kjac** [comment]
@emmaburstow as you wish, my liege 😛 all done.

**Comment by nul800sebastiaan** [comment]
Nice one Kenn!

**Pull request merged**
