### PR TITLE
Fix typo in Happy message for Saturday

### PR DESCRIPTION
**Pull request by Aaen**
### Description
When you log in to the backoffice on a Saturday it says Happy Caturday

I have fixed this typo so it says Happy Saturday for the EN-US language and EN language

### CODE REVIEW

**Comment by ronaldbarendse** [comment]
This is not a typo: https://www.urbandictionary.com/define.php?term=Caturday :rofl:

**Comment by ronaldbarendse** [comment]
But I think the 'funny' welcome texts might not be for everyone/each project, so maybe we should make them removable?

**Comment by abjerner** [comment]
I always imagined that *Caturday* was there on purpose. I could see arguments for both keeping it and removing it.

255d8cd84ada1238

**Comment by abjerner** [comment]
@Aaen perhaps try and ask around at the HQ? Although Per is not around at HQ anymore, perhaps someone still has an opinion about it?

Commits related to *Caturday*:
https://github.com/umbraco/Umbraco-CMS/commit/e59768dda07e0ac6b9301e3be3bc48c2157a7026
https://github.com/umbraco/Umbraco-CMS/commit/1152b61fb0876d0fb59b8dd0c0d2b528c4af53b5

**Comment by nul800sebastiaan** [comment]
It's on purpose :-)

http://knowyourmeme.com/memes/caturday

They can be changed of course. You can create user translation files in the config directory and drop them in your projects by default when you create a new one.

**Pull request closed without merging**
