### PR TITLE
Block list action z index

### PR DESCRIPTION
**Pull request by callumbwhyte**
The actions (appearing to the right hand side of block list editors on hover) clash with other UI elements, such as the publish actions menu.

Screenshot 2020-12-09 at 22 23 01

There is an insanely high `z-index` value set here to ensure they always stay on top of all custom + Umbraco styles loaded.

I have reduced the `z-index` to a more sensible level, inline with the similar `umb-confirm-action` component to avoid the clashes. Now it looks like this:

Screenshot 2020-12-09 at 22 29 08

_(I also cleaned up some of the CSS here, maybe want to review with whitespace ignored)_

### CODE REVIEW

**Comment by glombek** [comment]
Hi Callum,

Thanks for this PR!

However, this doesn't appear to be working for me.

`.umb-editor-footer` has `z-index: 30` so your `z-index: 999999` on `.umb-block-list__block-actions` still paces the buttons over the top of the publish menu.

Am I missing something?

Setting the `umb-block-list__block-actions` `z-index` to 30 or less puts it below the publish menu, but I'm not sure what else the buttons are trying to be above (custom block list views, perhaps?)

It may make sense to force `.umb-split-views` to be below `.umb-editor-footer` (<= 30) so that nothing within `.umb-split-views` can possibly escape that frame... but this may have other impacts!

Be good to hear your thoughts here.

Joe

**Comment by glombek** [comment]
In fact, setting `.umb-block-list__block-content>div` to have a `z-index: 0`, and then `.umb-block-list__block-actions { z-index: 1; }` would be less obtrusive! I'm not quite sure how the custom view stuff would work here though - maybe another container would need to be set to `z-index:0` also.

**Review by nul800sebastiaan — CHANGES_REQUESTED** [review]
@callumbwhyte could you try to make the changes as @glombek suggests?

**Comment by nathanwoulfe** [comment]
Looking at this on v8/contrib, I think it can be fixed by removing the z-index from umb-block-list__actions. With no z-index, the controls still sit on top of any custom view, and always behind the footer menu. 

The umb-block-list__block element is statically positioned, then has the umb-block-list-block and actions elements as children:
image

Given the actions element is absolutely positioned, it will create a new stacking context and always be atop the preceding element (unless the block has silly custom CSS to set its own z-index, which would already cause problems with overlapping the footer menu etc).

I think the easiest way forward is to kill the z-index on the block actions, and flag it as a potentially breaking change for custom block list views where the list view has a z-index (which it shouldn't need anyway)

**Pull request closed without merging**
