### PR TITLE
Remove top and bottom border for resizable handle

### PR DESCRIPTION
**Pull request by bjarnef**

### CODE REVIEW

**Comment by clausjensen** [comment]
Hi @bjarnef,

It makes it a lot easier to merge in your PR (and your PR will actually show here as merged) if you rebase your commits in the PR on the dev-v7 branch instead of merging the remote dev-v7 branch into your branch - this is what causes the 6 merge commits before your actual code changes above.

When I do the rebasing on my end, your actual commit will show up just fine in the git history (https://github.com/umbraco/Umbraco-CMS/commit/d9de5e5f2923fa73004e9b8ae889597e864033d2), but we will have to manually close this PR and it doesn't show up as 'accepted'.

Feel free to ask away if you need any assistance on how to do it - and thanks for your PR :smiley:

**Comment by bjarnef** [comment]
Hi @clausjensen

Thanks for your feedback :) ..  Yeah, I have noticed the "remote tracking" and think it was at some point I was testing some different git command - but didn't know how to get back to starting point :smile:

Sometimes I use command window, but often I just use the Windows Desktop client https://desktop.github.com/

But sometimes previously it sometimes fails to pull latest changes or push commits.. however a recent versions it has been much better and it has a button to pull in latest changes (not sure if it does a rebase behind the scene?).

I will pay more attention to it in the upcoming PR's :+1:  :sunglasses:

**Comment by clausjensen** [comment]
@bjarnef git can be very confusing - no worries :smile: 
Getting back to starting point can be even more confusing ... what I usually do whenever something goes really wrong is to stash the changes I've made and then just start over by doing a hard reset on the branches and reapplying the stash.

I'm not sure about what happens behind the scenes in the github desktop client, but I know that depending on what you choose in the gitextensions client it can actually do either a merge or a rebase on pull .. maybe the same happens in your client.

It's pretty awesome to have a lot of smaller PR's (instead of a big one) for the smaller kind of changes you usually do, since we can easily test them one by one, and merge them in one by one, which works really well with our workflow here. If the PR's are actually rebased correctly, merging is as easy as clicking one button, after reviewing the changes. 

So in the long run we can merge stuff a lot quicker == we can get a lot more fixes in .. that is actually the only reason why we care about the rebasing :smiley:

Thanks again for your help!

**Comment by bjarnef** [comment]
@clausjensen it is section 2 here https://help.github.com/desktop/guides/contributing/syncing-your-branch/ and it seems it does something like this behind the scenes https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/

But sometimes the desktop client have some limitations and just fails to merge changes because of conflict. At my workplace we use http://tortoisehg.bitbucket.org/ with git or mercurial in projects and in case of merge conflicts you have options in the desktop client to try if it can figure out the merge, take local or other version .. or open tool resolve, e.g. in Beyond Compare and merge the files manually :smiley:

But I think the github desktop client is more simple to use for beginners and works well at least for submitting smaller PR's.

Yes, I also like submitting those smaller PR's as it is quick and easy .. and often you can always fix a part of some related issues or a bigger issue. :relaxed:

**Pull request closed without merging**
