### PR TITLE
Upgradable Mvc5/WebApi2

### PR DESCRIPTION
**Pull request by Shazwazza**
This PR includes all of the code changes required to Umbraco core to make it compatible with both MVC4/5 and WebApi1/2.

I've tested an existing Umbraco 7.2.1 install and then upgraded to this version (which I've marked as 7.3) and then upgrade via Nuget to MVC5 and WebApi2 which works great. You need to follow the standard Microsoft upgrade path: http://www.asp.net/mvc/overview/releases/how-to-upgrade-an-aspnet-mvc-4-and-web-api-project-to-aspnet-mvc-5-and-web-api-2

This PR also loosens up the MVC/WebApi dependencies so Umbraco will allow MVC/WebApi versions that are less than 6 - this makes the Nuget upgrade possible.

I've also removed Umbraco's references to Microsoft.Web.Helpers library since we don't use it at all and it has compatibility problems. If you upgrade you'll need to remove this reference (which is also described in MS's upgrade docs)

The way that this is supporting MVC4/5 and WebApi1/2 is via reflection, namely in 2 places:

* ReflectedFixedRazorViewEngine - which detects the MVC version, if it's >= 5 then the wrapped engine will just be the standard RazorViewEngine, otherwise it uses reflection to create an instance of the deprecated FixedRazorViewEngine. The reflection is only used at startup so performance won't be much affected.
* ApplicationTreeExtensions is updated to check the WebApi version since some properties exist in the new version that don't in the old version so these need to be set via reflection. The reflected PropertyInfo's are cached so performance won't be much affected.

### CODE REVIEW

**Comment by sitereactor** [comment]
:+1:

**Comment by AndyButland** [comment]
Looks a great solution.  Spotted a small typo in a file name: src/Umbraco.Web/WebApi/MvcVersionCheck.cs (should be WebApiVersionCheck.cs)

**Comment by nul800sebastiaan** [comment]
Great! I'll review this soon.

**Comment by sitereactor** [comment]
Hey @Shazwazza I tried this by building your branch and installing the nuget packages in an empty VS solution. Everything seems to run fine, but I have a question about the /Views/web.config - after the upgrade of MVC (-> v5) and WebApi (->v2.2) should I update this config manually? I see the following two entries, which doesn't seem to be handled automatically through nuget:

`<host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />` under `<system.web.webPages.razor>`

and 

```
<pages validateRequest="false" pageParserFilterType="System.Web.Mvc.ViewTypeParserFilter, System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" pageBaseType="System.Web.Mvc.ViewPage, System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" userControlBaseType="System.Web.Mvc.ViewUserControl, System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35">
  <controls>
    <add assembly="System.Web.Mvc, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" namespace="System.Web.Mvc" tagPrefix="mvc" />
  </controls>
</pages>
```

**Comment by nul800sebastiaan** [comment]
That'd be a problem though, if people had installed it in a MVC4 project they shouldn't have MVC5 references in the web.config. Is there a way to separate that like done for the .NET framework? I don't think there's an "MVC framework" option in NuGet.
Wonder if there's some way we can detect the MVC version in Powershell and drop in the correct config file.

**Comment by Shazwazza** [comment]
Mvc nuget upgrades do not handle any Web confirm transforms other than the
man one. Like I mentioned in the upgrade notes, if you're want to upgrade
to MVC 5 you need to follow ALL of the normal MS upgrade notes, which
include all views Web configs, even including one that exist in app plugins
or elsewhere

**Comment by nul800sebastiaan** [comment]
This was a fresh install though. I think if you do a MVC4 to 5 upgrade in an existing site it will work pretty well.

**Comment by Shazwazza** [comment]
Maybe I'm missing the point here? A fresh install of umbraco via nuget will
have a mvc 4 views Web config - so long as the initial project created was
mvc 4. Then you upgrade to MVC 5, you need to follow ms guidelines for
upgrading, which includes manually upgrading all your views Web configs

**Comment by nul800sebastiaan** [comment]
Yes. but by loosening up the requirements we can now expect people to START with a blank MVC5 project and run into this problem which will be reported a few dozen times. :)

I think doing a NuGet upgrade from MVC4 to MVC5 will probably do all the config transforms automatically already.

**Comment by Shazwazza** [comment]
Starting with mvc 5 i haven't tested and dont know what it will do. But of
course our files wont be correct in that  case.

Mvc 5 upgrades will not affect Web configs in views folders,tried a few
times, plus there might be more than just the standard one in the views
folder like in app plugins

**Comment by sitereactor** [comment]
I've bumped into a rather strange issue by simply installing the [CollectionJson](http://www.nuget.org/packages/CollectionJson/) nuget package - [source available here](https://github.com/WebApiContrib/CollectionJson.Net) - I get a YSOD on heading the first page of the Fanoe starterkit:

```
Umbraco.Web.Models.DynamicPublishedContentList does not contain a definition for 'Any'
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Umbraco.Web.Models.DynamicPublishedContentList does not contain a definition for 'Any'
```

`Line 4:  @if (home.Children.Any())` in `Views\Partials\MainNavigation.cshtml`

I'm guessing there is something in that package that conflicts with Umbraco.

Steps to reproduce:
* Install the nugets from this PR in an empty Visual Studio solution.
* Install the Fanoe starterkit
* Update the nuget packages for MVC and WebApi to v5
* Correct versions in Views/web.config
* Check site still works
* Install this nuget: `Install-Package CollectionJson`
* Check site again and see YSOD

**Comment by nul800sebastiaan** [comment]
We've seen this issue before (mvc4) after installing Warren's analytics package for example. It's something to do with extension methods being weird.

**Comment by sitereactor** [comment]
Its also using a package called DynamicUtils (also on nuget), so maybe that might be the problem. Think it has a couple extension methods.

**Comment by sitereactor** [comment]
I tried this again removing the two mentioned nuget packages, and adding the code as part of my solution instead and this works perfectly fine. So yeah looks like there is something funky going on with the extension methods, which is unrelated to this PR.

**Comment by Shazwazza** [comment]
Awesome! The extension method thing is caused by multiple extension methods
targeting a generic IEnumerable. It can also be solved by adjusting the
imports or using the method directly as a static method.

I had a thought about the views Web configs... We could create a separate
package if we wanted to auto update these, called something like 'mvc5 view
config upgrader' wouldn't be difficult but not sure if it's really worth
it?

**Pull request merged**
