### PR TITLE
Review: Bug fix#17149 User Validation on Audit Repository .Save Method

### PR DESCRIPTION
**Pull request by IbrahimMNada**
### Description

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/17149

this pull request is a fix for this issue : https://github.com/umbraco/Umbraco-CMS/issues/17149

Which states that a content publish can be established using `ContentService` with a non existing user.

A Simple Database Validation/ and simple caching mechanism were added in order to check if the user really exists in the database  

---
_This item has been added to our backlog AB#46955_

### CODE REVIEW

**Comment by JasonElkin** [comment]
Hey @IbrahimMNada, thanks for making a PR to fix this 🎉

Someone from the team will get this reviewed and get back to you soon.

**Comment by mikecp** [comment]
Hello @IbrahimMNada,

Apologies for the delayed answer

**Comment by mikecp** [comment]
Hello @IbrahimMNada,

Apologies for the delayed answer 😅
Your update looks fine, but I was wondering if you had given a try to @Zeegaan 's suggestion to use the `IUserService` to get the User info?
I'm asking because that would probably make a more robust solution, and since the class is internal, I don't think it would be a problem to inject the service in the constructor for example.

So it would be super great if you could check how that would work out😁

Cheers!

**Comment by IbrahimMNada** [comment]
I have no problem injecting the IUserService in the Audit repository , 
but wont that break the paradigm of the idea that repositories should not depend on services ? 
its the other way around , services should depend on repositories.
and it would cause a circular dependency leading to a stack-overflow if we later needed to inject the repos into a service.
 (please correct if I'm wrong) I have  randomly checked some repositories didnt seen any ones that uses services. 
 
 
plus if we go with services we lose the caching , which in my experience is gonna be useful since most of the time me or the people I know  used content services mostly for migration/bulk transitions. 

but never the less its you call , i'm ready to change it

**Comment by mikecp** [comment]
Woopsie my bad, I did not pay attention to the fact that it was a Repository 😅

Then it's indeed fine 👍

**Comment by mikecp** [comment]
Hi again @IbrahimMNada ,

I took, a further look, it all works fine, thanks a lot 👍

Before merging, I wanted to suggest trying to get rid of the hardcoded SQL statement, which can turn out tricky to maintain (aka we forgot about them😅 ) through time and maybe try to take inspiration from what is done in the `PerformGet` method a little above.

This could give like the code below (not tested), which I think would be easier to maintain if some DB related things change through time.

```
    Sql<ISqlContext> sql = SqlContext.Sql();
    sql = sql.Selectt<UserDto>();
    sql.Where(GetBaseWhereClause(), new { Id = entity.UserId });
   
    int? userIdQueryResult = Database.FirstOrDefault<UserDto>(sql) ?? throw new InvalidOperationException("The user id does not exist");
```
Would you maybe be up for trying this approach 😁?

No problem if you don't have the time to, then I'll merge your code as-is 👍

Cheers!

**Comment by IbrahimMNada** [comment]
Not a Problem
I will change/try today for sure

**Comment by IbrahimMNada** [comment]
Done , I have change it to follow Npoco annotations , made the method more reusable/overridable for other consumers

**Comment by Zeegaan** [comment]
Hello 👋 
I just had a talk with the team about this proposed solution, and although we really appreciate the time you've taken to work on this, we don't think that this s the solution we want.

We want to fix this in the `AuditService` itself, and it should return and Attempt<AuditOperationStatus>, and if the user doesn't exist, we will return a failed attempt, this matches the other services patterns 👍 
Altough this means refactoring a lot of places, where services use the AuditRepository directly, it will be much easier to maintain going forward.

We will mark the issue as a sprint candidate, so this works goes in our backlog.

**Pull request closed without merging**
