### PR TITLE
v8: Fix table cells collapsing when sorting doctypes in Nested Content

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
At the moment when sorting doctypes in Nested Content config, the table cells collapse. This might be a bug in `ui-sortable` when sorting in applied to tables.
E.g. here is an example of the problem https://www.foliotek.com/devblog/make-table-rows-sortable-using-jquery-ui-sortable/

This PR add a fix for this similar to the one used in the old Related Links property editor.
https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/views/propertyeditors/relatedlinks/relatedlinks.controller.js

It seems there are still some issues with e.g. just a single document type and sorting like, where it seems the table header cells jumps a bit, but at least this avoid the cells in the table rows to collapse.

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hey @bjarnef ,

Can you let us know how to reproduce this?

Poornima

**Comment by bjarnef** [comment]
Hi @poornimanayar 

- Create an instance of Nested Content property editor in data types or use an existing datatype.
- Do a sorting on the doc types items using the move handle on the left.

Before the table cells collapsed as they didn't kept their width/styling when dragging the row.

**Comment by poornimanayar** [comment]
Hey @bjarnef ,

I shall get this tested today and let you know how it goes :-) Thank you for the work as always.

Poornima

**Comment by nul800sebastiaan** [comment]
Lovely, that works much nicer, thanks for the fix @bjarnef ! ⭐️

**Pull request merged**
