### PR TITLE
V8: Optionally show the item type in the list of items in Nested Content

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

This PR adds the option to show the name of the item type underneath the item title and icon in the NC property editor. 

While this is principally redundant when icons are show, I find that the item type name would bring additional value to the editors - specially when there are a lot of item types available (thus a lot of icons to tell apart).

To utilize this feature it must be explicitly enabled in the NC configuration. Unlike "Show Icons" this option defaults to `false`.

Here's how it all works:

nc-item-type-name

### CODE REVIEW

**Comment by kjac** [comment]
Property naming fixed. Thanks @bjarnef 👍

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by kjac** [comment]
PR updated with latest v8/dev

@nul800sebastiaan we've got customers starting to request this feature on their own now. Any idea if this is going in?

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by poornimanayar** [comment]
Tested this again against the latest `v8/contrib` and this is good to go!

**Comment by nul800sebastiaan** [comment]
Hey @kjac - for now, we would encourage you to use the possibility to Nested Content label templates to add the type name or a description next to your label. Just like with PR https://github.com/umbraco/Umbraco-CMS/pull/7098, we're going to overhaul this dialog and the idea is to make the options more descriptive. For now I'll close this one and we'll wait for the Block Editor work to be done first.

**Pull request closed without merging**
