### PR TITLE
Replace attribute with `noPasswordManager` directive

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
This PR replaces a few ` data-lpignore="true"` I noticed with the `no-password-manager` added a while ago, which handle this https://github.com/umbraco/Umbraco-CMS/blob/1527b2577e7273157cfede70444c65f838a87225/src/Umbraco.Web.UI.Client/src/common/directives/util/noPasswordManager.directive.js#L21

but also other password managers in case added later.

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi @bjarnef 

Thanks for this useful PR. 

Myself or another Core Collaborator will review soon!

In the meantime, is there any article link where I can find the "no-password-manager" attribute described, for more understanding?

Thanks

Emma

**Comment by JasonElkin** [comment]
Hey @emmagarland, I know this one. `no-password-manager` is a directive that serves as an abstraction for setting the `data-lpignore` [attribute here](https://github.com/umbraco/Umbraco-CMS/blob/05b89999afb65caf7e8dd7f17d34edbaa10cc842/src/Umbraco.Web.UI.Client/src/common/directives/util/noPasswordManager.directive.js#L21). Presumably so it can be changed, or more added at a latter date.

Specifically, the attribute stops LastPass from trying to autofill the field.

**Comment by emmagarland** [comment]
@JasonElkin excellent, that is a great directive to know about! Thanks both cc @bjarnef

**Comment by bjarnef** [comment]
I searched around, but it doesn't seem a password manager like [1Password](https://1password.com) has an attribute to disable it at the moment.

**Pull request merged**
