### PR TITLE
U4-7874 - Add events to content editor

### PR DESCRIPTION
**Pull request by lars-erik**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description
Added events for "new ready", "loaded", "saving", "saved", "unpublishing" and "unpublished".

### CODE REVIEW

**Comment by dawoe** [comment]
Hi @lars-erik 

I checked this and all events are fired.

@nul800sebastiaan looks fine to me.

**Comment by nul800sebastiaan** [comment]
I love it! Thanks @lars-erik !

**Comment by skttl** [comment]
Did this get into 7.11?

**Comment by nul800sebastiaan** [comment]
Yeah, but @lars-erik didn't want to close the issue. Done anyway now! Make more issues ;-)

**Comment by lars-erik** [comment]
It's got the 7.11 release tag at least. :) But we're after the grid-one if you're thinking of fixing the copy/close package.

**Comment by lars-erik** [comment]
@skttl the other one should also be in 7.11 https://github.com/umbraco/Umbraco-CMS/pull/2639/commits/76c924fbaa3da89d9865d9ec405e6dbb123852e3

**Comment by nul800sebastiaan** [comment]
Correct: http://issues.umbraco.org/issue/U4-11356

**Comment by lars-erik** [comment]
@nul800sebastiaan I think it was the copy/paste PR i didn't wanna close. But I should have the branch on my repo, so it should be alright.

**Comment by skttl** [comment]
@lars-erik I wanted this one too :)

**Comment by lars-erik** [comment]
👍 :)

**Comment by dampee** [comment]
Had this been added to the Documentation somewhere?

**Comment by lars-erik** [comment]
@dampee Not AFAIK. Feel free. :)

**Pull request merged**
