### PR TITLE
Changes add-button to a button

### PR DESCRIPTION
**Pull request by skttl**
Makes it possible to tab to the button.

### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: #3633 

### Description
Changed the `<a>` to a `<button>` which makes it possible to tab to the add-button, for adding Nested Content values using only the keyboard.

### CODE REVIEW

**Comment by skttl** [comment]
Wait, doesn't work yet :)

**Comment by abjerner** [comment]
Alternative you can stick with the `<a/>` and give it a `href="#"` attribute. Then you should be able to tab to it as well ;)

**Comment by skttl** [comment]
Just did :)

**Comment by abjerner** [comment]
Awesome. I'll try to give it a spin later today ;)

**Comment by nul800sebastiaan** [comment]
Sweet, thanks @skttl ! 👍

**Pull request merged**
