### PR TITLE
Replaced umb-checkbox with umb-toggle in listview copy overlay

### PR DESCRIPTION
**Pull request by poornimanayar**
I noticed that when you try to copy items in a list view the "Relate to Original" option uses `umb-checkbox`. I have replaced it with `umb-toggle` to make it consistent.

**Before**
listview-copy-before

**After**
listview-copy-after

### CODE REVIEW

**Comment by bjarnef** [comment]
I wonder if the "Relate to original" and "Include descendants" should be `umb-checkbox` instead of `umb-toggle`.

E.g. in link picker we have "open in new window" as checkbox.

Not sure if these are classified as settings.

Here are some great articles about toggle vs checkbox.
https://www.nngroup.com/articles/toggle-switch-guidelines/
https://uxmovement.com/buttons/when-to-use-a-switch-or-checkbox/
https://uxplanet.org/checkbox-vs-toggle-switch-7fc6e83f10b8

**Comment by poornimanayar** [comment]
@kjac ,

Thanks for the review. I have made the amends. Regd #6903 I had the exact same thoughts as yours while I was reviewing it :-) 

Poornima

**Comment by kjac** [comment]
Merged! Thanks again ⭐️

**Pull request merged**
