### PR TITLE
Add KeepAlive settings to resolve #7116

### LINKED ISSUE #7116: keepalive/ping component should have some config options
Currently the KeepAlive component (see https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web/Scheduling/KeepAlive.cs) uses the `_runtime.ApplicationUrl` to send a request to itself. Typically we require that an Umbraco website can send requests to itself based on the external configured URL for the website which normally requires configuring some internal DNS resolution. This might not always be possible in all hosting scenarios, so we want to be able to configure this component with some options:

* Best to create a new interface: IKeepAliveOptions
* The interface should contain 2x properties (for now, maybe more later)
  * Disable (bool) - which would forcibly disable keep alive from running
  * KeepAliveUrl (string) - this could be null and in which case the KeepAlive component would just continue to use the `_runtime.ApplicationUrl`
* The ctor of the `Umbraco.Web.Scheduling.KeepAlive` should then have another ctor parameter of type `IKeepAliveOptions` which could be an optional parameter that defaults to NULL
* Then the component's code needs to be updated to use these options if they are not null
* Then the `Umbraco.Web.Scheduling.SchedulerComponent` needs to be updated to pass in an instance of IKeepAliveOptions in the `RegisterKeepAlive`
  * For now, it will be easiest to create an internal class `KeepAliveOptions` which implements `IKeepAliveOptions` which reads from appSettings, these keys could be used (which could be added as constants to `Umbraco.Core.Constants.AppSettings`)
    * "Umbraco.Web.KeepAlive.Disabled" 
    * "Umbraco.Web.KeepAlive.Url" 

---
_(Original post below...)_

## Umbraco version

I am seeing this issue on Umbraco version: 8.1.3

Reproduction
------------

### Bug summary

The `Ping` action in the `KeepAliveController` only allows local request. If requests are not coming from localhost, the `OnlyLocalRequests` attribute returns a 404. 
In my case, the 'umbracoApplicationUrl' is set to 'https://admin.mysite.com/umbraco'. This setting is being used by the [`KeepAlive` RecurringTaskBase.](https://github.com/umbraco/Umbraco-CMS/blob/27223738c6af045b637bb9944b53134e681ce5e5/src/Umbraco.Web/Scheduling/KeepAlive.cs#L60).
The task sends an HTTP GET request to 'https://admin.mysite.com/umbraco/api/keepalive/ping'. When making that request, a 404 is return because of the `OnlyLocalRequests` attribute.

This is causing the logs to be full of 404 issues. 
_Can we change the behavior for the `KeepAlive` task so it can use a new base URL setting specifically for `KeepAlive`?
Alternatively, it would be great to be able to turn off the KeepAlive functionality?_

### Specifics

- umbracoApplicationUrl set to 'https://admin.mysite.com/umbraco'
- admin.mysite.com is proxied through Cloudflare
- site is hosted on Azure App Service

### PR DESCRIPTION
**Pull request by Swimburger**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

Fixes #7116 

### Description
A keepAlive config section has been added to `umbracoSettings.config`. I did my best to replicate the logic of the existing config sections.
The new **keepAlive** section has two settings:

- **enableKeepAliveTask**: 
   Enables the periodic KeepAliveTask.
   Use this setting to disable the KeepAliveTask in case you already have an alternative.
   For example, Azure App Service has keep alive functionality built-in.
   Defaults to "true".
- **keepAlivePingUrl**:
   The url of the KeepAlivePing action. By default, the url will use the umbracoApplicationUrl setting as the basis.
      Change this setting to specify an alternative url to reach the KeepAlivePing action. eg http://localhost/api/keepalive/ping
      Defaults to "{umbracoApplicationUrl}/api/keepalive/ping".

The reason for using `umbracoApplicationUrl` as a default in the `keepAlivePingUrl` setting, is to maintain backwards compatibility.

Though I intend to add unit tests if applicable after receiving feedback, I've tested the basics by hand so far:

- enableKeepAliveTask
  - true => everything works as before
  - false => keepAliveTask doesn't run as expected
  - remove keepAlive-node or enableKeepAliveTask-attribute => falls back to true
- keepAlivePingUrl
  - {umbracoApplicationUrl}/api/keepalive/ping => uses umbracoApplicationUrl and reached keepAlivePing action.
  - https://localhost:12345/umbraco/keepalive/ping => assuming that's the correct port, reaches peekAlivePing action.
  -  remove keepAlive-node or keepAlivePingUrl-attribute => falls back to "{umbracoApplicationUrl}/api/keepalive/ping"

**Extra change**: [OnlyLocalRequests] attribute has been removed from the keepAlivePing action so it can be reached from outside. I don't think this is a security concern and allows people to reach keepAlivePing action from outside when necessary such as in my case. (Azure App Service + DNS in Cloudflare).

### CODE REVIEW

**Comment by Swimburger** [comment]
Not sure why gulp failed, no gulp related files were modified. Can the integration build be retriggered?

**Comment by emmaburstow** [comment]
Hi @Swimburger 

Thanks for the PR - and congrats on the first to this repo! The work looks fab. You've done an excellent job replicating existing patterns. The code looks good too. We'll test and make sure nothing breaks but in the meantime, nice work! As it's a first contribution, once we merge, you'll get a shiny new contributor badge on your Our.Umbraco.com profile :)

Emma

**Comment by Swimburger** [comment]
Thank you @kjac for the feedback. I believe I was able to implement all the suggested changes.

**Comment by kjac** [comment]
@Swimburger there's a merge conflict with `umbracoSettings.config` on this PR now. Could you have a look at resolving it?

Please note that I have changed the base branch from `v8/dev` to `v8/contrib` for this PR. This means you'll have to pull `v8/contrib` and merge it into your PR branch to resolve the conflicts.

**Comment by Swimburger** [comment]
Conflict has been resolved. Should the PreviewBadge HTML not be minified like it was before?

**Comment by kjac** [comment]
Thanks again, @Swimburger ... don't worry about the preview badge HTML for now. If it needs minifying that'll be another PR 😄

**Comment by mastermoe01** [comment]
when will this be released?

**Comment by nul800sebastiaan** [comment]
@mastermoe01 This fixes issue https://github.com/umbraco/Umbraco-CMS/issues/7116 which is marked for release 8.6.0, so it will be available in a few days.

**Comment by Swimburger** [comment]
@mastermoe01 you can find the release with this new addition here: https://our.umbraco.com/download/releases/860

Btw, I don't see a contributor badge on my Umbraco profile: https://our.umbraco.com/members/Swimburger/
Is it not connected correctly @emmaburstow ?

**Comment by nul800sebastiaan** [comment]
@Swimburger whoa sorry about that, got you your contrib badge! 🎉 
And now I realize there's even more PRs in this release made by the community, I only counted the ones with the 8.6.0 label on the PR, not the one where the label was on the issue. Will correct this soon, thanks!

**Pull request merged**
