### PR TITLE
Resolved more warnings, and marked more warning types as errors

### PR DESCRIPTION
**Pull request by emmagarland**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

Continuing on from #16990 

If there's an existing issue for this PR then this fixes some of #15015 

### Description

Updated all projects to only list remaining specific warning codes as warnings instead of errors (errors is now default).

Fixed various warnings where they are more straight-forward, including:

- SA1111/SA1116/SA1119 parenthesis formatting
- SA1117 params formatting
- SA1312/SA1306 lowercase variables and field names
- SA1121 built-in type
- SA1500/SA1513/SA1503 formatting braces
- SA1400 declare access modifier 
- SA1122 string.Empty
- SA1310 no underscore
- SA1649 filename match type name
- IDE0049 name simplified
- IDE0057 simplify substring
- IDE0074 compound assignment
- IDE0032 use auto-property
- IDE0037 simplify member name
- IDE0008 explicit type not var
- IDE0016/IDE0270/IDE0041 simplify null checks
- IDE0048/SA1407 clarity in arithmetic
- IDE1006 params naming rule violation
- IDE0042 deconstruct variable
- IDE0044 make field readonly
- IDE0018 inline variable declarations
- IDE0074/IDE0054 compound assignment
- IDE1006 naming
- CS1573 param XML
- CS0168 unused variable

Comment formatting in project files for consistency.

To test, ensure solution builds, tests and runs as expected. Worth scanning the files changes to ensure no likely issues I've not considered.

Currently seeing 8617 solution-wide warnings (this needs verification)

### CODE REVIEW

**Comment by georgebid** [comment]
And I will also look at this one when you are finished with it 😺

**Comment by emmagarland** [comment]
@georgebid think I'm finished with this so far, but I won't publish till the other I merged since I branched off that one (fewer files to read!).

Some Codescene warnings are because the files got bigger due to formatting changes etc.

**Comment by georgebid** [comment]
@emmagarland The other is merged now so feel free to edit and let me know when this one is ready to be looked at 😸

**Comment by emmagarland** [comment]
@georgebid Coolio, thanks, I'll let you know when it's all ready! 😃

**Comment by emmagarland** [comment]
@georgebid I've now merged from `contrib` and tweaked a few merge issues and comments locations. I've built and run locally, so it's now ready for review. 

Again, Codescene is not happy that I've increased the length of things by updating the formatting according to the Stylecop guidelines etc, but I don't think that can be helped at this stage. 

It would also be good to know what you get for number of warnings on this branch (and possibly `contrib`). I'm not getting consistent numbers atm.

Let me know if any questions!

**Pull request merged**
