### PR TITLE
Improve image cropper UX

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, this fixes: https://github.com/umbraco/Umbraco-CMS/issues/3148
- [x] I have added steps to test this contribution in the description below

### Description

This PR fixes a few UX issues for the Image Cropper, as outlined in #3148:

1. Adds explicit buttons for saving and resetting the crop
2. Makes the close button behaves like a close button should
3. Ensures that crops are only applied when saved (not immediately after opening a crop)
4. A bit of wording and spacing :)

image cropper after

The testing should be pretty straight forward. Though - when testing it, make sure you test this scenario also:
1. Upload a new file
2. Open a crop for editing
3. Edit the crop
4. Close the crop editor by the close button (effectively discarding the changes)
5. Ensure that the crop is still "attached" to the main image

### CODE REVIEW

**Comment by kjac** [comment]
@nul800sebastiaan totally doable. But the "x" and the "reset" has two different functionalities:

- The "x" is essentially your "discard changes"; it discards whatever you've done since the last time you clicked "Save" on the crop.
- The "reset" actually resets the crop, thus linking it back to the main image.

Soooo... I think we need both.

**Comment by nul800sebastiaan** [comment]
@kjac 🤔
You make a good point!

So I had a little look with Mads and took some inspiration from Google Photos.

How about 3 buttons: Reset (a link, just like it is now but larger text), "Undo edits" (gray background, to discard changes) and "Done" (green background, to save changes). The "Undo" and "Done" buttons should be on the right, like in our normal UX patterns.

The wording is a bit different, "Done" instead of "Save" since you don't save anything until you save the document. And "Undo edits" is nicely borrowed from google photos 😉

**Comment by kjac** [comment]
@nul800sebastiaan so something like this?

image

**Comment by nul800sebastiaan** [comment]
@kjac Looks great!

**Comment by kjac** [comment]
Super I'll update the PR

**Comment by kjac** [comment]
Done 😄

**Comment by nul800sebastiaan** [comment]
Awesome! The updates look and work great, let's go for it! Thanks @kjac 🏅

**Comment by kjac** [comment]
Whoo 🎉

**Pull request merged**
