### PR TITLE
Fixing regression bug introduced in #14806

### PR DESCRIPTION
**Pull request by wtct**
Fixing regression bug introduced in #14806 and found during investigation of #16803 - well tested on db with 300k+ nodes

### Description

Fixing regression bug introduced in #14806 and found during investigation of #16803 - well tested on db with 300k+ nodes

Please consider merging this PR as a quick fix for bug introduced in the #14806 by @Zeegaan.

There is lack of the WHERE clause in the sql count queries.

It has massive impact on publish/unpublish operations in Umbraco instances with huge amount of content.

In our case it's not possible to use the CMS by editors after upgrading to the 13.4.1.

### CODE REVIEW

**Comment by georgebid** [comment]
Thanks for the PR to fix this bug @wtct, someone on the core collaborators team will review this soon, although, it may be helpful if @Zeegaan takes a look, as I expect you'll be most familiar with this change 😺

**Comment by piotrbach** [comment]
Hi @georgebid, we have double-checked the code and can confirm that it works correctly🎉. 

Do you conduct performance testing before releases🤔? 
The issue seems to go unnoticed with a small number of documents but becomes significant as the dataset grows.
It's surprising that this obvious bug is being reported only now, considering it affects projects from versions 10, 13, and 14. 
With over 300,000 records, the CMS becomes unusable for editors.

I hope this PR gets approved soon🙏🤠, as it is blocking our key project.
Btw. Referring to [this blog post on Umbraco performance issues](https://umbracare.net/blog/addressing-umbraco-performance-issues-a-critical-update-for-version-13-and-14/) might speed up the review.

cc: @wtct @Zeegaan

**Comment by Zeegaan** [comment]
Thanks for this contribution, and the write up around it 😁 
Looks good, tests good 🚀

**Comment by piotrbach** [comment]
Hi @Zeegaan no problem!
Btw. When can we expect the release of fixed v13, so we can update our project?
This fix is critical for us🙏. 
@wtct

**Comment by Zeegaan** [comment]
We have a few other issues we are in the process of fixing for v13, so can't really give a precise timeline unfortunately. 

So I would say hopefully in the next 2 weeks time, but I cannot promise anything 😁

**Comment by wtct** [comment]
@Zeegaan Maybe it's worth considering releasing a new version just with this fix, because it's a critical issue?

**Comment by nul800sebastiaan** [comment]
Cherry-picked for v13 in 2736a513a3dd0a29aeac61ace614ff2effdf7135

**Comment by OwainJ** [comment]
Just hit this issue trying to migrate 400k nodes into a new v13 site 😬 if this could be released as a patch to 13.4, as 13.5 is 2+ weeks away, I would be eternally grateful!! 🙏

**Comment by piotrbach** [comment]
Hi @georgebid @Zeegaan @nul800sebastiaan, sorry to bother you again. 
I was wondering if there's any update or an estimated release date for the fixed version of v13? 
Thanks in advance🤝

@wtct

**Comment by Zeegaan** [comment]
Yes but it's not good news unfortunately, its gonna be around the beginning of September 😁 
However, if you really need this patch for your project, you can always use a nightly build 💪 
https://docs.umbraco.com/umbraco-cms/fundamentals/setup/install/installing-nightly-builds

**Comment by prjseal** [comment]
> Cherry-picked for v13 in [2736a51](https://github.com/umbraco/Umbraco-CMS/commit/2736a513a3dd0a29aeac61ace614ff2effdf7135)

Hi Seb, 

Would you be able to cherry pick this for v10 too please? We are experiencing this on one of our Umbraco Cloud v10 sites and v10 is also LTS isn't it?

Kind regards

Paul

**Comment by RosenPetrovFFW** [comment]
I am also looking after the release of version 13.5.0. 53k nodes in the project and we are impacted by this problem, too.

**Comment by RosenPetrovFFW** [comment]
Sebastiaan, replied to me that probably later today 13.5.0 would be released!

**Comment by wtct** [comment]
> Cherry-picked for v13 in [2736a51](https://github.com/umbraco/Umbraco-CMS/commit/2736a513a3dd0a29aeac61ace614ff2effdf7135)

Hi @nul800sebastiaan,

Please take into account that this issue has been introduced in the v10.8.0 during the security phase after the support phase as we can see here:

https://umbraco.com/products/knowledge-center/long-term-support-and-end-of-life/

https://our.umbraco.com/download/releases/1081 (Released on Tuesday, December 12 2023)
https://our.umbraco.com/download/releases/1080 (released between 10.7.0 and 10.8.1)
https://our.umbraco.com/download/releases/1070 (Released on Thursday, September 7 2023)

So now we have to decide if we want to upgrade to the secure version or stay with the efficient one (10.7.0), or even go for 13.5.2 what could be challenging in projects.

Could you please consider merging this PR to v10 and prepare another release?

Thanks in advance!

Best!

cc: @piotrbach

**Comment by nul800sebastiaan** [comment]
@wtct Unfortunately I can't help you here:

- The performance issue [was introduced]https://github.com/umbraco/Umbraco-CMS/pull/14806) on Sep 14, 2023 - v10 was in Support Phase
- You [reported performance issues](https://github.com/umbraco/Umbraco-CMS/issues/16803) on Jul 19 2024, v10 was in Security Phase
- You [provided a PR](https://github.com/umbraco/Umbraco-CMS/pull/16837) on Jul 29 2024, v10 was in Security Phase

Since we're not delivering any more releases for v10 except for security updates, we recommend you upgrade to v13 instead.

**Pull request merged**
