### PR TITLE
v8: Imagepicker prevalue and grid setting/styles as infinite editor

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/4911

### Description
This PR fixes the broken `imagepicker` prevalue editor, which was using `umb-overlay` + `mediapicker` overlay (which has been removed in v8). It replaces this with infinite editing.

Furthermore the `umb-overlay` has a z-index on `7500` while `.umb-editor` for infinite editing only has z-index `100`, so when opening the imagepicker infinite editing, the `umb-overlay` convered the infinite editor with a transparent white overlay, but was removed the clicking in infinite editing, because the `umb-overlay` was closed. I have therefore also replaced the grid config/styles with inifinite editing.

image

image

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hello again @bjarnef ,

Many thanks for this PR. We shall test it and let you know if anything is needed. :-)

Poornima

**Comment by bjarnef** [comment]
@nul800sebastiaan can we prioritize this for next release since it at the moment isn't possible in core to use image picker on grid settings/styles, unless you add a custom prevalue editor.

**Comment by benjimedia** [comment]
Hey, do we have any idea which release of v8 this bugfix will be available in?

**Comment by nul800sebastiaan** [comment]
@bjarnef What am I doing wrong testing this PR?

image

image

**Comment by bjarnef** [comment]
@nul800sebastiaan I have to check it again since it has been a while since I worked on this. Maybe also with latest v8 changes.

**Comment by nul800sebastiaan** [comment]
@bjarnef I think I'm just putting that JSON in the wrong thing, I have the same result in 8.0.1.. I just have no idea how to use this haha

**Comment by nul800sebastiaan** [comment]
Yep,it's just me, it needs to be surrounded by square brackets `[ ]` whoops! Something seems to work now. 😄

**Comment by nul800sebastiaan** [comment]
@benjimedia  I'm in the process of applying the PR to v8.0.2, due out next Tuesday.

**Pull request merged**
