### PR TITLE
Fixes #U4-11406 by setting the thread culture before rendering macro

### PR DESCRIPTION
**Pull request by enkelmedia**
Fixes this issue: http://issues.umbraco.org/issue/U4-11406

### Description
Since I wanted to avoid making to much changed in the old legacy stuff I figured that this is a quite pragmatic solution and I guess that these parts of the core will be either rewritten or wiped for V8.

I know that it might be hacky but it does the job. Any feedback is appreciated =D

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi,

Many thanks for the PR. We will review the PR within the next 14 days .

Regards,
Poornima

**Comment by nul800sebastiaan** [comment]
Hi @enkelmedia - I have a few hesitations about this:

1. It is basically a breaking change, the behavior changes from the previous behavior which might confuse users - it is however an improvement
2. What happens when multiple domains with multiple cultures point to the same node?
image
3. Do we always get a culture? In other words, are we missing null checks here?
4. This should ONLY be done when rendering the content in the backoffice, I am not sure how to test for that though.. We shouldn't force a cache lookup for the current page if we're already on the current page and the culture has been set already.

**Comment by enkelmedia** [comment]
Hi!

@nul800sebastiaan Thank for the fast feedback!

1. It only effects the backoffice preview of the macro but I agree, might be considered a breaking change. But at the same time it's just a preview-feature does not have impact on the underlaying macro-stuff.

2. The "GetCulture"-method only returns one culture which when I tested it was the right one considering the place in the tree that I was testing in. I haven't look into the inner details of "GetCulture" but in the scenario that you are pointing at there is really no way to "know" the right culture for the front end i guess?

3. Not sure, I should probably add null-checks if we still want to go ahead with this approach as solution.

4. Thats right, this is only when the rendering is done in the backoffice, since the implementation lives in MacroController.cs that is a UmbracoAuthorizedJsonController you can't access this method from outside the backoffice.

**Comment by nul800sebastiaan** [comment]
@enkelmedia Thanks for the clarifications! 
Can you test what happens when there's 2 cultures on the root node? I assume it will take the first. I don't think it's much of a problem, the experience is hopefully better than before. And if you add some null checks, that would be awesome!

**Comment by enkelmedia** [comment]
Hi again!

I tested what happens when you have multiple hostnames with different cultures on one node, turns out that GetCulture() returns the last culture in the list. In the case below it would be Swedish, switching the order would return Finish. The first "Culture / Language" that is set to Swedish is ignore when the Finish culture is selected for the last hostname in the list.

image

If I just leave everything empty with no hostnames or any culture it will just fallback on English.

image

I've added null checks and updated the PR, please let me know if there is anything else that we need to address.

Cheers!

**Comment by nul800sebastiaan** [comment]
@enkelmedia Awesome, I can live with that, it's certainly an improvement over the previous situation!

Thanks very much 👍

**Pull request merged**
