### PR TITLE
V8: Fix clientside mandatory validation for checkbox list

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5762

### Description

This PR fixes the clientside mandatory validation for checkbox list; see #5762 for details.

This PR does _not_ fix the serverside validation, which is apparently also broken/not implemented.

With this PR applied, here's how a mandatory checkbox list behaves:

checkbox-list-mandatory-validation

### CODE REVIEW

**Comment by bjarnef** [comment]
@kjac I wonder if the radiobuttons also should validate on `!model.value.length` instead of `model.value == ''` and also use one-way binding as in checkbox list?

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by nul800sebastiaan** [comment]
Yay! I was just wondering why it didn't work earlier this week. Of course I should've known you'd already fixed it. 😉

**Comment by bjarnef** [comment]
@nul800sebastiaan is the change function back at `vm.changed`? I renamed it to `vm.change` in this PR https://github.com/umbraco/Umbraco-CMS/pull/6345 😁

**Comment by bjarnef** [comment]
It seems so..
https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.controller.js#L8

https://github.com/umbraco/Umbraco-CMS/blob/v8/dev/src/Umbraco.Web.UI.Client/src/views/propertyeditors/checkboxlist/checkboxlist.html#L4

**Comment by nul800sebastiaan** [comment]
Yikes! 

Merging is difficult. :-(

Fixed in 8.2.0 5fdae055d56873b670fa141503d73c0a9060a57e / 8.1.5 2a3b169923e2382e6ed4c6a6f07ed8ab2c874cc6

Thanks for noticing @bjarnef !! ⭐️ 🏅

**Pull request merged**
