### PR TITLE
V14: Untangle the preview functionality from the auth cookie

### PR DESCRIPTION
**Pull request by bergmania**
### Description
This PR redo how the preview cookie works, because it cannot get the auth cookie, as that is not long living.

Instead the preview cookie, saves a user key in an encrypted way (using IDateProtector). This user key is then used on preview requests to look up and ensure the user is still valid (approved and not locked out).

If the user is valid it is added to as a principal like before.

### Test
- Enter preview mode and ensure you can see draft versions

### CODE REVIEW

**Review by Migaroez — APPROVED** [review]
Works as described.
Made a few minor improvements
- Log the error in debug mode when the trycatch fails in UserBasedPreviewTokenGenerator.VerifyAsync
- Since the tokengenerator can fail to generate, it seems better to bubble this up instead of swallowing it, even if our implementation is unlikely to do it.
- Return an attempt instead of nullable object for TryGetPreviewClaimsIdentityAsync

**Comment by iOvergaard** [comment]
Remember to update the OpenAPI.json file, gents 😎

**Comment by Migaroez** [comment]
You beat me to fixing the broken test...
Added a backlog item to expand the tests

**Comment by Migaroez** [comment]
Nice catch on the httpOnly check in the test and updating the delete requirement!

**Comment by iOvergaard** [comment]
> Nice catch on the httpOnly check in the test and updating the delete requirement! I have also added a backlog item to expand the integration tests

Apparently, we made the same fixes, so my changes ended up not doing much at all in the end. But it's looking great now!

**Pull request merged**
