### PR TITLE
Style Public access dialog

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR fixes: https://github.com/umbraco/Umbraco-CMS/issues/3193
- [x] I have added steps to test this contribution in the description below

### Description

This fixes some of the more prominent UI issues in the Public access dialog:

protect after

To test, verify that:

1. The button bar aligns at the bottom of the dialog
2. The group boxes are of equal height
3. The confirmation looks ok
4. It's still possible to both add and remove protection

### CODE REVIEW

**Comment by abjerner** [comment]
Oh well. Silly me. I posted my response in the issue instead of this PR 😢 

I'll have a look at your changes and report back. Hopefully I'll be able to do so within the next few days ;)

**Comment by abjerner** [comment]
Btw - one small thing I noticed. The button for confirming the setup for public access is now called **Update**. To be consistent with other dialogs, shouldn't it be called **Save**?

**Comment by kjac** [comment]
@abjerner it's always been "update". It's easy to change but I didn't want to introduce more UI changes than strictly necessary. 

Just say the word and I'll change it.

**Comment by abjerner** [comment]
@kjac I wasn't sure about that part, as I haven't looked that much into your PR yet. But I think **Save** makes the most sense - also following some of the other dialogs.

**Comment by kjac** [comment]
@abjerner there you go :)

**Comment by nul800sebastiaan** [comment]
@kjac I haven't looked at this yet, but why do you get node Id's when you pick login/error pages. They're page titles right now.

**Comment by kjac** [comment]
@nul800sebastiaan they're not node IDs, it's just my page titles 😁 they're named after the GitHub issues I've been testing...

**Comment by nul800sebastiaan** [comment]
@kjac 😂 
Okidoki!

**Comment by nul800sebastiaan** [comment]
Looking good, thanks @kjac !

**Pull request merged**
