### PR TITLE
Block List Settings throws exception if Models builder mode is set to "Nothing"

### PR DESCRIPTION
**Pull request by AndreyKarandashovUKAD**
Not sure if my fix is good. I think it's not so good idea to use ModelsBuilderSettings in Value converter,
but I do not understand why do we need to use settingsType if we can use the same way as we have for _contentData_ type.

                    var settingsType = blockConfig.SettingsElementTypeKey.HasValue 
                        ? _blockConverter.GetModelType(blockConfig.SettingsElementTypeKey.Value)
                        : typeof(IPublishedElement);
                    var layoutType = typeof(BlockListItem<,>).MakeGenericType(contentData.GetType(), settingsType);`

Should we use use settingsData.GetType() instead of using _blockConverter.GetModelType() method?

UPD: If everything looks fine - I'll fix Unit tests. 

Issue: https://github.com/umbraco/Umbraco-CMS/issues/11712

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Hey there @AndreyKarandashovUKAD, apologies for the delay on this one! Your changes were great 💪 except for this one annoying thing that we need to be aware of breaking changes, so we can't just change a public constructor. Not to worry though, I've amended it for you, left the original ctor there and added an obsolete warning on it. Then I made sure to send an instance of `IOptions<ModelsBuilderSettings>` from the old ctor to the new ctor so anybody using the old one will still get the expected result. 

Thanks again!

**Comment by ronaldbarendse** [comment]
Changing the settings type based on the ModelsBuilder mode will certainly result in runtime exceptions! If you're using `SourceCodeAuto` (or `SourceCodeManual`) during development, (correctly) change that to `Nothing` in production (because the models are already compiled) and use `BlockListItem<ActualContentModelType, ActualSettingsModelType>` in your views, this will now return `BlockListItem<ActualContentModelType, IPublishedElement>` instead, which are incompatible 💥 

I'm not saying there's no related bug, just that this fix will result in a regression. Looking at https://github.com/umbraco/Umbraco-CMS/issues/11712#issuecomment-1036324639, it might actually be something in [Anaximapper](https://github.com/AndyButland/Anaximapper) or the way it maps the settings type...

**Comment by nul800sebastiaan** [comment]
That's a good point @ronaldbarendse - for now I've reverted this in 75613cf06174ecdd39f53d332598c1346a3df631 and if you would like to have another look at this @AndreyKarandashovUKAD then that would be amazing 🙏

**Comment by AndreyKarandashovUKAD** [comment]
@ronaldbarendse Even if you don't you anaximapper and models builder set to Nothing this issue appears, so not sure what way is the best. I prefer to use my own models instead of models builder during the development.

**Pull request merged**
