### PR TITLE
U4-9154 Media Picker for Grid Editor doesn't update if image changed on media…

### PR DESCRIPTION
**Pull request by jchurchley**
Modifying the grid rendering to handle when a user changes an image associated with a media idea. In addition, if the image is deleted but the media node exists have an explanation included. If the media node has been deleted it will reset to allow for new image to be added. Finally, if the media node has been moved to the recycle bin then tell the user this is now in the recycle bin.

### CODE REVIEW

**Comment by jchurchley** [comment]
Hi can anyone provide any feedback on how this can be accepted? Would be useful to give me content editors an early Christmas present.

**Comment by Shazwazza** [comment]
Hi! Thanks for the effort so far. If you can resolve the current merge conflicts that would be ace!

**Comment by jchurchley** [comment]
Thanks for tip Shannon! All merged. Hopefully it will be a valuable addition

**Comment by nul800sebastiaan** [comment]
Hey @jchurchley - first of all: sorry about the (very) late reply! 
As you may be aware, we're working on making the PR process a lot better, if you weren't aware then there's some blog posts to catch up on! 😃 
https://umbraco.com/blog/introducing-the-new-pr-team/
https://umbraco.com/blog/the-pr-team-chronicles-month-one/
https://umbraco.com/blog/the-pr-team-chronicles-july-2018/

Then.. wow that is a bit of a mess, but we can just start over!

I'll close this for now, make sure to have a read over the review below and let's see if we can improve this a little before merging it in!

## Untangling the mess

I'd recommend you first sync your fork with the upstream, as you can read here (make sure you switch back to the `dev-v7` branch first!): https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/.github/CONTRIBUTING_DETAILED.md#keeping-your-umbraco-fork-in-sync-with-the-main-repository
Once you have the latest `dev-v7` locally, create a new branch (maybe call it `U4-9154-2`). Then you can cherry pick your initial commit: `git cherry-pick 437a248ca916f7b3b6f5691ebd6244dfd98bf850`. That should get you back on track!

## Review
Thanks for this contribution, in general it's very helpful and a good improvement!

First of all, I think this works kinda okay, but you're testing on `parentId="-21"` and that should be without quotes. 
Second: in `url = $scope.control.value.image = mediaHelper.resolveFile(media);` it seems unecessary to get the image from the scope if you're immediately overwriting it with the resolved file?

Then I'm worried about the performance of this, since now for each image loaded in the grid we'd have to go an look it up in an extra request, not sure if we can improve that somehow though. Maybe before you retry this on @madsrasmussen can comment?

Lastly, once we delete a media item from the recycle bin, we now get a big red 404 in the bottom of the screen because the `resolveFile` call returns a 404. Would be good to nicely handle that error and show the appropriate message.

**Pull request closed without merging**
