### PR TITLE
Let it be possible to have macros inlined (in span) in Rich Text Editor

### PR DESCRIPTION
**Pull request by jomehmet**
Let it be possible to have macros inlined (in span) in Rich Text Editor so you can have variables in the middle of a text that can be updated in one content node, instead of updating it on hundreds of different places.

### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/discussions/13564

### Description
Currently it's not possible to have macro in the middle of a sentence/paragraph in the Rich Text Editor, since tinymce splits it up to three paragraphs, as the Macro placeholder in the markup is a div, which is not valid inside a paragraph.

This PR adds the possibility to have the Macro in the middle of a sentence.

The feature is fully backwards compatible, as the behaviour is opt in.

#### How to test the changes
- Create a document type, f.ex. _Document Type A_ and add a property with Rich Text Editor that has macro enabled.
- Create a New Partial view macro, and let it output a hardcoded text, f.ex. 15%.
- Go to Settings -> Macros -> Parameters -> Add a parameter called: **enableInlineMacro** and use Toggle as editor.
image

- Go to Content and create a new _Document Type A_
- Write a paragraph and add a macro in the midle of the text and make sure **enableInlineMacro** is enabled
image

- Verify it's not been split into paragraph + div + paragraph on multiple line
image
image

#### Extra info
Projects that wants Inlined Macro to be enabled by default can add a Custom Macro Parameter with default value of Toggle to be Enabled

```
    [DataEditor(
        alias: "enableInlineMacro",
        type: EditorType.MacroParameter,
        name: "Enable Inline Macro",
        view: "boolean",
        Group = "Macro Config",
        Icon = "icon-list")]
    public class EnableInlineMacro : DataEditor
    {
        public EnableInlineMacro(IDataValueEditorFactory dataValueEditorFactory)
            : base(dataValueEditorFactory)
        {
            DefaultConfiguration.Add("default", "1");
        }
    }
```

### CODE REVIEW

**Comment by jomehmet** [comment]
Based on the [feedback](https://github.com/umbraco/Umbraco-CMS/discussions/13564#discussioncomment-4692703) from @mikecp this PR is updated with a commit that let you enable the setting per. macro. The how to test section is updated in accordance with this new change.

**Comment by mikecp** [comment]
Hi @jomehmet ,

Thanks for this PR, it will be a nice addition to the macro rendering 👍

As you noticed, I started reviewing and adding some comments, mainly regarding breaking changes, because those are not allowed in minor versions. It seemed avoidable in the first files, but then I had a quick look down and saw some database migrations etc. and those will definitely be breaking changes. This means that this PR can only be put in V12.

This brought me to think a little further down a point that had come to my mind yesterday. It was about the fact that having the setting per macro would mean that if you wanted to use the same macro inline and as bloc, you would actually need to create two different macro's which would be identical except for that flag.

Long story short, I would like to know what you think about the alternative scenario of putting the inline/bloc choice in the macro picker of the RTE itself. Something like this (or maybe clearer with radio buttons or...):

image

 The choice could then be added as an extra attribute of the inserted macro, as is already done with the macroAlias attribute.

image

I see a few points of consideration about this approach:
 
- It becomes a Front-end update, no change is needed to the macro model itself, it becomes an extra "reserved" attribute within the RTE. So you get rid of all the database/data model/display model creation and mappings.
This probably means no breaking changes and possibility to merge in 11.2,, and it will probably also be much easier to cherry-pick to V10 if HQ wishes to.
- In the MacroTagParser, adapting the _macroRteContent Regex should make it possible to retrieve the "macroDisplayInline" attribute value without too much trouble
-  You can use the exact same macro both inline and in bloc depending on the situation. It becomes an editor's choice depending of the situation instead of a developer's choice at macro creation time.
- It has no impact on other places where you can add macro's (like in razor views) and where you don't need this inline/bloc distinction

I am well aware that this probably means undoing quite some of the work you did,, which is never nice, but I think that the benefit might be worth it. That said, I am no expert in the macro rendering so I might be completely overseeing some aspects here 😅

In any case, I'm keen to read your opinion about this 😊

Cheers!

**Comment by jomehmet** [comment]
> Long story short, I would like to know what you think about the alternative scenario of putting the inline/bloc choice in the macro picker of the RTE itself. Something like this (or maybe clearer with radio buttons or...):
 few points of consideration about this approach:
> 
> * It becomes a Front-end update, no change is needed to the macro model itself, it becomes an extra "reserved" attribute within the RTE. So you get rid of all the database/data model/display model creation and mappings.
>   This probably means no breaking changes and possibility to merge in 11.2,, and it will probably also be much easier to cherry-pick to V10 if HQ wishes to.
> * In the MacroTagParser, adapting the _macroRteContent Regex should make it possible to retrieve the "macroDisplayInline" attribute value without too much trouble
> * You can use the exact same macro both inline and in bloc depending on the situation. It becomes an editor's choice depending of the situation instead of a developer's choice at macro creation time.
> * It has no impact on other places where you can add macro's (like in razor views) and where you don't need this inline/bloc distinction

Thanks for going through the code @mikecp 😃
Personally I would prefer the current beahavior as the content editors are making a lot of repeating clicks through the day, and I think it would be annoying for them to have this extra click.

Nevertheless I'm eager to get something in that dosen't conflict with the "breaking changes policy".

Could we arrange so this current PR get's  included in future umbraco major version? In the meanwhile I create a PR with your  proposal? Is it ok if I have a global appsetting where default behaviour can be selected? as in our case we will always have the switch enabled.

**Comment by mikecp** [comment]
HI @jomehmet ,

Sorry for my late reaction. Let me check with HQ what their preferred approach would be on this.
I promise I'll get back to you quicker this time 😅

Cheers!

**Comment by jomehmet** [comment]
> Sorry for my late reaction. Let me check with HQ what their preferred approach would be on this. I promise I'll get back to you quicker this time 😅

No worries! looking forward to their preferred approach. Just let me know and I'll prepare something based on your feedback :)

**Comment by mikecp** [comment]
Hello @jomehmet ,

I got some feedback from HQ 🙂
To summarize, their message is to avoid making too big changes to macro's behavior at the moment because, as you may know,  they are in the process of completely rethinking the backoffice and, therefore, they are not sure yet if/how macro's usage and implementation will evolve in that story.

So, I guess the most optimal way to proceed for us is to implement the "lightweight" version now and to wait to have more info about the future of the backoffice before implementing the "breaking" version to target it.

I hope this makes sense for you 😁

Cheers!

**Comment by jomehmet** [comment]
Thanks for checking this up. I'm positive to create the "lightweight" version.
I'm thinking of either "remember" what choice used last time in the localStorage of the browser or having a appsetting to set globaly what should be the default. I think localStorage would give less code and more user friendly.

What do you think @mikecp ?

**Comment by mikecp** [comment]
Hey @jomehmet!

I would go for the local storage version because I know that HQ tries to limit the amount of "new app settings" to a minimum.
And also, maybe even more important, as you said, it's less code and more user friendly because then each user can have their own choice + change their mind along the way 😀

Also, to avoid that you get some branching issues: I think you started on v11/contrib but in the meantime that branch was removed and we just have a "contrib" branch in the repo. So I'm not sure of what this will give on your side if you update this branch and try to commit. Since I think there will be a lot of significant changes from the current code, it might be quicker to create a new branch from scratch... Up to you of course but now you know 😅

In any case, I'll be looking looking forward to this!! 👍🎉

**Comment by jomehmet** [comment]
Hi @mikecp :)

I minimized this PR and updated [the description](https://github.com/umbraco/Umbraco-CMS/pull/13628#issue-1517155685).
The choice of having the macro inline must be persisted somewhere, so I'm using the convention that, if there is a macroparameter named exactly: **enableInlineMacro** with the value "1", this means the user want's to have a inline macro.
There are more details in the description. To avoid making too much changes in this PR I'm also leting it be up to each project if they want a more advanced macro parameter editor than Toggle to enable macro. This is shown in the description in the paragraph called Extra info.

Hope this change fits your expectations and that we can get this into Umbraco 10.

**Review by mikecp — APPROVED** [review]

**Comment by jomehmet** [comment]
> Thanks @jomehmet for this new version, it works great and without breaking changes 👍🎉 

Glad to help😃👍

> Also, congratulations on your first contribution to Umbraco! H5YR! If you provide us with your account name on Our, @nul800sebastiaan will be very happy to assign our shiny contributor's badge to you 🥇

My Our account is now connected to this GitHub account, and I changed my name there to the same as on GitHub: jomehmet 

> I will also leave to him the task of deciding whether or not this should be brought into V10.

🤞

> 
> And now we'll be looking forward to your next PR 😉

Thanks 😃

**Comment by nul800sebastiaan** [comment]
Great work! And congrats on your shiny new contributor badge! https://our.umbraco.com/members/jomehmet  🏅

**Comment by mikecp** [comment]
Hello again @jomehmet ,
Just coming back on this because I forgot to mention it: if you have not done so yet, it might be worth creating a PR to update the Umbraco documentation about this feature 😉

Cheers!

**Comment by jomehmet** [comment]
Sure @mikecp! else this would be pretty much hidden functionality.
https://github.com/umbraco/UmbracoDocs/pull/4971

**Comment by mikecp** [comment]
Great @jomehmet ! H5YR 🎉

**Comment by richarth** [comment]
Thanks for getting back to me @nul800sebastiaan, that's understandable.

**Pull request merged**
