### PR TITLE
Postgresql prerequisites

### PR DESCRIPTION
**Pull request by dlidstrom**
### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description

This PR fixes some prerequisites for PostgreSQL persistence implementation. It corrects sql quoting from hardcoded use of Sql Server specific syntax (also supported by Sqlite) `[]` to use of `SqlSyntax.GetQuotedColumnName`. Brackets are unsupported in PostgreSQL.

It also adds primary key settings for link tables. This is also a prerequisite for PostgreSQL since NPoco will return the primary key column for inserts to a PostgreSQL database, whereas for Sql Server it returns `SCOPE_IDENTITY()` and for Sqlite `last_insert_rowid()`. Insert queries will fail without these attributes since NPoco will try to return `ID`.

This should be a safe change to make. It means columns will be quoted with `"` as per the existing persistence implementations. As far as I can tell this works identical to `[]` quotes.

I've also made the initial insert of English language to use auto-increment to allow the primary key to advance. Otherwise the next language to insert will fail (but subsequent tries will succeed).

### CODE REVIEW

**Review by mikecp — CHANGES_REQUESTED** [review]
Hi @dlidstrom ,

Thanks for this update👍. 

I will need to check with HQ for some of this, but I already wanted to mention that I noticed that the `[PrimaryKey] `attributes that you added on the DTO classes only mention the first column, while the `[PrimaryKeyColumn]` attribute that already exists within the classes, all contain at least two columns. (see example below)

image

So I guess that this should be adapted to have a match between the two 😁

Cheers!

**Comment by dlidstrom** [comment]
@mikecp Fixed so that the primary key column attributes have matching column names.

**Comment by dlidstrom** [comment]
Found an issue with the initial language insert. PostgreSQL will not increment the sequence associated with column `umbracolanguage.id`. So the next language to be inserted (by an admin) will try to insert with id 1 (already associated with English). To solve this I've changed the initial insert to use primary key auto-increment instead of hardcoding to 1.

**Comment by Jogai** [comment]
Is this still planned for inclusion? I think supporting postgresql is something that makes Umbraco more interesting for the whole open source community.

**Comment by bergmania** [comment]
Hi everyone..

Thanks for the effort done to make PostgreSQL possible.

There’s a few things I'm worried about in this PR.

1) Adding both `PrimaryKeyAttribute` and `PrimaryKeyAttribute` on the DTOs seems kind of duplicate. IMO this sounds more like an issue in NPoco if it doesn’t understand when the information is specified in one of the ways. But maybe that’s my lack of knowledge, but I’m really worried about the maintainability of our codebase.

2) Adding a `IsPostgresql` method in the CMS is definitely not something we want. Everything about PostgreSQL should be in a package. The fact that we already have `IsSqlite` and `IsSqlServer` is already a code smell, we would like to get rid of.
The reason is PostgreSQL can't currently be an officially supported provider as we cannot increase the size of our manual test matrix, which is already too big while just supporting two database providers.

3) The queries that are changed are still pretty hardcoded. I have a feeling it will just be a matter of time before we write another query that does not support PostgreSQL. I’m sure there is a better way to ensure this then these small tweaks to the queries.

4) Finally, I don't understand what the `docfx` update has to do with this?

**Comment by dlidstrom** [comment]
Hi @bergmania 

This work was done after reading [this comment](https://github.com/umbraco/Umbraco-CMS/discussions/12437#discussioncomment-2789615).

> for v10 it's easier than ever to add additional databases just by adding a package ref (that's how it works now for all of our supported engines) The [Umbraco.Cms.Persistence.Sqlite](https://github.com/umbraco/Umbraco-CMS/tree/release/10.0.0/src/Umbraco.Cms.Persistence.Sqlite) project would be a good starting point for inspiration especially given that SQLite syntax is inspired by postgres.

That gave some hope. Now to your questions.

1. That was required for the way NPoco works.

> NPoco with PostgreSQL will return the primary key value after insert,
so we need to define one for each table.

This can easily be enforced in each model class using a simple unit test.

2. This hack was the only way, due to the incomplete persistence abstraction. At least it follows the pattern in place and can be fixed with same mechanism that fixes the current hack.
3. That’s hard to solve since Umbraco really is geared towards SQL Server and SQLite. However any PostgreSQL fans could provide the necessary testing and point out wrongly escaped queries, if and when it happens.
4. Nothing. This is probably only a rebase issue on my end.

Feel free to close this if you think it will never be merged. I believe I’ve done my part which is to show some of the feasibility and limitations of the current approach.

**Comment by Tenney00Tang** [comment]
Hope to support postgresSQL soonly.  PostgresSql is so lovely comparing to MS SQL

**Comment by loid345** [comment]
Is there any news on this revolutionary improvement?

**Comment by nul800sebastiaan** [comment]
Hey all, we had another chat about this and we are going to have to put Postgres support on the shelve for now, if we're going to do it then we need some help from HQ to make sure it's done right. At the moment, this is not a priority and we can't give the needed help for it. We think this is a good one to look into when we make the switch from NPoco to EFCore, but that's also not going to happen any time soon.

I will close this one but mark it with the `idea` label, meaning we can take inspiration from here once this becomes a priortiy for us again. I want to thank you for putting the effort in so far already @dlidstrom, much appreciated! 💪

**Comment by mikkeljohnsen** [comment]
When will this become a priority ?

I have been looking af Umbraco for so many years now. First I waited 4-5 years for dotnet core to be adopted, so it could run on at container on Linux, now I have to wait for PostgreSQL to be available, since running MSSQL is not an option.

It is a very slow Open Source project ...

**Comment by dlidstrom** [comment]
@mikkeljohnsen it is also possible to use SQLite. This has quite a few benefits over PostgreSQL, actually. It is fully supported already.

**Pull request closed without merging**
