### PR TITLE
V13/feature/add user groups pagination

### LINKED ISSUE #15822: Pagination Missing for User Groups in Umbraco - Realy long loading times
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

13

### Bug summary

User groups lack pagination functionality, leading to significant slowdowns when managing a large number of groups. This becomes particularly evident when dealing with hundreds of groups, causing performance issues and hindering user experience.

### Specifics

- The issue arises within the user groups section of Umbraco, where pagination is absent.
- The problem becomes pronounced as the number of user groups increases, causing significant performance degradation.
- Currently observed in a project with approximately 500 groups, with expectations of further growth.

### Steps to reproduce

1. Create a substantial number of groups, e.g., 500 (can be done using the provided test controller or similar method).
2. Navigate to the users section within Umbraco.
3. Choose one of the following options:
Option 1: Click on "Groups" directly.
Option 2: Click on a user and then proceed to click on "Add Group."
[TestController.zip](https://github.com/umbraco/Umbraco-CMS/files/14474646/TestController.zip)

### Expected result / actual result

The user groups dashboard should display a limited number of groups per page (e.g., 25) and provide pagination controls at the bottom of the page, similar to other dashboard functionalities within Umbraco.

### PR DESCRIPTION
**Pull request by Yinzy00**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #15822

### Description
This pull request enhances the user group management system by implementing pagination functionality. The changes include adding pagination controls to both the user group dashboard and the user group picker, enabling smoother navigation and management of large datasets. This enhancement improves the overall user experience and ensures better performance when dealing with a significant number of user groups.

### How to test
1. Create atleast 25 groups (can be done using the provided test controller linked below or similar method).
2. Navigate to the users section within Umbraco.
3. Choose one of the following options:
Option 1: Click on "Groups" directly.
Option 2: Click on a user and then proceed to click on "Add Group."

[TestController.zip](https://github.com/umbraco/Umbraco-CMS/files/14474672/TestController.zip)

### CODE REVIEW

**Comment by mikecp** [comment]
Hello (from Belgium 😊) @Yinzy00,

Thank you for your pull request and for providing paging on User Groups. And congratulations on your first contribution to the Umbraco CMS 😁
Someone from the core collaborators team will have a look at it soon, but I already took the action of rebasing your PR to the `contrib `branch, which is the one that community pull requests should be applied to. The other branches are in fact reserved to HQ folks 😉

Cheers!

**Comment by Yinzy00** [comment]
Thanks @mikecp

**Comment by nul800sebastiaan** [comment]
Hey there @Yinzy00. I'm having a look at this and I will give you a heads up that we're no longer adding new features in v13 while we build on v14. 

That said, I understand the performance problem is an annoyance for you and it makes me wonder: how many user groups do you actually have and why do you need all of those? Perhaps there is a way to use granular permissions instead of this many user groups. 25 user groups sounds reasonable but you're the first person I know of that has over 500 groups, as mentioned in the linked issue. I can't help but feel that this is a bit of an edge case and there might be a better way.

**Comment by bielu** [comment]
@nul800sebastiaan I reported similar issue related to v7 or v8 (dont remember now, but i had over 100 groups) :) so that issues happens 😓

**Comment by nul800sebastiaan** [comment]
I'll close this one for now @Yinzy00. Please add some information on the issue report #15822 so we get an idea of what all those user groups are used for so we can figure out what the actual use case is before we start thinking about what the solution might need to be. 

Thanks for the attempt so far! 👍

**Comment by Yinzy00** [comment]
Hi @nul800sebastiaan, we're managing 250 sites within a single Umbraco instance for a corporation that operates multiple branches, each needing its own website. Each of these sites is categorized by one of three types: national, provincial, and city-level, to reflect the scope of each branch.
In addition to the site types, our setup includes three custom integrations for each site, designed to manage distinct datasets relevant to the branch it represents.
For user rights management, we've developed a detailed custom framework aimed at simplifying permission settings for site administrators, structured around user groups. This framework allows for granular control over access, enabling administrators to specify read/write permissions for both the website content and the integrations on a per-site basis.
Moreover, we aim to tailor access permissions based on the type of branch a site represents. For example, it should be possible to assign read-only access to a site of the provincial type while granting write access to a city-type site.
To achieve this, we envisage setting up:

## Site specific groups
- Group City 1 (x250 for the 250 sites)
- Group Province 1 (x all provinces)
- Group National

## City rights
- Group City Write Website
- Group City Read Website
- Group City Write Integration 1 (x 3 for the 3 integrations)
- Group City Read Integration 1 (x 3 for the 3 integrations)

## Province rights
- Group Province Read Website
- Group Province Write Website
- Group Province Read Integration 1 (x 3 for the 3 integrations)
- Group Province Write Integration 1 (x 3 for the 3 integrations)

## National rights
- Group National Read Website
- Group National Write Website
- Group National Read Integration 1 (x 3 for the 3 integrations)
- Group National Write Integration 1 (x 3 for the 3 integrations)
For example, a user associated with "City 1" and "Province 1" groups, also possessing "Province Read Website", "City Write"  and "City Write Integration 1" permissions, would have the ability to view the "Province 1" website without editing capabilities but could edit the "City 1" site and should be able to read & edit integration 1. for City 1.
This approach ensures a comprehensive and scalable access control system, offering precise management of permissions across all sites and their respective integrations.
Also good to know is that the custom integrations are custom dashboards that wil work with external api's and will show & hide funcionaltiy & data based on user groups.


If you have alternative solutions that don't involve extensive grouping, I'm open to hearing your suggestions.


And also, I think having pagination is never a bad thing? :smile:

**Pull request closed without merging**
