### PR TITLE
Add swiss languages as backoffice languages

### PR DESCRIPTION
**Pull request by marwaldv**
Add missing backoffice languages as properties etc. are translated via translation section (e.g. with "#Backoffice Settings"). At the moment the swiss languages always need to be added via the umbraco/Config folder.

### CODE REVIEW

**Comment by mikecp** [comment]
Thanks a lot @marwaldv for those new translations files 👍
Someone from the Core Collaborators team will have a look at your PR soon!

**Comment by iOvergaard** [comment]
@marwaldv Would you mind adding these to the new Backoffice as well (V14, V15)? 

The format has moved to JSON, but if you spin up a V13 Backoffice, you can look in the network tab and find a request to "localizedText" and essentially copy the body of that over. The new [Backoffice repository is found here](https://github.com/umbraco/Umbraco.CMS.Backoffice) and the localization files are found under `src/assets/lang`.

**Comment by nul800sebastiaan** [comment]
Hi there @marwaldv! Thanks again!

Just a hint: as you may know, this PR qualifies for [Umbraco's Hacktoberfest](https://umbraco.com/blog/join-us-for-umbraco-hacktoberfest-2024/) participation for which you can [earn rewards](https://cultiv.social/@sebastiaan/113311358180849090).
If you were to make 1 more contribution in the next few days, would be great to see your contributions qualify! You can do it.. 😉

**Comment by marwaldv** [comment]
> @marwaldv Would you mind adding these to the new Backoffice as well (V14, V15)?
> 
> The format has moved to JSON, but if you spin up a V13 Backoffice, you can look in the network tab and find a request to "localizedText" and essentially copy the body of that over. The new [Backoffice repository is found here](https://github.com/umbraco/Umbraco.CMS.Backoffice) and the localization files are found under `src/assets/lang`.

In which repositories would I need to create a pull request for V14 and V15?

**Comment by iOvergaard** [comment]
@marwaldv The [Umbraco.CMS.Backoffice](https://github.com/umbraco/Umbraco.CMS.Backoffice) repository is the place to create those. You should fork it and create a pull request to the `main` branch with the changes. Thanks so much for doing this!

**Comment by marwaldv** [comment]
> @marwaldv The [Umbraco.CMS.Backoffice](https://github.com/umbraco/Umbraco.CMS.Backoffice) repository is the place to create those. You should fork it and create a pull request to the `main` branch with the changes. Thanks so much for doing this!

@iOvergaard here you go: https://github.com/umbraco/Umbraco.CMS.Backoffice/pull/2503

**Review by iOvergaard — APPROVED** [review]

**Pull request merged**
