### PR TITLE
Grid Datatype- Delete Row Configuration - Changed the styles from warning to danger for the confirm delete button, added localization keys

### PR DESCRIPTION
**Pull request by poornimanayar**
In the grid datatype when you try to delete a row config, the overlay uses `warning` style all over. Since the application uses `danger` for deletes I have changed it to `danger` style. I have also added localization keys

**Before**
image

**After**
image

### CODE REVIEW

**Comment by poornimanayar** [comment]
@kjac ,

I completely agree there! I should have noted that in first place. Anyway, merge conflicts fixed and amends made :-)

Poornima

**Comment by kjac** [comment]
Hi @poornimanayar. Could I ask you to resolve the merge conflicts once again?

Please note that I have changed the base branch from `v8/dev` to `v8/contrib` for this PR. This means you'll have to pull `v8/contrib` and merge it into your PR branch to resolve the conflicts.

**Comment by poornimanayar** [comment]
Hmm,, very bizzare and I have no clue why this happens when i merge `v8/contrib` to my branches. I ll get this fixed

**Comment by poornimanayar** [comment]
closing this one and re-opened a new one in https://github.com/umbraco/Umbraco-CMS/pull/7399

**Pull request closed without merging**
