### PR TITLE
U4-11187 - Adds friendlier "Enable JavaScript" message

### PR DESCRIPTION
**Pull request by leekelleher**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org/issue/U4-11187

### Description

Adds friendlier "Enable JavaScript" message. Adapted from <https://enable-javascript.com/> guidelines.

Moves the `<noscript>` tags into the main body - within `#mainwrapper` (fullscreen overlay), so to allow the link to work.

Additional commits in this PR ... as I got a bit zealous with editing, then thought they'd been good to send over.

- Removed additional whitespace
- Removed the "type" attribute from the `<script>` tags (not required in HTML5)
- Switched to use the correct `BareMinimumServerVariablesScript` extension method

### CODE REVIEW

**Comment by leekelleher** [comment]
Thanks @dawoe! You're right, the link styling could be more distinctive.

I'll look to either update this PR or submit a new one if it gets merged in.

**Comment by leekelleher** [comment]
I've updated the PR with some basic style enhancements. Added a screenshot on the issue tracker: <http://issues.umbraco.org/issue/U4-11187#comment=67-47041>

**Comment by nul800sebastiaan** [comment]
Very nice indeed @leekelleher - thanks for the help! 👍

**Comment by leekelleher** [comment]
@nul800sebastiaan Heads up on the `temp8` branch, I noticed this PR got reverted, (it's still part of `dev-v7` branch).

From looking over the repo history, I'm suspecting that the huge "renormalize" commit 7a615133ff9de84ee667fb7794169af65e2b4d7a might have caused it? // @zpqrtbnk 

From my limited knowledge of Git, I believe that when the `temp8` merges in the latest `dev-v7` commits, the changeset (from 7a615133ff9de84ee667fb7794169af65e2b4d7a) has in something like this, (since there's no rename in Git)...

- **delete file "src/Umbraco.Web.UI/umbraco/Views/Default.cshtml"** (note lowercase "umbraco" folder)
- **create file "src/Umbraco.Web.UI/Umbraco/Views/Default.cshtml"** (note uppercase "Umbraco" folder)

So with the merge, Git would look at the change (from this PR) and go _ok, that file path has been deleted, let's discard it_, and then keep the recreated one (with the old content).

I think the "renormalize" may also have to happen on the `dev-v7` branch, to bring everything in order?

_Disclaimer, I'm not a lawyer - oops, I mean Git expert - take my advice with a pinch of salt._ ❤️

**Comment by Shazwazza** [comment]
@leekelleher i'll have a look now. We had an issue with merging recently because our repo is so large that we reached a git maximum for comparing files. We've didn't discover that till later so have updated our local Git settings and merging works better now so i think this comes down to a manual merge error.

Things we've learned:

* Git does not 'track' renames whatsoever
* When merging or adding files to the git index it will try to guess renames based on a hash of a comparable files, by default this comparison is set to 50% but you can tweak Git with certain commands to change that percentage
* When merging a ton of files, git will tell you that it's not going to do it's magical comparison so you won't get renames shown in your merge output .... there's a setting you can tweak for that `git config merge.renamelimit 3000` (since the limit we exceeded was 2500 or something)

**Comment by Shazwazza** [comment]
Have merged that up to v8 in rev: 9d7519d591056967386ce2a6a5314c703723c6f2 however i've had to tweak it because our styling and html has been changed in v8. I've had to add a noscript trick hide the mainwrapper but then show it with JS if it's enabled, otherwise the way it was means that the noscript area is inside the newer grey background which is a bit ugly. Here's what it looks like in v8

image

**Comment by leekelleher** [comment]
Cool, thanks @Shazwazza!

**Pull request merged**
