### PR TITLE
U4-11462 Error when using Simple Injector - 'The Tree controller is missing the Umbraco.Web.Trees.TreeAttribute attribute'

### PR DESCRIPTION
**Pull request by nul800sebastiaan**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org/issue/U4-11462

### Description

This error led me do some investigation. We seem to really need the `[Tree]` attribute on a `TreeController` class so we could discover it and populate the tree. 

However, the `[Tree]` attribute is limited to putting the tree in 1 single section, which is why we had a `DictionaryTreeBaseController` class and derived from that `SettingsDictionaryTreeController` and `TranslationDictionaryTreeController` so we could move it between two sections.

In this PR I've combined those two subclasses, leaving us with a single class. After that we immediately get the error that Simple Injector also came up with: `The Tree controller is missing the Umbraco.Web.Trees.TreeAttribute attribute`. While loading trees, we really want to get information from that pesky attribute that we can't use.

So.. in order to fix this, and I'm not sure if this is the correct approach, I now fall back to the trees.config file if the attribute is not found. This still gives us all the information we need to populate the tree and as an added bonus we can now put the tree in ANY section (even Content, crazy)!

Happy to do updates after a review, I might have just hacked the planet here, but.. it works 😉

### CODE REVIEW

**Comment by Shazwazza** [comment]
The reason you are getting that error is because your tree is missing the attribute entirely. If you add this back to the `DictionaryTreeController` you wont get this error anymore `[Tree(Constants.Applications.Settings, Constants.Trees.Dictionary, null, sortOrder: 3)]`

The GetTreeAttribute isn't used for anything apart from:
* Updated the trees.config if the type isn't registered yet
* Getting the tree name/alias

So it's not used for anything regarding sections. If you add the tree attribute back the problem should be fixed.

**Comment by nul800sebastiaan** [comment]
@Shazwazza Then I can't move the tree to the Translation section or anywhere else any more. 😢

**Comment by Shazwazza** [comment]
Yes you can the only thing this attribute does regarding the section, is when the config doesn't exist for this tree, it will update the config, if the config exists for the tree, it does nothing

**Comment by Shazwazza** [comment]
Here's where that code happens https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Services/ApplicationTreeService.cs#L86 , so if the tree isn't registered in config, it will use the section in the attribute, else it doesn't do anything

**Comment by nul800sebastiaan** [comment]
Amazing! Tried it out, totally works. Thanks again!

**Comment by danlister** [comment]
😄 Awesome stuff guys!

**Pull request closed without merging**
