### PR TITLE
Temp/Missing-swedish-translations

### PR DESCRIPTION
**Pull request by Adolfi**
Found some missing swedish translations. 
Cheers!

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @Adolfi ,

Thank you for your work. We shall get back to you if anything else is needed.

Poornima

**Comment by Adolfi** [comment]
@poornimanayar Any update on this one? Our of curiosity, how do you validate these typ of language specific PR:s? Do you google translate it or do you have a contact in each language?

**Comment by poornimanayar** [comment]
Hi @Adolfi ,

Hope you are well. And thank you for being patient. We haven't quite cleared the Hacktoberfest backlog yet. I shall review this and get back to you. And yes, Google Translate would be the way :-)

Poornima

**Comment by poornimanayar** [comment]
@Adolfi ,

While you are it you might want to address these as well?

image

Poornima

**Comment by poornimanayar** [comment]
And a few here as well? Do you think you can help? I have verified the rest, its all good :-)

image

Poornima

**Comment by Adolfi** [comment]
No need to. Info and Media are the same in Swedish! 👍🏻

**Comment by Adolfi** [comment]
Ah, there are a few there under the User access settings I could have a look at.
Or if you have approved these once you could merge this one in and I can submit a new PR with the User translations beginning next week?
Would that be fine?

**Comment by poornimanayar** [comment]
Hahaha, sorry about that. I should have tried it on Translate myself before I reported. Let me know whether the second one is okay and I can approve this. :-)

**Comment by Adolfi** [comment]
Haha I think we are replying to each other at the same time. Did you see my last comment about merging this one and I can create a new PR next week?

**Comment by poornimanayar** [comment]
Hi @Adolfi ,

You can submit a new PR no problem. But it would be better if you do it here as then, it can all go in together. I dont do the merge but will bring this to @nul800sebastiaan 's attention :-) 

Poornima

**Comment by Adolfi** [comment]
Ok. I can submit it to this PR. Just thought it would be nice to close this one while I had your attention and you've approved all the other once. But L'll add a few more then next week.
Thanks

**Comment by poornimanayar** [comment]
No worries at all. I ll make sure I will look at your amends :-)

Poornima

**Comment by nul800sebastiaan** [comment]
The backlog is long, just add more commits to this one @Adolfi 😅

**Comment by Adolfi** [comment]
@nul800sebastiaan hehe! :D

**Comment by Adolfi** [comment]
INCOMING!!!!! 
image

Wow, the User section was really section that was missing some attention in the Swedish translations. :) I hope I found them all, the translations are really messy to compare since they are not sorted equal. I might go build some sort of console tool to automaticlly sort and diff translation files in Umbraco, but that's for another day. :)

Happy Google Translating! :)

**Comment by poornimanayar** [comment]
Merged in now! Thanks once again 👍

**Pull request merged**
