### PR TITLE
Properly HTML encode text in helper methods

### PR DESCRIPTION
**Pull request by ronaldbarendse**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6275

### Description
This PR makes sure most helper methods accepting `string` parameters and returning `IHtmlString` properly HTML encode the text. As described by @Shazwazza in https://github.com/umbraco/Umbraco-CMS/issues/6275#issuecomment-532075299, it also adds documentation comments to let people know this is done (so you don't double-encode the text).

### CODE REVIEW

**Comment by ronaldbarendse** [comment]
A lot of the helper methods on `IndexedArrayItem` are redundant, e.g. all the `IsNot*()` methods (just negate the return value or switch the parameters `valueIfTrue` and `valueIfFalse`) and the overloads containing only the `valueIfTrue` parameter (these could be removed by adding a default value to `valueIfFalse`).

Just having the `IsFirst()`, `IsLast()`, `IsIndex()`, `IsModZero()`, `IsEven()` and maybe even `IsOdd()` with the boolean return value and another with both optional parameters `valueIfTrue` and `valueIfFalse` set to `null` would be enough. And if these changes would be implemented, the return type could be changed from `HtmlString` (which should be `IHtmlString` to begin with) to `string` and therefore not require HTML encoding the values anymore.

For now I've kept all the existing method signatures in this PR, so we don't introduce binary breaking changes, only functional ones (as described in the already linked [comment](https://github.com/umbraco/Umbraco-CMS/issues/6275#issuecomment-532075299)).

**Comment by nul800sebastiaan** [comment]
I am still not sure if we can just switch this up on people without causing some serious pain. Maybe @Shazwazza will have some more input on this one.

**Comment by ronaldbarendse** [comment]
@nul800sebastiaan The linked comment already contains @Shazwazza's input and the worst thing that could happen is double-encoding the text... This is not so serious compared to the potential XXS issues (if you're not manually encoding the text before passing it into these methods) and fixing would mean only removing your own call to `HttpUtility.HtmlEncode()`.

**Comment by ronaldbarendse** [comment]
Just found out `@Html.Wrap()` also doesn't encode the `innerText` value!

With this one it was a little harder to see why, as it first creates an `HtmlTagWrapperTextNode`:

https://github.com/umbraco/Umbraco-CMS/blob/06b136fdf66ae685c8985af90ac075535e635e74/src/Umbraco.Web/HtmlHelperRenderExtensions.cs#L807-L823

And this instance is later written to an output stream without HTML encoding the text:

https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web/Mvc/HtmlTagWrapperTextNode.cs#L5-L17

**Comment by nul800sebastiaan** [comment]
@ronaldbarendse What does your last comment mean for this PR? I am not sure how it's related?

**Comment by ronaldbarendse** [comment]
It means I've found another helper method (`Html.Wrap()`) that doesn't properly HTML encode text, so that should also be fixed (either in this PR or as a new one).

**Comment by nul800sebastiaan** [comment]
Thanks! I'll have to ask the team if we want to make all these breaking changes.

One thing we can't do is mark methods as obsolete without having an alternative for them. Maybe to you they don't make sense and I know we're probably violating the c# programming bible, but these methods are there, they're convenience methods we like to provide. 

In any case, I need to get someone at HQ to figure out if we want these changes and when and how we can make it clear that everybody will need to start cleaning up their views after upgrade. For example, on Umbraco Cloud with automatic upgrades we'll just straight-up be breaking people's views if we roll this out, so I am not very hopeful we can do them in this way.

**Comment by nul800sebastiaan** [comment]
Ah, I just realized that we don't auto-upgrade minor releases on Cloud, so it's opt-in and they need to test on a separate environment, that makes it a lot lower in impact.

**Comment by ronaldbarendse** [comment]
As @Shazwazza commented in the linked issue https://github.com/umbraco/Umbraco-CMS/issues/6275#issuecomment-532075299 (referenced in this PR), fixing potential XSS issues is more important then double-encoding text (if you use something like `Model.IsDescendant(child, HttpUtility.HtmlEncode(someValue))`) or encoding HTML (if you use these methods like `Html.Raw()`, e.g. expecting the text to be rendered as HTML).

This should be released as breaking change in a new minor, with the advise to check custom code/views that uses the methods listed in the issue.

Regarding the obsoleted methods: you can still use them and the alternative is to use simple conditionals, e.g. instead of `Html.If(Model.SomePropertyToCheck, "Render this text when the property is true")`, write:
```
@if (Model.SomePropertyToCheck) {
   <text>Render this text when the property is true</text>
}
```
These convenience methods aren't documented well and are completely custom to Umbraco, so I don't see any real advantage to having them compared to the standard, generic, platform independent Razor code.

**Comment by nul800sebastiaan** [comment]
Alright, I've discussed this some more and it's good to get this encoding issue out of the way for once and for all. 

In the future, I'd like to ask you not to move all the methods around like you did with `BeginUmbracoForm`. Not only is it impossible for me to see what is changed, it's also not necesary.(yes, I know it looks more pleasing if they're in the right order 🙈). After spending time re-ordering I could finally see that you changed the value for the `htmlAttributes` parameter from `new Dictionary<string, object>()` to `null`. However, those method calls eventually propagate to this code: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/HtmlHelperRenderExtensions.cs#L746 and there is no null check here, so it will fail. I reverted all of those changes for now.

I also turned all the `Obsolete`s into `TODO`s. For a bit of background, those helper methods were once made to help people inexperienced with MVC / Razor to move from XSLT to Razor more easily. They're definitely legacy now and should be moved or removed. They're Friendly, in other words, and yes, they're not very nice where they are right now. The joys of legacy! 
We never want to `Obsolete` something without having an alternative available, that's just confusing and not helpful. So I've turned them into `TODO`s, I don't know if we want to keep there around for vNext but if we do it might be good to move their logic to `HtmlHelper` and then they can be `Obsolete`d.

Sorry it took quite a while to get this reviewed, but we're finally there! Thanks for all the work on this!

I will mark this as a breaking change since people might have been relying on the previous behavior of not encoding the HTML.

As @Shazwazza tweeted (I believe related to this), XKCD made an excellent cartoon for these types of breaking changes.. 😅 https://twitter.com/Shazwazza/status/1271005573060849665

**Pull request merged**
