### PR TITLE
U4-5683 Migrate Dictionary tree & editor to angular

### PR DESCRIPTION
**Pull request by dawoe**
PR for Migrate Dictionary http://issues.umbraco.org/issue/U4-5683

### CODE REVIEW

**Comment by dawoe** [comment]
This is still in Progres by they way.... still need to create the edit view and clean up the old tree

**Comment by dawoe** [comment]
Everything is migrated..old tree still needs to get cleaned up

**Comment by nul800sebastiaan** [comment]
Thanks @dawoe. just want to let you know we've seen this massive update and we'll get back to you soon. Thanks very much for the effort so far! #h5yr

**Comment by dawoe** [comment]
Hi @nul800sebastiaan 

Any news on this one ?

Dave

**Comment by dawoe** [comment]
Any news on this one ?

**Comment by nul800sebastiaan** [comment]
This is amazing Dave, I've spent the day looking at this one and making some small changes to the coding style aaaaannddd...... with my additional changes we can now move the tree to the translation section too! 🎉 🎉 

AWESOME job mate and very sorry for the delay!!
7.11 is going to be a super fun release thanks to you!

**Comment by dampee** [comment]
Awesome!

**Comment by marcemarc** [comment]
Wowsers, let us remember this day for many years to come!

**Pull request merged**
