### PR TITLE
V8: Update backoffice icon fonts to use svgs

### PR DESCRIPTION
**Pull request by MMasey**
**Summary**

This PR updates almost all of the icons using the icon font found throughout the backoffice with SVGs. Each icon is now it's own svg file with the following naming convention `icon-[name]`. I have created an IconController that currently pointed to a folder containing these icons and makes them usable via the an angular directive call `umb-icon`. This not only improves accessibility, but also make it much easier to customise the icons available in the back office.

This is a pretty big PR and is currently still a work in progress, so i'd really appreciate some input/feedback whether it's around the coding style, tackling the SVG sanitization (I have a potential solution but don't just want to throw it in there) or just general questions. I think it's almost there but I may be wrong.

I've put a fair amount of detail in the issue https://github.com/umbraco/Umbraco-CMS/issues/3560 so I would recommend having a read through to get up to speed. 

I'm creating this as a draft PR for the time being as I don't think it's ready to be properly submitted yet.

Many thanks

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @MMasey 

Thanks for this work - can see it's still a work in progress so give us a nudge when you'd like us to get stuck in.

Em

**Comment by MMasey** [comment]
Hey @emmaburstow I'd really like to get some feedback on this from some people in HQ. I think the main thing that is left is the SVG santization which I could add in, but it would add some dependencies to the core which I didn't just want to put in without running it by someone 😜 Then it also probably needs a fair amount of testing.

Thanks

**Comment by nul800sebastiaan** [comment]
Hey @MMasey ! We had a bit of a chat about this at HQ and of course we love the changes, it's going to be great. One big concern we had here is that all of these SVG files are going to be downloaded 1 by 1 during at least the first request to the icon picker (for example). Would it be possible to combine them into 1 big file that gets downloaded once and nicely cached?

That immediately adds a bit of complexity of course, ideally it would be possible to add a few more SVG files into a folder and they'd be bundled into that one file too somehow. Got any suggestions on how we could make that work?

Other than that, we'll need to consider backwards compatibility, which I think you have done already but could you describe that a little further? I think this is both important for existing site that get upgraded and for package developers who are already using the font icons.

**Comment by MMasey** [comment]
Hey @nul800sebastiaan, thanks for getting back to me on this 🙂 

In understand the concerns with downloaded each icon one by one. The reason why it is currently done this way is because in order to take advantage of being able to manipulate the svgs via CSS, they need to be inline. This can be achieved in two ways. 

1. A huge SVG sprite sheet could be added into the body of the page just below the opening `<body>` tag, and then you can do something like `<svg><use xlink:href="#whatever" /></svg>`  when you want to use an icon. Due to the number of SVGs that would need to be included in the spritesheet, this isn't a good solution as it would seriously bloat the HTML on the page.
2. Request each icon individually only when they are required and place them inline. This is what the directive currently does. Whenever an icon is requested, it also caches it so that it doesn't need to make the request again. When the icon picker is opened, there is a separate API call that is used to download all of the available icons so in theory this could done as part of the initial load event for the backoffice instead so that all the icons are available once it has loaded, but then once it would mean pulling down a large amount of data. My thought process behind this was that a content editor wont require all of the possible icons that are available, so why not just give them the ones they need.

The controller that handles getting the icons can be found at https://github.com/umbraco/Umbraco-CMS/blob/85fce5f72ce084688a17eac10244964b8726e207/src/Umbraco.Web/Editors/IconController.cs#L25-L113

To break down what it does, it searches the folder that contains the icon. 

- `GetIcon` will search for an icon with a specific name in the folder location and return it's file contents in a response model called `IconModel` which has a field for the icon name, and the svg string.
- `GetAllIcons` will get the name of each icon in the icons folder, the will get file contents for each svg icon and will return an `List<IconModel>` containing all the information for each icon.

The JS that handles the icon requesting and caching can be found here  https://github.com/umbraco/Umbraco-CMS/blob/85fce5f72ce084688a17eac10244964b8726e207/src/Umbraco.Web.UI.Client/src/common/services/iconhelper.service.js#L236-L319

In regards to backwards compatibility, I haven't removed any of the existing icon support so any packaged that still used the `<i class="icon"/>` syntax shouldn't have any problems. That said, I think these is still some older legacy code that could be deleted/cleaned up.

I'd be happy to catch up on a call to discuss this further if it would be easier. Cheers

**Comment by MMasey** [comment]
I''m going to close this PR in favour of #5606

Thanks

**Pull request closed without merging**
