### PR TITLE
Fixes issue with OrderByDescending generating invalid SQL

### PR DESCRIPTION
**Pull request by abjerner**
This issue seems to have existed for some time, as it affects Umbraco 9.0.0 and 9.1.0, but is also present in [v8/contrib](https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Core/Persistence/NPocoSqlExtensions.cs#L318).

Say for my redirects package, I have a `RedirectDto` for the communication with the database. I can order by two fields in ascending order like below using Umbraco's `OrderBy` extension method:

```csharp
var sql = scope.SqlContext
    .Sql()
    .Select<RedirectDto>()
    .From<RedirectDto>()
    .OrderBy<RedirectDto>(x => x.Path, x => x.QueryString);
```

The part of the query for the ORDER statement then looks like this:

```sql
ORDER BY [SkybrudRedirects].[Url], [SkybrudRedirects].[QueryString]
```

Umbraco has a similar `OrderByDescending` extension method. So with this method, the following code:

```csharp
var sql = scope.SqlContext
    .Sql()
    .Select<RedirectDto>()
    .From<RedirectDto>()
    .OrderByDescending<RedirectDto>(x => x.Path, x => x.QueryString);
```

generates the following SQL:

```sql
ORDER BY System.Linq.Enumerable+SelectArrayIterator`2[System.String,System.String]
```

I had a look at the source code, and the `sql.OrderBy(columns.Select(x => x + " DESC"))` line is making a call to a method in NPoco which has a `params object[]` parameter that isn't compatible with an `IEnumerable<string>` value.

Changing the line to `sql.OrderByDescending(columns)` uses a method overload in Umbraco's `NPocoSqlExtensions` class which generates the correct SQL:

```sql
ORDER BY [SkybrudRedirects].[Url] DESC, [SkybrudRedirects].[QueryString] DESC
```

### CODE REVIEW

**Review by mikecp — COMMENTED** [review]
Nice catch @abjerner ! 👍

Maybe a suggestion: in order to keep things consistent I would also update the "single field" method just above it, on line 255 and also use the same extension method:

`return sql.OrderByDescending(sql.SqlContext.SqlSyntax.GetFieldName(field));`

Since that method accepts a last parameter `params[] string`, it works with both single or list.

What do you think? 

And also: would you mind making the same fix for the v8/contrib branch 😁?

**Comment by nul800sebastiaan** [comment]
@abjerner As @mikecp suggests, would be good to update that as well. And unfortunately, the window for v8 PRs is now closed 😅 Can you help get this one updated? 👍

**Comment by abjerner** [comment]
I've missed @mikecp's reply - probably because I was on vacation at the time 🤔 

I'll try if I can find some time to have another look 😉

**Comment by mikecp** [comment]
Hey @abjerner, if you don't have time I can perform the change myself if you want. Just let me know 😉

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Hi @abjerner , I've made the update so we can still merge for this month   😁
Thanks again for spotting and solving this problem 👍

**Pull request merged**
