### PR TITLE
Corrected all the miss spellings of "Separate" - Issue: 4060

### PR DESCRIPTION
**Pull request by readingdancer**
### Prerequisites

Fixes: https://github.com/umbraco/Umbraco-CMS/issues/4060

### Description

These spelling mistakes have existed in the code base for years, I think it's a good time to fix them before the next major version is released!

Seperator -> Separator
Seperate -> Separate

### CODE REVIEW

**Comment by abjerner** [comment]
Hi Chris,

Thanks a lot for correcting this 👍 

I or someone else from the PR team will have a look a this shortly. As you may know, we strive to review new PRs within 14 days - but hopefully we can do this sooner 😉 

I do have one concern about your changes. As there may be packages or custom code that uses the old CSS class names with the wrong spelling, I think it would be best to add new classes (opposed to replacing the old ones) with the correct spelling. Eg. rather than replacing 
`.umb-breadcrumbs__seperator {` with `.umb-breadcrumbs__separator {`, we could allow both selectors like `.umb-breadcrumbs__seperator {`, `.umb-breadcrumbs__separator {`.

Anders, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by abjerner** [comment]
But seeing as this targets the `temp8` branch, the "breaking changes" may me irrelevant ;)

**Comment by readingdancer** [comment]
Hi Anders,
This is why I just targeted the v8 branch, I think there will be enough other breaking changes for package devs to deal with, IMHO, correcting a spelling mistake in their code shouldn't be a big issue if it arises at all, if we added secondary classes when would we ever get rid of the old ones?
Cheers,
Chris

**Comment by abjerner** [comment]
@readingdancer I was a bit too quick to write, so I hadn't seen you targeted `temp8` when I made my first reply. I don't think it would be a problem for `temp8`, but I'll make sure to test that ;)

**Pull request merged**
