### PR TITLE
Fix button styling in block list & block grid overlay

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
### Description
Update `blockgrid.blockconfiguration.overlay.less` & `blocklist.blockconfiguration.overlay.less` so that the text in the button is visible. Use variables for color in the buttons instead of hardcoded value. 

Before: 
image

After: 
image

### CODE REVIEW

**Comment by mikecp** [comment]
Thanks for this update @erikjanwestendorp !

Someone from the collabs team will have a look at it soon!

**Comment by bjarnef** [comment]
Actually I suggested this a long time ago, but it didn't seem HQ wanted the text to be visible, but more like a placeholder button: https://github.com/umbraco/Umbraco-CMS/pull/8686

But I think it is kinda inconsistent eith other pickers - also that these have rounded corners, but not elsewhere in the UI.

**Comment by erikjanwestendorp** [comment]
@bjarnef Thanks for your comment and the reference to your PR! IMHO it's weird that the text is not visible indeed.. 🙈 I was already surprised that this had not been resolved before, but now I understand why. Let's see what happens now 😛.

**Comment by nielslyngsoe** [comment]
@bjarnef @erikjanwestendorp First and foremost thanks for sharing opinions. I just wanted to let you know that we changed the approach to this with UI Library. Meaning in v.14 this text would be visible. :-) So it's good to make this change now.

**Comment by georgebid** [comment]
Hey @erikjanwestendorp sorry for the delay on this one, but all looks good from my testing so I have gone ahead and merged this in. Thanks again for your PR! 😸

**Pull request merged**
