### PR TITLE
Access document, media and member types by guid and udi

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
This PR enable the option to access document, media and member types by guid and udi and not only by id.

At the moment this it already possible for content, media and member nodes (and in Umbraco Forms as I remember) ... and also for datatypes and macros https://github.com/umbraco/Umbraco-CMS/pull/6847

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hiya @bjarnef,

thanks for the work here. It'll be really useful to be able to access document types by udi and guid! We'll take a look and let you know if we need anything.

Emma

**Comment by bjarnef** [comment]
@nul800sebastiaan do you see any issues with this and similar PRs to request document by `Guid` and `Udi`?

**Comment by bjarnef** [comment]
@emmaburstow it seems these PR's are a bit forgotten compared to new incoming PR's. Anything you need from me regarding these "access nodes from guid and udi" PR's? 😊🦄

**Comment by nul800sebastiaan** [comment]
Lovely work @bjarnef - happy to merge!

**Comment by ChrisMullaley** [comment]
I'm not sure if this is the right place to mention this but we are looking at upgrading or Umbraco version and hit an issue relating to this change.

We have client code that was calling ContentTypeController.GetById(int id). Those calls started failing after the update and I tracked it down to the fact that our client code adds a trailing slash to the URL. That was preventing the custom action selector from finding the right action method.

We've fixed it in the client code but it might be useful for others to know, It also means that there is a small inconsistency in how URLs are resolved between standard controller actions and these overloaded ones.

**Pull request merged**
