### PR TITLE
v8: Fix general localization

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
I have fixed a few localization e.g. the new tree groups in v8 - the word `Templating` is not easy to translate directly to Danish. Some suggestion could be `Design` or `Layout`. Maybe @kjac og @hartvig have some suggestions?

I have also localize the close button in help drawer and the text on member groups which haven't any properties.

image

### CODE REVIEW

**Comment by bjarnef** [comment]
@abjerner yes I thought about using `umb-empty state` but it is more used when there is no content. In this case the member group has content, at least the id, but at the moment not available to add more properties (maybe that would be possible some day).

Furthermore it felt a bit more consistent with users sections and member to use `umb-box`. If member groups do have a guid, we could also show the id + guid as under a member.

**Comment by abjerner** [comment]
@bjarnef yes, I think something like your first screenshot along with the **General** box could work really well 😉

**Comment by bjarnef** [comment]
@abjerner I have adjusted it a bit and it now looks like this.

image

Maybe it also makes sense to have content apps under member and member groups, but I think it needs some discussion at Umbraco HQ first.

image

**Comment by kjac** [comment]
@bjarnef bit late to the party here but how about using both words? *Design og layout* as the Danish translation for *Templating*?

**Comment by bjarnef** [comment]
@kjac I tried updating this, but it seems the ordering now are based on the name.

I think it is important the order is the same independent of the language.

image

**Comment by bjarnef** [comment]
I also noticed a missing translation when saving a member group.

image

**Comment by abjerner** [comment]
@bjarnef thanks - looks good with the new changes 👍 

I'll try having another look at it, but it should be a walk in the park approving it now 😉 

Regarding the missing translation for the notifications, I think I actually created a PR for that in v7 (or maybe I just thought about doing it). So perhaps there's something in the v7 branch se can use? Feel free to add it as part of this PR, or create a new PR - whatever you think is easiest ;)

**Comment by bjarnef** [comment]
@abjerner it seems it used a incorrect localization key in MemberGroupController. I have fixed it in https://github.com/umbraco/Umbraco-CMS/pull/4274/commits/28b1568e0f04f4060cc1ab7aa6ad9a14122cf20e

image

**Comment by kjac** [comment]
> @kjac I tried updating this, but it seems the ordering now are based on the name.
> 
> I think it is important the order is the same independent of the language.
> 

@bjarnef sounds like that's a new issue. Make sure you raise it so it can be dealt with 👍

**Pull request merged**
