### PR TITLE
Updated all 404 and 500 responses to use problem details model

### PR DESCRIPTION
**Pull request by bergmania**
Updated all 404 and 500 responses to use problem details model

# Test
- Ensure swagger now show correct model for 404
- Smoke test apis that can return 404.

### CODE REVIEW

**Review by iOvergaard — COMMENTED** [review]
Looks like it doesn't show up in Swagger for GET document item:
image

Also not for public-access:
image

Nor for domains:
image

**Comment by iOvergaard** [comment]
On a related note, the "400" error for `PUT document/{id}` does not show the ProblemDetails object, but the 404 now does:
image

**Comment by iOvergaard** [comment]
GET & POST for indexers do not indicate that a 404 can be thrown, but I think that is the case?

image

**Comment by iOvergaard** [comment]
Partial views snippets does not indicate a 404:

image

**Comment by iOvergaard** [comment]
Redirect management GET & DELETE do not indicate a 404:

image

**Comment by iOvergaard** [comment]
2 out of 3 relation type controllers do not indicate 404:

image

**Comment by iOvergaard** [comment]
These tracked reference controllers do not indicate 404:

image

**Comment by iOvergaard** [comment]
I clicked through most of the controllers that take in some kind of {id} and this is what I found. Most of the controllers indicated 404 correctly 🙌

**Comment by bergmania** [comment]
- Items endpoints to not seem to return 404's. you can add many Ids and all that exist are returned.
- Public access endpoint was missing
- Domains also just return an empty list. But we could argue this should return 404.
- Redirects can't but we can argue it should, even that it is an extra check for us.
- Relations, only one of them can actually, but we could argue the other also should return 404.
- Tracked references can't return 404 - Still is a bit special as we dont really know what type the key is, we only know we need to look into a table

**Review by iOvergaard — APPROVED** [review]
LGTM

**Pull request merged**
