### PR TITLE
V8 - Remove dashboards.config - use CollectionBuilder

### PR DESCRIPTION
**Pull request by warrenbuckley**
Refactor of dashboards  …
* Remove dashboards from Configs().Dashboards
* Remove dashboard.config XML file & associated code reading from XML
* Load Dashboards from TypeLoader into a CollectionBuilder
* Load merge/concat C# Dashboard Types with package.manifest
* Add buildercolletion to an extension method on Composition

### CODE REVIEW

**Comment by warrenbuckley** [comment]
## Unit Test
The current unit test class `DashboardSettingsTests.cs` I have commented out for now, but this was mostly XML sanity checking when I look at this.

Should I be unit testing the existence/count of our C# types we ship with core or ...?!

**Comment by warrenbuckley** [comment]
@bergmania has done a review of this in a PR with code changes/suggestions
https://github.com/umbraco/Umbraco-CMS/pull/4248

**Comment by zpqrtbnk** [comment]
(which has been merged)

**Comment by zpqrtbnk** [comment]
Hey have pushed a commit to the dashboards tree - cleaning up the serialization - basically serializing a different thing (a model for views), so no need for attributes and hacks - have also renamed things, `IDashboardSection` came from the configuration section, now is `IDashboard` since we don't have sections anymore etc - feel free to review & comment, apart from that I'm happy with it and OK to merge

**Comment by warrenbuckley** [comment]
Happy - lets merge in then :)

**Pull request merged**
