### PR TITLE
Add IContextCache to deploy connectors

### PR DESCRIPTION
**Pull request by ronaldbarendse**
This adds the `IContextCache` that was added to Deploy 4.7.0, 9.5.0 and 10.1.0 (see PR https://github.com/umbraco/Umbraco-Deploy/pull/673) and updates the connector interfaces that are part of the CMS to use this.

These changes are backwards compatible for callers, but breaking for the implementations to ensure the `IContextCache` overload is always used. Updating implementations to be compatible again is as simple as adding the new `IContextCache contextCache` parameter, as the previous (now obsolete) method will then fallback to the interface default implementation using `PassThroughCache.Instance`.

### CODE REVIEW

**Review by AndyButland — APPROVED** [review]
Looks good to me.  Approving, but just one thing to consider... do we we want the implementations for `IContextCache` in core?  I can see you need to have `PassThroughCache`, but the other two might be better in Deploy, so we can more easily make changes to them should we ever need to.

You'll need to liaise too please with @bergmania about getting these changes into CMS, as we'll need to put out an RC2 in order to be able to take a dependency on them.

**Comment by bergmania** [comment]
I agree with Andy, about moving the deploy specific implementations to deploy.

**Comment by leekelleher** [comment]
Hiya. I've finally got around to testing my Contentment package with Umbraco 11.0.0-rc5, and hit a breaking-change with the `.ToArtifact` method.

To reproduce, from the CLI, I installed a fresh Umbraco 11.0.0-rc5 site, ran the installer, backoffice loaded up, all good, then stopped the website and added the Contentment package...

- `dotnet add package Our.Umbraco.Community.Contentment`
- `dotnet run`

Then I got the following error...

<details>
<summary>Stack trace from <code>dotnet run</code> after adding Contentment to an Umbraco 11.0.0-rc5 instance</summary>

```
Unhandled exception. System.Reflection.ReflectionTypeLoadException: Could not load all types from "Umbraco.Community.Contentment, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null" due to LoaderExceptions, skipping:
. System.TypeLoadException on Umbraco.Community.Contentment.DataEditors.EditorNotesConfigurationConnector: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.EditorNotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Umbraco.Community.Contentment.DataEditors.NotesConfigurationConnector: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.NotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
. System.TypeLoadException on Umbraco.Community.Contentment.DataEditors.RenderMacroConfigurationConnector: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.RenderMacroConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.EditorNotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.NotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.RenderMacroConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Umbraco.Cms.Core.Composing.TypeFinder.GetTypesWithFormattedException(Assembly a)
   at Umbraco.Cms.Core.Composing.TypeFinder.GetClassesWithBaseType(Type baseType, IEnumerable`1 assemblies, Boolean onlyConcreteClasses, Func`2 additionalFilter)
   at Umbraco.Cms.Core.Composing.TypeFinder.FindClassesOfType(Type assignTypeFrom, IEnumerable`1 assemblies, Boolean onlyConcreteClasses)
   at Umbraco.Extensions.TypeFinderExtensions.FindClassesOfType[T](ITypeFinder typeFinder, IEnumerable`1 assemblies, Boolean onlyConcreteClasses)
   at Umbraco.Cms.Core.Composing.TypeLoader.<>c__DisplayClass21_0`1.<GetTypes>b__0()
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilderExtensions.AddAllCoreCollectionBuilders(IUmbracoBuilder builder)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder.AddCoreServices()
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder..ctor(IServiceCollection services, IConfiguration config, TypeLoader typeLoader, ILoggerFactory loggerFactory, IProfiler profiler, AppCaches appCaches, IHostingEnvironment hostingEnvironment)
   at Umbraco.Extensions.UmbracoBuilderExtensions.AddUmbraco(IServiceCollection services, IWebHostEnvironment webHostEnvironment, IConfiguration config)
   at Umbraco11rc5.Startup.ConfigureServices(IServiceCollection services) in C:\VCS\Umbraco\Development\Umbraco11rc5\Startup.cs:line 32
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass14_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Umbraco.Cms.Web.Common.Hosting.UmbracoHostBuilderDecorator.Build()
   at Umbraco11rc5.Program.Main(String[] args) in C:\VCS\Umbraco\Development\Umbraco11rc5\Program.cs:line 6
System.TypeLoadException: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.EditorNotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.NotesConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ToArtifact' in type 'Umbraco.Community.Contentment.DataEditors.RenderMacroConfigurationConnector' from assembly 'Umbraco.Community.Contentment, Version=4.2.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
```

</details>

From the changes on this PR, I can see that the `Obsolete` attribute has been added...

https://github.com/umbraco/Umbraco-CMS/pull/13287/files#diff-27975a4ec9d6d75aaaffce8ed8b4e4259989327ecce6df8cb8a032064400c9f1R30

...so I'm unsure why I'd get an unhandled exception on building against the Contentment package.

For reference, here's a link to the source of one of the `ToArtifact` calls: https://github.com/leekelleher/umbraco-contentment/blob/4.2.0/src/Umbraco.Community.Contentment/DataEditors/EditorNotes/EditorNotesConfigurationConnector.cs#L69

**Comment by bergmania** [comment]
Hi @leekelleher.. We'll take a look.. Thanks for reporting

**Comment by leekelleher** [comment]
Thanks @bergmania. I realized later that the `IDataTypeConfigurationConnector` interface has the new method points, thus breaking the implementation, (sounds obvious now 🤦). 😅

**Comment by ronaldbarendse** [comment]
@leekelleher This PR indeed contains breaking changes for the implementations listed below, so you'll need to update these to be compatible for Umbraco 11.

Since Contentment is multi-targeting Umbraco based on .NET versions, this would mean you can't target .NET 7 against anything lower than Umbraco 11. This in turn means Umbraco 10 projects with Contentment installed can't upgrade their target framework to .NET 7 (similar to how Umbraco 9 projects currently can't upgrade to .NET 6 because of the minimum Umbraco 10 dependency that's on the Contentment .NET 6 build). Since Umbraco aligns with the .NET LTS versions, it doesn't make much sense to upgrade .NET versions without upgrading Umbraco, so this should be fine (for now, as Umbraco 12 will still target .NET 7, because .NET 8 has a projected release date of 2023-11, aligning with Umbraco 13 LTS).

## Breaking changes
New method overloads were added to these interfaces:
- `IDataTypeConfigurationConnector`
  - `string? ToArtifact(IDataType dataType, ICollection<ArtifactDependency> dependencies, IContextCache contextCache)`
  - `object? FromArtifact(IDataType dataType, string? configuration, IContextCache contextCache)`
- `IServiceConnector`
  - `IArtifact? GetArtifact(Udi udi, IContextCache contextCache)`
  - `IArtifact GetArtifact(object entity, IContextCache contextCache)`
- `IValueConnector`
  - `string? ToArtifact(object? value, IPropertyType propertyType, ICollection<ArtifactDependency> dependencies, IContextCache contextCache)`
  - `object? FromArtifact(string? value, IPropertyType propertyType, object? currentValue, IContextCache contextCache)`
- `IGridCellValueConnector`
  - `string? GetValue(GridValue.GridControl gridControl, ICollection<ArtifactDependency> dependencies, IContextCache contextCache)`
  - `void SetValue(GridValue.GridControl gridControl, IContextCache contextCache)`

The corresponding overloads without the `IContextCache` parameter are obsoleted and have a default implementation that forwards calls using `PassThroughCache.Instance`.

**Comment by leekelleher** [comment]
Thanks @ronaldbarendse - all understood. 👍 

I must admit that I'm confused about the breaking-change policy for major versions (in terms of package support). I was lead to believe that if there was a proposed removal, that would be deprecated in v9, remain for v10 and removed in v11. Giving package developers time to align their codebases.

Would the same logic not apply to additions, (especially with interfaces)?

Seeing a similar discussion (from April) about new methods on interfaces, https://github.com/umbraco/Umbraco-CMS/pull/12218#issuecomment-1089918641, could we take a similar approach? e.g. keeping `IDataTypeConfigurationConnector` as is for v11, introducing `IDataTypeConfigurationConnector2`, remain for v12 and merge them in v13? _(or maybe there's a way to do this with default interfaces, but I may be lacking C# knowledge there)._

My main point is... **that when someone is trying out the v11 RC, would we expect them to install existing packages (that supported v10), or expect them to be broken?**

I can happily compile Contentment against v11/.NET7, (I've already done this), but it does feel like added pressure to actively support Umbraco's major version release cadence, which may become a big ask for free/open-source solo developers over time.

**Comment by bergmania** [comment]
IMO we should do whatever is possible to avoid these breaking changes..

It seems like we can just add default implementations that all just throw NotImplementedExceptions, then we are home safe on this.

I tested out Contentment when doing this for `IDataTypeConfigurationConnector`, and that seems to work. Not sure if there are any big disadvantages to that.

**Pull request merged**
