### PR TITLE
Edge Cases for Issue #13838: Hotkey Actions Triggered from Web Components

### PR DESCRIPTION
**Pull request by markadrake**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

#13838 Typing '1' or '2' into an input inside a web component toggles the content/info content apps instead of writing '1' or '2' 

### Reproduce:

1. Create the necessary folder structure: `/App_Plugins/WebComponent/`
2. Create a `package.manifest` (below)
3. Create a `template.html` (below)
4. Restart your Umbraco web application as necessary.
5. Update a `content type` with a new `property` and choose the `Web Component` editor.
6. Type "**1**" or "**2**" into the property editor field to see the hotkey actions toggle between apps.

> **package.manifest**

```
{
    "propertyEditors": [
        {
            "alias": "Web Component #13838",
            "name": "WebComponent13838",
            "icon": "icon-block",
            "group": "Common",
            "editor": {
                "view": "~/App_Plugins/WebComponent/template.html",
            }
        }
    ]
}
```

> **template.html**

```
<uui-input
	label="Username"
	type="text"
	placeholder="Enter your username...">
</uui-input>
```

### After this PR:

The code for hotkey actions already has some basic checks in place. With this PR, the element we run these checks against will first come from `composedPath`. [Read more about **composedPath** from MDN.](https://developer.mozilla.org/en-US/docs/Web/API/Event/composedPath) 

For web components with a _open_ Shadow DOM, we have a better look at the true source of the event.

For web components with a _closed_ Shadow DOM, nothing should change. 

7. Switch to this branch and rebuild the UI.
8. Restart your Umbraco web application as necessary.
9. Type `**1**` or `**2**` into the property editor field. The hotkey actions will be cancelled.

### Opportunities:

Web Component authors should be informed about the hotkey system and potential issues from allowing keydown events to propagate too far. I am not confident I know the best place in our documentation to put such warning/notice. Nor am I confident I know what the current status of the UUI library is, and the architecture of the upcoming replacement for AngularJS.

### CODE REVIEW

**Comment by georgebid** [comment]
Thanks for the PR @markadrake! Someone from the core collaborator team will take a look soon. Cheers :grin:

**Comment by nul800sebastiaan** [comment]
Thanks again @markadrake - I really enjoyed the steps for a minimal reproduction, that REALLY helped me get through this review quite quickly, thanks for that #h5yr! 

This is not the first time we're dealing with `1` and `2` (and `3` etc - however many content apps there are) being problematic, as you've already seen in the code 😅 - to be honest I don't know how many people even know these shortcuts exist. Anyway, that's beside the point, this is fixed wonderfully now! 👍 

Honestly I am not too concerned about this any more now, the keyboard shortcuts now work great again and not when trying to edit content, so all good. We're hard at work on new backoffice where we don't need to hack around and plug stuff into AngularJS or remove it again, it should all be much more smooth sailing (and yes, the web components, as far as I can tell, are indeed closed).

**Note:** I've taken the opportunity to reformat the file as you used tabs instead of spaces (I know, I know, tabs should be used, but that's not our current setup yet!). So it looks like more has changed in this commit, but in reality it's just reformatting correctly.

Thanks for the help here, very nice fix! 🏅

**Comment by nul800sebastiaan** [comment]
Cherry picked for 10.6 in aaec419672315b7dc4db3a57bf57c17c9be8f339

**Comment by markadrake** [comment]
Thanks so much for the kind words @nul800sebastiaan! I love how friendly the community has been over my past 8, maybe 10, years. 

I apologize for missing the tabs/space formatting. I do have some defaults set in VSCode. I should have caught that on my commit. 

If I can ever help or assist on the UI/UX side of the new backoffice, please let me know. I really enjoy contributing to the project (when I have time)!

Thanks again for the wonderful feedback,

**Pull request merged**
