### PR TITLE
Fixes U4-7249 Insert Macro split button, when selecting a macro that …

### PR DESCRIPTION
**Pull request by TimGeyssens**
…has parameters the dialog should immediately show those

### CODE REVIEW

**Comment by TimGeyssens** [comment]
@nul800sebastiaan any chance this can get into 7.4 final? :)

**Comment by nul800sebastiaan** [comment]
Sure thing!

**Comment by TimGeyssens** [comment]
Sweet, thanks!

**Comment by nul800sebastiaan** [comment]
Awesome, works like a charm, thanks!

**Comment by TimGeyssens** [comment]
Great, been bugging me for ages :) thanks for merging!

**Pull request merged**
