### PR TITLE
Features/u4 11424 use umb toggle directive permissions.tab

### PR DESCRIPTION
**Pull request by BatJan**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description
Replacing the "checkbox" in the document and media type editors "permissions" tab to make use of the umb-toggle directive, which is already in the codebase.

Video showing the toggle on the "Media Type" permissions tab here: https://www.youtube.com/watch?reload=9&v=fHshO8jiRlY&feature=youtu.be

Video showing the toggle on the "Document Type" permissions tab here: https://www.youtube.com/watch?v=Iy8Mqp9Pf_o&feature=youtu.be

Pretty much identical but my hope is that it makes it easier to just see what has changed and what the test scenario is? :-)

Link to issue tracker: http://issues.umbraco.org/issue/U4-11424

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi,

Many thanks for your PR. We shall review your PR within the next 14 days and let you know of the outcome.

Regards,
Poornima([The Community Pull Request Team](https://umbraco.com/blog/introducing-the-new-pr-team/))

**Comment by poornimanayar** [comment]
Hi @BatJan ,

I have reviewed the PR and tested it as well. It all looks good.  Nice one! 

Poornima([The Community Pull Request Team](https://umbraco.com/blog/introducing-the-new-pr-team/))

**Comment by nul800sebastiaan** [comment]
SuperTak @BatJan ! Very helpful with the video's too 👍

**Comment by BatJan** [comment]
You're welcome - I'll make it into embeddable GIF's for the next PR's I'm going to make - That way it's not even necessary to visit Youtube :)

**Comment by poornimanayar** [comment]
How could I forget to mention those YouTube videos. They were superb! Very commendable effort 🙂

**Comment by BatJan** [comment]
Thank you @poornimanayar :-) I figured it would make it way easier to see the change in effect rather than doing a lot of tedious description in text. I will make the effort again for the coming PR's and perhaps even do GIF's if that would make even better sense? :)

**Pull request merged**
