### PR TITLE
V8: It should be possible to disallow all types at content root 

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

*This PR partially reverts #4418*

As it stands we can't disallow all types at root in content and media; if no types are markes as allowed at root, all types explicitly are made available at root. #4414 called for this feature to help newcomers, and however sympathetic that is, it's kinda bad not being able to lock down the editors at root level, specially for content.

Here's how it currently works:

disallow-at-root-before

With this PR, you explicitly need to allow content types at root before they're made available (for this PR I have opted to keep the behavior as-is for media):

disallow-at-root-after

This also applies to move and restore operations:

disallow-at-root-after-move

As for aiding newcomers, #6573 is specifically aimed at this and, and even though it's primarily centered around blank installs it will also work for this scenario.

#### Testing this PR

1. For content, make sure you can disallow every all content types at root level.
2. Once disallowed, make sure you can't move any content types to the root level.
3. For media, verify that you can still create any media type at root level if no media types are allowed at root level.

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
In #4414 the scenario is: a developer new to Umbraco just created a doctype and it's not showing up. #6573 then tells them: hey, you need to create a document type here in order to add something.

So I would suggest that #6573 looks for existing document types and suggests updating the permissions. Maybe an extra button that takes you to the settings section?

**Comment by kjac** [comment]
@nul800sebastiaan while this PR and #6573 are designed to compliment each other, I didn't want to be presumptuous by expecting both to be accepted 😄 

If they are indeed both accepted, I would suggest the following changes to #6573 

1. Update the wording a bit, so it hints at the option to edit the permissions of existing doctypes in instead of creating a new one.
2. Look into making "Allow at root" default true for the first doctype created, as this is likely to be the case anyway.

I wouldn't add an extra button though, the top menu does a top job at taking people to the settings section.

**Comment by nul800sebastiaan** [comment]
@kjac In order to help with number 1 I've added a few more things to this PR: https://github.com/umbraco/Umbraco-CMS/pull/6580/commits/fca68e149c4ea2e3eb8b69c80fe22853b6a1a023

This looks like this when there are existing doctypes but none are allowed at root

image

What do you think?

I think this is good for now, I am not sure about number 2 (first doctype allowed at root by default) but that's a different issue.

**Comment by kjac** [comment]
That's awesome @nul800sebastiaan 😀

**Pull request merged**
