### PR TITLE
IsNullOrWhiteSpace Extension method for HtmlEncodedString

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
Not sure if this is an desired addition. But in soms cases it can be usefull to check if  a 'IHtmlEncodedString' is null or only contains whitespace. In this way you can prevent HTML will be rendered if the `IHtmlEncodedString` only has whitespace:

```
@if (!Model.MyProperty.IsNullOrWhiteSpace())
{
    <div class="my-class">
        @Html.Raw(Model.Intro)
    </div>
}
```

### CODE REVIEW

**Comment by ronaldbarendse** [comment]
This method also checks and strips empty HTML tags, so a better name would be something like `IsNullOrEmptyHtml`.

And if this is used with property values, a better solution might be to override the default Property Value Converters to return `null`, instead of the empty `IHtmlEncodedString` instances: these returned values are cached, so you don't have to re-process them on every request. This can be a big performance improvement, especially when the value contains a large chunk of HTML that needs to be loaded/parsed into an `HtmlDocument` to strip all HTML (just to check whether it's not empty). The views can then also use a simple null check or pattern matching (`@if (Model.MyProperty is IHtmlEncodedString myProperty) { ... }`).

**Comment by erikjanwestendorp** [comment]
@ronaldbarendse Thanks for the review. I hadn't realized that this could really lead to performance issues. I often use this extension method for RTE's that contain little HTML.

Of course I can choose to override the default Property Value Converter, but then I have to do this again for every project, it would be nice if this was an option by default or not?

A possible solution in my opinion could be to add an extra toggle and then check the configuration within the PropertyValueConverter. Based on this setting you can check whether the value should be null.

image


Of course I want to work on this, but is there a chance that this will be merged?

**Comment by erikjanwestendorp** [comment]
@ronaldbarendse Thanks for your detailed explanation. 

Emptiness looks like a nice package. I'm definitely will create a PR to implement a NullableMarkdownEditorValueConverter and a NullRteMacroRenderingValueConverter. 

Regarding to this PR: 
- [x] Update the PR with the method you suggested. 
- [x] Tested the method 
- [x] Add a Unit Test

**Review by ronaldbarendse — APPROVED** [review]

**Comment by erikjanwestendorp** [comment]
@ronaldbarendse Can this one be merged?

**Comment by busrasengul** [comment]
Thank you @erikjanwestendorp 
This is merged now 🎉

**Comment by erikjanwestendorp** [comment]
Gracias @busrasengul, and congratulations with joining the collab team!

**Comment by nul800sebastiaan** [comment]
Cherry picked for 10.5 in 010ea5a2aae4cc50724ce3c03ab6317698e587f1

**Pull request merged**
