### PR TITLE
Remove HtmlSanitizer

### LINKED ISSUE #9615: Update HtmlSanitizer
As one that's been using AngleSharp for quite a while on earlier versions of Umbraco 8 (8.6.4), i was a bit confused when trying to upgrade to 8.10.1 today.

Seeing that it has a dependency on a 2 year old version of HtmlSanitizer, and that in turn having a dependency on a 3 year old version of AngleSharp, stopping me from upgrading, unless i downgrade AngleSharp.

Any reason for these old versions suddenly appearing, or would it be possible to include a newer version of HtmlSanitizer, and by that a newer AngleSharp?

### PR DESCRIPTION
**Pull request by nul800sebastiaan**
Due to a security issue, HtmlSanitizer has decided to pull all v4 versions from NuGet: https://github.com/umbraco/Umbraco-CMS/issues/9615#issuecomment-773305267

We tried updating to v5 of the package but it won't build on the CI server nor locally: https://github.com/umbraco/Umbraco-CMS/issues/9615

After exploring some options we came to the conclusion that

- We only added sanitization of SVGs for the SVG icons since v8.8 (https://github.com/umbraco/Umbraco-CMS/issues/3560#issuecomment-484289060). 
- This was out of an abundance of caution, the SVGs shipped with Umbraco of course don't contain any scripting
- The sanitization was added for packages/additional icon(pack)s people might want to load 

We came to the conclusion that installing icons poses the same risk that is already present when installing any other packages: they can contain malicious javascript and/or dlls and/or other malicious content. 

Therefore, we've decided it is okay to remove the SVG sanitizer while we look for alternatives, so as to fix people's NuGet installs for now.

Furthermore: this pinned the version of Anglesharp people were using, and working around that was quite a pain, this also resolves that problem, we don't rely on AngleSharp anywhere so people can use any version they want again.

After merging, this needs to be backported to v8.8.x and above and released as a patch release for 8.8 through 8.11.

Fixes #9615

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Note: I don't understand why some people have problem restoring the package, the v4 version has not been deleted from NuGet, but it's been unlisted. Even after deleting my local NuGet cache I have no problems installing Umbraco nor upgrading from a version lower than 8.8.

**Review by emma-hq — APPROVED** [review]

**Comment by lars-erik** [comment]
@nul800sebastiaan I think it might have to do with your nuget settings with regard to taking the uppermost or lowermost versions for the indirect dependencies.

I was able to upgrade 8.6 to 8.11 by installing HtmlSanitizer -v 4.0.nnn first.

**Comment by ronaldbarendse** [comment]
@nul800sebastiaan Note that removing the HtmlSanitizer dependency from the Umbraco NuGet packages won't remove the entry in the `packages.config`, but does remove the version restriction (>= 4.0.217 && < 4.999999.0). This will allow it to update to version 5 (when doing an `PM> Update-Package`), which might cause similar issues as discussed in https://github.com/umbraco/Umbraco-CMS/issues/6495#issuecomment-565068508.

Uninstalling can be automatically done in the [`install.ps1`](https://github.com/umbraco/Umbraco-CMS/blob/34e80d86e8c0b754f6b7a02e307f53cb32806bbe/build/NuSpecs/tools/install.ps1) script that runs on NuGet install (including updating to newer versions), although other custom packages might still require it and throw errors (which should be ignored in a try/catch).

Or just put a warning/reminder message in the release notes (and [ReadmeUpgrade.txt](https://github.com/umbraco/Umbraco-CMS/blob/34e80d86e8c0b754f6b7a02e307f53cb32806bbe/build/NuSpecs/tools/ReadmeUpgrade.txt)) to manually uninstall the package if needed?

**Comment by ronaldbarendse** [comment]
@nul800sebastiaan Besides the above comment, this should already be marked as breaking change, because the `Umbraco.Core.Constants.SvgSanitizer` class is removed, right?

**Comment by nul800sebastiaan** [comment]
Correct, it is a breaking change, hopefully not something people are actively using. 

Other than that, it's not in the way if people don't uninstall the NuGet but we'll put it in the version specific upgrade docs.

**Pull request merged**
