### PR TITLE
Lets get the NuGet packages working with Website projects

### PR DESCRIPTION
**Pull request by mattbrailsford**
A continuation of the original PR #193, I still think it's worth while adding support to allow the NuGet package to be installed on Website projects.

I've updated the install.ps1 scripts to use the project path that will work for both project types, however the issue now (and the error Seb was reporting in the original PR) is down to the change to use /build/UmbracoCms.prop/.target files in order to copy over the UmbracoFiles that shouldn't be included in the .csproj. On the original PR, this was coded against a previous version of the installer files that used xcopy to copy the files over instead which meant it would work for both. The reason for the error being that NuGet will automatically try and inject any target files in the /build/ folder into your .csproj file, and obviously a website project doesn't have one, and so it fails.

The question then is, is there any way we can make this work without the build folder? and in a way that would work for both project types? If copying worked before, what was the reason for moving to the target files? is there an alternative?

I know website projects are viewed as an "edge case" and not "the proper way to do things", but it would certainly make things easier for people who just want a simpler solution.

PS This PR as it stands clearly can't be merged in, it has just been created in order to hold the discussion.

### CODE REVIEW

**Comment by sitereactor** [comment]
If we remove the build props/targets then publishing from Visual Studio will be missing all the files that are not explicitly added to the csproj, which includes the Umbraco and umbraco_client folders. The fact that these files are injected into the csproj means that publishing/deploying from VS is a lot easier for web applications.
I'd argue that this is something that should be handled by nuget, and I would have thought it was clever enough to distinguish between project types.
I realize this does help the situation, but I think we might be able to find some inspiration in AutoMapper. I think they made it work by having build props as part of the nuget, but handled by Powershell rather then having nuget inject them. It might have changed since I looked at it, but pretty sure the history is there (for our inspiration). So if my theory is correct I believe we "just" need to have the Powershell figure out the project type and only inject for certain types.

One thing that we need to carefully consider is the upgrade story - especially if we point to a file in a versions nuget package folder.

**Comment by mattbrailsford** [comment]
Thanks @sitereactor for taking the time to consider this. 

I agree, it does sound like NuGet should handle this situation, but if there is an easy enough work around that doesn't add a ton of complication, it would be nice to support it. I'll take a look at AutoMapper project and see how they are doing it (thanks for the tip).

Regarding paths, I think as long as within the powershell scripts you use $project.Properties.Item("FullPath").Value to access the project path, it will work for both project types so it shouldn't stop you from resolving a path if you need to.

**Comment by mattbrailsford** [comment]
Ok, so with the latest commit, it should now support both web apps and websites.

I've copied how AutoMapper injects the props/targets manually, and added a check within the install.ps1 file to check whether the project is a web app or a website. If web app, it injects the msbuild props/targets into the project. If it's a website, it just robocopy's the umbraco files direct to project root, excluding the web.config (I figure I should exclude the web.config right?)

I've installed this NuGet package on both a website and web app project, and both worked as expected.

**Comment by sitereactor** [comment]
Does this work with upgrades as well? Does it remove the old or just update the path to the new package path?

**Comment by mattbrailsford** [comment]
As in remove the old "build" folder? not currently, but I can make that work.

The injection/copy code is made to just run on new install. I believe the rest of the code should handle upgrades.

**Comment by mattbrailsford** [comment]
I guess for old installs, they will already have the injected includes in pointing to a /build folder, so in that instance, if we find a build folder, we could just copy the contents of the new msbuild folder into it, and all should be right with the world. It just means old upgraded installs still use build, new installs would use msbuild folder.

**Comment by mattbrailsford** [comment]
So, it looks like if you delete the build folder, it auto removes the imports anyway, so I've changed the logic for injecting the imports around a bit so it runs on upgrades too, but checks to see if an import has already been registered, if not, it injects it.

**Comment by Jeavon** [comment]
Wow, that looks like it took a lot of unpicking! Why hasn't it been merged already?

**Comment by sitereactor** [comment]
@Jeavon I'm afraid we haven't had time to test this yet.

**Comment by Jeavon** [comment]
@sitereactor ah ok, I was interested if there were any issues, thanks

**Comment by sitereactor** [comment]
@Jeavon the only issue is time :wink:

**Comment by warrenbuckley** [comment]
Hello @mattbrailsford & @Jeavon 
Is this still a valid concern & something you want to see looked at being merged in & reviewed for the core, considering it's been a while since this was worked on & I am now wondering if this is still a problem or not anymore?

Thanks,
Warren :)

**Comment by warrenbuckley** [comment]
Hi @mattbrailsford & @Jeavon 
I have tried this out this morning and it works fine. So we must have resolved this at a later point.

I tested with VS2017 in an Empty ASP.NET Website project using 4.6.2 .NET Framework using the Nuget UI to install UmbracoCms.

So with this I am going to close the PR.

Thanks,
Warren :)

**Pull request closed without merging**
