### PR TITLE
Fix dead lock with TypeLoader

### PR DESCRIPTION
**Pull request by Shazwazza**
This deadlock can occur in both v8 and the netcore branches, this fix is for v8 (the netcore fix is #9959)

This is why:

image

There is actually no reason at all for GetFileBasePath to use the _locko lock and I believe it was used by accident and just re-using an existing lock field. The GetFileBasePath method is actually just a lazy initializer for a value so that's what it should be and that is how this is fixed. Now we have a Lazy _fileBasePath which is initialized with GetFileBasePath and then _fileBasePath.Value is used where needed and this fixes the deadlock.

### CODE REVIEW

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Hi @Shazwazza, it's doing the trick indeed! Thanks!

**Comment by mikecp** [comment]
Woops, can't merge this one 😄

**Comment by mikecp** [comment]
@Shazwazza any issue with retargeting this to v8/contrib?

**Comment by Shazwazza** [comment]
@mikecp I've updated to v8/contrib 👍

**Pull request merged**
