### PR TITLE
V8: Ensure consistent template file casing no matter how templates are created

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

#4300 fixed the casing of templates created manually. However, the corresponding template aliases and files are still cased wrongly (in camel case) when compared to the templates created when creating a content type (in pascal case):

image

This PR fixes it. Template creation works like this when the PR is applied:

template-file-casing

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @kjac - excellent spot!

Em

**Comment by Shazwazza** [comment]
I haven't looked at thy underlying code but since we're already passing the name and alias in, shouldn't this be handled by the service instead of the way the service is called?

**Comment by kjac** [comment]
@Shazwazza it should, and in all fairness it's been a while since I did the PR. My guess is I didn't want to create a logical breaking change in a publicly available service implementation.

Ideally `CreateTemplateWithIdentity()` should be obsoleted and refactored without the alias parameter, as should `CreateTemplateForContentType()`. Not entirely sure that's in scope for this fix, but I'm happy to do it if it makes sense to do now.

**Comment by Shazwazza** [comment]
@kjac I'll need to dig into it, i will follow up as soon as i get through my current backlog of stuff.

**Comment by kjac** [comment]
No rush 😀

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Pull request merged**
