### PR TITLE
14263 user password validation missing requirements

### PR DESCRIPTION
**Pull request by nagolucky18**
### Prerequisites

- [X] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes [14263](https://github.com/umbraco/Umbraco-CMS/issues/14263)

### Description

The following changes were made:

- Update password tip directive to include information about all password tips and not just minimum password length and non-alphanumeric characters. Now, in addition to minimum password length and non-alphanumeric tips, there are tips for digit, uppercase, and lowercase if they are present in the app settings.
- Update embedded resources for en and en_us to include the new password tip strings. This pull request will be draft until all embedded resources have been updated.

How to test:

1. Update user and member password settings in appsettings.json to include the desired password requirements.

image

2. Run Umbraco

3. Change your password. Observe that new tips are present for desired user settings.

image

4. Create a new member. Observe that new tips are present for desired member settings.

image

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi @nagolucky18!

Good work on starting your PR to fix #14263.

The team will leave it for now, but soon as you're ready for review, please publish it and we'll take a look!

Also, please let us know if we can help! 🙂 

Thanks,

Emma

**Comment by nagolucky18** [comment]
All translations for password tips added.

**Comment by emmagarland** [comment]
Thanks so much @nagolucky18 and apologies for the very delayed reply. 

I'm just checking with HQ that this will still be added to v13 and applied to the new backoffice UI (codename Bellissima) for feature parity. 

I'll let you know as soon as I hear back :) Thanks so much for all your efforts, I'm sure we'll use at least the translations if not the code too. 

Emma

**Comment by emmagarland** [comment]
Hi @nagolucky18 

Firstly apologies for the delay in getting this reviewed!

I have an update for you about merging this. 

As you may or may not know, we're working on a rewrite of the Umbraco backoffice, codenamed Bellissima (https://umbraco.com/blog/bellissima-preview-releases-of-the-new-backoffice/), and we're trying to make sure that it has feature parity with the current AngularJS-based backoffice.

We're at a point in the development phase where we want to start wrapping up a beta version to ship sometime soon, and we will have to implement a **feature freeze** on the current backoffice so that we don't keep increasing the scope of Bellissima. 

Unfortunately, that means we will have to stop accepting PRs like this one that create significant changes to the current backoffice. Since we won't be able to commit to doing this for v14, we will need to close it for now. 

As a general rule from now on, we're still happy for features in C# code but anything that gets introduced or refactored in AngularJS probably won't make it. Bugfixes are still great of course!

We'd also be super pleased to see this PR for v14, if this is something you'd be interested in doing.

Thanks for the efforts here, and we hope to see you back as a contributor soon! 👍

**Pull request closed without merging**
