### PR TITLE
Fix for issue 11987 - Ignores missing package dependencies in sort

### LINKED ISSUE #11987: Package import errors if dependent on composition in a dependant package
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.3.0-rc1

### Bug summary

Working with a complex site that uses packages to modularize code and promote reuse (good things!).  I've run into an issue where I get an error "Missing dependency. Error in type Node`2, with key [composition name]" when it tries to load the package that consumes the dependency. This happens whether the dependent package already exists in the project or is loaded from the consuming package.

As a result of the error, neither package's elements are installed

### Specifics

This appears to be an issue in the graph sorting XML elements in dependency order at Umbraco.Cms.Infrastructure.Packaging.PackageDataInstallation, line 517.  The TopoGraph used to sort dependencies throws the "Missing Dependency" error because it cannot find the composition from the dependency. Its scope is limited to the current XMLDocument contents.  The composition dependency is not resolved until the call to Create/UpdateContentTypeFromXml on line 528 (which resolves the composition on line 801).

This may be the cause or similar to Issue #8128 and would also handle the request made in #11763

It seems like there is a simple fix for this (PR forthcoming): setting throwOnMissing = true in the graph.GetSortedListCall on line 517
List<XElement> documentTypes = isSingleDocTypeImport
                ? unsortedDocumentTypes.ToList()
                : graph.GetSortedItems(throwOnMissing:false).Select(x => x.Item).ToList();

### Steps to reproduce

Set up a package that includes a composition definition. Pack it via NuGet and host it locally
Setup  a package project with a document type that implements the composition defined in step 1
Set up a test project for the package defined n step 2
Run the test project.  You will see the missing dependency error in the log/console.

### Expected result / actual result

There should be no error and all elements from both packages should be visible in the Document Types list.

### PR DESCRIPTION
**Pull request by tconnellredmane**
### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #11987
### Description
See issue for detailed description of problem solved.

The package import process throws a Missing Dependency" error when importing packages with dependencies on compositions defined in other packages.  Sorting the incoming document types by dependency creates an error state because the externally-defined composition does not exist within the graph's scope (the incoming XML document). This changes ignores these missing dependencies so they can be resolved by later code.

Testing guidelines are in the issue

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Hi there @tconnellredmane and thanks for the PR! While I do understand that people don't like to see errors, I am wondering if this just hides other problems. Maybe I'm misunderstanding but if not all dependencies are installed, as I think you're suggesting here, then the document types wouldn't work anyway? Maybe I misunderstood something though, so please enlighten me! 👍

**Comment by tconnellredmane** [comment]
Hi @nul800sebastiaan, No problem with the delay.  If Project B is missing you have a whole different challenge that is outside of the scope of this issue, and likely a packaging/reference problem.  If you meant Project A, in my use case Project B includes a reference to Project A (installed via NuGet), so it shouldn't ever go missing.  Other use cases may vary.

In all of my testing, entities from Project A are added before entities from Project B, but that may be a coincidence.  I can dig in and look at how the package import process is ordered, or you might know off the top of your head if they are handled in dependency order.  If this is coincidental, it may point to additional work for this branch.

I think your question just reinforces my idea that the dependent entity check is happening in the wrong place.  The purpose of the code in question is merely to sort the incoming entities based on reference, so that incoming compositions, etc. are processed before any new entities that depend on them.  The actual dependency resolution happens later, outside of the sort.  The way it is currently written, (incomplete) dependency checking happens as a by-product of the sort, which isn't a great idea (breaks the Single Responsibility Principle, if you want to get technical), and is also handled elsewhere anyway.

**Comment by emmagarland** [comment]
Hi @tconnellredmane!

Just been reviewing some of the longer running PRs, and noticed this one (it's been a while sorry!)

I've rebased to the `umbraco:contrib` branch. 

Do you have any examples of the packages that show the failures in order for us to test this, or do we need to create one to confirm this?

I've brought across the steps in the related issue #11987:

1. Set up a package that includes a composition definition
2. Pack it via NuGet and host it locally
3. Setup a package project with a document type that implements the composition defined in step 1
4. Set up a test project for the package defined in step 3
5. Run the test project to see the missing dependency error in the log/console


Thanks,

Emma 🙂

**Comment by tconnellredmane** [comment]
Hi Emma,
Sorry, I don’t have anything you can use at hand.  If you have trouble setting up test packages I can see what I can pull together.

**Comment by emmagarland** [comment]
Hi @tconnellredmane 

Apologies for the delay, I have tried to return to this issue to attempt to replicate it, but with no luck so far. 

Here are my replication steps as best as I can share. I am using the latest Umbraco templates for v11, in case that affects anything:

1.	Ensure you have the latest Umbraco templates with `dotnet new install Umbraco.Templates`
2.	Create a new Umbraco package in the required folder via `dotnet new umbracopackage --name PRPackage11988`
3.	Create a new Umbraco project in the required folder via `dotnet new umbraco`
4.	Create a composition in this project

image


image


5.	Create a package in this project
6.	Download the package, which will be a single _package.xml_ file
7.	Add a Migrations folder to the package project `PRPackage11988`
8.	Create a migration file within this Migrations folder, `PackageMigrationPlan.cs`, as per [the docs](https://docs.umbraco.com/umbraco-cms/extending/packages/creating-a-package); this file inherits from `AutomaticPackageMigrationPlan`
9.	Added the _package.xml_ from step 6 to the step 5 Migration folder. NB, currently, if I use a _package.xml_ file it causes an unrelated error already [logged here](https://github.com/umbraco/Umbraco-CMS/issues/12125), so until that is resolved, I have been zipping up the package.xml file as _package.zip_ 
10. Set the build action on this package file to be an embedded resource via the property editor 
11. Pack the package from within the package folder in step 2 via `PRPackage11988` via `dotnet pack PRPackage11988 -p:PackageVersion=1.1.0 --output .`
12.	Create a new Umbraco project in the required folder, which references that package via `dotnet new umbraco -n Project11988 -p PRPackage11988`
13.	Build and run `Project11988`
14.	In same running Umbraco, create a document type that implements the composition defined in `PRPackage11988`

image


15.	Create package in this project
16.	Download _package.xml_
17.	Setup a package project in the required folder (this will have the document type that implements the composition defined in PRPackage11988) via `dotnet new umbracopackage --name PRPackageB11988`
18.	Add a Migrations folder to this project
19.	Create a migration file `PackageMigrationPlan.cs`, as [the docs](https://docs.umbraco.com/umbraco-cms/extending/packages/creating-a-package); this file inherits from `AutomaticPackageMigrationPlan`
20.	As per steps 9-10, add previous package.xml to the Migration folder as a zipped up package.zip file and make it an embedded resource
21.	Pack this package `PRPackageB11988` via `dotnet pack PRPackageB11988 -p:PackageVersion=1.1.0 --output .`
22.	Create a new Umbraco project in the required folder, referencing the second package `PRPackageB11988` via `dotnet new umbraco -n ProjectB11988 -p PRPackageB11988`
23.	Build and run `ProjectB11988` via `dotnet run -verbose`

Here, I expected to observe the missing dependency error in the log/console. However, I don’t see any issues on the logs. I can se
[packageXmlFiles.zip](https://github.com/umbraco/Umbraco-CMS/files/11545225/packageXmlFiles.zip)
e that the composition from Package A is not present in the package B doctype, though:

image

I would really appreciate if you are able to replicate my steps and tell me where the error you are reporting comes in. 

I've also attached the `package.xml` files for Package A and Package B so you can inform me if I have missed anything that this error is caused by. 

Also, please note that when running the projects created with the packages, you will currently get an error due to a line in the project file that is to be removed in future. Removing this line (or the equivalent for your project file) referencing the nonexistant "build" folder will enable the project to run again:

`<Import Project="..\PRPackageB11988\build\PRPackageB11988.targets" />
`   

Best wishes,

Emma

**Comment by emmagarland** [comment]
Hi @tconnellredmane,

Since we haven't heard from you for a while, we're closing this PR for now, but we'd love to start another conversation about it if you get a chance to focus on it again.

If you want to reactivate this PR, please feel free to reply to this, and we can take it from there 😃 

All the best and thanks again for your contribution,

Emma

**Pull request closed without merging**
