### PR TITLE
Updated ru.xml - new ver6.2 keys were added

### PR DESCRIPTION
**Pull request by abryukhov**

### CODE REVIEW

**Comment by zpqrtbnk** [comment]
This PR has been closed because it was targetting a branch such as `7.x.x`, and these branches are closed when the version is released, and replaced with a simple `release-7.x.x` tag. If the PR is still relevant, we invite you to re-submit the PR, targetting the current version 7 development branch, ie `dev-v7`. Many thanks!

**Comment by abryukhov** [comment]
@zpqrtbnk, this PR is totally not for v7 dev thread.
It's updated Umbraco UI language file for Russian language with the latest keys added for Umbraco ver 6.2... (node type change dialog etc.)

**Comment by zpqrtbnk** [comment]
Ah well... the point is, apart from critical issue or security fixes, no further 6.x release is planned. So, the PR will not get merged into 6.x. But maybe it's worth updating it for 7.x?

**Comment by abryukhov** [comment]
Sad that this PR was not merged into 6.2.6 which was released recently, afaik, but nothing to do ;-)
What about v7, it's russian ui lang resource file is supported and periodically updated by me too, so the 7.x RU lang file is in actual state, thank you.

**Pull request closed without merging**
