### PR TITLE
Fixing when a start node is a content item in a nested list view

### PR DESCRIPTION
**Pull request by Shazwazza**
If you have a user with a start node that is nested within 2 or more list views, the tree will not expand when the user logs in and therefore the user cannot actually navigate to or edit their start node.

## Testing

Create a tree structure like:

* Home
  * List View
    * List View
      * Content

And then create a new user and set their start node to `Content`. When you log in the tree will expand to show `Content`. Be creative, try nesting a start node in a bunch of list views, maybe even have a content -> list view -> content -> list view type scenario, it should all work.

### CODE REVIEW

**Comment by warrenbuckley** [comment]
Code changes makes sense/read fine 👍 
Off to test this out from your notes :)

**Comment by warrenbuckley** [comment]
## Test Feedback
@Shazwazza a few weird quirks from testing, see my attached video for reference
https://youtu.be/r4wx4BFJ9qs

- The content tree does not sync up correctly with the node selected, it seems to highlight the parent.
- Back arrow in a list view should be removed/disabled if you can not visit its parent.

**Comment by Shazwazza** [comment]
@warrenbuckley that seems odd since i fixed that tree sync issue since it was previously syncing to the parent like in your video (what is up with your audio btw , lol) . Anyways, i'll try to have a look, i had the same tests as you and seemed to be working on my machine.

**Comment by Shazwazza** [comment]
@warrenbuckley right! I've fixed it all up. It was a pretty crazy thing going on indeed. My orig tests were pretty simple but the code didn't cover all scenarios like yours. It should be good now if you can please test. You can have a look at the latest commit to see what was changed:

* Now ensures that all start nodes are used (calculated) since before it was only using start nodes directly assigned to the user which was wrong
* Deals with cases where the start node is a non-list view that exists underneath a start node along with dealing with when there's a child/descendant of this non-list view start node that is a list view

**Comment by warrenbuckley** [comment]
Code changes look/read fine. Off to retest this

**Comment by warrenbuckley** [comment]
Retested and all works as expected - good stuff 💪

**Pull request merged**
