### PR TITLE
V8: Add custom crop indication to image cropper

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/2932

### Description

This PR adds an indication to crops that have been customized by the editors, so they're easily identifiable when looking at the list of crops. The PR is a V8 redo of #3145, although the implemented solution differs a bit to cater for the comments made on the original PR.

When this PR is applied, a little text ("User defined") appears under the crops that are customized by the editors. There is no text for the automatic/non-customized crops, so the customized ones are easily recognizable among all the available crops.

It looks like this:

display-user-defined-crops

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey Kenn,

Considering how wonderfully you document your PR's, copy and pasting feels *wrong*. I'll stop it now. Thanks for your recent contributions! I'll dig into these later in the week. You're a ⭐️ 

Em

**Comment by ronaldbarendse** [comment]
Nice and subtle user feedback! The text 'User defined' is also much more explicit then any icon or colored dot and keeps the crops in their original position (compared to #3145).

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Pull request merged**
