### PR TITLE
Fixes #13732 - IsBackOfficeRequest is extremely inefficient

### LINKED ISSUE #13732: IsBackOfficeRequest is extremely inefficient
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

v9, v10, v11

### Bug summary

https://github.com/umbraco/Umbraco-CMS/blob/v11/contrib/src/Umbraco.Core/Routing/UmbracoRequestPaths.cs

This gets called a lot and does a lot of unnecessary things.
- It can optionally take the Path property from a Request instead of trimming the entire URL.
- _defaultUmbPaths is useless, this can just be a string.
- urlPath gets split by forward slash for PluginController, while this should just count slashes and avoid unnecessary allocations.

Created originally as a discussion here #11640 but this seems completely ignored.

### Specifics

_No response_

### Steps to reproduce

Just run Umbraco.

### Expected result / actual result

Should be optimized.

### PR DESCRIPTION
**Pull request by Nuklon**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #13732

This greatly improves the performance of IsBackOfficeRequest.

### CODE REVIEW

**Review by mikecp — CHANGES_REQUESTED** [review]
HI @Nuklon ,
Thanks a lot for providing this performance improvement 👍
And also thanks for your patience since V9 for getting this in 😅

I have left two comments on which I would like to get your feedback. One of them aims at making this even more efficient 😉

Cheers!

**Comment by Nuklon** [comment]
@mikecp, is this OK to merge now? I'd rather not see this effort also go to waste 🙂

**Comment by mikecp** [comment]
Hi @Nuklon,
Busy week last week, but don't worry, I'll check your PR in the coming days 👍

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Hello @Nuklon ,

Here we go for the merge! Thank you for helping make Umbraco more performant 👍

I see that this is your first contribution, this is awesome! Congratulations!!  🎉
If you provide us with your account name on Our, @nul800sebastiaan will be very happy to assign our shiny contributor's badge to you 🥇

And we'll be looking forward to your next ones 😉

Cheers!

**Comment by nul800sebastiaan** [comment]
Cherry picked for 10.5 in 4f8b8b3415e09223555d09d7467e80062eff494e

**Pull request merged**
