### PR TITLE
install ngAria 

### PR DESCRIPTION
**Pull request by Matthew-Wise**
Another one for accessibility 😸 ngAria makes angular more aria aware meaning things like ng-required aren't needed instead we can just use required. It should also improve the use of ngShow/Hide.

@RachBreeze has tested this with the login in order to make sure it's working as intended.

Thanks
Matt

### CODE REVIEW

**Comment by RachBreeze** [comment]
Hi @sebastian-claesson  and @Matthew-Wise 
I like this PR a lot, it solves an issue around the "required" attribute not firing alerts to the screen reader correctly.  In the current site  we've tabbed into required textboxes and the screen reader has said they are invalid, before a user has entered anything.  This PR only sets the state as invalid on the form submit, so the user of a screen reader only hears invalid when they tab into an empty required textbox post form submit

**Comment by BatJan** [comment]
A little more background information about the module @Matthew-Wise have added can be found here https://docs.angularjs.org/api/ngAria - In short it "should" be "plug'n'play". Only concern I have about this is that some of the attributes it will set augomagically might already have been set manually by contributers. I know I've seen @kjac add some aria-disabled attributes in some PR's for instance 😃 

So perhaps the manually added should be removed before this PR is merged.

**Comment by Matthew-Wise** [comment]
Did you also build Umbraco.Web? As the Javascript/JsInitialize.js was updated but its an embedded resource

Matt

**Comment by nul800sebastiaan** [comment]
Duh! That was silly! Of course I forgot that part. Awesome, it all works, great job! ⭐️

**Comment by nul800sebastiaan** [comment]
Hi there @Matthew-Wise,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing 🥇 

We have had another record breaking amount of PR's in both the CMS, Documentation, and other smaller public repositories. You can read all about the numbers in the [Umbraco Hacktoberfest round-up blog post](https://umbraco.com/blog/pr-team-update-november-2019-hacktoberfest-round-up/).

Due to the amazing work you and others in the community have been doing, we've had a bit of a hard time keeping up. 😅 While all of the PRs for Hacktoberfest might not have been merged yet, you still qualify for receiving some Umbraco swag, congratulations! 🎉 

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://docs.google.com/forms/d/e/1FAIpQLSc-K97Zl5k86cVebKWWqieLM4Fm_jCMGVdbQdYnq4IUJ7EvZg/viewform) :point_left: Please follow this link to fill out and submit the form, **before December 19th 2019**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before February, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
