### PR TITLE
Uduf-Hackathon U4-5366

### PR DESCRIPTION
**Pull request by christophnz**
When importing document types, only document types part of the import were added as allowed child node types. Changed code also uses ContentTypeService to find existing document types by alias and adds them as allowed child node type.

http://issues.umbraco.org/issue/U4-5366

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thank you @christophnz - that's beautiful! Works well  👍 

If you have an account on Our Umbraco I'd love to give you a contribution badge, but I couldn't find you at the moment. :)

image

**Comment by christophnz** [comment]
Thank you Sebastiaan!
This is me on OUR: https://our.umbraco.org/member/140992

On 23/02/2018 3:46 am, "Sebastiaan Janssen" <notifications@github.com>
wrote:

Thank you @christophnz <https://github.com/christophnz> - that's beautiful!
Works well 👍

If you have an account on Our Umbraco I'd love to give you a contribution
badge, but I couldn't find you at the moment. :)

[image: image]
<https://user-images.githubusercontent.com/304656/36554791-83f0053e-1800-11e8-86d9-c4767b10c272.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/umbraco/Umbraco-CMS/pull/2467#issuecomment-367762577>,
or mute the thread

**Comment by nul800sebastiaan** [comment]
Cool, badge added and thanks again!

**Comment by Nicholas-Westby** [comment]
Thanks for making this happen, @christophnz!

**Pull request merged**
