### PR TITLE
Hide icons and use buttons instead of empty anchors in Examine dashboard

### PR DESCRIPTION
**Pull request by BatJan**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
It's all in the title really - Some housekeeping ensuring that `<a>` elements with empty `href` attributes are replaced with `<button>` elements and that `<i>` elements are hidden using `aria-hidden="true"`.

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Nice one Jan, will have to give it a spin soon!

**Comment by nul800sebastiaan** [comment]
Also note: the "Test" links in this screenshots are anchors as well, I might be wrong in merging that, they should probably be buttons as well, not sure.

**Comment by BatJan** [comment]
@nul800sebastiaan No worries, the lack of styling was an oversigt on my part. Forgot about testing the search 🤦‍♂ 

No the test items are proper links referencing other nodes in the backoffice - They have `ng-href` attribute with values in them 😉 

Anything else I need to address? 😃

**Comment by nul800sebastiaan** [comment]
Nope, just the button styling! 👍

**Comment by nul800sebastiaan** [comment]
All great now, thanks @BatJan!

**Pull request merged**
