### PR TITLE
v7 Change z-index for notification

### LINKED ISSUE #6065: NotificationsService displays notifications under dialog
When using notificationsService in a custom tree from a dialog the notification is displayed under the dialog. 

This might be by design but in my usecase it appeared to be a bug 

Reproduction
------------

Create a custom tree in backoffice. 
Add a menu alternative that opens a dialog and trigger either success, error or warning in notificationsService.
You can not read the notification since it is displayed under the dialog

### Specifics
Umbraco 8.0.2
Browser: Chrome 75.0.3770.142
Have not tried it in other browser 

### Steps to reproduce

Create a custom tree in backoffice. 
Add a menu alternative that opens a dialog and trigger either success, error or warning in notificationsService.

### Expected result

You can see the full notification, and read the text 

### Actual result

The dialog covers the leftmost part of the text, or the whole text.

image

### Suggestion
This is an easy fix just change 
.umb-notifications {
   z-index: 1000;    
}
to 
.umb-notifications {
   z-index: 1100;    
}
in 
https://github.com/umbraco/Umbraco-CMS/blob/853087a75044b814df458457dc9a1f778cc89749/src/Umbraco.Web.UI.Client/src/less/components/notifications/umb-notifications.less

if there is no other case where this behavior is desirable

### PR DESCRIPTION
**Pull request by bielu**
If there's an existing issue for this PR then this fixes #6065

As described in issue step to test that:
Steps to reproduce
Create a custom tree in BackOffice.
Add a menu alternative that opens a dialog and trigger either success, error or warning in notificationsService.

Expected result
You can see the full notification, and read the text

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks very much @bielu ! 

It looks like this is your first accepted contribution for Umbraco CMS, congrats! 🎉

You have earned yourself a contributor badge on Our for this one, congrats!  https://our.umbraco.com/members/id:275715/ 🏅

**Comment by bielu** [comment]
It wasn't first 🤣🤣 I had 2 already merged for v8

**Comment by nul800sebastiaan** [comment]
Haha! Weird, GitHub says you're a first-time contributor! And you didn't have your badge on Our yet, so now you've earned that one! 😊

**Comment by bielu** [comment]
Just to show:
Screenshot_2019-08-13-21-42-58-227_com android chrome
I had 2 merged by Shannon🤣🤣

**Pull request merged**
