### PR TITLE
Fix issue with Removing after unpublish parent

### LINKED ISSUE #8393: V7: it is impossible to remove node with children after unpublish only parent.
v7: 7.15.4
Steps to reproduce:
1) install Umbraco with Starter Kit
2) Unpublish about Us
3) Try to remove About Us
Expected result:
About us with childrens will be moved to trashbin
Actual result:
image

### PR DESCRIPTION
**Pull request by bielu**
### Prerequisites

- [ ] I have added steps to test this contribution in description of related issue

If there's an existing issue for this PR then this fixes #8393

### Description

@nul800sebastiaan  here you have PR with proposed fixed

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks @bielu that does the trick indeed! 👍

**Comment by nul800sebastiaan** [comment]
Hmmm, forgot that the unit tests were failing, I'll need to have a look.

**Comment by nul800sebastiaan** [comment]
Aha, the path of the descendants is not being updated, so we don't see that the descendants are in the recycle bin..

**Comment by nul800sebastiaan** [comment]
Super annoying, I tried to make a failing unit test, if I move the code back that you moved then everything is fine in the unit test, but not in the interface. If I use your updated code the unit test is failing but the interface is fine! 😱 


```csharp
[Test]
public void Can_Move_Content_Structure_With_Unpublished_Parent_To_RecycleBin_And_Empty_RecycleBin()
{
    // Arrange
    var contentService = ServiceContext.ContentService;
    var contentType = ServiceContext.ContentTypeService.GetContentType("umbTextpage");

    // Publish all the content items in the tree
    var content = contentService.GetById(NodeDto.NodeIdSeed + 1);
    contentService.SaveAndPublishWithStatus(content, 0);

    var descendants = contentService.GetDescendants(content).ToList();
    foreach (var descendant in descendants)
        contentService.SaveAndPublishWithStatus(descendant, 0);

    var subsubpage = MockedContent.CreateSimpleContent(contentType, "Text Page 3", NodeDto.NodeIdSeed + 2);
    contentService.SaveAndPublishWithStatus(subsubpage, 0);

    // Unpublish only the parent - see issue https://github.com/umbraco/Umbraco-CMS/issues/8393
    contentService.UnPublish(content, 0);

    // Act
    contentService.MoveToRecycleBin(content, 0);
    descendants = contentService.GetDescendants(content).ToList();

    // Assert
    Assert.That(content.ParentId, Is.EqualTo(-20));
    Assert.That(content.Trashed, Is.True);
    Assert.That(descendants.Count, Is.EqualTo(3));
    Assert.That(descendants.Any(x => x.Path.Contains("-20") == false), Is.False);

    //Empty Recycle Bin
    contentService.EmptyRecycleBin();
    var trashed = contentService.GetContentInRecycleBin();

    Assert.That(trashed.Any(), Is.False);
}
```

**Comment by bielu** [comment]
@nul800sebastiaan I am also looking into issue with uni tests, maybe I will find something here :)

**Pull request merged**
