### PR TITLE
3463 - Suggestion: Make checkboxes look prettier in checkbox lists

### PR DESCRIPTION
**Pull request by BatJan**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues/3463) for the proposed changes in this PR, the link is: https://github.com/umbraco/Umbraco-CMS/issues/3463
- [x] I have added steps to test this contribution in the description below

### Description
I aligned the checkboxlist to look and feel a little more like the rest of the UI we now have in the Umbraco backoffice.

So before the checkboxes would look like this
checkbox-list-before

And now they look and behave like this
checkboxlist-after

Please let me know if I should do further tweaks or change something 😃

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @BatJan 

Those really are pretty checkboxes! We'll have a look over and be in touch if we need to be.

Hope DK Fest went well!

Em

**Comment by BatJan** [comment]
Thanks @emmaburstow 😃 

Yes it was a really good day and well organized and interesting talks and workshops 👌

**Comment by poornimanayar** [comment]
Hi @BatJan ,

Really pretty checkboxes! And totally love the gifs :-) I am going to give this a spin.

Poornima

**Comment by poornimanayar** [comment]
Hi @BatJan,

I havent fully tested this across the browsers, but one thing which caught my eye is how the labels wrap. I have tried it on a 7.12.x and cant recreate it there. Perhaps you could give a quick check?
image

Poornima

**Comment by nul800sebastiaan** [comment]
@BatJan Additionally, I think the animations are too slow, like the radiobuttons. I think I set them to `.05` there :-)

**Comment by nul800sebastiaan** [comment]
@BatJan I already updated the radio buttons ;-) You even asked me since when I do CSS! :-D

**Comment by nul800sebastiaan** [comment]
Aha! Then don't mind me! 🤦‍♂️ 
I do remember trying .05 but I guess .1 was good then! 👍

**Comment by BatJan** [comment]
However the animation on the arrow is still set to 0.3 both places - I can try setting that to 0.1 too. But that will then also need to be done on the radio button thingy :-)

**Comment by nul800sebastiaan** [comment]
@BatJan Please note, the same problem with long descriptions is present for the radiobutton customizations. Can you apply any fixes from here to there as well? It's okay to do in the same PR.

image

**Comment by BatJan** [comment]
@nul800sebastiaan I fixed the label issue with the radio buttons in this PR too.

**Comment by poornimanayar** [comment]
Hi @BatJan ,

I have tested all the fixes for checkboxes and radiobuttons and I can confirm that its all looking good! They are indeed really pretty! Great work as always!

Poornima

**Comment by ronaldbarendse** [comment]
I agree this looks a lot better, but just want to point out (judging by the posted screenshots):

- There's quite some white-space above the input fields, ideally I would horizontally align the property name with the text of the first item (move them 15px upwards) or else use the same distance as the textbox has (15px from divider to input, so move them 12px upwards);
- The text of the radio buttons are 41px apart, while the checkboxes are 40px (slight difference), but the original checkboxes were 25px apart: that's an 60% increase in height! Having a lot of items (or multiple properties) would make the page considerably longer and that's not something I would be happy about;
- The current toggle button (`umb-toggle`) has a height of 24px and the check icon a font-size of 15px: both radio buttons and checkboxes differ from this existing style (checkbox height: 22px, icon size: 13px);
- Also make sure the item text of both radio buttons and checkboxes are vertically aligned, e.g. start the text 34px from the left, so both have 10px between the radio button/checkbox and the text.

**Comment by BatJan** [comment]
Ok, so I have just given this a new spin making the checkbox smaller and adjusted the margins etc. - I've done both the radio buttons and the checkboxes in this PR since #3225 has been closed.

The radio buttons now look like those @nul800sebastiaan referenced in his screendump.

It should all look better now and act more like what you expect from the default radio and checkboxes just in a nicer customized manner that will be the same cross browser too.

Please see the gif below to get an idea about how it looks and works now.

radio-buttons-and-checkboxes

**Comment by nielslyngsoe** [comment]
@BatJan Much nicer, thanks.

I though have two minor details that I would like to get implemented.

1. In the radio-button list you can only tab to the selected radio-button, which makes is hard to change your choice with the keyboard.

2. Could we split the code for the checkbox-list, so we have umb-checkbox-item and umb-checkbox-list. In this way we would be able to use the checkbox for a single checkbox. Also so we can use the checkbox as part of a more complex list item.
( I understand that I could do that already today, but its more nice if its scoped/named correctly, and thereby easier to find in the future. My point is if your only using the umb-checkbox-item, you wouldn't find it natural to look in the checkbox list code. )

Let me know what you think about that, and ones its ready I will make sure it gets merged into V7 and as well in V8.

**Comment by BatJan** [comment]
Hi @nielslyngsoe - Thanks for getting back to me on this one :-)

1: I'll have a look and see what's going on 👍

2: Yes I agree it would be much nicer too. Actually I was thinking about refactoring the whole thing so the checkbox itself could be a directive, which would be it easier to reuse throughout the UI, which was going to be my next step once this is in core anyway 😉 

I'll see if I can find some time for looking into this this week and give you a ping when I have something ready.

Happy v8 release celebration btw! 🍻

**Comment by BatJan** [comment]
Hi again Niels

Regarding issue number 1 you mentioned above - I created this Codepen to make sure I remembered it correctly - What you experience in my PR is the same as the default behavior using regular radio buttons. Try it out here https://codepen.io/BatJan/pen/WmbxLd - It is how it works out of the box and since the only thing I do is to visually hide the real radio button and make use of the :checked pseudo selector to make the custom look and feel I don't ever touch the default behavior. I was a bit surprised about this myself as well when I tested things 😃 - But that's how it works. 

So initially you tab through the possible radio buttons and when you have selected the one you need to check then you hit the "space" key. After that the way you select another option is by using the up and down arrows, which also works in the PR. So I would say that this actually works as expected.

Now, had the name of each radio button been different you would be able to tab through each of the buttons but that would also allow you to select all of them, which is not the intention 😃 

I'll see what I can do about your second suggestion now. Stay tuned 😎

**Comment by BatJan** [comment]
Sorry for the spam @nielslyngsoe 😇 

I have now done a refactor of the code to simplify it a lot - I have done as you suggested but I went with "umb-form-control" instead and then added "--radiobutton" and "--checkbox" modifiers so when re-using the checkbox one would look for the "umb-form-control--checkbox".

Making a generic block for this will save us some code duplication and make it easy to reuse the checkbox styling.

However as I mentioned I will also look into making a checkbox directive, which will make it even easier to re-use throughout the UI. I have changed the state of the PR back to WIP and will change it once this one is ready for review again.

Regarding the first comment I noticed that the :focus style was not being set on the radio button - That has also been fixed and makes it a little easier to see when the radio button actually has focus. Sorry for the long explanation above if this is actually what you meant in that comment 😃 

I'm looking forward to receiving your input and thoughts.

**Comment by nielslyngsoe** [comment]
Hi @BatJan

I agere on everything :-D

Also my bad for falsely remembering how the radio buttons work — great that you investigated!

**Comment by BatJan** [comment]
@nielslyngsoe Great 😄 

I have now created 2 new directives - One called "umb-checkbox" and one called "umb-radiobutton". I figured that having the radio button as a directive as well would be a good thing in order to make it easier for package developers to reuse the same look and feel in case they make use of the radio buttons - And of course if there is somewhere in the backoffice where it could make sense to reuse it.

I hope you like what you see 😃 - And please let me know if you have any further requests or questions.

Yeah I was also a bit confused about it when I started working on the PR - I guess I've not been using my keyboard much to navigate forms before 😆

**Comment by nielslyngsoe** [comment]
Hi @BatJan 

Perfect, I did though decide to rename umb-form-control to umb-form-check.
I thought the name control was too generic, where this now states that its for forms that will be checked.

I will merge, celebrate and then I will bring it to V8 as well.

**Comment by BatJan** [comment]
Wuhu! 😃 It's all fine by me 🙌

**Pull request merged**
