### PR TITLE
U4-9282 Rollback not working

### PR DESCRIPTION
**Pull request by Shazwazza**

### CODE REVIEW

**Comment by aboanas1** [comment]
hi
I need to start umbraco from the first steb , kan you help me to start step
by step.
thank you
Mohamad

2016-12-19 8:59 GMT+03:00 Shannon Deminick <notifications@github.com>:

**Comment by nul800sebastiaan** [comment]
Hi @aboanas1 ! Spamming Github pull requests is not going to help.
We have a few resources available that you can check out:
Video tutorials at https://umbraco.tv
Documentation on our community site: https://our.umbraco.org/documentation/
You can ask specific questions at the forum: https://our.umbraco.org/forum/'
And of course if you have issues, there's a lot of information to be found in Google.

Good luck and have fun discovering Umbraco!

**Comment by ruskom** [comment]
Hello,

Do you know when this change will be released to Umbraco Cloud?
We suffer from this rollback issue a little bit.

Thank you.

**Comment by nul800sebastiaan** [comment]
@ruskom Yep, it will come early next week!

**Comment by ruskom** [comment]
Fantastic news. Thank you.

**Pull request merged**
