### PR TITLE
U4 6297

### PR DESCRIPTION
**Pull request by AussieInSeattle**
As per comments in U4-6297.  

To use this merge:

add expected config.settings in your grid.editors.config.js file as follows:
{
    "name": "RWC Headline",
    "alias": "rwc-headline",
    "view": "/app_plugins/rwc.grid.headline/editor.html",
    "render": "/app_plugins/rwc.grid.headline/editor.cshtml",
    "icon": "icon-coin",
    "config": {
        "settings": [
                {
                    "label": "Hide Background?",
                    "description": "Check if you want to hide the gray'ish background color for the header",
                    "key": "hideBackground",
                    "view": "boolean"
                }
        ]
    }
}

It results in anew icon next to your control that will show the "settings editor" for whatever you have defined in config.settings above - therefore a very quick way to put together some custom ui on a control.

Then in your view you can use:
control.value.settings.hideBackground

Then in your render you can use:
Model.value.settings.hideBackground

### CODE REVIEW

**Comment by Shazwazza** [comment]
Cool, have added comments to the issue. In the future make sure you update the issue with 'Fix submitted' = pull request and link back to this PR please :)

**Comment by AussieInSeattle** [comment]
Good feedback - I was following this guide:
http://24days.in/umbraco/2014/your-first-pull-request/

Can you please have Seb update it with the last step (update the issue with the PR link and "Fix Submitted") - I'm sure a lot of new PR'ers will use that guide as it's the best one out there.  (Have also commented on the article above).

**Comment by Jeavon** [comment]
@AussieInSeattle just tried out this PR, great work!

**Comment by AussieInSeattle** [comment]
@Jeavon Thanks mate.  I need to modify the PR slightly from some changes that I made - in the dialog callback within editControlSettings fucntion I removed the if statement stuff and simply do:
control.settings = data.config;

**Comment by AussieInSeattle** [comment]
@Shazwazza - I'm a PR newbie - how do you modify a PR as per the small change mentioned above?

**Comment by Jeavon** [comment]
@AussieInSeattle just push further commits to AussieInSeattle:U4-6297 and they will get added automagically to the PR

**Comment by AussieInSeattle** [comment]
@Jeavon - thanks - i just committed the change to that branch on my side (under AussieInSeattle in github) - do I need to push the updated PR back across to Umbraco-CMS or am I done?

**Comment by Jeavon** [comment]
You're done, you can watch you changes build and hopefully pass the 2711 tests! https://ci.appveyor.com/project/SebastiaanJanssen/umbraco-cms-hs8dx/build/198

**Pull request merged**
