### PR TITLE
Fix notifications not sending when user has multiple of same type

### LINKED ISSUE #4713: Notifications not sending to user who has same notification for multiple content items
Notifications not sending when user has notifications configured for multiple content items.

### Bug summary

When a user has multiple notifications of the same type on different content items that are at the same level, they don't receive a notification. If user removes one of the notifications from one of the content items, so they've only got one notification set up on a content item, the notification will successfully send. 

Tried having two different notification actions ("Create" & "Send To Publish" in our case) on the different content items and the notifications send as expected.

### Specifics

Using Umbraco `7.13.2`. Client reported issue after upgrading from `7.10.5`.

### Steps to reproduce

Add the same notification on multiple content items at the same level. Perform action that would trigger notification.

### Expected result

User should receive notification.

### Actual result

User doesn't receive notification.

### PR DESCRIPTION
**Pull request by peterkeating**
### Prerequisites

Fixes #4713.

### Description

When working on this I decided to change the logic so instead of looping over each of the users within a batch, it loops over the notifications associated to the batch of users. 

There are a couple of rules that might require some discussion but can easily be tweaked.

- If one of the entities matches a notification for the user, only send a notification for the entity that first matches
- Only send one notification to a user, don't send multiple notifications for the same action to the same user

These two rules was what made me favour a `while` loop over a `foreach` on `notifications`.  The `isMatched` property and `break` (on line 160) are ensuring multiple notifications aren't sent to the same user.

I've branched from `v7-dev` as we came across this issue with an Umbraco 7.13.2 install, however looking at `NotificationService` on the `v8-dev` branch, the same issue will occur.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @peterkeating!

First of all, congrats on making your first PR to this repo! Secondly, thanks for all the documentation you've done too. It really helps us assess the work when contributions are this detailed. 

We'll take a look at the code, test that everything works as it should do and then merge if we're happy. If there's something we need to know a little more about or that needs clarifying, we'll be in touch to ask. 

Once the work is merged, you'll get a shiny contributor badge on your our.umbraco.com profile :)

Emma, [Pull Request team](https://umbraco.com/blog/introducing-the-new-pr-team/)

**Comment by Newnab** [comment]
Hi @emmaburstow ! Hope you're doing well (we met recently at the UK festival, if you needed the reminder :) )

I know you're probably super busy, but I just wanted to just nudge this and see how it's getting on - is there any kind of timeframe for getting it merged in? :) It's something one of our customers is chasing, so I thought I'd see if there was any movement yet.

**Comment by Newnab** [comment]
Just another nudge on this, wondering if there's any update?

**Comment by Newnab** [comment]
Hello! Just poking this again to see if there was any update or resolution?

**Comment by nul800sebastiaan** [comment]
Hi @Newnab - Thanks for this! The code looks fine, I need a little help understanding something though:

`// when a match has been found, skip other notifications for user.`

So say I have multiple *different* types of notifications set up for a content item, shouldn't I get all of them? I will admit I've not used the built-in notifications system for a long long time so I can't remember exactly how that all works. If you can clarify why we need to remove the rest of the notifications for the user then that would be helpful!

**Comment by DannerrQ** [comment]
Hi all,

Has there been any progress on this? Currently experiencing the same issue. We technically can work around it by switching notifications to the parent node, but that's not ideal as we only want notifications on some of the nodes.

**Comment by DannerrQ** [comment]
> So say I have multiple _different_ types of notifications set up for a content item, shouldn't I get all of them? I will admit I've not used the built-in notifications system for a long long time so I can't remember exactly how that all works. If you can clarify why we need to remove the rest of the notifications for the user then that would be helpful!

Hi @nul800sebastiaan, I'm not the original dev on this but I've been looking at the code and think I may be able to help clarify. `SendNotifications` gets called separately for each different type of notification (e.g. it gets called for update, then called again for publish when clicking on 'Save & Publish').

So.. the code at this point is only removing other notifications _of this type_ (see the `action` parameter). It's important to remove the rest of the user's notifications at this point so that they don't get sent twice, e.g. if there's notifications set on two different ancestor nodes.

**Comment by peterkeating** [comment]
@DannerrQ Thanks for clarifying, I did think that was the case but wanted to debug it again locally to make sure.

**Comment by nul800sebastiaan** [comment]
Thanks @peterkeating and apologies for the long wait! The code is a little bit complex so it had to be reviewed and tested thoroughly. With all the big releases in the last few months this has proven to be difficult.

Well done on your first PR for Umbraco CMS as well, great job! 🎉

You are now the proud owner of a shiny new Contributor badge on Our Umbraco https://our.umbraco.com/members/id:276914/ 🎖

**Pull request merged**
