### PR TITLE
U4 11334 Content type edit, click on icon always shows black empty icon

### PR DESCRIPTION
**Pull request by mvanhelmont**
### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description
This issue is there for a very long time. Everytime I want to edit any content type and change the icon, when I click on it, Umbraco always gives me empty black icon, instead of selected icon and color I want to change.

iconpicker2

Issue: http://issues.umbraco.org/issue/U4-11334

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hiya @mvanhelmont 

The code looks sound to me but one of the checks has failed. Could you have a look at the appveyor results and see what you can do? I can see there's a duplicate name issue from the test(umbTestPage) but can't see evidence of that in the files you've committed so it's probably a red-herring. 

Emma, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-pr-team/)

**Comment by mvanhelmont** [comment]
Hi @emmaburstow 

I think it has nothing to do with my code indeed. Looks more like this PR: https://github.com/umbraco/Umbraco-CMS/pull/2610

Has merged 5 hours ago and added the test CanRegisterConsentWithoutComment.

**Comment by abjerner** [comment]
@mvanhelmont As you're already onto, AppVeyor may fail because of things unrelated to your pull request (which I'm pretty sure is the case here).

I also gave your code a spin, and it works like a charm 👍 

Anders, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by emmaburstow** [comment]
Thanks @abjerner!

**Comment by nul800sebastiaan** [comment]
Works great @mvanhelmont - very nice UX improvement, thanks! 👍

**Pull request merged**
