### PR TITLE
Update Google JS to HTTPS

### PR DESCRIPTION
**Pull request by kolchy**
Failing to load over a HTTPS connection.

### CODE REVIEW

**Comment by Shazwazza** [comment]
thanks! i don't think we ship with this but good to have it correct

**Comment by Shazwazza** [comment]
Can you re-target dev-v7 ?

**Comment by kolchy** [comment]
Thought I had already? Tried again... dev-v7.6 yeah? couldn't find a dev-v7
only branch?

**Comment by nul800sebastiaan** [comment]
Okay, that was a bad idea.. suddenly there was a million changes when I retargeted it (see below)
Thanks, I'll update this is manually into `dev-v7`!


image

**Comment by nul800sebastiaan** [comment]
https://github.com/umbraco/Umbraco-CMS/commit/a57abce96ef8bd4253683900805a769746e64146

**Pull request closed without merging**
