### PR TITLE
Adds dropshadow to logo so its discernible on light backgrounds

### PR DESCRIPTION
**Pull request by skttl**
This one adds a drop shadow (in the same color as the default background) to the svg logo used for the login page. When setting a light login background, the logo is hard to see, this PR tries to fix that:

Before (on light and dark backgrounds)

msedge_TvO8p39Z8o

msedge_eKXIsLlQkr

After (on light and dark backgrounds)

msedge_RE3izwhNla

msedge_3S9hqdl88F

### CODE REVIEW

**Comment by bjarnef** [comment]
I see the idea, but I don't think Umbraco in general use shadow on the logo in the product or in marketing.
If developers for some reasons want to customize the login screen with a light background, they should probably change the logo anyway - either a different version of the Umbraco logo or another custom logo.

I think the blue Umbraco logo would fit better on a light background.

Maybe their should be some alternative versions here like black and blue:
https://github.com/umbraco/Umbraco-CMS/tree/v9/contrib/src/Umbraco.Web.UI.Client/src/assets/img/application

**Comment by skttl** [comment]
Or maybe the logo could be inlined and then the fill color can be configurable?

**Comment by bjarnef** [comment]
In this case it could be an inline SVG, but developers can also use both png and svg images, so probably not easy to make a generic rule if people using a white png logo on transparent background with a light background color.

I would say it is up to the developer to configurate this.
We already have the following options:

- Configurable background image
- Configurable background color

The default background color is `#162335`:
https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Web.UI.Client/src/less/pages/login.less#L16

So I guess the light background color is when you inject custom CSS, but in that case you could just specify another logo.
It would however be useful to add a few alternative color versions of the Umbraco logo, e.g. `#000000` and `#3544b1`.

image

**Comment by nathanwoulfe** [comment]
I agree this requires input from HQ - logo treatment can be a delicate issue for marketing/brand teams 😸

**Comment by nathanwoulfe** [comment]
I've raised this on Slack, will see what the response looks like

**Comment by nathanwoulfe** [comment]
HQ verdict is nay to drop shadow, but yay to shipping the dark logo variant as well, which is available from https://umbraco.com/about-us/press/

I'd expect a nay to inline SVG allowing any fill colour as that would also create opportunities for non-compliant logos (ie hot pink logo, pattern-filled logo etc)

**Comment by bjarnef** [comment]
@nathanwoulfe yeah, shipping with a `umbraco_logo_blue.svg` and `umbraco_logo_black.svg` as well would be great.

**Comment by emmagarland** [comment]
Hi again @skttl!

I've just rebased this one to `contrib`.

The .svg file now has a conflict since the changes were made a while ago. 

Please let me know if you need anything,

Best,

Emma 🙂

**Comment by skttl** [comment]
Thanks @emmagarland 

The logo has changed from being just the icon, to now include the word "umbraco" too. I've fixed the conflict for you :)

**Comment by skttl** [comment]
Although, has HQ changed stance on the drop shadow? cc @nathanwoulfe 

> HQ verdict is nay to drop shadow,

**Comment by emmagarland** [comment]
Hi @skttl 

This has been discussed with HQ and we won't be changing to a drop shadow for the logo at this time. 

However, the issue of a light logo on a light background has been considered by HQ internally and could be a consideration for future login screen designs. 

You would be welcome to create a [feature request](https://github.com/umbraco/Umbraco-CMS/discussions/new?category=features-and-ideas) for the option of choosing a dark Umbraco logo instead of a light one, if that would be something that would help in this use case here?

For the meantime, I will close this PR, but really appreciate the effort and the thought that this has generated. 👍 

Best wishes,

Emma

**Pull request closed without merging**
