### PR TITLE
MemberModelMapper to return member groups ordered alphabetically

### PR DESCRIPTION
**Pull request by Geckex**
MemberModelMapper.GetMemberGroupValue - order member groups alphabetically by name.

### Prerequisites

This fixes: https://github.com/umbraco/Umbraco-CMS/issues/5507

### Description
This is used in ContentPropertyDisplay class - for UI purposes only.

image

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @Geckex 

And thanks for your first PR to this repo. We'll take a look at the code, check nothing breaks and if we're happy, we'll merge. When we do, you'll get a nice new contib badge for your Our.Umbraco.Com profile.

Thanks,

Emma, [Pull Request team](https://umbraco.com/blog/introducing-the-new-pr-team/)

**Comment by nul800sebastiaan** [comment]
Thanks very much @Geckex - this has been driving me crazy over the years haha!

Congratulations on your first pull request to Umbraco CMS as well, well done!

I'd love to give you a contributor badge on Our Umbraco, is this your profile over there? https://our.umbraco.com/members/id:2698/

**Comment by Geckex** [comment]
Hi Sebastiaan - great news, thanks.

My profile is this one: https://our.umbraco.com/members/id:13672/

Thanks again - let me know if anything else is bugging you ;0)
(In Umbraco I mean ;0)

**Comment by nul800sebastiaan** [comment]
@Geckex Aha, that's where you're hiding! You've now got that shiny contributor badge on your Our Umbraco profile 🎖 👍

**Comment by Geckex** [comment]
That’s great - thanks

**Pull request merged**
