### PR TITLE
Makes sure supplied arguments cannot be used more than once.

### PR DESCRIPTION
**Pull request by dknippers**
### Prerequisites
PR for #7777 to discuss a possible solution.

### Description
This commit simply makes sure none of the supplied arguments can be used more than once, which I believe is the issue here.

### CODE REVIEW

**Comment by emmary2020** [comment]
Hey @dknippers 

Thanks for the PR. Much appreciated. We'll take a look and let you know if we've any questions. 

All the best,

Em

**Comment by dknippers** [comment]
Hi @nul800sebastiaan,

You register it with the container as an `IThing`, but you later request a `Thing4` which is not registered. So this crash makes sense. You have 2 options:

1) Request an instance of `IThing` (it will not have `.Thing` and `.Thing2` properties though).
2) Register it as a `Thing4`

Regardless, the test should be done with 2 parameters of the same type. @tompipe used 2 parameters of type `string` in his issue, for example. In your code it uses `Thing1` and `Thing2`, which are not the same type so the Assert will always be true, even without this PR.

I have pushed a version of `CanRegisterSingletonWithCreate` to this PR that will fail without this PR and succeed after this PR. In there, I use the same type for both parameters (`Thing1`). That is what the issue was about (multiple parameters of the same type, but all parameters get set to the first value of that type).

Let me know if that unit test was helpful, or if you wanted to test something else!

**Comment by nul800sebastiaan** [comment]
Duh.. well that makes total sense now, thanks!

Yay, it fails! And is fixed with this PR. 👍 

```csharp
        [Test]
        public void CanRegisterMultipleSameTypeParametersWithCreateInstance()
        {
            var register = GetRegister();
            var factory = register.CreateFactory();
            register.Register<Thing4>(factory =>
            {
                var param1 = "param1";
                var param2 = "param2";

                return factory.CreateInstance<Thing4>(param1, param2);
            });
            var instance = factory.GetInstance<Thing4>();
            Assert.AreNotEqual(instance.Param1, instance.Param2);
        }
```

image

**Comment by nul800sebastiaan** [comment]
Ah I see you already updated the tests @dknippers - wonderful! ⭐ 

Great to have tried it myself as well as I saw the error in me trying to use 2 params of a different type, which was not the problem!

**Comment by nul800sebastiaan** [comment]
I've [moved the test into a separate test and used the strings for a clearer error](https://github.com/umbraco/Umbraco-CMS/pull/7814/commits/558ffaeba70e922240a124a47faa1718a8f3e0be), this error now is a bit confusing: 

```
Umbraco.Tests.Composing.ContainerConformingTests.CanRegisterMultipleSameTypeParametersWithCreateInstance

  Expected: not equal to <Umbraco.Tests.Composing.ContainerConformingTests+Thing1>
  But was:  <Umbraco.Tests.Composing.ContainerConformingTests+Thing1>
```

Other than that, this is great, thanks very much @dknippers!

**Pull request merged**
