### PR TITLE
Added check for publish permissions to remove option for Publish At a…

### PR DESCRIPTION
**Pull request by madden-tom**
…nd Unpublish At if the user doesnt have Publish permissions

Hi,
I had 2 routes to implement this simple change, though none of them felt 100% ideal they both solve the problem. I've added nulls to the properties list where the permissions don't allow it and then stripped out any nulls at the end because Umbraco doesn't like this nulls present and leaves and empty Properties page. This leaves some nice looking code, but feels awkward because I'm adding and then removing items from the list

The alternative I came up with was to change the constructor for the properties to not include the release and unpublish items and use an insert to add them after the constructor, but this meant hard coding the locations in the list to keep them in the same order as is standard in Umbraco.

Hope this makes sense :)
t

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Ha! The joys of working with an older codebase. Looks fine on the face of it, I'll make some time this week to look at it properly. Thanks so far, love seeing these kinds of contributions!

**Comment by nul800sebastiaan** [comment]
Note to self/reviewer: need to test what happens if someone else saves data in the publishdates and someone who doesn't have these fields then saves the same document. Need to make sure values don't get cleared out.

**Comment by madden-tom** [comment]
Okay, I experimented with different users making amendments and found Umbraco didn't like the hidden fields (I should have tested a bit more, sorry), so I have changed the fields to be display only when relevant and this seem to work whether edited by an admin or by a writer, preserving values between users and doesn't involve the previous dealing with null items - woohoo!

**Comment by nul800sebastiaan** [comment]
Whoop! Good one, thanks for looking further into this! Will give it a go as soon as I have a bit of time this week.

**Comment by nul800sebastiaan** [comment]
Great! All merged in and will be released with 7.4.3. #h5yr!

**Pull request merged**
