### PR TITLE
Update default greens in variables.less to provide better contrast.

### PR DESCRIPTION
**Pull request by nagolucky18**
Lighthouse accessibility tool identified the green selected for "Login" (and other) buttons as low-contrast. Change default greens to offer more contrast.

### Prerequisites

- [X] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes [15070](https://github.com/umbraco/Umbraco-CMS/issues/15070)

### Description

The following changes were made:

- Changed the default green colors in "variables.less" to provide better contrast. This is because Google's lighthouse accessibility tool identified the current green as low-contrast. See below for old green vs. new green.

Old:
279119582-2e650c40-a633-4ef1-b835-e3066eb955b5

New:
new_green

To test the changes:

1. Open Umbraco without logging in **in Chrome** (Edge may also work for this)
2. From the developer tools, navigate to the "Lighthouse" tab.
3. Click "Analyze Page Load" with the "Accessibility" checkbox checked.
4. Observe the output. Notice that there are no issues with contrast.

**Note:** Because this is a variable, other styles that use this green are also affected. This should, in theory, fix any other accessibility issues due to the use of this green.

### CODE REVIEW

**Comment by mikecp** [comment]
Hi @nagolucky18 ,

Thanks for this update.! I'll quickly check with HQ whether the "new greens" are OK for them or not and I'll keep you posted of their answer.

Cheers!

**Comment by mikecp** [comment]
Hi @nagolucky18 ,

Sorry for coming back to you so late 😬
Thanks a lot for your patience!

It seems that HQ updated the colors of their UI Library components to have better contrasts (and they pass the A11Y tests), so they suggest to use the same green(s) as in the UI LIbrary. So it would be super great if you could adapt your change to use one of the UI LIbrary greens. 
Let me know if you need any help with this and I'll get back to you quicker this time 😁

Cheers!

**Comment by nagolucky18** [comment]
@mikecp 

> Hi @nagolucky18 ,
> 
> Sorry for coming back to you so late 😬 Thanks a lot for your patience!
> 
> It seems that HQ updated the colors of their UI Library components to have better contrasts (and they pass the A11Y tests), so they suggest to use the same green(s) as in the UI LIbrary. So it would be super great if you could adapt your change to use one of the UI LIbrary greens. Let me know if you need any help with this and I'll get back to you quicker this time 😁
> 
> Cheers!

No worries! I get it, with the holidays and such. I'm not familiar with the location of the UI Library file(s). Is there a directory you could point me to? Or otherwise a commit or Github item where the update was made? Thanks.

**Comment by mikecp** [comment]
Hi @nagolucky18 ,

The files are in fact located in the [Umbraco.UI](https://github.com/umbraco/Umbraco.UI) repository, and I believe that this PR might be the one we're looking for 😁

https://github.com/umbraco/Umbraco.UI/pull/648

I hope this helps, let me know if you need anything else 😉

Cheers and have a good week-end!

**Comment by nagolucky18** [comment]
@mikecp It looks like the greens in that commit still fail the lighthouse accessibility test from Google. The values in [https://github.com/umbraco/Umbraco.UI/pull/648](https://github.com/umbraco/Umbraco.UI/pull/648) were selected because they passed A11Y though, so I'll go ahead and push the commit that updates them to closely resemble the new greens if that is OK.

**Comment by nul800sebastiaan** [comment]
Hey @nagolucky18 - we're currently working on a slightly refreshed color scheme for v15, which should take contrast into account as well. Therefore, I will close this PR in favor of the upcoming work from HQ. 
Thanks very much for this first attempt, we appreciated it!

**Pull request closed without merging**
