### PR TITLE
Fixes U4-8310 - allows rename of content type alias that changes casing only…

### PR DESCRIPTION
**Pull request by AndyButland**
…without being incorrectly validated as using an alias already in use.

### CODE REVIEW

**Comment by mvanhelmont** [comment]
Hi @AndyButland i have some feedback on your PR I know it's a old one already and not merged, I have another fix for it.

Changing line:

`if ((exists) && (ctId == 0 || ct.Alias != contentTypeSave.Alias))`

to

`if ((exists) && (ctId == 0 || ct.Alias.ToLowerInvariant() != contentTypeSave.Alias.ToLowerInvariant()))`

works also and I don't see any disadvantages, don't know what the PR Team thinks about it?

**Comment by AndyButland** [comment]
Does look quite a bit simpler!  Free free to create a new PR for this with your solution @mvanhelmont, and mark it as an alternative to this.  The PR team can then close this one and hopefully review and pull in yours.  FWIW I'd go with @AliSheikhTaheri's second version above.

**Comment by mvanhelmont** [comment]
@AliSheikhTaheri it's all yours if you want #H5YR

**Comment by AliSheikhTaheri** [comment]
Thanks guys created a PR for it: https://github.com/umbraco/Umbraco-CMS/pull/2884

**Comment by nul800sebastiaan** [comment]
Thanks gentlemen, I merged @AliSheikhTaheri's change! Nice and easy 👍

**Pull request closed without merging**
