### PR TITLE
Documentation for recently merged UmbNodePreview 'alias' property

### PR DESCRIPTION
**Pull request by AdamPrendergast**
Documentation added to support the recent merged change to add alias property to UmbNodePreview.

Related to this issue: http://issues.umbraco.org/issue/U4-11437

### CODE REVIEW

**Comment by dawoe** [comment]
Hi @AdamPrendergast 

Thanks for this PR. We will try to review it in max 14 days.

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by dawoe** [comment]
@nul800sebastiaan 

I see changes in this PR that should already be part of #2692 which is merged in dev-v7 eg. injecting userservice in the controller

What could be the cause ?

Dave

**Comment by AdamPrendergast** [comment]
@nul800sebastiaan @dawoe Apologies... I did in fact create it from my branch. Let me recreate it again branched off an up to date dev-v7.

**Comment by nul800sebastiaan** [comment]
No apologies needed! We're here to help!

**Comment by AdamPrendergast** [comment]
@nul800sebastiaan @dawoe I now have everything synced with upstream dev-v7.

I've just merged it all in to this branch to avoid having to create a new PR.

The changes should now just contain of the small documentation changes

**Comment by nul800sebastiaan** [comment]
Wonderful! All merged, thanks again!

**Pull request merged**
