### PR TITLE
U4-9151 Bug fix for getImagePropertyValue typeerror

### PR DESCRIPTION
**Pull request by JustAGuyTryingToCodeSomething**
Calling getImagePropertyValue  on mediahelper.service.js  - mediaHelper.getImagePropertyValue({ mediaModel: item}) - resulted in a type error.

- Problem caused by a reference to imageProp.value instead of imageProp.value.src. 
- Amended mediahelper.service.js to return the image path using ImageProp.value.src.
- Added unit test as umb-media-helper-spec.js to test path is returned using a dummy imageModel.

Note: The src attribute is being added by ImageCropperPropertyEditor.cs line 219  - p.Value = "{src: '" + p.Value + "', crops: " + crops + "}"; following a PostAddfile request; and is reflected in database table cmsPropertyData (dataNtext). I have presumed the addition of this src attribute is desirable and not the true bug.

### CODE REVIEW

**Comment by arknu** [comment]
You might want to allow for both using the value directly and using value.src, as it is still an option to use a regular upload field for images (even though Image cropper is now default). Also, this would break for upgrades still using an Upload field.

**Comment by JustAGuyTryingToCodeSomething** [comment]
I'll take another look at it. I wouldn't want to break Upload field.

**Comment by JustAGuyTryingToCodeSomething** [comment]
- Updated code to fallback to imageProp.value if ImageProp.value.src {src:} is not available.
- Couldn't reproduce an image upload without the {src:""} attribute using 7.5.4 property editors (I did try!) but presume there is a legacy issue where  historic database entries will store path directly as string and therefore code needs to be more robust.

**Comment by nul800sebastiaan** [comment]
Hey there @JustAGuyTryingToCodeSomething !

I'm writing today after anouncing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Pull request closed without merging**
