### PR TITLE
v8: Fix package download

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/4965

### Description
This PR fixes package download, so e.g. a package named `Ørskov Test Package` is downloaded as `Ørskov_Test_Package_1.0.0.zip` instead of `Ã_rskov_Test_Package_1.0.0.zip`.

It seems to work both using `HttpUtility.UrlEncode(fileName)` and `Uri.EscapeDataString(fileName)`.

### CODE REVIEW

**Comment by bjarnef** [comment]
Furthermore the filename was not set in `Content-Disposition` header (at least not in Chrome).

image

But it is set when using `HttpUtility.UrlEncode(fileName, encoding)`.

image

I also found this example, but not sure if it is necessary with the brower specific logic.
https://stackoverflow.com/a/35926772/1693918

**Comment by poornimanayar** [comment]
Hi @bjarnef ,

I have tested this PR and it works as expected. However, can you let us know what action we need to take regd the last point on your comments? Does this need more work or is it ready to be merged as-is?

Poornima

**Comment by bjarnef** [comment]
Hi @poornimanayar

It should be ready as it is. It doesn't seem to be neccesary with the browser specific code as in the stackoverflow question.

You could the different package names with `æøå` or e.g. `ä`, `ü` or `é`.

**Comment by nul800sebastiaan** [comment]
Thanks very much @bjarnef !

**Pull request merged**
