### PR TITLE
V8: Prevents user from changing a document type to an element type if it's already been used to create content.

### PR DESCRIPTION
**Pull request by AndyButland**
This PR implements the restriction recommended in issue #5604.

In testing you should find that the option to switch to an element type is disabled for document types that aren't currently element types and have at least one content item created from them.

image

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @AndyButland 

Thanks for the work on this. It's a fantastic fix! We'll take a look and let you know if we need anything,

Em

**Comment by poornimanayar** [comment]
Hi @AndyButland ,

Can you resolve the conflict on this PR? One of us can then test this. Looks like a great feature.

Poornima

**Comment by AndyButland** [comment]
Sure @poornimanayar - I've updated to the latest in `v8/dev` branch and resolved the conflict.

**Comment by poornimanayar** [comment]
Hi @AndyButland ,

I have tested this. Works well! I cannot convert a doc type to an element type or an element type to a doc type once content had been created. I am assuming this is the expected result.

The help text is useful in the case when I am trying to convert a doc type to an element type, but maybe we can capture the other scenario as well where I am trying to convert an element type to a doc type. See my screenshot below. Wouldnt it be better if the help text can tell about element type to document type as well? What do you think?

image


Regards,
Poornima

**Comment by AndyButland** [comment]
I did consider the reverse case - changing an element type to a document type - but seemed it would be a lot more difficult to check for that (as the use of a particular element type will be only found within the data stored for nested content properties, rather than just having to check for a record in the `umbracoContent` table).  So given we're still not checking for that, it didn't seem correct to mention in the help text.  It's probably true you still wouldn't want to change an element type to a document type after it's been used, but you still could if you wanted to.

**Comment by poornimanayar** [comment]
Hi @AndyButland ,

Retested it, all good. I think my pc was misbehaving. I can, for sure, convert element type to doc type and the help text does not appear there. Totally my bad. Wonder what happened there. Anyway, happy to approve the PR. Great work BTW, great addition :-)

Poornima

**Comment by poornimanayar** [comment]
Hello @AndyButland ,

Hope you are well! Read your article [here](https://medium.com/@ThisisZone/moving-away-from-cms-as-a-platform-7cc11033d54), what a great reference point! Enjoyed reading it!

I think its high time we get this merged into v8, so would it be possible for you to fix the merge conflicts and merge the latest `v8/contrib` branch into the PR? I will give it a test again and see how it goes. Apologies for the long wait on this one but I am going through some of the old PRs which I had approved but not yet merged and landed upon this brilliant one! 

Regards,
Poornima

**Comment by AndyButland** [comment]
Hi @poornimanayar - thanks for your comments on the article, glad you enjoyed it.

I've fixed the conflicts now - just a couple in language files, so should be good to move forward with.

**Comment by poornimanayar** [comment]
And merged :-)

**Comment by rogermal** [comment]
A lot of Datatype filtering uses document types that are element types, which is wrong - it should allow all document types to filter on because you may want to create content from a document type that you also want to filter on. How do we alter the Datatype filtering to allow this ?

**Pull request merged**
