### PR TITLE
feat: Expose ComposerGraph for custom composers

### PR DESCRIPTION
**Pull request by nikcio**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

Sometimes when building a plugin it would be nice to control when the composers of the specific plugin is triggered in case you have logic that needs to run before the internal composers in your plugin. So rather than copy-pasting the `ComposerGraph` it would be nice if there was a generic version exposed so you could group your composers within your plugin.

To test the addition create your own composer interface for example `ITestComposer` that inherits from `ICusomComposer` and add a call to `AddComposers<ITestComposer>()`. This should compose your composers.

Example use case: https://github.com/nikcio/Nikcio.UHeadless/pull/211

### CODE REVIEW

**Comment by georgebid** [comment]
Hey @nikcio thanks a lot for this PR! Someone on the core collaborators team will review this soon 😸

**Comment by mikecp** [comment]
Hi @nikcio ,
Thanks for your PR, it's indeed a nice addition to be able to control the composition flow😉
I had a quick look at your changes, and I can already tell you that changing the definition of a public interface is considered as a breaking change and will only be allowed in major versions.
However, I was wondering if you could not achieve the same by "doing the opposite", meaning that you would keep the IComposer interface as is, and then declare your ICustomComposer as implementing IComposer:

```
public interface ICustomComposer : IComposer
{}

```

I did not test this so I might be saying silly things😅 , but this would resolve the breaking change, and also probably simplify the global amount of changes by removing the need to replace IComposer by ICustomComposer in some of the classes you updated.

It would be great if you could try to see if it works that way 😁

Cheers!

**Comment by nikcio** [comment]
@mikecp Yeah it would be great if that worked but this results in the current add composers statement in the setup always running all the composers. And having any subsequent custom add composers statements just running the composers once more. So in this way you wouldn't be able to add services conditionally.

**Comment by bielu** [comment]
This pr reminds me old approach of ICoreComposer, IUserComposer etc, which were removed as it was introducing too much complexity, it was simplified on purpose. I would argue that any composer never should be internal, as they are depedency ordering tool. So if package is registering internal composer, it makes it impossible to control order by additional packages. I would rethink design in this case, instead of introducing this change which will make Order of registration even more complicated than it is already 😓

**Comment by nikcio** [comment]
@bielu I only want to expose the ComposerGraph so you would be able to run your own composers completely disconnected from the standard `IComposer`. I don't want to reintroduce the same approach as `ICoreComposer`, `IUserComposer`, etc.
I just want to make it possible to reuse this class instead of copy pasting it.

In essence this is how I see it being used:
`IComposers` are the default Umbraco composers and there's only one kind. These run in their own context with the `AddComposers()` call in `startup.cs` - TLDR: They keep working as they are now.

You now also have the possibility to have your own composing context by making your own interface from `ICustomComposer`:
```csharp
interface IMyPackageComposer : ICustomComposer {
}
```

Now you can in your own code run `AddComposers<IMyPackageComposer>()` this will run only the composers you created with your own interface. All `IComposer` implementations still run on the default `AddComposers()` call in `startup.cs`.

So I don't want to increase the complexity of the composers but just make it possible to have your own composer loop in your own application.

**Comment by bielu** [comment]
@nikcio I understand what you trying to achieve, but I am afraid it will finish with that you need use different composer to each umbraco package.  Also not really why you need own implementation for this class 🤔
So from my point of view now, if I will decide modify something in your package I will need to implemented composer which implements IMyPackageComposer instead of IComposer. Now lets think uSync, Konstrukt and any other package will follow this pattern and we have same mess as we had with ICore /IUser and IComposer 😓

**Comment by bielu** [comment]
@nikcio if you register anything in DI i might need to replace or modify it, so yeah I would use it :) I had example for it with Umbraco pdf indexer which I had to register before and replace their own services with Elastic one!

**Pull request closed without merging**
