### PR TITLE
Supporting URL picker in umbracoRedirect magic property

### PR DESCRIPTION
**Pull request by callumbwhyte**
I've always thought it would be cool to allow the (single) Multi URL Picker to be used with the magic `umbracoRedirect` property - it's much more intuitive for editors when dealing with external links.

Thankfully it was a pretty easy change!

First we fetch the value of the `umbracoRedirect` property (object), then we check it's type - if it's an integer it's a legacy picker and we can fetch the content from the cache, if it's a Udi we can fetch the content from cache, and if it's a single `Link` we use the `Url` property.

The type checking should also be slightly more performant, as we eliminate several calls to `.Value` and lots of null checking too.

### CODE REVIEW

**Comment by callumbwhyte** [comment]
@nul800sebastiaan Indeed you're right, these changes do break the manually typed node IDs... I overlooked that `.Value<T>` calls `TryConvertTo<T>` in the background if no value converter is found, meaning "399444" is correctly converted to an integer.

We should probably agree on some scope for these changes, and avoid breaking as many things as possible...

No core pickers should return integers anymore, and I'm pretty sure legacy data is migrated (could be wrong). It would make sense that someone could type a node ID in a text field though.

Further it would also make sense that someone could type a full URL in the field and use that for the redirect. We'd probably need to validate that it is a correct URL before attempting the redirect though?

**Comment by nul800sebastiaan** [comment]
Ah I think I confused myself here! There's a few of these redirect properties. Got it now why these changes are needed. 

The URL picker stores data differently (`[{"name":"Node Name","udi":"umb://document/0ca3c2f8ffa747eaa550421f37f6d63d"}]`) than the content picker (`umb://document/0ca3c2f8ffa747eaa550421f37f6d63d`).

I think the url validation already happens, I typed an invalid url and no redirect happened, so `request.SetRedirect(redirectUrl);` is doing some checking it seems.

The main question I have at the moment is why did the `FollowInternalRedirects` need to be updated, the `umbracoRedirect` property is usually handled by `FollowExternalRedirect` right? Even though that method name doesn't really match what we're trying to do here. The code comment specifies this as well https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Core/Routing/PublishedRouter.cs#L706

**Comment by nul800sebastiaan** [comment]
@callumbwhyte I'd love to get this merged still! Just have the questions above that need clarifying when you have a minute please.

**Comment by callumbwhyte** [comment]
@nul800sebastiaan I would love to also, busy week... It's on my list for this weekend!

**Comment by emmagarland** [comment]
Hi again @callumbwhyte 😄 

Still looking through some of the longer running PRs, and found another one of yours, sorry again for the delay!

I've just rebased, and there is now a conflict in `PublishedRouter.cs`. I think you were also going to clarify some of @nul800sebastiaan questions [here](https://github.com/umbraco/Umbraco-CMS/pull/12107#issuecomment-1061788630)?

Let us know if you need anything to progress this one at all!

Thanks,

Emma

**Comment by emmagarland** [comment]
Hi @callumbwhyte!

Since we haven't heard from you for a while, we're closing this PR for now, but we'd love to see another PR for this if you get a chance to focus on it again.

Or, if you want to reactivate this PR, please feel free to reply to this and we can take it from there 😃 

All the best and thanks again for your contribution,

Emma

**Pull request closed without merging**
