### PR TITLE
Bugfix: #10414 - Validation message doesn't disappear once the issue is fixed

### LINKED ISSUE #10414: Validation message doesn't disappear once the issue is fixed
### Which Umbraco version are you using?

8.14.0

### Bug summary

With a textbox set to having a maxmium of 500 characters, after correctly receiving a warning that the text it too long, the error is not removed if you set the textbox to empty.

### Specifics

The error is removed if you type new content, but if you leave the textbox blank you continue to get the error

### Steps to reproduce

1. Create a textbox with a maximum length (e.g. 500)
2. Enter 500+ characters and try to save. You should be correctly prohibited
image

3. Select all characters and delete them, and the error message does not go away.
image

The error message is only removed when typing a text in to the box

### Expected result / actual result

As soon as the text length falls within the accepted bounds the error message should be removed.

### PR DESCRIPTION
**Pull request by BatJan**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #10414 

### Description
This PR ensures the validation message is removed in case one decides to remove all chars at once.

**Before**
textstring-validation-before

**After**
textstring-validation-after

### CODE REVIEW

**Comment by OwainWilliams** [comment]
Morning @BatJan  - I hope to have a chance to review this over the next day or so. If I've any questions I'll drop a message. 
Thanks for the contrib!

**Review by OwainWilliams — APPROVED** [review]

**Comment by OwainWilliams** [comment]
Thanks @BatJan - I've tested this and the validation now works as expected. Great spot!

**Comment by nibbe02** [comment]
@OwainWilliams I'm wondering if the bug remains in version 8.16. Unfortunately, I experience a similar problem with the media selector.

https://user-images.githubusercontent.com/10845659/131214634-4912c4e8-77b6-45d3-ab4a-5de192b0d8cb.mp4

**Comment by BatJan** [comment]
@nibbe02 It's not directly related - The issue fixed here is for the validation of the "textstring" property editor. The issue you showcase above is probably related to the media picker, which has it's own set of logic :-)

If time allows and no one has a look before me I'll see if I can give it a go and find a fix 👍🏻

**Comment by nibbe02** [comment]
Thank you for explaining it to me. I thought these shared validation functionality, but now I know :)

**Pull request merged**
