### PR TITLE
U4-11166 Hide disabled users from the users list view

### PR DESCRIPTION
**Pull request by jamescoxhead**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description
Fixes [U4-11166](http://issues.umbraco.org/issue/U4-11166). When the `hideDisabledUsersInBackoffice` setting in umbracoSettings.config is set to true disabled users are now hidden from the users list view.

### CODE REVIEW

**Comment by abjerner** [comment]
Hi @jamescoxhead - thanks a lot for creating this PR 👍 

I will try to give your code a spin. We strive to review PRs within 14 days, but hopefully I can do this over the weekend ;)

Anders, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by abjerner** [comment]
@jamescoxhead thanks again for taking the time to create this PR.

I had some time to test your code, and it turns out that the `IsApproved` property is also `false` for invited users, and we don't really wish to hide these (at least I don't think so).

Ideally we should make a check like `user.UserState != UserState.Disabled`, but the `UserState` property isn't available at this point (I think this is because the `filterQuery` parameter is applied at the database level).

The `GetAll` method a few lines down the file does however already take an array of `UserState` as parameter. So I'd imagine we could do something like:

```C#
    if (UmbracoConfig.For.UmbracoSettings().Security.HideDisabledUsersInBackoffice)
    {
        if (userStates == null || userStates.Length == 0)
        {
            userStates = new []
            {
                UserState.Active, UserState.Invited, UserState.LockedOut
            };
        }
    }
```

With the code above, we do however still get the option to limit the list to disabled users only (see screenshot below). This may be fine, as the above code just hides disabled users from the initial list (all statuses).

image

As you can see from my screenshot, specifically selecting *Disabled* also lists *Invited* users, which may be another bug.

If we should also hide *Disabled* from the status selector, `Services.UserService.GetUserStates()` can be replaced with `Services.UserService.GetUserStates().Where(x => x.Key != UserState.Disabled).ToDictionary(x => x.Key, x => x.Value)`. But as things has changed a bit since the `hideDisabledUsersInBackoffice` setting was introduced (eg. a new user section with invites), it might be a good idea to discuss what we actually want this setting do. Perhaps @nul800sebastiaan has some thoughts on this? Should it hide *all* mentions of disabled users?

**Comment by jamescoxhead** [comment]
Hi Anders - thanks for the feedback. I'll try to update the PR towards the end of the week.

**Comment by nul800sebastiaan** [comment]
Thanks @jamescoxhead and @abjerner !

I think the observations are mostly correct:
1. It would be good to show disabled users in the status filter, but not show them by default in the "All" status.
2. Invited users should indeed be shown in the "All" status.

If those two points can be fixed then I'm happy to merge!

**Comment by jamescoxhead** [comment]
Thanks @nul800sebastiaan - I've updated the PR with your feedback. I've added in the inactive state I mentioned above, as without it there's no way to view users who have been created but haven't logged in.

**Comment by nul800sebastiaan** [comment]
Thanks for the updates @jamescoxhead ! It was almost correct, I was just missing the `Inactive` label in the overview, turns out you forgot to update the UserState for that one, it's fixed here! https://github.com/umbraco/Umbraco-CMS/commit/a411c9c300b7b6f4127aa9b5fb48eeb325313e6c

All good now and we can actually hide disabled users again! 👍🎉

**Pull request merged**
