### PR TITLE
Change the property accessed on the external provider from SocialIcon to Icon.

### LINKED ISSUE #10674: External Login Provider Icons Not Displayed
### Which *exact* Umbraco version are you using? For example: 8.13.1 - don't just write v8

v9/dev

### Bug summary

Icons for External Login Providers do not render on the login page. 

### Specifics

The external login provider icon is rendered to the page accessing the SocialIcon property of the external login provider's properties for example
```<i class="fa" ng-class="login.properties.SocialIcon"></i>```

The external login provider's does not contain a SocialIcon property, it should be Icon. This is rendered further down the page in a script tag 
```
providers: [{..."properties":{"ButtonStyle":"btn-success","Icon":"fa-cloud", ...}}]
```

### Steps to reproduce

Add an external login provider and load the login page. The external login providers won't have nice icons on them.

### Expected result / actual result

The external login providers should have nice icons beside them.

### PR DESCRIPTION
**Pull request by cleversolutions**
### Prerequisites

- [ X] I have added steps to test this contribution in the description below

Fixes #10674 

### Description
Change the property accessed on the external provider from SocialIcon to Icon. 

Note: I accidentally included in this branch some changes from another branch. I've removed those changes in this branch so there is now only 1 file changed by this PR.

### Testing
I Rebuilt Umbraco, registered an external provider and checked that the icon exists.

You can add an external provider to test this using this gist https://gist.github.com/cleversolutions/afcd985dbfe19b93b6436f5626c623b5

### CODE REVIEW

**Comment by bjarnef** [comment]
Not specific related to changes in this PR, but I wonder if we instead of this
```
<i class="fa" ng-class="login.properties.Icon"></i>
```

can use this:

```
<umb icon="{{login.properties.Icon}} class="fa {{login.properties.Icon}}"></umb-icon>
```

That way it should be possible to use a custom SVG icon, while font icon should still work.

**Comment by cleversolutions** [comment]
I’ll try that out this morning @bjarnef. Any tips on front end workflow? I’ve been doing a full build after each change which is kind of slow. Thanks.

**Comment by cleversolutions** [comment]
Excellent here is a screenshot of using icon-molecular-network (because what a fun icon right)
image

And a screenshot of using a font-awesome icon
image

**Comment by bjarnef** [comment]
@cleversolutions it could be nice to backport this for v8 as well, where it seems the icon was stored in a `SocialIcon` property.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/Security/AuthenticationOptionsExtensions.cs#L94

but it could be in a separate PR.

It seems Umbraco has these SVG icons to use:
https://github.com/umbraco/Umbraco-CMS/tree/v8/contrib/src/Umbraco.Web.UI.Client/src/assets/icons

You could try with `icon-umbraco.svg` - it has been added recently and I think it is not part of the Umbraco core font icons.
Furthermore you can also try with a custom SVG icon in `App_Plugins` folder, e.g. `~/App_Plugins/MyPlugin/Backoffice/Icons/Coffee.svg`.

https://our.umbraco.com/forum/using-umbraco-and-getting-started/106330-how-to-use-custom-svg-icons

You should then be able to use `coffee` icon.

**Comment by cleversolutions** [comment]
Thanks @bjarnef, configuring the external provider with icon-molecular-network did use an SVG. 

For reference this is how I've configured it:
```
loginOptions.AddBackOfficeLogin(new BackOfficeExternalLoginProviderOptions(
                    "btn-success",
                    "icon-molecular-network"
                )
```
And this is the result
image

I've also tested with a custom icon placed in ~/App_Plugins/MyPlugin/Backoffice/Icons/custom-icon.svg:
```
loginOptions.AddBackOfficeLogin(new BackOfficeExternalLoginProviderOptions(
                    "btn-success",
                    "custom-icon"
                )
```
Result:
image

Also if anyone is curious this is how I got the font-awesome icon working. Note this is a little different than v8. V8 assumes a font-awesome icon and includes the fa class, this update no longer assumes font awesome and requires that you include the fa class in the Icon attribute of the BackOfficeExternalLoginProviderOptions.
```
loginOptions.AddBackOfficeLogin(new BackOfficeExternalLoginProviderOptions(
                    "btn-success",
                    "fa fa-google"
                )
```

I think I'm also going to submit a separate PR to docs to document how to setup an external login provider in v9.

**Comment by cleversolutions** [comment]
I've just pushed one more change. The user overlay now uses the proper attribute for the external provider icon.

image

**Comment by Shazwazza** [comment]
Absolutely wonderful :) thanks everyone 🎉

**Comment by bjarnef** [comment]
@Shazwazza is there a better way we can serialize the additional data to consistent use camel case syntax in Angular views?

I have noticed we also have some properties in media section like `MediaPath`, but something er could look at in other PR or BackOffice rebuild later.

**Comment by Shazwazza** [comment]
I'm not exactly sure what you are referring to here?

**Comment by bjarnef** [comment]
It would be ideal to use camel case in the views, e.g. `{{login.properties.icon}}` instead of `{{login.properties.Icon}}` as in this PR 😁

**Pull request merged**
