### PR TITLE
V8: Make sure media picker items are sortable

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/6035

### Description

Items picked in a media picker with "Pick multiple items" enabled should be sortable, but they are not. See #6035 for more details.

This PR fixes the sortable implementation of the media picker. When it is applied, the picked items can be sorted:

media-picker-sortable-after

Note that I have removed the `$scope.$watch` as part of this PR as it didn't seem to have any positive effect. I removed it because it caused a reload of all images when sorting the media picker items, thus executing a bunch of unnecessary requests.

#### Testing this PR

1. Verify that media picker items _cannot_ be sorted when "Pick multiple items" is _disabled_ on the media picker config.
2. Verify that media picker items _can_ be sorted when "Pick multiple items" is _enabled_ on the media picker config.
3. Verify that the updated item sort order is persisted when saving the content.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Oh lovely. Yes, they should be sortable. Thanks for seeing to it that they are. We'll let you know if we need you.

Em

**Comment by kjac** [comment]
Merge conflicts resolved

**Comment by nul800sebastiaan** [comment]
Hmmm,I think some recent merges might have caused it to do some weird stuff!



I've also observed picked images going missing but it's now impossible to reproduce, so not sure what that is all about 🙈

**Comment by kjac** [comment]
@nul800sebastiaan I can't reproduce your errors 😲 Works on My Machine (tm)

**Comment by nul800sebastiaan** [comment]
Hmmmm.. well, my browser likes this change today, so I'm happy! Must've done something weird last time. 😁 

THANKS!

**Comment by ceee** [comment]
I thought this PR was cherry picked for 8.1.5 release (and should also be there in 8.2)? 
I can't get it to work after updating to 8.2, anyone can confirm?

**Comment by kjac** [comment]
@ceee while I haven't tested this in 8.2 it seems to work just fine in vLatest:

media-picker-sortable

**Pull request merged**
