### PR TITLE
Support SVG icon in action menu

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
This is a new PR of closed https://github.com/umbraco/Umbraco-CMS/pull/10757 to v9.

Currently this introduce a breaking change to specify full icon name (like in most other part of UI). Alternatively we could use the approach in https://github.com/umbraco/Umbraco-CMS/pull/10757 with a UseLegacyIcon property to make it work with current icons and full icon name.

At the moment it is assumed the icon (font icon or SVG icon) always is prefixed with icon- which is not always the case and not a requirement in other part of the UI).

```
public class ApplicationComposer : ComponentComposer<ApplicationComponent>, IUserComposer
{
    public override void Compose(Composition composition)
    {
        base.Compose(composition);
    }
}

public class ApplicationComponent : IComponent
{
    public void Initialize()
    {
        //register custom menu item in the media tree
        TreeControllerBase.MenuRendering += TreeControllerBase_MenuRendering;
    }

    public void Terminate()
    {
        TreeControllerBase.MenuRendering -= TreeControllerBase_MenuRendering;
    }

    private void TreeControllerBase_MenuRendering(TreeControllerBase sender, MenuRenderingEventArgs e)
    {
        if (sender.SectionAlias == "content" && sender.TreeAlias == "content")
        {
            var coffeeMenuItem = new MenuItem("coffee", "Coffee Time")
            {
                Icon = "coffee-cup",
                SeparatorBefore = true
            };

            e.Menu.Items.Insert(e.Menu.Items.Count - 1, coffeeMenuItem);
        }
    }
}
```

**Before**

image

**After**

image

I have attached the folder with the custom `coffee-cup.svg` icon here, so extract this folder to App_Plugins:
[CustomIcons.zip](https://github.com/umbraco/Umbraco-CMS/files/8146673/CustomIcons.zip)

### CODE REVIEW

**Comment by nathanwoulfe** [comment]
Hi @bjarnef just to clarify - do these changes introduce a breaking change?

Probably not one for this PR, but I'd love to see all those icon string served from `Constants.Icons`. Would make these sorts of changes cleaner, eliminate the potential for typos, and be ever so slightly more performant...

**Comment by bjarnef** [comment]
Hi @nathanwoulfe 

Yes, this PR instroduce a breaking change as previous you could just specify `delete` as icon and it would use icon `icon-delete`... setting `icon-delete` would not work, unless you had a font icon `icon-icon-delete`.

Previous it did only work for font icons.

If we should avoid a breaking change we could introduce a property like `UseLegacyIcon` as in the old PR.

Checking for psysical file with same name isn't enough, så font icons are combined in a one or multiple files.. and regarding SVG icons it would probably require to search directories again including folders in `App_plugins` and `Umbraco` folder.

**Comment by nathanwoulfe** [comment]
Ah, ok. Personally, I'd avoid adding the UseLegacyIcon and wait for v10 with a breaking change. Adding support for legacy just feels a bit dirty IMO - keep moving forward, not looking too far backwards 😄

**Comment by bjarnef** [comment]
Yea, that was what I was hoping for in v9 release, but unfortunely that didn't happen 😅

Hopefully in v10 then. It's a similar issue solved in https://github.com/umbraco/Umbraco-CMS/pull/12062

**Comment by bjarnef** [comment]
@nathanwoulfe anything I need to adjust regarding this? It would be great if we can resolve the last bits of the UI to support custom icons as well.

**Comment by bjarnef** [comment]
@nul800sebastiaan I have also updated this, so core menu actions no longer use the legacy icon, but specify full icon name.

image

**Comment by bjarnef** [comment]
Example for v9 with/without `icon-` prefix and custom SVG icon:

```
public class ApplicationComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        builder.AddNotificationHandler<MenuRenderingNotification, TreeNotificationHandler>();
    }
}

public class TreeNotificationHandler : INotificationHandler<MenuRenderingNotification>
{
    private readonly IBackOfficeSecurityAccessor _backOfficeSecurityAccessor;

    public TreeNotificationHandler(IBackOfficeSecurityAccessor backOfficeSecurityAccessor)
    {
        _backOfficeSecurityAccessor = backOfficeSecurityAccessor;
    }

    public void Handle(MenuRenderingNotification notification)
    {
        // for all content tree nodes
        if (notification.TreeAlias == Umbraco.Cms.Core.Constants.Applications.Content &&
            _backOfficeSecurityAccessor.BackOfficeSecurity.CurrentUser.Groups.Any(x =>
            x.Alias == Umbraco.Cms.Core.Constants.Security.AdminGroupAlias))
        {
            var wineMenuItem = new MenuItem("wine", "Wine Time")
            {
                Icon = "wine-glass",
                SeparatorBefore = false,
            };

            var coffeeMenuItem = new MenuItem("coffee", "Coffee Time")
            {
                Icon = "coffee-cup",
                SeparatorBefore = true,
                UseLegacyIcon = false,
            };

            var beerMenuItem = new MenuItem("beer", "Beer Time")
            {
                Icon = "icon-beer-glass"
            };
            
            notification.Menu.Items.Insert(5, wineMenuItem);
            notification.Menu.Items.Insert(6, beerMenuItem);
            notification.Menu.Items.Insert(7, coffeeMenuItem);
        }
    }
}
```

**Comment by nathanwoulfe** [comment]
Updated base to 10/contrib, will let tests run, review and merge. Can then be cherry-picked back to 9 if appropriate (I'd expect not, I'd like to think the book is closed for 9, outside of bugs/regressions)

**Comment by nathanwoulfe** [comment]
I'll even deal with the conflicts since I introduced them by changing the base branch 😄

**Comment by nathanwoulfe** [comment]
@bjarnef I think I need to hold off pushing anything - given the base is now v10, if I push changes I think it will cause issues in your repo as the original branch was v9-based... Not sure the best way to progress this, other than you retargeting the PR from a fresh v10-based branch?

**Comment by bjarnef** [comment]
@nathanwoulfe I think we can resolve the merge conflicts, so it is in sync Witherspoon `v10/contrib` branch.

**Comment by bjarnef** [comment]
@nathanwoulfe I have now resolved this merge conflicts and should be in sync with latest v10 changes.

**Comment by nathanwoulfe** [comment]
Hey @bjarnef this all looks fine, works nicely with v10 (updated the test case to use `MenuRenderingNotification` to add the coffee cup node, icon display correctly).

I'm a little confused by the test failures. Tests are failing because `MenuItemList.CreateMenuItem<T>()` contains a possible null reference return (the method explicitly returns null if no action exists), but the method is a nullable return type (`MenuItem?`) so I'm not sure why the test would fail on the null return, when the method allows it...

**Comment by nathanwoulfe** [comment]
And for reference, my test code:

```c#
    public class ApplicationComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.AddNotificationHandler<MenuRenderingNotification, MenuRenderingNotificationHandler>();
        }
    }

    public class MenuRenderingNotificationHandler : INotificationHandler<MenuRenderingNotification>
    {
        public void Handle(MenuRenderingNotification notification)
        {
            if (notification.TreeAlias == "content")
            {
                var coffeeMenuItem = new MenuItem("coffee", "Coffee Time")
                {
                    Icon = "coffee-cup",
                    SeparatorBefore = true,
                    UseLegacyIcon = false, // default value is true
                };

                notification.Menu.Items.Insert(notification.Menu.Items.Count - 1, coffeeMenuItem);
            }
        }
    }
```

**Comment by bjarnef** [comment]
@nathanwoulfe oh, it seems something gone wrong in the merge as it has reverted the changes in v10 where e.g. `MenuItemList.CreateMenuItem<T>()` returns a nullable `MenuItem`.

**Comment by nathanwoulfe** [comment]
Maybe a new feature branch from v10/contrib, then cherry pick your changes into that branch and push a fresh PR...

I think merging 10 into 9 causes hiccups, probably take as long to sort that out as it would to cut a new branch

**Comment by bjarnef** [comment]
@nathanwoulfe closing this and starting moving stuff to a new branch from latest changes in `v10/contrib` branch https://github.com/umbraco/Umbraco-CMS/pull/12403

**Pull request closed without merging**
