### PR TITLE
V9/tmp nucache lock

### LINKED ISSUE #12148: Sql Database ThreadAbortException results in NuCache local db locked
### Which *exact* Umbraco version are you using? For example: 9.0.1 - don't just write v9

9.4.0-rc and 8.18.0

### Bug summary

When Umbraco starts up and runs through the process of refreshing/populating the NuCache local db file, it can result in the physical file being locked if a transient network condition occurs while the data is being read from the database.  This results in the following logs:

```
									
Message:
Exception ("4aa0a49a").
The thread has been aborted, because the request has timed out.

									
Exception:
System.Threading.ThreadAbortException: Thread was being aborted.
   at SNIReadSyncOverAsync(SNI_ConnWrapper* , SNI_Packet** , Int32 )
   at SNINativeMethodWrapper.SNIReadSyncOverAsync(SafeHandle pConn, IntPtr& packet, Int32 timeout)
   at System.Data.SqlClient.TdsParserStateObject.ReadSniSyncOverAsync()
   at System.Data.SqlClient.TdsParserStateObject.TryReadNetworkPacket()
   at System.Data.SqlClient.TdsParserStateObject.TryPrepareBuffer()
   at System.Data.SqlClient.TdsParserStateObject.TryReadByteArray(Byte[] buff, Int32 offset, Int32 len, Int32& totalRead)
   at System.Data.SqlClient.TdsParserStateObject.TryReadString(Int32 length, String& value)
   at System.Data.SqlClient.TdsParser.TryReadSqlStringValue(SqlBuffer value, Byte type, Int32 length, Encoding encoding, Boolean isPlp, TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParser.TryReadSqlValue(SqlBuffer value, SqlMetaDataPriv md, Int32 length, TdsParserStateObject stateObj, SqlCommandColumnEncryptionSetting columnEncryptionOverride, String columnName)
   at System.Data.SqlClient.SqlDataReader.TryReadColumnInternal(Int32 i, Boolean readHeaderOnly)
   at System.Data.SqlClient.SqlDataReader.TryReadColumn(Int32 i, Boolean setTimeout, Boolean allowPartiallyReadColumn)
   at System.Data.SqlClient.SqlDataReader.GetValues(Object[] values)
   at NPoco.RowMappers.PropertyMapper.Map(DbDataReader dataReader, RowMapperContext context)
   at NPoco.MappingFactory.Map(DbDataReader dataReader, Object instance)
   at NPoco.Database.<Read>d__156`1.MoveNext()
   at NPoco.Database.<QueryImp>d__164`1.MoveNext()
   at Umbraco.Core.Persistence.NPocoDatabaseExtensions.<QueryPaged>d__8`1.MoveNext()
   at Umbraco.Web.PublishedCache.NuCache.DataSource.DatabaseDataSource.<GetAllContentSources>d__13.MoveNext()
   at Umbraco.Web.PublishedCache.NuCache.ContentStore.SetAllFastSortedLocked(IEnumerable`1 kits, Boolean fromDb)
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.LoadContentFromDatabaseLocked(IScope scope, Boolean onStartup)
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.LockAndLoadContent(Func`2 action)
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.<EnsureCaches>b__36_0()
```

At this point, Umbraco can't recover and the NuCache file is indefinitely locked.  This is accompanied by a large number of the following log entry after the initial one:

```
Message:
An unhandled exception occurred

									
Exception:
System.IO.IOException: The process cannot access the file 'C:\local\Temp\UmbracoData\748c65bf441f4d693b51602dbfa2e300\NuCache\NuCache.Content.db' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at CSharpTest.Net.IO.TransactedCompoundFile..ctor(Options options)
   at CSharpTest.Net.Storage.BTreeFileStoreV2..ctor(Options options)
   at CSharpTest.Net.Collections.BPlusTree`2.OptionsV2.CreateStorage()
   at CSharpTest.Net.Collections.BPlusTree`2.NodeCacheBase..ctor(BPlusTreeOptions`2 options)
   at CSharpTest.Net.Collections.BPlusTree`2.NodeCacheNone..ctor(BPlusTreeOptions`2 options)
   at CSharpTest.Net.Collections.BPlusTree`2..ctor(BPlusTreeOptions`2 ioptions)
   at Umbraco.Web.PublishedCache.NuCache.DataSource.BTree.GetTree(String filepath, Boolean exists, ContentDataSerializer contentDataSerializer)
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.MainDomRegister()
   at Umbraco.Core.Runtime.MainDom.Register(Action install, Action release, Int32 weight)
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.<EnsureCaches>b__36_0()
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.EnsureCaches()
   at Umbraco.Web.PublishedCache.NuCache.PublishedSnapshotService.CreatePublishedSnapshot(String previewToken)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Umbraco.Web.UmbracoInjectedModule.EnsureHasContent(UmbracoContext context, HttpContextBase httpContext)
   at Umbraco.Web.UmbracoInjectedModule.EnsureUmbracoRoutablePage(UmbracoContext context, HttpContextBase httpContext)
   at Umbraco.Web.UmbracoInjectedModule.ProcessRequest(HttpContextBase httpContext)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

### Specifics

It seems that this is because when Umbraco queries the data (Content and Media) from the database, it maintains an open connection while transforming and writing each entry to the NuCache file (it iterates through an IEnumerable instead of retrieving everything at once).  This could result in a ThreadAbortException if the  connection times out, or a network transient error occurs.

Because this isn't handled gracefully, an exception means that the NuCache file is left in a locked state (it's never released).

### Steps to reproduce

Unfortunately, this is not easy to reproduce reliably.  However I do have a potential fix (PR pending)

### Expected result / actual result

NuCache local database file should be unlocked in the event of an exception while reading data from the database.

### PR DESCRIPTION
**Pull request by robertjf**
### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #12148 

### Description
The changes are two-fold.  Firstly, we now retrieve the content/media from the database in one go due to using `.ToList()` on the enumerations instead of maintaining an open connection and operating on each item individually; secondly, we wrap the relevant operation within a try-catch to allow us to gracefully exit the method without causing the local db to remain locked.

### CODE REVIEW

**Review by mikecp — CHANGES_REQUESTED** [review]
Hi @robertjf ,

Thanks for your PR, this is a very interesting catch 👍 

We had some discussions with HQ about it, and it seems that doing a plain "ToList()" might cause some memory issues in case there is a lot of content, since we would then have all the content loaded in memory at once.
There is actually a remark in NuCacheContentRepository in the code of GetAllContentSources stating that "// We also want to read with a db reader and not load everything into memory,"

So, @bergmania came with a proposal for an intermediate solution, where the content would be loaded in memory "in batches" and then handled one by one.

The suggestion would be to remove the "ToList()" from PublishedSnapshotService and then adapt the methods of the _contentStore.SetAllFastSortedLocked and _contentStore.SetAllLocked and replace

`foreach (var kit in kits)`

with

```
foreach (var kitGroup in kits.InGroupsOf(100))
foreach (var kit in kitGroup)
```

Where 100 could be configurable. With default value 1. Then it would be the same behavior as now, but people with timeouts could try a larger value. Ultimately int.MaxValue having the same behavior as doing a ToList() up-front, which might be interesting in situations where there is not too much content.

I think this alternative is interesting because it allows the users to choose which configuration best fits their need.

What do you think? Would you be up to do those adaptations? 😁

**Comment by robertjf** [comment]
Hey @mikecp I like the idea of using `InGroupsOf()`; I've added a new setting to the NuCache configuration - `KitBatchSize` with a default of 1.  I've also optimised the InGroupsOf() to always be groups of 1 if the content is coming from the local db cache instead of the database.

Happy to make any additional changes...

**Comment by mikecp** [comment]
Hi @robertjf ,

Thanks for making the changes so quickly 👍😊

I think we're almost there, the only "problem" left (which I did not think about when writing my previous comments...) is the fact that we are adding parameters to public methods, which is a breaking change, and which therefore cannot be merged as-is into V9. But the solution is quite simple in this case: we just need to create the original versions back which then just call the new versions with the default values.
If you could do that last bit, I think we would then be ready to merge 😁

**Comment by robertjf** [comment]
@mikecp oops, yes of course!  Done... I've also marked the old method signatures as obsolete.

**Comment by mikecp** [comment]
Thanks @robertjf for updating so quickly again, and good idea to mark the methods as obsolete 👍 
I see that @nul800sebastiaan made some last "style cleanups undo", so I guess we're all set now for a merge 🎉

**Review by mikecp — APPROVED** [review]

**Comment by gabador-mof** [comment]
Hi! This What's the likelihood this will make it back to V8? We've just finished building a site in V8, and it would be unfair to ask the client to upgrade even before we release it... I think this may fix one of the issues that we are experiencing currently, which is as is similar to that described in the original issue referenced.

**Comment by benbracedigital** [comment]
I would also be interested in this being available in V8. We still have many clients on V8 who would be affected.

**Comment by EelmanE** [comment]
Does anyone know if this became available for v8?

**Comment by mikecp** [comment]
No idea, but at first sight I would say it did not. Maybe @nul800sebastiaan can give a more definitive answer 😉

**Comment by nul800sebastiaan** [comment]
Haven't looked into it, but I bet if there was a PR for the `v8/dev` branch we'd be able to merge it quite quickly. 👍 I just don't know how very different these parts of the code are in v9.

**Comment by EelmanE** [comment]
@nul800sebastiaan Seems like v8/dev is still on v8.18.0 or am i missing something?

**Comment by nul800sebastiaan** [comment]
Possibly, but that's besides the point, we can handle merging etc. :)

**Comment by mikecp** [comment]
The structure is quite different, the base projects/paths in which the modified files reside don't exist in V8 😢

**Comment by EelmanE** [comment]
I've found the corresponding code and made the changes based on the v9 pr. I'll have to test is first before i can make the pr :)

**Comment by EelmanE** [comment]
I've tried the code in our website but unfortunatly it doesn't fix our issues :( Still getting the ThreadAbortExceptions

**Pull request merged**
