### PR TITLE
Use color picker component in block list editor configuration

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
At the moment when the UX for icon color and background color in block list editor isn't great. There is not much guidedance regarding the input format or validation of this.

This PR re-use the `<umb-color-picker>` component indroduced in this PR: https://github.com/umbraco/Umbraco-CMS/pull/8812

r0vqMfSRiU

### CODE REVIEW

**Comment by bjarnef** [comment]
With PR https://github.com/umbraco/Umbraco-CMS/pull/9094 we might want to allow empty (clear) in configuration of color picker component here, so it is possible to clear an previous selected color.

**Comment by nielslyngsoe** [comment]
Oh yes, this would be great!

I think we should allow the user to have empty color, just an easy way to get back to 'default' :-)

**Comment by bjarnef** [comment]
@nielslyngsoe it should now be possible to clear any existing selected color.

HioyHMMBrM

**Comment by bjarnef** [comment]
@nul800sebastiaan @nielslyngsoe is it too late for this to be part of v8.10 with the other block list improvements? 😁🙈

**Review by nathanwoulfe — APPROVED** [review]
A nice UX improvement, thanks @bjarnef. I've tested and it works perfectly - makes sense to cherry pick for 8.10, but I'm not sure on the policy given the RC is released...

**Comment by nielslyngsoe** [comment]
@bjarnef i see it has ben tagged with 8.11, so it didnt become part of 8.10. But with the new release cycles, 8.11 will be out in 6 weeks. So waiting for a release should hopefully not be a topic of much focus going forward. :-)

**Comment by nathanwoulfe** [comment]
That tagging was me - given 8.10 RC is out, any new merge is labelled for 8.11. 

I guess if there was an RC2 due to finding something requiring a fix for release it could be pulled in, but that's not my call (and probably a risky precedent to set)

**Comment by nielslyngsoe** [comment]
@nathanwoulfe all good, my conclusion was since this did not have a 8.10 tag it has missed the train. But we will have one shortly in the next year 👍  and yep, we don’t include new stuff after RC.

**Pull request merged**
