### PR TITLE
Might as well have constants for the external searcher (and indexers)

### PR DESCRIPTION
**Pull request by abjerner**

### CODE REVIEW

**Comment by abjerner** [comment]
Still not quite sure when an issue is necessary, so here goes: http://issues.umbraco.org/issue/U4-8716

**Comment by Shazwazza** [comment]
always best to create an issue so we can schedule things :)

Next part for this PR would be to ensure all of these constants are used everywhere in the core where they may be hard coded.

**Comment by warrenbuckley** [comment]
This looks fine @abjerner but before I merge this PR in. Any place where a magic string is used is to update with these new constants you have created.

Are you able to do this please?

**Comment by abjerner** [comment]
@warrenbuckley Yup. I haven't had the time yet, but planned on doing so if you guys didn't me to it. I'll probably look into it over the weekend or some time next week ;)

**Pull request merged**
