### PR TITLE
Huntsman case - AuditLog was not returning NodeId from DB

### PR DESCRIPTION
**Pull request by warrenbuckley**
This was a hunstman case - https://umbraco.zendesk.com/agent/tickets/39085
And needs an internal review/sanity check please.

The customer was following along the tutorial about creating a custom dashboard, so do the same & ensure you get back the correct IDs in order to then use the entity id to get further details about the item as mentioned in the tutorial.

https://our.umbraco.com/documentation/tutorials/Creating-a-Custom-Dashboard/

### CODE REVIEW

**Comment by warrenbuckley** [comment]
@Shazwazza or @zpqrtbnk are you able to do a sanity check & review of this please as its to do with the data-layer.

In the meantime, I have sent the customer a custom built DLLs from this PR git commit hash - 5eab37573cbf96ff90c1d82ff40b89324efb91ee

**Comment by dawoe** [comment]
@warrenbuckley 

This is already fixed in 7.13  branch i think in these PR's : https://github.com/umbraco/Umbraco-CMS/pull/2719 and this one https://github.com/umbraco/Umbraco-CMS/pull/2866

Maybe it's better to cherry pick those to the patch branch ?

Dave

**Comment by dawoe** [comment]
Or partially fixed I think

**Comment by dawoe** [comment]
And I see the issue for the docs to update the dashboard tutorial is still open as well
https://github.com/umbraco/UmbracoDocs/issues/894

**Comment by nul800sebastiaan** [comment]
Ah! I knew I'd seen an update for this, I just couldn't find it. Let's see if we need to merge these.

**Comment by marcemarc** [comment]
@dawoe @nul800sebastiaan it's on my list to update the tutorial once these are merged, but perhaps should have added a warning about the tutorial brokenness as soon as we were aware... :-(

**Comment by RobertCopilau** [comment]
The only thing that needs merging in the PR is line 100 which fixes the issue where it would return the ID instead of the nodeId.

The rest are changes which are not needed as they have been done already in latest dev-v7, or not required (for 7.13) due to Stephan doing some query building fixes which are also present in dev-v7 branch.

Have tested that before I left on my Holiday and it worked fine, but I can run a quick test again to see if works without the extra changes.

Sorry @warrenbuckley, I should have been more clear in my notes :|.

**Comment by RobertCopilau** [comment]
I can confirm that line 100 is the only thing that needs merging to fix the issue.

**Comment by marcemarc** [comment]
@RobertCopilau ha, Ironically, I think I've made the same fix here... https://github.com/umbraco/Umbraco-CMS/pull/3759

**Comment by RobertCopilau** [comment]
Well, that is just great then :D.

I just noticed that this PR is targeted to a patch branch, so all the changes are required to fix the issue at hand in that version of Umbraco (7.12.4) therefore it can be merged.

Since I already tested the latest dev-v7 with the ID fix, I will just merge your PR right away @marcemarc, thanks for that btw :).

**Comment by nul800sebastiaan** [comment]
@RobertCopilau @warrenbuckley - I don't know why these paging changes and method overloads are needed in this patch branch. Are you 100% sure they're also in dev-v7 already? I wouldn't want to give something to a customer that will suddenly disappear in the next release.

**Pull request merged**
