### PR TITLE
U4-8487 - extract composition

### PR DESCRIPTION
**Pull request by AndyButland**
This PR adds a new feature to the document type editor allowing a user to select a number of properties of the document type and extract it into a composition.  A new type will be created for the composition, the selected property groups (tabs) and property types copied or moved as appropriate and a relationship set up so the new type is now a composition for the original/

There are a checks to ensure invalid compositions can't be created - this can't be done on a type that's already used as a composition elsewhere and only properties that aren't already inherited can be selected.

### CODE REVIEW

**Comment by AndyButland** [comment]
I've added further to this PR to allow for extracting a composition into an existing type, as well as creating a new one.  This should make it more useful - e.g. would allow two content types sharing some fields to be re-factored to use a common base composition.

More complex though as have to deal with aliases clashing, which I've set up this way:

- If both types have a field of the same alias and the same data type, the field is removed from the selected type and the content re-mapped to the field on the composite
- If fields have the same alias but different data types, you can't safely merge so instead the field is moved the composite with an amended alias, so you end up with both fields on the composite.  E,g, if you had `bodyText` as a rich text field on one type and a text area field on the other, you'd end up with `bodyText` and `bodyText` two on the composite.

Fairly sure there's lots to review but to pick out one thing I'm aware of that needs updating - in `ContentTypeRepository.ExtractComposition()` I'm currently refreshing the back-office by clearing all the content type and content runtime cache.  Fairly sure there must be a better, more targeted way of doing that.

**Comment by Shazwazza** [comment]
Hi Andy,

I think it will be best that you demo some of these new features at the retreat so we can all get a good understanding of the changes being made and what is required.

Also note that any cache invalidation done *must* be done using a cache refresher. These are always executed based on events.

**Comment by AndyButland** [comment]
Sure, good idea.

**Comment by poornimanayar** [comment]
Hi @AndyButland ,

Hope you are well. We are now focussing on some of the PRs that has been sitting in the queue, trying to test and feedback on them. This work is really super cool and I think it would be great if we can get it in. Is there any chance you can resolve the conflicts to help us start on this PR?

Regards,
Poornima, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by poornimanayar** [comment]
Thanks for the prompt reply @AndyButland . I can defenitely help you on that. :-)

Poornima

**Comment by nul800sebastiaan** [comment]
Hey there!

I'm writing today after anouncing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately this proposed feature won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Pull request closed without merging**
