### PR TITLE
V8: Make "Open in split view" look better in narrow viewports

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

In a somewhat narrow viewport, the "Open in split view" button causes the language selector to bounce around because of some text wrapping:

language-selecor-narrow-viewport-before

This PR does a bit of mending. It's still not perfect, but at least better than the current solution:

language-selecor-narrow-viewport-after

Perhaps someone with mad flexbox skills can do better 😄

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hello Kenn, my old friend. 

Thanks for the work. We'll let you know if we need anything here in due course.

Em

**Comment by nielslyngsoe** [comment]
Good catch. Looking at it I think it wouldn't hurt to set a minimum width of the dropdown, to make sure that we have a decent width. So the dropdown would in situations like this get wider than the name-input, expanding to the right.
What do you think @kjac ?

**Comment by kjac** [comment]
Works for me 👍

**Comment by kjac** [comment]
@nielslyngsoe so I tried a minimum width. It's not the best of solutions. Turns out the language selector must be at least 540px wide to have the culture "Macedonian (Former Yugoslav Republic of Macedonia)" fit just remotely comfortably inside it. And in split view that's 2x 540px 😲 

I did tweak the current solution a bit more so it expands beyond the width of the input to support such long culture names, but still with the absolute positioning of the split view button. Now it looks like this:

image

**Comment by nielslyngsoe** [comment]
@kjac Super great! I´m merging this!

**Pull request merged**
