### PR TITLE
V8: Create dialogs have horizontal overflow

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

The awesome work by @MMasey in 405e9a79 has had a bit of a negative impact on the create dialogs throughout the system (except in Content); there's a horizontal overflow going on:

create-dialog-overflows

Given how we should definitively keep on moving towards the goal from 405e9a79, I have updated all create dialogs according to the changes in that PR. This removes the overflow, and as a bonus it is a step along the way to make all of the create dialogs keyboard accessible.

When this PR is applied, the menus behave like you'd expect:

create-dialog-overflows-after

### CODE REVIEW

**Comment by MMasey** [comment]
Awesome, thank @KennethJakobsen, I have no idea how I missed that 🤦‍♂ 😂

**Comment by kjac** [comment]
😆 I do believe @KennethJakobsen is receiving weird notifications from time to time

**Comment by MMasey** [comment]
😂 It's really not my day is it

**Comment by kjac** [comment]
That ain't fair, #5729 is awesome 👍

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by nul800sebastiaan** [comment]
Beautiful @kjac - many thanks! 👍 

Merged and cherry picked into 8.1.2 - https://github.com/umbraco/Umbraco-CMS/commit/36eccb472cca07b580d791135d29a3f1a61e9706

**Pull request merged**
