### PR TITLE
Fixed ContentLastChanceFinder not being called for nodes without templates

### PR DESCRIPTION
**Pull request by vsilvar**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
Due to a regression during the implementation of Public Access (#10137), the `ContentLastChanceFinder` wasn't being executed for nodes that were found but didn't have a template.
This made it impossible to override the default 404 page for such cases without workarounds.

This commit also ensure that the domain and culture is set before the `ContentLastChanceFinder` executes.
And that the route values `TemplateName` is updated accordingly.

Steps to reproduce:
- Create a content type without a template
- Configure a `IContentLastChanceFinder` as in the example.
  Due to the example implementation, ensure the first content node actually has a template set and it exists on disk.
- Verify that when accessing the url for a page of the content type created above the `ContentLastChanceFinder` never executes
- With the suggest fix it should now execute and also set any found content node and template

ContentLastChangeFinder example:
```csharp
    public class Startup
    {
        ...
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddUmbraco(_env, _config)
                .AddBackOffice()
                .AddWebsite()
                .AddComposers()
                .SetContentLastChanceFinder<LastChanceContentFinder>()
                .Build();
        }
        ...
    }

    public class LastChanceContentFinder : IContentLastChanceFinder
    {
        private readonly IUmbracoContextAccessor _umbracoContextAccessor;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public LastChanceContentFinder(IUmbracoContextAccessor umbracoContextAccessor, IHttpContextAccessor httpContextAccessor)
        {
            _umbracoContextAccessor = umbracoContextAccessor;
            _httpContextAccessor = httpContextAccessor;
        }

        public Task<bool> TryFindContent(IPublishedRequestBuilder request)
        {
            var firstRoot = _umbracoContextAccessor.GetRequiredUmbracoContext().Content!.GetAtRoot().FirstOrDefault();

            if (   firstRoot == null // No root node exists
                || firstRoot.TemplateId == 0 // Found a node but it doesn't have a template set
                || !PhysicalTemplateExists(firstRoot.GetTemplateAlias())) // Template view file doesn't exist on disk
            {
                // NOTE: This IContentLastChangeFinder just returns the first content page available.
                // Ensure it exists, it has a template set and the actual template file exists on disk!
                Debugger.Launch();
            }

            request.SetPublishedContent(firstRoot);

            return Task.FromResult(true);
        }

        private bool PhysicalTemplateExists(string templateAlias)
        {
            ICompositeViewEngine viewEngine = _httpContextAccessor.HttpContext!.RequestServices.GetRequiredService<ICompositeViewEngine>();
            return viewEngine.FindView(
                new ActionContext(
                    _httpContextAccessor.HttpContext!,
                    _httpContextAccessor.HttpContext!.GetRouteData(),
                    new ActionDescriptor()
                ),
                templateAlias,
                false
            ) is { View: not null };
        }
    }
```

### CODE REVIEW

**Comment by vsilvar** [comment]
Hey @nul800sebastiaan, thanks for taking a look.

I see that in your example you are registering the `LastChanceContentFinder` as if it was a normal `IContentFinder`, but in order for it to work, it needs to be set as the `ContentLastChanceFinder`.

You can do that, by using `.SetContentLastChanceFinder<LastChanceContentFinder>()` instead of `.AddCustomContentFinders()`.

**Comment by vsilvar** [comment]
@nul800sebastiaan This PR has been pending for a while, is more information still needed?

**Comment by nathanwoulfe** [comment]
Hey @vsilvar would you mind taking a look at the merge conflict? I don't think it's anything major.

**Comment by vsilvar** [comment]
Hey @nathanwoulfe
Just merged the latest v10/contrib and fixed the merge conflicts.

**Comment by nathanwoulfe** [comment]
Hey @vsilvar, I've taken this for a spin and still get a 404 response when attempting to access the template-less content. Registered the same IContentLastChanceFinder from @nul800sebastiaan's example, using the `SetContentLastChanceFinder<T>` extension.

Could you please confirm this is working for you, and share your exact implementation?

**Comment by bineagu** [comment]
Any updates on this? Or any workarounds as I'm using Umbraco without templates on all nodes (except root) so I'm a bit stuck.

**Comment by nathanwoulfe** [comment]
Will try to get back to this today and see if I can reproduce...

**Comment by lauraneto** [comment]
Any updates on this?

**Comment by nathanwoulfe** [comment]
I had every intention of trying to reproduce, but haven't had a chance, and won't for at least the next few days.

**Comment by nathanwoulfe** [comment]
@vsilvar still no joy on this - using your example implementation, and a content tree like the below, both no-template nodes return 404, after running through the TryFindContent method in the LastChanceContentFinder

@nul800sebastiaan, I wonder if this could be a good one for UmbraCollab as it might need some more discussion/demonstration? (Seb isn't around this week, not sure who will be leading collab in his absence)

image

**Comment by nathanwoulfe** [comment]
I think it might be something screwy at my end - my 404 page is never returned, for any request.

I'd really like to see this running before I merge it, but given the LastChanceContentFinder executes, then as @lauraneto said, the issue is fixed.

**Comment by shearer3000** [comment]
hello - will this target the 10.1 release? thanks

**Comment by nathanwoulfe** [comment]
I'd still like to see it running end-to-end, but haven't had any luck with returning my 404 page. 

Would be good to get some additional eyeballs on it, I'll ask the collabs team if anyone can spare a few minutes

**Comment by mikecp** [comment]
Looks all fine to me except there are new conflicts apparently...

**Comment by nathanwoulfe** [comment]
Thanks @mikecp, I think the issues here are entirely mine 😃 
@vsilvar if you could kindly resolve the conflict, I'm happy to merge this
@shearer3000 this will be part of 10.2.0, as we've hit the cut-off for 10.1.0

**Comment by vsilvar** [comment]
@nathanwoulfe I've merged in the latest changes and resolved the conflicts.

**Comment by nathanwoulfe** [comment]
First job for Monday morning is merging this. Sorry it has taken so long!

**Comment by nathanwoulfe** [comment]
@vsilvar thank you for your patience! This is all good, merged, finally done.

**Comment by bineagu** [comment]
Is this going to Umbraco 9 too? Thanks!

**Pull request merged**
