### PR TITLE
Support custom SVG icon in grid editor row configuration

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
This PR adjust grid editors to allow use custom SVG icons, e.g. via package.manifest:

```
{
    "gridEditors": [
        {
            "name": "Custom editor",
            "alias": "custom",
            "view": "textstring",
            "icon": "coffee-cup"
        }
    ]
}
```

image

I have replaced icons in grid editor placeholders, so if you wanted to replace the default grid editors with a custom icon it should potentially work.
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI/config/grid.editors.config.js

However in my test it didn't seem to use `coffee-cup` but fallback to e.g. `icon-picture`.

image

### CODE REVIEW

**Comment by bjarnef** [comment]
I have a feeling that the icon not shown has something to do with the lazy loaded icon here:
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/common/directives/components/umbicon.directive.js#L39

**Comment by nathanwoulfe** [comment]
@bjarnef I've added some additional changes - the itempicker dialog wasn't using the umbIcon directive, so wasn't showing the custom icons when clicking Add Content in the grid editor. I've updated to use umbIcon, and fixed the related CSS to ensure the icons display.

Please double check my changes, if you agree it's all looking good, I'll merge this one.

**Review by nathanwoulfe — APPROVED** [review]

**Comment by nathanwoulfe** [comment]
Ah cool, missed that one. Will merge it first, then deal with any conflicts my changes might have introduced (probably easier than reverting, I tend to break stuff when I revert)

**Comment by nathanwoulfe** [comment]
@nul800sebastiaan are you happy for these to be included in the 8.13 and 8.14 patches? There are a few SVG-related PRs which make sense to release as one set of improvements...

**Review by nathanwoulfe — APPROVED** [review]
No more merge conflict, all good to go. Thanks @bjarnef

**Comment by nul800sebastiaan** [comment]
Somehow forgot to take this and a few other ones into 8.13.1 🙈 Will re-label and do so for 8.14.1 instead.

**Pull request merged**
