### PR TITLE
U4-5796 - Order the notifications dialog by alias name

### PR DESCRIPTION
**Pull request by redmorello**
I've ordered the notifications dialog by the notification alias name. Also added a little CSS into the usercontrol to make the checkbox appear to the left of the label for clarity.

If I get some extra time, I'll try and convert this to angular like the permissions dialog :)

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Yikes, usercontrols!! 

From experience: the first thing that's going to happen when someone opens this dialog now is they scream in horror: "I am soooo used to the old order, please change it back, you're making me lose productivity".

So it would be great to target this change to the `dev-v7.8` branch, since then we can mark it as a "breaking" change. 

Any chance you can provide a before & after screenshot so we can more easily review this?

Cheers,
Sebastiaan.

**Comment by redmorello** [comment]
Before:
screen shot 2018-01-10 at 15 59 27

After:
screen shot 2018-01-10 at 15 57 11

**Comment by redmorello** [comment]
@nul800sebastiaan do I need to do anything regarding the re-targeting to 7.8 ??

**Comment by bjarnef** [comment]
There is also another PR about updating the UI of the notifications dialog, which is more consistent with the permissions dialog ;)
https://github.com/umbraco/Umbraco-CMS/pull/2302

**Comment by nul800sebastiaan** [comment]
Thanks Ian @redmorello! As pointed out PR #2302 is already open for this and is more in the line of what we want. And we also have some HQ work done by Mads in PR #1546 - I'll comment on both that those need combining.

We appreciate the work but will close in favor of the other solutions offered. Thanks very much and we look forward to seeing more of your help come in #h5yr!

**Pull request closed without merging**
