### PR TITLE
#12802 Fix partial view model type replacements

### PR DESCRIPTION
**Pull request by mikaellindemann**
### Prerequisites

- [x] Steps to reproduce the fixed bug can be found in the linked issue.

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/12802

### Description
As suggested by @nul800sebastiaan, Partial Views should now replace using `"Model?.Content"` rather than `"Model.Content"`, since all templates have been updated to respect nullable reference types.

I have kept the old replacements as well.

### CODE REVIEW

**Comment by mikecp** [comment]
Hello @mikaellindemann ,

Thanks a lot for this correction 👍
I have tested it and it removes the compilation errors indeed, but there are still some warnings, so I'm pinging @nul800sebastiaan here to have his point of view and see if I can merge your PR as is, or if we should bring some updates to it first.

I'll first put the navigation snippets example before/after your PR so that we see the concrete thing. 

Before:
image

We have the error on "Content" property as expected on lines 15 and 22 + some other stuff on line 23

After:
image

We don't have the property error anymore, but we now have a complaint about possible null reference on Model, on line 15.

So, I would say that a first thing that we need to adapt, is to replace `Model?.Content.` by `Model?.`
This seems more logical to me 😁

But if we do that, we get other complains:

image

It basically propagates the "possible null exception" to the next part on line 15, and it will keep complaining until we've added the nullable check on the whole path: 

`@{ var selection = Model?.Root()?.Children?.Where(x => x.IsVisible(PublishedValueFallback)).ToArray(); }
`

Also, it introduces a "possible null exception" on line 27, where we had the replace from `(Model?.Content)` to `(Model)`.
Two remarks here:
- here we have to keep `(Model)` and not `(Model?)`
- The logic of the snippet makes that we can solve this by putting `(Model!)` instead of `(Model)`, but there is no guarantee that we can do this replace in all situations.

I hope my explanations are not too confusing, but basically, what I would like to know from @nul800sebastiaan is if we can merge the PR (with the small change I mentioned), be happy that we removed the "compilation" error and just ignore the subsequent warnings, or should we address those warnings - but then I'm not sure we can cover all possible scenarios.

And sorry @mikaellindemann  that this PR might turn out to be not as straightforward as it seemed 😅

Thanks and Cheers to you both!

**Review by mikecp — CHANGES_REQUESTED** [review]
Changes cf. previous comment

**Comment by mikaellindemann** [comment]
I suppose that the remaining warning(s) will also be present in the Macro Partials generated from the same snippet.
So maybe this should be fixed in the snippet source.

**Comment by nul800sebastiaan** [comment]
I don't think we need to blow up the scope of this PR. 😅  It's difficult for me to imagine that at the time the snippet is added to a template that the `Model` is actually null. 

However, it might be good to iterate on this and do a review of all the snippets. We could do something to check if Model is null and then return a message saying we don't have a Model, but it will be difficult to guide people to fix that problem since we don't know the reason for that.

As some background info, these snippets are meant to be easy starting points for people inexperienced with Umbraco and it's querying syntax. They should be easy to read. Adding additional null checks for the more rare cases will make them less readable, but I think it's a good idea, making sure that we add nice comments in there saying something maybe like "this should rarely happen but..".

For now though, we wanted to have a small fix that would work for most people and this seems to work, so feel free to merge @mikecp! And congrats on your first pull request for Umbraco CMS @mikaellindemann 🎉

**Comment by mikaellindemann** [comment]
@nul800sebastiaan @mikecp Do we need a separate PR for Umbraco 9, or can it be backported automatically?

**Comment by nul800sebastiaan** [comment]
We're not really actively looking for updates for v9 any more. We expect newcomers to start on v10 and they may encounter this bug there, but if people have been on v9 for a while they will most likely already have dealt with this problem on their own. So all good for making this v10 only! 👍

**Comment by mikecp** [comment]
Hey @mikaellindemann , @nul800sebastiaan ,

Somehow your feedback escaped my radar, but I'll gladly merge the PR now 😁

Thanks @mikaellindemann and congrats on your first PR for Umbraco! If you provide us with your account name on Our, @nul800sebastiaan will be happy to assign our shiny contributor's badge to you 🥇

We'll be looking forward to your next contribution 😉

Cheers!

**Review by mikecp — APPROVED** [review]

**Comment by mikaellindemann** [comment]
GitHub and Our Umbraco should be aligned 😊: https://our.umbraco.com/members/mikaellindemann/

**Pull request merged**
