### PR TITLE
Add comments to methods in `IWebHookService`

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
Added comments to methods in new `IWebHookService`.

Not sure if create, update and delete should have `int userId = Constants.Security.SuperUserId` param like many others services, e.g. `IDataTypeService`:
https://github.com/umbraco/Umbraco-CMS/blob/a2a2680defd40ed0ef72fb85bf6d7a9bf1db33bc/src/Umbraco.Core/Services/IDataTypeService.cs#L75

which is used for `Audit()`:
https://github.com/umbraco/Umbraco-CMS/blob/a2a2680defd40ed0ef72fb85bf6d7a9bf1db33bc/src/Umbraco.Core/Services/DataTypeService.cs#L515

while looking into supporting Webhooks in management API, I noticed other services pass in `CurrentUserKey(_backOfficeSecurityAccessor)`, so maybe we need this later anyway?
https://github.com/umbraco/Umbraco-CMS/pull/15147/files#diff-33a00493a31cf8daad754645a3ba59e063c24b6aa7d9a89fc24a3226237f6a6eR35

### CODE REVIEW

**Comment by bjarnef** [comment]
@Zeegaan while looking at webhooks in https://github.com/umbraco/Umbraco-CMS/pull/15147 I think we could use a `GetMultipleAsync(IEnumerable<Guid> ids)`.

similar to languages:

```
public async Task<IEnumerable<ILanguage>> GetMultipleAsync(IEnumerable<string> isoCodes) => (await GetAllAsync()).Where(x => isoCodes.Contains(x.IsoCode));
```

**Comment by Zeegaan** [comment]
Hmm I considered this when doing the original implementation, but I'm not really sure where it would be useful to get multiple by ids 🤔 If you can think of a use-case that would use this, then I am open to implement it! 💪

**Comment by Zeegaan** [comment]
LGTM 🚀

**Comment by bjarnef** [comment]
@Zeegaan the multiple by ids, was because I looked into the management API in v14, which had an `Items` endpoint, but maybe we don't need if for webhooks 🤷‍♂️

**Comment by bjarnef** [comment]
Do we need `int userId = Constants.Security.SuperUserId` as well like on `IDataTypeService` - it seems it used for audits, but not sure about audits for webhooks?
Maybe it could be useful the multiple backoffice users has access to create webhooks and then also can be created from code (super user).

**Comment by Zeegaan** [comment]
For now no, its used for an Audit trail, but we don't need that for Webhooks. This should be more in line with `ILanguageService`` from v14 👍

**Pull request merged**
