### PR TITLE
Remove Newtonsoft.Json from ImageCropperPropertyEditor

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

This PR removes Newtonsoft.Json from ImageCropperPropertyEditor.

### Testing this PR

1. Given a document type with an image cropper property, validate that:
   - Copying a document results in the image cropper file being copied on disk as well.
   - Deleting a document results in the image cropper file being deleted from disk as well.
2. Given the default media type with an image cropper property, validate that:
   - Creating a media results in all "umbraco" system fields (width, height, bytes etc.) being populated correctly.
   - Changing the image cropper file on a media results in the previous image cropper file being deleted from disk, and all system fields being re-populated correctly.
   - Deleting a media results in the image cropper file being deleted from disk as well.

It might be easier to test this on V13, which is perfectly valid (although testing it on V14 is obviously preferred). The source can be transferred to V13 _almost_ without changes - get in touch with @kjac for details.

### CODE REVIEW

**Comment by bergmania** [comment]
I think we mis the stuff in `ImageCropperTemplateCoreExtensions.cs` that seems related

**Comment by kjac** [comment]
Turns out it was a case of invalid JSON in the media builder. That's not to say that the `ImageCropperTemplateCoreExtensions` class should not be amended too, but that's for another PR.

**Comment by nikolajlauridsen** [comment]
Just as a heads-up, I've migrated the `ImageCropperValueConverter` so I can fix the `ImageCropperTemplateCoreExtensions ` in my PR 😄 (fortunately the usage of Newtonsoft is entirely not needed in that class, no image value converter returns `JObject` or even `JsonDocument` or `JsonNode` 😄

**Comment by Migaroez** [comment]
Everything tests out ok, except that the media folder the file resides in still exits when removing media from the recycle bin

**Comment by kjac** [comment]
@Migaroez that's the current behavior too 😄

**Review by Migaroez — APPROVED** [review]

**Pull request merged**
