### PR TITLE
Fix U4-9977

### PR DESCRIPTION
**Pull request by Bitmapped**
Update fonts and stylesheet to include TinyMCE table icons missing per U4-9977

### CODE REVIEW

**Comment by Shazwazza** [comment]
Do we need the json files like tinymce-small.json ? (i'm not sure what these do but they are pretty large)

**Comment by Bitmapped** [comment]
I don't think the JSON files are specifically required. Its the font files that are needed because the glyphs are stored in them. I just basically brought over the fonts folder from the current TinyMCE release.

**Comment by Shazwazza** [comment]
ok cool, any chance you could test without the json files and if that works update this PR without them?

**Comment by Bitmapped** [comment]
Sorry for the delay in responding. Things seem to work OK without the JSON files in my dev install so I've removed them from the PR.

**Comment by madsrasmussen** [comment]
Thanks! It works like a charm 👍

**Pull request merged**
