### PR TITLE
U4-11437: Added 'Document Type Alias' title to appear on mouse hover …

### PR DESCRIPTION
**Pull request by AdamPrendergast**
…over 'Document Type Name' under content 'Info' tab

This is a minor, 'nice to have' feature that allows a developer to preview the Document Type Alias by hovering over the Document Type Name in the 'Info' tab on a content item without having to click and open the Document Type.

Similar functionality exists when hovering over property titles. This is really useful for a quick glance at what an alias is when developing.

*Changes Made*
Added 'alias' to the umbnodepreview directive. This is currently only used by 'umb-content-node-info.html'.

The label will simply not display if 'alias' is not set by other areas using the umbnodepreview directive.

---

This is my first attempt at a contribution - so I thought I'd keep it simple. All feedback welcome :)

### CODE REVIEW

**Comment by AdamPrendergast** [comment]
Going to add check for debug mode and admin login. This should only display when both of these conditions are satisfied

**Comment by nul800sebastiaan** [comment]
This is great @AdamPrendergast ! Thanks very much 👍 

And would you look at that shiny new Contributor badge! http://our.umbraco.org/member/26102

**Comment by AdamPrendergast** [comment]
Woo hoo! That's fantastic news @nul800sebastiaan 

I've spotted a few other cosmetic things while completing that task. Do I need to create an issue on http://issues.umbraco.org/ for each contribution? Or does that confuse matters?

Tak,
Adam

**Comment by nul800sebastiaan** [comment]
@AdamPrendergast Typically, if it makes sense that something shows up in the release notes then there should be an issue for it. Not each tiny change needs a separate issue though. Use your best judgement :-)

**Comment by AdamPrendergast** [comment]
Fantastic, thanks @nul800sebastiaan.

One more thing. The documentation will need updating here for 7.11 here:

https://our.umbraco.org/apidocs/ui/#/api/umbraco.directives.directive:umbNodePreview

I don't mind doing this but could do with an understanding of the workflow. Basically how can update the docs and does this have to happen after 7.11 is released?

Many thanks,
Adam

**Comment by nul800sebastiaan** [comment]
@AdamPrendergast What updates will it need? It works by updating the description in the file, like here: 
https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web.UI.Client/src/common/directives/components/umbnodepreview.directive.js#L7

This is built and updated automatically by the build server upon release.

**Comment by AdamPrendergast** [comment]
@nul800sebastiaan Right... that makes sense. I just need to add in the 'alias' parameter.

I'll do that later for you in a PR.

Thanks again,
Adam

**Pull request merged**
