### PR TITLE
Added gulp-angular-embed-template

### LINKED ISSUE #4845: V8: Inline AngularJS templates into directives and controllers
Currently all the templates for the various directives in the back office are pulled in via a templateUrl property. This causes angularjs to have to make a network request per template and load them all up to render the back office. There are a number of ways we can reduce that network traffic. I think we can do it purely via the existing build tools (Gulp) as well.

We can make some sizable performance improvements by changing the way we do this using one of two methods:

1. Bundle all the templates into a single file and then pre-load them into the templateCache for quick access. Achievable via https://www.npmjs.com/package/gulp-inline-angular-templates and https://www.npmjs.com/package/gulp-angular-templatecache
2. (preferred) Embed the templates as strings within the directives. Achievable via https://www.npmjs.com/package/gulp-angular-embed-templates

I prefer option 2 as it would give us the option of loading directives/components on the fly in the future which is something I'd love to move towards for yet more speed gains.

However either option comes at a bit of a cost regarding developers ability to poke around the code or to quickly make changes to the back office. You can't as easily hack around an AngularJS template for development once we go this route. Admittedly you shouldn't be doing this anyway as its easy to lose the change when you upgrade etc. but for quick and cheap "learning by hacking" we would lose some of the ease with which you could do that. To be fair I think this is totally worth it as in my eyes we should be moving to more cleaner code base which would enable this anyway and this is a step in the right direction, one of many I'd like to see it take on.

What can I do?

I'm happy to do a play around and see if I can get this in and working and then document any improvements in performance it makes and then update any docs on the tool chain that people should be aware of. Basically I'd love to just get it working and a PR put in :)

### PR DESCRIPTION
**Pull request by PeteDuncanson**
Fixes #4845 by embedded the angularjs templates for directives in the directives, cuts down on network traffic and increases speed to render

To test. Assuming you have already got a built version of the code up and running go take a look at the /src/umbraco.web.ui/umbraco/js/umbraco.directives.js file size, copy the file and rename it to something you'll remember (I just add "_pete" to the end of the file extension). Ensure the back office all runs as it should.

Change directory in a command prompt to "/src/umbraco.web.ui/" folder. 

Run `npm install` to get the new goodies in your build chain.

Run `gulp js` or `gulp dev` with the new config in this PR which will regenerate the javascript using the new bit of magic. Now compare the file size of the umbraco.directives.js file, it should have increased.

Hit up the back office again and ensure everything is working. Check that the number of network requests between the to checks has reduced as per the screen shots in the original issue. 

https://github.com/umbraco/Umbraco-CMS/issues/4845

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @PeteDuncanson 

Thanks for your work on this. One of us will take a look and let you know if we need anything.

Thanks,

Em

**Comment by PeteDuncanson** [comment]
Any update on this one? The build appears to have broken on restoring nuget which is kind of out of my hands. Can someone retrigger it so we can see if the light goes green and its good to pull in?

**Comment by Shazwazza** [comment]
Have queued a rebuild, we'll see what happens.

@nielslyngsoe have you seen this one yet? If you have a chance, please have a read through the info at #4845

**Comment by nul800sebastiaan** [comment]
I've given this a spin and it works like a charm. Great description too so I know what I'm looking for and WHY ⭐️  

Thanks @PeteDuncanson ! 👍

**Pull request merged**
