### PR TITLE
V8: Add optional culture parameter to UrlAbsolute extension

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

I find myself needing the absolute URL to all culture variants of a given page. Unfortunately the `UrlAbsolute()` extension method on `IPublishedContent` does not allow for specifying a culture for the absolute URL.

This PR fixes it. When applied you can specify a culture name in - e.g. `myPage.UrlAbsolute("da-DK")`. The culture name is optional, so `myPage.UrlAbsolute()` still works.

#### Breaking change?

Theoretically this is a breaking change. However, I really don't see it being breaking in any practical term:

- Code that references the extension method will be recompiled when upgrading Umbraco and rebuilding the project, so no problem there.
- Views that use the extension method will be recompiled at runtime after an upgrade, so no problem there either.

This leaves behind packages that reference the extension method. They may or may not break (there seem to be divided opinions when searching for any kind of concrete answers here). However, *if* indeed they break I'd rather break them this early in the V8 lifecycle than later on. 

The alternative is to have an overload of `UrlAbsolute()`, which *could* lead to compile time errors later on (`The call is ambiguous between the following methods or properties...`), and which would have to stay in the source forever.

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Correction, @abjerner made the great point that the original method without culture might still be fine.

**Comment by kjac** [comment]
I'm pretty sure @dawoe is correct, but I'll add the overload anyway.

**Comment by kjac** [comment]
@nul800sebastiaan wait... so *don't* add the overload?

**Comment by nul800sebastiaan** [comment]
@kjac Sorry, that was unclear. Yes to the overload, but don't deprecate the original method. 😅

**Comment by kjac** [comment]
@nul800sebastiaan all done 👍

**Comment by nul800sebastiaan** [comment]
Thanks @kjac - all good now! 👍

**Comment by christophnz** [comment]
Note that as of 8.1 `UrlAbsolute()` has actually been removed altogether from `PublishedContentExtensions.cs` and I have found that the "correct" way to doing this is now `.Url(mode: UrlMode.Absolute)`

(see: https://github.com/umbraco/Umbraco-CMS/commit/11ef00c63d9773fccf1d58897a74f7808c428760#diff-182d0a3c19feafdbcc33e1798ad57511) and further down in `UmbracoContext.cs` this added line: `[Obsolete("Use the Url() method with UrlMode.Absolute.")]`

**Pull request merged**
