### PR TITLE
WIP - Create ISmtpService and a implementation using Mailkit

### PR DESCRIPTION
**Pull request by Jeavon**
System.Net.Mail.SmtpClient is obsolete, it needs to be replaced with Mailkit. (#5512)
I started replacing it directly but realised that there should be SmtpService within Umbraco so I started working on adding this.
At this early stage, I have been working out all the parts that are needed and adding base files etc. I would like some guidance to ensure my plan (files, naming etc) is v8 correct which is why I have opened this PR early.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @Jeavon!

Thanks for the Pr. I can see it's a WIP so we'll hold off until you're ready for us to take a look.

Em

**Comment by Jeavon** [comment]
@Shazwazza following on from #5512 I will proceed with this approach and check in again with you once there's something worth discussing.

**Comment by ronaldbarendse** [comment]
IMHO the first change should be to update all mail sending methods to use `IEmailSender` (as per https://github.com/umbraco/Umbraco-CMS/pull/2029#issuecomment-440525735 from @Shazwazza), not to introduce another dependency (MailKit)...

The built-in `SmtpClient` just works, so keeping the existing `EmailSender` implementation should be fine. Whenever you require additional features (e.g. provided by MailKit), you should be able to change the implementation. This would also make it possible to change to a non-SMTP implementation, e.g. using SendGrid, SparkPost, etc.

**Comment by Jeavon** [comment]
I'm going to close this draft PR as it's being superseded in Unicore

**Pull request closed without merging**
