### PR TITLE
Get multiple with keys function for dictionary items

### PR DESCRIPTION
**Pull request by patrickdemooij9**
This is something that I've wanted for some time now. Within Umbraco we have the GetDictionaryValue function. However, you can only pass one key through it. This is annoying as each GetDictionaryValue call is a call to the database if that key hasn't been put into the cache yet. Meaning that on first load of a page with 20 dictionary values, it'll do 20 calls to the server.

By being able to ask for multiple dictionary values, we'll be able to combine the SQL and reduce it down to 1 call which will save a lot of time for the initial startup of a page. 

I tested it with the following code:
```
@{
    var translations = new string[] { "Test", "Test2", "Test3", "Test4", "Test5" };
}

<html>
<body>
<h1>Old</h1>
@foreach (var translation in translations)
{
    @Umbraco.GetDictionaryValue(translation)
}

<h1>New</h1>
@foreach (var test in _localizationService.GetDictionaryItemsByKeys(translations))
{
    @test.Translations.FirstOrDefault().Value
}
</body>
</html>
```

### CODE REVIEW

**Comment by patrickdemooij9** [comment]
Looked a bit further into this as I was wondering why the Default App Policy wasn't caching for me when I would use that one instead of the SingleItemsOnlyRepositoryCachePolicy. Here (https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Infrastructure/Cache/DefaultRepositoryCachePolicy.cs#L208) we are checking if there are any cached items related to the ids given. So this would check something like "Test1", "Test2".

If they don't exist in cache yet, but are found later on, they are then added to the cache here (https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Infrastructure/Cache/DefaultRepositoryCachePolicy.cs#L75). One big issue though is that it is using the entity.Id! This won't work with the DictionaryRepository as the caching checks on the ItemKey. Not quite sure how we would be able to fix this, especially as we also need it on ids for the DictionaryByUniqueIdRepository.

**Comment by nathanwoulfe** [comment]
Hey @patrickdemooij9 pretty sure this will be a breaking change as it's modifying a public interface, even as an additive change.

@nul800sebastiaan can correct me if I'm wrong, but I think this will need to target v10

**Comment by nathanwoulfe** [comment]
Or, instead of waiting for v10, introduce ILocalizationService2, inheriting ILocalizationService, and add the new method to 2. Umbraco registers the new interface, but nothing breaks downstream for anyone implementing a custom ILocalizationService. Then, come v10, the two interfaces merge back into ILocalizationService

@nul800sebastiaan are we ok with doing this? I'm sure I've seen it done in other places...

**Comment by patrickdemooij9** [comment]
Working with some caches on work today and I was reminded back to this PR. I think there might be an issue in here with making the cache invalid due to the new cache keys. Will have to take a look at it later, but wanted to let you know in case this PR already gets approved in the meantime

**Comment by nul800sebastiaan** [comment]
It looks like this was already implemented, I can't see a PR specifically but it looks like it came in from this mammoth merge : https://github.com/umbraco/Umbraco-CMS/commit/6dc874147f14c06d975aac09d7fd12ab2b159bc8

Specifically the interface and method now look like this, pretty close to what you had as well:

https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Persistence/Repositories/IDictionaryRepository.cs#L11
https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Core/Services/LocalizationService.cs#L226

Thanks for the help @patrickdemooij9 and sorry we didn't get to it earlier! I'll close this one, thanks again!

**Pull request closed without merging**
