### PR TITLE
Add section icon in section picker + clean up V7 section icon handling

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/4450

### Description

In V7 we have icons for the sections. In V8 these are gone. As outlined in #4450 this has an impact on the group editor.

This PR cleans up a bunch of unused V7 section icon handling and adds a generic icon to the section list and picker in the group editor. It looks like this:

section-icons

The icons have solely been added for consistency with the rest of the UI. Since the sections have no icons, it would not make sense to have different (meaningful?) icons for each section in the list/selector as these icons wouldn't convey any meaning - at least not to new V8 users.

### CODE REVIEW

**Comment by bjarnef** [comment]
@kjac better than before 👍 
Not sure if it should still be possible to add section icons although not used in global navigation with sections, e.g. also when adding custom sections?

I guess Umbraco HQ should decide whether it makes sense to keep icons here and if it should be optional to set an icon (maybe we fallback to this `icon-application-window` if not set?). // cc @hartvig

**Comment by kjac** [comment]
Yeah... I don't think custom icons make sense if they're not used actively in the UI. If you haven't seen the V7 UI, you'll probably be wondering where the heck those icons came from and what they mean.

**Comment by bjarnef** [comment]
Yes, it might be a bit confusing to Ed Itor 😁😆

**Comment by kjac** [comment]
Hah! 😆

**Comment by bjarnef** [comment]
@nul800sebastiaan what to do with the section icons in v8? Should we use fallback icons like this or should sections still have icons to keep section picker consistent with other pickers?

**Comment by nul800sebastiaan** [comment]
We're moving away from icons in favor of meaningful text where possible and needed.

As such there will be no section icons in the v8 backoffice. I think these icons look absolutely fine and they server a pretty good purpose in this case. 👍

**Pull request merged**
