### PR TITLE
U4-6902 - Changed from internal to public

### PR DESCRIPTION
**Pull request by rasmuseeg**
Just like the ContentFinderResolver.cs

### CODE REVIEW

**Comment by rasmuseeg** [comment]
Danm forgot to name the branch: U4-6902

**Comment by Shazwazza** [comment]
We'll need to review this, the thumbnails provider thing is super old and probably shouldn't even exist IIRC. I'll get back to you but i think this is totally superceded by using Image processor.

**Comment by rasmuseeg** [comment]
@Shazwazza Okay, but what i'm trying to do is create a AbstractThumbnailResolver for pdf's files?

**Comment by Shazwazza** [comment]
right, forgot it was used for that... i'll pull this in, might become obsolete one day though.

**Comment by rasmuseeg** [comment]
Cool, thanks :+1: - Shame, i like the simplicity for inserting types this way ;-)

**Comment by Shazwazza** [comment]
The resolvers wont get obsoleted, but the IThumbnailProvider thing is super old and not sure it makes a lot of sense anymore but i guess we use it for weird things like icons for file types.

**Comment by rasmuseeg** [comment]
Umbraco could be prettier on that part :-) Icons for common used file types, like pdf, xlst, csv etc.

**Pull request merged**
