### PR TITLE
added round corners in umb-media-grid for media-picker

### PR DESCRIPTION
**Pull request by nielslyngsoe**
Added round corners on items in media-picker.

image

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
@nielslyngsoe As discussed here: https://github.com/umbraco/Umbraco-CMS/pull/8686#issuecomment-680700097

Is rounded corners something you want or don't want? ;-)

**Comment by nielslyngsoe** [comment]
@nul800sebastiaan I know exactly what I want, I want consistency and a friendly look. 🤩

To answer your concern: I would like round corners on these as that unifies the look of 'cards', makes them more friendly.

**Comment by bjarnef** [comment]
@nielslyngsoe in that case it would be great to update all pickers "add" buttons to use rounded corners as well. I think would should have a New class instead of `umb-node-preview-add` but keep this for legacy support.

In the HTML pickers will use this class or in less extend from this class, so we only need to update this one place.

**Comment by nielslyngsoe** [comment]
@bjarnef I think that sounds like a good plan, it sounded like you had a good idea about how to go about it, so feel free to make your suggestion as a draft PR. then we can finish it together?

**Pull request merged**
