### PR TITLE
Change GetMinNonAlphaNumericChars() to return 1

### PR DESCRIPTION
**Pull request by niekvanderreest**
Change the return value of this extension method to return either 0 or 1. Returning 2 forces all passwords to contain at least 2 special characters when using this extension in code to check if a password meets requirements

Image of  Microsoft.AspNetCore.Identity.PasswordOptions, does not default to 2 special characters (it's not configurable)
image

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks @niekvanderreest! The code update makes sense to me but can you please guide me in how I can test it?

**Comment by niekvanderreest** [comment]
@nul800sebastiaan

You can test this in a SurfaceController with an EditPassword function.
You'll need to inject an IOptions settings class: 
private readonly MemberPasswordConfigurationSettings _memberPasswordConfigurationSettings; 
And in constructor
IOptions<MemberPasswordConfigurationSettings> memberPasswordConfigurationSettings

Constructor code block:
_memberPasswordConfigurationSettings = memberPasswordConfigurationSettings.Value;

Example:
```
private readonly MemberPasswordConfigurationSettings _memberPasswordConfigurationSettings;

public MemberController(IOptions<MemberPasswordConfigurationSettings> memberPasswordConfigurationSettings)
{
    _memberPasswordConfigurationSettings = memberPasswordConfigurationSettings.Value;
}
```

In appsettings.json set "RequireNonLetterOrDigit" to true:
(My config settings)
```
"Security": {
  "MemberPassword": {
    "RequiredLength": 10,
    "RequireNonLetterOrDigit": true,
    "RequireDigit": false,
    "RequireLowercase": false,
    "RequireUppercase": true,
    "HashAlgorithmType": "PBKDF2.ASPNETCORE.V3",
    "MaxFailedAccessAttemptsBeforeLockout": 5
  }
},
```

You can then withness that _memberPasswordConfigurationSettings.GetMinNonAlphaNumericChars() returns 2
``` 
var minRequiredNonAlphanumericCharacters = _memberPasswordConfigurationSettings.GetMinNonAlphaNumericChars();
if (minRequiredNonAlphanumericCharacters > 0)
{
    var num = model.NewPassword.Where((t, i) => !char.IsLetterOrDigit(model.NewPassword, i)).Count();
    if (num < minRequiredNonAlphanumericCharacters)
    {
        ModelState.AddModelError("", "Je wachtwoord moet minimaal " + minRequiredNonAlphanumericCharacters + " speciale tekens bevatten");
    }
}
```

**Comment by nul800sebastiaan** [comment]
@niekvanderreest Oh I see, can I ask please why you're manually checking the password configuration?

`_memberManager.ValidatePasswordAsync(newPassword)` (in `IMemberManager`) should do all of that for you and return a `Succeeded` and `Errors` object for you to work with.

**Comment by niekvanderreest** [comment]
@nul800sebastiaan, 
It's a project migration from umbraco 7 to umbraco 10, trying to avoid as much code changes as possible, also I noticed that the returned errors from _memberManager.ChangePasswordAsync and _memberManager.ResetPasswordAsync (have not checked ValidatePasswordAsync) are not always in the correct localisation (Dutch)

So the checks are there to return messages before even trying a change, I guess _memberManager.ValidatePasswordAsync(newPassword) would do the same thing though!

**Comment by nul800sebastiaan** [comment]
@niekvanderreest that seems correct, the keys have not been translated to Dutch yet 

image

I'm not saying we shouldn't fix the code above, but you can translate the required keys by dropping in a user translation file:


```xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<language alias="nl" intName="Dutch" localName="Nederlands" lcid="" culture="nl-NL">
  <creator>
    <name>The Umbraco community</name>
    <link>https://our.umbraco.com/documentation/Extending-Umbraco/Language-Files</link>
  </creator>
  <area alias="user">
    <key alias="passwordRequiresNonAlphanumeric">TRANSLATEME</key>
  </area>
</language>
```

The file would go into the folder where your website's `.csproj` file is in `config\lang\nl.user.xml`.

I highly recommend you try that out instead of writing a lot of code to duplicate our code. 😅

image

**Comment by nul800sebastiaan** [comment]
Whoops wrong button! 

I just gave that a go, and there's more to translate.. but most importantly, there's a silly extra message that you indeed would want to update under the first password field:

image

So, while I still encourage you to use the built-in `memberManager`, it would give you the wrong message anyway, this PR fixes that. 👍

**Comment by niekvanderreest** [comment]
@nul800sebastiaan,

Would providing a file with translations to dutch be something one can provide as a small community contribution?

**Comment by nul800sebastiaan** [comment]
Thanks again @niekvanderreest, works like a charm! 👍 

> Would providing a file with translations to dutch be something one can provide as a small community contribution?

Yes! That would be an excellent additional update, go for it!

**Comment by nul800sebastiaan** [comment]
Cherry picked for 10.5 in 0ce2fdb23b1064b8f3b1c8ef1c7250e803db9a0b

**Pull request merged**
