### PR TITLE
Fix swedish translation for somethingElse.

### LINKED ISSUE #9796: Umbraco Heartcore: Button is wrongly translated to swedish which causes some confusion among our editors.
In Umbraco Hearcore (with Swedish translation):

**1.**  When selecting a content- or Media node in the tree structure
**2.** then pressing the "..." that appears to the right of the Node title a "Create dialog" opens to the right of the tree structure.
**3.** At the bottom right corner of this dialog there is a button to show the "Edit actions" of the actual node. This button is translated to "Ångra" in swedish which means "Regret". 

Is it possible to find a more suitable translation for this button, and/or make the Edit actions more accessible?

See steps 1-2-3 in the image:
image

## Umbraco version

I am seeing this issue on Umbraco version: Umbraco Heartcore

Reproduction
------------

If you're filing a bug, please describe how to reproduce it. Include as much
relevant information as possible, such as:

### PR DESCRIPTION
**Pull request by jesperlofgrensappa**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #9796 

### Description

I fixed the translations for the somethingElse key which was translated to the swedish word for "Regret". The new translation is now word for word "Do something else".

Here's where you can find the translated text:
image

### CODE REVIEW

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Thanks @jesperlofgrensappa for this PR, let's merge it without regrets 😉

And since it is your first contribution, @nul800sebastiaan will gladly assign you your contributor badge on Our. Congratulations! 👍

**Comment by nul800sebastiaan** [comment]
Thanks @jesperlofgrensappa - if you can send me a link to your profile on [Our Umbraco](https://our.umbraco.com/) then I'll happily add a contrib badge for you! 👍

**Comment by jesperlofgrensappa** [comment]
Thanks for approving! This is my profile https://our.umbraco.com/members/jesperlofgrensappa/

**Comment by nul800sebastiaan** [comment]
Thanks! And congrats on your shiny new contrib badge! 🎖️

**Pull request merged**
