### PR TITLE
Logviewer adjustments

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
This PR updates a few things in log viewer:

- Replace anchors with `<button>` elements
- Use `<umb-icon>` and fixes issue with toggle arrow up/down icon when open/close "saved searches"
- Fixes issue with self-closing angular `<umb-checkbox>` component in log levels dropdown (in this case the self-closing custom angular element didn't cause issues except additional whitespace)
- Updates log levels colors to better match the log level type
- Empty state message isn't showm while loading (e.g. when selecting the different log levels from the dropdown)

I think the colors of the log levels was a bit off. Often "orange" is associated with "warning" and "red" is associated with "error".
I have then chosen a dark gray (close to black for "Fatal" log level). Furthermore I have updated "Debug" to use a blue "info" color, since "Debug" and "Verbose" colors is a bit too close to each other.

I searched a bit for "log level colors" and something like these examples seemed to be familiar:

image

image

### CODE REVIEW

**Comment by bjarnef** [comment]
**Before**

chrome_2020-07-29_19-43-26

**After**

image

**Comment by nathanwoulfe** [comment]
For what it's worth, I like it. 🎨

**Comment by nul800sebastiaan** [comment]
Looks great to me too! I added `rel="noreferrer"` to links that have `target="_blank"` for security reasons.

**Comment by bjarnef** [comment]
Thanks @nul800sebastiaan
I will try to remember adding this in future for other links with `target="_blank"`
https://web.dev/external-anchors-use-rel-noopener/

**Pull request merged**
