### PR TITLE
Makes sure the nucache is not truncated when its null

### LINKED ISSUE #14253: NuCacheContentRepository.Rebuild can truncate the table without rebuilding the cache
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.3.1

### Bug summary

When calling: `NuCacheContentRepository.Rebuild(null, null, null)`
The `cmsContentNu` table gets truncated but no of the rebuild methods gets called leaving the  `cmsContentNu`  table empty.

### Specifics

_No response_

### Steps to reproduce

1. call: `NuCacheContentRepository.Rebuild(null, null, null)`
2. see the table `cmsContentNu` is empty after the call

### Expected result / actual result

I would expect a method called Rebuild to actual perform a Rebuild and not just leave the cache empty.
in the `Rebuild*DbCache()` methods passing null or an empty array is treated equally but this is not the case in the `Rebuild()` method.

I would suggest changing the checks before the truncate to:
```
if ((contentTypeIds != null && !contentTypeIds.Any())
      && (mediaTypeIds != null && !mediaTypeIds.Any())
      && (memberTypeIds != null && !memberTypeIds.Any()))
{
    if (Database.DatabaseType == DatabaseType.SqlServer2012)
    {
        Database.Execute($"TRUNCATE TABLE cmsContentNu");
    }

    if (Database.DatabaseType == DatabaseType.SQLite)
    {
        Database.Execute($"DELETE FROM cmsContentNu");
    }
}
```
this ensures we don't truncate if null is passed

the other way would be to remove the `if` statements around the `Rebuild*DbCache()` method calls

### PR DESCRIPTION
**Pull request by DeadMonkeyX**
### Prerequisites

- [X] I have added steps to test this contribution in the description below

### Description

This pull request should fix #14253  by changing the checks in the `NuCacheContentRepository.Rebuild` to make sure that it does not truncate the table if null is passed as parameters

### Test
    1. call: NuCacheContentRepository.Rebuild(null, null, null)
    2. see the table cmsContentNu is not empty after the call

https://github.com/umbraco/Umbraco-CMS/issues/14253

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi @DeadMonkeyX 

Just checking as I'm trying to debug it. Did you test this with a SQL Server instance as opposed to SQLLite? 

Because delete is called instead of truncate on the SQLLite db instance, so I just wondered if this affected the use case at all before I test it. 

Thanks


Emma

**Comment by emmagarland** [comment]
Hi @DeadMonkeyX 

I can confirm I've replicated this scenario. I've just tweaked the code to remove the extra brackets.

My replication steps were:

**Before this PR**

CmsContentNu table: 

1. Debug Umbraco
2. Put a breakpoint in method `RebuildDatabaseCacheIfSerializerChanged()` in `NuCacheContentService`, to fake a rebuild of the cache being needed
3. Startup the application or save a document type to trigger the `_publishedSnapshotService` Event handler and therefore the Rebuild method
4. Set all the default values of the parameters in the Rebuild method to null in debug
5. Observe error
Screenshot of error


6. Observe the empty `CmsContentNu `table:

Empty CmsContentNu table

 
**After this PR**
 
`CmsContentNu `table is populated: 
Populated CmsContentNu table


1. Debug Umbraco
2. Put a breakpoint in method “RebuildDatabaseCacheIfSerializerChanged()” in NuCacheContentService, to fake a rebuild of the cache being needed
3. Startup the application or save a document type to trigger the _publishedSnapshotService Event handler and therefore the Rebuild method
4. Set all the default values of the parameters in the Rebuild method to null in debug
5. No error is thrown and the `CmsContentNu `table remains the same:

Populated CmsContentNu table

RE the SQLLite table so I wondered if this would happen too, but I didn't manage to replicate this yet. 

Once the tests have run, we can merge this PR to fix issue #14253. 

Thanks again so much for the fix! 👍 

Emma

**Comment by emmagarland** [comment]
Hi @DeadMonkeyX, this PR has now been successfully merged! 🙌 Great work!

**Comment by DeadMonkeyX** [comment]
Hey @emmagarland 

Thank you very much :) 

I'm so happy that it is now merged :D

**Comment by emmagarland** [comment]
@DeadMonkeyX Fantastic! And since I've just seen it's your first contribution to Umbraco, you can now have a shiny new contributor badge on your Our Umbraco profile! One of the team will sort this for you soon 😎👏

**Comment by emmagarland** [comment]
Hi @DeadMonkeyX 

Just to let you know that you now have a shiny new Contributor badge on [your Umbraco profile](https://our.umbraco.com/members/id:296085/) 🎉 

Thanks

Emma

**Comment by nul800sebastiaan** [comment]
Cherry picked for v10/11 in 76ad99beb015d390ad6fd8f91bf464d9a01c321d

**Pull request merged**
