### PR TITLE
V8/dev/upgrading gulp to v4

### PR DESCRIPTION
**Pull request by readingdancer**
This is related to issue: #4846

### Description

I had previously looked at upgrading the client side build to use Gulp 4 and to update the various dependencies to remove all the client side build security warnings. I noticed that @PeteDuncanson has also looked at this back in March, but I am guessing it's been slightly forgotten in the TODO pile, so I hope it's ok to submit this pull request :)

This pull request does the following:

1) Updates the client side build to use Gulp 4
2) Updated the Gulpfile to use Require and Export statements, which is now the recommended way of adding tasks, currently they are all in series, we can maybe start to run some items in Parallel as we improve this further.
3) Updates as many of the dependencies as possible to remove the security warnings, we have gone from about 60 down to 16.
4) Added the Karma Spec Reported to allow the Client side unit test report to be more useful than just a list of numbered tests passing, it makes it much easier to see what is wrong, see screen shot.
5) Fixed a couple of typos.

TODO

The last security issues are all related to the gulp-ngdocs package which from GitHub looks rather dormant, it's not been updated for 3 year ( https://github.com/nikhilmodak/gulp-ngdocs )

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey Chris! 

Thanks for the work here. We'll take a look and let you know if we need anything further from you.

Em

**Comment by nul800sebastiaan** [comment]
Thanks @readingdancer ! Sorry for the delay, I've been on a little holiday. We'll need to review and test this one some more but I think it's a good one to work on for 8.2.

The one thing I do see a problem with at the moment is that you've undone all the recent work to split the build process up into smaller files. I will plead complete ignorance as to why this was done, that's all @nielslyngsoe's territory but I am sure he had good reason for that. Is there any reason to combine these `gulps/tasks` files into one again?

**Comment by nul800sebastiaan** [comment]
Ah, don't mind me, it's not actually combining all of them again, all good!

The docs build actually works right now. I don't see the problem in leaving it there, we are not shipping vulnerable code that I know off, the only place that the docs output goes is to Our. I'd need to check if the related security vulnerabilities would end up on Our though, but it seems unlikely.

**Comment by readingdancer** [comment]
Hi @nul800sebastiaan 

I hope you had a good holiday?

As you probably noticed when you dug a little deeper, the solution is still split into separate files, however I have removed files that were essentially combining other files which I think makes things clearer from within the top level Gulpfile.

In Gulp 4 you can now goup tasks using the Series and Parallel functions, currently everything is still running in Series, but I think it may be possible to change some of these to run in Parallel. We have done this on some of our site builds and it can potentially reduce the time to takes to build the solution on a multi-core machine ( which most people use these days ).

Here's a link to that part of the Gulpfile:

https://github.com/umbraco/Umbraco-CMS/pull/5806/files#diff-434c93137cc20bdf2e2f527f6b98ce58R29

I agree about the Docs, it would just be nice if we could remove all these warnings / errors to make the build as clean as possible :)

If there is anything else you are unsure about, feel free to ping me on Skype or reply to this thread :)

Cheers,

Chris

**Comment by readingdancer** [comment]
Hi @emmaburstow & @nul800sebastiaan 

I just wondered if you have had a chance to look at this pull request? After doing all the work on this almost a month ago, it would be a shame for it to become forgotten...

Cheers, Chris

**Comment by nul800sebastiaan** [comment]
Apologies for the delay, in the mean time we've had a couple of huge releases and a serious security issue to deal with, so the priorities had to shift.

I would really like to get back into this one but we really need that docs build to actually work, even if it's all deprecated and shows warnings. After investigating it a few months ago, we found that there's currently no alternatives to build the docs. 

Could you please look into enabling the docs build again and seeing if that works?

**Comment by nul800sebastiaan** [comment]
Just as an update, we're still working on this. We've separated out the Docs project into it's own directory so that it doesn't affect the rest of the build any more. https://github.com/umbraco/Umbraco-CMS/pull/6409

This means the blocker in this PR has been lifted. I will try to do a merge now and see how far I get.. 🙈

**Comment by nul800sebastiaan** [comment]
Alright, apart from a little mistake in my merge, that worked quite well. All corrected now and it does seem like the build output is quite the same as before this change. So it's time for @nielslyngsoe to give it another look!

**Comment by nielslyngsoe** [comment]
Hi @readingdancer thanks for your work on this matter, and as well pushing for this to happen. I have taken your PR and build on top of it to ensure that everything works and is up to date. Please feel free to have a look and provide changes if you see any issues with the current state.
https://github.com/umbraco/Umbraco-CMS/pull/6809

By the way this means that I will close this one and the talk can continue on the new PR

**Comment by nul800sebastiaan** [comment]
Thanks again @readingdancer for kickstarting this, it's been a bit interesting for HQ to understand what the build is doing and why, but we've finally got it all figured out (we think 😮 ). Your changes and our updates have now been merged: https://github.com/umbraco/Umbraco-CMS/pull/6809

Thanks!

**Comment by readingdancer** [comment]
For some reason I didn't see any of the last 5 comments until now, I am glad that this PR was helpful in the end :)

**Pull request closed without merging**
