### PR TITLE
Update noUiSlider to v15.2.0

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
This PR upgraded noUiSlider to latest ~~v15.1.1~~ v15.2.0
https://github.com/leongersen/noUiSlider/releases

This also includes a new `drag` event, which allow to drag the connect between two handles and using the `connect` option: https://refreshless.com/nouislider/slider-options/#section-connect

```
vm.sliderOptions = {
    "start": [25, 75],
    "step": 1,
    "behaviour": 'drag-tap',
    "connect": [false, true, false],
    "tooltips": [true, true],
    "format": {
        to: function (value) {
            return value.toFixed(2);
        },
        from: function (value) {
            return Number(value);
        }
    },
    "range": {
        "min": 1,
        "max": 100
    }
};
```

GosW4pfKOK

### Test notes
- Check slider in Image Cropper still works.
- Check slider in Media Picker v3 works as expected.
- Check custom slider in e.g. a dashboard. An example here: [MyDashboard.zip](https://github.com/umbraco/Umbraco-CMS/files/6534866/MyDashboard.zip) and the implemented `onDrag` event is triggered.

### CODE REVIEW

**Comment by bjarnef** [comment]
In Umbraco 8.14.0-RC is look like this, but no event is fired when dragging the connect, because the `drag` event doesn't exists in noUiSlider until v15.1.0: https://github.com/leongersen/noUiSlider/releases/tag/15.1.0

The connect could however need some UI love as well if using this feature:

igDS0N9rYO

// cc @madsrasmussen @nielslyngsoe

**Comment by bjarnef** [comment]
Color of the connect has been updated in https://github.com/umbraco/Umbraco-CMS/pull/10349

**Comment by bjarnef** [comment]
We could probably update this to v15.2.0 at the time of this writing: https://github.com/leongersen/noUiSlider/releases/tag/15.2.0

**Comment by nul800sebastiaan** [comment]
Go for it @bjarnef!

**Review by nul800sebastiaan — APPROVED** [review]

**Comment by bjarnef** [comment]
@nul800sebastiaan should this be target for v8.16.0 release.. I guess it is too late for v8.15.0?

**Pull request merged**
