### PR TITLE
Added missing Sql mapping for standard Replace function:

### PR DESCRIPTION
**Pull request by pynej**
.Where<MyModel>(s => s.Name.Replace(" ", "-") == userName)

Should generate valid SQL:
REPLACE([dbo].[MyModel].[Name], ' ', '-')

### CODE REVIEW

**Comment by Shazwazza** [comment]
Interesting, is this going to work with MySql and SqlCe ?

**Comment by Shazwazza** [comment]
Also, we need a link to an issue for this if you can make one

**Comment by clausjensen** [comment]
http://issues.umbraco.org/issue/U4-8775

**Comment by pynej** [comment]
According to the Doc's both SqlCe and mysql support the function natively and with he same syntax.

**Comment by Shazwazza** [comment]
Cool - any chance you could chuck in a unit test some place for this?

**Comment by pynej** [comment]
It would need to go in this file, but I can't seam to figure out how to get the tests to run on my VS 2015 Express install.

/Tests/Umbraco.Tests/Persistence/Querying/ExpressionTests.cs

**Comment by Shazwazza** [comment]
k cool, we'll see what we can do when we review, cheers!

**Comment by Shazwazza** [comment]
btw, we use Resharper test runner - so you might want to try that

**Comment by pynej** [comment]
I added a test that should be located in the right place, and in theory will work.  I'm still trying to figure out how to get my software setup to actually run a test :)

**Comment by pynej** [comment]
I can't load ReSharper on my addition to VS.  I put in a basic test  though that will just need to be reviewed and tweaked as needed.

**Pull request merged**
