### PR TITLE
http://issues.umbraco.org/issue/U4-8530

### PR DESCRIPTION
**Pull request by davidwincent**
Adds Preview property to ContentItemDisplay

### CODE REVIEW

**Comment by davidwincent** [comment]
Might need some documentation.
I have tested the solution with an event handler similar to this:

```
    public class StartupEventHandler : ApplicationEventHandler
    {
        protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {
            base.ApplicationStarted( umbracoApplication, applicationContext );
            EditorModelEventManager.SendingContentModel += EditorModelEventManager_SendingContentModel;
        }

        private void EditorModelEventManager_SendingContentModel(System.Web.Http.Filters.HttpActionExecutedContext sender, EditorModelEventArgs<Models.ContentEditing.ContentItemDisplay> e)
        {
            if (e.Model.ContentTypeAlias == "testDoc")
            {
                e.Model.Preview = false;
            }
        }
    }
```

**Comment by davidwincent** [comment]
@Shazwazza - We discussed this at codegarden. Is this the solution you had in mind?

**Comment by davidwincent** [comment]
OK, thanks!
Should be fairly easy to implement and will be hidden for anyone that does not need this feature.

**Comment by Shazwazza** [comment]
The issue with this is that it is button specific, the model needs to control all buttons that can be toggled. I'll pull this in and update the logic.

**Comment by Shazwazza** [comment]
Actually, i now realize that the other buttons are controlled by the 'AllowedActions' list, preview is handled separately because it's not a permission based button . So all I'll do is update some of the names. Thanks! :)

**Comment by davidwincent** [comment]
Great! H5YR

**Pull request closed without merging**
