### PR TITLE
check for recursive value

### PR DESCRIPTION
**Pull request by poornimanayar**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org/issue/U4-8617

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @poornimanayar 

Thank you for submitting this pull request! We will aim to review this in the next 14 days and will get back to you regarding our progress with it.

Thanks!

Emma (CPR team)

**Comment by emmaburstow** [comment]
Hi @poornimanayar 

I'm just looking at this and wondered if you could give me a bit more info as to how I can see it working? All looks great but just want to make sure I've been thorough.

Thanks,

Emma

**Comment by poornimanayar** [comment]
Haha @emmaburstow Let me try recollecting what I did.

Poornima

**Comment by nul800sebastiaan** [comment]
This one is not easy to repro (webforms, yikes!) - but I got it and the fix is good! 

Thanks @poornimanayar ! 👍

**Pull request merged**
