### PR TITLE
v7: fix content service - unpublish

### LINKED ISSUE #8393: V7: it is impossible to remove node with children after unpublish only parent.
v7: 7.15.4
Steps to reproduce:
1) install Umbraco with Starter Kit
2) Unpublish about Us
3) Try to remove About Us
Expected result:
About us with childrens will be moved to trashbin
Actual result:
image

### PR DESCRIPTION
**Pull request by bielu**
### Prerequisites

- [ ] Step to test are describe in following issue

If there's an existing issue for this PR then this fixes #8393

I added logic if there is any children to unpublishing all children.

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Hmm, I actually don't think it is supposed to work this way, for performance reasons we specifically do not do this and unpublishing a parent should just move all descendants to the recycle bin based on if any ancestors have -20 in the path.. 

Additionally I've tried to reproduce the original problem and I can't. I have created a node with children and descendants, throw it in the recycle bin and am then perfectly able to delete it from the bin. I also tried with the starter kit but also no problem..



I'll close this one and the related issue. Of course if you have other steps to repro or can find the root cause of your problem we're happy to have another look!

**Comment by bielu** [comment]
@nul800sebastiaan you actually missed one step! 
I describe that issue occurs when you unpublish node with children first.

**Comment by nul800sebastiaan** [comment]
@bielu Ah yes, okay, now I can reproduce! Unfortunately this is not how it should be fixed, unfortunately I also don't have guidance on how it really should be fixed 🙈

**Comment by bielu** [comment]
@nul800sebastiaan the issue here is we need go through all children (perf issue) or change how removing things works(breaking change) I was looking into that over last week and it is the best what I found we can do without breaking staff around but maybe @Shazwazza will have better idea.

**Comment by nul800sebastiaan** [comment]
Something must have changed along the way, I just tried in 7.12 and there I can perfectly delete it.. strange!

**Comment by bielu** [comment]
I think it is related to changes of cache in 7.14/7.15(not sure now)

**Comment by c9mbundy** [comment]
Perhaps related to #8244 ? I closed this issue as reproducing was inconsistent, but I also suspected something to do with cache.

**Comment by bielu** [comment]
@c9mbundy this is same bug but in different context.

**Comment by bielu** [comment]
@nul800sebastiaan any ideas or maybe information from internal conversations?

**Pull request closed without merging**
