### PR TITLE
ru.xml UI lang file

### PR DESCRIPTION
**Pull request by abryukhov**
Added / updated keys for 7.4

### CODE REVIEW

**Comment by simonbusborg** [comment]
Merged :) #h5yr :cake:

**Comment by abryukhov** [comment]
@simonbusborg thank you again.

can you tell me if you know, are the people who contribute the language resouces use some tools for easily comparing and adding/changing missing keys for further manual translation? There were cases when the translation task itself takes a couple of minutes rather than task of new/updated keys manually search :-)

**Comment by simonbusborg** [comment]
@abryukhov The process at the moment isn't optimal. I don't know if people are using any tools for it, or if they're just doing good 'ol hard word :) 

My suggestion is that you could raise a flag on [the forum](https://our.umbraco.org/) about this, there might be someone with the same issue or even a good solution :)

**Comment by abryukhov** [comment]
Ok, will raise a theme on the forum, and maybe will try to connect with my ex-collegue at the latest web-studio job, who was helping me with translation and AFAIR started to develop some kind of simple xml umbraco lang files analyser/comparer couple of years ago :-)

**Comment by clausjensen** [comment]
@abryukhov I've made this tool that runs as a grunt-plugin and goes through all the language xml files and updates them with missing keys based on what is in the selected "base language file" (en_us.xml).

If you want to test it feel free to pull this branch: https://github.com/umbraco/Umbraco-CMS/pull/1074 and use the `grunt localize` task in the `\src\Umbraco.Web.UI.Client` folder.

The plugin/task is set up in that branch to "just work": you just pull the branch, run `npm install` to install the modules and then `grunt localize` and you should see the files get updated with any missing keys. Missing keys that are inserted in the various language files are also marked with a `missingTranslation="true"` attribute so you can easily search through the `ru.xml` file for those entries. When you have translated something, make sure to remove this attribute from the element also.

When you submit the translated files - please only submit updated files where you actually did translation :smile: we'll let someone else handle updating the other files with missing keys for their languages.

It's still in testing phase so it would be great if you would please report any unusual stuff it might do with the files or if something is broken!

In case you're interested in the tool itself the source is on github: https://github.com/clausjensen/grunt-umblocalize

**Pull request merged**
