### PR TITLE
Improve performance and reduce memory use and reduce array allocations by reusing char[]

### PR DESCRIPTION
**Pull request by nzdev**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes N/A

### Description

What?
Introduced Umbraco.Core.Constants.CharArrays.

Replaced instantiations of common char[] by reusing readonly char[]. Also replaced implicit new char[]'s when params char[] methods are called.

Why?
Reduce allocations, reduce memory use, improve performance.

How to test?
Existing tests pass.

### CODE REVIEW

**Review by nathanwoulfe — APPROVED** [review]
Hi @nzdev, I've eyeballed all the file changes, everything looks fine. I see no reason not to make these changes, but pinging @Shazwazza in case he has any input before I merge.

**Review by Shazwazza — APPROVED** [review]
Yeah looks good! @nathanwoulfe feel free to merge/tag for next release :)

**Comment by Shazwazza** [comment]
@nathanwoulfe you still ok to merge this one or waiting on something?

**Comment by nathanwoulfe** [comment]
@Shazwazza absolutely. I think it got lots in my piles of notifications.

**Pull request merged**
