### PR TITLE
V8: Use umb-checkbox for RTE configuration

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

This PR replaces the existing system checkboxes with `umb-checkbox` on the RTE configuration:

rte-checkboxes

Whoo, pretty 🎉 

**Note:** This PR conflicts with the logic implemented in #5068 to support stylesheets in nested folders. Both PRs are authored by me though, so once either one is merged I'll update the other.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @kjac 

Thanks for this contribution - as always, you'll hear from us if we need you,

Em

**Comment by nul800sebastiaan** [comment]
@kjac Looks great! I've merged in the latest v8 to resolve the merge conflicts.

One little problem: it seems I can not (de)select any stylesheets, saving with a checked on stylesheet just returns an non-checked list on refresh. Maybe it has something to do with the recent changes to enable folders for stylesheets?

**Comment by kjac** [comment]
There's bound to be conflicts there. Serves me right for doing so many PR's 😆

I'll have a look at it 👍

**Comment by kjac** [comment]
@nul800sebastiaan it's fixed now 👍

**Comment by nul800sebastiaan** [comment]
YAS! Awesome, works great now, lovely update, cheers!

**Pull request merged**
