### PR TITLE
U4-9254 - Added defaultSection to webroutingsection - used by routes.js

### PR DESCRIPTION
**Pull request by CasperTDK**
The default section to show should not be hardcoded!

We've made a custom dashboard for our editors and they do not like to click the section button each time the log in. They want it to be the standard/default view instead of content.

Let me know if the setting should be somewhere else :)

### CODE REVIEW

**Comment by Shazwazza** [comment]
Thanks for the PR, some quick notes:

* The webroutingsection should not be used for configuration like this, this section is for internal routing of how Umbraco works and is tied with IIS, not for back office angular routing
* The ideal way to do this is to add another column in the user table to denote the user's default section so it can be assigned per user, this could be done against the 7.6 branch
* Alternatively (or in the meantime), you could add a JS event (or similar) to when this "content" section is going to be used so that you could override this with your own code and have your own configuration used

**Comment by CasperTDK** [comment]
Hi Shannon

Thanks for the feedback!
So I am hearing that you would still prefer that the "default section route" is static on application level - with an option to set a different option for a specific user, correct?

I'd prefer having both options, but I can manage with a "user level" override 👍 

Can you confirm?

**Comment by CasperTDK** [comment]
@Shazwazza  Ping

**Comment by Shazwazza** [comment]
Yes ideally you could set this per user which would need to be an additional db column, you could also have a global option as you suggest. Currently there's not really an ideal place to store this in config in the umbracoSettings.config file where it should go (so we don't keep polluting more appSettings) but I would say considering the different types of settings that exist underneath the `<content>` node, you could put it there, like `defaultEditingSection`

**Comment by nul800sebastiaan** [comment]
Hey there @CasperTDK !

I'm writing today after anouncing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.
Hey @madsoulswe and thanks for the PR. Many apologies about the very late reply! 🙈

I feel like this issue has been fixed since you've submitted this PR already so I'll close it for now. If you can still reproduce the problem on the latest version of v7 then feel free to re-open this one! 👍 

Once again, apologies for the delay.

**Pull request closed without merging**
