### PR TITLE
Fixes: U4-8298 CacheRefresher authorization logic reversed - traditio…

### PR DESCRIPTION
**Pull request by Shazwazza**
…nal load balancing will not work

### CODE REVIEW

**Comment by houssamedelby** [comment]
Hey Shannon,

I'm using Umbraco 7.4.1 and I am facing this problem. I wonder if there is a way to work this around in order to avoid upgrading to 7.4.3?

**Comment by nul800sebastiaan** [comment]
@houssamedelby Well, you could drop the dlls from 7.4.3 in the site in which you have this problem and then you're already 90% done with the upgrade. 

The upgrade from 7.4.1 to 7.4.3 is easier than any workaround I can think of. :)

**Comment by houssamedelby** [comment]
Thanks Sebastiaan for the quick response. I agree with you, the thing is, to be honest, i didn't have the best experience with upgrading with earlier versions. I've been using Umbraco for a while now, from the early 4.7.x untill now. Each time i did an upgrade, i got a certain bug fixed but on the other hand i got other issues stopped working. 
But I'll try your advice this time and hope nothing goes crazy :)

**Comment by nul800sebastiaan** [comment]
We've been working really hard at making the upgrade process much smoother, have a look at this blog post too (but I don't think you'll need it this time!) 

https://cultiv.nl/blog/how-to-diagnose-umbraco-upgrade-problems/

**Comment by houssamedelby** [comment]
Sorry to bother you again, but i've just taken a look on U7.4.3 and it seems to have more bugs then U7.4.1. My question is, is there by any chance a way for me getting the bug fix for just this issue  "CacheRefresher", without getting the whole upgrade thing?

Thanks in advance,
Houssam

**Comment by nul800sebastiaan** [comment]
@houssamedelby Huh? Between 7.4.1 and 7.4.3 we have fixed 71 bugs: https://our.umbraco.org/contribute/releases/compare

I'm not sure how you came to the conclusion we introduced more bugs?

Anyway, if you really want only this problem fixed then you can do a clone of the Umbraco repository, check out the `release-7.4.1` tag and apply the changes as made in this commit. Once you build all that you have v7.4.1 with only this problem fixed. 
Of course, in the process you will have also immensely complicated future upgrades and it seems like you wanted to avoid that, so I wouldn't recommend you do this. :)

**Comment by houssamedelby** [comment]
well,
I've got it from this link:
http://issues.umbraco.org/issues
If you choose the affected versions filter, you will get 214 bugs for U7.4.1 and 276 bugs U7.4.3!
Not really sure if that's actually the case, but these numbers are definitly not mine :).

Anyhow, I am very thankfull for your valuable tips. I'll try to stick to your suggestions as possible.

Regards,
Houssam

**Pull request merged**
