### PR TITLE
U4-8963 Updates for ImageProcessor parameters to support background c…

### PR DESCRIPTION
**Pull request by clausjensen**
…olor and new crop modes

updated existing test to test all cropmodes.

### CODE REVIEW

**Comment by Jeavon** [comment]
@clausjensen looks good, adding additional parameters to the existing methods might be a breaking change though, someone did try recently to do something similar but got stuck, see http://issues.umbraco.org/issue/U4-8751

**Comment by clausjensen** [comment]
@Jeavon yep .. we just found out the same thing.. we can't really do it as an overload due to the many optional parameters and ambigious signatures ... so it's going to have to be a breaking change at some point. I had originally created one PR for both this and the new crop modes, but ended up splitting it so at least the crop modes could get added and then this will have to wait a bit.

**Comment by clausjensen** [comment]
Just adding a link to the issue tracker here for ref. http://issues.umbraco.org/issue/U4-8963

**Comment by warrenbuckley** [comment]
Note: Updated the PR branch from `dev-v7` to the newer `dev-7.6` branch which this is intended for

**Pull request merged**
