### PR TITLE
V7: Fixes #6132,  dates being blanked out on save/publish when user locale (momen…

### LINKED ISSUE #6132: The date picker is empty after save/publish for users with locales not matching the angular locale files
The date picker is empty after save/publish for users with locales not matching the angular locale files. (Probably affects more than the date picker)

Reproduction
------------

(done with Umbraco 7.13.1)

- Create a data type using the property editor Umbraco.DateTime.
- Keep the default format DD.MM.YYYY HH:mm (dunno if it affects anything)
- Keep offset on (dunno if it affects anything)
- Use the data type for a property

- Create a user with Norwegian locale
- Log into the backoffice
- Create doc. with the date picker
- Select a date
- Save & Publish

The date should now be blank, although stored. (save / publish now clears the date)
The date is back if the backoffice and/or content is reloaded.

### Bug summary

The Norwegian user locale is nb-NO. The angular-locale_nb-NO.js file is attempted loaded, but does not exist, since only angular-locale_no.js is bundled with angular 1.1.5.
This leads to the behavior described above.

### Expected result

Correct locale file loaded and dates shown after save/publish.

### Actual result

No locale file loaded and date blank after save/publish.

---

### Workaround

I work around it for now by copying the file on build:

    <Target Name="EnsureNorwegianLocaleFile" AfterTargets="CopyUmbracoFilesToWebRoot">
        <Copy SourceFiles=".\umbraco\lib\angular\1.1.5\i18n\angular-locale_no.js" DestinationFiles=".\umbraco\lib\angular\1.1.5\i18n\angular-locale_nb-NO.js" Condition="!Exists('.\umbraco\lib\i18n\angular-locale_nb-NO.js')"/>
    </Target>

### Suggested fix

Copy the file manually in Umbraco.Web.UI.Client since angular 1.1.5 won't be upgraded nor probably ever contain the file angular-locale_nb-NO.js. :)

### PR DESCRIPTION
**Pull request by lars-erik**
This should fix #6132 
Not much to say to expand on that. :)

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Knowing nothing about moment, could you spend a few words on why this fixed the issue with a period in your datetime please? Does it just convert your localized Norwegian date/time to the hardcoded format?

And...... if you're hardcoding the format here, does it overrule the format you have set in the datype configuration, therefore.. is this the correct solution or should we use the format set in the datatype? (why/why not?)

**Comment by lars-erik** [comment]
As far as I've understood the date is _always_ stored as `YYYY-MM-DD HH:mm:ss.fff` in the database.  
In the current (7.15.1) datepicker controller, when content is loaded, the date is parsed with moment and a hardcoded format to match the above:

`datepicker.controller.js (167):`

    var dateVal = $scope.model.value ? moment($scope.model.value, 'YYYY-MM-DD HH:mm:ss') : moment();

When the date is returned from the server it actually varies from the one in `$scope.model.value` because the latter has colons in it. (Probably due to moments locale settings)

The current then does `moment(newVal)` without a format on the date that comes from the server. As opposed to how it is parsed on load.

`datepicker.controller.js (47):`

    var newDate = moment(newVal);

This change merely makes the "on changed due to colon/dot transform when save/publish" do the same as on loaded, which apparently works fine.

I've tested this both with default format on the datatype and a "Norwegian" format on the datatype. (Blank vs. DD.MM.YYYY HH:mm)

**Comment by stevemegson** [comment]
Although this works, I'm not sure that it really should. We're forcing moment to parse the date as `YYYY-MM-DD HH:mm:ss` even though we know it's really `YYYY-MM-DD HH.mm.ss`, and moment happens to handle that better than when we give it the same value with no format specified.

The real issue seems to be how we're formatting the date rather than how we're parsing it - the server should always be sending `HH:mm:ss` and not `HH.mm.ss`.

The code looks straightforward:

```c#
public static string ToIsoString(this DateTime dt)
{
    return dt.ToString("yyyy-MM-dd HH:mm:ss");
}
```

but in the format string, `:` means "the time separator in the current culture". When the current user's locale specifies `.` as the time separator, we generate incorrect "ISO" dates.

**Comment by lars-erik** [comment]
Right, so rather change that line to `"yyyy-MM-dd HH\:mm\:ss"`, then?

**Comment by stevemegson** [comment]
I guess we should pass `CultureInfo.InvariantCulture` into `ToString`, just in case any other locales have other surprises in store for us. There's bound to somewhere that formats years as roman numerals or something.

**Comment by lars-erik** [comment]
Maybe, _but_ wouldn't this possibly break a lot of other things vs. nothing breaking from the change in the property editor controller?

**Comment by stevemegson** [comment]
This seems to be the only place that actually calls `ToIsoString()`, so there shouldn't be any side effects.

**Comment by lars-erik** [comment]
I'm thinking peeps might have used the value in views etc.  
But if so, we're probably helping "fix" or unobtrusively obsolete existing workarounds instead of breaking stuff.  
I'm making a debug build to test now.

**Comment by lars-erik** [comment]
Looks good. :)

**Comment by lars-erik** [comment]
As of now the fix is running in production for a customer until 7.15.3 ;)

**Comment by nul800sebastiaan** [comment]
This last change certainly seems to make the most sense. 

>so there shouldn't be any side effects.

Famous last words 🙈 

Thanks for the help @lars-erik and @stevemegson - great detective work!

**Comment by lars-erik** [comment]
\o/ 

#h5yr for great nudging in the right direction, @stevemegson!

**Comment by crick3t** [comment]
Currently we have the same issue in Umbraco version 8.2.1, as the one on #6102 the second animation.
We have set the date picker to show the date in UK format (**DD/MM/YYYY**). After selecting the date if the focus is on the text box, the date is cleared out when it loses the focus. 
As a work around, we have set it to the default format YYYY-MM-DD and with that one it is working.
_(I am only commenting here because the other tasks are referencing this as a fix.)_

**Pull request merged**
