### PR TITLE
Regenerating API docs

### PR DESCRIPTION
**Pull request by elit0451**
WIP -> 1/2 of API docs for v8 are able to be automatically generated(c# docs)

### CODE REVIEW

**Comment by zpqrtbnk** [comment]
Quick comment about these changes: a large part of what is done at the beginning of the script (getting NuGet, Visual Studio etc) is already done in the generic build script. And it would be easy-ish to get DocFx to install as part of that script. Better not repeat ourselves.

**Comment by zpqrtbnk** [comment]
Trying to elaborate: I have posted a commit to the [Umbraco.Build](https://github.com/umbraco/Umbraco-Build) project (but haven't uploaded a new version to NuGet yet) that enables the main build script to get DocFx.

With this changes in place, and the following change in `build/build.ps1` around lines 30-40:
~~~~
   $ubuild.Boot($PSScriptRoot,
-    @{ Local = $local; },
+    @{ Local = $local; WithDocFx = $true },
     @{ Continue = $continue })
~~~~

The build script will get docfx. Meaning... if, in PowerShell, you do
~~~~
PS> $b=build/build.ps1 -get
~~~~ 
Everything (NuGet etc) is managed and you get a "build object" that gives you access to DocFx:
~~~~
&$b.BuildEnv.DocFx metadata $docFxJson
~~~~

Also, the "build object" provides you with MSBuild in `$b.BuildEnv.VisualStudio.MsBuild` so you don't have to worry about finding where it is, etc.

With this in place, your script can be greatly simplified.

Ideally, even the re-building of Umbraco can be performed by the build script. It already does, but in `Release` mode - I am not sure why we need to build a `Debug` build to get documentations?

And then, the script should probably should respect the build "conventions" used for Umbraco:
* anything "temp" goes to the `$b.BuildTemp` directory (`build.tmp`) - that would be what currently goes into `_site`
* anything "final" goes to the `$b.BuildOutput` directory (`build.out`) - that would be the ZIP files you produce

And ultimately, building the doc would become a command in the main build script.

Hope this kinda makes sense and helps, ping me with questions!

**Comment by elit0451** [comment]
Thanks for the input! Will apply the new changes 👍

**Comment by Shazwazza** [comment]
Hi @elit0451 I've tried the steps to build but unfortunately I'm getting errors.

* I've updated to the v8/spike/api-docs branch
* I've updated the build.psi file to have this line `{ Local = $local; WithDocFx = $true }` ... though I'm unsure how this works, I would also think that we should be able to pass a parameter in to the script and not have to change the script to test?
* Then i've run `$uenv=build/build.ps1 -get` which seems to work
* Then i run `$uenv.PrepareCSharpDocs()`

And i get a lot of errors and warnings in the docfx output, some about invalid globbing patterns and files not found:

```
PS C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0> $uenv.PrepareCSharpDocs()
Prepare C# Documentation
Restore NuGet
Logging to C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\build.tmp\nuget.restore.log
[19-05-06 03:28:43.622]Warning:[ExtractMetadata]NOTE that `../` is currently not supported in glob pattern, please use `../` in `src` option instead.
[19-05-06 03:28:45.136]Info:[ExtractMetadata]Loading projects...
[19-05-06 03:28:47.487]Warning:[ExtractMetadata](C:/Users/Shannon/Documents/_Projects/Umbraco/Umbraco_8.0/src/Umbraco.Core/Umbraco.Core.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file 'C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\Umbraco.Core\Umbraco.Core.csproj' with message: The imported project "C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\build\temp\docfx.console.2.42.0\tools\Microsoft.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\Umbraco.Core\Umbraco.Core.csproj
[19-05-06 03:28:47.627]Warning:[ExtractMetadata](C:/Users/Shannon/Documents/_Projects/Umbraco/Umbraco_8.0/src/Umbraco.Web/Umbraco.Web.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file 'C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\Umbraco.Web\Umbraco.Web.csproj' with message: The imported project "C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\build\temp\docfx.console.2.42.0\tools\Microsoft.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\Umbraco.Web\Umbraco.Web.csproj
[19-05-06 03:28:47.632]Warning:[ExtractMetadata]Project 'C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\Umbraco.Core\Umbraco.Core.csproj' does not contain any documents.
[19-05-06 03:28:47.636]Warning:[ExtractMetadata]Project 'C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\Umbraco.Web\Umbraco.Web.csproj' does not contain any documents.
[19-05-06 03:28:47.647]Info:[ExtractMetadata]Generating metadata for each project...
[19-05-06 03:28:48.300]Warning:[ExtractMetadata]No metadata is generated for Umbraco.Core,Umbraco.Web.
[19-05-06 03:28:48.309]Info:Completed in 4841.8083 milliseconds


Build succeeded with warning.
[19-05-06 03:28:48.316]Warning:[ExtractMetadata]NOTE that `../` is currently not supported in glob pattern, please use `../` in `src` option instead.
[19-05-06 03:28:48.316]Warning:[ExtractMetadata](C:/Users/Shannon/Documents/_Projects/Umbraco/Umbraco_8.0/src/Umbraco.Core/Umbraco.Core.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file 'C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\Umbraco.Core\Umbraco.Core.csproj' with message: The imported project "C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\build\temp\docfx.console.2.42.0\tools\Microsoft.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\Umbraco.Core\Umbraco.Core.csproj
[19-05-06 03:28:48.316]Warning:[ExtractMetadata](C:/Users/Shannon/Documents/_Projects/Umbraco/Umbraco_8.0/src/Umbraco.Web/Umbraco.Web.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file 'C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\Umbraco.Web\Umbraco.Web.csproj' with message: The imported project "C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\build\temp\docfx.console.2.42.0\tools\Microsoft.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\Umbraco.Web\Umbraco.Web.csproj
[19-05-06 03:28:48.317]Warning:[ExtractMetadata]Project 'C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\Umbraco.Core\Umbraco.Core.csproj' does not contain any documents.
[19-05-06 03:28:48.317]Warning:[ExtractMetadata]Project 'C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\Umbraco.Web\Umbraco.Web.csproj' does not contain any documents.
[19-05-06 03:28:48.317]Warning:[ExtractMetadata]No metadata is generated for Umbraco.Core,Umbraco.Web.
        6 Warning(s)
        0 Error(s)
[19-05-06 03:28:49.557]Info:6 plug-in(s) loaded.
[19-05-06 03:28:49.571]Info:Post processor ExtractSearchIndex loaded.
[19-05-06 03:28:49.619]Info:No files are found with glob pattern api/**.yml,api/index.md, excluding <none>, under directory "C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\ApiDocs"
[19-05-06 03:28:49.621]Warning:NOTE that `../` is currently not supported in glob pattern, please use `../` in `src` option instead.
[19-05-06 03:28:49.622]Warning:NOTE that `../` is currently not supported in glob pattern, please use `../` in `src` option instead.
[19-05-06 03:28:49.623]Info:No files are found with glob pattern images/**, excluding obj/**,../../build.tmp/_site/**, under directory "C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\ApiDocs"
[19-05-06 03:28:49.623]Warning:NOTE that `../` is currently not supported in glob pattern, please use `../` in `src` option instead.
[19-05-06 03:28:49.737]Info:Markdown engine is dfm
[19-05-06 03:28:49.754]Warning:Ignored duplicate file C:/Users/Shannon/Documents/_Projects/Umbraco/Umbraco_8.0/src/ApiDocs\index.md.
[19-05-06 03:28:50.247]Info:Cannot load build info: 'build.info' not found under 'C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\src\ApiDocs\obj\.cache\build'
[19-05-06 03:28:50.277]Info:[BuildCore.Build Document]Max parallelism is 8.
[19-05-06 03:28:50.278]Warning:[BuildCore.Build Document]Ignored duplicate file C:/Users/Shannon/Documents/_Projects/Umbraco/Umbraco_8.0/src/ApiDocs\index.md.
[19-05-06 03:28:50.987]Info:[BuildCore.Build Document.CompilePhaseHandlerWithIncremental.ConceptualDocumentProcessor]Building 1 file(s) in ConceptualDocumentProcessor(BuildConceptualDocument=>CountWord=>ValidateConceptualDocumentMetadata)...
[19-05-06 03:28:50.987]Info:[BuildCore.Build Document.CompilePhaseHandlerWithIncremental.TocDocumentProcessor]Building 1 file(s) in TocDocumentProcessor(BuildTocDocument)...
[19-05-06 03:28:51.700]Warning:[BuildCore.Build Document.LinkPhaseHandlerWithIncremental.ConceptualDocumentProcessor.Save](index.md#L6)Invalid file link:(~/api/Umbraco.Core.html).
[19-05-06 03:28:51.703]Warning:[BuildCore.Build Document.LinkPhaseHandlerWithIncremental.ConceptualDocumentProcessor.Save](index.md#L7)Invalid file link:(~/api/Umbraco.Web.html).
[19-05-06 03:28:51.809]Info:[BuildCore.Build Document.LinkPhaseHandlerWithIncremental.Apply Templates]Applying templates to 2 model(s)...
[19-05-06 03:28:52.244]Info:[BuildCore.Build Document]XRef map exported.
[19-05-06 03:28:52.428]Info:[Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing ExtractSearchIndex]Extracting index data from 1 html files
[19-05-06 03:28:52.481]Info:[Postprocess]Manifest file saved to manifest.json.
[19-05-06 03:28:52.597]Info:Completed building documents in 3025.6929 milliseconds.
[19-05-06 03:28:52.599]Info:Completed in 3708.1935 milliseconds


Build succeeded with warning.
[19-05-06 03:28:52.606]Warning:NOTE that `../` is currently not supported in glob pattern, please use `../` in `src` option instead.
[19-05-06 03:28:52.606]Warning:NOTE that `../` is currently not supported in glob pattern, please use `../` in `src` option instead.
[19-05-06 03:28:52.607]Warning:NOTE that `../` is currently not supported in glob pattern, please use `../` in `src` option instead.
[19-05-06 03:28:52.607]Warning:Ignored duplicate file C:/Users/Shannon/Documents/_Projects/Umbraco/Umbraco_8.0/src/ApiDocs\index.md.
[19-05-06 03:28:52.607]Warning:[BuildCore.Build Document]Ignored duplicate file C:/Users/Shannon/Documents/_Projects/Umbraco/Umbraco_8.0/src/ApiDocs\index.md.
[19-05-06 03:28:52.608]Warning:[BuildCore.Build Document.LinkPhaseHandlerWithIncremental.ConceptualDocumentProcessor.Save](index.md#L6)Invalid file link:(~/api/Umbraco.Core.html).
[19-05-06 03:28:52.608]Warning:[BuildCore.Build Document.LinkPhaseHandlerWithIncremental.ConceptualDocumentProcessor.Save](index.md#L7)Invalid file link:(~/api/Umbraco.Web.html).
        7 Warning(s)
        0 Error(s)

7-Zip (a) 18.01 (x86) : Copyright (c) 1999-2018 Igor Pavlov : 2018-01-28

Scanning the drive:
22 files, 1291936 bytes (1262 KiB)

Creating archive: C:\Users\Shannon\Documents\_Projects\Umbraco\Umbraco_8.0\build.out\csharp-docs.zip

Add new data to archive: 22 files, 1291936 bytes (1262 KiB)


Files read from disk: 22
Archive size: 413024 bytes (404 KiB)
Everything is Ok
```

There is an output zip but because the metadata build failed, the api docs are empty

**Comment by Shazwazza** [comment]
(FYI - the ui docs seem to work 🎉 )

**Pull request merged**
