### PR TITLE
fix: ensured that allowed user name characters are supported in backo…

### PR DESCRIPTION
**Pull request by bielu**
### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description
Partially fix: https://github.com/umbraco/Umbraco-CMS/issues/14808

Test steps:
1. set UsernameIsEmail to false
2. set AllowedUserNameCharacters to include space
3. create user with name containing a space in login
4. try to change password / unlock / disable user
5. you will get user correctly updated

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi @bielu,

Thanks for your PR to partially fix #14808, to allow a change of password for users with a space in their name.

May I check when you say partially fix, what would be remaining in #14808? Would it be sub-bug 1 you put in the issue?

Thanks, and one of the Core Collaborators team will review this as soon as possible.

Best wishes

Emma

**Comment by bielu** [comment]
@emmagarland subbug 1 remaining after merging as it is bigger change

**Comment by Zeegaan** [comment]
Looks good, tests good 🎉

**Comment by emmagarland** [comment]
Thanks for the reply, @bielu. One of the team will get onto this as soon as possible.

Emma

**Pull request merged**
