### PR TITLE
WIP - Accessibility: Extend clickable area directive

### PR DESCRIPTION
**Pull request by BatJan**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
This PR is a work in progress - Description will be updated once the PR is ready for review.

### CODE REVIEW

**Comment by BatJan** [comment]
@nielslyngsoe As discussed in Slack I'm having an issue with Umbraco not loading properly after adding this directive - I get a blank screen and when I check the console log there is a 404 error... Not sure what I might be missing compared to the time before .net5/6 :-) Any pointers you can think of will be greatly appreciated! /cc @MMasey

**Comment by BatJan** [comment]
@MMasey @nielslyngsoe Doh! The error happened because I had by mistake Pascal Cased the directive name instead of camel casing it 🤦🏻 😅

**Comment by MMasey** [comment]
🐪 haha doh! Easily done 😄 nice work figuring it out!

**Comment by nul800sebastiaan** [comment]
Hey @BatJan I am just cleaning up at the moment, since this has been in draft for a long time, I'll close it off for now. If you're happy to still work on this we can always reopen it. Thanks!

**Pull request closed without merging**
