### PR TITLE
feat: change package template to use razor class library

### PR DESCRIPTION
**Pull request by Mantus667**
### Prerequisites

- [ ] I have added steps to test this contribution in the description below

### Description
- Use a RCL as base for the umbraco package template.
- Set v10.0.0 as default version for the package template

Usage of RCLs as base of Umbraco Packages is discussed in multiple occasions in the last month.
Most of the official Umbraco packages moved to be RCLs.
The most important part is the automatic handling of assets which was handled before with the custom build task.

In the last package team meeting we discussed to provide a PR to change the template.

### CODE REVIEW

**Comment by abjerner** [comment]
Probably a good idea, but a few things to consider:

- Not all packages have assets (but probably doesn't anyways if they are RCLs)

- If RCLs become officially recommended by Umbraco (not sure if they are now), RCL should also be supported by Umbraco. I don't have a good overview of what parts are still missing. Most areas are properly fine, but these aren't:

  - `package.manifest` files are not picked up from virtual directories - see https://dev.to/kevinjump/umbraco-10-razor-class-library-packages-pt3-40bb
  
  - SVG icon files are not picked up from virtual directories - see my PR here https://github.com/umbraco/Umbraco-CMS/pull/12833

**Comment by Mantus667** [comment]
@abjerner 

Yes indeed, there are things to consider. As you mentioned the package.manifest loading and svg loading.
We discussed this in our last package team meeting and are currently looking if we find (all) spots where changes would be required. There should be some more. Most part where the IFileProvider isn't used. @KevinJump knows some locations.

So it's an intentional draft PR.

**Comment by nul800sebastiaan** [comment]
Hey there @Mantus667 - are you still planning to work on this? I think we have an alternative now in https://github.com/LottePitcher/opinionated-package-starter (which is working towards RCLs as well). 

Maybe it's a good time to rethink this one, not sure what the packages team is up to for this one at the moment.

**Comment by nul800sebastiaan** [comment]
Just remembered Ronald might be working on something similar: #13776

**Comment by ronaldbarendse** [comment]
> Just remembered Ronald might be working on something similar: #13776

That PR adds a new `umbracopackage-rcl` template (instead of changing the existing one), so users can still use the latest `umbracopackage` template if they want to target v10 (that uses the build targets).

If you want to use RCLs with v10, the Opinionated Umbraco Package Starter Template shows how you can use `IManifestFilter` to accomplish this in PR https://github.com/LottePitcher/opinionated-package-starter/pull/8, but I recommend sticking to the officially supported methods in the CMS 😄

**Pull request closed without merging**
