### PR TITLE
Clear the add user form when state is inviteUser so that it is not pr…

### PR DESCRIPTION
**Pull request by ThomasAdams2**
…e-filled with details from previously invited user

https://github.com/umbraco/Umbraco-CMS/issues/3631

####Description for testing
To test we will now see that after inviting a user, and clicking the invite another user button, the invite user form is not pre-filed with the details of the user that was just invited.
The user form can then be filled in as usual and this user can then be invited.
this process can be repeated, and all users are invited by email with the correct details, which are also shown in the user section.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @ThomasAdams2 

Thanks for the PR! One of us will take a look over the work you've done and we'll let you know if you need to do anything. If not, we'll go ahead and merge.

Thanks,

Emma, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-pr-team/)

**Comment by stevetemple** [comment]
Is it helpful to keep the groups and message but not, obviously, the name and email? Or is it better just to clear those, I'm thinking if you're inviting a bunch of people you're probably keeping the groups the same 90% of the time.

**Comment by ThomasAdams2** [comment]
I decided to clear all the fields as that was the cleanest and simplest solution, which to me is the expected behaviour as it is now consistent with opening a new invite user form from the users page.

**Comment by emmaburstow** [comment]
Hey @nul800sebastiaan - can we get someone to have a look at this? Some interesting discussion over expected behaviours. An Hq perspective would be useful :)

**Comment by ThomasAdams2** [comment]
@stevetemple  @nul800sebastiaan I've added a new method which only clear the name and email fields, the group selection is now kept between user invites but keeping the message requires a larger change to the code as that is not stored in the user so I have left this as it currently is for now.

**Comment by nul800sebastiaan** [comment]
Frustratingly, the `message` property actually gets cleared out along the way.. and I can't figure out why, at all, even after adding many `console.log` messages! 😅

@ThomasAdams2 if you're smarter than me, could you try and see why this is the case?

**Comment by nul800sebastiaan** [comment]
Hey there @ThomasAdams2 !

I'm writing today after announcing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Pull request closed without merging**
