### PR TITLE
Update the umbraco ascii art

### PR DESCRIPTION
**Pull request by prjseal**
I thought it would be a good idea to update the ascii art to a font similar to the one in the umbraco logo on the umbraco.com website.

### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
It's just a simple update of the ascii art in the readme.txt which shows after installing umbraco via nuget

### CODE REVIEW

**Comment by emmaburstow** [comment]
I am LOVING this change. @nul800sebastiaan - what do hq think???

**Comment by poornimanayar** [comment]
Nice one @prjseal

**Comment by nul800sebastiaan** [comment]
It's wonderful, thanks very much @prjseal !

**Comment by ronaldbarendse** [comment]
Nice detail with using all those `8`s 😉

**Pull request merged**
