### PR TITLE
V8: Angular Divorce: isString

### PR DESCRIPTION
**Pull request by MMasey**
This PR replaces the use of `angular.isString` in favour of `Utilities.isString` as part of #7718.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey Mike! 

Thanks for the PR! Speak soon 👍 

Em

**Comment by nul800sebastiaan** [comment]
Thanks very much @MMasey! 🍻

**Comment by nathanwoulfe** [comment]
@MMasey you're a champion.

**Comment by nielslyngsoe** [comment]
@MMasey Great!

**Pull request merged**
