### PR TITLE
Non-administrator users logged out when creating user groups (issue #3018)

### PR DESCRIPTION
**Pull request by jannikanker**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, this fixes: https://github.com/umbraco/Umbraco-CMS/issues/3018
- [x] I have added steps to test this contribution in the description below

### Description

As the linked issue correctly states, any non-admin user will get a 401 Unauthorized response when trying to create a user group, even when they have access to the Users section and thus a "Create Group" button.

This happens because the current authorization logic requires any non-admin user to have access to whatever user group they're trying to save. Which is pretty hard when the group hasn't been created yet...

Exact steps to reproduce are in the issue as well.

These initial commits make it possible for non-admins to create groups, as I believe they should be able to (and I need it to work for a not-so-far-in-the-future project).

I am, however, fairly certain that my "implementation" is less than ideal... But I can't really see how else to make it work without flipping large parts of the authorization logic on its head, so _I'd love some help here_ :-)

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Looks like you're mixing up 2 PR @jannikanker - always make sure to create a new branch from `dev-v7` before you start working on a new PR.

You're working on the `dev-v7` branch right now, which means that you'll never be able to get the changes from the origin repository ever again (the umbraco owned git repository).

Normally what you would do is: 

- Fork Umbraco-CMS
- Clone Umbraco-CMS
- Immediately create a branch
- Work on that until you're ready to submit a PR
- Switch back to `dev-v7`
- Get the latest changes from the origin umbraco repo (https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/.github/CONTRIBUTING_DETAILED.md#keeping-your-umbraco-fork-in-sync-with-the-main-repository)
- Make a new branch from the latest changes in `dev-v7` 
- Make new code
- Submit PR
- Switch back to `dev-v7` 
- Get latest changes
- .. and so on!

Since you've made commits now on top of `dev-v7` you won't be able to get the changes from the origin any more. 

I would recommend you make a fresh clone of your fork of the Umbraco repository. I can fix this PR and merge it (after I review it) but you will need to start over with a  new copy for future contributions.

**Comment by nul800sebastiaan** [comment]
@jannikanker I'll fix this one up, no problem! 

So for the next one just make sure to make a fresh clone and create a branch when you start working, from then on it should be smooth sailing! 👍

**Comment by poornimanayar** [comment]
Hi @jannikanker ,

Is this ready to be tested?

Poornima

**Comment by jannikanker** [comment]
Hi @poornimanayar :-) I'm not sure if testing should start before Sebastiaan has fixed the PR-mess I made? Also, I was kind of asking for a little help on the PR itself (I'm not sure my way of implementing this fix is "ideal"), but can it be tested? I guess :-P

**Comment by nul800sebastiaan** [comment]
It's on @Shazwazza's list to have a look over soon!

**Comment by jannikanker** [comment]
Is my proposed fix really awful enough to render @Shazwazza speechless? :-P Or am I just being too impatient? ;-)

**Comment by Shazwazza** [comment]
@jannikanker I think @nul800sebastiaan just got a bit busy :) We did have a quick chat some time ago about it. I think the solution is fine and I don't see any any security risk with the changes.

I'll happily approve but will leave it to @nul800sebastiaan to merge or I'll chat with him today.

**Comment by nul800sebastiaan** [comment]
Thanks @jannikanker I will give it another go, sorry for the delay!

**Comment by cloudweb13** [comment]
@nul800sebastiaan when does this PR will be merged? We are waiting for this issue.

**Comment by nul800sebastiaan** [comment]
Finally got around to testing this one, well done @jannikanker ! 🏅

Thanks all for your patience 🙈

**Comment by jannikanker** [comment]
Thanks - and right back at you guys! #H5YR

**Pull request merged**
