### PR TITLE
V11/bugfix/10502 listview node permissions

### PR DESCRIPTION
**Pull request by kmeilander**
### Prerequisites

- [X] I have added steps to test this contribution in the description below

### Description
When a node has a list view enabled, the list view actions do not the parent's granular node permissions do not cascade down to the children. Note that if the user clicks into the node, they do thee the action in the Actions menu.

Also if you're using a list view with the "Edit in Infinite Editor", this would mean that users cannot do these actions (since they don't get the action menu on the node details in the infinite editor)

To test:

1. In the content tree, create an item with a list view, and a create some children
2. Create a new user group setup the permissions:
a. Set the main permissions to not allow a permission (delete/publish/unpublish/move/copy).
b. In granular permissions. choose the list node made in step 1, and allow the given permission for that node (eg delete/publish/unpublish/move/Copy).
3. Login as a user with this permission and go to the list view page.
4. Click on individual items on the list view and  validate that they can do the action in the list view.  Note that he actions should also be present when in the details view if you don't select "Edit in Infinite Editor" in the list view configuration.

There also was an issue with the permission check for unpublish. It was using "U" instead of "Z". It looks like there was an old comment in there related to how the unpublish logic used to work (based on the publish permission), but it looks like this should be updated so i did that too.

image

### CODE REVIEW

**Comment by kmeilander** [comment]
My PR for v10 had some conflicts (https://github.com/umbraco/Umbraco-CMS/pull/13263), and looked like we've moved on to v11, so i re-did my PR for v11.  

I also want to call out that I got some of this code from an abandoned Pull Request of https://github.com/umbraco/Umbraco-CMS/pull/8943

**Comment by kmeilander** [comment]
Actually in re-reading the issues, i think this fixes https://github.com/umbraco/Umbraco-CMS/issues/11085 but may not fix https://github.com/umbraco/Umbraco-CMS/issues/10502 (I'm having trouble understanding how to reproduce this one)

**Comment by georgebid** [comment]
Hey @kmeilander! Thank you for the PR, I have been looking into this and just want to check on why you think this fixes #11085 but not #10502 if 11085 was closed due to it being a duplicate of 10502? If you don't think it is a duplicate do you believe #11085  can be re-opened? I will spend more time looking into this but just wanted to put that question out to you 😄

**Comment by kmeilander** [comment]
@georgebid,  it's been a while, and looking at this again, I'm not sure that is true either. 

But if I remember right, I think that my fix only partially addressed the issue with granular permissions on list view.  The actions to select items should be working now (so like copy, delete, etc), but i don't think i fixed the list view browse permission issue, so if you have granular browse permission, it still may not work.   The title of #11085  is a little more broad so i may of thought that didn't include the browse action, but re-reading it now it looks like it does.

I also remember from looking at the permission code that there was a lot of clean up/refactoring that should of been done to fully address the issue, but instead just focused on the list view actions part, specifically the delete action, since that was the part that I wanted to fix.

**Comment by georgebid** [comment]
@kmeilander Thanks for the quick response! I will take a look at this today. For now, I have removed the link to #10502 and will update that one where necessary.

**Comment by georgebid** [comment]
Hey @kmeilander! It's been a while since my last response - so I just wanted to check in to see if you have any thoughts/feedback on the above? Thanks 😄

**Comment by nul800sebastiaan** [comment]
Hey there @kmeilander! It's been a while since we've heard from you. We'd love to keep going on this one but it seems like it doesn't fit in for you at the moment. In order to keep things tidy, we'll close this one for now. Please let us know when you can get back to it, we can either resurrect this PR or go for an attempt number 2! Thanks again for all your work on this and we hope to hear from you soon! 🙌

**Pull request closed without merging**
