### PR TITLE
Fixed broken link in detailed contrib doc

### PR DESCRIPTION
**Pull request by pritesh-tailor**
The link to the the issues was broken (Your first code code contribution section). I've updated to the readonly issue tracker and added a reference to new issue tracker.

Removed a line on upvotes, as i don't believe that's relevant anymore.

### Prerequisites

- [ ] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is:
- [ ] I have added steps to test this contribution in the description below

### CODE REVIEW

**Comment by dawoe** [comment]
Hi @pritesh-tailor 

Congrats on your first contribution to Umbraco. Although a very small and easy one, it is a very important one.

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by nul800sebastiaan** [comment]
Lovely, thanks very much @pritesh-tailor and congrats with your first contribution! 

Enjoy that shiny contributor badge on your Our Umbraco profile as well! 👍 https://our.umbraco.com/member/274336

**Comment by pritesh-tailor** [comment]
Thanks Sebastiaan! Glad to have finally made my first but most certainly not my last contribution.

**Comment by nul800sebastiaan** [comment]
Bring it on! 🎉

**Comment by nul800sebastiaan** [comment]
Hi there @pritesh-tailor,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing :pray:

If you haven't heard already we have had a record breaking amount of PR's in both the CMS and the Documentation repository. You can read all about the numbers in the [Umbraco Hacktoberfest Aftermath blog post](https://umbraco.com/blog/the-2018-hacktoberfest-aftermath/).

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://goo.gl/forms/smjQwEMDM5cUnz6x1) :point_left: Please follow this link to fill out and submit the form, **before November 21st 2018**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before December, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Comment by nul800sebastiaan** [comment]
@pritesh-tailor Hi there Pritesh!

Can you please fill in the swag form ASAP? We are almost ready to order but missing a couple of entries, yours is among those missing :-)

https://goo.gl/forms/smjQwEMDM5cUnz6x1

Thanks!

**Comment by pritesh-tailor** [comment]
Hi Sebastiaan

Apologies for my late response, I kept forgetting to check the size of the shirt I got from Codegarden 🙄.

All done now :)

Thanks,
Pritesh

**Pull request merged**
