### PR TITLE
v8: Add package contributors

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/4036 and it also fixes https://github.com/umbraco/Umbraco-CMS/issues/4388

### Description
This PR add the option to add contributors to package as packages often have multiple contributors and instead of add multiple developers to author property.

The property re-use `Umbraco.MultipleTextstring` property editor.

image

### CODE REVIEW

**Comment by bjarnef** [comment]
The contributors are stored as child xml elements:

```
<info>
    <package>
      <name>Test Package</name>
      <version>1.0.0</version>
      <iconUrl></iconUrl>
      <license url="http://opensource.org/licenses/MIT">MIT License</license>
      <url>https://our.umbraco.com</url>
      <requirements type="Strict">
        <major>8</major>
        <minor>0</minor>
        <patch>0</patch>
      </requirements>
    </package>
    <author>
      <name>Bjarne Fyrstenborg</name>
      <website>https://our.umbraco.com</website>
    </author>
    <contributors>
      <contributor>Anders Bjerner</contributor>
      <contributor>Warren Buckley</contributor>
    </contributors>
    <readme><![CDATA[]]></readme>
</info>
```

**Comment by bjarnef** [comment]
Upload local package now looks like this:

image

**Comment by bjarnef** [comment]
To test this:

- Create a package with/without contributors and ensure the contributors are shown after refresh
- Upload the local package using the package in /media folder or download the package file and check contributers are listed in summary before install.

image

**Comment by bjarnef** [comment]
@Shazwazza what do you think of this addition? Is it okay it is a string array?

**Comment by nul800sebastiaan** [comment]
Lovely work, thank you very much! 🎉 And great with the translations as well! 🥇🥇

**Pull request merged**
