### PR TITLE
Fixed open doc type button

### PR DESCRIPTION
**Pull request by hemraker**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
🎉

**Comment by abjerner** [comment]
But is it *really* fixed? 😛 

http://issues.umbraco.org/issue/U4-10805

**Comment by hemraker** [comment]
@abjerner cheeky 😂 While it does fix the referenced issue, it does not even attempt to address U4-10805.

**Comment by abjerner** [comment]
@hemraker No worries. Just saw this pull request and figured I post the link to my issue.

As I mentioned at the meetup in February, this affect the user experience, so prioritizing my two issues would be super nice ;)

**Pull request merged**
