### PR TITLE
V9: Get all servers, including inactive

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
Don't know if this is a desired addition, but I would like to be able to see all server registrations, including the inactive ones. 😄 

Functionality: 
Expand `IServerRegistrationService.cs` and it's implementation with a `GetServers()` method to return all servers and not only active servers.

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
@erikjanwestendorp Thanks for this one! I am wondering what the use case is, why would you want to know about the inactive servers please? :-)

**Comment by erikjanwestendorp** [comment]
@nul800sebastiaan Thanks for your reply :-). Perhaps this is indeed something that is not often used, but in some scenarios it can be useful to have a complete overview of all servers.

Recently I made a dashboard where all servers are displayed and where it is possible to delete inactive ones. For this I made my own repository to retrieve servers and remove them from the database. In this scenario it would have been nicer to be able to do this via an Umbraco Service. But it's not really necessary, no :-)

**Comment by nul800sebastiaan** [comment]
I just got some feedback from a colleague that sadly, adding to a public interface is a breaking change and needs to  wait for v10. But we'd be happy if you tried again and targeted the `v10/dev` branch instead! 

FYI: I noticed that the comments on the new method were not updated, still referring to active servers. 

And for `GetActiveServers` I'd say let's change that to `return GetServers(bool refresh = false).Where(x => x.IsActive);` instead. The results are cached by default so the overhead is negligible.

I'll close this one for now and look forward to merging a v10 version of this one! 👍 Thanks again @erikjanwestendorp!

**Comment by erikjanwestendorp** [comment]
@nul800sebastiaan Thanks again, I just created a new [PR](https://github.com/umbraco/Umbraco-CMS/pull/12072) targeting the v10 branche.

**Pull request closed without merging**
