### PR TITLE
V8 - #3434 - change checkboxes on property type settings to toggle 

### PR DESCRIPTION
**Pull request by dawoe**
…n content type designer

### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is: #3434 
- [x] I have added steps to test this contribution in the description below

### Description

I already converted the Allow varying by culture to a toggle. To make it look good I reused the same markup as on the document type permissions.

But now we have classes like sub-view-columns in there. While the end result looks good, the code looks nasty

@madsrasmussen do you have any pointers on how to fix this without using the sub-view css classes before I change the remainging checkboxes like validation and settings for when we are configuring a membertype

Dave

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
@dawoe I should ask @madsrasmussen for an explanation but it seems like he thinks toggles is not always the best way to go: https://github.com/umbraco/Umbraco-CMS/issues/3421#issuecomment-433377685

Not sure if that's the case here too?

**Comment by madsrasmussen** [comment]
My rule of thumb is: Toggles are for settings and something that will "stay the same" when you return to it. Checkboxes are for selection and "confirmation". 

@bjarnef linked me to this article which has a pretty good overview of different scenarios for checkboxes, radios, and toggles: https://lexicondesign.io/docs/patterns/Forms/radio_check_toggle.html

I think it is fine to move the properties setting checkboxes to toggles 👍 

@dawoe I normally use the umb-control-group (component or css classes) when working with form elements. It gets me a long way. I also want to remove the "sub view" css classes at some point because we should be able to use the umb-control-group css classes instead. The end result should be close to identical.

**Comment by dawoe** [comment]
@madsrasmussen will see if I can make it look pretty when using umb-control-group

**Comment by dawoe** [comment]
@madsrasmussen 

I converted all the checkboxes for property settings to toggles. I also updated the designer so the it's indicated a property is varied by culture.

property setttings toggles

**Comment by hartvig** [comment]
Great work - in general - and in particular where there's no further explanation - it'll work better if the toggle floats left to the action (for instance "Field is mandatory", etc.

**Pull request merged**
