### PR TITLE
v8: Accessibility Create User Page Title

### PR DESCRIPTION
**Pull request by RachBreeze**
This PR sets the page title when creating a user, it extends #7102

### CODE REVIEW

**Comment by emmaburstow** [comment]
😄

**Comment by RachBreeze** [comment]
Hi,  I'd like to look to finish of the title work I've been doing and would be good to get feedback on this PR please, there's a few places in the CMS where as a developer we can't just set the title and screen reader properties properties containing the name are loaded after the header is loaded, and ng-hide won't resolve this issue.  This works alongside #7102 in an attempt to resolve this issue

**Comment by RachBreeze** [comment]
Hiya 
Have you managed to review this yet please?  Is there anything I can do to assist?  As mentioned above I've got a few more tbd issues which would be dependent on this PR so it would be great to get feedback.

**Comment by poornimanayar** [comment]
Hi @RachBreeze ,

Apologies for delayed response. Can you fix the merge conflict here? I can look at it for you then :-)

Poornima

**Comment by RachBreeze** [comment]
Hi @poornimanayar 
I have fixed the merge conflict thank you
Rachel

**Comment by nul800sebastiaan** [comment]
Thanks, this works like a charm :-)

image

**Pull request merged**
