### PR TITLE
V8: Hide the "Add" button for Nested Content in "single mode"

### LINKED ISSUE #7323: Nested content with max set to one shows add button
When using Nested content as a dataset (min 1, max 1) it shows the add content button in 8.4.
This button should be hidden when min is 1 and max is 1.

Screenshot Capture - 2019-12-12 - 08-27-17

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #7323

### Description

When Nested Content is configured in "single mode":

image

...the "Add" shouldn't be visible (as the one allowed item is automatically added):

image

Currently it is... but with this PR, the "Add" button disappears in "single mode".

### CODE REVIEW

**Comment by poornimanayar** [comment]
@kjac , can you fix the merge conflicts against `v8/contrib` ?

**Comment by kjac** [comment]
@poornimanayar merge conflicts resolved 👍

**Comment by kjac** [comment]
...aaand merge conflicts resolved again 😆

**Comment by kjac** [comment]
And again 😲

**Comment by poornimanayar** [comment]
Sorry for leaving it open for too long @kjac , merged in now :-)

**Pull request merged**
