### PR TITLE
Removes EmbedProviders.config & moves into C# types

### PR DESCRIPTION
**Pull request by warrenbuckley**
Removes EmbedProviders.config & moves into C# types (As its a configfile that is rarely ammended IMO)

### CODE REVIEW

**Comment by warrenbuckley** [comment]
## Example
If you wish to add your own OEmbed provider you will need to do the following

### Spotify - OEmbed
```csharp
using System.Collections.Generic;
using Umbraco.Web.Media.EmbedProviders;

namespace My.Website
{
    public class Spotify : EmbedProviderBase
    {
        public override string ApiEndpoint => "https://embed.spotify.com/oembed/";

        //Playlist
        //https://open.spotify.com/user/spotify/playlist/37i9dQZF1E4sNI4jZloSZr?si=cueBooBfTnqCGriSa4N_Kg
        //spotify:user:spotify:playlist:37i9dQZF1E4sNI4jZloSZr

        //User
        //https://open.spotify.com/user/spotify?si=JhWXrK0ORwOvn5Zjs3ISag
        //spotify:user:spotify

        //Artist
        //https://open.spotify.com/artist/0iirUbtgwt9jEkc2Grin8C?si=TLeUR2cHR-KPRJJhW6YiVg
        //spotify:artist:0iirUbtgwt9jEkc2Grin8C

        //Album
        //https://open.spotify.com/album/0lvtdqkqIln6uDBBUT7DHL?si=XTVJIEmnS_OVv9l6ktPFiw
        //spotify:album:0lvtdqkqIln6uDBBUT7DHL

        //Track
        //https://open.spotify.com/track/7aCk4XfXIEJM2MecU6Gmf2?si=vESDzI0xTNeA9FQ_dvf1eQ
        //spotify:track:7aCk4XfXIEJM2MecU6Gmf2

        public override string[] UrlSchemeRegex => new string[]
        {
            @".*.spotify.com/.*",
            @"spotify:.*"
        };

        public override Dictionary<string, string> RequestParams => new Dictionary<string, string>();

        public override string GetMarkup(string url, int maxWidth = 0, int maxHeight = 0)
        {
            var requestUrl = base.GetEmbedProviderUrl(url, maxWidth, maxHeight);
            var oembed = base.GetJsonResponse<OEmbedResponse>(requestUrl);

            return oembed.GetHtml();
        }
    }
}
```

### Composer
```csharp
using Umbraco.Core.Components;
using Umbraco.Web;

namespace My.Website
{
    public class CustomOEmbedComposer : IUserComposer
    {
        public void Compose(Composition composition)
        {
            composition.OEmbedProviders()
                .Append<Spotify>();
            
        }
    }
}
```

## Example Spotify URLs to test
**Playlist**
https://open.spotify.com/user/spotify/playlist/37i9dQZF1E4sNI4jZloSZr?si=cueBooBfTnqCGriSa4N_Kg
spotify:user:spotify:playlist:37i9dQZF1E4sNI4jZloSZr

**User**
https://open.spotify.com/user/spotify?si=JhWXrK0ORwOvn5Zjs3ISag
spotify:user:spotify

**Artist**
https://open.spotify.com/artist/0iirUbtgwt9jEkc2Grin8C?si=TLeUR2cHR-KPRJJhW6YiVg
spotify:artist:0iirUbtgwt9jEkc2Grin8C

**Album**
https://open.spotify.com/album/0lvtdqkqIln6uDBBUT7DHL?si=XTVJIEmnS_OVv9l6ktPFiw
spotify:album:0lvtdqkqIln6uDBBUT7DHL

**Track**
https://open.spotify.com/track/7aCk4XfXIEJM2MecU6Gmf2?si=vESDzI0xTNeA9FQ_dvf1eQ
spotify:track:7aCk4XfXIEJM2MecU6Gmf2

**Comment by warrenbuckley** [comment]
@jmayntzhusen some free docs/example above if this PR gets merged in ⬆️

**Comment by zpqrtbnk** [comment]
looks quite nice. question: why is `OEmbedResponse` fields `Height`, `Width`... moving from `int?` to `double?` - there's probably a reason but it feels weird?

**Comment by warrenbuckley** [comment]
@zpqrtbnk Ok the int to double one was due to one oembed provider returning a decimal number as opposed to a while number in my testing and then threw

**Pull request merged**
