### PR TITLE
U4-11149 fixed error when creating new xslt file

### PR DESCRIPTION
**Pull request by dawoe**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org/issue/U4-11149

### Description

The create task was missing in the UI.xml file. Added it back now it works

### CODE REVIEW

**Comment by dawoe** [comment]
I just noticed this also when trying to create a new member group with the latest dev-v7 branch.
 So maybe it has deeper underlying cause.

I see last commits in LegacyDialogHandler are done by @Shazwazza 

Maybe he has an idea what is the cause ?

**Comment by dawoe** [comment]
The member groups not working is related to this commit by https://github.com/umbraco/Umbraco-CMS/commit/0d2df4de811fbbd5760e0ef70adf0abcf8da326c by @RobertCopilau 

It changed the namespace of MemberGroupsTask class

@nul800sebastiaan should i fix in this PR or should i create a seperate one ?

**Comment by dawoe** [comment]
Fixed the issue with membergroups in a seperate PR : https://github.com/umbraco/Umbraco-CMS/pull/2545

**Comment by nul800sebastiaan** [comment]
This actually should be fixed in UI.Release.xml, which is the one we use when building Umbraco. I have no idea how this ever could have worked, doesn't seem like this part of the file has changed a lot in the last few years.

**Comment by dawoe** [comment]
I added it to the release.xml as well.

There have been some changes in the code that handles this. But could not track it down. Maybe it's because there are 2 node types in the xml to handle xslt files. One with alias initXslt and one with alias xslt

Dave

**Comment by nul800sebastiaan** [comment]
Cool! I'll merge it, not sure what happened but it seems like it hasn't worked for a long time.

I actually thought we were just hiding the XSLT tree if there was not files in the XSLT folder on disk :-)

**Pull request merged**
