### PR TITLE
Optimized CombinedGuidsMediaPathScheme

### PR DESCRIPTION
**Pull request by JimBobSquarePants**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
This PR provides optimization to two methods used within the `CombinedGuidsMediaPathScheme`

- Hex string generation from bytes
- Guid combination via exclusive disjunction

Both methods were either allocating to much memory or performing too many calculations per operation. 

The public `byte[].ToHexString()` extension methods have been replaced by an internal class `HexEncoder` (internal since the method is used once only internally) that utilizes static LUTs to optimize performance. A bug fix in the original untested code has also been implemented.

The private `Combine(Guid a, Guid b)` method has been relocated to an internal `GuidUtils` class and optimized to remove the double `ToByteArray()` allocation that occured for each operation.

Comprehensive unit tests have been added as well as benchmarks.

**HexEncoder**

Method | Count |         Mean |        Error |     StdDev | Ratio |
------------------- |------ |-------------:|-------------:|-----------:|------:|
ToHexStringBuilder |     8 |    786.49 ns |    319.92 ns |  17.536 ns |  1.00 |
ToHexStringEncoder |     8 |     64.19 ns |     30.21 ns |   1.656 ns |  0.08 |
|       |              |              |            |       |
ToHexStringBuilder |    16 |  1,442.43 ns |    503.00 ns |  27.571 ns |  1.00 |
ToHexStringEncoder |    16 |    133.46 ns |    177.55 ns |   9.732 ns |  0.09 |
|       |              |              |            |       |
ToHexStringBuilder |    32 |  2,869.23 ns |    924.35 ns |  50.667 ns |  1.00 |
ToHexStringEncoder |    32 |    181.03 ns |     96.64 ns |   5.297 ns |  0.06 |
|       |              |              |            |       |
ToHexStringBuilder |    64 |  5,775.33 ns |  2,825.42 ns | 154.871 ns |  1.00 |
ToHexStringEncoder |    64 |    331.16 ns |    125.63 ns |   6.886 ns |  0.06 |
|       |              |              |            |       |
ToHexStringBuilder |   128 | 11,662.35 ns |  4,908.03 ns | 269.026 ns |  1.00 |
ToHexStringEncoder |   128 |    633.78 ns |     57.56 ns |   3.155 ns |  0.05 |
|       |              |              |            |       |
ToHexStringBuilder |   256 | 22,960.11 ns | 14,111.47 ns | 773.497 ns |  1.00 |
ToHexStringEncoder |   256 |  1,224.76 ns |    547.27 ns |  29.998 ns |  0.05 | 

**Guid Combine**

Method |     Mean |     Error |    StdDev | Gen 0/1k Op | Gen 1/1k Op | Gen 2/1k Op | Allocated Memory/Op |
------------- |---------:|----------:|----------:|------------:|------------:|------------:|--------------------:|
CombineUtils | 33.34 ns |  8.086 ns | 0.4432 ns |      0.0133 |           - |           - |                28 B |
CombineLoop | 55.03 ns | 11.311 ns | 0.6200 ns |      0.0395 |           - |           - |                84 B |

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hey @JimBobSquarePants 

Thanks for making the time to put together this contribution. One of us will take a look and let you know if we have any questions or need anything from you.

Em

**Comment by zpqrtbnk** [comment]
Beautiful, and those `[FieldOffset(00)]` have such a nice C smell. Special bonus point for naming it `GuidUtils` and not `GuidHelper` (death to helpers!). Wondering if it would be even more elegant to make it an extension method on Guids, eg `guid1.CombineWith(guid2)`?

Oh, and if I wanted to be annoying, I'd say... you've spelled "hexidecimal" in a few places and... should be "hexadecimal". Other than that, go for it.

For the sake of the discussion, what do you think about the idea of not using the Guid full string but shortening it to, say, 9 chars (it's currently commented out)?

**Comment by JimBobSquarePants** [comment]
@Shazwazza Yeah, pretty advanced stuff, decomposing the guid using it's layout in memory is particularly tricksy. If you want me to add more documentation to clarify how things work just comment on the diff in the PR and I'll update accordingly.

@zpqrtbnk My spelling is hampered by autocorrect, I have become incredibly lazy... Shocking! 

Death to helpers indeed! Glad you agree.

I'm not a fan of extension methods when structs are involved tbh, basically because the struct copy is now hidden from the user. 

``` c#
// Passing the struct by ref or val is really obvious here. 
Guid combined  = GuidUtils.Combine(guidA, guidB);

// When using an extension method the calling syntax is exactly the same when passing the struct by ref or by val. This could lead to someone updating the extension in the future to pass by ref and you wouldn't know you were potentially breaking code at runtime. 
Guid combined = guidA.CombineWith(guidB);
```

As for trimming the guid output? I would recommend against it. We've already dramatically reduced the uniqueness of the Guid by halving the unique bits. Further trimming to 9 chars would bring us dangerously close to hitting the birthday paradox.

**Comment by Shazwazza** [comment]
I'm all happy with it, @zpqrtbnk can go ahead and merge if he's happy, Cheers!

**Comment by zpqrtbnk** [comment]
well then... let's merge! thanks!!!

**Pull request merged**
