### PR TITLE
Fixes: #14486 - Some sr-only texts not localized

### PR DESCRIPTION
**Pull request by johanbomoller**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

#14486 

- Added swedish translations for the visuallyHiddenTexts area contributed in comments on the issue by @plannero.
- Localized strings in umb-tree-item and umb-tree with translations in sv and en-US.

Test: Change user language to swedish and browse the content tree with a screen reader. Or just search for the strings in Chrome DevTools.

### CODE REVIEW

**Comment by busrasengul** [comment]
Thank you @johanbomoller for your very first PR for Umbraco projects. 🎉 Someone from Core Collabs team will look into this.

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Hi @johanbomoller ,

Thanks for this PR and for helping making Umbraco more accessible 👍

I have checked and it all works fine, I just needed to remove a trailing comma that sneaked in, and while I was at it, I also added the new labels in the default en.xml file. I hope you won't mind 😁

I'll merge this PR as soon as the tests have finished running on my changes.

I also see that this is your first contribution to the Umbraco CMS; congratulations!! 🎉
If you provide us with your account name on Our, our steward @nul800sebastiaan will be more than happy to assign our shiny contributor's badge to you 🥇

And now we'll be looking for your next ones 😉

Cheers!

**Comment by johanbomoller** [comment]
Hi @mikecp and thank you!
Indeed it is my contribution. My account name on Our is johanbomoller and I actually have another PR up 😉

**Comment by mikecp** [comment]
That's great to hear @johanbomoller !
It will certainly be picked up soon by me or one of my teammates. Keep up the good pace! 👍😉

**Pull request merged**
