### PR TITLE
Localize "unsaved changes" dialog.

### PR DESCRIPTION
**Pull request by bjarnef**
Issue: http://issues.umbraco.org/issue/U4-8343

Added localization of "unsaved changes" dialog. I have translated the text in Danish and also added the keys for the other languages - so they will still see the English translation and it also make other developers aware of the changes, so they can translate the text in other PRs.

### CODE REVIEW

**Comment by abryukhov** [comment]
Hi, @bjarnef,

nice to see the progress in localization tasks, thank you.

I have a question: how Umbraco deals with duplicated lang-files area names (I haven't tested at all by myself)? Your new keys are grouped in their own 'notifications' area, but the area with the same name already exists...

**Comment by bjarnef** [comment]
Okay, I didn't noticed the other `notifications` area used for notification emails.
I might rename it to something else.

I think the it doesn't matter with duplicated areas, although it should be avoided and stick to one area with that alias. If it find duplicated keys I think it is the last one that is used.

**Comment by bjarnef** [comment]
@abryukhov I have renamed the area to `prompt`... no sure if there is a better alias.
I think the `umbConfirmAction` directive works similar to this "prompt" but having used that directive yet: https://github.com/umbraco/Umbraco-CMS/blob/75c2b07ad3a093b5b65b6ebd45697687c062f62a/src/Umbraco.Web.UI.Client/src/common/directives/components/umbconfirmaction.directive.js

I see you have updated ru.xml in another PR's, so feel free to fork this branch and submit a PR for it, then I can merge it into this branch, so this PR will be updated.

**Comment by abryukhov** [comment]
Ok, I've added new commit to my latest existing PR #1227 with all my changes (new area, new keys to other areas and some typos correction).

There is one previous unmerged PR concerning ru UI lang file (#1171)... If I did it all correct tonight, the latest PR should contain all changes in its two commits, including changes from #1171... But I think it would be best way to merge them both ordered by id :-)

**Comment by simonbusborg** [comment]
Looks good @bjarnef 🤘 Thanks and major #h5yr for all the good work

**Pull request merged**
