### PR TITLE
v8: Update image cropper slider

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/3985

### Description
This PR updates the image cropper slider from using a regular `<input type="range" />` to use `umb-range-slider` component.

It might need a bit adjustments, e.g. the image isn't scaled when dragging slider (as the current slider does, but first on drag end).

Furthermore we might not want to show a tooltip or should we convert this to a human friendly format (e.g. percentage, where minimum value is 100% and e.g. max is 300% or a higher value than 100%). The same applies to the pips if we want to show these.

### CODE REVIEW

**Comment by bjarnef** [comment]
The image can be updated by using `on-slide` event, but it seems to lack a bit when doing this compared with the traditional slider.
https://refreshless.com/nouislider/events-callbacks/

I also tried with `on-update` but on init the handle then seems to just a bit between center and current value.

```
<umb-range-slider
          ng-model="sliderValue"
          options="sliderOptions"
          on-setup="setup(slider)"
          on-slide="slide(values)"
          on-change="change(values)">
</umb-range-slider>
```

```
scope.slide = function (values) {
       scope.dimensions.scale.current = values ? values.toString() : null;
};
```

**Comment by bjarnef** [comment]
It now seems to work with `on-slide`. I guess it was expensive to use `sliderRef.noUiSlider.set(scope.dimensions.scale.current);` inside the `scope.$watch("dimensions.scale.current")`.

It now needs to set the current scale position on init.

**Comment by bjarnef** [comment]
It seems to work very well now.

**Comment by bjarnef** [comment]
Furthermore it can use the **wNumb** plugin to format the tooltip and pips.

Otherwise it might be possible manuel in the format to function and in pips filter function.

E.g. 

```
to: function (value) {
     return parseFloat(parseFloat(value).toFixed(3)) + "%";
}
```

where it need to convert the min to 100% and max to a higher percent.

**Comment by nul800sebastiaan** [comment]
Thanks @bjarnef - currently the custom cropper seems very broken so I can't test this properly. But based on what I've tried out with this it looks great!

Can you remove the old slider completely and don't show the tooltip, I am not sure it's useful information and we don't have it on our current slider either. 

After that it seems it's completely ready for merging once the other cropper issues have been fixed!

**Comment by bjarnef** [comment]
@nul800sebastiaan sure, I just kept the original slider if you wanted to compare with how the existing slider works.

I can also remove the tooltip and the pips if needed. If they should be used I though of the values should be converted to percentage, so minimum value is 100% and then increasing from this value and the tooltip could show the current percentage.

We can also just remove it for now and add it later if needed.

**Comment by nul800sebastiaan** [comment]
@bjarnef Thanks! Yeah, for now I don't think they add anything to the experience so let's remove them and see how it goes. 

Looks like @kjac is close to fixing the cropper problems tonight so I'd love to test it out again and merge it all!

**Comment by kjac** [comment]
The current zoom issue is tied to the current slider. I'll push a fix for it later tonight. Just keep it in mind when changing the slider for something prettier 😊

**Comment by bjarnef** [comment]
@nul800sebastiaan I have removed the old range slider, disabled tooltip and slider pips,

image

**Comment by nul800sebastiaan** [comment]
@bjarnef What does that mean? There's a "Reset crop" link to zoom back to original size, right?

**Comment by nul800sebastiaan** [comment]
I see what you mean now, you can't get back at all to zooming out so far that the image fits in the crop area. Must be something to do with the scaling being off 🤔

**Comment by bjarnef** [comment]
@nul800sebastiaan yeah, it might be something with the calculations.

Maybe @kjac wants to have a look at this? 😉
Otherwise I might look a bit further on this issue in the upcoming days.

**Comment by nul800sebastiaan** [comment]
I've been playing around a bit, I think the problem is that the initial size on the scale is not set correctly. As soon as I move the slider, it jumps to 1.00 instead of (in this case) 0.15. 

And when going down all the way to the left, the minimum should not be hardcoded to 0.3 but the calculated value you get initially (`0.1408..`) in this case. That way it will stay constrained to the crop area.

**Comment by bjarnef** [comment]
@nul800sebastiaan the initial value is set to 0.3 here https://github.com/umbraco/Umbraco-CMS/blob/98c36e06f82ba4a89926d34ebaece336e5fe10ca/src/Umbraco.Web.UI.Client/src/common/directives/components/imaging/umbimagecrop.directive.js#L36

but then updated here https://github.com/umbraco/Umbraco-CMS/blob/98c36e06f82ba4a89926d34ebaece336e5fe10ca/src/Umbraco.Web.UI.Client/src/common/directives/components/imaging/umbimagecrop.directive.js#L169-L185

but not sure if the max should be hardcoded from init value 3 to 2 in `resizeImageToCrop`, which is called inside `init`.

**Comment by bjarnef** [comment]
@nul800sebastiaan in this part of the code `sliderRef` was null. I guess this was executed before `sliderRef` was set in setup callback function. https://github.com/umbraco/Umbraco-CMS/blob/1838870c4f750d5b091ff9fa634ab8f9db465172/src/Umbraco.Web.UI.Client/src/common/directives/components/imaging/umbimagecrop.directive.js#L186-L195

I have moved this inside `setup` function where the callback returns the slider reference and also updated the default `min` value from `0.3` to `0` (not sure what the value 0.3 does?).

**Comment by bjarnef** [comment]
@nul800sebastiaan maybe you want to check how it works with the latest changes?

**Comment by nul800sebastiaan** [comment]
@bjarnef Awesome!! This seems to work really nicely now! Thanks for sticking with it for so long! ⭐️ 🎖

**Comment by bjarnef** [comment]
Wuhoo! 🤓😎🦄🎉🏆🔙🔚

**Pull request merged**
