### PR TITLE
Fix of U4-4538

### PR DESCRIPTION
**Pull request by BatJan**

### CODE REVIEW

**Comment by craigs100** [comment]
Still seeing this problem in V7.1.8 and V7.2.1 sites.

**Comment by Shazwazza** [comment]
@craigs100  this PR only targeted the spanish language file

**Comment by craigs100** [comment]
@Shazwazza Good point! Issue raised for other languages.

**Comment by Shazwazza** [comment]
Yup all good, just pointing that out. I've fixed up your issue now though, there was 2 langs with problems.

**Pull request merged**
