### PR TITLE
Added regex for youtube shorts for v8

### PR DESCRIPTION
**Pull request by Ambertvu**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

Issue described here. https://github.com/umbraco/Umbraco-CMS/issues/13632

### Description
Added backport for 8.18, I hope have the right branch for this :-)

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi again @Ambertvu!

Thanks for your PR to fix #13632 where embedding YouTube short URLs doesn't work. 

One of the Core Collaborators team will review this as soon as possible.  👍 

Best wishes

Emma

**Comment by JasonElkin** [comment]
Sorry @Ambertvu. I tried changing the target branch and it did terrible things to the history.

Let me drop a note to HQ to make sure that this will actually make it into v8 (it's on bugfix only support now, i.e. no more minors). If it does, I think we'll need the PR to be recreated from/to v8/dev.

**Comment by Ambertvu** [comment]
Hmm odd, I made it from that branche though, but perhaps I fked up, haha.
Let me know if its still needed!

**Comment by nul800sebastiaan** [comment]
Hey all, let's focus our efforts on v13+ here. If this is needed for v8, then a custom OEmbed provider will do the trick. I'll close this one, thanks!

**Pull request closed without merging**
