### PR TITLE
U4-9025 - Add sortable to color picker prevalues

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org/issue/U4-9025

### Description
I have created a new PR for this other PR https://github.com/umbraco/Umbraco-CMS/pull/1504, which was a mess and since it has been open for two years a lot has happened since then, so there were several conflicts, so time to start this on a fresh with latest changes in `dev-v7` branch.

### CODE REVIEW

**Comment by bjarnef** [comment]
A few issues at the moment

- After save the color label doesn't seem to be persisted

image

image

- After save the color sortorder doesn't seem to be persisted

image

image

In `ConvertEditorToDb` I have also added a null check on `sortOrder` property.

I think these lines would be the same:
```
int sortOrder = int.TryParse(x["sortOrder"]?.ToString(), out int sortOrder) ? sortOrder : 0;```
```
```
int.TryParse(x["sortOrder"]?.ToString(), out var sortOrder);```
```

for `id`:

```
var idString = x["id"] == null ? "0" : x["id"].ToString();
int id = int.TryParse(idString, out id) ? id : 0;
```

I think it could also be written as:

```
int id = int.TryParse(x["id"]?.Tostring(), out int id) ? id : 0;
```
or

```
int.TryParse(x["id"]?.Tostring(), out var id);
```

**Comment by nul800sebastiaan** [comment]
Alright, your code changes indeed make sense, I've applied them.

🙈 🙈 🙈 🙈 

SORRY, it included unrelated commits again, but not to worry, this is going to be fine once I merge it! 

Anyway..


I can see that the browser does not submit an actual sortOrder, so we'll infer them from the order the browser sends them in, which is the sorted order.

So now there's 2 things:

1. When "Include labels?" is set to on, the color label gets stored correctly and retrieved correctly, no problem. However, the ordering the browser is wrong. I can see that the values get returned in the correct order and with these changes there is a sortOrder property available that we could use.. but..
2. When "Include labels?" is set to off, we ONLY store the colors, which is the default behavior apparently so we can't change that else it would be a breaking change. So for both 1 and 2 we will just need to sort things in the browser from the exact order specified in the json we return, can you look into that?

See the image below, the ordering in the json is fine but I have NO idea why the presentation is wrong, what am I missing?

image

**Comment by bjarnef** [comment]
@nul800sebastiaan yeah, at the moment the ordering doesn't work correct, maybe I have missed something from my original PR or because the labels has been added since then.

I am not sure if the logic inside sortable `update` function is needed, when using `ng-model` on the parent element, which seems to be required to set, when using `ui-sortable`.

I think I originally copied some of the other property editors, when stored multivalues prevalues, e.g. for dropdown, checkboxlist and radiobuttonlist.

**Comment by bjarnef** [comment]
@nul800sebastiaan I think it did work before the labels was included and it used same approach as sorting prevalues in dropdown, checkboxlist and radiobuttonlist, but it is long ago I tested that part.

Is there anything that differs from the prevalues of the mentioned property editors? Not sure if we can re-use exactly same stuff here.

I am a bit buzy of the office these weeks, because I am the only one, who is not on holiday, but I would just get this started on scratch if anyone has time to work on this and since I think this stuff has been missing :)

**Comment by nul800sebastiaan** [comment]
Alright, I think all the problems are now fixed. This will require some testing to make sure everything works as intended now.

I know there's 1 bug with the useLabel thing, I am finding it impossible to see if the labels input box should be displayed, so it's always shown but if labels are not to be used then any entered labels will be overwritten with the color name. This is no different from how it works today though, I think, so let's see if we can fix this separately.

**Comment by nul800sebastiaan** [comment]
If you have some time to test then that would be amazing @bjarnef !

**Comment by bjarnef** [comment]
@nul800sebastiaan I have tested this and it seems to work great both with "Include labels" true and false and the sortorder is persisted in the prevalues and match the order on the document type property.

Of course when "Include labels" is false you could add a color `#000000` and specify a label name "Black"  it isn't persisted on save, but fallback to "000000" since it doesn't use labels.

I think either "Include labels" should be inside the same prevalue editor for the multivalues colors (but probably not something that is re-useable?) or some javascript to toggle these (but kinda of a hack I guess).

For now maybe just explain in the description for "Add color" that labels only works with "Include labels?" enabled? Maybe also rename "Add color" to "Colors"?

**Comment by bjarnef** [comment]
Maybe we can also add the class `dib` to the parent div of the toggle, so only the toggle is clickable and not much of the whitespace?
https://github.com/umbraco/Umbraco-CMS/blob/7ee510ed386495120666a78c61497f58ff05de8f/src/Umbraco.Web.UI.Client/src/less/utilities/layout/_display.less#L24

**Comment by bjarnef** [comment]
We should probably also keep the style of the "Add" button consistent.
Not sure if you want to use the purple (secondary) color here or the default gray button style?

image

Also the "remove" is not consistent. If the style of the "Remove" should be like on checkboxlist prevalues, I think the hover cover should be red like on pickers on properties, e.g. "Call To Action Link" on Home node in starterkit package.

image

**Comment by bjarnef** [comment]
Great @nul800sebastiaan !

Not sure how you guys want it to be, maybe @madsrasmussen has ideas for this (if not he's on holiday?).

- Should these prevalues "Add" buttons be grey, purple or another color?
- Sometimes to "Remove" buttons are the red button and sometimes more like a button link (like in content), but with green hover in prevalues instead of red hover like in content section.
- Some of the latest changes for dropdown/checkboxlist, radiobuttonlist prevalus now has a grey background. should we also have this on the color prevalues?
- The labels for these says "Add prevalue" or "Add color"? Maybe this should just be changed to Prevalues/Colors since it is both for add, remove and sorting. The description can then have short description about you can add, remove and sort prevalues/colors.

**Comment by nul800sebastiaan** [comment]
Let's follow the newest example, the Flexible Dropdown.

image

Purple Add button, grey boxes with a remove link on the right side, who even knows what a "prevalue" is haha. But yeah, Just "Colors"and a description is even better! 👍

**Comment by nul800sebastiaan** [comment]
Hi five!! Looking and working wonderfully now! 👍 

Thank you @bjarnef ! ⭐️

**Comment by bjarnef** [comment]
Awesome @nul800sebastiaan 
Now we can finally sort colors without removing and adding them again 😁

**Pull request merged**
