### PR TITLE
Added hook for onSelectAnchorItem in umb-editor-header.

### PR DESCRIPTION
**Pull request by jamiepollock**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/8440

### Description

This adds a hook for onSelectAnchorItem for umb-editor-navigation to umb-editor-header.

Here is a [simple dashboard demo](https://github.com/umbraco/Umbraco-CMS/files/5008439/demo-8440.zip) which can be dropped into an Umbraco solution which uses this code base. 

The demo app dashboard utilizes this new hook so it can be tested by HQ. This was used as part of my own testing during development. The demo app reports the navigation item & anchor when clicked in the browser developer console.

**Note:** The current implementation does not modify the active state of the anchor item. If this is required we can discuss the best place to implement this.

### CODE REVIEW

**Review by nul800sebastiaan — CHANGES_REQUESTED** [review]
Thanks @jamiepollock and apologies for the delay! I'm having a heck of a time trying out this PR, I am expecting to see the subviews when I switch between the "section" buttons but nothing is happening, what am I missing?

**Review by nathanwoulfe — APPROVED** [review]
Hey @jamiepollock, hope you remember raising this almost a year ago... Works really nicely, I can certainly see how this will be useful.

@nul800sebastiaan not sure why the dashboard views don't load, I see the same output as your example. However, the new function is called, and the expected values are logged. Looking on a content node, the new function is called when selecting an anchor in the content dropdown, so it follows then that passing in a function on the new attribute will see that function called correctly.

I'm happy to merge this, assuming there are no concerns from the example not working as expected?

**Comment by jamiepollock** [comment]
@nathanwoulfe @nul800sebastiaan hey both, I am sorry I've been ghosting this ticket for so long. Life has been just crazy this past year due to multiple factors, I've not had the energy to deal with anything outside of work. I'll try my best to make amends going forward. I could go on but I'm sure we've all had a rough year or so with COVID.

If you & Seb are happy to merge this then that's great. Otherwise I can try and pick up where I left off. I don't know why the example isn't working as expected. I apologise about that.

**Comment by nathanwoulfe** [comment]
Hey @jamiepollock all good my friend, completely understand. I'll try pick it up again next week, see if I can sort the dashboard demo

**Pull request closed without merging**
