### PR TITLE
U4-10561 - Performance improvement for IsAncestorOrSelf

### PR DESCRIPTION
**Pull request by danbramall**
[U4-10561](http://issues.umbraco.org/issue/U4-10561) - Changed IsAncestorOrSelf method to use path comparison rather than AncestorOrSelf, for improved performance.

### CODE REVIEW

**Comment by leekelleher** [comment]
@danbramall - I've made an update to the other `Is` extension methods.  If you wanted to grab the commit? (or copy the code?) https://github.com/leekelleher/umbraco-cms/commit/5fe0675f7615b4f76c93629a1bf8a9a608dc5321
or I can do a new pull-request? (it would include your commit, so you'll still get credit 😎)

**Comment by leekelleher** [comment]
I've submitted a new pull-request with the extra commits, #2768.
Rebased it against the latest `dev-v7` branch too.

**Comment by nul800sebastiaan** [comment]
Thanks @danbramall - I've just merged Lee's additional changes in the other PR, so I'll close this!

**Comment by coolmikkel** [comment]
A little comment to @nul800sebastiaan, @leekelleher and @danbramall 

I'm not able to test my question to the pull-request.

Wouldn't string.StartsWith some times result in a wrong result?

```
content.Path = "-1,20,30,200"
content.Level = 4

other.Path = "-1,20,3"
other.Level = 3

content.IsDescentant(other)
=>
other.Level (3) < content.Level (4) == true
&&
"-1,20,30,200".StartsWith("-1,20,3") == true
```
But that is not true. [content] is NOT descendant of [other]

Maybe my summer vaction brain has lost it in the heat. And all of the above is wrong.

**Comment by leekelleher** [comment]
@coolmikkel  Aww poop! You're correct. I'll review and update accordingly. Thanks for picking up on this!

**Comment by leekelleher** [comment]
Patched the code, submitted in PR #2787

**Pull request closed without merging**
