### PR TITLE
v8 Macros don't render in the RTE and various

### PR DESCRIPTION
**Pull request by Shazwazza**
Now that we can actually selected a macro (based on https://github.com/umbraco/Umbraco-CMS/pull/4210) it exposes more issues. 

When you try to choose the macro and have it render in the rte a YSOD occurs on the call to GetMacroResultAsHtmlForEditor

There are several reasons for this but many of them have to do with changes made over 2 years ago in v8 that weren't cleaned up yet. I have got this fixed but then it exposed several other problems:

* UmbracoHelper should be injectable and it's services should be injected, there are several constructors that don't fulfil this need and cause issues
* UmbracoHelper's Media method doesn't work correctly and isn't using the media method calls to the cache correct (still left over logic from v7)
* The way macros and templates are rendered is super old and crappy and this is causing other problems, since we've updated the old `page` class to something more relevant this is relatively easy to clean/fix up, still not pretty but much better and we can expose 2 simple interfaces IMacroRenderer and ITemplateRenderer
* Macro rendering requires having a variation context set and there wasn't one
* Now that macros are rendered and inserted, there's yet another problem - with the update of TinyMce our macro navigation is broken. Before when you'd navigate in the RTE it would select the macro correctly and move around it and also allow you to delete it's block correclty, now that no longer works properly.
* TinyMCE also doesn't load in the rendered macro contents on page load - due to our new skin setup
* The loading image has been removed for this too so that needs to be replaced with something else
* TinyMCE also doesn't update a macro when it's selected and the parameters are edited.

### CODE REVIEW

**Comment by Shazwazza** [comment]
Initial commit does the following: 

New IMacroRenderer and ITemplateRenderer and hides underlying logic for these in internal classes. Massively cleans up the macro rendering logic (almost makes sense now), removes unused macro code, injects UmbracoHelper wherever it's needed (not creating manually), fixes UmbracoHelper to have it's services injected, no more empty services, allows setting the AssignedContentItem on the UmbracoHelper and ensures it's lifespan is Transient, updates all corresponding ctors. Fixes macro rendering, ensures the correct culture variation is assigned, and that we can render macros for any given IPublishedContent, not just the one assigned in the request.

**Comment by Shazwazza** [comment]
This fixes all sorts of things:

* New IMacroRenderer and ITemplateRenderer and hides underlying old legacy logic for these in internal classes. 
* Removes a bunch of old legacy logic that we don't want or use anymore like HttpContext.Items["pageElements"]
* Massively cleans up the macro rendering logic (almost makes sense now) and removes unused macro code (there was a lot)
   * Fixes macro rendering, ensures the correct culture variation is assigned, and that we can render macros for any given IPublishedContent, not just the one assigned in the request.
* Injects UmbracoHelper wherever it's needed (not creating manually)
   * Fixes UmbracoHelper to have it's services injected, no more empty services and allows setting the AssignedContentItem on the UmbracoHelper and ensures it's lifespan is Transient
   * Updates all corresponding ctors. 
* Fixes TinyMce macro implementation which broke with new changes
   * Actually uses the built in tinymce plugin 'noneditable' which wasn't really working before, this allows us to remove all of the custom code we had to deal with this ourselves
   * Fixes the macro styles in tinymce which broke for various reasons - new tinymce version, new distraction-free theme, etc... 
    * Fixes being able to insert and render a macro into tinymce without YSODing
    * Fixes the grid tinymce implementation to make sure the configured 'theme' is passed in (i.e. so you can have distraction free in the grid)
    * Fixes loading macro content when the editor is loaded, this was totally broken with tinymce updates

## Testing

* Create 2x RTE data types one with distraction free and one with classic and allow macros in each
* Create a macro or two with parameters, ensure that it can be used in rte and that it renders contents, make sure the view has some simple content to render
* Create 2x grid editor one with the rte in distraction free and one with classic
* Create a page with a document type containing all of these properties
* Insert macros into all of these properties - it should work
* Click on any of these macros, they will be highlighted, ensure you can delete them but you cannot edit the block, also the macro toolbar button will be hightlighted, you can also keyboard navigate on top of a macro and it will be highlighted
* Edit a macro, click on it and click on the macro toolbar button and the macro dialog will display with all of the filled in parameters of the macro selected, update the parameters, then do this again and ensure the parameters are correct in the dialog
* Save the content item, navigate away and come back to the page, all macros should load correctly and display
* Make sure all tests are passing (you can see this in Azure Devops)

## Known issues

The distraction free editor in the rte when it is in the grid has a slight problem: when you select a macro in the rte a mysterious white box is overlaid ... we'll need to fix this another time.

**Comment by bergmania** [comment]
I can't test everything yet, due to some errors.

- When I try to add a Macro in a grid on a unsaved page
   - The reason is because the `pageid` is  `-1` and ` _contentService.GetById(pageId)` then returns `null` 

- When I save the content before adding macros to it, I get another error:
  - The reason is because ` _umbracoContextAccessor.UmbracoContext.ContentCache?.GetById(contentId)` returns `null`

**Comment by bergmania** [comment]
I can continue if the document is published. When I save the content with the macro, and move away from the page and back, The macro-configuration is opened automatically?

**Comment by Shazwazza** [comment]
@bergmania thanks! I've fixed up those issues, though that last one is odd, i can't replicate that one but maybe was resolved with the latest merge? I've found another issue with pinning the RTE toolbar but that won't stop you from testing.

For the first bug, if the Id is -1, then there is no content to render against so it's not possible to render a macro, so when that happens we render the default text which is equivalent to when a macro is rendered in the RTE and is not configured to render it's contents.

**Pull request merged**
