### PR TITLE
temp-6217 | Preview not working with remove trailing slash

### PR DESCRIPTION
**Pull request by jveer**
Issue #6217

### CODE REVIEW

**Comment by jveer** [comment]
@nul800sebastiaan Thanks for the feedback, actually I just noticed that the preview was hard-coded with a ending slash in one of the controllers. So I removed that hard-coded slash to make the preview work even when removing the slash via web.config instead of the `umbracoSettings`. PR is updated

**Comment by nul800sebastiaan** [comment]
@jveer Have you tested this without your rewrite rules as well? 

There's a few seemingly random changes in here, there must be a reason we added the `../` at some point for example and I am afraid that we're just working around your particular problem right now instead of finding a structural solution.

**Comment by jveer** [comment]
@nul800sebastiaan Yes, I've tested this locally with both the rewrite rule and without, same for the setting in `umbracoSettings`.

However, I think the reason `../` was added, was because the preview page had an trailing slash. The only location in the code where the `lazyload.min.js` is loaded using `../` is for the preview index, for all other locations it's directly loading `lib/lazyload-js/lazyload.min.js`.

Therefore I've changed all locations where the preview page is called to exclude the trailing slash, so the view will always work with the new accessing of the preview page.

**Comment by nul800sebastiaan** [comment]
Thanks again @jveer - I've closed the related issue with a reason here: https://github.com/umbraco/Umbraco-CMS/issues/6217#issuecomment-553180844

**Pull request closed without merging**
