### PR TITLE
V8: UX updates to the listview copy dialog + add option to include descendants

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

The copy dialog used by listviews needs a little TLC:

1. It does not have any contextual help text. The copy dialog used by trees has a text like "Choose where to copy [node name] to in the tree structure below". 
2. The "Submit" button is always enabled. If you click it without choosing a target for the copy operation, the dialog simply closes without any user feedback.
3. There is no option to include or leave out descendants. The copy dialog used by trees has this option.

image

This PR addresses all of the issues mentioned above:

listview-copy-update

### CODE REVIEW

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Comment by poornimanayar** [comment]
Hey @kjac ,

can you resolve the merge conlicts.

Poornima

**Comment by kjac** [comment]
@poornimanayar sure, all done 👍

**Comment by kjac** [comment]
PR updated with latest v8/dev and the checkbox is now a toggle as per #6944 

image

**Comment by poornimanayar** [comment]
Seeing more changes here, so i am holding off merge till we are sure about it!

**Comment by kjac** [comment]
@poornimanayar good call 👍

**Comment by kjac** [comment]
@poornimanayar I've merged from `v8/contrib` and now the PR looks all good to go again 👍

**Comment by kjac** [comment]
Cross linking this to #7702

**Pull request merged**
