### PR TITLE
U4-10537 - Enable editor to skip Macro Selection step, when there is only one macro, and it has parameters

### PR DESCRIPTION
**Pull request by marcemarc**
Issue: http://issues.umbraco.org/issue/U4-10537

This PR means that when an editor clicks the Insert Macro Button inside a rich text area or grid, if the site only has One Macro, they will skip straight to the enter parameters stage, instead of having to pick the Macro when it's the only option available.

If the Single Macro doesn't have parameters, I've left it so that they still need to pick the single Macro, otherwise the immediate insertion of the Macro, is a bit un-nerving.

If there is more than one Macro then everything is the same.

I've put in two separate commits, as I'm not sure to what extent the InsertMacroController is still being used?

It is the MacroPickerController that is used in Rich Text Area and Grid.

### CODE REVIEW

**Comment by marcemarc** [comment]
discussed with @nul800sebastiaan and @hartvig at the UK Hackathon, and we think this is a good thing, but just too late in the day to merge into the hackathon release

**Comment by nul800sebastiaan** [comment]
Thanks @marcemarc - makes total sense and works as expected! 👍

**Comment by marcemarc** [comment]
@nul800sebastiaan w00t

**Comment by hartvig** [comment]
I understand the use-case and appreciate the improvement, but this means that the UX is inconsistent. Ie. in one scenario this would open the select macro option and in another it would open options for a specific macro.

The ideal solution would be to allow special insert-specific-macro buttons to be added to the RTE.

**Comment by marcemarc** [comment]
@hartvig it sort of doesn't make the UX inconsistent, to an editor who only uses a site that happens to have one macro, which has parameters eg there is nowhere else they can see the alternative... but then there is a mismatch with the name eg 'macro'

So I love the suggestion that you could easily configure a custom tiny mce button to fire a particular macro...

It's kinda what we ended up doing for the client in the end: (because they also wanted to pop open an image picker):

https://youtu.be/BunOlQ1xzHg

but it was quite tricky to get working, let's make macros great again!

**Pull request merged**
