### PR TITLE
U4-3268 - changed Nvarchar to Ntext to avoid character limit of 500

### PR DESCRIPTION
**Pull request by raduorleanu**
### Prerequisites

- [x] I have [created an issue](https://github.com/umbraco/Umbraco-CMS/issues) for the proposed changes in this PR, the link is: https://github.com/umbraco/Umbraco-CMS/issues/3268
- [x] I have added steps to test this contribution in the description below

### CODE REVIEW

**Comment by dawoe** [comment]
Hi @raduorleanu 

Thanks for this PR.

I think changing the storage type of a property editor is a breaking change.

This will need to be tested thouroughly first.

Maybe @nul800sebastiaan can say something about it already

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by nul800sebastiaan** [comment]
@dawoe I encouraged him to make this change! 😉

I am not sure how storing the value in a larger field would be a breaking change:

1. Upgraders will still have their data stored in the same column as before
2. This only applies to new installs or newly created datatypes
3. I didn't test but I don't think querying will break

**Comment by dawoe** [comment]
That's why I said needs to be tested  thouroughly first. I am not sure either

😄

**Comment by Shazwazza** [comment]
Wont a data migration then be necessary for this on upgrade to move all data from nvarchar to ntext? Else it will (might) just return empty values for existing values?

**Comment by nul800sebastiaan** [comment]
I can't see a problem: 

- Existing site before this PR has a Datatype that stores member groups in Nvarchar
- It's still displaying selected groups after the PR and it still stores them in nvarchar
- The caches values are still a comma seperated list of string
- Creating a new datatype makes the values for that one appear in the ntext column
- The cached output is the same, comma separated list

Nothing seems to break and if we were to make a migration then we'd have to also change the storage type on the old datatype AND move all the values over. 

I would just go with this, it's simple, it doesn't need to touch existing data and if someone runs into the limitation because it was once created as nvarchar we can tell them how to update their database.

Any objections @Shazwazza @dawoe ? Anything I missed?

**Comment by Shazwazza** [comment]
Without the migration, if you then just go and re-save the existing data type, it will now update the data type to look at ntext but all data will be in nvarchar?

**Comment by nul800sebastiaan** [comment]
Aha good point @Shazwazza - funnily enough though.. it doesn't really care where the data is coming from, it's happily showing my previously nvarchar-saved data. 

Anyway, I guess something will fall over then. We'll just have to bit the bullet and make a migration for it.

**Comment by nul800sebastiaan** [comment]
Thanks again @raduorleanu for the help, for now I'll close this one and rethink what we need to do to get this one over the finish line. Let me know if you can still help, it will be more work and quite a few more moving parts will need to be involved.

**Comment by nul800sebastiaan** [comment]
Hi there @raduorleanu,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing :pray:

If you haven't heard already we have had a record breaking amount of PR's in both the CMS and the Documentation repository. You can read all about the numbers in the [Umbraco Hacktoberfest Aftermath blog post](https://umbraco.com/blog/the-2018-hacktoberfest-aftermath/).

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://goo.gl/forms/smjQwEMDM5cUnz6x1) :point_left: Please follow this link to fill out and submit the form, **before November 21st 2018**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before December, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request closed without merging**
