### PR TITLE
Add skip links to header

### PR DESCRIPTION
**Pull request by mattbegent**
### Prerequisites

This issue resolves https://github.com/umbraco/Umbraco-CMS.Accessibility.Issues/issues/15

### Description

This PR adds skip links to the header to allow users to skip to the menu and main content.

umbraco-skip-links

To test the change tab through the website and select each skip link. "Skip to menu" will skip the user to the first navigation link and "Skip to content" the user to the first visible focusable element in the main content.  On pages where there is a left column, this will focus on the first element in the left column. On pages where there is no left column (like Packages), it will focus on the first focusable element in the main column.

I had to use buttons instead of links (you would normally use links for skip links that anchor to ids), because the angular routing in Umbraco uses hashes and these were being intercepted.

I debated about the placement of these links. I tried pushing the navigation right when they are focused, however this meant the navigation was partly pushed off screen on certain viewports sizes. I also considered pushing the content down (I've seen this on some websites), however the main content in Umbraco is absolutely positioned.

W3 reference:
https://www.w3.org/WAI/WCAG21/Understanding/bypass-blocks.html

### CODE REVIEW

**Comment by MMasey** [comment]
Thanks for this PR @mattbegent! I've shared it with the rest of the accessibility team and we'll get back to you soon 😄

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Hi @mattbegent ,
Thanks for this contribution, it works great and it's always nice to add features that improve accessibility 👍

I will wait to get the feedback from @MMasey and the accessibility team to see if I can merge your PR as-is or if they wish some adaptations first 😉

Cheers!

**Comment by mikecp** [comment]
Hi @mattbegent ,

It seems to be OK for the accessibility team, so let's get this merged right now 😉

Thanks again and congratulations on your first contribution to the Umbraco CMS 🎉
If you provide us with you account name on Our, @nul800sebastiaan will be very happy to assign our shiny contributor's badge to you 🥇

And now we'll be looking forward to your next PR's 😁

Cheers!

**Comment by nul800sebastiaan** [comment]
Cherry picked for 10.5 in f70533e3a09658f25eb7850671be375c55d78911

**Comment by mattbegent** [comment]
> Hi @mattbegent ,
> 
> It seems to be OK for the accessibility team, so let's get this merged right now 😉
> 
> Thanks again and congratulations on your first contribution to the Umbraco CMS 🎉 If you provide us with you account name on Our, @nul800sebastiaan will be very happy to assign our shiny contributor's badge to you 🥇
> 
> And now we'll be looking forward to your next PR's 😁
> 
> Cheers!

Thanks @mikecp. Super news! My Our Umbraco username is mattbegent.

**Comment by nul800sebastiaan** [comment]
Thank you Matt and congrats on your shiny new contributor badge! 👍 https://our.umbraco.com/members/mattbegent/

**Pull request merged**
