### PR TITLE
[DRAFT] Netcore/members migration removeproviders - merge after roles and signinmanager

### PR DESCRIPTION
**Pull request by emmagarland**
### Prerequisites

- [ ] I have added steps to test this contribution in the description below

### Description

This is a draft PR for removal of the providers and refactoring of the helpers. It is not complete but I wanted to show what I was working on. It will be merged last after #9902, #9946 and #9985

### CODE REVIEW

**Comment by Shazwazza** [comment]
@emmagarland I'm just working on converting the member macros to netcore which will also be cleaning up the `IUmbracoWebsiteSecurity` class (possibly killing it off). Let me know if that overlaps with anything here or other work you're doing. Cheers!

**Comment by emmagarland** [comment]
Sounds fab @Shazwazza - I’ve been moving house so haven’t been able to do anything since the work shown in the PRs.

**Comment by Shazwazza** [comment]
@emmagarland I'm going to close this PR since most of the work done in here is already completed elsewhere and is now quite far out of date. Cheers!

**Comment by emmagarland** [comment]
Makes sense @Shazwazza, thanks for letting me know!

**Comment by Shazwazza** [comment]
@emmagarland there's still some goodies in here but i'll go through each change and apply what's needed manually. Cheers!

**Comment by emmagarland** [comment]
> @emmagarland there's still some goodies in here but i'll go through each change and apply what's needed manually. Cheers!

Awesome, glad it can still be of some use!

**Pull request closed without merging**
