### PR TITLE
U4-5242 - Allow user to enter a custom validation error message

### PR DESCRIPTION
**Pull request by clarkd**
This PR adds a ValidationCustomErrorMessage field which is displayed as the error text if validation does not pass. 

Just attending some Umbraco courses with Per and I asked if this was possible - seems like a useful feature so thought it would be worthwhile creating a PR after he told me it wasn't!

screenshot 2017-10-18 13 02 47

I've updated the propertytype under the legacy businesslogic but wasn't sure if this was required? Let me know if not and I can revert that commit.

### CODE REVIEW

**Comment by clarkd** [comment]
Closing due to inactivity.

**Comment by nul800sebastiaan** [comment]
@poornimanayar I think it's because the database is not being updated.  The SQL files were updated, we should really delete them as they're unused. We need a Migration instead to add the new column in the database.

Try adding this one and changing the version in web.config back to 7.11.1 so that the 7.12 migrations run.

```
using Umbraco.Core.Logging;
using Umbraco.Core.Persistence.SqlSyntax;

namespace Umbraco.Core.Persistence.Migrations.Upgrades.TargetVersionSevenTwelveZero
{
    [Migration("7.12.0", 3, Constants.System.UmbracoMigrationName)]
    public class AddCustomErrorMesssageForProperties : MigrationBase
    {
        public AddCustomErrorMesssageForProperties(ISqlSyntaxProvider sqlSyntax, ILogger logger)
            : base(sqlSyntax, logger)
        {
        }

        public override void Up()
        {
            Alter.Table("cmsPropertyType")
                .AddColumn("validationCustomErrorMessage")
                .AsString()
                .Nullable();
        }

        public override void Down()
        { }
    }
}
```

**Comment by poornimanayar** [comment]
Yes, I did gather that it was something to do with migrations but wasn’t sure how to fix it

**Comment by poornimanayar** [comment]
Shall give it a go and try testing 🙂

**Comment by clarkd** [comment]
Great to see some activity on this! Let me know if I can assist?

**Comment by nul800sebastiaan** [comment]
Thanks @clarkd and apologies for the delay on reviewing this. 

FYI, we've been making some changes recently to really focus on PRs coming in, and we're slowly getting to the older PRs too, if you'd like to learn more, here's some reading material:
https://umbraco.com/blog/introducing-the-new-pr-team/
https://umbraco.com/blog/the-pr-team-chronicles-month-one/

We'll let you know how it goes with this new feature, which is something we've been wanting to have for a long time, thanks for your work on it so far!

**Comment by poornimanayar** [comment]
Hi @clarkd ,

I am going to test this today :) Shall let you know. Looks like a really nice feature

Regards,
Poornima, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by poornimanayar** [comment]
Hi @clarkd ,

I have tested the functionality and it looks good. I can enter custom error messages and see them. I went to test the custom error message functionality against just a mandatory field but I could not get the custom error message to show. I think it would be nice if we can get the custom error message to show in this scenario as well rather than just locking it down to custom validation only(I know, the issue addresses only custom validation). Do you think you can have a look at it?

I have managed to rebase the PR and add the migration class as @nul800sebastiaan mentioned to get it all working against the latest dev-v7 branch. I am not sure I can push those changes in. 

Poornima

**Comment by clarkd** [comment]
Closing - inactive.

**Pull request closed without merging**
