### PR TITLE
U4-11458 - Fix multiple issues for angular logResource

### PR DESCRIPTION
**Pull request by dawoe**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org/issue/U4-11458

### Description

This PR fixes following bugs found when using the log resource : 
-  method getPageUserLog calls wrong API method
- fixed issue with multiple WHERE clauses in generated sql query for getting user log
- Mark logResource methods as obsolete where called API method is marked as obsolete
- Unmarked one API method as obsolete, because there is no alternative
- date parameters were not passed correctly to API, so they were always null in the API methods
- added missing documentation in the logResource
- set correct current page number in api

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @dawoe 

Thanks for you PR and sorry it's taken so long for me to get around to having a look (I wasn't ignoring you, I promise). I will have a good look at this some time this week and let you know if you need to change anything.

Emma

**Comment by Shazwazza** [comment]
I can confirm the duplicated WHERE clause, this also exists in another method where we have similar logic to combine queries. I'm going to take a look and update unit tests. The fix should be part of the logic that combines the queries so will reply once I know more, thanks!

**Comment by Shazwazza** [comment]
@dawoe I've created a PR for you to have a look at which addresses the SQL issues: https://github.com/umbraco/Umbraco-CMS/pull/2866 

Let me know if that all makes sense and if so please merge and then update this branch with the latest from dev-v7 without your SQL adjustments and I'll review the other fixes that you've got here. 

Thanks!

**Comment by marcemarc** [comment]
@nul800sebastiaan we're holding off rewriting the angularJS dashboard tutorial in the docs, as this PR will fix the bit that uses the logResource and allow us to update the code to enable people to fix the exercise...

... do we know if this is 'ready to go' in the next release?

**Comment by dawoe** [comment]
Hi @marcemarc 

It probably needs some work after the referenced PR from Shannon is merged

Dave

**Comment by nul800sebastiaan** [comment]
@dawoe All ready with the other PR, go ahead! 👍

**Comment by dawoe** [comment]
I have merged in latest dev-v7. Unit tests are green. I also tested the rest of my changes.

Maybe somebody can test this again : 
- make sure audit log on info tab works
- take the tutorial https://our.umbraco.com/documentation/tutorials/Creating-a-Custom-Dashboard/

**Comment by nul800sebastiaan** [comment]
Great, looks good @dawoe ! Glad that the inconsistencies are gone now, well done! 👍

**Comment by prjseal** [comment]
> I have merged in latest dev-v7. Unit tests are green. I also tested the rest of my changes.
> 
> Maybe somebody can test this again :
> 
> * make sure audit log on info tab works
> * take the tutorial https://our.umbraco.com/documentation/tutorials/Creating-a-Custom-Dashboard/

I Dave I tested the tutorial and there is still an error with the logResource on Umbraco v7.12.3

You can pull this repo to see it. (https://github.com/prjseal/Umbraco-Documentation-Tutorials)[https://github.com/prjseal/Umbraco-Documentation-Tutorials]

**Pull request merged**
