### PR TITLE
V8: Improvements for logviewer search results view

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

As an addition to #4970, this PR fixes up a few things on the logviewer search result view.

#### Search input icons are badly placed

How it currently looks:

image

With this PR applied it looks like this:

image

#### "Save search" name input is really small

How it currently looks:

image

With this PR applied it looks like this:

image

### CODE REVIEW

**Comment by bjarnef** [comment]
@kjac I think it was intended the "example searches" dropdown was placed at right in the input next to the search button. Previously it was placed there.
https://github.com/umbraco/Umbraco-CMS/issues/4656
https://github.com/umbraco/Umbraco-CMS/issues/4343

**Comment by kjac** [comment]
Oh! Whaddya know! I'll have a look at mending that.

**Comment by warrenbuckley** [comment]
@kjac let me know when this is ready for a review and I will take a look :)

**Comment by kjac** [comment]
@warrenbuckley ready - it should look like this now:

image

I have taken the liberty of renaming "Example Searches" to "Saved Searches" because that's what they really are 😄 

#4343 is not fixed by this PR.

**Comment by warrenbuckley** [comment]
Code changes look fine - just got to clone it down and take it for a quick spin.

**Comment by warrenbuckley** [comment]
This looks fine thanks for the tidy up @kjac 💪

**Pull request merged**
