### PR TITLE
Fixes issue: U4-11416 - Better formatting for the video tiles in the developer section.

### PR DESCRIPTION
**Pull request by readingdancer**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org/issue/U4-11416

### Description

I have changed the formatting of the video tiles on the Get Started tab of the developers section so that they now wrap nicely, always have equal heights and on mobile they change to a single column list with the icon on the left side. ( currently the formatting was completely broken on mobile )

#### How it currently looks on mobile:

before-mobile

#### How it looks with this pull request:

after-mobile

#### How it currently looks on a desktop:
screenshot 2

#### How it looks on a desktop with the pull request:
screenshot 5

### CODE REVIEW

**Comment by abjerner** [comment]
@readingdancer This looks awesome - thanks for creating the pull request 👍 

UI wise this is definitely a change for the better. But I'm wondering what's the reason for changing each title from an anchor element to a div with a click event?

IMO click events are a bit bad for UX  - for instance users will no longer be able right click and open the link in a new tab. The anchor element also had `target="_blank"`, so it would open in a new window/tab by default, whereas the click event will just use the same tab.

Anders Bjerner,
Community PR Team

**Comment by readingdancer** [comment]
Hi @abjerner 
Originally I removed this as I couldn't get the darn thing to flex nicely with the horizontal height. However now it's all working I've managed to switch it back and it's working fine :)

The pull request has been  updated as appropriate.

Something seems to have gone strangely wrong with my rebase, hence it's showing multiple commits, but the end result is fine. If anyone can point me in the direction of instructions how I can squash these commits before a pull request, that would be really useful ;)

Chris

**Comment by nul800sebastiaan** [comment]
We can squash it while merging, no worries!

image

**Comment by readingdancer** [comment]
@abjerner & @nul800sebastiaan 

Just realised I had not added the target="_blank" back in, this has now been done.

Unless there is anything else, I think I've finished for now :)

Chris

**Comment by abjerner** [comment]
@readingdancer Awesome. Good work ;)

Actually there is one tiny thing that I forgot about earlier as it wasn't there in the first place. But any link with `target="_blank"` should ideally have `rel="noopener"` as well for security reasons.

You can read a bit more about why that is here: https://mathiasbynens.github.io/rel-noopener/

Otherwise I think your code looks good - I'll try to give it a spin when I get home from work ;)

**Comment by abjerner** [comment]
👍

**Comment by readingdancer** [comment]
Unless you actually have a wide screen monitor, you might not appreciate how huge these icons looked when you have your browser at full screen size :)

#### This is what a 3440x1440 screen looked like before:
before

#### This is what it looks like now:
after

**Comment by readingdancer** [comment]
@nul800sebastiaan do you have any idea if @UmbracoHQ have got the original design files for these icons? If so, any chance we could get them as SVG images instead as these would be a lot smaller and would render so much better on the different screen sizes.

**Comment by nul800sebastiaan** [comment]
We don't..

**Comment by readingdancer** [comment]
Ah... that's a shame.

**Comment by nul800sebastiaan** [comment]
No need to overcomplicate it for now, we might also start changing them some time soon!

**Pull request merged**
