### PR TITLE
U4-11367 - Show trashbin icon again

### PR DESCRIPTION
**Pull request by AndersBrohus**
### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description

Found this issue and though it was an easy one for me to fix - http://issues.umbraco.org/issue/U4-11367 - After looking through older releases i found the source of the problem, the "position:relative;" was removed, so i tried putting it in again, and i haven't found any issues after :)

### CODE REVIEW

**Comment by dawoe** [comment]
Hi Anders,

Thanks for this PR..will try to have a look on Sunday or monday to test your fix.

Will get back at you.

**Comment by AndersBrohus** [comment]
Hi Dave :)

Sounds great, looking forward to hear from you :)

**Comment by dawoe** [comment]
Hi @AndersBrohus 

I have tested this PR and I can confirm the delete icon is back. So nice job.

Maybe @madsrasmussen can have a look. I know he made the change that introduced the bug. As far as I can see it was related to scrolling and tour functionality in PR #2330 

@nul800sebastiaan for me this looks OK

**Comment by AndersBrohus** [comment]
Thanks alot :)

Looking forward hearing if i need to make any changes :)

**Comment by nul800sebastiaan** [comment]
👍 good stuff, thanks!

**Pull request merged**
