### PR TITLE
Merged Nested Content property value converters

### PR DESCRIPTION
**Pull request by ronaldbarendse**
Instead of having 2 property value converters for Nested Content (one handling single `IPublishedContent` and the other multiple/many items as `IEnumerable<IPublishedContent>`), I've merged them to a single PVC: `NestedContentValueConverter`.

As per PR #2918, I've also added the `DefaultPropertyValueConverter` attribute, so custom implementations are now possible. This should make it possible to, for example, filter out items with the property `umbracoNaviHide` checked, instead of having to do this in your views (using the `.IsVisible()` extension method). Having a single PVC also makes this scenario easier!

Regarding a possible breaking change: the previous classes could not be inherited, because that would throw an error saying multiple PVCs for the same editor are found. The PVCs are also dynamically added/resolved, so no direct references to the classes should exist... Maybe @Shazwazza or @zpqrtbnk (or anyone else at HQ) can give a definitive answer on this?

Connected to #2925

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @ronaldbarendse ,

Many thanks for the PR. We shall try and review the PR soon and feedback. How did you test this? Can you add your comments?

Regards,
Poornima, [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by ronaldbarendse** [comment]
I didn't test it yet, just did a quick edit and build 😇

After setting up a new install using the starter kit, I did get an error because the `JsonValueConverter` was also registered as default PVC (Nested Content stores it's value as JSON and that converter automatically registers itself for all JSON values). After shadowing the converter, this error is now fixed 🎉

**Comment by ronaldbarendse** [comment]
I've updated the linked issue (#2925) and think we should continue the discussion there!

**Comment by nul800sebastiaan** [comment]
Hey there @ronaldbarendse !

I'm writing today after announcing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Pull request closed without merging**
