### PR TITLE
U4-5572 - Sanitize default media item names, when dragging/drop.

### PR DESCRIPTION
**Pull request by OptimisticCoder**
Pascal casing, replace underscores and remove file extension.
http://issues.umbraco.org/issue/U4-5572

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
FYI: There was recently some contention about this because we already do this for the name of the file actually on disk. We may not want this for reasons that people are now expecting and in fact relying on the name of the media item being the exact filename.

**Comment by OptimisticCoder** [comment]
It could be an option configurable in umbracoSettings maybe?

**Comment by DanDiplo** [comment]
Files used to be sanitized like this in Umbraco 6 media settings, so I think if anything the v7 was the change and this is just putting it back to how it should be. I know a lot of sites use the media item name for things like alt text on images etc. However, I find most editors cannot be bothered going through and renaming every single file they have uploaded; therefore you end up with poor alt text which is also poor for SEO. I can't see any circumstance where I or any client would want the current behaviour.

**Comment by Shazwazza** [comment]
I guess the title of this and the issue is a bit misleading, i've updated the title of the issue to be more accurate. This simply has to do with naming the media item's name based on the file name, not really anything to do with the file name. We already sanitize the file name to ensure that it meets the legal file naming requirements. 

I'll have to manually merge this stuff in since quite a lot has changed since then but the change will not change the physical file name - apart from the normal legal sanitization, this will just ensure that the media item's name is nicer.

**Comment by Shazwazza** [comment]
Hi all, I've updated the issue with implementation details: http://issues.umbraco.org/issue/U4-5572

Lets discuss it there, I've scheduled for this to be in 7.4.1 release and marked as 'up for grabs'. I'll close this PR however because it is quite out of date from the current codebase. Please open a new PR when ready, thanks!

**Pull request closed without merging**
