### PR TITLE
U4-8548: Images preview while sorting items

### PR DESCRIPTION
**Pull request by mzajkowski**
Enabled preview for images while sorting items in dialog. Default icons are set up for folders and files other than images. Quick and easy fix for aspx user controls until it will be rebuild in the next major release.

### CODE REVIEW

**Comment by clausjensen** [comment]
@mzajkowski Could you create an issue for this on the tracker, please? Thanks :)

**Comment by mzajkowski** [comment]
@clausjensen there is an issue for that, sorry for not including it inside the description: http://issues.umbraco.org/issue/U4-8548

**Comment by clausjensen** [comment]
@mzajkowski Thanks a lot :) Just making sure we have all PR's matched up with issues so they don't get lost!

**Comment by nul800sebastiaan** [comment]
Hey there @mzajkowski!

I'm writing today after anouncing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Pull request closed without merging**
