### PR TITLE
Out-of-date models status flag is created when using SourceCodeManual and Development Runtime

### LINKED ISSUE #14965: No OOD.flag is created when using SourceCodeManual and Development Runtime
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

11.4.2

### Bug summary

When using SourceCodeManual and Umbraco:CMS:Runtime is set to Development, notificationhandlers for generating ood.flag is never registered, which means ModelsBuilder wont detect changes to content models or types.

### Specifics

In src\Umbraco.Web.Common\ModelsBuilder\DependencyInjection\UmbracoBuilderDependencyInjectionExtensions.cs line 111 to 131 different notificationhandlers are registered. OutOfDateModelsStatus is only registered for BackofficeDevelopment, which means you can end up with a modelsbuilder (and developer) that think it's registered for SourceCodeManual  and OutOfDate flagging, but no changes are ever reported.

### Steps to reproduce

In appsettings, set:

    "Umbraco":  {
        "CMS": {
         ...
        "Runtime": "Development",

        "ModelsBuilder": {

             "FlagOutOfDateModels": true,

             "ModelsMode": "SourceCodeManual"

         }
    ....

When changing documents or types, no OOD.flag file will be generated and models builder will look like this:

image

 

### Expected result / actual result

When chaning content type or data types, we expect to see:

image

and a ood.flag file created in the published models folder.

Adding:

            builder.AddNotificationHandler<ContentTypeCacheRefresherNotification, OutOfDateModelsStatus>();
            builder.AddNotificationHandler<DataTypeCacheRefresherNotification, OutOfDateModelsStatus>();

to:

        if (builder.Config.GetRuntimeMode() != RuntimeMode.Production)
        {
            // Configure service to allow models generation
            builder.AddNotificationHandler<ServerVariablesParsingNotification, ModelsBuilderNotificationHandler>();
            builder.AddNotificationHandler<TemplateSavingNotification, ModelsBuilderNotificationHandler>();

            builder.AddNotificationHandler<UmbracoApplicationStartingNotification, AutoModelsNotificationHandler>();
            builder.AddNotificationHandler<UmbracoRequestEndNotification, AutoModelsNotificationHandler>();
            builder.AddNotificationHandler<ContentTypeCacheRefresherNotification, AutoModelsNotificationHandler>();
            builder.AddNotificationHandler<DataTypeCacheRefresherNotification, AutoModelsNotificationHandler>();
        }

Will fix this issue.

### PR DESCRIPTION
**Pull request by jannikanker**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description
This PR is in draft as I 1) need verification that this is a code bug and not a documentation bug, and 2) need to test a bit more before finalizing.

Should fix #14965 by implementing the change proposed in that same issue.

Test by following the steps to reproduce and verify that the ood.flag file is created upon changing a document type.

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi @jannikanker 

Thanks for the PR, which should fix #14965.

I see this is still in draft, so please let us know once it is ready for review and one of the Core Collaborators team will review it! 

And also, feel free to reach out if you need any help to get this out of draft 🙂 

Best regards

Emma

**Comment by jannikanker** [comment]
> Hi @jannikanker 
> 
> Thanks for the PR, which should fix #14965.
> 
> I see this is still in draft, so please let us know once it is ready for review and one of the Core Collaborators team will review it! 
> 
> And also, feel free to reach out if you need any help to get this out of draft 🙂 
> 
> Best regards
> 
> Emma

Ah, okay. So I should just complete the PR and wait for a Core Collaborator to determine whether it's go or no go? Will do, thanks :-)

**Review by ronaldbarendse — APPROVED** [review]
Thanks for creating the fix @jannikanker (and @splab for raising the issue) 💪🏻 The OOD flag should indeed get written in both `BackofficeDevelopment` and `Development` runtime mode...

I did remove duplicate adding of the `OutOfDateModelsStatus` handlers though, so they are now only added when not in `Production` runtime mode, since that can only use ModelsBuilder mode `Nothing` and therefore does not require keeping track of this. Both other development modes can use the manual ModelBuilder modes, which will require these handlers 👍🏻

**Comment by ronaldbarendse** [comment]
As a workaround, you can add the following composer to your project to ensure the handlers are also added in `Development` runtime mode:
```c#
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.Configuration.Models;
using Umbraco.Cms.Core.Notifications;
using Umbraco.Cms.Infrastructure.ModelsBuilder;

public class OutOfDateModelsStatusComposer : IComposer
{
    public void Compose(IUmbracoBuilder builder)
    {
        if (builder.Config.GetRuntimeMode() == RuntimeMode.Development)
        {
            builder.AddNotificationHandler<ContentTypeCacheRefresherNotification, OutOfDateModelsStatus>();
            builder.AddNotificationHandler<DataTypeCacheRefresherNotification, OutOfDateModelsStatus>();
        }
    }
}
```

Make sure to remove this composer again after updating to a version that contains this fix, as the handlers would otherwise be added more than once.

**Pull request merged**
