### PR TITLE
V8/feature/0000 remove out icon

### PR DESCRIPTION
**Pull request by nielslyngsoe**
General style adjustments, getting rid of some visual noise, including:

- Removing the out-icon for Links in Content-Into-tab and Media-Info-Tab.
- using umb-outline for links.
- added round corners and corrected colors for Links.
- adjust the style for XS badges.
- changes User badge to use XS.

### CODE REVIEW

**Comment by warrenbuckley** [comment]
All good :)

**Comment by bjarnef** [comment]
@nielslyngsoe it seems something has gone wrong in this PR, which has introduced `historyLabelKey` and removed `historyLabel` variable. However it is still using the `historyLabel` in the component view: https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web.UI.Client/src/views/components/content/umb-content-node-info.html#L46 which I can't see have been replaced in this PR.

**Comment by bjarnef** [comment]
Strange, I tried replacing with the following in the view:

```
<umb-box-header title="{{historyLabel}}">
   ...
</umb-box-header>
```

It seems localize the title attribute, but not rendering the label text inside the component, which should use the `title` property.

image

**Comment by bjarnef** [comment]
Also when using `title-key` it doesn't seem to work as expected.

image

**Comment by bjarnef** [comment]
Using e.g. `general_history` directly in view seems to work fine though.

```
<umb-box-header title-key="general_history">
       ...
</umb-box-header>
```

image

**Comment by bjarnef** [comment]
It seems it is rendering the `<umb-box-header>` before the `historyLabelKey` binding is ready.

When `title` it only seems to render a regular `title` attribute on the `<umb-box-header>`. Not sure if something in Angular v1.8.0 regarding this?

**Pull request merged**
