### PR TITLE
V8: Don't send notifications for children of the subscribed entity

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

When subscribing to notifications for a content entity, you're notified about the same actions on all children. 

For example if I have subscribed to publish notifications for some content with children and I do a "publish with descendants" on the content with another user, I am notified about the publish action being performed on the content - *and* on every last one of the children! Likewise I'll receive notifications when any of the children are published independently of the content I've subscribed to.

It seems the notification service is deliberately coded this way, but it really does not make any sense, so this PR removes it. When this PR is applied, notifications are only sent if the applicable actions are performed on the content entity you have subscribed to.

#### Testing this PR

1. Create two users - A and B.
2. Subscribe user A to the publish events on a content item that has children.
3. Let user B publish the content item and all its children (including draft versions too). Verify that user A is notified only about the content item being published - not any of the children.
4. Let user B make some changes on one of the children and publish it. Verify that user A does *not* receive any publish notification.

### CODE REVIEW

**Comment by emmaburstow** [comment]
Morning! Thanks for the work Kenn. We'll take a look and let you know if there's anything we need from you.

Em

**Comment by nul800sebastiaan** [comment]
Yeah, so.. the thing is.. it would be extremely annoying to have to set up permissions on all 2000 subnodes if you just want to know that any node in the tree has been updated somehow. The notifications setup indeed purposely applies to the current node + all descendants. 

Need to have a think about how we can make this a choice. 🤔

**Comment by kjac** [comment]
Haha well I'm two lines away from pushing a similar PR for V7 😆 so I guess we'll have to think about it times two!

**Comment by kjac** [comment]
Anyway... I suppose it's equally annoying to receive 2000 notifications for all children when you move the node you subscribed to. Possibly even more annoying 🤔

**Comment by kjac** [comment]
PR updated with latest v8/dev

**Pull request closed without merging**
