### PR TITLE
Bugfix/umbraco backoffice icon #10192

### PR DESCRIPTION
**Pull request by harikrishna43**
Added
If there's an existing issue for this PR then this fixes 
https://github.com/umbraco/Umbraco-CMS/issues/10192
### Description
added Umbraco icon for icon picker

image

### CODE REVIEW

**Review by mikecp — APPROVED** [review]

**Comment by mikecp** [comment]
Thanks for this addition @harikrishna43 👍 
It was indeed a shame to not have the Umbraco icon in there 😁

And a big congratulations and H5YR on your first contribution to the Umbraco CMS repository 🎉🎉
@nul800sebastiaan will be happy to add a contributor's badge to your profile!

**Comment by harikrishna43** [comment]
Thanks @mikecp .

**Comment by nul800sebastiaan** [comment]
Thanks for the addition @harikrishna43 and congrats on your shiny new Contributor badge on your profile: https://our.umbraco.com/members/id:274761/ 🎖

**Comment by harikrishna43** [comment]
Thanks @nul800sebastiaan

**Pull request merged**
