### PR TITLE
Required on view models

### PR DESCRIPTION
**Pull request by bergmania**
This PR adds RequiredAttribute on viewmodels, because swagger ignore the non-nullable types, if we add a default value.

The client needs to be updated before this is merged

### CODE REVIEW

**Review by iOvergaard — APPROVED** [review]
The models look good, but we have a lot of places to fix in the client code, which should probably happen first before merge.

**Comment by bergmania** [comment]
Just let me know and then you can update the client om this branch before merging

**Comment by madsrasmussen** [comment]
@bergmania This one is approved on the client side. Do we need to make any changes before merging?

**Comment by bergmania** [comment]
Everything should be good to go now

**Pull request merged**
