### PR TITLE
Add copy logic to Media Picker

### PR DESCRIPTION
**Pull request by patrickdemooij9**
If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9948

Added a copy action to the media picker. Here is a video showing it:
imageCopy

### CODE REVIEW

**Comment by nathanwoulfe** [comment]
Hey @patrickdemooij9  this looks really cool, will try to find some time to give it the attention it deserves 😃

**Comment by nathanwoulfe** [comment]
@patrickdemooij9 I'm seeing an issue where the image on the clipboard is set as selected, and can't be de-selected. To reproduce:
- select image in picker
- copy
- open second media picker
- select from clipboard
- copied image is set as selected, can't be deselected (and can't be inserted, due to being marked as selected)

Would you mind taking a look?

**Comment by patrickdemooij9** [comment]
@nathanwoulfe. It has been fixed!

**Comment by nathanwoulfe** [comment]
Thanks @patrickdemooij9, will try to get to this today. 👍

**Review by nathanwoulfe — APPROVED** [review]
Updates work great, thanks @patrickdemooij9

**Comment by nul800sebastiaan** [comment]
Hello @patrickdemooij9 and @nathanwoulfe! Really cool work here and we LOVE the feature ❤️ 

In fact, we even loved it before you started working on it, so much so that we'd already made this a feature while working on the upcoming v3 of the media picker! https://github.com/umbraco/Umbraco-CMS/pull/9461

It's a bit unfortunate that the frontend team didn't know this PR was going on and that you both didn't know that the frontend team was working on this. 🙈 
I've reverted this PR, a shame that we didn't spot this earlier, sorry about that! Luckily, the good news is that we'll have a copy feature soon, couldn't make it into 8.13 but we're getting it ready  and it will be in 8.14 instead.

Thanks both for your hard work on this, great stuff! 🌟  Apologies again for having to revert this.

**Pull request merged**
