### PR TITLE
U4-7561 Backoffice Media Section should provide information on physic…

### PR DESCRIPTION
**Pull request by nul800sebastiaan**
…al location of files

This works for all media types that have a property with alias `umbracoFile` and if the value stored in that is either a string (upload field) or a cropper. The `GetCropUrl` method will detect the difference and give a url back.

### CODE REVIEW

**Comment by Nicholas-Westby** [comment]
It seems strange that you have hardcoded the string "umbracoFile". This should probably be part of the umbracoSettings.config file: https://our.umbraco.org/documentation/reference/config/umbracosettings/

imaging

Another thing to note is that this configuration should allow you to specify multiple file fields (e.g., one could do "primaryFile", "secondaryFile", "tabletFile", and so on), though your commit only handles one of the possible cases.

**Comment by nul800sebastiaan** [comment]
@Nicholas-Westby  Minimal Viable Product :-) Changed to at least use the Constant for "umbracoFile". 
Umbraco installs the media types by default to have this alias, the issue was asking for an easy way to access a file url now that it is a cropper by default for new installs. We can expand on this further once this PR gets accepted.

**Comment by nul800sebastiaan** [comment]
Come to think of it, that setting is actually quite cool! I'm going to use that in the code.. and see if I  can make it a comma separated value as well.

**Comment by nul800sebastiaan** [comment]
Nice, we can already provide multiple aliases in that section, so this will work:

```
      <autoFillImageProperties>
        <uploadField alias="umbracoFile">
          <widthFieldAlias>umbracoWidth</widthFieldAlias>
          <heightFieldAlias>umbracoHeight</heightFieldAlias>
          <lengthFieldAlias>umbracoBytes</lengthFieldAlias>
          <extensionFieldAlias>umbracoExtension</extensionFieldAlias>
        </uploadField>
        <uploadField alias="umbracoFile2">
          <widthFieldAlias>umbracoWidth2</widthFieldAlias>
          <heightFieldAlias>umbracoHeight2</heightFieldAlias>
          <lengthFieldAlias>umbracoBytes2</lengthFieldAlias>
          <extensionFieldAlias>umbracoExtension2</extensionFieldAlias>
        </uploadField>
      </autoFillImageProperties>  
```

**Comment by nul800sebastiaan** [comment]
That was easy, all updated and using that config now, thanks for pointing it out @Nicholas-Westby !

**Comment by Nicholas-Westby** [comment]
It appears as if you are still referencing the "umbracoFile", albeit through a constant: https://github.com/umbraco/Umbraco-CMS/pull/1015/files#diff-39df3164649c0f55bc9fbc55852fa173R140

That line says:

```
if (media.Properties.FirstOrDefault(x => x.Alias == Constants.Conventions.Media.File) != null)
```

Within that if statement, you then enumerate the image properties:

```
var autoFillProperties = UmbracoConfig.For.UmbracoSettings().Content.ImageAutoFillProperties;
    foreach (var field in autoFillProperties)
```

That does not make sense, as your code that loops over all image properties defined in the config would only happen to run if somebody also has "umbracoFile" defined on the media item.

It might also be worth pointing out that one could potentially create multiple media types, and each of those media types could have only a subset of the image properties configured in the umbracoSettings.config file (i.e., I'm not sure if your code accounts for the possibility that those properties may not exist on the media item you are working with in particular).

**Comment by nul800sebastiaan** [comment]
Duh! Of course.. :+1: fixing!

**Pull request merged**
