### PR TITLE
Support custom SVG icon in listview

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/10339

### Description
If using custom SVG icons for document types these wasn't shown in listview table or grid layouts.
In fact it would also be an issue if using the e.g. `<umb-table>` component in a dashboard with custom SVG icons. 

otQWs86UQx

image

---
_This item has been added to our backlog [AB#12147](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/12147)_

### CODE REVIEW

**Comment by bjarnef** [comment]
I also noticed it was an issue in the various create dialog for content, media and member if using custom SVG icons.

image

**Comment by bjarnef** [comment]
@nul800sebastiaan these would also be great to fix 😁

**Comment by bjarnef** [comment]
@nul800sebastiaan can you add the labels for this one as well? 👍

**Comment by bjarnef** [comment]
This should also fix a custom icon set on a user group, which currently doesn't work.

image

**Review by nathanwoulfe — APPROVED** [review]
All works perfectly, I'm seeing SVGs everywhere I'd expect to see SVGs. I've merged latest v8/contrib to re-run the test suite, hopefully that fixes the failure. Will merge this when I see all green ticks ✔️ ✔️ ✔️

**Pull request merged**
