### PR TITLE
Add "Move" option for deleted items in the media tree

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

This PR is the media tree equivalent to #3772. It adds move capability inline in the restore dialog if an item in the media tree can't be restored automatically to its original location.

### Testing this PR

1. Delete a folder with some items in it.
2. Attempt to restore one of the items from the recycle bin.
3. Verify that you're prompted to move it manually and that you can do so directly in the restore dialog.
4. Attempt to restore the folder.
5. Verify that the folder can be restored automatically to its original location in the tree.

It looks like this:

media-restore-move

🎄 20/24 🎄

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @kjac ,

Thanks! Lets test and get back to you :-)

Poornima

**Comment by kjac** [comment]
Yay 🎉

**Comment by kjac** [comment]
Super. If by merging you mean to V8, I already promised to do it by hand @ #3931 😄

**Comment by nul800sebastiaan** [comment]
Sweet, this all works as expected, thanks again @kjac !

**Pull request merged**
