### PR TITLE
V8: Add option to create nonclustered primary keys using ICreateBuilder

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5229

### Description

This PR makes it possible to specify if the primary key on a table should be created as clustered (default) or not. See #5229 for more details.

#### Testing this PR

It's not the easiest PR to test. 

First and foremost you need a site running on SQL Server, as SQL CE doesn't support clustered keys at all.

Then you need to inject a migration that actually creates a table - perhaps @mattbrailsford can help here. I have tested it by manually injecting this migration into the core upgrade plan:

```cs
public class TestNonClusteredPrimaryKey : MigrationBase
{
  public TestNonClusteredPrimaryKey(IMigrationContext context) : base(context)
  { }

  public override void Migrate()
  {
    Create.Table("testNonClusteredPrimaryKey")
      .WithColumn("id").AsGuid().NotNullable()
      .WithColumn("test").AsString(512).NotNullable()
      .Do();

    Create.PrimaryKey("PK_testNonClusteredPrimaryKey", clustered: false)
      .OnTable("testNonClusteredPrimaryKey")
      .Column("id")
      .Do();
  }
}
```

### CODE REVIEW

**Comment by emmaburstow** [comment]
"It's not the easiest PR to test" 😆 

Thanks @kjac - we'll let you know if we need anything,

Em

**Comment by nul800sebastiaan** [comment]
Ah you DID warn it wasn't the easiest to test. Good thing I did though since it was missing a small detail, SQL defaults to clustered indexes (at least.. mine did) and therefore you need to explicitly add `NONCLUSTERED` to the query. I've added this now: https://github.com/umbraco/Umbraco-CMS/pull/5261/files#diff-fd49d883e9c39e8f4153c46b9186b32bR24

This generates: `ALTER TABLE [testNonClusteredPrimaryKey] ADD CONSTRAINT [PK_testNonClusteredPrimaryKey] PRIMARY KEY NONCLUSTERED ([id])` 

And my key looks good: 

image


For reference, this is the hacky code I used to run the migration from App_Code:

```
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Core.Logging;
using Umbraco.Core.Migrations;
using Umbraco.Core.Migrations.Upgrade;
using Umbraco.Core.Scoping;
using Umbraco.Core.Services;

public class MigrationCreateTables : MigrationBase
{
    public MigrationCreateTables(IMigrationContext context)
        : base(context)
    { }

    public override void Migrate()
    {
        base.Logger.Debug<MigrationCreateTables>("Before creating table");

        Create.Table("testNonClusteredPrimaryKey")
            .WithColumn("id").AsGuid().NotNullable()
            .WithColumn("test").AsString(512).NotNullable()
            .Do();

        Create.PrimaryKey("PK_testNonClusteredPrimaryKey", clustered: false)
            .OnTable("testNonClusteredPrimaryKey")
            .Column("id")
            .Do();
        base.Logger.Debug<MigrationCreateTables>("After creating table");
    }
}
public class MyMigrationPlan : MigrationPlan
{
    private readonly ILogger logger;
    public MyMigrationPlan(ILogger logger)
        : base("MyApplicationName")
    {
        this.logger = logger;
        logger.Debug<MyMigrationPlan>("Do migration");

        From(string.Empty)
            .To<MigrationCreateTables>("first-migration");
    }
}

public class MyCustomComponent : IComponent
{
    private readonly IScopeProvider scopeProvider;
    private readonly IMigrationBuilder migrationBuilder;
    private readonly IKeyValueService keyValueService;
    private readonly ILogger logger;

    public MyCustomComponent(
        IScopeProvider scopeProvider,
        IMigrationBuilder migrationBuilder,
        IKeyValueService keyValueService,
        ILogger logger)
    {
        this.scopeProvider = scopeProvider;
        this.migrationBuilder = migrationBuilder;
        this.keyValueService = keyValueService;
        this.logger = logger;
    }

    public void Initialize()
    {
        // perform any upgrades (as needed)

        logger.Debug<MyMigrationPlan>("Initialize");

        var upgrader = new Upgrader(new MyMigrationPlan(logger));
        upgrader.Execute(scopeProvider, migrationBuilder, keyValueService, logger);

        logger.Debug<MyMigrationPlan>("After execute");
    }

    public void Terminate()
    {
    }
}

public class MyAppComposer : IUserComposer
{
    public void Compose(Composition composition)
    {
        // component for startup
        composition.Components()
            .Append<MyCustomComponent>();
    }
}
```

**Comment by kjac** [comment]
@nul800sebastiaan good stuff 🏅 I simplified the conditional clustered/nonclustered constraint building a bit, but the logic remains the same as your change.

**Comment by nul800sebastiaan** [comment]
Perfect, SuperTak! ⭐️

**Pull request merged**
