### PR TITLE
Adding method for copying on IContentService without copying children

### PR DESCRIPTION
**Pull request by steentottrup**
Adding the option to copy ONLY the given content, without any children.

New Copy method created on ContentService, with an additional argument, for whether or not to copy recursively.

### CODE REVIEW

**Comment by jacan** [comment]
Soooo.... What's the holdup?

**Comment by nul800sebastiaan** [comment]
https://twitter.com/paulsterling/status/638963051853676544 :-)

**Comment by zpqrtbnk** [comment]
looking into it

**Comment by Shazwazza** [comment]
All prs need to be associated with an item on the tracker btw.

**Comment by zpqrtbnk** [comment]
Issue http://issues.umbraco.org/issue/U4-7060, manual-merged with http://github.com/Umbraco/Umbraco-CMS/commit/37e6e61eff260c0b415056e271492dddc6469505

**Comment by steentottrup** [comment]
Didn't know an issue was needed, is that documented somewhere? For future reference.

**Comment by paulsterling** [comment]
Yes it is https://our.umbraco.org/contribute/guidelines-for-core-contribution/ The first item we review in the Reviews of code contributions.  Thanks for the PR!

**Comment by Shazwazza** [comment]
Also on our long list of things TODO is revamp, update and simplify that page(s) ;)

**Pull request closed without merging**
