### PR TITLE
HtmlImageSourceParser does not use IImageUrlGenerator

### PR DESCRIPTION
**Pull request by olibos**
Fix proposal for: #8331

* Remove sealed from HtmlImageSourceParser class to allow inheritance.
* Inject `IImageUrlGenerator` to generate Image Crop URL.  

Adds tests for the new feature.

### CODE REVIEW

**Comment by olibos** [comment]
Hello @nul800sebastiaan ,
I don't think the build failed is related to my PR.
Can you have a look?

**Comment by olibos** [comment]
image

**Comment by nul800sebastiaan** [comment]
Sorry about that @olibos - no that was definitely not related to this PR, not to worry! ;-)

**Comment by nul800sebastiaan** [comment]
Just a general note, I know it's hard to resist but please keep the code style that the files came with, it's really hard to review/compare and merge when things move around in the file, I know it looks ugly but try to be more additive and not move things around if they don't need to move. Also.. usings inside the namespace is never good (for us) 😄

**Comment by olibos** [comment]
Sorry for the extra work 😉

**Comment by nul800sebastiaan** [comment]
No worries! I did see a unit test in there which is really awesome!! 🎉🎉

**Pull request closed without merging**
