### PR TITLE
U4-11386 Adding a service worker to the back office to aid performance

### PR DESCRIPTION
**Pull request by Matthew-Wise**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description
http://issues.umbraco.org/issue/U4-11386

Adding a service worker to locally cache the angular template views. This change improves the preserved performance for lower bandwidth users in particular.

Thanks
Matt

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi,

Many thanks for your PR. We shall review your PR within the next 14 days and let you know of the outcome.

Regards,
Poornima (CPR Team)

**Comment by nul800sebastiaan** [comment]
@Matthew-Wise Sorry for the delay on this one, I'm looking for someone to dive into service workers a little bit. Hope we can get to it next week!

**Comment by Nicholas-Westby** [comment]
Two questions:

* **Already Cached?** Aren't things like AngularJS templates cached already by the browser?
* **Less Aggressive Caching?** Will this allow for easy cache busting in development mode? Currently, I think if you're debugging from Visual Studio and/or you have debug="true" in your web.config, some magic happens to ensure caches are more readily invalidated (to aid in quicker development).

**Comment by Matthew-Wise** [comment]
Hi Nicolas,

**Already Cached?** 

Yes they already cached as any page you visit is, however these caches cant not be relied upon and still require a network request, so in cases where a users connection is low (3G etc) for example on a train.

They will avoid the network completely allowing those partial views they have already cached to be loaded in milliseconds.

Less Aggressive Caching? 

The cache keys are set using the same versioning used currently to clear the caches and for debug mode I check this and remove the service worker to ensure it doesn't get in the way.

https://github.com/umbraco/Umbraco-CMS/pull/2670/files#diff-59f6d902e3e44a9455306e7656a47fd9R108

Matt

**Comment by nul800sebastiaan** [comment]
Hey @Matthew-Wise ! We think this is really cool and want to try it out but we feel it's a bit of a risky change at the moment in v7. Would you mind trying again but create this for v8? That way we get more time to experiment and play with it at HQ and see if we run into unforeseen issues.

I'll close this for now and will be happy to see a new PR for v8 if you have some time to try again. Let me know if you need some help or anything getting up and running with v8.

Thanks again! 👍

**Comment by Matthew-Wise** [comment]
No worries @nul800sebastiaan  totally understand Ill review the code again as I move it to v8. All setup as I removed one of the aspx for the v8 hackathon

Matt

**Pull request closed without merging**
