### PR TITLE
V13 Unable to click the user profile in tours introduction

### PR DESCRIPTION
**Pull request by SarojShresthaa**
### Prerequisites

- [  ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes 

### Description
Commented out the line /* focusLockService.addInertAttribute();*/ in the umbtourstep.directive.js file.

### CODE REVIEW

**Comment by lauraneto** [comment]
Hi @SarojShresthaa ,

Thank you for your (first 🎉) pull request! 🙌
Next time please fill in the description of the pull request, especially with a reference to the ticket you are fixing, so we know what the initial issue was and how to test the changes. (this time I was able to find it and link it)

As for the pull request itself, a member of the Core Collaborators team will look into it soon!
In the meantime, it would be nice if you could already check if the failing build is due to your changes, as it is failing on integration tests relating to Tours. If you follow the trail of the build, you will end up [here](https://dev.azure.com/umbraco/Umbraco%20Cms/_build/results?buildId=171524&view=logs&j=1f01615a-c292-5319-2ec9-971d2fa2b6e3&t=6d400299-b333-5850-4192-720b541cd350&l=19096).
If you are unsure, that is no issue, let us know and we can help you out! 🙂

**Comment by SarojShresthaa** [comment]
Hey @lauraneto, I don't think my Changes have made those build error

**Comment by georgebid** [comment]
The same branch has been used to fix #16746 - @ whoever tests this, we will need to make sure 16746 also passes before merging.

**Comment by lauraneto** [comment]
Hi @SarojShresthaa,
It looks like there are changes in this PR that are not related to the initial issue.
When working on an issue you should create a different branch (from `contrib`) per issue so that we can test and merge your changes in isolation, otherwise it gets too hard to manage (every time you make another fix, it shows up in this PR as well).
For now, I will close this PR, but if possible please create a new one with only the changes for the reported issue. Thanks! 🙏

**Pull request closed without merging**
