### PR TITLE
Update V8_GETTING_STARTED.md

### PR DESCRIPTION
**Pull request by AndersBrohus**
### Prerequisites

- [ ] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes:

### CODE REVIEW

**Comment by AndersBrohus** [comment]
That went too fast :)

Just updated the Getting Started with a new link to V8 instead of temp8_cg18 :)

**Comment by nul800sebastiaan** [comment]
Hey @AndersBrohus - this fil

**Comment by nul800sebastiaan** [comment]
Whoops, keyboard fail 😅😅

Instead, this file will get deleted soon since the relevant info should just be in the normal contributing guidelines, thanks for the help though! 👍

**Comment by AndersBrohus** [comment]
Thanks for the answer! 😄

**Pull request closed without merging**
