### PR TITLE
V8/feature/block list hide content in overlay option

### PR DESCRIPTION
**Pull request by nielslyngsoe**
Was suporse to be named: "v8/feature/block-list-hideContentInOverlay-option".
This PR is adding the ability to hide the content editor from the infinite editing overlay in the Block List property editor.
The content editor is already hidden if the editor is set to inline mode. But for the default mode, this enables the specific block type to force the content editor to be hidden. This is preferred if the custom view for the given block type delivers a UI that provides editing of the content.

### CODE REVIEW

**Comment by warrenbuckley** [comment]
@nielslyngsoe when you get a chance, can you please fix the merge conflict up for me.

**Comment by nielslyngsoe** [comment]
@warrenbuckley up to date :-)

**Comment by warrenbuckley** [comment]
@nielslyngsoe so maybe it should not open at all or give me a specific error/UX message as to why it's empty

image

**Comment by nielslyngsoe** [comment]
This PR has turned bad in merge conflicts. so made a new one:
https://github.com/umbraco/Umbraco-CMS/pull/8368

**Pull request closed without merging**
