### PR TITLE
Fix null language in variant change event

### PR DESCRIPTION
**Pull request by nathanwoulfe**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

Resolves issue #8355 where language is null on invariant content, so attempting to access language.culture throws an exception. Changed to pass the language object as the event data, rather than language.culture

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
@nathanwoulfe Thanks! I know this will fix the error but semantically it looks a bit weird: has the culture actually changed if there is no culture?

**Comment by nathanwoulfe** [comment]
@nul800sebastiaan if a tree falls in the forest... I can wrap the event in a variant length check - if there's more than one variant, the culture has changed. That would also have been a solution for language.culture being null (but still makes better sense to emit the entire language object rather than just the culture property).

Hold the line caller, I'll update.

**Comment by nul800sebastiaan** [comment]
@nathanwoulfe I'm also happy with always emitting the language, but then the event needs to be renamed! 🙂

**Comment by nul800sebastiaan** [comment]
All good like this as well, thanks @nathanwoulfe 👍

**Pull request merged**
