### PR TITLE
Accessibility: Open User Details - Back icon arrow is identified as "Umbraco link"

### PR DESCRIPTION
**Pull request by BatJan**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

This PR then this fixes issue 111 from #5277

### Description
This PR ensures that the text "Back" is read out to screen readers and the <a> tag has been replaced with a <button> tag, which fixes the button no longer being mentioned as an "Umbraco link" in a screen reader.

It is the button being shown in the users section when editing either groups or user profiles as shown in the images below.

user-profile-settings

user-group-settings

### CODE REVIEW

**Comment by emmaburstow** [comment]
Thanks Jan! Great bit of optimisation for a screen reader. These are always fun to test 😂 

Em

**Comment by BatJan** [comment]
Yeah, we kinda need to figure out if we're actually using them right 😃

**Comment by nul800sebastiaan** [comment]
Lovely updates @BatJan 👍 Thanks!

**Comment by nul800sebastiaan** [comment]
image

🥇

**Pull request merged**
