### PR TITLE
v8: Fix package options view

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes: https://github.com/umbraco/Umbraco-CMS/issues/4409

### Description
This PR filter the tree when selecting "Package options view" in a created package. Not sure which file extensions that are supported, but since the description mention a `html` file I have allowed only the following: `cshtml`, `vbhtml`, `html` and `htm`.

Also note that this PR https://github.com/umbraco/Umbraco-CMS/pull/4423 fixes the issue where all descendants have `not-allowed` cursor, when e.g. a root folder not is allowed to be picked.

### CODE REVIEW

**Comment by Shazwazza** [comment]
Only html files are allowed for views

**Comment by bjarnef** [comment]
@Shazwazza okay I will update the PR, but I guess `.htm` also will work?

**Comment by kjac** [comment]
I don't get this. Why are we limiting the package contents to view files only? What if the dev wants to bundle up js, css, images or even dll's?

**Comment by Shazwazza** [comment]
Yup I guess htm works too, not sure why mb is like that though

**Comment by bjarnef** [comment]
@Shazwazza the mb dashboard now use `.html` thanks to @zpqrtbnk 🎉
I think it is fine the filter still allow `.htm` if package developers for some reason wants to include that instead of `.html`.

**Comment by nul800sebastiaan** [comment]
Thanks very much, works like a charm! 👍

**Pull request merged**
