### PR TITLE
 Angularize translation pages

### PR DESCRIPTION
**Pull request by ssougnez**
### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description
The goal of this PR is to angularize all "translation related" pages.
**Note that this PR is not yet fully completed but good enough to allow PR team to test it**
**Moreover, for the test sake, I didn't delete anything related to the "old way", so the PR team can easily compare both system**

**Comparison**

Here are some screenshot to compare the old screens with the new one:

old-global
new-global

old-task-1
new-task-1

**Question**

- For the preview of the page once the task is uploaded, I use the preview page of the content section, is that OK? It seems pretty much the same than the translation one. In the sentence displayed in the old screen after an upload, it's written that if the base page exists, a comparison between it and the new one will be displayed but it does not seem to work.
- What's the flow for new label? I added a few key in "en-US.xml" file and I wonder how I get them translated for other languages.

**What now?**

So now, I'll continue cleaning my code and improving it and during this time, PR team can test this this PR and give me a feedback.

### CODE REVIEW

**Comment by dawoe** [comment]
Hi @ssougnez 

Thanks for this PR. Having converted the dictionary section to angular myself I know what amount of work goes in to a change like this.

I will try to review and test this one soon.

Don't know what the plans are with this section from Umbraco HQ. This is a part of the core that has been neglected for too long.

Dave [Community Pull Request team](https://umbraco.com/blog/introducing-the-new-cpr-team/)

**Comment by nul800sebastiaan** [comment]
Looks like an epic task @ssougnez ! And a huge improvement of what we have now, if only because it will now actually load fast and be easier to debug. 

I think it's great that you mostly stuck to the UX that was already available for this, that's the way to go. It will take a bit longer to review this one but it looks like great work so far! 👍

**Comment by ssougnez** [comment]
Cool. As this is mostly done, I won't work on it until your comments, this way, I'll make the final change and apply your comments in a one shot ;-)

**Comment by ssougnez** [comment]
Hi,

do you have an update for that issue?

**Comment by dawoe** [comment]
Hi @ssougnez 

I still have this on my TODO list to review and test. But this is a pretty big one. So will need to free up some time.

Maybe you can already merge in the latest version of dev-v7 so the merge conflicts are resolved.

Dave

**Comment by nul800sebastiaan** [comment]
Hey there @ssougnez !

I'm writing today after announcing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Pull request closed without merging**
