### PR TITLE
3564 - Make reuse of property editors priority over creating new editors

### PR DESCRIPTION
**Pull request by jacklawry**
### Prerequisites
- [x] I have added steps to test this contribution in the description below

### Description
When adding a new property editor it now shows in the updated order so you now reuse the previously created editors by default.

Relates to issue https://github.com/umbraco/Umbraco-CMS/issues/3564

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hiya @jacklawry 

Thanks for the Pr and congrats on your first PR! This definitely needs a bit of discussion so we'll have a chat and let you know what we decide. It's certainly something that's been brought up before. 

Emma

**Comment by jobf** [comment]
This is great, as a new user it is far too easy to create unnecessary data types.

Showing the existing ones by default is massively more intuitive!

**Comment by andyneil** [comment]
This makes total sense. Especially for new people who are unfamiliar the implications of creating new data types. I've accidentally clicked new far too many times only to then have to go back.

**Comment by StefanoChiodino** [comment]
This is great, and tbh only the beginning. The best step would be to not automatically generated a name for it, and have the dev actually think about it. "Homepage - heading - textstring"? No, how about you call it what it is (e.g. "textstring (max 50 characters)"?

This change was a welcome improvement over V4, but in the day to day it empowers juniors to create a property for each field,which is a ridiculous standard.

**Comment by nul800sebastiaan** [comment]
I've commented on the issue on why it is the way it is: https://github.com/umbraco/Umbraco-CMS/issues/3564#issuecomment-444927230

**Comment by nul800sebastiaan** [comment]
Closing in favor of #3836

**Pull request closed without merging**
