### PR TITLE
Fixed url redirect creation issue

### PR DESCRIPTION
**Pull request by bernardmoes**
Issue: https://github.com/umbraco/Umbraco-CMS/issues/3186
Previous PR: https://github.com/umbraco/Umbraco-CMS/pull/3286

This pull requests resolves the issue of the wrong original URL being used for creating redirects when having implemented custom URL providers.

For the creation of redirects, the source of the original url was determined by the route property of the content. Using the url property instead makes the creation of redirects also compatible with custom url providers.

Tested using the custom url provider sebastiaan created when testing the previous pull request. Thanks @nul800sebastiaan 

```
public class CustomUrlProvider : IUrlProvider
    {
        public string GetUrl(UmbracoContext umbracoContext, int id, Uri current, UrlProviderMode mode)
        {
            var content = umbracoContext.ContentCache.GetById(id);

            if (content != null && content.DocumentTypeAlias == "product")
            {
                return   content.Name.ReverseString().ToUrlSegment().EnsureStartsWith("/");
            }

            return null;
        }

        public IEnumerable<string> GetOtherUrls(UmbracoContext umbracoContext, int id, Uri current)
        {
            var content = umbracoContext.ContentCache.GetById(id);

            if (content != null && content.DocumentTypeAlias == "product")
            {
                var urls = new List<string>();

                urls.Add(content.Name.ToUrlSegment().EnsureStartsWith("/"));

                return urls;
            }

            return null;
        }
    }

    public class CustomUrlContentFinder : IContentFinder
    {
        public bool TryFindContent(PublishedContentRequest contentRequest)
        {
            if (contentRequest == null)
                return false;

            var uri = contentRequest.Uri;

            var segments = uri.Segments.Where(x => x != "/").ToList();

            if (segments.Any() && segments.Count == 1)
            {
                var urlPart = segments.First();

                var products = UmbracoContext.Current.ContentCache.GetByXPath("//product[@isDoc]").ToList();

                var matchedProduct = products.FirstOrDefault(x =>
                    x.Name.ReverseString().ToUrlSegment() == urlPart || x.Name.ToUrlSegment() == urlPart);

                if (matchedProduct != null)
                {
                    contentRequest.PublishedContent = matchedProduct;
                    return true;
                }
            }

            return false;
        }
    }

    public class UrlProviderRegistration : ApplicationEventHandler
    {
        protected override void ApplicationStarting(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {
            ContentFinderResolver.Current.InsertTypeBefore<ContentFinderByNotFoundHandlers, CustomUrlContentFinder>();
            UrlProviderResolver.Current.InsertTypeBefore<DefaultUrlProvider, CustomUrlProvider>();
        }
    }
```

### CODE REVIEW

**Comment by bernardmoes** [comment]
@dawoe Thanks for your review. Somehow didn't notice those issues during my testing. I just commited some changes which should resolve all the issues you mentioned. I thoroughly tested this time:

- All previously made redirects are still working
- Formatting of the old url in the database is consistent now. Always relative and without trailing slash.
- Works with and without custom url providers
- Tested different domainprefix and trailingslash settings

Looking forward to your approval

**Comment by bernardmoes** [comment]
@nul800sebastiaan Why is my pull request being ignored? It's been here for over 6 months and no reply, not comment, no nothing.

**Comment by nul800sebastiaan** [comment]
Very sorry @bernardmoes - love the idea of this PR but it kinda fell of my radar after a while 🙈  

Please note we've been having a bigger focus on v8 for the past few months so v7 has been getting lower priority. 

I need some help from others at HQ to make sure this is the correct fix and it's not going to break anything for anyone. 

It's on the todo list and I'll get back to you (it will take a bit of time though).

**Comment by nul800sebastiaan** [comment]
As an update: I've talked to @zpqrtbnk about this and he has concerns about the way this is being fixed and it potentially being a breaking change. More feedback to come.

**Pull request closed without merging**
