### PR TITLE
Restructure docs

### PR DESCRIPTION
**Pull request by tiffy74**
### Prerequisites

[Improve contribution guidanceissue #960](https://github.com/umbraco/UmbracoDocs/issues/960)

### Description
Have completely restructured the documentation in the .github folder.

I have added contents and navigation and gone through each document and added relevant links and navigation where appropriate.

As a result I believe it reads better and has more logical progression for people trying to work their way through the contribution guidance.

Prepared to work on this further as appropriate and collaborate with others on improving guidance where possible.

I have manually tested as much as possible any of the links however if there are any external files that link to this guidance they will also need to be amended

My original issue was submitted to UmbracoDocs as issue #960 however it was in reference to the docs in the Umbraco-CMS project and not to the UmbracoDocs project

### CODE REVIEW

**Comment by emmaburstow** [comment]
Hi @tiffy74 

Congrats on your first PR here! Lots of work here so we'll have a look through and let you know if we need anything from you.

Em

**Comment by nul800sebastiaan** [comment]
Hi there @tiffy74,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing :pray:

If you haven't heard already we have had a record breaking amount of PR's in both the CMS and the Documentation repository. You can read all about the numbers in the [Umbraco Hacktoberfest Aftermath blog post](https://umbraco.com/blog/the-2018-hacktoberfest-aftermath/).

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://goo.gl/forms/smjQwEMDM5cUnz6x1) :point_left: Please follow this link to fill out and submit the form, **before November 21st 2018**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before December, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Comment by tiffy74** [comment]
Hiya

So i've renamed the contributing file back - I didn't really touch the readme and the license files.

I was in 2 minds about numbering the files - it was purely just to order them in a logical manner within the github repo - but tbh that's probably not very important.

Really the intention was to create a logical reading order for the content that was already there - so I can imagine this may not be ready to merge just yet but more than willing to continue to refactor it into a state you are happy with - if you are comfortable with me doing so.

Thanks!

Tiff

**Comment by nul800sebastiaan** [comment]
Hi again @tiffy74  and thanks so much for the efforts here. I just realized this was still open after we've just gone through a big cleanup and consolidation of several readme files. I would love it if you'd give the current versions another glance and see if we've missed anything.

My apologies for not giving your PR the proper timely review, hopefully we can do much better in the future! Many thanks once again and I hope this doesn't put you off from helping out on future contributions! 🙈

**Pull request closed without merging**
