### PR TITLE
Installer adjustments

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description
A few adjustments to installer where some properties in `installerService` get assigned a value `null` instead of `undefined`. Furhermore the anchor element on starterkit view is changed to a `button` element.

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @bjarnef ,

Thanks again for the PR. We shall review it and get back to you :-)

Poornima

**Comment by kjac** [comment]
@bjarnef thanks 👍 could you add some steps to test this, please?

**Comment by bjarnef** [comment]
@kjac the best way to test this is the set `umbracoDbDSN` and `Umbraco.Core.ConfigurationStatus` to empty string in `web.config`, which should trigger the installer.

Then go through the installer steps and ensure Umbraco is installed correct, eventually the step to install a starterkit, where `<a>` element is changed to a `<button>` element.

I saw somewhere @Shazwazza mentioned variables shouldn't be assigned to a `undefined` value since you actually assign a value, where it is better to assign `null`.

**Comment by kjac** [comment]
@bjarnef aah I get it, it's a bit housekeeping + changing that link to a button - thanks, much appreciated 👍

**Comment by bjarnef** [comment]
@kjac did you had a further look at this?

**Comment by kjac** [comment]
@bjarnef I did... I started a review and tagged you in it. Does it not show for you?

**Comment by nul800sebastiaan** [comment]
@kjac I think you only "self-requested a review" but never saved your comment. Let us know if you have anything to add. From my point of view this looks good and the installer works as expected.

Thanks @bjarnef! 👍 

Note: some more stuff for @nathanwoulfe & friends to refactor in due time for #7663

**Pull request merged**
