### PR TITLE
Dependancy Update: Switch to Serilog.Expressions away from deprecated Serilog.Filters.Expressions

### PR DESCRIPTION
**Pull request by warrenbuckley**
This PR adds support for the new/updated Serilog Expressions Nuget package, this is the library that allows users to perform complex searches and query their log data.

The `Serilog.Filters.Expressions` package is deprecated and recommended to upgrade to `Serilog.Expressions`.
https://www.nuget.org/packages/Serilog.Filters.Expressions

## Notes
This PR adds support to backport the Serilog query function `Has()` such as `Has(Duration) and Duration > 1000` it was renamed in the new library to `IsDefined()` but to help with backporting and ensuring existing saved log queries do not break, I have added support for `Has()` and to allow mapping of the more verbose built in property names to the short hand versions

Such as `@MessageTemplate` is now `@mt`

---
_This item has been added to our backlog [AB#17611](https://dev.azure.com/umbraco/243e7927-03b2-44e2-908f-d4ac7ea5daaa/_workitems/edit/17611)_

### CODE REVIEW

**Comment by warrenbuckley** [comment]
Using the dev build of Serilog.Expressions 3.2.2-dev-00083 until 3.3.0 is released from this PR https://github.com/serilog/serilog-expressions/pull/67

This adds support in NameResolvers for a new method to override TryResolveBuiltInPropertyName which fixes the last problem I had which was mapping back the more verbose built in property names to the short hand version.

**Comment by warrenbuckley** [comment]
@bergmania ready for you to review now that Serilog.Expressions 3.3.0 has been released to Nuget

**Review by bergmania — APPROVED** [review]
LGTM 💪

**Comment by deekoulos** [comment]
any idea when this will be released?

**Comment by nathanwoulfe** [comment]
Looks like it's in for v10, which is due June 16.

**Pull request merged**
