### PR TITLE
Temp 5147 hide grid reorder

### LINKED ISSUE #5147: Hide grid reorder when scrolling to end of grid content
By default the grid reorder is positioned static, but get sticky (fixed) when its position reach the bottom of the header. However you can have several properties after the grid content and when scrolling futher down the page the reorder bar remain sticky. Instead it should be hidden when the bottom of the grid content reach the bottom of header.

image

image

Here is an example where the sticky element (in this case a sidebar) moves up, when it reach the footer. https://abouolia.github.io/sticky-sidebar/

### PR DESCRIPTION
**Pull request by nathanwoulfe**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #5147 

### Description

Changes here fix the overly-persistent umbStickyBar directive - currently the directive does all manner of cloning and positioning and scroll sniffing to attach the element top of the container, but does not release the stuck element when the container has scrolled off screen (or out of view). Screenshots in @bjarnef 's issue show this.

Attaching/detaching the umbStickyBar  element is trivial using position:sticky. It sticks when it hits the top, and detaches appropriately too. Issue with sticky is that there isn't an event (or state) to indicate that the element has been stuck.

Enter IntersectionObserver. 👍 

Using IntersectionObserver we can watch for when an element enters or exits another (typically a parent or ancestor). To make that work here, I've rewritten the umbStickyBar directive to add two observed elements as siblings of the umbStickyBar. These 'sentinels' are positioned at the top and bottom of the umbStickyBar's parent element so we can monitor its relative position as the page scrolls.

When the sentinels enter/exit, we toggle a class on the umbStickyBar element, to indicate [in]active state.

All that to add a box-shadow to the umbStickyBar when it is stuck! Sounds like a lot, but compared to the old directive, it's much, much cleaner and should be easier to maintain.

To verify, open a page with a grid editor and scroll. The grid header (with the reorder button) is the umbStickyBar element, and will unstick once the grid has scroll out of view. I've verified this on a grid in a standard editor, on a grid in an infinite editor, and on a list view in an infinite editor (from the homepage node in the starterkit).

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hey @nathanwoulfe ,

Great work! We shall review the PR and get back to you if anything else is needed. Watch this space till then :-)

Poornima

**Comment by nathanwoulfe** [comment]
👍you know where to find me.

**Comment by poornimanayar** [comment]
Hi @nathanwoulfe ,

I have tested this now. I can see that the reorder button hides once you scroll past the grid but I have noticed a console error. It might be my machine but can you double check your end? 

Poornima

**Comment by nathanwoulfe** [comment]
Hi @poornimanayar 

I'll have a look, definitely should not be any console errors...

N

**Comment by nathanwoulfe** [comment]
Ah crap. I rebased.

Will kill this PR, check the console issue, and open a new PR.

**Pull request closed without merging**
