### PR TITLE
Datepicker custom format

### PR DESCRIPTION
**Pull request by Alain-es**

### CODE REVIEW

**Comment by Shazwazza** [comment]
What issue is this solving/related to?

**Comment by Alain-es** [comment]
Datepicker controls display dates by default with the format YYYY-MM-DD. We want to use the format  DD-MM-YYYY. This PR will add a new prevalue field allowing users to customize the format. If no format is provided then the default one is used. Values are always saved with the default Umbraco format YYYY-MM-DD.
This PR includes a fix for the method `$scope.hidePicker = function () ` since sometimes it fails finding the control, and therefore logs errors in the browser console. 

http://issues.umbraco.org/issue/U4-6632

**Comment by Shazwazza** [comment]
Nice one! I'll pull this in and review.

**Comment by Alain-es** [comment]
Great! Thanks

**Pull request merged**
