### PR TITLE
V8: Fix the link picker anchor list

### PR DESCRIPTION
**Pull request by kjac**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/5297

### Description

This PR fixes the link picker anchor dropdown as described in #5297:

image

#### Testing this PR

The only way I found to test this is to insert an anchor link from source view in an RTE and pick the content where that RTE is placed from a link picker or an RTE somewhere else 😄

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
@kjac An easier way to test.. ;-)

image

**Comment by emmaburstow** [comment]
Hey @kjac - try as I might, I just can't get that drop down to appear. I have gone to the Contact page in the starter kit site, entered the contact page as the node to link to from the RTE and the arrow doesn't appear. I've tried entering something into the anchor field and saving and re-opening too. Any advice?

**Comment by kjac** [comment]
Hi @emmaburstow 😄 

You need to:

1. Create an anchor link on page A (either by using the RTE source editor or by enabling anchor link editing as per Sebastiaans comment above).
2. Open the link picker from page B.
3. Pick page A as link target.
4. The anchor link should be in the dropdown?

**Comment by emmaburstow** [comment]
Thanks Kenn! I'll give this a go

**Comment by kjac** [comment]
Haha neither did I until recently 😆

**Comment by nul800sebastiaan** [comment]
Fixed some merge conflicts and this now works wonderfully again, thanks @kjac ! 🎖

**Comment by marcoteodoro** [comment]
@nul800sebastiaan is this supposed to work with when RTE's are inside nested content blocks?

**Pull request merged**
