### PR TITLE
Make sure the configured url provider mode is used when getting a url

### PR DESCRIPTION
**Pull request by dawoe**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

You can configure Umbraco to generate absolute urls out of the box by changing the web.Routing section umbracoSetttings.config file.  You can do this by settting `urlProviderMode="Absolute"`

So by setting this I would expect umbraco to generate absolute urls when I request the url through the url property of a IPublishedContent item.

However on 8.3.0 it still generates relative urls after setting this in the config. This is cased by the default value for mode being Auto on the Url method in PublishedContentExtensions. 

I changed the default value of the mode to UrlMode.Default. And when it is set it will get the mode configured on the url provider. This is backwards compatible because when there is no urlProvider mode configured in the web.Routing section it will default to Auto.

Can this be part of 8.3.1 ? This is blocking me now. I don't want to write a lot of custom code just to have absolute urls

Dave

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Quote from Shannon: 
> I don't think his extra if statement is required though, the mode should just be passed to the UrlProvider.GetUrl which handles the mode in there and already does the default check - you can have a look by following the call into UrlProvider.GetUrl and UrlProvider.GetMediaUrl (both of which have Default as the default)

Other than that I can confirm this is a regression from 8.0 created in 8.1 in this PR: https://github.com/umbraco/Umbraco-CMS/pull/5312

**Comment by dawoe** [comment]
Hi @nul800sebastiaan and @kjac 
I removed the if statement

**Comment by kjac** [comment]
Thanks @dawoe 👍 I'll get on it.

**Comment by kjac** [comment]
Merged 😄 thanks again, @dawoe

**Comment by nul800sebastiaan** [comment]
Note: I've marked this as breaking, not because I think it will break anything but if someone has accidentally been using `Absolute` but not realized that it doesn't do anything, they'll see a bit of different behavior now.

**Pull request merged**
