### PR TITLE
Backwards compatible upgrade to ImageSharp 2

### PR DESCRIPTION
**Pull request by skttl**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #11938

### Description
This upgrades ImageSharp and ImageSharp.Web to 2.0.0 without making breaking changes in Umbracos public API.

ImageSharp.Web 2.0.0 is still unreleased, so WIP until that gets released.

To test, check if image generation works, eg. https://localhost:44331/umbraco/assets/img/login.jpg?width=200&format=webp

### CODE REVIEW

**Comment by maartenmensink** [comment]
@skttl v2.0.0 has been released. Do you need help completing this?

**Comment by skttl** [comment]
Hi @maartenmensink 

ImageSharp.Web 2.0.0 hasn't been released yet: https://www.nuget.org/packages/SixLabors.ImageSharp.Web/

**Comment by maartenmensink** [comment]
> Hi @maartenmensink
> 
> ImageSharp.Web 2.0.0 hasn't been released yet: https://www.nuget.org/packages/SixLabors.ImageSharp.Web/

Yeah sorry about i miss read the package name 🙈. Let me know if i can help when it is released!!! I want this feature back in my life 😄

**Comment by jaddie** [comment]
What's happening with this? If this is the case that its backwards compatible without any breaking changes then it would be great to get this integrated tbh as I was reading about this and its being spoken about for V10 instead which seems a long while off.

**Comment by skttl** [comment]
> What's happening with this? If this is the case that its backwards compatible without any breaking changes then it would be great to get this integrated tbh as I was reading about this and its being spoken about for V10 instead which seems a long while off.

Imagesharp. Web 2 is still not released, and v10 is only a couple of months away, scheduled for release in q1 of 2022

**Comment by ronaldbarendse** [comment]
@skttl Thanks for trying to get this to work in v9, but simply updating a dependency to a new major version is considered a breaking change and because ImageSharp.Web v2 contains breaking changes that Umbraco uses (and is compiled against), upgrading your site to use v2 will throw exceptions during boot.

We might actually want to add an upper dependency version limit to v9, because we now know the newer major version is incompatible 🤔 

Anyway, Umbraco 10 will ship with updated ImageSharp/ImageSharp.Web v2 dependencies (see the progress and details on PR https://github.com/umbraco/Umbraco-CMS/pull/12185), so I'll close this one.

**Pull request closed without merging**
