### PR TITLE
Implementing new colour picker for document types

### PR DESCRIPTION
**Pull request by OwainWilliams**
Changing the dropdown menu for a colour swatch picker

### Prerequisites

- [X] I have written a descriptive pull-request title
- [X] I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description

Remove the dropdown menu of colours from the Document Type icon selector and replace it with a colour swatch option. 

http://issues.umbraco.org/issue/U4-11168

### CODE REVIEW

**Comment by OwainWilliams** [comment]
A known issue which I need help with is, the colour swatches are not showing their colour. However, when I click on the swatches, the colours do change the icons. So everything works, it's just the colours dont show just now. 

image

**Comment by bjarnef** [comment]
@OwainWilliams any reason why you don't add a directive for this? :)

https://github.com/bjarnef/Umbraco-CMS/commits/temp-color-swatches-directive

**Comment by OwainWilliams** [comment]
Because the last time I did that I broke my PR 😊 once it's merged you're more than welcome to create your own PR and make it a directive.

**Comment by bjarnef** [comment]
I think it would be easier to work on the same PR to contribute, but I have submitted a new PR, which introduce an directive instead.

**Comment by nul800sebastiaan** [comment]
🎉 🏅 Merged! 

So I've taken the additional changes @bjarnef put in his PR to turn the swatches into a directive as well, without making the mess that this accidentally caused in the first place.

Thanks again @OwainWilliams for hanging in there. Love this new way of selecting colors, it's much much nicer than a drop down! 👍 💯 

Thanks very much @bjarnef for the help here as well! 

@OwainWilliams And.. of course you now have a shiny Contributor badge on Our! 💪 https://our.umbraco.com/member/144571

**Pull request merged**
