### PR TITLE
Added GetCount based on memberAlias

### PR DESCRIPTION
**Pull request by codingdefined**
### Description
We have a GetCount based on MemberCountType but not based on the memberAlias. Added a GetCount based on the memberAlias.
Issue https://github.com/umbraco/Umbraco-CMS/issues/2986

### CODE REVIEW

**Comment by codingdefined** [comment]
I am not sure if I have created a PR on the correct branch

**Comment by bjarnef** [comment]
@codingdefined I don't see the parameter `memberAlias` is being used in the code changes?

I noticed there wan't a `GetCount()` method, but just a `Count()` for member type: https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Core/Services/MemberService.cs#L721-L734

**Comment by codingdefined** [comment]
@bjarnef Thanks for noticing it, I thought Count based on memberAlias is not present. Bdw if you see memberAlias was defaulted to Constants.Conventions.MemberTypes.SystemDefaultProtectType, that's why used it. I should have directly use memberAlias. Though there are no count method for including both of them like MemberCountType and memberAlias, should I change this function to take both into account?

**Comment by bjarnef** [comment]
I think we could add this `GetCount()` which is a copy of the existing `Count()` and the existing `Count()` can be marked as deprecated/obsolete. And then the `GetCount()` method can have an overload which take both MemberCountType and memberAlias into account.

@nul800sebastiaan could this be a solution for this? Or is there a `Count()` method in other services?

**Comment by abjerner** [comment]
Sorry for going so long without a reply.

The other services seem to use either `Count` and `GetCount`, so it isn't consistent between the various services. But as the member service already has a `Count` method, I think we should stick with this name.

The existing method has the following signature:

```c#
int Count(string memberTypeAlias = null);
```

We can't really change this due to the `IMemberService` interface, but we can create a number of overloads - such as:

```C#
int Count(MemberCountType memberType);

int Count(MemberCountType memberType, string memberTypeAlias);
```
or just:
```C#
int Count(MemberCountType memberType, string memberTypeAlias = null);
```

As updating the `IMemberService` interface will be a breaking change, we can only make this change in the `MemberService` class (like you have already done).

@nul800sebastiaan do you have any pointers here? Ideally we should add the new methods as extension on `IMemberService`, but I'm not sure whether this is possible, as we need logic from inside `MemberService` to make the query.

**Comment by bjarnef** [comment]
@abjerner okay, maybe it could be made consistent for v8, but not sure if this change reach v8 release. Anyway the method should use the parameter `memberTypeAlias` instead of `SystemDefaultProtectType`.

**Comment by nul800sebastiaan** [comment]
Hey there @codingdefined!

I'm writing today after announcing at [Codegarden](https://codegarden19.com/), our yearly conference, that the upcoming version 7.15.0 will be the last Umbraco v7 release with new features in it. From now on all our efforts will be focused on version 8 instead. 🎱

We're wrapping up the 7.15 version at the moment and unfortunately these proposed changes won't be able to make it in there. 

We'd like to extend a big thank you the efforts on this so far and we would love it if you could have a look at porting this feature over to v8 instead. Of course if you have any questions on where to start then feel free to [ask on the forum](https://our.umbraco.com/forum/contributing-to-umbraco-cms/), we monitor all questions there and we're happy to assist.

Thanks again for the work in this PR and we hope to see you contributing to v8 some time soon!

Best, Sebastiaan and the Umbraco CMS team.

**Pull request closed without merging**
