### PR TITLE
Adjust grid editor layout configuration

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/9825

### Description
This PR fixes a few issues with configuration of layout/rows.

- Fixed wrong end-closing tag of `<button>` element which was `</a>` + added missing `type` attribute on button element.
- Registred functions on `vm` to be a bit more consistent with the rest of code base. I found a function `closeArea` in row configuration, which doesn't seem to be used, but I have leaved it for now.
- Previous the rows in layout configuration was using traditional checkboxes along with `checklist-model` and `checklist-value` which auto-populated the `allowed` array with row names. However since we are using `<umb-checkbox>` we need to bind the value to a model, but the row itself was not unique per section/column. I have extended the `sections` in the layout with a rows, which basically have a copy of the rows and a selected state. This is used to bind the value on the checkbox and/or if the button element next to it is clicked. On submit this property is deleted again, so we have to original JSON.
The might be a better way to handle this in future, but for now it seems to do the trick :)

**Layout configuration**

jzjtVAmXkf

**Row configuration**

YvozltVuL3

### CODE REVIEW

**Comment by nathanwoulfe** [comment]
Relates to #9410

**Comment by madsrasmussen** [comment]
Hi Bjarne, 

Thanks for the PR 🎉 

When testing it a found a couple of smaller things that I have fixed.

* When adding a new section in the layouts dialog we didn't copy the rows so there was nothing to select.
* When cleaning up rows in the submit function it looked in the wrong place.
* I have also made sure to clean up on close

You can see my commit here: 
https://github.com/umbraco/Umbraco-CMS/pull/9887/commits/ca4d43d28a8ce537a61eae35688a3fc0cc9cc494

Does this look ok to you and can I get you to do an extra test with the new fixes?

**Comment by bjarnef** [comment]
Hi Mads

Great, I have tested the PR with your changes, and it seems to work as expected. I minor thing is when checking all rows or editors and submit the overlay and re-open it again, it could probably have the "Allow all row configurations" or "Allow all editors" toggle enabled, but I think it has always worked this way.

The input fields could be closer the labels by removing the `form-horizontal` class, but it may cause issues with other overlays and something that can be looked at in another PR.

image

image

**Comment by madsrasmussen** [comment]
Thanks Bjarne for taking you time to do an extra test 🥇 

Yes, I agree that the overall design of the dialogs could use some more love. I can see that there is a PR from Nathan with some style clean-up. I will have to see if that also includes some UI love :)

I think this PR does what it should and I will get it merged!

**Comment by nathanwoulfe** [comment]
Most of my changes are polish and cleanup, not substantially changing anything. Still be good to merge, nothing wrong with a bit of polish ☺️

**Pull request merged**
