### PR TITLE
fixed rel attribute on links to content or media in the RTE

### PR DESCRIPTION
**Pull request by bowserm**

### CODE REVIEW

**Comment by Shazwazza** [comment]
If you can link this PR with an issue on the tracker we'll pull it in (http://issues.umbraco.org), thx!

**Comment by bowserm** [comment]
This is the issue that this pull request is related to: http://issues.umbraco.org/issue/U4-6582

**Comment by bowserm** [comment]
Also relevant is: http://issues.umbraco.org/issue/U4-5480

It would probably be good to read this before merging this pull request.

**Comment by Shazwazza** [comment]
So this PR changes the rel attribute to be an Id... the issue mentions that there was nothing put into this rel attribute but the code was trying to put data.rel. Any chance you know if data.rel is always null?

If the rel attribute never actually showed up in the link, then this PR should be updated to use a data- attribute (perhaps data-id) or something.

**Pull request closed without merging**
