### PR TITLE
U4-10999 Fixed wrong description on mediaresource.search

### PR DESCRIPTION
**Pull request by Migaroez**

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Whoops, targetting a different branch didn't work as I though it would. Anyway, when this is merged, we should cherry pick it to 7.7 as well.

**Comment by nul800sebastiaan** [comment]
Thanks @Migaroez ! I've also applied this change to 7.7, much better now! 

Do you have an account on Our Umbraco? If you send me a link to your profile I'd love to add a badge to thank you for the contribution!

**Comment by Migaroez** [comment]
@nul800sebastiaan  sven@comm-it.be

**Comment by nul800sebastiaan** [comment]
Oh! Hi Sven!

Well you are now unmasked ;-)

Also, cool looking badge! https://our.umbraco.org/member/153763

**Pull request merged**
