### PR TITLE
V8 - Convert to .NET SDK CSProj files

### LINKED ISSUE #5264: Migrate Umbraco.Core and Umbraco.Web to SDK projects
MSBuild 15 (shipped in VS 2017) introduced a new MSBuild project file structure called 'sdk projects': https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-use-project-sdk?view=vs-2019

These are often thought of as part of [.NET Core](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj) but it can be used for .NET full framework projects (such as Umbraco).

In v8 it already starts to use it through the `<PackageReference` of NuGet over an external file, but generally speaking they are still the old style project files.

I'd like to propose the migration of Umbraco across to the new project system for a few reasons:

1. Helps modernise Umbraco as it slowly progresses towards a netstandard codebase
2. Simplifies the build process by using the `dotnet` cli for compilation rather than `msbuild`
3. Reduce potential merge conflict points as `*.cs` files are not required to be in the project file, only embeded resources and other 'special' includes
4. Easily integrate [SourceLink](https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink) to improve debugging of Umbraco

I've taken this approach with [Chauffeur for v8](https://github.com/aaronpowell/Chauffeur/tree/umbraco-v8) and it works seemlessly, I can even use vscode as my editor since the build engine is the .NET cli rather than msbuild.

It wouldn't be possible for the web project where you need to launch IIS express, but I think all other projects would be fine.

### PR DESCRIPTION
**Pull request by warrenbuckley**
This is a draft/WIP PR for attempting to get the SLN & projects to use .NET SDK type. Fixes #5264 

## Why?
* Easier to maintain & add things we explicitly need to do
* All files are included
* Nuget package references are here too
* Developer Experience - Debugging into our source code with SourceLink (Seems to require newer SDK csproj to work)

### CODE REVIEW

**Comment by warrenbuckley** [comment]
# Do not merge this in ⚠️ 
This needs discussion & extensive testing

## Notes
- I have upgraded the three class libraries CSProj's to the newer/slimmer .NET SDK CSProj type
   - Umbraco.Core
   - Umbraco.Examine
   - Umbraco.Web

**Comment by warrenbuckley** [comment]
## Preliminary Tests

- [x] Opens in VS2017 & SLN Builds
- [x] F5/Debug Umbraco.Web.UI & installer UI loads from VS2017
- [x] Powershell `.\build.ps1` is happy & builds
- [x] Opens in VS2019 & SLN Builds
- [x] F5/Debug Umbraco.Web.UI & installer UI loads from VS2019
- [ ] Test ZIP build output (Todo)
- [ ] Test NuPkg & SnuPkg output (Todo)

As this super new teritoary, I am still dubious that I may have missed something or done something wrong. Paging @zpqrtbnk & @Shazwazza for some extra eyes 👀 on this.

**Comment by warrenbuckley** [comment]
OK after doing the preliminary tests above, I suggest the reviewer do the same & triple check everything looks OK in VS2019 & VS2017 as we expect.

Also, the above comment with questions/notes would need to be answered too
https://github.com/umbraco/Umbraco-CMS/pull/5341#issuecomment-486274427

**Comment by abjerner** [comment]
@warrenbuckley great to see some progress on this 👍

I'm not sure whether this is your intent or not, but some (if not all) of the information in the `SolutionInfo` files can be moved to the `.csproj` file as well.

https://github.com/skybrud/Skybrud.Essentials/blob/master/src/Skybrud.Essentials/Skybrud.Essentials.csproj#L23,L28

There is a good example here as well:

https://stackoverflow.com/a/42143079

I haven't found out how you are generating the NuGet packages, but these can be build directly based on the `.csproj` file without the use of a `.nuspec` file.

**Comment by warrenbuckley** [comment]
@abjerner Yes I could move them into CSProj but I believe our build piepline (Powershell & Azure DevOps) modifies that `SolutionInfo.cs` file to update the version number etc.

Again I am not sure we want to change too much all at once - with changing the build process/pipeline by moving the Nuget properties into CSProj & get Nuget to generate from CSProj as opposed to NuSepcs. Again I think we do some magic by updating them first in the pipeline. That's one for @zpqrtbnk to help answer that.

**Comment by warrenbuckley** [comment]
Closing this PR for now, as this is quite big changes at the moment and found out that newer SDK style project is not needed to enable Sourcelink, yay 😄

**Pull request closed without merging**
