### PR TITLE
U4 9379 - add confirmation step to unpublish action

### PR DESCRIPTION
**Pull request by nathanwoulfe**
### Prerequisites

- I have written a descriptive pull-request title
- I have linked this PR to an issue on the tracker at http://issues.umbraco.org

### Description
[Discussion on the tracker](http://issues.umbraco.org/issue/U4-9379) was around changing the keyboard shortcut and/or adding a confirmation dialog for unpublish actions, particularly as the CTRL+U shortcut is the default for show source.

I've left the shortcut in place, as (IMO) while unpublish isn't a common action, keeping it ensures a complete set of publishing actions are available from the keyboard. Further, adding a confirmation step removes the risk of accidentally unpublishing an entire 35k node site with a couple of keystrokes...

My changes add a new notification in the same style as the route change warning, which warns that unpublishing the current page will remove it and all descendants from the site. I was going to add this in the valformmanager directive alongside the routechange code, but ended up keeping it all in the edit controller, mainly because the controller should remain responsible for unpublishing the page. It also allows the event subscription to be created just-in-time, when the unpublish button is clicked, rather than when the view loads.

Also included a bit of CSS to ensure the notifications aren't obscured by the left nav on small screens.

Notification works like this:

- user clicks unpublish
- notifications service displays the warning notification, listener subscribes to content.confirmUnpublish
- user clicks either unpublish or cancel in the notification
- the notification controller raises an event
- listener in edit.controller responds to the event data -> a bool representing the action taken (true = unpublish, false = cancel)
- if true, the unpublish proceeds as normal
- if false, just reset the button state
- finally, unsubscribe the confirmUnpublish listener

Unsubscribing inside the listener callback means a user can repeatedly publish and unpublish a page (if they really wanted to) without having to refresh the backoffice to resubscribe to the confirmUnpublish event - subscription happens inside the $scope.unpublish function, so it's always ready when we need it. Also means it's not created by default.

Otherwise, each unpublish request creates a new listener, and raises multiple events, and displays multiple confirmation notifications.

Should look something like this:
unpublish-notification

### CODE REVIEW

**Comment by dawoe** [comment]
Hi Nathan,

Thx for the PR. Will try to test this somewhere in the coming 2 weeks. I'm pretty sure this will break my nexu package. But that's something I need to fix in there.

Dave

**Comment by nathanwoulfe** [comment]
Thanks Dave. Hopefully doesn't break Nexu - my changes basically sit ahead of the normal unpublish, so from a quick look at Nexu, your interceptor should still catch the unpublish API request and do it's magic... Hope I haven't created any work for you!

**Comment by dawoe** [comment]
Probably means when nexu is installed the user can get 2 confirmations...but that's something I need and probably can fix.

**Comment by nul800sebastiaan** [comment]
Fantastic job @nathanwoulfe ! I am sure this will make a lot of people very happy! 🎉 🎉 

That beautiful contrib badge is more than deserved!  👍

**Comment by nul800sebastiaan** [comment]
Whoops, forgot to link to profile with that shiny badge : https://our.umbraco.com/member/40806

**Pull request merged**
