### PR TITLE
Fix ViewContext.FormContext not being set during BeginUmbracoForm

### LINKED ISSUE #13913: Client validation breaks when using multiple forms with the same field names on the same page
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

10.4.0

### Bug summary

When you have two forms using `Html.BeginUmbracoForm` to instantiate the form on the same page the client validation fields (`data-val` etc) do not get set on the second form.

Inspecting the source code and the ASP.NET Core code it looks like `Html.BeginUmbracoForm` is not setting `ViewContext.FormContext` like `Html.BeginForm` does.

Workaround:
Add `@{ ViewContext.FormContext = new FormContext { CanRenderAtEndOfForm = true }; }` before your call to `Html.BeginUmbracoForm`

### Specifics

Commenting out the first form lets the second form work correctly.

### Steps to reproduce

Create a page with two forms with different form models on it (in my case the forms were in partials).
Each form should use `Html.BeginUmbracoForm` to generate the form tags
Set up the form models to have a field with the same name and validation eg `[Required] public string Name { get; set; }`
Render the page
The second form will be missing client validation attributes on the form element

### Expected result / actual result

Multiple forms should work fine on the same page

### PR DESCRIPTION
**Pull request by kiasyn**
Client validation is broken without this if there are multiple forms with the same field names on a page.

### Prerequisites

Fixes #13913

### Description

Fixes ViewContext.FormContext not being set by Html.BeginUmbracoForm which is normally set in Html.BeginForm

### CODE REVIEW

**Comment by lauraneto** [comment]
Hi @kiasyn ,

Thank you for your contribution!
Unfortunately I am having some issues reproducing the initial issue.
Could you share more details and/or code snippets that I can use to reproduce it?
Thanks!

**Comment by lauraneto** [comment]
Hi again @kiasyn ,

Thought I could add some more details about what I tried so it's easier for you to tell me what you did differently. 🙂
1. Checked out the latest `contrib` branch commit to make sure I have the latest changes/fixes.
2. Followed the Umbraco documentation about creating forms, which can be found [here](https://docs.umbraco.com/umbraco-cms/fundamentals/code/creating-forms).
Basically created a surface controller with two different actions, two form models and two partials.
So something like this:

ContactFormController.cs:
```
public class ContactFormController : SurfaceController
{
    ...

    [HttpPost]
    public IActionResult Submit(ContactFormViewModel model)
    {
        ...
    }

    [HttpPost]
    public IActionResult Submit2(ContactFormViewModel2 model)
    {
        ...
    }
}

public class ContactFormViewModel
{
    [Required]
    public string Name { get; set; }
    [EmailAddress]
    public string Email { get; set; }
    [Required]
    public string Message { get; set; }
}

public class ContactFormViewModel2
{
    [Required]
    public string Banana { get; set; }
    [EmailAddress]
    public string Email { get; set; }
    [Required]
    public string Apple { get; set; }
}
```
ContactForm.cshtml
```
...
@using (Html.BeginUmbracoForm(nameof(ContactFormController.Submit), "ContactForm"))
{
    <div class="input-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Email"></label>
        <input asp-for="Email" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Message"></label>
        <textarea asp-for="Message"></textarea>
        <span asp-validation-for="Message" class="text-danger"></span>
    </div>
    <br />
    <input type="submit" name="Submit" value="Submit" />
}
```

ContactForm2.cshtml
```
...
@using (Html.BeginUmbracoForm(nameof(ContactFormController.Submit2), "ContactForm"))
{
    <div class="input-group">
        <label asp-for="Banana"></label>
        <input asp-for="Banana" />
        <span asp-validation-for="Banana" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Email"></label>
        <input asp-for="Email" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Apple"></label>
        <textarea asp-for="Apple"></textarea>
        <span asp-validation-for="Apple" class="text-danger"></span>
    </div>
    <br />
    <input type="submit" name="Submit" value="Submit" />
}
```

4. Added a simple doc type with template just so I could add the forms and test.
Home.cshtml
```
...
<h2>Form 1</h2>
<partial name="Partials/ContactForm" model="@(new ContactFormViewModel())" />

<h2>Form 2</h2>
<partial name="Partials/ContactForm2" model="@(new ContactFormViewModel2())" />

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.js"></script>
```

5. Tried out the client validation and both Email fields were working as expected, with validation in place and also not colliding in any way.

Is there anything that I am missing or that you used/configured differently?

**Comment by kiasyn** [comment]
hi @lauraneto, thanks for looking into this one.

I just set up the same test case you used in my own contrib environment and I can still see the issue occuring.

If you do a view source of the generated HTML you can see the difference:

Contact form 1:

```html
    ...
    <label for="Email">Email</label>
    <input type="email" data-val="true" data-val-email="The Email field is not a valid e-mail address." id="Email" name="Email" value="" />
    <span class="text-danger field-validation-valid" data-valmsg-for="Email" data-valmsg-replace="true"></span>
    ...
```

Contact form 2:

```html
    ...
    <label for="Email">Email</label>
    <input type="email" id="Email" name="Email" value="" />
    <span class="text-danger field-validation-valid" data-valmsg-for="Email" data-valmsg-replace="true"></span>
    ...
```

See the data-val attributes not getting added to the second input?

It does appear to render to still validate that the Email field in ContactForm2 is valid, but if you add a [Required] attribute to the Email property it won't give you a 'The Email field is required.' error message like it does on ContactForm1

Then if you add a `@{ Html.ViewContext.FormContext = new FormContext { CanRenderAtEndOfForm = true }; }` before each of your `Html.BeginUmbracoForm` you can see the generated HTML changes and the 'The Email field is required' error message starts working.

Hope this is enough information to reproduce!

**Comment by lauraneto** [comment]
Hi @kiasyn ,

Thank you for the explanation, it was very helpful! I tested it again and was able to confirm what you mentioned.
I have merged the pull request so this should be fixed in the next release `11.3.0`.

Thanks again! 🙂

**Comment by nul800sebastiaan** [comment]
Cherry picked for 10.5 in e9d17d3b9f8b1d7654cc8d3cb3cb1d9ad7dfdaaa

**Pull request merged**
