### PR TITLE
Renames the true false field to be more descriptive

### PR DESCRIPTION
**Pull request by Attackmonkey**
Also includes Migration to rename existing data type. That will need to be assigned to a proper version.

This PR is for U4-10334

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
@Attackmonkey 
Thanks! I see you've included a migration, but the file isn't committed. 
Could you update this and target it for version 7.8 please? That's the first version where we can make new database changes. 

And as for naming, I would just name it `Checkbox` - we never use `Single` anywhere else, we usually just have the default type and then when necessary suffix `List` or `Multiple`.

**Comment by Attackmonkey** [comment]
D'oh, sure, will sort those changes out tonight and re-submit.

**Comment by Attackmonkey** [comment]
OK, those changes are in :)

**Comment by nul800sebastiaan** [comment]
Hi @Attackmonkey ! Sorry for the ... slight .. delay 🙈 

I still enjoy this change, makes sense! If you could retarget it for 7.12.0 then we can pull it in soon, would be awesome!

Thanks!

**Comment by Attackmonkey** [comment]
Sure! I'll have a look at this as soon as I can! Might be after the weekend, but will try and get it sorted ASAP :)

**Comment by nul800sebastiaan** [comment]
Just thinking now, should we call it `Toggle` instead now that it.. looks like a toggle? 😀 

image

**Comment by nul800sebastiaan** [comment]
I've decided against that, Checkbox makes more sense, no matter what it later looks like in the UI.

Thanks for your patience @Attackmonkey and thanks for the contribution! :+1:

**Pull request merged**
