### PR TITLE
Added IBackOfficeUserManager instead of BackOfficeUserManager

### PR DESCRIPTION
**Pull request by LennardF1989**
This PR fixes an (I assume oversight) in the code of the BackOfficeSignInManager, that will make it possible to override the instance of the IBackOfficeUserManager.

Right now, the only workaround is to make your own BackOfficeSignInManager, to be able to inject an instance of IBackOfficeUserManager and then do this:
```
            builder.Services.Replace(new ServiceDescriptor(
                typeof(IBackOfficeSignInManager),
                typeof(MyBackOfficeSignInManager),
                ServiceLifetime.Scoped
            ));

            builder.Services.Replace(new ServiceDescriptor(
                typeof(IBackOfficeUserManager),
                typeof(MyBackOfficeUserManager),
                ServiceLifetime.Scoped
            ));
```

Do keep in mind that your custom IBackOfficeUserManager still has to extend the original BackOfficeUserManager, because it's tightly coupled in the code. But at least it's now possible to actually override virtuals.

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks @LennardF1989! We'll have a look soon! 👍

**Comment by nul800sebastiaan** [comment]
Hey again @LennardF1989 - Unfortunately as the build failure indicates this is a breaking change, changing the signature of a public method causes a binary breaking change. 

Usually we'd work around it by duplicating the public method (or constructor) and obsoleting the old one. I have fixed this locally but it looks you're not allowing me to push to your branch, so if you could fix it up then the tests can run and I can tap the merge button when all is well:


```
    public BackOfficeSignInManager(
        IBackOfficeUserManager userManager,
        IHttpContextAccessor contextAccessor,
        IBackOfficeExternalLoginProviders externalLogins,
        IUserClaimsPrincipalFactory<BackOfficeIdentityUser> claimsFactory,
        IOptions<IdentityOptions> optionsAccessor,
        IOptions<GlobalSettings> globalSettings,
        ILogger<SignInManager<BackOfficeIdentityUser>> logger,
        IAuthenticationSchemeProvider schemes,
        IUserConfirmation<BackOfficeIdentityUser> confirmation,
        IEventAggregator eventAggregator)
        : base((BackOfficeUserManager)userManager, contextAccessor, claimsFactory, optionsAccessor, logger, schemes, confirmation)
    {
        _userManager = (BackOfficeUserManager)userManager;
        _externalLogins = externalLogins;
        _eventAggregator = eventAggregator;
        _globalSettings = globalSettings.Value;
    }

    [Obsolete("Use ctor which takes IBackOfficeUserManager - this one will be removed in v14")]
    public BackOfficeSignInManager(
        BackOfficeUserManager userManager,
        IHttpContextAccessor contextAccessor,
        IBackOfficeExternalLoginProviders externalLogins,
        IUserClaimsPrincipalFactory<BackOfficeIdentityUser> claimsFactory,
        IOptions<IdentityOptions> optionsAccessor,
        IOptions<GlobalSettings> globalSettings,
        ILogger<SignInManager<BackOfficeIdentityUser>> logger,
        IAuthenticationSchemeProvider schemes,
        IUserConfirmation<BackOfficeIdentityUser> confirmation,
        IEventAggregator eventAggregator)
        : base(userManager, contextAccessor, claimsFactory, optionsAccessor, logger, schemes, confirmation)
    {
        _userManager = userManager;
        _externalLogins = externalLogins;
        _eventAggregator = eventAggregator;
        _globalSettings = globalSettings.Value;
    }
```

Thanks!

**Comment by LennardF1989** [comment]
I allowed pushing @nul800sebastiaan! But if I get to it earlier, I'll merge your fix :)

**Comment by nul800sebastiaan** [comment]
Ah I just realized in your opening post you're only trying to replace the interface `IBackOfficeSignInManager` - but how about inheriting from the concrete `BackOfficeUserManager` as Ronald notes and using that one instead?

**Comment by nul800sebastiaan** [comment]
> If the following works (not tried yet):

Yes! I got that one to work. 👍 
And @ronaldbarendse also pointed out to me you could use `AddUserManager` / `AddSignInManager` extension methods to make replacement of `BackOfficeUserManager` easier. It depends a bit on what you're trying to achieve. https://github.com/umbraco/Umbraco-CMS/blob/contrib/src/Umbraco.Web.BackOffice/DependencyInjection/UmbracoBuilder.BackOfficeIdentity.cs#L47C20-L48

> The question then becomes, what's the point of the abstraction to an interface? It all feels really tightly coupled as it is and it doesn't add anything :P

Maybe.. not sure, but it looks like they were introduced for our unit tests - https://github.com/umbraco/Umbraco-CMS/pull/8913. There's also a note there that both the interface and the concrete needed to be registered side-by-side in the DI. 

> That said, why not keep the original constructor, tag it as obsolete, then add a third for the interface? I'll run the tests myself tonight and see if I can come up with a fix. Otherwise we can just assume this PR to be void :)

That's what I've done and as you can see (https://github.com/umbraco/Umbraco-CMS/pull/14246/checks?check_run_id=13653343218) it will fail the tests as the constructors become ambiguous. 

```
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Umbraco.Cms.Web.Common.Hosting.UmbracoHostBuilderDecorator.Build() in /_/src/Umbraco.Web.Common/Hosting/UmbracoHostBuilderDecorator.cs:line 67
   at Umbraco.Cms.Tests.Integration.TestServerTest.UmbracoWebApplicationFactory`1.CreateHost(IHostBuilder builder) in /_/tests/Umbraco.Tests.Integration/TestServerTest/UmbracoWebApplicationFactory.cs:line 26
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.DelegatedWebApplicationFactory.CreateHost(IHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
   at Umbraco.Cms.Tests.Integration.TestServerTest.UmbracoTestServerTestBase.Setup() in /_/tests/Umbraco.Tests.Integration/TestServerTest/UmbracoTestServerTestBase.cs:line 84
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
--InvalidOperationException
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
--InvalidOperationException
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
--InvalidOperationException
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
--InvalidOperationException
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
--InvalidOperationException
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(ICollection`1 serviceDescriptors, ServiceProviderOptions options)
--InvalidOperationException
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCall
```

With that said, I will close the PR for now as replacing the concrete class works and making this change backwards compatible is not a trivial task unfortunately. It seems like a refactor in the future might be in order but I can also see that it will be a big refactor, so I'm not sure where that would fit in.

Thanks again for the PR!

**Pull request closed without merging**
