### PR TITLE
Templates can still be editable when using runtime mode Production bug fixed  #16622

### LINKED ISSUE #16622: Templates can still be editable when using runtime mode Production
### Which Umbraco version are you using? (Please write the *exact* version, example: 10.1.0)

14.0.0

### Bug summary

Templates in the BackOffice can still be editable when using runtime mode Production

### Specifics

The template in BackOffice (live env) can still be editable when using runtime mode Production
image
Templates are not supposed to be editable on live env as runtime compilation is not enabled and is set to Production.

### Steps to reproduce

Configuring the runtime mode: Production
Follow these steps from https://docs.umbraco.com/umbraco-cms/fundamentals/setup/server-setup/runtime-modes.
1. Config runtime mode to enable Development mode
2. Remove 2 properties from csproj project file: RazorCompileOnBuild and RazorCompileOnPublish
3. Enable Production mode in appsettings.Production.json
4. Open one template file in BackOffice (Live Environment), templates can still be editable 

### Expected result / actual result

Templates cannot be edited on live environment as runtime compilation is not enabled and is set to Production.
image

### PR DESCRIPTION
**Pull request by nick-hoang**
### Prerequisites

- [] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes (https://github.com/umbraco/Umbraco-CMS/issues/16622)

### Description
image

### CODE REVIEW

**Comment by emmagarland** [comment]
Hi @nick-hoang, 

Thanks for your PR to fix #16622, where templates can still be editable when using the Production runtime mode.

It looks like this is your first PR to this repository! Nice work! #H5YR 🎉

I've noticed this has changed thousands of files and I'm wondering if something might have gone awry with the merge? Let us know if you need any help getting this PR ship-shape. 

Best wishes

Emma

**Comment by nick-hoang** [comment]
hi @emmagarland 

I've just changed the file src/Umbraco.Web.UI.Client/src/views/templates/edit.html, you can see my last commit here: https://github.com/umbraco/Umbraco-CMS/pull/16923/commits/60eb16f27b1728797d2bf68c77b286933f6c4c05

Other commits are from me, I have no idea why they are included in my PR, these commits came when I pulled and merged new commits from the v13/contrib branch into my fork repo.

Hope it help.
Cheers

**Comment by emmagarland** [comment]
Thanks @nick-hoang 

I think that is because this pull request is targetting v14 ('contrib' branch), whereas 'v13/contrib' is the branch to target for v13. Which Umbraco version are you trying to work with?

Best wishes

Emma

**Comment by JasonElkin** [comment]
The rogue commit was reversible, so I've reverted it. I've retargeted to v13, which is where this was forked from and more importantly where the file being modified still exists.

**Comment by emmagarland** [comment]
> The rogue commit was reversible, so I've reverted it. I've retargeted to v13, which is where this was forked from and more importantly where the file being modified still exists.

Nice one @JasonElkin - I'll see if I can take a look later

**Comment by JasonElkin** [comment]
Hey @nick-hoang, thanks for fixing this!

And congratulations on having your first PR merged to Umbraco 🙌🎉

I see you have a profile on https://our.umbraco.com/, I'll get you assigned one of those shiny contributor badges.

Thanks again,
Jas

**Pull request merged**
