### PR TITLE
Updated border radius of notification to match button

### PR DESCRIPTION
**Pull request by arulprabakaran**
**Description**

This PR changes the border radius of umb-notifications component in backoffice to match the border radius of buttons.

**Before**

image

**After**

image

### CODE REVIEW

**Review by nathanwoulfe — APPROVED** [review]
Hey @arulprabakaran, firstly apologies for the delay in reviewing this one - it's a small but worthwhile change. Secondly, congrats on your first Umbraco contribution. If you can let us know your profile on our.umbraco, @nul800sebastiaan can add the ultra-exclusive contributor badge.

**Comment by nathanwoulfe** [comment]
Test failure won't be related to these changes.

**Comment by arulprabakaran** [comment]
> Hey @arulprabakaran, firstly apologies for the delay in reviewing this one - it's a small but worthwhile change. Secondly, congrats on your first Umbraco contribution. If you can let us know your profile on our.umbraco, @nul800sebastiaan can add the ultra-exclusive contributor badge.

Hi @nathanwoulfe, thanks for the merge. `arulprabakaran` is my profile name in our.umbraco.com.

**Comment by nul800sebastiaan** [comment]
Excellent, congrats on your shiny new contributor badge @arulprabakaran!🎖️  https://our.umbraco.com/members/arulprabakaran

**Pull request merged**
