### PR TITLE
V8/doctype tours

### PR DESCRIPTION
**Pull request by dawoe**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

### Description

This is a port of PR #2635 to V8. It makes it possible to have doctype specific tours. 

When creating tour there is a new property in the tour json called contentType. You can set this with a comma seperated string of doctypes that the tour should be visible on. It also supports setting of aliases of composition doctypes. If you use a composition doctype alias the tour will be visible on all doctypes implementing the composition

Here you can see a small demonstration

doctype-tours

You unzip
[this file](https://github.com/umbraco/Umbraco-CMS/files/3789883/doctype-v2.zip)
 in /Config/BackOfficeTours folder when you have the starter kit installed to test it

Dave

### CODE REVIEW

**Comment by poornimanayar** [comment]
Thanks @dawoe , you know the drill!

**Comment by nul800sebastiaan** [comment]
@kjac This sure looks like a lovely feature! I can see Mads had some concerns in the original PR but if they're resolved then this would be awesome to have! 👍

**Comment by dawoe** [comment]
Hi @nul800sebastiaan and @kjac 
I think all the concerns of Mads were resolved in the original PR already. Maybe @nielslyngsoe can give an opinion ?

I also merged the latest dev branch to fix the merge conflicts.

Dave

**Comment by nielslyngsoe** [comment]
@dawoe judging from the GIF, it looks good! As far as I understand Mads' concerns are solved. From a UI/UX perspective, this is good! 👏

**Comment by kjac** [comment]
Merged 👍 

@dawoe do you fancy updating the docs as well at https://our.umbraco.com/documentation/extending/Backoffice-Tours/ ?

**Comment by dawoe** [comment]
Hi @kjac 

Will update the docs soon.

Dave

**Pull request merged**
