### PR TITLE
Fixes #6467 - Removing code references to MacroContainer

### LINKED ISSUE #6467: Remove the leftover code from the legacy MacoContainer datatype
As discovered through PR https://github.com/umbraco/Umbraco-CMS/pull/6350 - we didn't intend to ship with code for the MacroContainer datatype.

The old code supporting this datatype needs to be removed, it quite broken at the moment anyway. 

We'd love some help with this.

### PR DESCRIPTION
**Pull request by Kerl1310**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes #6467 

### Description
Removed the code referencing MacroContainer from the project

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Uh oh! I did remove the "up for grabs" from this one, but I guess I forgot to add a link to the existing PR. Maybe you can compare yours with the existing one and see if the existing one is missing anything? 

https://github.com/umbraco/Umbraco-CMS/pull/6518

**Comment by nul800sebastiaan** [comment]
You've both changed 32 files, so that's nice and consistent! 😁

**Comment by Kerl1310** [comment]
Ah, sorry, didn't notice the removed labels!

**Comment by nul800sebastiaan** [comment]
Thanks again @Kerl1310 - I compared the work in the existing PR to this one and you both did the exact same things. Sorry that someone beat you to it! Hope to see more of your work soon though! 👍

**Pull request closed without merging**
