### PR TITLE
Fixes umbracoRedirect property to work with UDI IDs

### PR DESCRIPTION
**Pull request by jamescoxhead**
Fixes [U4-9897](http://issues.umbraco.org/issue/U4-9897).

Includes backwards-compatability support for integer-based IDs.

### CODE REVIEW

**Comment by Jeavon** [comment]
@jamescoxhead does this cover umbracoInternalRedirectId as well as umbracoRedirect?

**Comment by jamescoxhead** [comment]
No just umbracoRedirect. If I get time today/this weekend I'll patch umbracoRedirectId.

**Comment by jamescoxhead** [comment]
@Jeavon I've created a separate PR for umbracoInternalRedirectID, see #1942

**Comment by Jeavon** [comment]
Fab @jamescoxhead 

I think for v7.7 we should consider converting the special alias pickers and having the PublishedContentRequestEngine support IPublishedConent as it's kinda strange that these two aliases are treated specially. /cc @Shazwazza @zpqrtbnk

**Comment by nul800sebastiaan** [comment]
Thanks again! Closing this as this one was covered in the additional changes I made to https://github.com/umbraco/Umbraco-CMS/pull/1942

**Pull request closed without merging**
