### PR TITLE
v8: Add umbLoader directive

### PR DESCRIPTION
**Pull request by bjarnef**
### Prerequisites

- [x] I have added steps to test this contribution in the description below

If there's an existing issue for this PR then this fixes https://github.com/umbraco/Umbraco-CMS/issues/4958

### Description
This PR replaces a few places where `.umb-loader` is used with this `<umb-loader>` directive.

The `umb-loader` added in embed preview here https://github.com/umbraco/Umbraco-CMS/blob/91c52cffc8b7c70dc956f6c6610460be2d1adc51/src/Umbraco.Web.UI.Client/src/views/common/infiniteeditors/embed/embed.controller.js#L40 is replaced by `<umb-load-indicator>` directive is this PR https://github.com/umbraco/Umbraco-CMS/pull/4899

### CODE REVIEW

**Comment by poornimanayar** [comment]
Hi @bjarnef ,

Many thanks for your PR. You know what happens next :-)

Poornima

**Comment by nul800sebastiaan** [comment]
Hey @bjarnef - since I just learned about components recently: shouldn't we turn everything new into a component instead of a directive?

**Comment by bjarnef** [comment]
Could be, but it is more or less a copy of the existing `umb-load-indicator` with different markup and an additional a property for `position`. I guess there are several other directives, which should be a component then?

**Comment by bjarnef** [comment]
For some reason the `umb-load-indicator` also have `½` character in its code.

**Comment by bjarnef** [comment]
I guess it a only the recently added directives which are angular components.
https://github.com/umbraco/Umbraco-CMS/blob/91c52cffc8b7c70dc956f6c6610460be2d1adc51/src/Umbraco.Web.UI.Client/src/common/directives/components/content/umbvariantstate.directive.js

Most of them seems to be diretives.

**Comment by nul800sebastiaan** [comment]
Think it's fine for now, new stuff should just be components really, that seems to be the consensus at least.

**Comment by bjarnef** [comment]
It seems it should be quite easy to change these two loading directives to components.

**Comment by bjarnef** [comment]
It doesn't seem components in Angular 1.5 is a replacement for the older directive and components shouldn't be used for DOM manipulation.

https://stackoverflow.com/a/34982610

**Comment by bjarnef** [comment]
I think it would be okay to add this as an directive since the other loading indicator is a directive. A component is just a special directive a Angular 1.5 and it can always be changed to a component later.

**Comment by bjarnef** [comment]
@nul800sebastiaan anything we need to change on this except fixing the merge conflicts now? I would like the keep the new `umbLoader` as a directive just like the other `umbLoadIndicator` is. Angular components doesn't seem to be a replacement for directives and it seems components shouldn't be used for DOM manipulations. If there are specific reasons we should change this to components, I think it should be changed for both `umbLoader` and `umbLoadIndicator`.

**Comment by nul800sebastiaan** [comment]
All good @bjarnef - I'll see if I can find someone to test it all. I don't see any merge conflicts at the moment?

**Comment by bjarnef** [comment]
Thanks.. no, it was just the checks / build which failed.
https://umbraco.visualstudio.com/Umbraco%20Cms/_build/results?buildId=19487

image

**Comment by poornimanayar** [comment]
I am assuming that we are looking for the animated blue line here. In that case I have tested the following and found okay(over slow 3G Network Preset). I cant see any console errors either.

1. Copying content in a listview
2. Moving content in a listview
3. Copy content in tree
4. Move content in tree
4. Empty recycle bin in content tree
5. Moving doc types
6. Copying doc types

I could not test moving datatypes as I have to create a folder for that to test it well and I cannot create any folders. And this applies to creating new folders in doc types as well. Can someone just test that part?

**Comment by bjarnef** [comment]
@poornimanayar one more place where it is used is when init the tour (white bar in top).

**Comment by bjarnef** [comment]
@nul800sebastiaan have you had any chance to test this?

**Comment by bjarnef** [comment]
@nul800sebastiaan can we merge this to v8.2.0?

**Comment by nul800sebastiaan** [comment]
Thanks for the reminder @bjarnef ! Yep, this is great, ready for 8.2.0!

**Pull request merged**
