### PR TITLE
Fix dictionary key access

### PR DESCRIPTION
**Pull request by xumix**
Looks like someone does not know how to use a dictionary, this fix improves performance 10x for big dictionaries

### CODE REVIEW

**Comment by Shazwazza** [comment]
thx. Yup that is pretty ugly. This legacy code will be deleted entirely in v8 and is obsoleted in 7.3

**Comment by xumix** [comment]
Any chance to integrate this into 6.2.x branch? We are deeply invested in it and can't upgrade to 7.x any time soon.

**Comment by Shazwazza** [comment]
sure will do that now

**Comment by Shazwazza** [comment]
done in rev: d2662c17f781329969e16ba5919d044f7a520095 and will be available in 6.2.5

**Comment by xumix** [comment]
Thanks a lot!

**Pull request merged**
