### PR TITLE
Update ru.xml UI resources

### PR DESCRIPTION
**Pull request by abryukhov**
Couple of translation corrections

### CODE REVIEW

**Comment by abryukhov** [comment]
One additional question: since i made corrections in the default 'dev-v7' branch, should i explicitly make the same changes into the 'dev-v7.6' branch too, or they will be merged automatically?

**Comment by mikkelhm** [comment]
Hi @abryukhov
Thanks for the PR really appreciate it.

No need to do the changes in the dev-7.6 branch it is no longer used and will be closed shortly. Latest is in dev-v7 so everything should be perfect for this PR

**Comment by abryukhov** [comment]
Ok, thank you @mikkelhm

**Comment by mikkelhm** [comment]
@abryukhov I merged this one. Thank you for the contribution.

To keep track of the PRs and our release notes, we also need an issue on our.issues.org. I've done this for this PR, it is here: http://issues.umbraco.org/issue/U4-10031.

**Comment by abryukhov** [comment]
Thank you very much, will make it too for the future PRs :-)

**Pull request merged**
